### ISSUE TITLE
Survey fields get cleared when updating value on a custom widget made with PlacesAutocomplete

### ISSUE THREAD

**Issue by ajien** [surveyjs/surveyjs#1003]
### Are you requesting a feature, reporting a bug or ask a question?

Question

I was able to implement a custom widget using a React component for Google Maps Places Autocomplete. My problem is that once suggestions appear and the field state changes, the contents of all the other survey fields get cleared. Is there a way to prevent it?

[Here's what I did](https://stackblitz.com/edit/surveyjs-react-custom-component-widget) to integrate [React Places Autocomplete](https://www.npmjs.com/package/react-places-autocomplete) into the survey as a custom widget.

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version:

**Comment by andrewtelnov** [comment]
@ajien For some reason on making a request to get AutoComplete, the whole app is recreating together with Survey and all data and state is lost.

Thank you,
Andrew

**Comment by ajien** [comment]
I am able to fix this issue by wrapping the PlacesAutocomplete component with another component, which I then used as the custom widget for SurveyJS. Apparently, the problem was that I was calling setState when the autocomplete field gets updated (onChange), which affected the rest of the form as the entire component re-renders. By wrapping the autocomplete component with another component, the re-render happens only within the wrapper component, and does not affect the rest of the form.
