### ISSUE TITLE
Bug - Multi page survey does not work

### ISSUE THREAD

**Issue by yidan** [surveyjs/surveyjs#1004]
### Are you requesting a feature, reporting a bug or ask a question?
reporting a bug

### What is the current behavior?
When I implemented a multi page survey, each page has one question and auto-advance is turned on,  the page indicator moves to the next page as expected, but the question is always the question on the first page. 

And an error shows up:

Cannot find template with ID survey-page

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by yidan** [comment]
![screen shot 2018-03-17 at 7 17 30 pm](https://user-images.githubusercontent.com/1720237/37561250-0dde18f2-2a18-11e8-8118-47d3fab26bc3.png)

**Comment by andrewtelnov** [comment]
@yidan It sounds as a bug. However, we have never experienced or been reported about this issue before. Could you please shared us with a project on plunker or in any other way, so we will be able to reproduce it and fix.
Right now, I can see a knockout error, but survey-page template is here and I have not any idea, why it could not find it in your project.

Thank you,
Andrew

**Comment by yidan** [comment]
Thanks Andrew. I realized it could be a compatibility issue with our hosting software. Our website is hosted on Hubspot COS.  

You may take a look here
https://goo.gl/8YLDfS
password: test

Thanks!

**Comment by dmitrykurmanov** [comment]
Hello, we've found the problem. We put our templates as scripts with id `<script type="text/html" id="survey-progress">...` inside the div with survey `<div id="surveyContainer">` in your example.

And you have _site.min.js_ script which loaded after that.  `site.min.js` remove our scripts via the code: 
`a("div.header-container-wrapper, div.body-container-wrapper,div.footer-container-wrapper").find("script").remove();` So this code removes our templates.

We suggest two solutions:

1. You could render the survey 
```
var survey = new Survey.Model(surveyJSON);
$("#surveyContainer").Survey({
    model: survey,
    onComplete: sendDataToServer
});
```
  after the _site.min.js_ script (onDocumentReady for example) and it should do the trick.

2. You can modify your  _site.min.js_  script to exclude `surveyContainer` from removing scripts.

**Comment by yidan** [comment]
@dmitrykurmanov Thank you so much for looking into this! 
After moving the survey script after our sites.min js script, it still doesn't work :( 

But I found a walkaround, the vuejs version seems to work fine.

**Comment by tsv2013** [comment]
@yidan The code from your `sites.min js` script is executed on document ready, but code that creates and renders the survey is executing on loading, during parcing the `asdfcaefds` page.

So you need to move survey initialization later, then  `sites.min js` script is executed.

**Comment by yidan** [comment]
@tsv2013 I see! Thank you so much!
