### ISSUE TITLE
IsRequired errors show up when survey is loaded

### ISSUE THREAD

**Issue by nicklas669** [surveyjs/surveyjs#1006]
Hi guys.

### Are you requesting a feature, reporting a bug or ask a question?
Question/bug

### What is the current behavior?
When we load our surveys, all questions that have the "isRequired" attribute set show the requiredError text of "Please answer the question.", or in my case "Besvar venligst spørgsmålet.".

### What is the expected behavior?
Is there any way to have these errors not pop up on initial load? I have tried recreating the issue in your online survey builder but here the errors don't seem to show on initial load but rather when I click next/complete?

Kind regards, 
Nicklas

**Comment by andrewtelnov** [comment]
@nicklas669 Any chance that you are calling nextPage() or hasErrors() functions?

Thank you,
Andrew

**Comment by nicklas669** [comment]
@andrewtelnov I found out why this happens, thanks to your clue. We do not call nextPage() or hasErrors() directly but I found out that we are using sender.isCurrentPageHasErrors to determine whether we should show next/submit buttons... I guess this triggers the error validations?

**Comment by nicklas669** [comment]
Fixed, thanks.
