### ISSUE TITLE
DisplayValue for custom widget? 

### ISSUE THREAD

**Issue by kaphert** [surveyjs/surveyjs#1008]
I have a few custom widgets and one of them is a widget that adds a the https://flatpickr.js.org/ to the survey. 

The user sees a string like: 19 Mar 2018 but the actual value is 2018-03-19. 

In my situation the user is selecting a date in step 1 and I would like to show this date later on in one of the steps. This works fine when I use the `{field_name}` placeholder but it is giving me the value of 2018-03-19 which makes sense because that is the actual value. But I would like to show there the date formatted as 19 Mar 2018.

Is there a way to add equal to checkboxes, radiogroups and selects to have a displayValue property on custom widgets so I can control this output?

**Comment by andrewtelnov** [comment]
@kaphert Let me clearify.
You are using {field_name} some where in title and you want to show the display value and not the actual value, am I correct?
If this correct, I may add this functionality to custom widgets. It should not be hard to implement.

Thank you,
Andrew

**Comment by kaphert** [comment]
Yes indeed that is the short explanation ;-)

**Comment by andrewtelnov** [comment]
@kaphert Then I got it :)

**Comment by andrewtelnov** [comment]
@kaphert You will have to write something like:
```
//return not null if you want to change the default behavior
getDisplayText: function(question) {
 return question.value === 1 ? "one" : null;
}
```

Thank you,
Andrew

**Comment by kaphert** [comment]
@andrewtelnov jeez, that was quick. Thanks. One suggestion though, wouldn't it be better to rename the method to `getDisplayValue` to be more inline with the `displayValue` property?

**Comment by andrewtelnov** [comment]
@kaphert Yes, you are right. It is better, corrected.

Thank you,
Andrew
