### ISSUE TITLE
Update date format in Jquery-UI datepicker

### ISSUE THREAD

**Issue by terryttt** [surveyjs/surveyjs#1010]
### Are you requesting a feature, reporting a bug or ask a question?
ask a question

 I'm using JQuery DatePicker for a date field and I want to change the date format from 'mm/dd/yy' to 'dd/mm/y' e.g. 30/03/18. However, when I pick the date from the panel, the date value was incorrect.
 (please see the gif file below).

### What is the current behavior?

The date value was incorrect.

### What is the expected behavior?

Able to display date  properly with date format 'dd/mm/y'.

### How would you reproduce the current behavior (if this is a bug)?

go to http://surveyjs.org/examples/knockout/custom-widget-datepicker/
click on "Edit in Plunker"
replace the line
{name:"date", type:"text", inputType:"date", title: "Your favorite date:", dateFormat: "mm/dd/yy"}
with
{name:"date", type:"text", inputType:"date", title: "Your favorite date:", dateFormat: "dd/mm/y"}

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

![surveyjs_question](https://user-images.githubusercontent.com/36942718/37644075-9147f284-2c5d-11e8-8910-afdc11b3f6e4.gif)

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by dmitrykurmanov** [comment]
moved to the widgets repo
