### ISSUE TITLE
On render pass data to pre-populate IF the field exists

### ISSUE THREAD

**Issue by Braunson** [surveyjs/surveyjs#1020]
I'm trying to `onRender` populate multiple fields but only if they exists. The data to pre-populate would be provided in the form or an array or object.

Ideally this is what would happens:

```
var data = [
     name: "bob",
     email: "bob@domain.com"
];
```

And on render it will fill the `name` field if it exists with the data's name, and the same for email. I'm trying to make this dynamic so I don't have to manually set each field since the data array would be dynamically generated.

**Comment by andrewtelnov** [comment]
@Braunson You may prepare the mode in the code. here is [the example](https://plnkr.co/edit/4Pj3I3xCquAkN7AAGzeP?p=preview).

Thank you,
Andrew

**Comment by Braunson** [comment]
Thanks @andrewtelnov I also made use of setting `survey.data` which will set pre-populate the data if the inputs exists with the same name.
