### ISSUE TITLE
Is there a visibleIf option for multipletext items?

### ISSUE THREAD

**Issue by testweird123** [surveyjs/surveyjs#1022]
### Are you requesting a feature, reporting a bug or ask a question?
 I'm wondering if there's a visibleIf option for multipletext items.

### What is the expected behavior?
Say I select options in a checkbox. The items in multipletext should be displayed based on options selected in checkbox.

### Specify your

* browser: Chrome
* browser version: 64.0.3282.119
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.14

**Comment by andrewtelnov** [comment]
@testweird123 Unfortunately text item in multiple text doesn't support visibleIf. It is in our plan, but we will add it, after we will refactor our code and start to render text question as text item. Again it is in our TODO list.
We are recommending using Panel. You may achieve the same UI with it, plus get additional functionality if needed.
You may set Panel.title, put into it any question(s), set question.startWithNewLine to false to have several questions in one line, and so on.

Thank you,
Andrew

**Comment by testweird123** [comment]
Okay, this seems to do the job for now. Thanks!
