### ISSUE TITLE
Survey.Data not working for ChoicesFromWeb drop down

### ISSUE THREAD

**Issue by michaelh15** [surveyjs/surveyjs#1029]
### Are you requesting a feature, reporting a bug or ask a question?
Bug?

### What is the current behavior?
Survey.Data is not setting data correctly when using a drop down with choices from web as the datasource.

### What is the expected behavior?
I would expect the dropdown to work exactly the same no matter what the datasource as I've tried to show in the example.

### How would you reproduce the current behavior (if this is a bug)?
In the plunker below, look at the index.js file and you will see that I'm setting the two drop downs in the same way and they are using the same values, but the second drop down gets its items using ChoicesFromWeb and the first drop down gets it's items from a predefined list. The first drop downs value is set using survey.Data, but the second drop downs value is not set.

#### Provide the test code and the tested page URL (if applicable)
https://plnkr.co/edit/OiT3N5KFwt54FjWjONTU?p=preview

**Comment by tsv2013** [comment]
Thank you for the report. It's a bug. We'll fix it.

**Comment by andrewtelnov** [comment]
@michaelh15 The bug has been fixed. The fix will be available in the next minor release.

Thank you,
Andrew
