### ISSUE TITLE
Checkbox in Matrix Dynamic Rows doesn't work

### ISSUE THREAD

**Issue by Lynn42** [surveyjs/surveyjs#1031]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug

### What is the current behavior?

No matter how many answers you select in a checkbox within a matrix (dynamic rows), the result string only gives back 1 answer (the one you selected first).

### What is the expected behavior?

The result string gives back all answers selected.

### How would you reproduce the current behavior (if this is a bug)?
Go to https://surveyjs.io/Editor/Editor/

Use this Survey Structure:

`{
 completedHtml: "<p><b>Bedankt voor het invullen van het formulier.</b></p><p>Uw informatie is succesvol opgeslagen.</p>",
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "matrixdynamic",
     name: "Tandartsen",
     title: "Tandartsen",
     columns: [
      {
       name: "Vaardigheden",
       cellType: "checkbox",
       colCount: 1,
       choices: [
        "1",
        "2",
        "3"
       ]
      }
     ],
     horizontalScroll: true,
     choices: [
      "Ja"
     ],
     cellType: "text",
     rowCount: 1,
     maxRowCount: 40,
     addRowText: "Voeg tandarts toe",
     removeRowText: "Verwijder tandarts"
    }
   ]
  }
 ],
 pagePrevText: "Vorige pagina",
 pageNextText: "Volgende pagina"
}`

Fill out the question with the TEST functionality, and see that it only gives back the first answer you gave, no matter how many answers you selected.

Note:
- This issue did not occur in version 1.0 of SurveyJS
- The same error occurs in the Matrix multiple choice
- A 'normal' checkbox question (not in a matrix) works just fine!
- We tested on both SurveyJS Editor & Library, v. 1.0.15. They give the same (wrong) result string back.

### Specify your

* surveyjs version: 1.0.15

**Comment by tsv2013** [comment]
Thank you for the report. It's a bug. We'll fix it.

**Comment by andrewtelnov** [comment]
@Lynn42 A unit test is added and bug is fixed. The fix will be availalbe in the next minor version.

Thank you,
Andrew
