### ISSUE TITLE
Question about comment sanitization

### ISSUE THREAD

**Issue by alzulas** [surveyjs/surveyjs#1033]
### Are you requesting a feature, reporting a bug or ask a question?

Asking a question

### What is the current behavior?

Just wondered if there are any buffer length checks or content checks for text entering in comments or text. Before I go through all the work of sanitizing my data, I figured I would check if it was already built in. 

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@alzulas  There is no such a property at the current moment. I would agree that it makes sense to introduce it. I would do it on survey level and for text/comment questions.
About others and comments input text for other questions - I would introduce it on survey level only.
survey.maxTextLength (0 - no limits, for text and comment questions), survey.maxOthersLength (0 - no limits, for others and comments inputs in question)
Additionally, QuestionText and QuestionComment, maxLength (-1 - default,  gets the value from survey, 0 - no limits).
Will it work for you?

Thank you,
Andrew

**Comment by alzulas** [comment]
I can use those for buffer length for now, and will validate for alpha numerics and a limited number of punctuation on my side. Thanks again guys!
