### ISSUE TITLE
defaults for new row/panel in matrix/panel dynamic

### ISSUE THREAD

**Issue by masciugo** [surveyjs/surveyjs#1034]
### Are you requesting a feature, reporting a bug or ask a question?

feature

### What is the current behavior?

brand new row/panel in matrix/panel dynamic is blank

### What is the expected behavior?

set defaults for new row/panel

**Comment by tsv2013** [comment]
You can set a defaultValue property for questions inside a panel dynamic:
```JSON
{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "paneldynamic",
     name: "question1",
     templateElements: [
      {
       type: "dropdown",
       name: "question2",
       defaultValue: "item3",
       choices: [
        "item1",
        "item2",
        "item3"
       ]
      }
     ]
    }
   ]
  }
 ]
}
```
Is it what you want to achieve?

Unfortunately we have not implemented defaultValue for matrix cells. We'll discuss it with the team.

Thank you for the suggestion.

**Comment by masciugo** [comment]
ok panel and matrix row work differently because the first one is made of several questions (with their own default values which can be set as you said) while the matrix row is part of a question: the whole matrixdynamic. So forget about the panel

defaultValue for matrix cells is maybe what I need as it cover my use case which is defaultValue for the whole row in case of matrixdynamic. But defaultValue for any kind of matrix is already implemented. I would suggest to make explicit the fact that the defaultValue I am talking about (_rowDefaultValue_) is for the new added row. _rowDefaultValue_ would be a property of matrixdynamic only

**Comment by andrewtelnov** [comment]
@masciugo rowDefaultValue property for Matrix Dynamic definately makes sense. It goes to our TODO list.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@masciugo [defaultRowValue](https://github.com/surveyjs/surveyjs/issues/1166) is here.

Thank you,
Andrew
