### ISSUE TITLE
Auto close popup base on completedHtml

### ISSUE THREAD

**Issue by Hafees89** [surveyjs/surveyjs#1035]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

Can't add any value after call completedHtml.

### What is the expected behavior?

Popup function closed after 3-5 second once completedHtml called.

Hi,

Basically I make popup for surveyjs and everything work quite ok,
but how do I close my popup automatically after 3-5 second after I call completedHtml?

Example code : completedHtml: "<p align='center'><br><br><b>Thank you for completing the feedback. Page will be closed in 3 second. </p></b>"

How do I add auto close popup once this function call? Thank you.

**Comment by andrewtelnov** [comment]
@Hafees89 It was not as simple as I think. We need an option - hideWindowOnComplete, true by default.
Here is the [workaround with the current version](https://plnkr.co/edit/jUIcxT?p=preview)

Thank you,
Andrew

**Comment by Hafees89** [comment]
Thank you @andrewtelnov, this what I'm looking for.

**Comment by andrewtelnov** [comment]
@Hafees89 The folloing property has been added: 
```
  /**
   * Set this value to negative value, for example -1, to avoid closing the window on completing the survey. Leave it equals to 0 (default value) to close the window immediately, or set it to 3, 5, 10, ... to close the window in 3, 5, 10 seconds.
   */
  public closeOnCompleteTimeout: number = 0;
```
From the next version, you will be able to use the following syntaxes:
```
            $("#surveyElement").SurveyWindow({
                model: survey,
                expanded: true,
                closeOnCompleteTimeout: 3
            });    
```

Thank you,
Andrew
