### ISSUE TITLE
Spacing colCount bootstrap

### ISSUE THREAD

**Issue by jerome-lemaire** [surveyjs/surveyjs#1036]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
Spacing between answers when colCount set is incorrect

### What is the expected behavior?
Answers correctly spaced

### How would you reproduce the current behavior (if this is a bug)?
See the links below

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
NOT WORKING: (SurveyJS 1.0.16) https://jsfiddle.net/6ejcqkzk/)
WORKING (SurveyJS 0.97.0) https://jsfiddle.net/9zoawsLt/

### Specify your

* browser: Google chrome
* browser version: 65.0.3325.181
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.16

**Comment by tsv2013** [comment]
Thank you for the report.We'll fix it.
