### ISSUE TITLE
Event Validator on Multipletext inside paneldynamic is not working.

### ISSUE THREAD

**Issue by testweird123** [surveyjs/surveyjs#1037]
Reporting a bug.

### What is the current behavior?

On using event validator on multipletext items inside paneldynamic I get an error : Cannot read property of undefined.
I have recreated the issue in the below plnkr.

https://plnkr.co/edit/RpuVBJI6T4ElmPr3f1K6?p=preview

### Specify your

* browser: Chrome
* browser version: 64.0.3282.119
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.14

**Comment by andrewtelnov** [comment]
@testweird123 I have added a unit test and fixed it. The fix will be available in the next minor update.
As a workaround, please use the followng code:
```
        var leastamount = options.question.value['wholesaler'];
        var mostamount = options.question.value['retail'];
```
Here is the [update plunker](https://plnkr.co/edit/MydToBZEeoXSiGgBFYiO?p=preview)

Thank you,
Andrew

**Comment by testweird123** [comment]
Thank you for the quick response.
