### ISSUE TITLE
VisibleIf condition based on checkbox question not working when choice value begins with number

### ISSUE THREAD

**Issue by AhmedAglan** [surveyjs/surveyjs#1039]
### Are you requesting a feature, reporting a bug or ask a question?
BUG

### What is the current behavior?
When building visibleIf condition based on checkbox question and choice value begins with number like "3b" or "001en" it doesn't work correctly.

Tested page URL:
using contains operator:
https://plnkr.co/edit/lKijKCZVIcEW9QLUR0LA?p=preview

Using equal operator:
https://plnkr.co/edit/mr4n2fIS7gsKYFIWOBLe?p=preview

**Comment by andrewtelnov** [comment]
@AhmedAglan Reproduced the issue in a unit test and fixed it.
The fix will be available in the next minor version, on the next week.
