### ISSUE TITLE
`visibleIf` in `matrixdropdown` row not working in VueJs, but does in jQuery

### ISSUE THREAD

**Issue by exnihilo-creatio** [surveyjs/surveyjs#1040]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

Using the code with a `matrixdropdown` type

`columns: [
                {
                    name: "using",
                    title: "Do you use it?",
                    choices: [
                        "Yes", "No"
                    ],
                    cellType: "radiogroup"
                }, {
                    name: "rate",
                    visibleIf: '{row.using} = "Yes"',
                    title: "Please rate the framework itself"
                }
            ]`

The `visibleIf` shows the needed input field when the `using` field's answer is `Yes` with the jQuery version, however, the same code does not work with the VueJs version.

The VueJs version does work if there are multiple pages and you click `previous` and then `next`.

### What is the expected behavior?

That the `rate` input field is also visible when the condition `'{row.using} = "Yes"'` equals `true` with the VueJs version.

### How would you reproduce the current behavior (if this is a bug)?

Go to [jQuery version](https://plnkr.co/edit/bAgeuufTvWP2ZDrJ4ssm?p=preview) in order to test the jQuery version.

Go to [VueJs version](https://plnkr.co/edit/27Z5fPakC4Od8pGhSFWe?p=preview) in order to test the VueJs version.

### Specify your

* browser: **Firefox + Chrome**
* browser version: **FF 59.0, Chrome 65**
* surveyjs platform: **vuejs**
* surveyjs version: **1.0.16**

**Comment by andrewtelnov** [comment]
@exnihilo-creatio The issue is fixed.  The fix will be available in the next minor update on this week.

Thank you,
Andrew
