### ISSUE TITLE
Custom widgets not rendering correctly when upgrading from v.1.0.14 to v.1.0.15+

### ISSUE THREAD

**Issue by nicklas669** [surveyjs/surveyjs#1041]
### Are you requesting a feature, reporting a bug or ask a question?
Bug/question

Hi SurveyJS team.

We have some custom widgets that we have developed using version 1.0.14 of your plugin. When we upgrade to version 1.0.15 or 1.0.16, our widgets no longer render correctly.  E.g.: We have a "dropdown widget" which renders as a select list and fetches some data on load which is put into the select list. In v.14 this worked well but in v.15 the question element is rendered as a input tag instead of our wanted selected tag. Below are some images of what I have tried to describe.

Below is a snippet of our dropdown widget. It can be seen that the 5th parameter defines the HTML markup, htmlTemplate, that our widget should produce:
![markup](https://user-images.githubusercontent.com/4216390/38543199-2f50ccde-3ca4-11e8-947a-f3e76b7f9c51.PNG)

Working dropdown widget in v.14:
![working dropdown](https://user-images.githubusercontent.com/4216390/38543065-cde0e59c-3ca3-11e8-8122-4a15fb6117d6.PNG)

Same dropdown widget in v.15:
![image](https://user-images.githubusercontent.com/4216390/38543059-c7c09982-3ca3-11e8-83fa-486cb93904e9.png)

I have looked at the difference in the generated HTML markup, the difference can be seen on the following link. The markup on the left is the widget in v.14 and the markup on the right is the same widget in v.15: [http://www.mergely.com/BdcMLl2e/](http://www.mergely.com/BdcMLl2e/)

It looks like there is automatically inserted a <input> field on questions now or something? I hope you can give me some hints as to what is happening..

Kind regards,
Nicklas

**Comment by dmitrykurmanov** [comment]
Hello! Please tell what framework do you use?

**Comment by nicklas669** [comment]
@dmitrykurmanov  We are using https://surveyjs.azureedge.net/1.0.14/survey.jquery.min.js, so jquery.. is this what you mean?

**Comment by dmitrykurmanov** [comment]
Sorry, but we can't realize what's wrong based upon the information you've provided. An our example on the site works ok.  Could you please provide a small example with the problem on plunker (or another sandbox) ? And we will debug it.

**Comment by tsv2013** [comment]
I've reviewed changelog between 1.0.14 and 1.0.15 and havn't found - what could be a cause of such a breaking change.
I've reviewed the diff you provided. And I think the text question is rendered instead of empty template.
Can you check - what question and what template name do you have at this point of your markup - `<!-- ko template: { name: question.koTemplateName()`?
What is the type of the question?

**Comment by nicklas669** [comment]
Hi @tsv2013 . I am not quite sure what you are asking for but I have tried to extract the information you asked for. It can be seen in this diff (v.14 on the left, v.15 on the right): [http://www.mergely.com/Tm8lnuVO/](http://www.mergely.com/Tm8lnuVO/). It looks like there is no difference here?

The JSON for our question is the following:
```
 {
  "pages": [
    {
      "elements": [
        {
          "type": "dropdownChoiceWidget",
          "name": "1525075935799",
          "visibleIf": "",
          "validators": [
            {
              "type": "dropdownChoiceWidgetvalidator"
            }
          ],
          "title": {
            "da-DK": "Vælg speciel indklaget"
          },
          "dropdownurl": "External/Complaint/GetListOfSpecialRespondents",
          "help": {
            "da-DK": ""
          },
          "description": {
            "da-DK": ""
          },
          "tag": "",
          "isRequired": true
        }
      ]
    }
  ],
  "questionTitleTemplate": "{title} {require}",
  "showCompletedPage": false,
  "templateName": "Testing survey version change"
}
```

Thanks in advance,
Nicklas

**Comment by andrewtelnov** [comment]
@nicklas669 Could you send us your custom widget code and instruction how to reproduce the issue. Unless we do not reproduce the issue, we will unlikely understand what is going on here, and as result, we will not be able to help.

Thank you,
Andrew

**Comment by nicklas669** [comment]
I have heard back from the team who worked further on the project, after I moved to another one. The problem seems to be fixed if the type/name of our widgets is strictly lowercase instead of camelCase as we had.. very weird behaviour.

**Comment by andrewtelnov** [comment]
@nicklas669 You may use the camel case. However question.getType() will return the value in lowcase always. Here is the code from unit test:
```
QUnit.test("customWidgets camel name", function(assert) {
  CustomWidgetCollection.Instance.clear();
  CustomWidgetCollection.Instance.addCustomWidget({
    name: "camelName",
    isFit: question => {
      return question.getType() == "camelname";
    }
  });
  if(!JsonObject.metaData.findClass("camelName")) {
    JsonObject.metaData.addClass("camelName", [], null, "text");
  }
  
  var survey = new SurveyModel({
    elements: [
      {
        type: "camelName", name: "q1"
      }
    ]
  });
  var question = <Question>survey.getQuestionByName("q1");
  assert.equal(
    question.customWidget.name,
    "camelName",
    "the custom custom widget is set"
  );
  CustomWidgetCollection.Instance.clear();
});
```

Thank you,
Andrew
