### ISSUE TITLE
Customize panel header to add react custom buttons

### ISSUE THREAD

**Issue by marc0n3** [surveyjs/surveyjs#1043]
### Are you requesting a feature, reporting a bug or ask a question?

Question/Feature request

### What is the current behavior?

Panel title is not customizable, but I need to add a button before the collapse to add a note to the question. 
The Component will be written in reactJS

### What is the expected behavior?
I can customize the rendering of the title or add components before the collapser

### Specify your

* browser: /
* browser version: /
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: "survey-react": "^1.0.16",

**Comment by marc0n3** [comment]
How do I add a React component before the button? As I know, it is not
possible to add subtree under a react controlled tree. This was why I was
asking a way to do this or to use a custom renderer for the panel.
Thanks in advance.
Marco

2018-04-11 21:22 GMT+02:00 Andrew <notifications@github.com>:

**Comment by marc0n3** [comment]
Maybe this is not relevant but if you change entries/react.ts to:
export { SurveyPage, SurveyRow, SurveyPanel } from "../react/reactpage";
exporting the panel too, I think is possible to do:
SurveyRow.prototype.createQuestion =(question)=>{

			if (question.isPanel) {
				return (
						<SurveyPanel
								key={question.name}
								panel={question}
								creator={this.creator}
								survey={this.survey}
								css={this.css}
						/>
				);
			} else {
				return (
						<SurveyQuestion
								key={question.name}
								question={question}
								creator={this.creator}
								css={this.css}
						/>
				);
			}
		}
inside my code to override the method and use an extension of SurveyPanel instead of the base.

I'll try this to see if works
Thanks

**Comment by marc0n3** [comment]
I confirm that in this way it works... Maybe it's a little bit hackish but works

**Comment by andrewtelnov** [comment]
@marc0n3 Could you make a pull request?

Thank you,
Andrew
