### ISSUE TITLE
visibleIf doesn't work correctly if elements are removing/adding during condition running

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#1044]
We were trying to use a trick, to re-oder questions on it's visible changing. So if a question becomes a visible just now, it becomes the last question.
Unfortunately, it doesn't work, since container runs condition (visibleIf) check in cycle  for an array, that is changing during this run.
The solution is to copy this array, array.slice() before the run.
The issue is came [from here](https://surveyjs.answerdesk.io/ticket/details/T549)

**Comment by andrewtelnov** [comment]
A new unit test is added and fixed.

**Comment by emailtosamit** [comment]
Is this issue resolved?

I created a simple two field form and fields are placed in following order:-
1. Comment  (this is long text field with "visibleIf": "{Issunny} = 'Yes'")
2. Is it sunny?(this is radio button with two choices (yes and no) and name property set to Issunny )

Outcome:-
When yes is selected in "Is it sunny?" the comment field gets visible before "Is it sunny?" field instead of after.

Expected result:-
The comment field should get visible after "Is it sunny?" field.

**Comment by andrewtelnov** [comment]
@emailtosamit It works absolutely correct. It is a very basic functionality. At the current day hundreds of companies use our products. They would not use us if we have bugs like this.
Here is [the working example](https://plnkr.co/edit/qI7VvrE3ZKsewlC5) that shows how it works.

Thank you,
Andrew

**Comment by emailtosamit** [comment]
hi Andew, 

Thanks for your response and sharing the example. But it does not work as i expect.

- In the example provided by you the "comment_suny" is placed above"Issunny" field. 
- When user is selecting "issunny" to 'no' the "comment_suny" is getting hidden.
- When user is selecting "issunny" to 'yes' the "comment_suny" is getting visible and appear above "Issunny" field.
-  In my scnerio i am expecting "comment_suny" should get visible **below** "issunny" field even thought in form it placed above "isSunny" field. 

Please let me know if that is possible or not. if yes then how?

Again thanks for your response.

**Comment by andrewtelnov** [comment]
@emailtosamit It shows as it is in the elements array order. I added isRainy in my example. It does exactly what you need.

Thank you,
Andrew

**Comment by emailtosamit** [comment]
Sorry @andrewtelnov  but that is not my scenario. 

In my scenario on the form, two control(A & B) is placed in sequential order A is first and B is second. A control is configured using "visibleif" expression. Initially A appear first and B appear second. As soon as "visibleif" trigger the A control get hidden. Now when the "visibleIf" get trigger again, i want control A should appear after control B. So it should appear afterwards in order B and A.

In other words for below form, initially "comment_sunny" appear first and then "isSunny". When user choose Yes in "isSunny", the "comment_sunny" hide. When user choose No in  "isSunny" then i want the "comment_sunny" to get visible after "IsSunny" ( So the first should be "IsSunny" and second should be "comment_sunny".

{
  "elements": [{
    "name": "comment_sunny",
    "type": "comment",
    "visibleIf": "{isSunny} = 'yes'"
  }, {
    "name": "isSunny",
    "type": "radiogroup",
    "choices": ["yes", "no"]
  }, ]
};

In summary initially control should appear as mention in JSON but if visibleif trigger then afterwards that particular control appear at last. I hope that clarify my scenerio.

**Comment by andrewtelnov** [comment]
@emailtosamit Your JSON should be the following:
```js
{
"elements": [
{
"name": "isSunny",
"type": "radiogroup",
"choices": ["yes", "no"]
},
{
"name": "comment_sunny",
"type": "comment",
"visibleIf": "{isSunny} = 'yes'"
}]
};
```
In this case the "comment_sunny" will be the second. You can use visibleIf condition for a question located on another page or you can have a dozen questions with visibleIf expression where {isSunny} is used. It doesn't mean that we have to remove a question from another page or show all these dozen questions in a random order. The order is preserved as it is in elements array.

Thank you,
Andrew

**Comment by emailtosamit** [comment]
Thanks @andrewtelnov. That answered my question. specialy the statement "The order is preserved as it is in elements array."

I was thinking to reuse the same control but it does not seems possible as per your explanation and i have to add another control.

For e.g in below form comment_sunny will always going to display in between isHot and isSunny

const json = { "elements": [{
    "name": "isHot",
    "type": "radiogroup",
    "choices": ["yes", "no"]
  },
 {
    "name": "comment_sunny",
    "type": "comment",
    "visibleIf": "{isSunny} = 'yes' or {isHot} = 'yes'"
  }, {
    "name": "isSunny",
    "type": "radiogroup",
    "choices": ["yes", "no"]
  }, ]
};

and if i want comment to display after isSunny then i have to add another comment control as below. right?

const json = { "elements": [{
    "name": "isHot",
    "type": "radiogroup",
    "choices": ["yes", "no"]
  },
 {
    "name": "comment_hot",
    "type": "comment",
    "visibleIf": "{isHot} = 'yes'"
  }, {
    "name": "isSunny",
    "type": "radiogroup",
    "choices": ["yes", "no"]
  },{
    "name": "comment_sunny",
    "type": "comment",
    "visibleIf": "{isSunny} = 'yes' "
  } ]
};

**Comment by andrewtelnov** [comment]
@emailtosamit They are two different questions and they will store data in the different JSON attribute. 

Thank you,
Andrew

**Comment by emailtosamit** [comment]
@andrewtelnov  agree but in my scenario due to some business rules either question 1 appear or question 2, both can't appear at same time. Hence was trying to store answer of both this  question in one answer field.

Thanks
-Samit

**Comment by andrewtelnov** [comment]
@emailtosamit As I said you can use `valueName` property to share data between questions.
```json
{ "elements": [{
"name": "isHot",
"type": "radiogroup",
"choices": ["yes", "no"]
},
{
"name": "comment_hot",
"valueName": "comment",
"type": "comment",
"visibleIf": "{isHot} = 'yes'"
}, {
"name": "isSunny",
"type": "radiogroup",
"choices": ["yes", "no"]
},{
"name": "comment_sunny",
"type": "comment",
"valueName": "comment",
"visibleIf": "{isSunny} = 'yes' "
} ]
};
```

Thank you,
Andrew
