### ISSUE TITLE
otherText field isn't getting rendered when locale is changed.

### ISSUE THREAD

**Issue by Jcook894** [surveyjs/surveyjs#1045]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
The current behavior is that once I change my locale to Spanish the otherText fields change to Spanish, but once I switch back to english, the otherText field stays in Spanish. 

This functionality was working in the previous version of surveyjs.

### What is the expected behavior?
The expected behavior is to have the otherText field switch to English and Spanish and vice versa. Which was not an issue in the previous version.

### How would you reproduce the current behavior (if this is a bug)?
Have an assessment that has an otherText field inside, with 2 different languages.

Set up input's with bindings that change the assessment from English to Spanish. (As code is below)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Working on a plunker.

```

//The inputs that switch the assessment from english to Spanish, and vice-versa.

<div [hidden]="!showLangSelect || pediAdult == ''" class="language-selector">
        <label>
      <input type="radio" [(ngModel)]="surveyModel.locale"  [(ngModel)]="pediSurvey.locale" (click)="this.chooseLang('default')"  value="default">
      English
    </label>
        <label>
      <input type="radio" [(ngModel)]="surveyModel.locale"  [(ngModel)]="pediSurvey.locale" (click)="this.chooseLang('sp')" value="sp">
      Spanish
    </label>
</div>

// The Question with the otherText field.

var json = {
 locale: "default",
 title: "Software developer survey.",
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "checkbox",
     name: "opSystem",
     title: "OS",
     isRequired: true,
     hasOther: true,
     choices: [
      "Windows",
      "Linux",
      "Macintosh OSX"
     ],
     otherText: {
      default: "Other",
      es: "Otro"
     }
    }
   ],
   title: "What operating system do you use?"
  },
  {
   name: "page2",
   elements: [
    {
     type: "checkbox",
     name: "langs",
     title: "Plese select from the list",
     isRequired: true,
     choices: [
      "Javascript",
      "Java",
      "C#"
     ],
     colCount: 4
    }
   ],
   title: "What language(s) are you currently using?"
  },
  {
   name: "page3",
   elements: [
    {
     type: "text",
     name: "name",
     title: "Name:"
    },
    {
     type: "text",
     name: "email",
     title: "Your e-mail"
    }
   ],
   title: "Please enter your name and e-mail"
  }
 ]
};


// The language function, which gets called in ngOnIt().

 ngOnInit(): void {
 ....
 ....
this.chooseLang(this.surveyModel.locale);
 }

chooseLang(lang) {
        if (lang === "sp") {
            this.surveyModel.locale = "sp";
            this.pediSurvey.locale = "sp";
            this.pediAdultSurvey.locale = "sp";
        } else if (lang === "default") {
            console.log(lang);
            this.surveyModel.locale = "default";
            this.pediSurvey.locale = "default";
            this.pediAdultSurvey.locale = "default";
        }
        this.surveyModel.render();
        this.pediSurvey.render();
        this.pediAdultSurvey.render();
        this.addCancelButton();
    }

////
```

### Specify your

* browser: Chrome, Firefox, IE, Edge
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version: Latest version

**Comment by andrewtelnov** [comment]
@Jcook894 I was able to reproduce the issue in a unit test and fix it.
The fix will be available in the next minor update, on the next week.
You may build the library by yourself using the instruction in the readme file.

Thank you,
Andrew

**Comment by Jcook894** [comment]
Here is the Plunker: https://plnkr.co/edit/WwLLucUfvdDroY8JegCu?p=preview

**Comment by Jcook894** [comment]
Thanks Andrew!
