### ISSUE TITLE
Css for Questions within dynamic panels

### ISSUE THREAD

**Issue by ashygk** [surveyjs/surveyjs#1049]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

Css for questions is working as expected

### What is the expected behavior?

Css for questions within dynamic panel is not applied.
I have a dynamic panel with multiple questions of type comment, dropdown etc.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular 5
* surveyjs version: 1.0.0

**Comment by tsv2013** [comment]
Could you please specify - what exact CSS rule doesn't work?
It can be overriden via the panel CSS rules. I think I can find corresponding selector for you. And you can check it in the "developer tools" window :-)
