### ISSUE TITLE
Display mode doesn't work for paneldynamic/matrixdynamic and matrixdropdown

### ISSUE THREAD

**Issue by testweird123** [surveyjs/surveyjs#1051]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a Bug

### What is the current behavior?
survey.mode="display" not working for few elements. (I think its for all elements inside paneldynamic/matrixdynamic and matrixdropdown

#### Provide the test code and the tested page URL (if applicable)
https://plnkr.co/edit/eztSSwVdphiLPi47gQTz?p=preview

### Specify your

* browser: Chrome
* browser version: 64.0.3282.119
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.16

**Comment by andrewtelnov** [comment]
@testweird123 I see it now. It doesn't work for paneldynamic.
We will fix it.

Thank you,
Andrew
