### ISSUE TITLE
Logo proposal for SURVEYJS

### ISSUE THREAD

**Issue by moenawar85** [surveyjs/surveyjs#1052]
Hello Sir... I designed Logo Icon/ Logotype for you. I hope you like it, I'm waiting for your response and answer. If you have any suggestion about color or add something in the logo I will do it. I will give you original file / editable file (CDR or PDF) and PNG.

![new logo design_logo icon](https://user-images.githubusercontent.com/36834147/38816356-1c00fac0-41c0-11e8-9c25-d12fad379c4c.png)

![new logo design_logotype](https://user-images.githubusercontent.com/36834147/38816404-31e2361a-41c0-11e8-9f6b-492fedadd9bf.png).

Best regards, Moenawar.
Thank you indeed.

You can contact me with email : monox.rhtm@gmail.com
My twitter : @moen85, steemit: https://steemit.com/@moenawar

**Comment by tsv2013** [comment]
Duplicate for https://github.com/surveyjs/surveyjs/issues/1032

**Comment by moenawar85** [comment]
So how sir? This logo rejected?

**Comment by tsv2013** [comment]
I'd like to ask you don't create duplicated issues. We can continue discussion in the main thread - https://github.com/surveyjs/surveyjs/issues/1032
To be honest I'm not sure we need a new logo for our project.

**Comment by moenawar85** [comment]
Ohhh... Okay. I'm sorry to do that.
