### ISSUE TITLE
defaultValue not populating for multipletext questions.

### ISSUE THREAD

**Issue by doliver-pulsemining** [surveyjs/surveyjs#1057]
### Are you requesting a feature, reporting a bug or ask a question?
Bug.

### What is the current behavior?
defaultValue property is ignored for all items in a multipletext question. I expected defaultValue to act the same as for a single entry question.

#### Provide the test code and the tested page URL (if applicable)

Example shows default value populating for single input questions but not for multipletext.
https://plnkr.co/edit/04RtBdSjjiSfZFL7GBkI?p=preview 

### Specify your

* browser: Chrome
* browser version: 65
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery
* surveyjs version: v1.0.0 -> v1.0.18

**Comment by andrewtelnov** [comment]
@doliver-pulsemining Here is the correct json: https://plnkr.co/edit/52YgdkZX026lnQcrQ6zC?p=preview
If you create the json in the builder, you will have it in this way.
I can't say that your json looks bad, but we decided to have defaltValue on top level object - question.

Thank you,
Andrew

**Comment by doliver-pulsemining** [comment]
Thanks for the fast response. That will work perfectly.

**Comment by alekhraut** [comment]
Hi @andrewtelnov,

I a trying to set data for multiple text, but am not able to set it.

Repo; https://github.com/alekhraut/MultipletextSurvey

Could you please check and let me know, if am missing out any thing.

-Thanks in advance.
