### ISSUE TITLE
Validation in custom widgets

### ISSUE THREAD

**Issue by gajayreddy9** [surveyjs/surveyjs#1060]
### Are you requesting a feature, reporting a bug or ask a question?
question

### What is the current behavior?
I have a custom widget for showing countries drop down for the telephone field which is working perfectly fine and now I want to validate the phone number entered based on the country selected using the plugin.

### What is the expected behavior?
I was able to  check if the entered number is valid based of the country but not able to throw the validation error on the UI. 

I wanted to show the validation message on the UI. if you look for the line ' throw the error message here' in the code below. It is the place where I want to throw the validation error.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
var widget = {
    name: "intlTel",
    htmlTemplate: "<input class='intlTel form-control max-width-tel' type='tel' name='phoneNumber'>",
    isFit: function(question) {
        return question.getType() === 'text' && question.inputType === 'tel';
    },
    afterRender: function (question, el) {
        var $el = $(el).find('.intlTel');
        $el.val(question.value);
        $el.attr("placeholder", question.placeHolder);
        $el.intlTelInput({
            formatOnInit: false,
            separateDialCode: true,
            utilsScript: "/Scripts/utils.js"
        });
        $el.on('change', updateQuestionValue);
        $el.on("countrychange", updateQuestionValue);

        function updateQuestionValue() {
             var isValid = $el.intlTelInput("isValidNumber");
            if (!isValid && $el.intlTelInput("getValidationError") !== 0) {
                var validationError = $el.intlTelInput("getValidationError");
                if (validationError === intlTelInputUtils.validationError.TOO_SHORT) {
                     throw the error message here
                }
                if (validationError === intlTelInputUtils.validationError.TOO_LONG) {
                      throw  error message here
                }
            }
             var dialCode = $el.intlTelInput('getSelectedCountryData').dialCode;
            if (dialCode != null && $el.val() !== "" && $el.val() !== dialCode) {
                question.value = "+" + dialCode + $el.val();
            } else {
                question.value = null;
            }
        }
    }
}

Survey.CustomWidgetCollection.Instance.addCustomWidget(widget);

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):  jquery
* surveyjs version:

**Comment by tsv2013** [comment]
You can create a [custom validator](https://surveyjs.io/Examples/Library/?id=validators-custom&platform=jQuery&theme=default) or [validate value on event](https://surveyjs.io/Examples/Library/?id=validators-event&platform=jQuery&theme=default).

**Comment by gajayreddy9** [comment]
I tried to create a custom validator. The code is below. But if you look at the line  'var $el = Survey.find('.intlTel');' I kind of need to find the element and then do some validation on top of the plugin I am using. Is there a way to find the element like I am accessing it in the custom widget.

'''var TelephoneValidator = (function (_super) {
    Survey.__extends(TelephoneValidator, _super);
    function TelephoneValidator() {
        _super.call(this);
    }
    TelephoneValidator.prototype.getType = function () {
        return "telephonevalidator";
    };
    TelephoneValidator.prototype.validate = function (value, name) {
        var $el = Survey.find('.intlTel');
        var isValid = $el.intlTelInput("isValidNumber");
        if (!isValid && $el.intlTelInput("getValidationError") !== 0) {
            var validationError = $el.intlTelInput("getValidationError");
            if (validationError === intlTelInputUtils.validationError.TOO_SHORT) {
                return new Survey.ValidatorResult(null, new Survey.CustomError("number short"));
            }
            if (validationError === intlTelInputUtils.validationError.TOO_LONG) {
                return new Survey.ValidatorResult(null, new Survey.CustomError("number long"));
            }
        }
     return null;
    };
    //the default error text. It shows if user do not set the 'text' property
    TelephoneValidator.prototype.getDefaultErrorText = function (name) {
        return "Not a valid phone number.";
    }
    return TelephoneValidator;
})(Survey.SurveyValidator);
Survey.TelephoneValidator = TelephoneValidator;
//add into survey Json metaData
Survey
    .JsonObject
    .metaData
    .addClass("telephonevalidator", [], function () {
        return new TelephoneValidator();
    }, "surveyvalidator");'''
