### ISSUE TITLE
Feature request: popups with additional info for question on mouse over

### ISSUE THREAD

**Issue by mradzivonenka** [surveyjs/surveyjs#1061]
### Are you requesting a feature, reporting a bug or ask a question?
Hi, it would be nice to have a possibility to add popup for question with some additional info

### What is the expected behavior?
![popup](https://user-images.githubusercontent.com/12149038/39175250-7be3206a-47b2-11e8-83cd-2ab5ab68f06d.png)

**Comment by tsv2013** [comment]
You can render additional elements (e.g. as on your picture) as shown in this example - https://surveyjs.io/Examples/Library/?id=survey-afterrender&platform=jQuery&theme=default

**Comment by mradzivonenka** [comment]
Perfect! Thank you!
