### ISSUE TITLE
Set defaultValue for matrix question.

### ISSUE THREAD

**Issue by bramson** [surveyjs/surveyjs#1065]
### Are you requesting a feature, reporting a bug or ask a question?

A question if it's already possible, and a feature request if it's not.

### What is the current behavior?

N/A

### What is the expected behavior?

I would like to set the default value for matrix questions.

### How would you reproduce the current behavior (if this is a bug)?

N/A

### Other details

For an "element" of type "matrix", the columns (the scores/values) are setup first.  So it would make sense to setup a default value by setting it with the row definitions...like this:

 rows: [
      {
       value: "product",
       text: "Quality of Product"
       defaultValue: "0"
      }, {
       value: "product",
       text: "Quality of Service"
       defaultValue: "0"
     }]

But I'd be happy if there were any way to do this.

**Comment by tsv2013** [comment]
Default value sould be set to a matrix question:
```JSON
{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "matrix",
     name: "question1",
     defaultValue: {
      product: "Slow",
      service: "Good"
     },
     columns: [
      "Bad",
      "Slow",
      "Good"
     ],
     rows: [
      "product",
      "service"
     ]
    }
   ]
  }
 ]

```

**Comment by bramson** [comment]
Perfect!  Thanks.
