### ISSUE TITLE
Textarea not rendering properly in Default CSS

### ISSUE THREAD

**Issue by derchirurg** [surveyjs/surveyjs#1066]
### Are you requesting a feature, reporting a bug or ask a question?
bug

### What is the current behavior?
Textarea fields (comments) where only rendered as one-liner in default theme.

### What is the expected behavior?
Should be rendered as multi liner.

### How would you reproduce the current behavior (if this is a bug)?
See Plunk: http://plnkr.co/edit/Inx1cyy8VHDwRmJ4Vbye

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: http://plnkr.co/edit/Inx1cyy8VHDwRmJ4Vbye

### Specify your

* browser: All
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version:1.0.19

**Comment by tsv2013** [comment]
Thank you for the report. Fix will be available in the nearest update.
