### ISSUE TITLE
Display mode with *

### ISSUE THREAD

**Issue by xiuzhen1103** [surveyjs/surveyjs#1067]
### Are you requesting a feature, reporting a bug or ask a question?

Ask a question

### What is the current behavior?
When survey on display mode, it has * on the beginning of each question due to attribute on survey "isRequired : true"

### What is the expected behavior?
Would it be possible remove * in front of question on display mode, please?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: http://plnkr.co/edit/EiPUDvJgrF1ABWPkvCyp?p=preview

### Specify your

* surveyjs platform (angular or react or jquery or knockout or vue): reactJs
* surveyjs version: 0.12.18, 0.12.26 (I am using these two versions, both same issue)
![image](https://user-images.githubusercontent.com/6764095/39302620-2530b468-494b-11e8-91b2-54955b9e5109.png)

**Comment by xiuzhen1103** [comment]
Hi @andrewtelnov Andrew, thanks for quick response, here is problem.  
Please check URL again,
survey.requiredText is working with version 0.12.18, but not in version 0.12.26. 
http://plnkr.co/edit/EiPUDvJgrF1ABWPkvCyp?p=preview

**Comment by xiuzhen1103** [comment]
Thanks for your help! don't worry about it, I have updated to one version on 0.12.34 which works find

**Comment by andrewtelnov** [comment]
@xiuzhen1103 It perfectly works now: http://plnkr.co/edit/QFUnBqAXzuQMHmGMmdjV?p=preview
You are using an old version. It is not even released. We have fixed this bug several months ago and added unit tests. The current version is: 1.0.19

Thak you,
Andrew

**Comment by xiuzhen1103** [comment]
Would it be possible if I could it working in 0.12.26, please? I have updated to 0.12.34 or 1.0.19 which which causing more issues for me.

**Comment by andrewtelnov** [comment]
What issues to you have with the latest version 1.0.19? You are using a beta version.

Thank you,
Andrew

**Comment by xiuzhen1103** [comment]
Small thing I could fix easily, element with survey CSS. However, I have add customised jQuery method to select class which is all broken, due to change updated version of HTML, for example I have raised this issue. 

https://github.com/surveyjs/surveyjs/issues/1063

**Comment by andrewtelnov** [comment]
@xiuzhen1103 We have changed the rendering in the release version and the way we are working with css classes. We made it more flexible + implement several themes created by our designer. I am not sure. what you are doing in your case, but I am positive that it should be done with the latest version as well.

Thank you,
Andrew

**Comment by tsv2013** [comment]
1.0.0 is the release version

**Comment by tsv2013** [comment]
As far as I remember we've introduced themes in 0.98.5. And we made our rendering consistent between platforms as this point. The older versions doesn't render invisible questions.

I've seen the sample markup [here](https://github.com/surveyjs/surveyjs/issues/1063#issuecomment-384342461). Could you explain us - what do you want to achieve? Probably we can suggest you a solution.
