### ISSUE TITLE
new feature: Add event when data loaded from rest 

### ISSUE THREAD

**Issue by xibman** [surveyjs/surveyjs#1068]
### New Feature
Add an event when data loaded with choice by url.

### What is the current behavior?
No event

### What is the expected behavior?
An event that can trigger if array of data returned by rest api is empty so  we can hide and disable the  input

**Comment by tsv2013** [comment]
The `QuestionSelectBase` has `choicesChangedCallback`. It's called on choices has been changed.
You can see sample usage here - https://github.com/surveyjs/widgets/blob/master/src/select2.js
Probably we need to document it

**Comment by xibman** [comment]
Ok so we would be able to track if array returned by rest service is empty or not. 
But is it possible to to hide the survey element (dropdown, checkbox ...) if array is empty

**Comment by xibman** [comment]
The visible property overide  the visibleif property  ?

**Comment by tsv2013** [comment]
@andrewtelnov A global event in survey, or event per question?

**Comment by xibman** [comment]
An easy test could be if the rest api return an empty array the question must not be visible

**Comment by tsv2013** [comment]
@xibman Other choice can be an option in the case

**Comment by xibman** [comment]
- specific object returned by the api could be used
- http error code returned by api  like this 
`{
  "code": 21211,
  "message": "The 'To' number 5551234567 is not a valid phone number.",
  "more_info": "https://www.twilio.com/docs/errors/21211",
  "status": 400
}`

**Comment by andrewtelnov** [comment]
The following event has been added:
```
  /**
   * The event is fired after choices for radiogroup, checkbox and dropdown has been loaded from the RESTful service and before they are assign to the question. 
   * You may change the choices, before it was assign or disable/enabled make visible/invisible question, based on loaded results
   * <br/> question - the question where loaded choices are going to be assigned
   * <br/> choices - the loaded choices. You may change them to assign the correct one
   * <br> serverResult - a result that comes from the server as it is.
   */
  public onLoadChoicesFromServer: Event< (sender: SurveyModel, options: any) => any,  any
> = new Event<(sender: SurveyModel, options: any) => any, any>();
```
Here is the code for you needs:
```
  survey.onLoadChoicesFromServer.add(function(survey, options) {
    options.question.visible = options.choices.length > 0;
  });
```
We will likely make a new update tomorrow on Saturday.

Thank you,
Andrew
