### ISSUE TITLE
Formatting rating questions

### ISSUE THREAD

**Issue by bramson** [surveyjs/surveyjs#1069]
### Are you requesting a feature, reporting a bug or ask a question?

A question if it's already possible, and a feature request if it's not.

### What is the current behavior?

N/A

### What is the expected behavior?

I would like to change the formatting of rating questions via CSS.

### Other details

After much difficulty I was able to adjust (some aspects of) the matrix question based on a previous question (I still can't reduce the height of the rows properly...there is an effect, but it's not really reducing the height).  Now I'm trying to adjust the formatting of the rating question, and I can do some things (increase the padding below), but not the important things (change color of each button, set the width of each button, center the buttons, etc.)  

Maybe it's just a matter of not knowing the relevant CSS properties of the buttons, or my lack of deep knowledge of CSS.  But I couldn't find any documentation or examples of changing the button properties to use as a springboard.

The same thing applies to the other element types.  For example, I cannot set the margins or padding or width or any other property of the text or comment or html type elements.  I can't figure out how to center the "previous", "next", and "complete" buttons either.  Maybe it's all easy, but adapting what worked for the .matrixtable class doesn't work for any of these.

**Comment by tsv2013** [comment]
Could you please share your design - how the rating question should look like? And your CSS rules that don't work. We'll try to find a solution for you.

**Comment by bramson** [comment]
Here is what it currently looks like:
![ratingcurrent](https://user-images.githubusercontent.com/16698232/39346489-5a09f09e-4a29-11e8-90c6-986cb8bfe2c4.PNG)
The group of button should fill width 670px, center aligned, with buttons of equal width.  I would also like to (manually) color them individually.
I would also like the "Next" button to be centered and larger, and various other things like setting the width and alignment of a "comment" element to match.  

Since nothing I've done with CSS has any effect, I doubts it's helpful for you to see that, but ...
```
  if (options.question.isRequired) {
           classes.title = "sq-title this-title-required";
        }
        if (options.question.getType() === "matrix") {
            classes.root = "table table-striped matrixtable";
        }
        if (options.question.getType() === "text") {
            classes.root = "textFormatted";
        }
        if (options.question.getType() === "rating") {
            classes.root = "btn-lg btn-nice";
        }
```
where, for example, 
```
.textFormatted {
  width: 670px;
  margin-left: auto;
  margin-right: auto;
}
```
This sort of thing worked to set the required question text red, and to resize and center the matrixtables, but it doesn't do anything to the other elements I'm trying to format.

**Comment by tsv2013** [comment]
What platfrom (jQuery, knockout, Angular, React or Vue) and theme are you using?

**Comment by bramson** [comment]
Currently jQuery and bootstrap, but not for any particular reason.  I have no idea what the differences are yet.  I'm just starting to figure out how to get the data from the survey output into a file (i.e. how to save the JSON file or results).

**Comment by bramson** [comment]
Yes, that basically works, although centering using   margin-left: auto;   margin-right: auto;
doesn't work, with width and margin-left: #px; does the job for me in this case.  

Strangely, once I implemented that change for the rating question, my CSS settings for the text and comment types applied correctly to those elements.

Thank you again for your help!
