### ISSUE TITLE
Extend answers data

### ISSUE THREAD

**Issue by khaled-ansary** [surveyjs/surveyjs#1071]
### Are you requesting a feature, reporting a bug or ask a question?

feature or question

### What is the current behavior?
Currently, we are getting the answer data with the 'input field name' and its value. For example,

{"question1":"Mango" ,"question2":20, "question3":300}

### What is the expected behavior?
Is it possible to get also some extra data with it? For example, the id of the questions
[ 
  {"id": 1, "question1":"Mango" },
  {"id": 2, "question2": 20 },
  {"id": 3, "question3": 300 }
]

**Comment by andrewtelnov** [comment]
@khaled-ansary onComplete event you are getting survey.data. It is survey results in json format. You may always use our json to create your own and store your json in your database, like:
```
myData = [];
var id = 1;
for(var key in survey.data) {
  var item= { id: id };
  item.key = survey.data[key];
  myData.push(item);
  id++
}
```

Thank you,
Andrew
