### ISSUE TITLE
Feature Request: Checkbox and Radio classes configurable

### ISSUE THREAD

**Issue by cschra** [surveyjs/surveyjs#1074]
Hello,

I would like to do a Feature Request.
I am developing a survey using survey-vue and had difficulties accessing the checkbox and radiobox classes. As far as I know there is currently no possibility to change the "checkbox-material" or the "circle class into something else.
It would be great to make these classes also configurable through the css Object. Maybe as "decorator" or something like that.

My current solution is to "hardcode" the classes into the library which is not very satisfying.

Thank you very much in advance!

**Comment by dmitrykurmanov** [comment]
@cschra great! Thank You!
