### ISSUE TITLE
Is there a way to get page number in options.question?

### ISSUE THREAD

**Issue by testweird123** [surveyjs/surveyjs#1077]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question

I am using onValueChanged(sender,options) event. Is there a way i can get page number of the question being changed? I need to know the page number on which options.question is located. I know options.page gives me a page object. But how do i get the page number?

I am aware that survey.currentPageNo gives me page number of current page I am on.
But is there a way I can get page number in options.question?

Thank you.

#### Specify your
browser: Chrome
browser version: 64.0.3282.119
surveyjs platform (angular or react or jquery or knockout or vue): jquery
surveyjs version: 1.0.19

**Comment by andrewtelnov** [comment]
@testweird123 page.visibleIndex property, the visible index of the page. It has values from 0 to visible page count - 1.

Thank you,
Andrew

**Comment by testweird123** [comment]
Thank you.
