### ISSUE TITLE
New Feature Required

### ISSUE THREAD

**Issue by kmshelke** [surveyjs/surveyjs#1078]
We are using Mobile to capture the survey answers. When we want the images to be captured we are using the file upload option. 

Is it possible to get image capture option (with nice camera icon), if we are using mobile for survey?

**Comment by andrewtelnov** [comment]
@kmshelke Do you know any JavaScript library that does what you need?
We may make an example of using it or show you a way of implementing the custom widget using this library.

Thank you,
Andrew

**Comment by kmshelke** [comment]
Thanks Andrew.

We are using the Survey JS in our Cordova mobile app. Here the file upload option opens the Choose Files option. We want to open the phone’s camera. For this, we have tried to use the Cordova Camera plugin. We request you to provide this camera functionality as an inbuilt option in Survey JS. JavaScript Code that can be used as per the below reference document.

https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-camera/’

**Comment by tsv2013** [comment]
We have a well commented example how to create a cusom widget - https://plnkr.co/edit/HdnYE5?p=preview
You can use it in order to implement integration with Cordova plugin in your application
