### ISSUE TITLE
Dynamically hide/show choices items based on expression

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#1079]
UPD Here are two demos:
[Show/Hide choices in radiogroup/checkbox/dropdown](https://surveyjs.io/Examples/Library/?id=condition-choicesVisibleIf)
[Show/Hide individual items in radiogroup/checkbox/dropdown](https://surveyjs.io/Examples/Library/?id=condition-itemValueVisibleIf)

That is probably the most requested functionality right now.
We require writing the code to change the choices items in dropdown, radiogroup and checkbox questions.
There are many scenarios where our users expect this functionality out of the box, without writing JavaScript code.
There are two most popular scenario.
1) Show/hode all choices items based on selected values in checkbox
For example in the first question, you are asking your user to select cars he drives or drived in the past, in the second questioon select the car he likes the most, from those he selected in the first question.
The first question is checkbox, the second question is radiogroup. They have the same choices. The json should be look like:
```
{
 elements: [
  {type: "checkbox", name: "cars", choises: ["Audi", "BMW", "Mercedes", "Volkswagen"]}
  {type: "radiogroup", name: "bestcar", choises: ["Audi", "BMW", "Mercedes", "Volkswagen"],
  visibleIf: "{cars} notempty", choicesVisibleIf: "{cars} contains {item}"}
 ]
}
```
The second question is visible when at least one value is selected in the first question and it is already implemented.
What should be implemented as well: choicesVisibleIf. It will run against each choice item and the choice item is visible if a user selected the choice value in the first question.

2) Show/hide a particular choice item based on answers in other questions. 
It is a more general implementation. Every choice item should have a visibleIf property. If this property is not empty, then based on expression evaluation, the item is visible or invisible.
so the choice item can be 
```
choices: [
  {value: "contactbyphone", "Could we contact you by phone", visibleIf: "{phone} notemty"},
  {value: "contactbyemail", "Could we contact you by e-mail", visibleIf: "{email} notemty"},
]
```
The first item is visible if question "phone" is not empty and the second item is visible if question "email" is not empty.

Note: The item.visibleIf has a higher priority than choicesVisibleIf property.

**Comment by andrewtelnov** [comment]
Run-time is implemented.
Will work on design-time, Editor. Will try to make a general solution.

**Comment by andrewtelnov** [comment]
It was implemented in Editor. To remove this functionality in Editor, you must call:
`delete SurveyEditor.SurveyQuestionEditorDefinition.definition["itemvalues@choices"]`

**Comment by masciugo** [comment]
great feature, thanks. Consider that if I remove from the first question a car that I previously selected in the second question, the submitted data would still include in the second question the removed car

**Comment by andrewtelnov** [comment]
@masciugo Yes, we have noticed this issue late. Right after v1.021 release. We will fix [the issue](https://github.com/surveyjs/surveyjs/issues/1093).

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@masciugo FYI, I have just fixed the bug. New unit tests are added.

Thank you,
Andrew

**Comment by cent040** [comment]
@andrewtelnov Thanks it's work

**Comment by kaphert** [comment]
@andrewtelnov Is there an event fired when the visibility of the choices is changed something equal to `survey.onVisibilityChanged`? I couldn't find it in the docs or in the code itself. 

I am trying to let survey 'communicate' with another vue component. If for example two from the four radiobuttons are hidden I would like to notify the vue component about that update. I am currently doing this with an `onCurrentPageChanged` event because I have a multi step form. But it would be cool if I could use some event for this. Is there any available that I missed?

**Comment by andrewtelnov** [comment]
@szacchino You can do it by using custom function:
```js
function canShowDynamicChoice(params) {
    if (!params || params.length != 4) return true;
    const panelValue = params[0] || [];
    const questionName = params[1];
    const index = params[2];
    const choiceValue = params[3];
    for (let i = 0; i < panelValue.length; i++) {
        if (i == index) continue;
        if (panelValue[i][questionName] == choiceValue) return false;
    }
    return true;
}
Survey.FunctionFactory.Instance.register(
    'canShowDynamicChoice',
    canShowDynamicChoice
);

const json = {
    questions: [
        {
            type: 'paneldynamic',
            name: 'panel1',
            panelCount: 2,
            templateElements: [
                {
                    name: 'question1',
                    type: 'dropdown',
                    choicesVisibleIf:
                        "canShowDynamicChoice({panel1}, 'question1', {panelindex}, {item})",
                    choices: [
                        'Item 1',
                        'Item 2',
                        'Item 3'
                    ],
                }
            ],
        },
    ],
};

const survey = new Survey.Model(json);
```

Here is [the example](https://plnkr.co/edit/uzXxuuf8NIxajrXX).

Thank you,
Andrew

**Comment by ManasaGowda99** [comment]
Hi 
I'm adding question using 
Survey.Serializer.addProperty("question", { ....}

Can anyone help me to add choicesVisibleIf programatically to survey
without using Json
