### ISSUE TITLE
Dynamic question text

### ISSUE THREAD

**Issue by gongon2dotcom** [surveyjs/surveyjs#1080]
### Are you requesting a feature, reporting a bug or ask a question?
Bug/question

### What is the current behavior?
With complex question name (like guid), dynamic text on other question not render properly. 

#### Provide the test code and the tested page URL (if applicable)

Test code

`{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "text",
     name: "71933be1-7ff8-dfcf-ee69-8950f8f8a280",
     title: "What's' your name?"
    },
    {
     type: "text",
     name: "age",
     visibleIf: "{71933be1-7ff8-dfcf-ee69-8950f8f8a280} notempty",
     title: "Hi, {71933be1-7ff8-dfcf-ee69-8950f8f8a280}, how old are you?"
    }
   ]
  }
 ]
}`

https://embed.plnkr.co/3M5E4oZmqP18SI63VKOA/

### Specify your

* browser: Chrome
* browser version: Latest
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.20

**Comment by gongon2dotcom** [comment]
The problem seems to be the high dash '-', if i use underscore instead, seems to works properly. 

71933be1**_**7ff8**_**dfcf**_**ee69**_**8950f8f8a280 instead of 
71933be1**-**7ff8**-**dfcf**-**ee69**-**8950f8f8a280

**Comment by andrewtelnov** [comment]
@gongon2dotcom Definately a bug. I will work on the fix. I believe our parser recognize - as a minus. It should not since it is inside the brackets.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@gongon2dotcom Unit test has been added and fixed.
We will likely release a new minor update on this week. You may rebuild the library from the sources, the instruction in the readme.

Thank you,
Andrew

**Comment by gongon2dotcom** [comment]
Good Job! Thank you Andrew!
