### ISSUE TITLE
"Visible If" functionality not working when condition depends on checkbox question item

### ISSUE THREAD

**Issue by halexiev-hedgeserv** [surveyjs/surveyjs#1081]
### Are you requesting a feature, reporting a bug or ask a question?

Bug.

### What is the current behavior?

Question B depends on checkbox question A's first item to be checked in order to show.

Currently when first item of A is clicked - question B does not show up.

### What is the expected behavior?

Question B should show up when first item of A is clicked/checked.

### How would you reproduce the current behavior (if this is a bug)?

See json below and use in SurveyJS builder itself to test.

#### Provide the test code and the tested page URL (if applicable)

Test code

```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "checkbox",
     "name": "q1",
     "title": "Agree?",
     "choices": [
      {
       "value": "q1i1",
       "text": "Yes"
      }
     ]
    },
    {
     "type": "multipletext",
     "name": "q2",
     "visibleIf": "{q1} = 'q1i1'",
     "title": "Are you sure?",
     "items": [
      {
       "name": "Yes"
      },
      {
       "name": "No"
      }
     ]
    }
   ]
  }
 ]
}
```

**Comment by andrewtelnov** [comment]
@halexiev-hedgeserv "{q1} = ['q1i1']" or "{q1}  contains 'q1i1'"

Thank you,
Andrew

**Comment by halexiev-hedgeserv** [comment]
@andrewtelnov Thank you!
