### ISSUE TITLE
VueJs `isSinglePage` and `panelydynamic` not working in display mode

### ISSUE THREAD

**Issue by exnihilo-creatio** [surveyjs/surveyjs#1082]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

The current behavior shows an error in VueJs when using the `isSinglePage` property in combination with a survey that has a `paneldynamic` element.

The error is as follows:

```
[Vue warn]: Error in render: "TypeError: Cannot read property 'questionTitleLocation' of undefined"

found in

---> <SurveyRow> at src\vue\row.vue
       <SurveyPanel> at src\vue\panel.vue
         <SurveyPaneldynamic> at src\vue\paneldynamic.vue
           <SurveyElement> at src\vue\element.vue
             <SurveyRow> at src\vue\row.vue
               <SurveyPanel> at src\vue\panel.vue
                 <SurveyElement> at src\vue\element.vue
                   <SurveyRow> at src\vue\row.vue
                     <SurveyPage> at src\vue\page.vue
                       <Survey> at src\vue\survey.vue
                         <Root>
warn @ vue.js:597
```

```
vue.js:1743 TypeError: Cannot read property 'questionTitleLocation' of undefined
    at VueComponent.get (survey.vue.js:12794)
    at Watcher.get (vue.js:3140)
    at Watcher.evaluate (vue.js:3247)
    at VueComponent.computedGetter [as questionRootClass] (vue.js:3503)
    at Object.get (vue.js:1945)
    at survey.vue.js:24751
    at Proxy.renderList (vue.js:3699)
    at Proxy.render (survey.vue.js:24747)
    at VueComponent.Vue._render (vue.js:4535)
    at VueComponent.updateComponent (vue.js:2788)
```

### What is the expected behavior?

No errors, and the page is shown in a single page.

### How would you reproduce the current behavior (if this is a bug)?

See [VueJs](https://plnkr.co/edit/gHGgLknARHNCbfvot1ab?p=preview)

### Specify your

* browser: Chrome
* browser version: Chrome 66
* surveyjs platform: vuejs
* surveyjs version: 1.0.20

**Comment by andrewtelnov** [comment]
@exnihilo-creatio The same problem with other platform and the error are show for both modes: edit and display. We are working on the fix.

**Comment by andrewtelnov** [comment]
@exnihilo-creatio a new unit test has been added and the bug has been fixed.

Thank you,
Andrew
