### ISSUE TITLE
Event for switch between Designer and Test Survey tab

### ISSUE THREAD

**Issue by ltrtuan** [surveyjs/surveyjs#1084]
Are there any event for this ? Thanks

**Comment by andrewtelnov** [comment]
@ltrtuan You are probably looking for this event: [editor.onTestSurveyCreated](https://surveyjs.io/Documentation/Builder/?id=surveyeditor#onTestSurveyCreated)

Thank you,
Andrew

**Comment by ltrtuan** [comment]
Thanks
