### ISSUE TITLE
restful choices dropdown element with preloaded data not working

### ISSUE THREAD

**Issue by masciugo** [surveyjs/surveyjs#1089]
### Are you requesting a feature, reporting a bug or ask a question?

bug

### What is the current behavior?

when trying to render a survey with a restful choices dropdown element with preloaded data the field is not set

### What is the expected behavior?

to apply the data after loading the choices so that the preselected one can be found in the choices list

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/3Fa0z1ks3OYTYYGl8OJC?p=preview

**Comment by masciugo** [comment]
[this other example](https://plnkr.co/edit/MMlbjbMVBeZ4GmQ5Ylan?p=preview) is a more complicated case where there is a dependency between two dropdowns. Maybe this bug is not easy to solve but the way it will be solved should take in consideration this other use case as I think the cascade dropdowns application is one of the nicest that surveyJS let you smoothly implement. Don't hate me! Thanks

**Comment by andrewtelnov** [comment]
@masciugo It has been fixed. Unfortunately, I could not write unit tests since the bug is related how knockout binds to select element. However, I hope, I have reviewed all variants.

Thank you,
Andrew

**Comment by masciugo** [comment]
great my both examples work with 1.0.22. thank you

**Comment by masciugo** [comment]
@andrewtelnov I claimed victory too early... I cannot have the second example working with react https://plnkr.co/edit/MMlbjbMVBeZ4GmQ5Ylan?p=preview

**Comment by andrewtelnov** [comment]
@masciugo Ok, I will take a look.

Thank you,
Andrew

**Comment by masciugo** [comment]
Thank you @andrewtelnov. I'll wait for the next release

**Comment by masciugo** [comment]
while waiting for the release I noticed that if I add `storeOthersAsComment: false` the second dropdown show the hasOther input. Even if I also add `hasOther: false`.  Please have a look to the updated plunker. Does the fix cover this?

thank you

**Comment by andrewtelnov** [comment]
@masciugo The problem exists in the current developer version. I will try to fix it before release.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@masciugo Added the unit test and fixed it.

Thank you,
Andrew
