### ISSUE TITLE
Three elements in the same line causing alignment issue

### ISSUE THREAD

**Issue by bappajubcse05** [surveyjs/surveyjs#1090]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

Three elements in the same line causing alignment issue as attached

![capture](https://user-images.githubusercontent.com/34443377/39926018-7019074a-551d-11e8-9d65-e238570de9d0.JPG)

### What is the expected behavior?

Should be aligned.

### How would you reproduce the current behavior (if this is a bug)?

Execute the attached code in Survey Builder

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "dropdown",
     name: "question4",
     choices: [
      "item1",
      "item2",
      "item3"
     ]
    },
    {
     type: "dropdown",
     name: "question3",
     choices: [
      "item1",
      "item2",
      "item3"
     ]
    },
    {
     type: "dropdown",
     name: "question2",
     startWithNewLine: false,
     choices: [
      "item1",
      "item2",
      "item3"
     ]
    },
    {
     type: "dropdown",
     name: "question1",
     startWithNewLine: false,
     choices: [
      "item1",
      "item2",
      "item3"
     ]
    }
   ]
  }
 ]
}

```

### Specify your

* browser: IE 11/Edge, Google Chrome, Firefox
* browser version: 
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery
* surveyjs version: latest

**Comment by dmitrykurmanov** [comment]
We've fixe the bug. Fix will be available in the next minor update.

**Comment by bappajubcse05** [comment]
Thanks.
