### ISSUE TITLE
Imagepicker - selecting multiple images

### ISSUE THREAD

**Issue by langphil** [surveyjs/surveyjs#1092]
Question:
I am currently employing imagepicker as part of my survey. I am looking to allow the user to select multiple images, but cannot find a function within survey.js to achieve this.

Is this a feature that currently exists?

Thanks in advance

**Comment by andrewtelnov** [comment]
@langphil Unfortunately it doesn't exist. It is not hard to implement, but we do not have it out of the box.

Thank you,
Andrew

**Comment by langphil** [comment]
No problem. Just thought I'd check. Thank you!
