### ISSUE TITLE
Nested Paneldynamic with preloaded data

### ISSUE THREAD

**Issue by cinziasala** [surveyjs/surveyjs#1096]
### Are you requesting a feature, reporting a bug or ask a question?
bug

### What is the current behavior?
the panels in the nested paneldynamic do not reflect the ones in the survey data

### What is the expected behavior?
Each panel should show its own nested panels

### How would you reproduce the current behavior (if this is a bug)?
https://plnkr.co/edit/AGCnn0Up6BIbh2B82ihI?p=preview

**Comment by andrewtelnov** [comment]
@cinziasala I see the bug that the first nested panel should have one item, however it has three. Are you talking about this issue? Probably there is another issue that I may missed.

Thank you,
Andrew

**Comment by cinziasala** [comment]
@andrewtelnov You got exactly the point, the first nested panel shows 3 items instead of 1.

Thanks
Cinzia

**Comment by cinziasala** [comment]
Thank you so much Andrew!
We need to be scrupulous as we are going to propose surveyjs in a big clinical context dealing with high sensitive data. 
You're not getting rid of us so easily :)
Thanks
Cinzia
