### ISSUE TITLE
How to modify the default behaviour for error validation of an element

### ISSUE THREAD

**Issue by rekotc** [surveyjs/surveyjs#1100]
### Are you requesting a feature, reporting a bug or ask a question?

ask a question

### What is the current behavior?
The default behaviour for the error validation of an element is a pop over. 

### What is the expected behavior?
I would like to be able to change the default behaviour by adding a tooltip message under the element

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
You can do it via CSS customization. I've created a sample for you - https://plnkr.co/edit/FoOw5GjSZQjYq4js73gS?p=preview
Validation message is shown as tooltip on hover.
In more complex scenarios another (more complex) approach can be used.

**Comment by rekotc** [comment]
thank you very much for your help!!
