### ISSUE TITLE
Apply custom style to the Survey using JS instead of CSS class

### ISSUE THREAD

**Issue by soutot** [surveyjs/surveyjs#1102]
### Are you requesting a feature, reporting a bug or ask a question?
Feature

### What is the current behavior?
Reading the docs I could only find ways of styling using CSS classes

Example:
```
// styles.css
.myCustomClass {
  padding: 10px;
}

// MyComponent.js
const myCss = {
  navigation: {
    next: 'myCustomClass',
  },
};
<Survey.Survey model={model} css={myCss} />
```

### What is the expected behavior?
I'd like to be able to style Survey components using JS. It'd be great if all components were accessible like React Components, instead of accessing them from an object. So it could also be used with Styled Components

Example:
```
const styles = {
  next: {
    padding: 10,
  },
};

<Survey.Survey model={model} style={styles} />
```

Example of styled components:
```
const StyledSurvey = styled(Survey.Survey)`
  next {
    padding: 10px;
  }
`
<StyledSurvey model={model} />
```

Or even: 
```
const StyledSurvey = styled(Survey.Survey.next)`
  padding: 10px;
`
```

To solve it by now I had to add a wrapper and access the created classes using Styled Components this way:

```
const myCss = {
  navigation: {
    next: 'myCustomClass',
  },
};

const StyledSurvey = styled.div`
  .myCustomClass {
    padding: 20px;
  }
`;

<StyledSurvey>
  <Survey.Survey model={model} css={myCss} />
</StyledSurvey>
```

If I misunderstood any topic of the docs, please let me know

**Comment by tsv2013** [comment]
Yes, currently SurveyJS supports CSS customization via classes and through the code on the [onAfterRenderQuestion](https://surveyjs.io/Documentation/Library/?id=surveymodel#onAfterRenderQuestion) event.

Survey internal classes are accessible from the root Survey object. E.g. `Survey.SurveyPage` or `Survey.SurveyQuestionRating` and so on. You can get classes list from the `.d.ts` file or through the object inspector in the browser.

Do you mean this library - [styled-components](https://github.com/styled-components/styled-components)?
I think you can pass SUrveyJS components to the `styled` library. Can you try it?

**Comment by soutot** [comment]
Exactly. The current solution to customize the style is via CSS classes, which assumes I need to have a CSS stylesheet in my project. I think it would be great to also be able to customize it via JS, so we could write codes like this example I mentioned:

```
const styles = {
  next: {
    padding: 10,
  },
};

<Survey.Survey model={model} style={styles} />
```

I couldn't find a way to handle this.


The second point, regarding styled components, is that the components should accept and pass down ```className``` prop to the top component since Styled Components HOC adds a ```className``` to handle the given style. 
For example, if I apply styled components on ```Survey.Survey``` like this:
```
const StyledSurvey = styled(Survey.Survey)`
  padding: 10px;
`;

<StyledSurvey model={model} />
```
The missing ```className``` in the root div (same div that contains ```sv_main sv_default_css``` classes), prevents the style to be applied.

**Comment by tsv2013** [comment]
@soutot Thank you for clarification. I see your point. As far as I understand your suggestion will require rather large amount of work to be done with the react version of the SurveyJS library. That's why I don't think we'll implement it immediately. We'll keep it as a suggestion until it will be requested a lot.
We are open to the community and welcome any pull request with valuable code covered by unit tests.
