### ISSUE TITLE
Dropdown - dynamic load url

### ISSUE THREAD

**Issue by derchirurg** [surveyjs/surveyjs#1107]
### Are you requesting a feature, reporting a bug or ask a question?
question

### What is the current behavior?
I statically put the URL of the restful service in the url property of the question.

### What is the expected behavior?
Dynamically change the URL based on environment per code. Is it possible to change the question URL before rendering? I am using the angular wrapper.

### Specify your

* browser: all
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version: 1.0.22

**Comment by tsv2013** [comment]
You can change the url on the fly. Here is live sample - https://plnkr.co/edit/6zMefbPBq0Ywniy7mEDK?p=preview

**Comment by derchirurg** [comment]
This does not work properly. It first tries to get the data from the first URL, then it makes a second request to the updated URL. In my scenario, I get an error on the first call.
Is there a way to intercept the first call?

**Comment by tsv2013** [comment]
No, unfortunately there is now way to interrupt the first call. It is assumed that you are setting the correct URL in the options.
Can you set the correct URL in the survey JSON? Or do not to set choicesByUrl options in the beginning, but set them when you get the correct URL?

**Comment by derchirurg** [comment]
This will also be working, thanks.
I am trying the approach to parse the survey JSON and replace the url on serverside, because I must identify the question (no identifiying name).
Thanks for your help.
