### ISSUE TITLE
Is it possible to add dynamic matrix column wise

### ISSUE THREAD

**Issue by ashygk** [surveyjs/surveyjs#1109]
### Are you requesting a feature, reporting a bug or ask a question?
Question/Feature

### What is the current behavior?
Able to add dynamic matrix row wise. is there a possibility to add them column wise?

### What is the expected behavior?

Add the dynamic matrix questions column wise 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: google chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):  angular 5
* surveyjs version: 1.0.22

**Comment by andrewtelnov** [comment]
@ashygk column has properties: visibleIf and enableIf. The column will be still visible, but questions inside its cells may be invisible or disabled.
To get the column value of the current row you may use: {row.yourColumnName}

Thank you,
Andrew

**Comment by ashygk** [comment]
I really don't get it. Please find the below json.. The survey has a dynamic matrix.. I want the questions to be displayed left side in column wise (date, Amb device, amb distance...) and whenever I click add date, new columns should be added

{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "matrixdynamic",
     name: "Current Level of Function",
     titleLocation: "hidden",
     columns: [
      {
       name: "Date",
       title: "Date",
       cellType: "text",
       inputType: "date"
      },
      {
       name: "AmbDevice",
       title: "Amb Device",
       cellType: "dropdown"
      },
      {
       name: "AmbDistance",
       title: "Amb Distance",
       cellType: "text"
      },
      {
       name: "Amb Assistance\t",
       cellType: "dropdown"
      },
      {
       name: "W/C Mobility\t",
       cellType: "dropdown"
      },
      {
       name: "Bed Mobility\t",
       cellType: "dropdown"
      },
      {
       name: "Standing Tolerance\t",
       cellType: "text"
      },
      {
       name: "Stairs",
       cellType: "text"
      },
      {
       name: "Balance",
       cellType: "dropdown"
      },
      {
       name: "UE Strength\t",
       cellType: "text"
      },
      {
       name: "Cognitive Function\t",
       cellType: "comment"
      }
     ],
     choices: [
      1
     ],
     cellType: "comment",
     rowCount: 1,
     confirmDelete: true,
     addRowText: "Add Date +",
     removeRowText: "Remove"
    }
   ]
  }
 ],
 showQuestionNumbers: "off"
}

**Comment by andrewtelnov** [comment]
@ashygk Arh, you want to add a new column on "Add Date +".
It could be easily done via code 
```
var column = matrixquestion.addColumn("newColumn", "My new Column");
//set column properties
```
However, there is no a button for it.
Do you need to add rows as well? 

Thank you,
Andrew

**Comment by ashygk** [comment]
![1](https://user-images.githubusercontent.com/36975459/40326469-fa0dd950-5d04-11e8-827b-7ed2a5c9cdc6.PNG)
![2](https://user-images.githubusercontent.com/36975459/40326470-fa349b30-5d04-11e8-8b16-6e7dac6edbc0.PNG)

**Comment by ashygk** [comment]
i wanted to behave like this..where it add all columns when add date is selected..similar to dynamic matrix ..but to be displayed vertically

**Comment by andrewtelnov** [comment]
@ashygk We do not have this functionality yet.
So, you are using matrix dropdown and you want to add a column, where header has the cell question as well.
Will [PanelDynamic question](https://surveyjs.io/Examples/Library/?id=questiontype-paneldynamic) work for you for now?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@ashygk In fact, it is a matrix dynamic where columns and rows are swapt.
Theoretically, it can be just one property. Of course rendering will be changed completly.
In your UI, where do you have remove column button?

Thank you,
Andrew

**Comment by ashygk** [comment]
Under the last row for each column

**Comment by andrewtelnov** [comment]
@ashygk I have started to work on this functinality. I hope it will be available on the next week.
Could you please provide me with your json and ideally with sample data (couple rows), so I could make a good example?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@ashygk You may see the progress here: https://github.com/surveyjs/surveyjs/issues/1116

Thank you,
Andrew

**Comment by ashygk** [comment]
Thank you so much @andrewtelnov . I really appreciate your help in implementing this.

**Comment by ashygk** [comment]
Please use the below json for example:

{
pages: [
{
name: "page1",
elements: [
{
type: "matrixdynamic",
name: "Current Level of Function",
titleLocation: "hidden",
columns: [
{
name: "Date",
title: "Date",
cellType: "text",
inputType: "date"
},
{
name: "AmbDevice",
title: "Amb Device",
cellType: "dropdown"
},
{
name: "AmbDistance",
title: "Amb Distance",
cellType: "text"
},
{
name: "Amb Assistance\t",
cellType: "dropdown"
},
{
name: "W/C Mobility\t",
cellType: "dropdown"
},
{
name: "Bed Mobility\t",
cellType: "dropdown"
},
{
name: "Standing Tolerance\t",
cellType: "text"
},
{
name: "Stairs",
cellType: "text"
},
{
name: "Balance",
cellType: "dropdown"
},
{
name: "UE Strength\t",
cellType: "text"
},
{
name: "Cognitive Function\t",
cellType: "comment"
}
],
choices: [
1
],
cellType: "comment",
rowCount: 1,
confirmDelete: true,
addRowText: "Add Date +",
removeRowText: "Remove"
}
]
}
],
showQuestionNumbers: "off"
}

**Comment by andrewtelnov** [comment]
@ashygk FYI: The feature has been implemented.
Could you please provide a sample data, one two records, so our example would look good?

Thank you,
Andrew

**Comment by ashygk** [comment]
`{
pages: [
{
name: "page1",
elements: [
{
type: "matrixdynamic",
name: "Current Level of Function",
titleLocation: "hidden",
columns: [
{
name: "Date",
title: "Date",
cellType: "text",
inputType: "date"
},
{
name: "AmbDevice",
title: "Amb Device",
cellType: "dropdown"
},
{
name: "AmbDistance",
title: "Amb Distance",
cellType: "text"
},
{
name: "Amb Assistance\t",
cellType: "dropdown"
},
{
name: "W/C Mobility\t",
cellType: "dropdown"
},
{
name: "Bed Mobility\t",
cellType: "dropdown"
},
{
name: "Standing Tolerance\t",
cellType: "text"
},
{
name: "Stairs",
cellType: "text"
},
{
name: "Balance",
cellType: "dropdown"
},
{
name: "UE Strength\t",
cellType: "text"
},
{
name: "Cognitive Function\t",
cellType: "comment"
}
],
choices: [
1
],
cellType: "comment",
rowCount: 1,
confirmDelete: true,
addRowText: "Add Date +",
removeRowText: "Remove"
}
]
}
],
showQuestionNumbers: "off"
}`

**Comment by andrewtelnov** [comment]
@ashygk I have got the survey json :) I would love to have a json result for one-two columns.
survey.data = {"Current Level of Function" : [
{"AmbDevice": "something",...},
{...}
]}
And there is no choices for amdDevices and other dropdown in your json :(

Thank you,
Andrew

**Comment by ashygk** [comment]
Survey Result: {"Current Level of Function":[{"Date":"2018-05-01","AmbDistance":"34","Amb Assistance\t":"D","Standing Tolerance\t":"high","UE Strength\t":"no ","Cognitive Function\t":"no function"},{"Date":"2018-05-09","AmbDistance":"23","Amb Assistance\t":"MAX","Standing Tolerance\t":"low","UE Strength\t":"yes","Cognitive Function\t":"blah blah"}]}

**Comment by ashygk** [comment]
surveydata : `{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "matrixdynamic",
     name: "Current Level of Function",
     titleLocation: "hidden",
     columns: [
      {
       name: "Date",
       title: "Date",
       cellType: "text",
       inputType: "date"
      },
      {
       name: "AmbDistance",
       title: "Amb Distance",
       cellType: "text"
      },
      {
       name: "Amb Assistance\t",
       cellType: "dropdown",
       choices: [
        "D",
        "MAX",
        "MOD",
        "MIN"
       ]
      },
      {
       name: "Standing Tolerance\t",
       cellType: "text"
      },
      {
       name: "UE Strength\t",
       cellType: "text"
      },
      {
       name: "Cognitive Function\t",
       cellType: "comment"
      }
     ],
     choices: [
      1
     ],
     cellType: "comment",
     rowCount: 1,
     confirmDelete: true,
     addRowText: "Add Date +",
     removeRowText: "Remove"
    }
   ]
  }
 ],
 showQuestionNumbers: "off"
}`

**Comment by andrewtelnov** [comment]
@ashygk The release is out. Here is [the demo](https://surveyjs.io/Examples/Library/?id=questiontype-matrixdynamic-vertical)

Thank you,
Andrew

**Comment by ashygk** [comment]
Thank you @andrewtelnov

**Comment by ashygk** [comment]
Hi, We have updated our applications, package.json to point to survey-angular: "1.0.25" to include the above functionality.
The survey doesn't get loaded and error pops up while rendering when Survey.SurveyNG.render is called.
Error below: 
core.js:1448 ERROR TypeError: Cannot read property 'children' of null
    at Object.render (survey.angular.js:1268)
    at Function.SurveyNG.render (survey.angular.js:8121)
    at DecisionTreeComponent.generateSurveyFromDefinition (decision-tree.component.ts:122)
    at SafeSubscriber.eval [as _next] (decision-tree.component.ts:96)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:240)
    at SafeSubscriber.next (Subscriber.js:187)
    at Subscriber._next (Subscriber.js:128)
    at Subscriber.next (Subscriber.js:92)
    at MapSubscriber._next (map.js:85)
    at MapSubscriber.Subscriber.next (Subscriber.js:92)

**Comment by ashygk** [comment]
SurveyData : `{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "matrixdynamic",
     name: "CurrentLevelOfFunction",
     titleLocation: "hidden",
     columns: [
      {
       name: "Date",
       cellType: "text",
       inputType: "date"
      },
      {
       name: "AmbDevice",
       title: "Amb Device",
       cellType: "dropdown",
       choices: [
        {
         value: "StandardWalker",
         text: "Standard Walker"
        },
        "WheelChair",
        {
         value: "QuadCane",
         text: "Quad Cane"
        },
        "Crutches",
        "Cane"
       ]
      },
      {
       name: "AmbDistance",
       title: "Amb Distance",
       cellType: "text"
      },
      {
       name: "AmbAssistance",
       title: "Amb Assistance",
       cellType: "dropdown",
       choices: [
        "IND",
        "MOD",
        "MAX",
        "MIN",
        "DEP",
        "SBA",
        "I"
       ]
      },
      {
       name: "W/CMobility",
       title: "W/C Mobility",
       cellType: "dropdown",
       choices: [
        "IND",
        "MOD",
        "MAX",
        "MIN",
        "DEP",
        "SBA",
        "I"
       ]
      },
      {
       name: "StandingTolerance",
       title: "Standing Tolerance",
       cellType: "text"
      },
      {
       name: "BedMobility",
       title: "Bed Mobility",
       cellType: "dropdown",
       choices: [
        "IND",
        "MOD",
        "MAX",
        "MIN",
        "DEP",
        "SBA",
        "I"
       ]
      },
      {
       name: "ToiletTransfer",
       title: "Toilet Transfer",
       cellType: "dropdown",
       choices: [
        "IND",
        "MOD",
        "MAX",
        "MIN",
        "DEP",
        "SBA",
        "I"
       ]
      },
      {
       name: "ROM",
       cellType: "text"
      },
      {
       name: "FineMotor",
       title: "Fine Motor",
       cellType: "text"
      }
     ],
     columnsLocation: "vertical",
     choices: [
      1,
      2,
      3,
      4,
      5
     ],
     rowCount: 1,
     addRowLocation: "top",
     addRowText: "ADD CLOF +"
    }
   ]
  }
 ],
 showTitle: false,
 showQuestionNumbers: "off",
 questionErrorLocation: "bottom"
}`

**Comment by andrewtelnov** [comment]
@ashygk Unfortunately, I could not reproduce it :( 
Here is your [json in plunker, angular, v1.0.25](https://plnkr.co/edit/vL6Mv1Yb8DC98rAS99lL?p=preview)

Thank you,
Andrew

**Comment by ashygk** [comment]
We have moved directly from survey-angular: 1.0.0 to 1.0.25 directly.. Is there any dependency?

**Comment by andrewtelnov** [comment]
@ashygk the current version successful work with json created for the first release, more than two years ago.
Do you use any events?
It is very likely the bug, but we have to reproduce it on our side to be able to fix it.

Thank you,
Andrew

**Comment by ashygk** [comment]
The json is created with the online builder, which is using 1.0.25

Yes, we are using events for onComplete, onAfterRenderQuestion, onTextMarkdown, onUpdateQuestionCssClasses. That is all

**Comment by andrewtelnov** [comment]
Could you please comment onAfterRenderQuestion, and then onTextMarkdown?

Thank you,
Andrew

**Comment by ashygk** [comment]
Tried, but no luck

**Comment by ashygk** [comment]
As per my analysis, function render(vnode, parent, callback)  in the survey.angular.js, the parent is null which is why there is no html collection in the children and raising error.
`div#Current Problem
accessKey
:
""
align
:
""
assignedSlot
:
null
attributeStyleMap
:
StylePropertyMap {size: 0}
attributes
:
NamedNodeMap {0: id, id: id, length: 1}
autocapitalize
:
""
baseURI
:
"https://blah.blah.us:4200/"
childElementCount
:
0
childNodes
:
NodeList []
children
:
HTMLCollection []
classList
:
DOMTokenList [value: ""]
className
:
""
clientHeight
:
0`

**Comment by ashygk** [comment]
The above is for different survey "Current Problem" which has parent as above

**Comment by andrewtelnov** [comment]
@ashygk Could you try to use non minimized/developer version and copy here the stack in our library. So we can get some ideas?

Thank you,
Andrew

**Comment by ashygk** [comment]
Not sure, just  happens when the survey has this new functionality..as all the other surveys are working fine

**Comment by ashygk** [comment]
the typeof elementid is still string.. there is an issue with document.getelementbyid(elementid), not sure why it is returning null.

```
var SurveyNG = /** @class */ (function () {
    function SurveyNG() {
    }
    SurveyNG.render = function (elementId, props) {
        var element = typeof elementId === "string"
            ? document.getElementById(elementId)
            : elementId;
        __WEBPACK_IMPORTED_MODULE_2_react_dom__["render"](__WEBPACK_IMPORTED_MODULE_1_react__["createElement"](__WEBPACK_IMPORTED_MODULE_4__react_reactSurvey__["a" /* Survey */], __WEBPACK_IMPORTED_MODULE_0_tslib__["a" /* __assign */]({}, props)), element);
    };
    return SurveyNG;
}());
```

**Comment by andrewtelnov** [comment]
You are saying it works for other jsons. It doesn’t make sense to me :(

Thank you,
Andrew

**Comment by ashygk** [comment]
Yes, it works for other jsons. Not just this one. 
![capture](https://user-images.githubusercontent.com/36975459/41247039-6604c3e4-6d72-11e8-8284-ed3a940ba389.PNG)

**Comment by andrewtelnov** [comment]
You may pass HtmlElement into the Survey constructor. Could you try it please?

Thank you,
Andrew

**Comment by ashygk** [comment]
Not sure which survey constructor you are talking about

**Comment by andrewtelnov** [comment]
You may pass element Id or element itself. If it is an element, then there is no need for calling getElementById.

**Comment by ashygk** [comment]
We are not calling it..it is internally being called in the survey.angular.js render function.

We are just making call Survey.SurveyNG.render(this.surveyName, { model: this.survey, css: cssConfig }); from our application.. that's it

**Comment by andrewtelnov** [comment]
@ashygk Sorry for being confusing. I'm talking about this code:
```
  let htmlEl = document.getElementById("surveyElement")
  //raise error if htmlEl is null
  Survey.SurveyNG.render(htmlEl, {
    model: survey
  });
```
Here is the [updated plunker](https://plnkr.co/edit/vL6Mv1Yb8DC98rAS99lL?p=preview)

Thank you,
Andrew

**Comment by ashygk** [comment]
Copied the  above snippet. htmlEl is returning null for this survey

**Comment by andrewtelnov** [comment]
@ashygk Then the problem somewhere in your code. SurveyJS starts to work after the render function is called. You just pass into the render function an invalid argument. 
We should do a better job and raise an error that renderedElement parameter is invalid. I will add it into our TODO list.

Thank you,
Andrew

**Comment by ashygk** [comment]
Ok. Also, i tried to include a dynamic matrix (vertical columns) in a separate survey. the survey still has columns showing horizontally.

**Comment by ashygk** [comment]
![capture2](https://user-images.githubusercontent.com/36975459/41256779-3b5c2858-6d90-11e8-95eb-67cba659e8ec.PNG)
![capture](https://user-images.githubusercontent.com/36975459/41256780-3b70dba4-6d90-11e8-85d6-2beea2b729f2.PNG)

**Comment by ashygk** [comment]
And, addRowLocation is set to top, but still is at the bottom

**Comment by andrewtelnov** [comment]
@ashygk I am afraid you are using the old version of SurveyJS for some reason on this page. Could you please recheck it? Unfortunately, I do not see any other reason.

Thank you,
Andrew

**Comment by ashygk** [comment]
Does newer version of surveyjs need knockout? how do i install it in my angular 5 app?

**Comment by andrewtelnov** [comment]
@ashygk You do not need knockout, it is already inside the library.
Have you tried our [quick start repo for angular](https://github.com/surveyjs/surveyjs_angular_quickstart)
and for [angular cli](https://github.com/surveyjs/surveyjs_angular_cli)

Thank you,
Andrew

**Comment by ashygk** [comment]
Was this made mandatory after surveyjs 1.0.0?

**Comment by andrewtelnov** [comment]
@ashygk Yes, we moved from pReact to knockout after v1.0.0 release, during a lot issues with pReact. 
However, knockout and before pReact has been included into the library and you should not see any difference.

Thank you,
Andrew

**Comment by ashygk** [comment]
Included "types": [ "knockout" ] in tsconfig.app.json. Works now.  I see the new functionality. 
You can close this thread :)

**Comment by andrewtelnov** [comment]
@ashygk I just talked to the guys. You are right. Angular2+ requires knockout typings. I did not know about it.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@ashygk We have added the [following issue](https://github.com/surveyjs/surveyjs/issues/1171)

Thank you,
Andrew

**Comment by Huuvinh94** [comment]
Hi @andrewtelnov 
survey.onValueChanged.add((sender, options) => {
.....
listMatrix.forEach((item, index) => {
                sender.getQuestionByName(name).**addColumn**('matrix-col-' + index, item.value);
                sender.getQuestionByName(name).columns[index].**setPropertyValue**('visibleIf', item.visibleIf); // from type text **Ex: ( {nameTex} = "item.value" )**
                sender.getQuestionByName(name).columns[index].choices = [''];
                sender.getQuestionByName(name).columns[index].cellType = 'checkbox';
              });
})
I am create question with type matrixdropdown and add column dynamic (function addColumn()), but when i add function setPropertyValue() then not working :(
Please help me!
