### ISSUE TITLE
Confirm form data submission in surveyModel.onComplete

### ISSUE THREAD

**Issue by mkgn** [surveyjs/surveyjs#1113]
I am using latest surveyjs. I was wondering whether it's possible to show a confirmation to user so that he can confirm sending data to server or not. 

        surveyModel.onComplete.add(result => {
               if (confirm)
                              send data to server
               else
                              just wait.
        });

When I try to show a confirmation within this method it still completes the survey. It would be nice to be able to show a confirmation before sending data to server.

**Comment by mkgn** [comment]
I see...
I think it is quite important to have a built in event such as onCompleteClicked() so that user can handle that event, do their thing (show confirmation etc...) and then decide whether to send the data to server or not.

**Comment by mkgn** [comment]
Is it possible for me to hide the complete button? What I am trying to do is have my own [complete] button. When it is pressed, i will get the confirmation from the user and if he want to proceed do the form submission.

I am trying to catch the [complete] button in the onAfterRenderPage method using survey.isLastPage. 
this.surveyModel.onAfterRenderPage.add(result => {
            console.log(result.isLastPage);
            if (result.isLastPage) {
                var completeBtn = document.getElementsByClassName("sv_complete_btn");
                console.log(completeBtn.length);
            }
        });

At this point the button doesn't seem to be there?

**Comment by andrewtelnov** [comment]
@mkgn It has been just implemented, https://github.com/surveyjs/surveyjs/issues/1242

Thank you,
Andrew
