### ISSUE TITLE
Panel Dynamic panelsState property with preloaded data

### ISSUE THREAD

**Issue by cinziasala** [surveyjs/surveyjs#1115]
### Are you requesting a feature, reporting a bug or ask a question?
ask a question

### What is the current behavior?
In "paneldynamic", when the panelsState is set to "collapsed" preloaded panels remain expanded.

### What is the expected behavior?
I would like to see the dynamic panels collapsed.

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/kDKrgKMWDxQVUNhdnj5W?p=preview

**Comment by dmitrykurmanov** [comment]
We've fixed the issue, fix will be available in the next minor.

**Comment by cinziasala** [comment]
Thanks really a lot!
