### ISSUE TITLE
SurveyJS looks different with bootstrap 4

### ISSUE THREAD

**Issue by derchirurg** [surveyjs/surveyjs#1121]
### Are you requesting a feature, reporting a bug or ask a question?
bug

### What is the current behavior?
There is a big difference between bootstrap 3 (3.3.7) and 4 (4.1.1). 
Please see the provided plunks.

### What is the expected behavior?
Should be look the same, especially the progress bar.

#### Provide the test code and the tested page URL (if applicable)

bootstrap 3.3.7: https://plnkr.co/edit/x5IS11uZnKpOcBwV2hGj?p=preview
bootstrap 4.1.1: https://plnkr.co/edit/AEC6DsoPGzHAmtzRRWif?p=preview

### Specify your

* browser: chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular / jquery
* surveyjs version: 1.0.23

**Comment by tsv2013** [comment]
In case of bootstrap theme SurveyJS uses a minimum of customizations to allow to use native bootstrap styling. So BS4 looks like it should. Of course our BS4 support can have some bugs and we'll fix them. Lack of space between progress bar and title is defenitely one of them.

**Comment by derchirurg** [comment]
This would be great if you can fix it. I implemented a workaround in setting .progress a margin.

**Comment by tsv2013** [comment]
I've created the separate issue concerning space between the top progress bar and the title - #1122

**Comment by tsv2013** [comment]
#1122 Is fixed. Fix will be available in the nearest update.
