### ISSUE TITLE
checkboxes returned values

### ISSUE THREAD

**Issue by masciugo** [surveyjs/surveyjs#1124]
### Are you requesting a feature, reporting a bug or ask a question?

question

### What is the current behavior?

when submit a survey with a checkbox question their returned values as string even if they were numbers in choices. If I save the response and try to populate the survey with the saved data it works but I wonder if that's correct. I mean If I build my data not by submitting the survey but by other mean using the available choices (numbers) and try to populate the survey those number are ignored. 

### What is the expected behavior?

If my choices are number I expect numbers in survey result. If they are string I expect string as answer

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/mk6F9vdyi8XPR17wwUwD?p=preview

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
Checkbox value attribute returns string (check e.g. this article - https://www.w3schools.com/jsref/prop_checkbox_value.asp)
That's why we got array of strings as a result mo matter what kind of values were passed.

Values can be transformed in the [onComplete](https://surveyjs.io/Documentation/Library/?id=surveymodel#onComplete) event handler.

**Comment by masciugo** [comment]
ok fine. But I still think that what you have in choices is what you save in the backend. So my rule of thumb will be: always use string as choices values in checkbox question. thank you
