### ISSUE TITLE
clearIf welcomed

### ISSUE THREAD

**Issue by masciugo** [surveyjs/surveyjs#1125]
### Are you requesting a feature, reporting a bug or ask a question?

question

### What is the current behavior?

If I have a dependency between questions I can use `visibleIf` along with `"clearInvisibleValues": "onHidden"` in order to reset a value when its question gets invisible. What if I need to reset the value but I don't want to hide the dependent question? 

### What is the expected behavior?

I imagine a property called `clearIf` which gets an expression as a value. Or maybe there is any other way to do this?

**Comment by tsv2013** [comment]
What do you think about the [expression](https://surveyjs.io/Examples/Library/?id=questiontype-expression&platform=jQuery&theme=default) question? Can it be helpful for you?

Can you share more details about your scenario? Probably we could find a suitable solution for you.

**Comment by masciugo** [comment]
As far as I know in Expression question the value is always calculated, you cannot alter it. Correct? 

I'd need something like a validation that is an expression that check the value and clear it too if necessary. I guess I could do it by adding a callback to the onValueChanged event which eventually clear the value but I was exploring if my specific need (simple conditional clear) may have experienced by someone else

**Comment by andrewtelnov** [comment]
@masciugo There is now expression validator. It doesn't clear the value, but it doesn't allow to go futher if expression doesn't return true.

Thank you,
Andrew

**Comment by masciugo** [comment]
ok, I'll try it thank you
