### ISSUE TITLE
Hide questions in display mode

### ISSUE THREAD

**Issue by derchirurg** [surveyjs/surveyjs#1129]
### Are you requesting a feature, reporting a bug or ask a question?
question

### What is the current behavior?
Is it possible to hide specific questions in display mode?

### What is the expected behavior?
Hide specific questions in display mode.

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version: 1.0.22

**Comment by andrewtelnov** [comment]
@derchirurg Please review [help this topic](https://surveyjs.io/Documentation/Library/#visibility)
You will have to write the custom function and register it:
```
function isDisplayMode() {
 return this.survey && this.survey.isDisplayMode;
}
Survey.FunctionFactory.Instance.register(“isDisplayMode”, isDisplayMode);
```
You may use it now in expression: `"isDisplayMode() = true"`

Thank you,
Andrew

**Comment by derchirurg** [comment]
Works, thanks
