### ISSUE TITLE
 Selecting other option with no input from drop down list and no error message is displayed

### ISSUE THREAD

**Issue by KLC215** [surveyjs/surveyjs#1130]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a  question

### What is the current behavior?
1. Select an option from drop down list with question type **matrixdynamic** 
2. Click next button and go to next page
3. Go back previous page
4.  Then selecting **other option with no input** from drop down list and no error message is displayed 
![suverybugdemo](https://user-images.githubusercontent.com/15123751/40602684-13cd1022-628c-11e8-8a5c-6627c2abcaa3.gif)

### What is the expected behavior?
1. Select other option from drop down list with question type **matrixdynamic** 
2. Click next button and go to next page
3. Go back previous page
4. Then selecting other option with no input from drop down list and error message is displayed 

### Specify your

* browser: Google Chrome
* browser version:  Version 66.0.3359.181 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): survey-react with ant design custom widget
* surveyjs version: 1.0.20

**Comment by andrewtelnov** [comment]
@KLC215 I have just tried without custom widget and it works as expected.
Could we get your custom-widget? Right now we can't reproduce the issue.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@KLC215 That is good. Let me try it on the current release version. I was trying to use the developers version. I will be back.

**Comment by KLC215** [comment]
@agelospanagiotakis  Thank you

**Comment by andrewtelnov** [comment]
@KLC215 Here [it is](https://plnkr.co/edit/Vir8xX6EClyPrWB3lrtq?p=preview)

Thank you,
Andrew

**Comment by KLC215** [comment]
Thank you again, Waiting for good news :)

**Comment by andrewtelnov** [comment]
@KLC215 The issue has been fixed. We will likely release a new minor update tomorrow.

Thank you,
Andrew

**Comment by KLC215** [comment]
It works like a charm. Thanks @andrewtelnov :)

**Comment by andrewtelnov** [comment]
Great!
