### ISSUE TITLE
File question - define file type filter

### ISSUE THREAD

**Issue by derchirurg** [surveyjs/surveyjs#1131]
### Are you requesting a feature, reporting a bug or ask a question?
feature

### What is the current behavior?
Questiontype file does not accept a file type filter.

### What is the expected behavior?
I want to select specific file types, like e.g. .pdf

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version: 1.0.22

**Comment by tsv2013** [comment]
According to the https://www.w3schools.com/tags/att_input_accept.asp we can assign to the `accept` properties only mime type values
We can create a set of predefined settings: images, audio, pdf, and allow users to pass their custom strings in an event handler
Will it be ok for you?

**Comment by derchirurg** [comment]
Yes, this would be ok.
But you do not have to use mime-types, you can also use file extensions like .pdf. See chapter "Attribute Values" of your linked source.
If I can pass .pdf|.docx it would be ok.

**Comment by tsv2013** [comment]
Thank you for the comment @derchirurg 
You will be able to pass any string to the `accept` attribute

**Comment by tsv2013** [comment]
I've added the acceptedTypes attribute. It will be available in the nearest update.

**Comment by derchirurg** [comment]
Thank you. Will it also be implemented in the builder?

**Comment by tsv2013** [comment]
@derchirurg Yes, it should be available in the Builder's property grid as a text field
