### ISSUE TITLE
Display mode does not work with tagbox widget

### ISSUE THREAD

**Issue by wysoki89** [surveyjs/surveyjs#1132]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

Tagbox dropdown is selectable when mode === 'display'

### What is the expected behavior?

Tagbox dropdown shoud not be selectable when mode === 'display'

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/ICfNz8AUW9CaMboVRXV5?p=preview

**Comment by tsv2013** [comment]
Probably this issue should be created in this repo - https://github.com/surveyjs/widgets/
I've cloned this issue into the https://github.com/surveyjs/widgets/issues/56

**Comment by wysoki89** [comment]
ok, thanks! I guess this https://github.com/surveyjs/widgets/ is the right repo
