### ISSUE TITLE
How to Hide Field maxTimeToFinishPage?

### ISSUE THREAD

**Issue by SammaniPalan** [surveyjs/surveyjs#1136]
### Are you requesting a feature, reporting a bug or ask a question?
question

### What is the current behavior?

There is a field calls maxTimeToFinishPage in the right pane of the editor
![image](https://user-images.githubusercontent.com/20948377/40672772-6a64372e-638d-11e8-8d31-f86265739810.png)

### What is the expected behavior?

Customer wants to hide that property. Can you please guide me how to hide that field?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version:Latest

**Comment by andrewtelnov** [comment]
@SammaniPalan Please read "Removing or Hiding properties" topic [here](https://surveyjs.io/Documentation/Builder/#addproperties)

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Please use [this repo](https://github.com/surveyjs/editor) to ask questions about Editor.

Thank you,
Andrew

**Comment by SammaniPalan** [comment]
Thank you , it solved my issue
