### ISSUE TITLE
cannot use visibleIf and clearInvisibleValues = "onHidden" together in matrixdynamic with preloaded data

### ISSUE THREAD

**Issue by masciugo** [surveyjs/surveyjs#1137]
### Are you requesting a feature, reporting a bug or ask a question?

bug maybe

### What is the current behavior?

cannot use `visibleIf` and `clearInvisibleValues = "onHidden"` together in matrixdynamic with preloaded data 

### What is the expected behavior?

use `visibleIf` and `clearInvisibleValues = "onHidden"` together

### How would you reproduce the current behavior (if this is a bug)?

you need to comment out `clearInvisibleValues = "onHidden"` to prepopulate the survey

https://plnkr.co/edit/8AK8XcQeHz7SAYMhe1xf?p=preview

**Comment by tsv2013** [comment]
Fix will be available in the nearest update
