### ISSUE TITLE
Custom numbering of questions that appears based on conditions

### ISSUE THREAD

**Issue by mradzivonenka** [surveyjs/surveyjs#1138]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
Please, check the images attached. I have 2 questions (number 1 and number 2) and when selecting "Yes" at first - 4 more questions will appear. And question that was at number 2 will become number 6

### What is the expected behavior?
Can you please suggest, how can i achieve the behavior when question that will appear will have numbers like "1a", "1b" and numbers of basic questions will not be changed 

![image](https://user-images.githubusercontent.com/12149038/40709938-0b7180fa-6400-11e8-8bf9-b6bd3667f762.png)
![image](https://user-images.githubusercontent.com/12149038/40710007-37a9a71a-6400-11e8-9ff0-86cc9e0e8c27.png)

The obvious way is to add numbers to title and disable surveyjs numbers of question. But probably there is another approach.

**Comment by mradzivonenka** [comment]
i ended up with mentioned custom numering solution and will close my question

**Comment by tsv2013** [comment]
You can add a custom property and fill the numbers.
I've created a sample for you - https://plnkr.co/edit/rOXzcY4kRKczHuDHLn8U?p=preview

**Comment by mradzivonenka** [comment]
Very nice! Thank you very much!

**Comment by sem1colon** [comment]
> You can add a custom property and fill the numbers.
> I've created a sample for you - https://plnkr.co/edit/rOXzcY4kRKczHuDHLn8U?p=preview

This doesn't work with the latest version.
