### ISSUE TITLE
Wrong context during visibleIf calculation for template elements of matrixdynamic question contain another matrixdynamic question

### ISSUE THREAD

**Issue by KLC215** [surveyjs/surveyjs#1139]
### Are you requesting a feature, reporting a bug or ask a question?

Maybe a bug.

### What is the current behavior?

![suvery-display-problem](https://user-images.githubusercontent.com/15123751/40712448-59763c84-6430-11e8-9f0a-4c3c9146f384.gif)

The template elements of matrixdynamic question contain another matrixdynamic question. The panel cannot be added correctly.

### What is the expected behavior?

The panels should be added smoothly and dynamically.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: [https://plnkr.co/edit/phT6BWEIfUvxjzzLCTqV?p=preview](https://plnkr.co/edit/phT6BWEIfUvxjzzLCTqV?p=preview)

### Specify your
* surveyjs platform (angular or react or jquery or knockout or vue): survey-react
* surveyjs version: 1.0.24

**Comment by Jojo109** [comment]
I also struggle this kind of problem. Is there any update for this question? Thanks.

**Comment by tsv2013** [comment]
@KLC215 , @Jojo109  we are working on the problem

**Comment by KLC215** [comment]
Thanks @tsv2013

**Comment by KLC215** [comment]
Thanks @tsv2013
