### ISSUE TITLE
Multiple instance of survey model from survey-react in one application 

### ISSUE THREAD

**Issue by Jojo109** [surveyjs/surveyjs#1143]
### Are you requesting a feature, reporting a bug or ask a question?
question
I found that there is some issues when there are multiple instance of survey model in one application when using survey-react.
There are some rough code in following.
let surveyModel1 = new Survey.Model(json1);
ReactDOM.render(
          <Survey.Survey
            model={surveyModel1 }
          />,
          document.getElementById('survey1')
        );
      

let surveyModel2= new Survey.Model(json2);
ReactDOM.render(
          <Survey.Survey
            model={surveyModel2}
          />,
          document.getElementById('survey2')
        );
      

I found that two survey model can interact each other and also the whole application will perform strangely.
Is there a proper way when using multiple survey instance in one application?

**Comment by tsv2013** [comment]
Can you specify - what exact problemes did you face? To start check and fix them.

**Comment by Jojo109** [comment]
Thanks @tsv2013 . Let me ask in this way first, is it acceptable for multiple survey model instance existing at the same time in one application?

**Comment by tsv2013** [comment]
Sure, multiple instances of the surveyjs model should work ok. E.g. in the SurveyJS builder we are using two instances simultaniously - one on the design surface, another - in the "Test Survey" tab.

**Comment by Jojo109** [comment]
Thanks @tsv2013 . However, for my case, i create multiple instances of the surveyjs model in one react component. Is it workable for multiple instances of the surveyjs model existing in same js file?

**Comment by tsv2013** [comment]
It should work

**Comment by Jojo109** [comment]
Thanks @tsv2013 . Let me review the code first.
