### ISSUE TITLE
Can we get an ES6 SFC VueJS example?

### ISSUE THREAD

**Issue by humblecoder** [surveyjs/surveyjs#1144]
Can we get an ES6 SFC VueJS example -- complete with appropriate `imports` and `component` specifications?

When I type
```
import * as SurveyVue from 'survey-vue'
...
...
components:{
    'survey': SurveyVue.Survey
  }
```
I receive:
```"TypeError: Cannot read property 'css' of undefined"```

If I simply import without declaring components then I receive an error stating, of course, that I didn't declare a `survey` component.

* browser:  Chrome
* browser version: 66.0.3359.181 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version: 1.0.24

**Comment by andrewtelnov** [comment]
@humblecoder Have you tried our [vue quick start repo](https://github.com/surveyjs/surveyjs_vue_quickstart)?

Thank you,
Andrew

**Comment by humblecoder** [comment]
Thanks!
