### ISSUE TITLE
Bug custom classes for rating

### ISSUE THREAD

**Issue by vnanhtuan** [surveyjs/surveyjs#1145]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug

### What is the current behavior?

When I use survey custom CSS function in rating, I want to add my cssclass in to HTML.
I followed this link: [https://surveyjs.io/Examples/Library/?id=survey-cssclasses&platform=Angular2&theme=default].
But I can add cssclass to label. Please see file attached below

### What is the expected behavior?
I want my cssclass to HTML

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here
survey.onUpdateQuestionCssClasses.add(function (survey, options) {
            const classes = options.cssClasses;
            const question = options.question;
            console.log('options', options);
            console.log('classes', classes);

            classes.root = 'sv_q_rating test-root';
            classes.item = 'sv_q_rating_item test-item';
            classes.itemText = 'sv_q_rating_item_text test-itemtext';
            classes.label = 'sv_q_rating_item test-label';
        });
![capture](https://user-images.githubusercontent.com/10513517/40964766-22a79d7e-68d6-11e8-8176-de821ee1f277.PNG)

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
I've prepared a sample for you - https://plnkr.co/edit/rQsGxa2yt0zEHZE2EE0f?p=preview
The sample customizes rating item CSS class and declares CSS rule to change rating item text color to magenta.

I should note, that in case of you customize classes you overrides all default classes. I recommend you to check what default classes are being used in SurveyJS library (via browser debug console or checking these files - https://github.com/surveyjs/surveyjs/blob/master/src/defaultCss/cssstandard.ts or https://github.com/surveyjs/surveyjs/blob/master/src/defaultCss/cssbootstrap.ts)

You can also check default styles in order not to breal default rating question appearance.
