### ISSUE TITLE
markdown conflicts with "showPageNumbers": true

### ISSUE THREAD

**Issue by masciugo** [surveyjs/surveyjs#1146]
### Are you requesting a feature, reporting a bug or ask a question?

bug

### What is the current behavior?

when showing page numbers in page titles with `"showPageNumbers": true` and markdown enabled the title is wrongly rendered 

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/maQFARdFPIJYCSVQaEHc?p=preview

**Comment by andrewtelnov** [comment]
@masciugo Additionally a new attribute is added into options paramater:
`options.element SurveyJS element where the string is going to be rendered. It is a question, panel, page or survey`

Thank you,
Andrew
