### ISSUE TITLE
Property 'getProcessedText' is missing in type 'SurveyPropertyEditorBase'

### ISSUE THREAD

**Issue by gwFletcher** [surveyjs/surveyjs#1148]
### What is the current behavior? Unable to build application.  Error is "node_modules/surveyjs-editor/surveyeditor.d.ts (71,22): Class 'SurveyPropertyEditorBase' incorrectly implements interface 'ILocalizableOwner'.
  Property 'getProcessedText' is missing in type 'SurveyPropertyEditorBase'. "

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
We have an Angular+SurveyJS boilerplate repo - https://github.com/surveyjs/surveyjs_angular_cli
I've just cloned it, installed latest npm packages (1.0.25) and run ng serve
It works ok for me.

Could you provide any additional info to reproduce the issue on our side.
Or could you get the surveyjs_angular_cli repo and try to reproduce the issue with this repo?
