### ISSUE TITLE
defaultValue does not work when survey.data is defined

### ISSUE THREAD

**Issue by wysoki89** [surveyjs/surveyjs#1149]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

defaultValue does not work when survey.data is defined

### What is the expected behavior?

defaultValue should work along survey.data

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://plnkr.co/edit/qY2fay2XuHa2aOqBsE4N?p=preview
Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version: Version 66.0.3359.181 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: 1.0.25

**Comment by andrewtelnov** [comment]
@wysoki89 You are totally overriding values by setting survey.data. The library decided that you want to make your first question empty. Please use survey.setValue("questionValueName", value).
Please, use the following code:
```
if(!!myData) {
 for(key in myData) survey.setValue(key, myData[key]);
}
```
Thank you,
Andrew

**Comment by naoey** [comment]
Is there a way to override this behaviour such that a question always takes its configured default value if only its value in data is falsey, rather than the whole data object being false?
