### ISSUE TITLE
Is there any way to add a custom spinner before displaying "thank you" page?

### ISSUE THREAD

**Issue by KLC215** [surveyjs/surveyjs#1152]
Hi. Is there any way to add a custom spinner before displaying "thank you" page?

**Comment by tsv2013** [comment]
In case of you are sending survey results on the server via your own code, you do it in the `onComplete` event handler. In this handler you can hide the survey container div and show any other markup, e.g. custom spinner. Then you post results to the server and waiting for response. After you get a response you can replace spinner with a "thank you" custom message.
Is it ok for you?

**Comment by KLC215** [comment]
Thanks @tsv2013. That's a great scenario. I found that surveyjs need to take a few seconds to validate questions before displaying my custom message, so I am looking for a way like `onBeforeComplete` event to prevent user send more than one requests to server. Is there any approach to do that?

**Comment by andrewtelnov** [comment]
@KLC215 Please review [this section](https://surveyjs.io/Documentation/Library/#storeresults), Store survey results in your own database,  in documentation. 

Thank you,
Andrew

**Comment by KLC215** [comment]
Thanks @tsv2013 and @andrewtelnov . I found another approach to do it. :)

**Comment by dmitrykurmanov** [comment]
@KLC215 if you want you could share your approach with us. It could be useful for other customers :)

**Comment by KLC215** [comment]
Since I am using survey-react, I unmounted survey component after I saved all survey data to Redux and replace my custom spinner and "Thank you" message on it. 
It may not a good solution, but it works in my scenario.

**Comment by andrewtelnov** [comment]
@KLC215 Yes, it should work fine. 
Thank you for sharing. 
Andrew
