### ISSUE TITLE
Is there a way to style survey questions?

### ISSUE THREAD

**Issue by JonBetts** [surveyjs/surveyjs#1154]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question

### What is the current behavior?
Survey questions do not have any CSS classes attached to them, so you cannot format them in any way (by overriding the class styling)

### What is the expected behavior?
Giving the survey questions a default class, so that you can then style them in some way.

What I am referring to is the questions on the left of the matrix ("I received a sufficient number of CVs... etc") as shown below:

<img width="777" alt="screen shot 2018-06-07 at 17 50 41" src="https://user-images.githubusercontent.com/1726558/41114057-30bd196a-6a7b-11e8-8fe0-5ee685b659c9.png">

If they each had a CSS class, then we could override that class in order to style the questions (e.g. make them bold).

Or is there another way to do this? I noticed the `onUpdateQuestionCssClasses` method, but I cannot see a way to edit these specific elements via that.

Thanks.

**Comment by tsv2013** [comment]
We have an example how to use the `onUpdateQuestionCssClasses` event - https://surveyjs.io/Examples/Library/?id=survey-cssclasses&platform=jQuery&theme=default

Survey object has the [onAfterRenderQuestion](https://surveyjs.io/Documentation/Library/?id=surveymodel#onAfterRenderQuestion) event. In the handler you can access just created markup and customize it.
