### ISSUE TITLE
Modify the error message in Matrix Dropdown

### ISSUE THREAD

**Issue by Jojo109** [surveyjs/surveyjs#1156]
### Are you requesting a feature, reporting a bug or ask a question?

Question

![capture22](https://user-images.githubusercontent.com/39783820/41147634-8bf995a6-6b39-11e8-9a27-ceaf505b0634.png)

I set the minRowCount of MatrixDynamic Question to be 1.
Then, can we change the error message in above picture?

**Comment by tsv2013** [comment]
You can change the message in your locale:
```JS
Survey.surveyLocalization.locales["en"].minRowCountError = "My message";
```

**Comment by Jojo109** [comment]
@tsv2013  Thanks
