### ISSUE TITLE
Review Quiz

### ISSUE THREAD

**Issue by ltrtuan** [surveyjs/surveyjs#1157]
Hi.
I have a project about Creating quiz for user.
- Step 1: super admin compose Quiz by Surveyjs Builder. I have an event "survey.onTestSurveyCreated.add" to get KEY of quiz.
- Step 2: after user took quiz, super admin review that quiz. I want to show KEY for each QUESTIONS (include matrix field) to easily review.
How can i do that ?

*** My idea
Your plugin has correctAnswer property in question JSON.
- How can i store correctAnswer in "survey.onTestSurveyCreated.add" event ?
- How can i show correctAnswer value below each question in REVIEW view of super admin. NOTE: i don't want to show in QUIZ view of user.
Thanks so much

**Comment by ltrtuan** [comment]
Sorry my bad. I didn't see correctAnswer property when compose question. So i don't need an event to store it.
My question is: Following the example https://surveyjs.io/Examples/Library/?id=survey-displaymode&platform=jQuery&theme=default , it let end-user can review their quiz, but they can't know which quiz right. How can i show CorrectAnswer below each question (NOTE: there are matrix fields, possible show in each ROW question ?) ?

**Comment by andrewtelnov** [comment]
@ltrtuan I would recommend you to use [onAfterRender](https://surveyjs.io/Documentation/Library/?id=surveymodel#onAfterRenderQuestion) and [onMatrixAfterCellRender](https://surveyjs.io/Documentation/Library/?id=surveymodel#onMatrixAfterCellRender) events
Here is the [example of using onAfterRender event](https://surveyjs.io/Examples/Library/?id=survey-afterrender)

Thank you,
Andrew

**Comment by ltrtuan** [comment]
Thanks for your supporting.
How can I detect TYPE OF QUESTION in onAfterRenderQuestion event ?

**Comment by andrewtelnov** [comment]
@ltrtuan 
```
survey.onAfterRenderQuestion.add(sender, options) {
  if(options.question.getType() !== "text") return;
 ...
});
```
Thank you,
Andrew

**Comment by ltrtuan** [comment]
You're the best.
My past question. How can i REMOVE "correctAnswer" property IN RENDER QUESTION, not IN BUILDER.
Thanks. Below is my JSON layout data. Because i SHOW this data in HTML field, so i want to remove correctAnswer, i don't want end-user to see it.
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "matrixdropdown",
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "columns": [
      {
       "name": "col",
       "title": "Answer",
       "cellType": "dropdown"
      }
     ],
     "correctAnswer": {
      "Question 1": {
       "col": 4
      },
      "Question 2": {
       "col": 5
      }
     },
     "name": "question1",
     "rows": [
      "Question 1",
      "Question 2"
     ],
     "title": "This is question"
    }
   ]
  }
 ]
}

**Comment by ltrtuan** [comment]
Hi andrew.
Why can i not get correctAnswer property in onMatrixAfterCellRender event ?

```
survey
.onMatrixAfterCellRender
.add(function (survey, options) {			
	var correctAnswer = options.question.correctAnswer ;
	console.log(correctAnswer);
});
```

**Comment by andrewtelnov** [comment]
@ltrtuan Here is [the code](https://plnkr.co/edit/e8TbTp80ykQQVW0IJ9HD?p=preview) you have to write.

Thank you,
Andrew
