### ISSUE TITLE
overflow:auto on .sv_qstn class breaks custom widgets

### ISSUE THREAD

**Issue by kaphert** [surveyjs/surveyjs#1158]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
The css property `overflow: auto` is by default applied on `.sv_qstn` which breaks custom widgets (choices.js) that have a dropdown or some other element.

I think overflow:auto is not a good default setting for the form.

I see in my compiled survey.vue.js file this row:
```
".sv_qstn": "display: inline-block; vertical-align: top; overflow: auto;",
```

### Specify your

* surveyjs platform (angular or react or jquery or knockout or vue): VUE
* surveyjs version: 1.0.25

**Comment by tsv2013** [comment]
This setting is for horizontal scrolling for questions, especially matrixes in case of long values and mach columns.
If you need other default behaviour, you can add your own CSS rule overriding the current behaviour.

**Comment by kaphert** [comment]
Ok, understandable. Yes I already added custom css to "fix" it for in my case.
