### ISSUE TITLE
Missing polish translations

### ISSUE THREAD

**Issue by padcom** [surveyjs/surveyjs#1160]
Missing polish translations for some keys:

  savingData, savingDataError, savingDataSuccess, saveAgainButton,  timerMin, timerSec, timerSpentAll, timerSpentPage, timerSpentSurvey, timerLimitAll, timerLimitPage, timerLimitSurvey, cleanCaption

**Comment by padcom** [comment]
Question: how do I manually override the translation until a new version is released?

I tried what's described in the docs as

```
Survey.surveyStrings.savingData = "Please wait. We are validating and saving your reponse";
Survey.surveyStrings.savingDataError = "That is my own text on error";
Survey.surveyStrings.savingDataSuccess = "That is my own text on success";
Survey.surveyStrings.saveAgainButton = "Try to save again";
```
but that won't even compile as ```surveyStrings``` seems not to be available.

**Comment by andrewtelnov** [comment]
@padcom It should work. 
To be more correct you may use the following code:
```
plLocale = Survey.surveyLocalization.locales["pl"];
plLocale.addPanel = "Dodaj panel";
plLocale.removePanel = "Usuń";
...
```
Here is the [example](https://plnkr.co/edit/4BRAkHfUH31ni8ZV4Kuu?p=preview)

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@padcom and thank your for sharing with updated translation.

Andrew

**Comment by padcom** [comment]
@andrewtelnov Unfortunately neither worked:

```
@Component({})
export default class App extends Vue {
  survey = new Model({ surveyId: '4246421e-19f6-4982-a69e-894a13576d75' })

  created () {
    this.survey.surveyPostId = '32d44468-af61-407e-aa0e-649a6329decd'
    this.survey.locale = 'pl'
    this.survey.surveyShowDataSaving = true
    const plLocale = Survey.surveyLocalization.locales['pl']
    plLocale.loadingSurvey = 'Test...'
  }
}
```

that yields still the old text when loading the survey.

**Comment by andrewtelnov** [comment]
@padcom Please change the code accordingly: https://jsfiddle.net/5s0mr36j/
I have forked the Vue 2.0 Hello Word app.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@padcom have you seen our [vue quick start repo](https://github.com/surveyjs/surveyjs_vue_quickstart/tree/master/src)
Here is [App.vue file](https://github.com/surveyjs/surveyjs_vue_quickstart/blob/master/src/App.vue)

Thank you,
Andrew

**Comment by padcom** [comment]
Ok, that clears a few things. For posterity:

```
import SurveyVue from 'survey-vue'
...
const plLocale = SurveyVue.surveyLocalization.locales['pl']
plLocale.loadingSurvey = 'Changed text'
```

I can also see the updated locales properly displayed on screen. That settles it then! Thank you!

**Comment by andrewtelnov** [comment]
@padcom You are very welcome!
