### ISSUE TITLE
Use expression in HTML question

### ISSUE THREAD

**Issue by derchirurg** [surveyjs/surveyjs#1162]
### Are you requesting a feature, reporting a bug or ask a question?
question

### What is the expected behavior?
Is it possible to use an expression in an html question? I want to show the count of a dynamic panel in html.

Sample text: You have added [x] elements to your panel.

If I use this in html template, it is not shown: {pg8-mypnl.length}

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version: 1.0.25

**Comment by derchirurg** [comment]
Please see issue [#1164](https://github.com/surveyjs/surveyjs/issues/1164)
Both events does not get invoked.

**Comment by andrewtelnov** [comment]
@derchirurg I found the issue. I gave the wrong link to the onDynamicPanelAdded. I have corrected it.

Thank you,
Andrew

**Comment by derchirurg** [comment]
@andrewtelnov The html variable does not update when I set the variable in the event.
Please see the updated plunk: http://plnkr.co/edit/zUdf33tVJ9bKnXri6UD8?p=preview

**Comment by andrewtelnov** [comment]
@derchirurg Indeed there is a bug, we have to preprocess html property as we do for title: http://plnkr.co/edit/ZWemmkK9wKiXGz0frmqQ?p=preview
We will fix it.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@derchirurg I have fixed this bug. html was rerendered on chaning the variable. 
We will likely release a new version on Wednesday. I may rebuild the library using the instruction in the Readme file

Thank you,
Andrew

**Comment by derchirurg** [comment]
That is great, thanks.
