### ISSUE TITLE
onPanelAdded and onPanelRemoved not invoked

### ISSUE THREAD

**Issue by derchirurg** [surveyjs/surveyjs#1164]
### Are you requesting a feature, reporting a bug or ask a question?
bug

### What is the current behavior?
The functions onPanelAdded and onPanelRemoved does not get invoked.
Please see provided plunk.

### What is the expected behavior?
should be invoked

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: http://plnkr.co/edit/dl5WxcFjDNQsuHTDSIWN

### Specify your

* browser: Chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version: 1.0.25

**Comment by andrewtelnov** [comment]
@derchirurg You are using a wrong event. You need onDynamicPanelAdded, here the plunker: http://plnkr.co/edit/SAT7vA6p9yxenUzJ2PQU?p=preview

Thank you,
Andrew
