### ISSUE TITLE
Adding custom input attributes is failing with Vue

### ISSUE THREAD

**Issue by kaphert** [surveyjs/surveyjs#1165]
### Are you requesting a feature, reporting a bug or ask a question?
Bug or feature request

### What is the current behavior?
I am working on a something to add custom attributes to input html elements. For example: add `min`, `max`, `maxlength`, `autocomplete` etc. to an input field. I am trying to do this with `onAfterRenderQuestion`. 

It works... but as soon as you leave focus on the field and get back to it 'maxlength' is gone from the element and you can enter as many characters as you want. 

### How would you reproduce the current behavior (if this is a bug)?
See this plunker. https://next.plnkr.co/edit/7jdwbtYToHHzgmwe?preview

1. Inspect the input element with your browser console. 
2. Now enter some values in the form
3. You can enter only a string of max length of 3 
4. Remove focus from field
5. Look in your console: maxlength is now removed from the input

### Build in solution for surveyjs?
Besides this behavior: maybe it would be a nice feature to add custom attributes on the actual form fields? 
Something like:
```
{
        type: "text",
        name: "q1",
        title: "Question 1"
        questionAttributes: {
              maxlength: 50,
              autocomplete: "off"
        }
}
```

### Specify your

* browser: Chrome / Firefox latest versions
* surveyjs platform (angular or react or jquery or knockout or vue): VUEJS
* surveyjs version: 1.0.25

**Comment by andrewtelnov** [comment]
@kaphert We have maxLength property already and it works fine. I forked your pluker: https://next.plnkr.co/edit/Q2Y1jHFyl8Mbm8UT

Thank you,
Andrew

**Comment by kaphert** [comment]
@andrewtelnov jeez, how could I've missed that. Thanks. That probably explains why it 'breaks' my custom maxlength attribute. Adding `automcomplete="off"` to it does behave as expected. 

Ok, besides the suggestion to have something like `questionAttributes: {}` I'm closing this.
