### ISSUE TITLE
trigger validation on the whole survey

### ISSUE THREAD

**Issue by masciugo** [surveyjs/surveyjs#1169]
### Are you requesting a feature, reporting a bug or ask a question?

question

### What is the current behavior?

_doComplete_ skip validation

### What is the expected behavior?

in my scenario I have an external navigation to change pages and save the data and I would like to go back and forth and complete the survey from any page. 
![screen shot 2018-06-12 at 18 58 12](https://user-images.githubusercontent.com/454321/41305245-9ead4166-6e72-11e8-90d8-1f2e3d76ba4c.png)

So far I used the _doComplete_ method in order to send the data but I noticed that validation were skipped!

So to run the validations and show the errors on questions I had to call _isCurrentPageHasErrors_ before changing the page but this way I am forced to resolve the errors. Very often to solve the errors my users need to check data in the other pages but they are stucked. 

What I really need is a way to trigger validations on the whole survey and show the errors on the several pages. Not just check errors page by page
A way to keep track of the survey errors and until there are errors my external save button will be disabled

any way to do that or could be implemented?

many thanks for this amazing library that I am try to use as a multipage form builder with great results

**Comment by andrewtelnov** [comment]
@masciugo The question is:
How to show all questions with errors on one page? Am I correct? 

It is not the hard task to implement for simple scenarios. The problem, that while the user correct errors, some other questions may become visible and that would require their attention as well.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@masciugo Or probably there should be a functionality, to hide all questions that doesn't require the user attention. They can be on multiple pages. What do you think?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@masciugo The easiest way to introduce this functionality, is to add onGetQuestionVisibilty event into survey. You will be able to make a question invisible, if it doesn't have any errors and keep visible questions with errors only. It should do the trick. So we will have two states an normal and show questions with errors only.

Thank you,
Andrew

**Comment by masciugo** [comment]
@andrewtelnov thank you for your effort but I think that your solution may be too much. However your first question is correct so what I did to solve my use case with the options I have is to check for errors on events like _onCurrentPageChanged_ and _onValueChanged_ with the method _isCurrentPageHasErrors_ which trigger validations. 

After changing a page with errors, in order to not miss them I show a summary alert about all unresolved errors along with their page location

![showerrors](https://user-images.githubusercontent.com/454321/41361483-6adf66e4-6f2f-11e8-825d-f76309090fa8.gif)


I am quite satisfied but I would prefer to have 3 things:

1. a new method _isSurveyHasErrors_ to manually run validations on all questions before calling _doComplete_
2. store the errors somewhere in the survey object after running validations so that I can show them somewhere else
3. avoid forcing focus on input with error. I may have two in the same page and I want to change the "other" 

what do you think?

**Comment by masciugo** [comment]
ok, I got it. Thanks!

**Comment by julination** [comment]
how can I trigger only the UI validation on screen? Like: "one questions is required!" what's the function that triggers this behavior?

**Comment by andrewtelnov** [comment]
@julination You can put your questions into panel and make this panel required. Here is [the example](https://plnkr.co/edit/xaiCBFVVLPJeURqF).

Thank you,
Andrew

**Comment by julination** [comment]
@andrewtelnov I was actually thinking about something like that:

I'm using react and I can't do isRequired manually or using only onComplete. 
the way you come up is when you are adding ".add" `survey.onComplete.add(function (result) {...
`
how can I do that on react? this "add" only triggers the validation on ui?

because I would need only to validate for instant. like:


`    const handleOnComplete = (surveyProps) => {
        const requiredCheckResult = surveyProps.validateAllisRequiredQuestions()

        if(requiredCheckResult) {
            // finish the upcomming behaviors
            // setStatus('CONCLUDED');
            // setEnddate(new Date().toLocaleDateString('pt-BR'));
        }
    }`
