### ISSUE TITLE
Error: TypeError: self.question.survey is undefined

### ISSUE THREAD

**Issue by derchirurg** [surveyjs/surveyjs#1175]
### Are you requesting a feature, reporting a bug or ask a question?
bug

### What is the current behavior?
I'm getting the error described below. It occurs in the jquery version. In Angular it works. But I need both.

> TypeError: self.question.survey is undefined
> 	QuestionImplementorBase/this.question.koRootClass<
> file:///[...]/survey.jquery.js:17044:1
> evaluateImmediate_CallReadThenEndDependencyDetection
> knockout-latest.debug.js:2142
> evaluateImmediate_CallReadWithDependencyDetection
> knockout-latest.debug.js:2114
> evaluateImmediate
> knockout-latest.debug.js:2078
> beforeSubscriptionAdd
> knockout-latest.debug.js:2206
> subscribe
> knockout-latest.debug.js:1299
> subscribeToDependency
> knockout-latest.debug.js:2030
> computedBeginDependencyDetectionCallback
> knockout-latest.debug.js:1973:115
> registerDependency
> knockout-latest.debug.js:1454
> computedObservable
> knockout-latest.debug.js:1884
> unwrapObservable
> knockout-latest.debug.js:476
> update
> knockout-latest.debug.js:4130
> applyBindingsToNodeInternal/</<
> knockout-latest.debug.js:3318
> evaluateImmediate_CallReadThenEndDependencyDetection
> knockout-latest.debug.js:2142
> evaluateImmediate_CallReadWithDependencyDetection
> knockout-latest.debug.js:2114
> evaluateImmediate
> knockout-latest.debug.js:2078
> ko.dependentObservable
> knockout-latest.debug.js:1939
> applyBindingsToNodeInternal/<
> knockout-latest.debug.js:3316
> arrayForEach
> knockout-latest.debug.js:159
> applyBindingsToNodeInternal
> knockout-latest.debug.js:3288
> applyBindingsToNodeAndDescendantsInternal
> knockout-latest.debug.js:3168
> ko.applyBindings
> knockout-latest.debug.js:3379
> activateBindingsOnContinuousNodeArray/<
> knockout-latest.debug.js:5237
> invokeForEachNodeInContinuousRange
> knockout-latest.debug.js:5188
> activateBindingsOnContinuousNodeArray
> knockout-latest.debug.js:5235
> executeTemplate
> knockout-latest.debug.js:5283
> ko.renderTemplate/<
> knockout-latest.debug.js:5325
> evaluateImmediate_CallReadThenEndDependencyDetection
> knockout-latest.debug.js:2142
> evaluateImmediate_CallReadWithDependencyDetection
> knockout-latest.debug.js:2114
> evaluateImmediate
> knockout-latest.debug.js:2078
> ko.dependentObservable
> knockout-latest.debug.js:1939
> ko.renderTemplate
> knockout-latest.debug.js:5317
> update
> knockout-latest.debug.js:5455
> applyBindingsToNodeInternal/</<
> knockout-latest.debug.js:3318
> evaluateImmediate_CallReadThenEndDependencyDetection
> knockout-latest.debug.js:2142
> evaluateImmediate_CallReadWithDependencyDetection
> knockout-latest.debug.js:2114
> evaluateImmediate
> knockout-latest.debug.js:2078
> ko.dependentObservable
> knockout-latest.debug.js:1939
> applyBindingsToNodeInternal/<
> knockout-latest.debug.js:3316
> arrayForEach
> knockout-latest.debug.js:159
> applyBindingsToNodeInternal
> knockout-latest.debug.js:3288
> applyBindingsToNodeAndDescendantsInternal
> knockout-latest.debug.js:3168
> applyBindingsToDescendantsInternal
> knockout-latest.debug.js:3150
> ko.applyBindingsToDescendants
> knockout-latest.debug.js:3366
> init/<
> knockout-latest.debug.js:4341
> evaluateImmediate_CallReadThenEndDependencyDetection
> knockout-latest.debug.js:2142
> evaluateImmediate_CallReadWithDependencyDetection
> knockout-latest.debug.js:2114
> evaluateImmediate
> knockout-latest.debug.js:2078
> ko.dependentObservable
> knockout-latest.debug.js:1939
> init
> knockout-latest.debug.js:4325
> applyBindingsToNodeInternal/</<
> knockout-latest.debug.js:3303
> ignore
> knockout-latest.debug.js:1461
> applyBindingsToNodeInternal/<
> knockout-latest.debug.js:3302
> arrayForEach
> knockout-latest.debug.js:159
> applyBindingsToNodeInternal
> knockout-latest.debug.js:3288
> applyBindingsToNodeAndDescendantsInternal
> knockout-latest.debug.js:3168
> ko.applyBindings
> knockout-latest.debug.js:3379
> activateBindingsOnContinuousNodeArray/<
> knockout-latest.debug.js:5237
> invokeForEachNodeInContinuousRange
> knockout-latest.debug.js:5188
> activateBindingsOnContinuousNodeArray
> knockout-latest.debug.js:5235
> activateBindingsCallback
> knockout-latest.debug.js:5361
> ko.utils.setDomNodeChildrenFromArrayMapping
> knockout-latest.debug.js:5734
> ignore
> knockout-latest.debug.js:1461
> ko.renderTemplateForEach/<
> knockout-latest.debug.js:5382
> evaluateImmediate_CallReadThenEndDependencyDetection
> knockout-latest.debug.js:2142
> evaluateImmediate_CallReadWithDependencyDetection
> knockout-latest.debug.js:2114
> evaluateImmediate
> knockout-latest.debug.js:2078
> ko.dependentObservable
> knockout-latest.debug.js:1939
> ko.renderTemplateForEach
> knockout-latest.debug.js:5370
> update
> knockout-latest.debug.js:5447
> update
> knockout-latest.debug.js:4244
> applyBindingsToNodeInternal/</<
> knockout-latest.debug.js:3318
> evaluateImmediate_CallReadThenEndDependencyDetection
> knockout-latest.debug.js:2142
> evaluateImmediate_CallReadWithDependencyDetection
> knockout-latest.debug.js:2114
> evaluateImmediate
> knockout-latest.debug.js:2078
> ko.dependentObservable
> knockout-latest.debug.js:1939
> applyBindingsToNodeInternal/<
> knockout-latest.debug.js:3316
> arrayForEach
> knockout-latest.debug.js:159
> applyBindingsToNodeInternal
> knockout-latest.debug.js:3288
> applyBindingsToNodeAndDescendantsInternal
> knockout-latest.debug.js:3168
> applyBindingsToDescendantsInternal
> knockout-latest.debug.js:3150
> applyBindingsToNodeAndDescendantsInternal
> knockout-latest.debug.js:3177
> applyBindingsToDescendantsInternal
> knockout-latest.debug.js:3150
> ko.applyBindingsToDescendants
> knockout-latest.debug.js:3366
> init/<
> knockout-latest.debug.js:4341
> evaluateImmediate_CallReadThenEndDependencyDetection
> knockout-latest.debug.js:2142
> evaluateImmediate_CallReadWithDependencyDetection
> knockout-latest.debug.js:2114
> evaluateImmediate
> knockout-latest.debug.js:2078
> ko.dependentObservable
> knockout-latest.debug.js:1939
> init
> knockout-latest.debug.js:4325
> applyBindingsToNodeInternal/</<
> knockout-latest.debug.js:3303
> ignore
> knockout-latest.debug.js:1461
> applyBindingsToNodeInternal/<
> knockout-latest.debug.js:3302
> arrayForEach
> knockout-latest.debug.js:159
> applyBindingsToNodeInternal
> knockout-latest.debug.js:3288
> applyBindingsToNodeAndDescendantsInternal
> knockout-latest.debug.js:3168
> ko.applyBindings
> knockout-latest.debug.js:3379
> activateBindingsOnContinuousNodeArray/<
> knockout-latest.debug.js:5237
> invokeForEachNodeInContinuousRange
> knockout-latest.debug.js:5188
> activateBindingsOnContinuousNodeArray
> knockout-latest.debug.js:5235
> activateBindingsCallback
> knockout-latest.debug.js:5361
> ko.utils.setDomNodeChildrenFromArrayMapping
> knockout-latest.debug.js:5734
> ignore
> knockout-latest.debug.js:1461
> ko.renderTemplateForEach/<
> knockout-latest.debug.js:5382
> evaluateImmediate_CallReadThenEndDependencyDetection
> knockout-latest.debug.js:2142
> evaluateImmediate_CallReadWithDependencyDetection
> knockout-latest.debug.js:2114
> evaluateImmediate
> knockout-latest.debug.js:2078
> ko.dependentObservable
> knockout-latest.debug.js:1939
> ko.renderTemplateForEach
> knockout-latest.debug.js:5370
> update
> knockout-latest.debug.js:5447
> update
> knockout-latest.debug.js:4244
> applyBindingsToNodeInternal/</<
> knockout-latest.debug.js:3318
> evaluateImmediate_CallReadThenEndDependencyDetection
> knockout-latest.debug.js:2142
> evaluateImmediate_CallReadWithDependencyDetection
> knockout-latest.debug.js:2114
> evaluateImmediate
> knockout-latest.debug.js:2078
> ko.dependentObservable
> knockout-latest.debug.js:1939
> applyBindingsToNodeInternal/<
> knockout-latest.debug.js:3316
> arrayForEach
> knockout-latest.debug.js:159
> applyBindingsToNodeInternal
> knockout-latest.debug.js:3288
> applyBindingsToNodeAndDescendantsInternal
> knockout-latest.debug.js:3168
> ko.applyBindings
> knockout-latest.debug.js:3379
> activateBindingsOnContinuousNodeArray/<
> knockout-latest.debug.js:5237
> invokeForEachNodeInContinuousRange
> knockout-latest.debug.js:5188
> activateBindingsOnContinuousNodeArray
> knockout-latest.debug.js:5235
> executeTemplate
> knockout-latest.debug.js:5283
> ko.renderTemplate/<
> knockout-latest.debug.js:5325
> evaluateImmediate_CallReadThenEndDependencyDetection
> knockout-latest.debug.js:2142
> evaluateImmediate_CallReadWithDependencyDetection
> knockout-latest.debug.js:2114

### How would you reproduce the current behavior (if this is a bug)?
I have tried to setup a plunk. It has a different error, but it is like the same szenario I have.
https://plnkr.co/edit/LKVIswpfbyOv95Pyt8L8?p=preview

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/LKVIswpfbyOv95Pyt8L8?p=preview

### Specify your

* browser: chrome, firefox
* browser version: 
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.26

**Comment by derchirurg** [comment]
When will the fix be available?

**Comment by tsv2013** [comment]
In the nearest update. Usually we release updates once in a week.

**Comment by derchirurg** [comment]
Thanks. I'm urgently waiting for the fix.

**Comment by derchirurg** [comment]
@tsv2013 Sorry, but it is not totally fixed.
The survey renders, but does not show the correct title, if setting default language. Please see the updated plunk.
https://plnkr.co/edit/LKVIswpfbyOv95Pyt8L8?p=preview

**Comment by tsv2013** [comment]
@derchirurg Your last remark is not related to the original issue and I've opened another therad - https://github.com/surveyjs/surveyjs/issues/1185 - Question has wrong title under certain circumstances
