### ISSUE TITLE
Cancel selection on a radiogroup item

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/surveyjs#1176]
@rekotc asked at the https://github.com/surveyjs/widgets/issues/64 thread:

Is it possible to uncheck a selection on a radiogroup item?

Thanks in advance.

**Comment by tsv2013** [comment]
Unfortunately SurveyJS library hasn't such a functionality for a while. I think this makes sence. @andrewtelnov what do you think?

**Comment by andrewtelnov** [comment]
I do not know how to make it visually. What kind of UI should we build?
It is logically to add a "none" item, but in this case, choosing 'none" value has the same meaning that clearing a value.

Thank you,
Andrew

**Comment by tsv2013** [comment]
@andrewtelnov So do I. Probabaly we can implement a common for all questions functionality - a reset button looks like a cross somethere nearby the title. Or we can ask our designer...

**Comment by rekotc** [comment]
It could be very nice to be just able to click again on the same radio to reset it... thanks for discussing the issue!

**Comment by tsv2013** [comment]
Added `showClearButton` option for the radiogroup question. Default if `false`. If set to `true` the clear button appears under the choices and resets question value on click. The feature will be available in the next update.
