### ISSUE TITLE
Survey does not render language specific title in conditional dynamic panel when isSinglePage is true

### ISSUE THREAD

**Issue by derchirurg** [surveyjs/surveyjs#1184]
### Are you requesting a feature, reporting a bug or ask a question?
bug

### What is the current behavior?
jQuery version
The survey renders, but does not show the correct title, if setting default language. Please see the plunk.
https://plnkr.co/edit/LKVIswpfbyOv95Pyt8L8?p=preview

On question 91 it shows question91, but should show the german title "Wählen Sie eine Option"

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/LKVIswpfbyOv95Pyt8L8?p=preview

### Specify your

* browser: all
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.27

**Comment by tsv2013** [comment]
Minimal sample to reproduce - https://plnkr.co/edit/AeXmRF?p=preview
Issue is related to the `panelCount: 2` setting in the JSON

**Comment by andrewtelnov** [comment]
@derchirurg @tsv2013 isSinglePage was the problem.
I have added the unit test and fixed it.

Thank you,
Andrew
