### ISSUE TITLE
No user friendly message for an invalid password

### ISSUE THREAD

**Issue by Nuarat** [surveyjs/surveyjs#1187]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
When the login\password is incorrect, there's no user friendly message saying what happened.
Instead there's a tooltip which says "invalid login attempt".

### What is the expected behavior?
Clearly say that the login or password didn't fit. Not in a tooltip, but somewhere where it's visible without any actions required.

### How would you reproduce the current behavior (if this is a bug)?
Try to log in with wrong credentials.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/Account/Login

### Specify your

* browser: any
* browser version: any
![login](https://user-images.githubusercontent.com/11683678/41713041-be114384-7554-11e8-9c60-97a7de7b2ddd.png)

**Comment by tsv2013** [comment]
We can't give an ability to find out a valid login name or password. That's why we tell no special info about the login errors. This is the common practice.
