### ISSUE TITLE
Forgot your password? Then create a new user instead!

### ISSUE THREAD

**Issue by Nuarat** [surveyjs/surveyjs#1189]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
The "Forgot your password" and "Create a new user" read as one action, because they're so close together. 

![forgot](https://user-images.githubusercontent.com/11683678/41713575-3694f732-7556-11e8-9a63-685ff0ca3c1d.PNG)

### What is the expected behavior?
These phrases should be visually separated from each other.

### How would you reproduce the current behavior (if this is a bug)?
it's always there

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/Account/Login

**Comment by dmitrykurmanov** [comment]
Fixed, fix will be available in the next patch release.
