### ISSUE TITLE
Decimal places in expression

### ISSUE THREAD

**Issue by vihansri** [surveyjs/surveyjs#1194]
### Are you requesting a feature, reporting a bug or asking a question?
question

### What is the current behavior?
the expression field has many decimal places
e.g. 2.3333333333333335

### What is the expected behavior?
there should be an option to restrict the number of decimal places
e.g. 2.33

### How would you reproduce the current behavior (if this is a bug)?
create an expression type question and set the displayStyle as decimal

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

{
     "type": "expression",
     "name": "Baseline_ACQ_Score",
     "title": "Your Score:",
     "titleLocation": "top",
     "expression": "({Baseline_ACQ_Q1} + {Baseline_ACQ_Q2} + {Baseline_ACQ_Q3} + {Baseline_ACQ_Q4} + {Baseline_ACQ_Q5} + {Baseline_ACQ_Q6})/6)\n"
    }

```

### Specify your

* browser: Chrome
* browser version: 66.0.3359.181
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version:

**Comment by andrewtelnov** [comment]
@vihansri You can set displayStyle to decimal. It will show "2.333" in this case.
I have added maximumFractionDigits and minimumFractionDigits. You may set maximumFractionDigits to 2 to get the result you need. They will appear in the next minor release on the next week.

Thank you,
Andrew
