### ISSUE TITLE
Use expression property in triggers instead of: name, operator and value

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#1197]
Triggers may have only one condition right now. There is no way to set the multiple conditions by using "and" and "or" operands.

The old way is continue to work. You may use both: name, operator and value or expression.
Editor will convert name, operator and value into expression and save into json expression only, if you go to Triggers tab and confirm changes.

**Comment by akhoury** [comment]
can you provide a usage example please? thanks

**Comment by andrewtelnov** [comment]
@akhoury Here is [the example](https://surveyjs.io/Examples/Library/?id=validators-expression)

Thank you,
Andrew

**Comment by akhoury** [comment]
Oh i thought this is a trigger expression support, something like 
```javascript
    triggers: [
      {
        condition: "{life-event} == 'moving' || {life-event} == 'inst' || {life-event} == 'loss'",
        setToName: "part-a-active",
        setValue: "yes"
      }
    ],
```

**Comment by andrewtelnov** [comment]
It does:
```
    triggers: [
      {
        expression: "{life-event} == 'moving' or {life-event} == 'inst' or {life-event} == 'loss'",
        setToName: "part-a-active",
        setValue: "yes"
      }
    ]
```

Thank you,
Andrew
