### ISSUE TITLE
Tiny issue

### ISSUE THREAD

**Issue by johannakate** [surveyjs/surveyjs#1203]
### Are you requesting a feature, reporting a bug or asking a question?

reporting a bug

### What is the current behavior?

sidebar menu says Add Survey into you Web Page, title correctly says Add Survey into your*** Web Page

### What is the expected behavior?

Add Survey into your Web Page

### How would you reproduce the current behavior (if this is a bug)?

it's just there on the website for you to see atm

#### Provide the test code and the tested page URL (if applicable)
n/a

Tested page URL:
https://surveyjs.io/Documentation/Library/?id=Add-Survey-into-your-Web-Page
Test code

```
your_code_here

```

### Specify your
n/a 
* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
Thanks for the report. I've updated the site.
