### ISSUE TITLE
Unable to get Datepicker with Icon trigger

### ISSUE THREAD

**Issue by ashygk** [surveyjs/surveyjs#1206]
### Are you requesting a feature, reporting a bug or asking a question?
Question/Feature

### What is the current behavior?
I am able to include datepicker using custom widgets from SuveyJS in my Angular5 application

### What is the expected behavior?

I would like to know if we have an option for datepicker to be displayed on an icon trigger
https://jqueryui.com/datepicker/#icon-trigger

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): Angular 5
* surveyjs version: 1.0.25

**Comment by tsv2013** [comment]
I've moved this issue to the proper repo - https://github.com/surveyjs/widgets/issues/66
