### ISSUE TITLE
Don't include value in valueHash if question is hidden on some condition

### ISSUE THREAD

**Issue by cliewdevelop** [surveyjs/surveyjs#1207]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question.

### What is the current behavior?
When we select a question that conditionally hides certain questions, **those questions still appear in valuesHash** - is there a way to differentiate them?

eg:
question A - Yes/No
question B (show if questionA===Yes) - "Yes"/"No"

Select question A - Yes
Select question B - Yes

valuesHash = {
A: "Yes",
B: "Yes
}

all good,

then change question A to "No"
Question B will be hidden

but valuesHash is still {
A: "No"
B: "Yes" (previously selected, hidden in view)
}

Is there any way to not populate B in valuesHash? 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

browser: Chrome
browser version: 66.0.3359.181
surveyjs platform: React with no JQuery
surveyjs version: 1.0.10

**Comment by tsv2013** [comment]
You should set the [clearInvisibleValues](https://surveyjs.io/Documentation/Library/?id=surveymodel#clearInvisibleValues) property to the `onHidden` value.

**Comment by cliewdevelop** [comment]
Thank you. Marking this as closed
