### ISSUE TITLE
PDF Export of completed survey 

### ISSUE THREAD

**Issue by bvolkmann** [surveyjs/surveyjs#1209]
### Are you requesting a feature, reporting a bug or asking a question?

I'm requesting a feature.

### Description

Hi everyone, 
I stumbled across Issue #401 while looking for a way to export single completed surveys as a PDF Document, 
that looks like the survey itself (like the "Display" mode).

Unfortunately that issue was closed in december 2017, so i had to create a new one, 
since the given answers were unsatisfying.

I'm proud and looking forward to integrate the SurveyJS library in our software,  
but also am in a desperate need for this functionality as we're planning to provide 
the completed surveys as PDF documents via an IHE interface.

Thank you!

Best regards,
B. Volkmann

**Comment by tsv2013** [comment]
Hello,

Thank you for the feedback. PDF exporting is a rather complex task that lays outside the SurveyJS library functionality baoundaries. I think PDF export can be done via the 3rd party libraries, that solving this task better. @andrewtelnov @dmitrykurmanov what's your opinion?

Thanks, Serge
SurveyJS Team

**Comment by andrewtelnov** [comment]
@bvolkmann @tsv2013 I would suggest to use libraries like [this](https://github.com/MrRio/jsPDF).
You may set the following survey options:
[survey.mode](https://surveyjs.io/Documentation/Library/?id=surveymodel#mode) = "display";
[survey.isSinglePage](https://surveyjs.io/Documentation/Library/?id=surveymodel#isSinglePage) = true;

Thank you,
Andrew

**Comment by bvolkmann** [comment]
With the 3rd party libraries html2canvas and jsPDF 
it was possible to export the single, filled survey to a PDF.

**Comment by SaharDastitash** [comment]
Hello ,

Can you please give us an example?

**Comment by SaharDastitash** [comment]
@bvolkmann  Could you please share your solution for the export to pdf?

**Comment by andrewtelnov** [comment]
@SaharDastitash Here is the [example](https://plnkr.co/edit/riq0aC5BCQRDYZiK?p=preview)

Thank you,
Andrew

**Comment by SaharDastitash** [comment]
Thank you @andrewtelnov for the prompt answer , I really appreciate that. That's what I exactly wanted. The problem is that it doesn't save all the questions in your example. It only saves the results in one page, Is there any way to fix this?

**Comment by andrewtelnov** [comment]
@SaharDastitash Yes, I can see what you are talking about. It can export data on one page only. We will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@SaharDastitash We started to work on a code that breaks our survey rendered result on pages. [Here is](https://plnkr.co/edit/WDjPvGQGufy4wT3f3hVW?p=preview) what we have right now. Please take a look at separate file: export_to_pdf.js

Thank you,
Andrew

**Comment by SaharDastitash** [comment]
@andrewtelnov  I'm not sure how does the code work but in the js file there is no SaveToPdf() function but the button is calling this function!

**Comment by andrewtelnov** [comment]
@SaharDastitash There is a "Files" section in plunker, in the top left corner. 
You will see export_to_pdf.js that does the job.

Thank you,
Andrew

**Comment by SaharDastitash** [comment]
Oh Thanks, I found the SaveToPdf() function in the index.js page. Thank you @andrewtelnov

**Comment by MugiwaraNoMehdi** [comment]
@andrewtelnov here is a complete example of printing survey in multipage without breaking any element of the survey : 
https://plnkr.co/edit/E7vsei4zm5xGr0DLq57r?p=preview

**Comment by andrewtelnov** [comment]
@MugiwaraNoMehdi We have made [an example](https://surveyjs.io/Examples/Library/?id=survey-pdf) and put our code into separate [GitHub repo](https://github.com/surveyjs/pdf).

Thank you,
Andrew

**Comment by MugiwaraNoMehdi** [comment]
I have tried your example, but the result is really bad :
[surveyResult.pdf](https://github.com/surveyjs/surveyjs/files/2723018/surveyResult.pdf)
you should take a look to my result : 
[test.pdf](https://github.com/surveyjs/surveyjs/files/2723023/test.pdf)

**Comment by andrewtelnov** [comment]
@MugiwaraNoMehdi Could you please check the latest source on [our repo](https://github.com/surveyjs/pdf). I have made some modification to make it look better.
You may do PR, it would be great if it fixes some issues you found.

Thank you,
Andrew

**Comment by MugiwaraNoMehdi** [comment]
for me it's done in ten lines of code : 
` var opt = {
        // margin array for the document [top, left, bottom, right]
        margin: [18, 10, 18, 10],
        // export file
        filename: 'test.pdf',
        // this option avoid breaking the survey on an element
        pagebreak: { mode: 'avoid-all' }
      };
      // getting the survey element
      var data = document.getElementById('surveyExportElement');
      // export
      html2pdf().set(opt).from(data).toPdf().get('pdf').then((pdfObject) => {
        // you can add headers or footers here... 
      }).save();`

I am just using html2pdf that does the job itself,

to avoid display issues you must : 

 1 - make #surveyelement have a fixed width, 595px is good for a4 'portrait'

 2 - add max-width for survey elements like for matrix  : 

`#surveyExportElement .sv_q_matrix {
  max-width: 590px;
}
#surveyExportElement .sv_q_matrix td {
  min-width: 0!important;
}
`
because the option " pagebreak: { mode: 'avoid-all' } " work for the height and not for the width.

my code consist of creating a new div, copy the survey in it, export, and hide it on finish.
html2pdf.js use jspdf and html2canvas, and it works really good, if you want I can make a pull request with my code.

Thank you

**Comment by andrewtelnov** [comment]
@MugiwaraNoMehdi I think we will just add ourself. I have added two new issues in our repo.

Thank you,
Andrew

**Comment by gologames** [comment]
Hello,

Look at [PDF Export Library ](https://surveyjs.io/Documentation/Library/?id=Pdf-Export)for SurveyJS, which we developed recently.
