### ISSUE TITLE
Best 

### ISSUE THREAD

**Issue by kywildermuth** [surveyjs/surveyjs#1210]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question

### What is the current behavior?

Javascript not recognized in the custom completedHtml that replaces default completed page

### What is the expected behavior?

Javascript contained in the <script> tag of the string assigned to completedHtml would be recognized successfully

### How would you reproduce the current behavior (if this is a bug)?
Example:

var results_html = 
"<button onclick='myFunction()'>Try it</button> <script type='text/javascript'> function myFunction( {var btn=document.createElement('BUTTON'); document.body.appendChild(btn);} </script>"

In the json, I assign completedHtml:results_html

The html button is recognized, but the javascript function myFunction is not. I have successfully rendered other html elements, like an image, headers, and body, so I can't figure out why the script tag is not working. 

### Specify your

* browser: chrome 
* browser version: Version 67.0.3396.99
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.0.1

**Comment by tsv2013** [comment]
SurveyJS doesn't allow scripting in markup blocks.
