### ISSUE TITLE
Free text option hangs after a validation error

### ISSUE THREAD

**Issue by leomicheloni** [surveyjs/surveyjs#1214]
### Are you requesting a feature, reporting a bug or asking a question?

It's a bug

### What is the current behavior?

The freetext field ("other option") using choices keeps blocked after trying to submit the survey with a space on it.

### What is the expected behavior?

The survey to be submited

### How would you reproduce the current behavior (if this is a bug)?

Using [this json](https://gist.github.com/leomicheloni/00652259d94e3b4a15fb27f01576f9d2) in the online editor https://surveyjs.io/Survey/Builder/ try to select the "other" choice and try to submit the survey, a validation error will be showned, after that just write a space in the text area and try to submit again, the "other" radio button is unable to be selected and the validation error stays visible, after that you cannot continue using the survey.

### Specify your

* browser: Google Chrome (can be test within the online editor)
* browser version: 67.0.3396.99
* surveyjs platform: jquery
* surveyjs version: 1.0.30

![bug](https://user-images.githubusercontent.com/1152021/42281842-07325f62-7fa5-11e8-8f6d-3ad1b1bc7627.gif)

**Comment by andrewtelnov** [comment]
@leomicheloni What OS do you have? 
I have tried in exact version: 67.0.3396.99 and could not reproduce it.

Thank you,
Andrew

**Comment by leomicheloni** [comment]
Windows 10, also tested on Windows 7

**Comment by leomicheloni** [comment]
I wrote the whitespace, I think it is not visible due to the gif conversion

**Comment by andrewtelnov** [comment]
@leomicheloni my bad. I did not read carefully.

Thank you,
Andrew

**Comment by leomicheloni** [comment]
That was fast! thanks!

**Comment by kaphert** [comment]
@andrewtelnov this solution causes a new problem. 

Try typing a word and quickly add a space behind it. It is automatically trimmed. It should only trim on blur, not on value change.
