### ISSUE TITLE
Retrieve and Append property to survey result JSON using 'onPartialSend' (questionid)

### ISSUE THREAD

**Issue by demeee** [surveyjs/surveyjs#1215]
### Are you requesting a feature, reporting a bug or asking a question?

First time of using this, I am trying to post to my server via ajax ‘onPartialSend’, I have an additional field ‘questionid’ attribute on my questions. Would I be able to retrieve this and setup my result struct to look like this:

```
result: [{"questionid":"6F149A8E-CF4B-45A3-8038-24A612E91AC","value":"Nissan"},{[{"questionid":"6F149A8E-CF4B-45A3-8038-24A612E91AC","value":3}]
```
I have added a new property:
```
Survey.JsonObject.metaData.addProperty("questionbase", {name: "questionid:text", default: '00000000000000000000000000000000001'});
```
My question element looks like this:
```
"elements": [{
				"type": "nouislider",
				"questionid": "E05CFB67-84A4-4AE8-8F92-629DFECB86F",
				"name": "On a scale of 0 to 10 how good are you at reflecting on your own performance and seeking feedback from others?"
}]
```
Using an example I found below, an attempted to retrieve the new property ‘questionid’ but, get and error (result.getQuestionByName(...) is null).
Any direction would be helpful. Thanks

#### Provide the test code and the tested page URL (if applicable)

Test code

```
survey
                .onPartialSend
                .add(function(result) {
var modifiedData = Object.keys(result.data).map(function(qName) {
                      return {
                        value: result.data[qName],
                        questionid: result.getQuestionByName(qName).questionid
                      }
                    });
                  
                    document
                        .querySelector('#surveyResult')
                        .innerHTML = "result: " + JSON.stringify(modifiedData);
});


```

### Specify your

* browser: Firefox
* browser version: 
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: v1.0.29

**Comment by andrewtelnov** [comment]
@demeee I have just tried onComplete and then onPartialSend. It works fine. Here is [the plunker](https://plnkr.co/edit/HWbmktfbuyurufRxsrAW?p=preview)

Thank you,
Andrew

**Comment by demeee** [comment]
@andrewtelnov , thanks for the quick response. No sure what was going on there, stripped everything back and yes it works. 

Just wondering is there is way of starting a survey on a particular page or staying on the same page after page refresh? Thanks

**Comment by andrewtelnov** [comment]
@demeee I beleive you are looking for the functionality that we have implemented in [this demo](https://surveyjs.io/Examples/Library/?id=real-patient-history)

Thank you,
Andrew

**Comment by demeee** [comment]
@andrewtelnov thanks, will take a look, your help was appreciated.
