### ISSUE TITLE
File question: show file name in the preview area

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/surveyjs#1218]
### Are you requesting a feature, reporting a bug or asking a question?
Feature request

### What is the current behavior?
File names are shown after files have been choosen nearby the "choose file" button
File names never shown if loaded from survey.data

### What is the expected behavior?
File names are shown always in the preview area

**Comment by tsv2013** [comment]
Proposed solution: change meaning of the [showPreview](https://surveyjs.io/Documentation/Library/?id=questionfilemodel#showPreview) option:
- `true` - show preview image
- `false` - hide any preview
- `"image"` - preview image only
- `"name"` - preview file name only
- `"both"` - preview image and file name

**Comment by tsv2013** [comment]
The proposed design:
![image](https://user-images.githubusercontent.com/3013415/42382796-087b7e40-813e-11e8-83af-b8f219104de1.png)

**Comment by DenisMrGnusa** [comment]
as you say tsv2013, Proposed solution is to change meaning of the 'showPreview' option. but in our case, uploading files is not just a picture document, but also allows questioners to be able to upload document files.

1. default `showPreview` value is `false` - hide any preview;
2. "image" - preview image and its name.
3. "document" - displays the document name as a link and by clicking it can download the file in question.

**Comment by tsv2013** [comment]
@DenisMrGnusa In case of storing files on your service SurveyJS library can't create a link to a downloadable file content. We can create an event in the survey model where you can provide survey model with a link to a file. So we can make both image and label downloadable link.

I don't think we need a separate `document` option due to the file question is not able to divide choosen files on documents, images etc. We can show image preview (if any) and a file name (with a link if provided).

**Comment by dmitrykurmanov** [comment]
We've implemented the feature, it will be available in the next update.
