### ISSUE TITLE
Multiple text questions do not work with saved data (Angular)

### ISSUE THREAD

**Issue by halexiev-hedgeserv** [surveyjs/surveyjs#1229]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

Multiple text questions do not display saved data, i.e. **survey.data = savedData** does not render the saved data for multiple text questions. Single text questions, for example, work fine.

### What is the expected behavior?

Saved data should be rendered for multiple text questions.

### How would you reproduce the current behavior (if this is a bug)?

See plunker below.

#### Provide the test code and the tested page URL (if applicable)

https://plnkr.co/edit/pEosJLHIz6anekmsfCfq?p=preview

### Specify your

* browser: Chrome
* browser version: 67
* surveyjs platform (angular or react or jquery or knockout or vue): Angular
* surveyjs version: 1.0.32

**Comment by andrewtelnov** [comment]
@halexiev-hedgeserv I have added unit tests and fixed them. The fix will be available in the next minor update, on the next week. You may build the library by yourself using the instruction in the ReadMe file.

Thank you,
Andrew
