### ISSUE TITLE
Error changing checkbox/radio question to image picker

### ISSUE THREAD

**Issue by rabberbock** [surveyjs/surveyjs#1232]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
If you add a checkbox/radio question to the page and then change it to an image picker it throws an error.

### What is the expected behavior?
Either there should be no option to change it to an image picker or it should be able to change to an image picker with no errors.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version: 
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version: 1.0.32

**Comment by tsv2013** [comment]
@rabberbock Thank you for the report. I've moved the issue to the corresponding repo - https://github.com/surveyjs/editor/issues/376

**Comment by tsv2013** [comment]
Closed as duplicate
