### ISSUE TITLE
Personalized html exercise in the middle of a questionnaire

### ISSUE THREAD

**Issue by xcesaralejandro** [surveyjs/surveyjs#1234]
Reference: https://surveyjs.io/Examples/Library/?id=survey-quiz

I need to do a custom type of exercise using the quiz I left as a url above. However, html questions do not count as a question / answer.

I can generate my own validation to know if the answer has been correct or not, but I need to add it to the counters that have a survey.

Which survey property is responsible for controlling count of questions that have been answered correctly and the total number of quiz questions?

Since knowing that, I could add my custom question counters correctly answered at the end in the method:
survey
        .onComplete
        .add(function (result) {
          // add the number of custom questions in html and those that have been answered correctly
        });

**Comment by andrewtelnov** [comment]
@xcesaralejandro We have the following functions and event:
[survey.getCorrectedAnswerCount](https://surveyjs.io/Documentation/Library/?id=surveymodel#getCorrectedAnswerCount)
[survey.getInCorrectedAnswerCount](https://surveyjs.io/Documentation/Library/?id=surveymodel#getInCorrectedAnswerCount)
[survey.onIsAnswerCorrect](https://surveyjs.io/Documentation/Library/?id=surveymodel#onIsAnswerCorrect)

Thank you,
Andrew
