### ISSUE TITLE
How to access a value inside of an expression of a "dropdown column" in "matrixdynamic question" to use it within visibleIf?

### ISSUE THREAD

**Issue by akhoury** [surveyjs/surveyjs#1239]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question

### What is the current behavior?

```javascript
      // this is not very helpful since the index may not be 0
      visibleIf: "{life-events.0.life-event} equal 'car-accident'",
      
      // tried these, no luck 

      // visibleIf: "{life-events.life-event} equal 'car-accident'",
      // visibleIf: "{life-event} contains 'car-accident'",
      // visibleIf: "{life-events.life-event} contains 'car-accident'",
      // visibleIf: "{life-events} contains {'life-event': 'car-accident'}",

```

### What is the expected behavior?

```
      visibleIf: "{life-events.life-event} contains 'car-accident'",
```

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:  https://plnkr.co/edit/nDPTc4HsG0G6RudtVK1Z?p=preview

Test code

```javascript

Survey.Survey.cssType = "bootstrap";
Survey.defaultBootstrapCss.navigationButton = "btn btn-green";

window.survey = new Survey.Model({ questions: [
          {
            type: "matrixdynamic",
            name: "life-events",
            title: "Enter the date you are",
            addRowText: "Add Life Event",
            removeRowText: "x",
            columns: [
              {
                name: "life-event",
                cellType: "dropdown",
                title: "Life event(s)",
                columnName: "life-event",
                isRequired: true,
                choices: [
                  {value: "car-accident", text: "Had a car accident"},
                  {value: "left-work", text: "Left work"},
                ]
              },
              {
                name: "life-event-date",
                title: "Date",
                cellType: "text",
                inputType: "date",
                dateFormat: "mm/dd/yy",
                isRequired: true
              }
            ],
            rowCount: 2
          },
          
    { 
      type: "comment", 
      name: "car-accident-comment", 
      title: "How did your car accident happen?",
      
      // this works only if they select "Car accident" as the first life event,
      // if the user selects it in the second row after they click "Add Life Event"
      // it won't work since the index would be 1 
      visibleIf: "{life-events.0.life-event} equal 'car-accident'",
      
      // tried these, no luck 
      // visibleIf: "{life-events.life-event} equal 'car-accident'",
      // visibleIf: "{life-event} contains 'car-accident'",
      // visibleIf: "{life-events.life-event} contains 'car-accident'",
      // visibleIf: "{life-events} contains {'life-event': 'car-accident'}",
      
      isRequired: true
    },
    
    { 
      type: "comment", 
      name: "left-work-comment", 
      title: "How or why did you leave work?",
      
      // same issue here
      visibleIf: "{life-events.1.life-event} equal 'left-work'",
      
      isRequired: true
    }
]});
survey.onComplete.add(function(result) {
	document.querySelector('#surveyResult').innerHTML = "result: " + JSON.stringify(result.data);
});

survey.setValue("region", "Africa");


$("#surveyElement").Survey({model:survey});


```

### Specify your

* browser: Chrome 
* browser version:  67.0.3396.99
* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version: 2.5.16

Thanks!

**Comment by andrewtelnov** [comment]
@akhoury I have created an example: https://plnkr.co/edit/hR7b59TyUaHsmJJtO4OC?p=preview
visibleIf should be: "{row.car-accident} equal 'left-work'" or "{panel.car-accident} equal 'left-work'"
You may use matrixdynamic or paneldynamic or both and make some questons readOnly in the panel.

Thank you,
Andrew

**Comment by akhoury** [comment]
I see, thanks @andrewtelnov but I was hoping to make the expression on a totally different page, not in the same row or panel, is there a way to do that? sorry if I wasn't 100% clear at first

**Comment by andrewtelnov** [comment]
@akhoury ok, I have updated [the example](https://plnkr.co/edit/hR7b59TyUaHsmJJtO4OC?p=preview) accordingly.
Please take into account, that I'm using the latest version 1.0.33.

Thank you,
Andrew

**Comment by akhoury** [comment]
I'm sorry again, but I got confused, do I have to use a panel on the next page in order to access the matrixdynamic's values? is there a way to do it for a simple question?

something like ? 

```javascript
window.survey = new Survey.Model({
  pages: [
    {
    questions: [{
      type: "matrixdynamic",
      name: "life-events-matrix",
      valueName: "life-events",
      title: "Enter the date you are",
      addRowText: "Add Life Event",
      removeRowText: "x",
      columns: [{
        name: "life-event",
        columnName: "life-event",
        cellType: "dropdown",
        title: "Life event(s)",
        isRequired: true,
        choices: [{
          value: "car-accident",
          text: "Had a car accident"
        }, {
          value: "left-work",
          text: "Left work"
        }, ]
        
      }, {
        name: "life-event-date",
        title: "Date",
        cellType: "text",
        inputType: "date",
        dateFormat: "mm/dd/yy",
        isRequired: true
      }],
      rowCount: 1
    }]
  }, {
    questions: [{
      type: "comment",
      visibleIf: "{panel.life-event} equal 'car-accident'"
    }]
  }]
});
```

**Comment by andrewtelnov** [comment]
@akhoury panel dymic and matrix dynamic are shared the same data, valueName: "life-events".
For every row in matrix dynamic, you will have one panel in panel dynamic. On adding/removing/changing rows in matrix dynamic, data in panel dynamic will change accordingly.
To which row are you going to bind your question?
Simple question is one value. You want to edit the array. How do you want to edit the array in one text question?
Panel dynamic solves this issue. It was created to edit the array of objects, same as matrix. 

Thank you,
Andrew

**Comment by akhoury** [comment]
I see I see, it makes sense now, i guess I kind of wished there is a way to `eval` a full javascript expression, even if there is a little bit of performance hit; with a small and finite number of questions it won't be a huge hit.

Thank you for your quick responses! and awesome work!

**Comment by akhoury** [comment]
by the way, this is kind of what i mean about being able to execute any javascript expression in the "visibleIf" expression, along with limiting the context in it to the `surveyModel.data` 

now I can do something like:

```javascript
visibleIf: "eval( this['life-events'] ? this['life-events'].map(e => e['life-event']).indexOf('car-accident') > -1 : false )",
```
I check if there is "eval( ... )" in the expression, if there is, I `eval` it with a context.

example here
https://plnkr.co/edit/LJq0ppyJyVDnJYdKFg4d?p=preview

However, i have to do it on `onAfterRenderPage`, `onValueChanged` events and after the survey is initialized at first.

**Comment by andrewtelnov** [comment]
@akhoury visibleIf expression should return true or false.
You may use built-in or your own custom functions. Here is [the documentation](https://surveyjs.io/Documentation/Library/#visibility)

Thank you,
Andrew

**Comment by akhoury** [comment]
Oh! "functions in expressions" are exactly what I want! thanks!
