### ISSUE TITLE
Custom CSS classes not working after upgrade 

### ISSUE THREAD

**Issue by masciugo** [surveyjs/surveyjs#1246]
After upgrading to 1.0.33 (from 1.0.25) my matrixdynamic and paneldynamic css custom classes don't work anymore

my css Object is:

```
const myCss =
{
  "pageTitle": "hidden",
  "row": "sv_row",
  "question": {
    "title": "text-bold"
  },
  "matrixdynamic": {
  //   "root": "table",
    "button": "btn btn-sm btn-outline",
    "buttonAdd": "btn-default",
    "buttonRemove": "btn-danger"
  },
  "paneldynamic": {
    "root": "paneldynamic-root",
    "button": "btn btn-sm btn-outline",
    "buttonAdd": "btn-default",
    "buttonRemove": "btn-danger"
  }
}

```

**Comment by masciugo** [comment]
just adding `"root": "sv_bootstrap_css"` solves the problem. I already had `Survey.Survey.cssType = 'bootstrap'` so I don't know exactly why it works now

**Comment by tsv2013** [comment]
We've changed themes management a bit. Now you need to call
```JS
Survey.StylesManager.applyTheme("bootstrap");
```

instead of the `Survey.Survey.cssType = 'bootstrap'`
