### ISSUE TITLE
Boolean resets value to indeterminate when default value is false in a matrix dynamic/ dynamic panel

### ISSUE THREAD

**Issue by ashygk** [surveyjs/surveyjs#1249]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?
when a matrix dynamic / dynamic panel has one of the column as boolean and its default value is set to false. And I add multiple rows and delete one, the boolean columns are setting its value as indeterminate for all rows

### What is the expected behavior?

boolean should reset to false as it is the default value

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@ashygk It works fine for me. Here is [the example](https://plnkr.co/edit/FFqc7rNEX4u3gpVV6Mp6?p=preview)

Thank you,
Andrew

**Comment by ashygk** [comment]
@andrewtelnov  Please try with your previous plunkr example json.

`var json = {
    questions: [
        {
            type: "matrixdynamic",
            name: "teachersRate",
            confirmDelete: true,
            confirmDeleteText: "Delete?",
            title: "Please rate your teachers",
            addRowText: "Add Subject",
            horizontalScroll: true,
            columnMinWidth: "130px",
            columnColCount: 1,
            cellType: "radiogroup",
            choices: [
                {
                    value: 1,
                    text: "Yes"
                }, {
                    value: 0,
                    text: "Sometimes"
                }, {
                    value: -1,
                    text: "No"
                }
            ],
            columns: [
                {
                    name: "subject",
                    title: "Select a subject",
                    isRequired: true,
                    cellType: "dropdown",
                    choices: [
                        "English: American Literature",
                        "English: British and World Literature",
                        "Math: Consumer Math",
                        "Math: Practical Math",
                        "Math: Developmental Algebra",
                        "Math: Continuing Algebra",
                        "Math: Pre-Algebra",
                        "Math: Algebra",
                        "Math: Geometry",
                        "Math: Integrated Mathematics",
                        "Science: Physical Science",
                        "Science: Earth Science",
                        "Science: Biology",
                        "Science: Chemistry",
                        "History: World History",
                        "History: Modern World Studies",
                        "History: U.S. History",
                        "History: Modern U.S. History",
                        "Social Sciences: U.S. Government and Politics",
                        "Social Sciences: U.S. and Global Economics",
                        "World Languages: Spanish",
                        "World Languages: French",
                        "World Languages: German",
                        "World Languages: Latin",
                        "World Languages: Chinese",
                        "World Languages: Japanese"
                    ]
                }, {
                    name: "explains",
                    title: "Clearly explains the objectives"
                }, {
                    name: "interesting",
                    title: "Makes class interesting"
                }, {
                    name: "button",
                    cellType: "text",
                    title: "Show More Information"
                }, {
                  name: "yes/no",
                  cellType: "boolean",
                  defaultValue: "false"
                }
            ],
            rowCount: 2
        }
    ]
};`

**Comment by andrewtelnov** [comment]
@ashygk I have updated the plunker. It works fine as well. Did I miss something?

Thank you,
Andrew

**Comment by ashygk** [comment]
Please don't enter any information in the rows and give it a try.

**Comment by andrewtelnov** [comment]
@ashygk got it. I can see intermidiate value shows after a row removing.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@ashygk I have fixed it finally. A unit test is added.

Thank you,
Andrew
