### ISSUE TITLE
Invisible page question appears in final survey result 

### ISSUE THREAD

**Issue by Jojo109** [surveyjs/surveyjs#1258]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug

### What is the current behavior?

There is unexpected question value in final survey result.

### What is the expected behavior?

The unexpected question value should not exist in final survey result.  

### How would you reproduce the current behavior (if this is a bug)?
1. The testing page is set to be visible when clicking the item 1 radio button of question 1. However, 
the paneldynamic question from testing page is exist in final result when clicking item2 and 3 radio button. The paneldynamic question is expected not to appear in final result when clicking item2 and 3 radio button. Moreover, when the visableIf property is deleted from comment question, The final result behave normally. 

![survey](https://user-images.githubusercontent.com/39783820/43582810-352b566a-9690-11e8-8085-62a8f07d03e1.gif)
![survey2](https://user-images.githubusercontent.com/39783820/43582813-3666da36-9690-11e8-8dc8-3923806e88ab.gif)

2. The onValueChanged method of survey model is also expected to be fired when submitting the form?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://next.plnkr.co/edit/12BKkACq42VWkrwV

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version: 1.0.25

**Comment by tsv2013** [comment]
@Jojo109 Thank you for the report. We'll fix it.

**Comment by Jojo109** [comment]
@tsv2013  Thanks

**Comment by andrewtelnov** [comment]
@Jojo109 A unit test is added and the bug is fixed. It will be available in the next minor update.

Thank you,
Andrew

**Comment by Jojo109** [comment]
@andrewtelnov Thanks
