### ISSUE TITLE
setChoices functionality

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/surveyjs#1262]
from the https://github.com/surveyjs/surveyjs/issues/1257#issuecomment-410222906:

> May I know if Surveyjs is planning to add support for setChoices just as SetValue is supported, this could be a great addition as sometimes, q.choices = [1,2,3] doesn't take into account all the side effects that are expected in Vuejs

**Comment by dmitrykurmanov** [comment]
@omkardusane would you like to subscribe your use case in gretater details?

**Comment by omkardusane** [comment]
Sure, 
I will share the use case below. 

In our case, the choices of some questions are available by API calls or other ways which involve authentication, hence 'ChoicesByUrl' is not suited. There also,  I have 4 different panels whose visibility is dependent on one question and four of them have the choice-oriented-questions named "Column", Also one of those panels have a question of type DynamicPanel, which inside itself, has more choice-oriented-questions , whose choices are dependent on a same source array I talked about above.
 So In the lifecycle of my application, when I have the choices array, I set it using a setChoices function that we created
```
this.srvHandler.setChoices = (name, choices) => {
      this.srvHandler.getAllQuestions().forEach(q => {
        if (q.name === name) {
          q.choices = choices;
        }
        if (q.getType() === "paneldynamic") {
          this.srvHandler.setChoicesInDP(q, name, choices);
        }
      });
    };
    this.srvHandler.setChoicesInDP = (dpQuestion, name, choices) => {
      if (dpQuestion.getType() === "paneldynamic") {
        dpQuestion.items.forEach(c => {
          c.panel.elements.forEach(innerQstn => {
            if (innerQstn.name === name) {
              innerQstn.choices = choices;
            }
          });
        });
      }
    };
```
which needs another function setChoicesInDP to be able to change choices of questions which have the same name but are nested into dynamic panels.

If you want I can share the SurveyJSON with you via a non-public medium such as e-mail. 
thanks.

**Comment by andrewtelnov** [comment]
@omkardusane I can see that you have solved the issue by adding an additional code.
We will keep this scenario in mind. However, I am not sure we will be able to introduce it shortly.
Panel Dynamic doesn't know about it's children. In fact the scenario could be more complicated. For example, you may have a nested Panel Dynamic inside a root Panel Dynamic and you may want to change a matrix column or matrix row in it (add/remove it), or change any other property of any other question.
We will do some experiments, but unfortunately I can't promise that we would be able to solve this issue in a good way.
Anyway, thank you for the feedback.

Thank you,
Andrew

**Comment by omkardusane** [comment]
Okay, This helps us understand more about surveyjs project and its roadmap. 
Thanks Dmitry and Andrew

**Comment by andrewtelnov** [comment]
@dmitrykurmanov @omkardusane It has implemented as a general functionality. On changing any property of a element in panel template, all elements in the dynamic panels will be updated acordingly.
Here is [the issue](https://github.com/surveyjs/surveyjs/issues/1265)

Thank you,
Andrew
