### ISSUE TITLE
"setState(...): Cannot update" error during pageVisibilityChanged Event

### ISSUE THREAD

**Issue by bernardworthy** [surveyjs/surveyjs#1269]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug

### What is the current behavior?

In the React version of SurveyJS, I'm getting the following error during the pageVisibilityChanged event.
 
Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.

### What is the expected behavior?

No error. 

### How would you reproduce the current behavior (if this is a bug)?

Answer the question in the sample at the url below and then watch the console.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: http://jsbin.com/kiluyusaca/edit?html,console,output

Test code: http://jsbin.com/kiluyusaca/edit?html,console,output

### Specify your

* browser: ANY
* browser version: ANY
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.0.24+ (1.0.23 and below do not show this error)

**Comment by dmitrykurmanov** [comment]
I've reproduced the problem

**Comment by dmitrykurmanov** [comment]
We've fixe it. Fix will be available in the next minor.

**Comment by bernardworthy** [comment]
Thanks for the quick fix @dmitrykurmanov!

**Comment by dmitrykurmanov** [comment]
@bernardworthy thank you for the example!

**Comment by bernardworthy** [comment]
Sure thing. We love this library and I've used it on a few projects for different clients, so great to see the awesome support. Keep it up!
