### ISSUE TITLE
How do you style the custom SortableJS widget?

### ISSUE THREAD

**Issue by ChrisAldridgeRIT** [surveyjs/surveyjs#1271]
### Are asking a question?
Yes. How do I go about styling the elements when using the sortablejs widget? Or how do I add classes to the main container elements and draggable item 

### What is the current behavior?
At the moment there seems to be no classes on the related object and all the styling is rendered inline?

### What is the expected behavior?
Control styles via extra css file or assign classes via config file?

### How would you reproduce the current behavior (if this is a bug)?
You can see what it does on the actual demo page
https://surveyjs.io/Examples/Library/?id=custom-widget-sortablejs&platform=jQuery&theme=default

Tested page URL:
https://surveyjs.io/Examples/Library/?id=custom-widget-sortablejs&platform=jQuery&theme=default

### Specify your

* browser: Chrome on Mac

**Comment by dmitrykurmanov** [comment]
We have the same issue in the widgets repo. Please go to: https://github.com/surveyjs/surveyjs/issues/1271
