### ISSUE TITLE
goNextPageAutomatic causes validation error to show up on page load

### ISSUE THREAD

**Issue by yidan** [surveyjs/surveyjs#1275]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

When goNextPageAutomatic is true, sometimes the field validation error (for required) will show up before the user enters anything in the field. 

### What is the expected behavior?

The field validation should happen after user input

### How would you reproduce the current behavior (if this is a bug)?

Set goNextPageAutomatic to be true, 
One question per page (that's my current setting, not sure if this is related) 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: 
https://surveyjs.io/published?id=cddefda3-d450-4804-ac3b-274898e09212

It happens to both my local copy (without using service) and the service version. 

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@yidan I have created a [pnkr example](https://plnkr.co/edit/fuRbhIeExhod8zBAIkoj?p=preview) with your survey.
Could you please provide an instruction how to reproduce the issue?
I have just tried it and everything works as expected.

Thank you,
Andrew

**Comment by yidan** [comment]
@andrewtelnov  Hi Andrew, could you try a few more times? I happened to me in the plnkr example. After hitting the Next button and going to this page, before I enter anything, the error message shows up. 
![screen shot 2018-08-14 at 8 03 00 am](https://user-images.githubusercontent.com/1720237/44093252-9f44b80a-9f98-11e8-9385-ad4a4f190351.png)

Appreciate your help!

**Comment by andrewtelnov** [comment]
@yidan Yes, I was able to reproduce it in MS Edge. It works fine in Chrome and other browsers.
We will work on the fix.

Thank you,
Andrew

**Comment by yidan** [comment]
@andrewtelnov Thanks Andrew. It does not work in Chrome for me, either. I'm on Chrome 68.0.3440.106 (Official Build) (64-bit), Mac OS X.

**Comment by andrewtelnov** [comment]
@yidan I beleive I have fixed the issue with my last commit. The fix will be available in the next minor update.

Thank you,
Andrew

**Comment by yidan** [comment]
@andrewtelnov  Thanks Andrew! Looking forward to the update :)
