### ISSUE TITLE
Changing template element visible property in PanelDynamic will lead to error

### ISSUE THREAD

**Issue by Jojo109** [surveyjs/surveyjs#1278]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?
I find a bug after updating survey-react to version 1.0.37 recently. This bug does not appear when I using survey-react in version 1.0.25. Any idea to get this bug? 

![image](https://user-images.githubusercontent.com/39783820/44196763-656ec480-a16f-11e8-9d1f-34de4c065006.png)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version: 1.0.37

**Comment by andrewtelnov** [comment]
@Jojo109 yes, onTemplateElementPropertyChanged method was added shortly.
I could not understand why it is called with isVisible property, since it should not.
I will try to make some checks, any chance to reproduce this issue for me?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@Jojo109 Unit test is added and the bug is fixed. It will be available in v1.0.38

Thank you,
Andrew
SurveyJS Team

**Comment by Jojo109** [comment]
@andrewtelnov  Thank you. 
However, I still give you the demo and script for my application.
The script link is here.
`https://next.plnkr.co/edit/12BKkACq42VWkrwV`

![survey2](https://user-images.githubusercontent.com/39783820/44206616-01f38f80-a18d-11e8-8879-2740793063ea.gif)

The error does not appear in version 1.0.25. It appears in version 1.0.37. 
Is the latest version solving problem in my application? Thanks

**Comment by andrewtelnov** [comment]
@Jojo109 If you build version from our source, there is an instruction in the readme file, then the problem will go away. You may go back to v1.0.35 and then update to v1.0.38 that we release on the next week.

Thank you,
Andrew

**Comment by Jojo109** [comment]
@andrewtelnov Thanks. 
I go back to v1.0.35. But is the bug **Invisible page question appears in final survey result #1258** fixed in v1.0.35? Then, my application can work fine in v1.0.35.

**Comment by andrewtelnov** [comment]
@Jojo109   v1.0.38 is available.

Thank you,
Andrew
