### ISSUE TITLE
Show survey pages as a tabs

### ISSUE THREAD

**Issue by NafanyaVictorovna** [surveyjs/surveyjs#1279]
### Are you requesting a feature, reporting a bug or asking a question?
Question: Can you help me with my issue: I have survey assessment with several pages and want to display them all in the same time use tabs, not buttons. Also I want to select any of it without the order - like page tabs in survey builder - is it possible?

### What is the current behavior?

Just the buttons, and can go to the page by order

### What is the expected behavior?

any page can be selected/opened

### Specify your

* browser: Chrome
* surveyjs platform: jquery 
* surveyjs version: surveyjs v1.0.16

**Comment by andrewtelnov** [comment]
@NafanyaVictorovna Yes, it is possible. We do it in our SurveyJS Editor in the designer and in the Test tabs.
Designer shows the same SurveyJS widget, but in design mode.

You will need the following:
[currentPage property](https://surveyjs.io/Documentation/Library/?id=surveymodel#currentPage) or [currentPageNo property](https://surveyjs.io/Documentation/Library/?id=surveymodel#currentPageNo) and [onCurrentPageChanged event](https://surveyjs.io/Documentation/Library/?id=surveymodel#onCurrentPageChanged)

Thank you,
Andrew

**Comment by NafanyaVictorovna** [comment]
@andrewtelnov  I see how your advice can help with custom selection, but how it can help to show pages in assessment like tabs - can not undestand?

**Comment by andrewtelnov** [comment]
@NafanyaVictorovna Do you want to show all pages at once as a list?
In this case, there is a property [survey.isSinglePage](https://surveyjs.io/Documentation/Library/?id=surveymodel#isSinglePage)
All pages will be converted into panels and will be added into one large single page. You may defined your own styles for these root panels, but using [onUpdatePanelCssClasses event](https://surveyjs.io/Documentation/Library/?id=surveymodel#onUpdatePanelCssClasses).
You will need to panels that parent is page, so it is a former page.
```
var pnl = options.panel;
var isRoot = !!pnl.parent && !!pnl.parent.getType() == "page";
```
Here is [the example](https://surveyjs.io/Examples/Library/?id=survey-cssclasses) of using the similar event for question.

Thank you,
Andrew

**Comment by dinopeterson** [comment]
Hi Nataly,
Would you be willing to share the code (CSS, JS etc. ) that you have created to place each in its own tab ?
Many thanks,

**Comment by yuvrajhshinde** [comment]
Hi Nataly,

Can you please share your code for adding each page in its own tab ?

Regards,
Yuvraj
