### ISSUE TITLE
Can I set required property to fields if some condition?

### ISSUE THREAD

**Issue by NafanyaVictorovna** [surveyjs/surveyjs#1280]
### Are you requesting a feature, reporting a bug or asking a question?

Questiuon/Feature
Can I add required property to specific  question if some condition is true?

### What is the current behavior?
No I can do field visible or enable by conditions

### What is the expected behavior?

Want to have opportunity add required property by condition
*****
If it possible do it for questions from different pages

### Specify your

* browser: Chrome
* surveyjs platform survey js v1.0.16

**Comment by andrewtelnov** [comment]
@NafanyaVictorovna Unfortunately, we do not have isRequiredIf property yet. However, it was asked several times. However, you may use an expression validator. Here is [the example](https://surveyjs.io/Examples/Library/?id=validators-expression). It is a more general solution, including your scenario.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@NafanyaVictorovna Here is [the plunker](https://next.plnkr.co/edit/O3rluyS8tj3bqqLc). What should I do to see the incorrect behavior?

Thank you,
Andrew

**Comment by NafanyaVictorovna** [comment]
@andrewtelnov  just go to next page and try to complete

**Comment by andrewtelnov** [comment]
@NafanyaVictorovna The issue that I see:
Set rating to 2, go to the second page, press Complete - get error.
Comeback to first page, set rating to 4, go to the second page - the error is still here, however on pressing complete, the survey is completed.
Are you taking about this issue?

Thank you,
Andrew

**Comment by NafanyaVictorovna** [comment]
@andrewtelnov Yes, but for me on plunker it is not completes

**Comment by NafanyaVictorovna** [comment]
@andrewtelnov 
Thank you. I've got what did you mean. And corrected my expression - it works good, as I want.
