### ISSUE TITLE
Validation message for input type number

### ISSUE THREAD

**Issue by gajayreddy9** [surveyjs/surveyjs#1284]
### Are you requesting a feature, reporting a bug or asking a question?

bug/question

### What is the current behavior?

I am using the input type number element and made it required. When I submit the survey without entering any value into the field the validation message says "Please answer the question." which is good but when I type in some characters and submit the survey it says   "Please answer the question." which is not very clear to the user. This happens in fire fox and IE number, in google chrome it is better as it does not allow any characters when you type into the number field. I tried adding the regex validator for only numbers but it still says "Please answer the question." when I enter some text, when I enter some decimal like 35.54 then it shows my custom message. 
 

### What is the expected behavior?

I would like to see "Please enter a number." or something like that makes more sense to the user when we enter text into the number field in firefox and IE.

### How would you reproduce the current behavior (if this is a bug)?

Can use the survey editor.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: firefox and IE.
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@gajayreddy9 The best way to solve it, is to use a third-party input text with support numeric entering. Here is [the example](https://surveyjs.io/Examples/Library/?id=custom-widget-inputmask)
The easy way is to set the requiredErrorText property of the question on: "Please enter a number.".

Thank you,
Andrew

**Comment by gajayreddy9** [comment]
The requiredErrorText property works for my situation. I completely missed it. Thank you for the help.
