### ISSUE TITLE
Dropdown not unescaping carachters in display mode

### ISSUE THREAD

**Issue by teocomi** [surveyjs/surveyjs#1288]
Hello,

It seems that special characters are not un-escaped in display mode.

Display mode:
![image](https://user-images.githubusercontent.com/2679513/44469591-be32d700-a61f-11e8-9782-a6cb835e5490.png)

Edit mode:
![image](https://user-images.githubusercontent.com/2679513/44469606-c854d580-a61f-11e8-9d96-505aa950fbef.png)

Thanks for the great library!

### Specify your

* browser: chrome
* browser version: 70.0.3529.3
* surveyjs platform: vue
* surveyjs version: 1.0.39

**Comment by andrewtelnov** [comment]
@teocomi I could not reporduce the issue. Could you please modify (this plunker example)[https://plnkr.co/edit/quh068OgvQXPjIDNDYEU?p=preview] so we can reproduce it?

Thank you,
Andrew

**Comment by teocomi** [comment]
Turns out it's because of showdown, https://next.plnkr.co/edit/aDPF0I5mFSr4Jepx

**Comment by andrewtelnov** [comment]
@teocomi Will it work for you? http://plnkr.co/edit/PvOrbTPdmBn20h3cY0O2?preview&p=preview

Thank you,
Andrew

**Comment by teocomi** [comment]
Sure, thanks!
