### ISSUE TITLE
create a Question object with JSON

### ISSUE THREAD

**Issue by Yourgene** [surveyjs/surveyjs#1290]
### Are you requesting a feature, reporting a bug or asking a question?
asking a question

### What is the question ?
Hello, 
I have a json file containing a list of questions, for example : 

`var json = {
  "questions": [
    {
      "name": "name",
      "type": "text",
      "title": "Please enter your name:",
      "placeHolder": "enter your name"
    }, {
      "name": "birthdate",
      "type": "text",
      "inputType": "date",
      "title": "Your birthdate:"
    }
} `

I would like, from this json, to create a Question object for each question, but without going through the survey method  `var survey = new Survey.Model(json);` . For reasons, I want to create each question individually, add them into new pages, and add the pages into the survey.

Is there a way to create a Question object just by passing a json in it, something like 
`var jsonQuestion1 = {
      "name": "name",
      "type": "text",
      "title": "Please enter your name:",
      "placeHolder": "enter your name"
    }`
`var question1 = new Survey.Question(jsonQuestion1);`
Or the only way is to parse the json and add the properties manuallly ?

Thank you in advance.

### Specify your

* browser: chrome
* surveyjs platform (angular or react or jquery or knockout or vue): react

**Comment by andrewtelnov** [comment]
@Yourgene Here is the code snip, questionJson - is the Json for individual question:
```
function createQuestion(questionJson) {
  if(!questionJson.type) return null;
  var question = Survey.JsonObject.metaData.createClass(questionJson.type);
  if(!question) return null;
  Survey.JsonObject.metaData.toObject(questionJson, question);
  return question;
}
```
I did not test it, but it should work.

Thank you,
Andrew

**Comment by Yourgene** [comment]
Hi, 
Thanks for your quick reply.

I had to change the code a bit, I replaced : 
`Survey.JsonObject.metaData.toObject(questionJson, question);`
to
`Survey.JsonObject.prototype.toObject(questionJson, question);`

and it works as intended !

Thanks a lot,
Vlad
