### ISSUE TITLE
Cannot display error message according to the localization in Matrix Dropdown Column

### ISSUE THREAD

**Issue by KLC215** [surveyjs/surveyjs#1292]
### Are you requesting a feature, reporting a bug or asking a question?
May be a bug

### What is the current behavior?
![survey1](https://user-images.githubusercontent.com/15123751/44521391-78e8d500-a705-11e8-8fe5-ceaceac2e45a.gif)

I simulated to change locale in `React - componentDidMount` with `onAfterRenderSurvey` event

### What is the expected behavior?
Since I added my custom property,
```js
Survey.JsonObject.metaData.addProperty('matrixdropdowncolumn', {
  name: 'requiredErrorText',
  isLocalizable: true,
});
```
I expect the survey should show error message by current locale.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: [https://next.plnkr.co/edit/HICIfTipkzn1INeS](https://next.plnkr.co/edit/HICIfTipkzn1INeS)

### Specify your

* browser: **Google Chrome**
* browser version: **68.0.3440.106**
* surveyjs platform (angular or react or jquery or knockout or vue): **React**
* surveyjs version: **1.0.38**

**Comment by andrewtelnov** [comment]
@KLC215 I have added requiredErrorText into column. The property has to be bind with the template question to work correctly.

Thank you,
Andrew

**Comment by KLC215** [comment]
Thanks @andrewtelnov :)
