### ISSUE TITLE
onProcessHtml no longer called for HTML Question

### ISSUE THREAD

**Issue by jgarver** [surveyjs/surveyjs#1294]
The fix for #1162 changed question-html.html to reference locHtml instead of processedHtml.  The result is that onProcessHtml isn't triggered for HTML questions.

I'm using the jquery build (knockout templates).

Thanks for everything you do!

**Comment by andrewtelnov** [comment]
@jgarver Yes, indeed. I have added a unit test and fix it. The fix will be in the next minor version. We will release it on the next week.

Thank you for using the product!
Andrew

**Comment by jgarver** [comment]
Fantastic!  Thanks!
