### ISSUE TITLE
Radio item id's

### ISSUE THREAD

**Issue by marjan-tropper** [surveyjs/surveyjs#1302]
### What is the current behavior?
For radio groups currently only the first option has an id and the rest of the options don't have any id's. 

### What is the expected behavior?
Is there a way to set id's for all options in a radio group? 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): Angular
* surveyjs version:

**Comment by tsv2013** [comment]
Hello,

I've fixed it via the https://github.com/surveyjs/surveyjs/commit/02ffd2284240834de44e17f5dca82d252693a44d commit.
Fix will be available in the nearest update.

Thanks, Serge
SurveyJS Team
