### ISSUE TITLE
surveyjs.io/org webapp is stopped

### ISSUE THREAD

**Issue by fkugel** [surveyjs/surveyjs#1309]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

website is down

### What is the expected behavior?

http://surveyjs.io
http://surveyjs.org 
...can be viewed

### How would you reproduce the current behavior (if this is a bug)?

visit website

**Comment by andrewtelnov** [comment]
@fkugel Please refer to [this issue](https://github.com/surveyjs/surveyjs/issues/1307)
Here is [some additional information](https://www.theregister.co.uk/2018/09/04/azure_its_getting_hot_in_here/)

Thank you,
Andrew

**Comment by fkugel** [comment]
closed as duplicate of 
https://github.com/surveyjs/surveyjs/issues/1307
