### ISSUE TITLE
Float number with decimal point

### ISSUE THREAD

**Issue by NafanyaVictorovna** [surveyjs/surveyjs#1312]
Question

Now I can set number input type, but it is only integer.

I want to input numbers for height or weight, for example, and expect to have opportunity input float numbers and manage count of numbers after decimal point.
How can I do it?

* Chrome
* surveyjs platform: jquery:
* surveyjs version:  v1.0.16

**Comment by tsv2013** [comment]
I've just tested number input:
```JSON
{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "text",
     name: "question1",
     inputType: "number"
    }
   ]
  }
 ]
}
```
And it works ok for me.
Probably I've missed someth?

**Comment by tsv2013** [comment]
I've noticed that you are using SurveyJS of the version: v1.0.16. I think it is better to use the latest version v1.0.42

**Comment by NafanyaVictorovna** [comment]
@tsv2013 but how can I manage the count of numbers after dot? for example I want enter no more than five digits after decimal point,  I tried to use regexp but it doesn't work for me. My regexp:
^\s*(?=.*[1-9])\d*(?:\.\d{1,5})?\s*$

**Comment by tsv2013** [comment]
I tested this survey, it seems it works as expected:

````JSON
{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "text",
     name: "question1",
     validators: [
      {
       type: "regex",
       text: "Not more than  5 digits after separator",
       regex: "^\\d*?.\\d{0,5}$"
      }
     ],
     inputType: "number"
    }
   ]
  }
 ]
}
````

**Comment by NafanyaVictorovna** [comment]
@tsv2013 I tested your json via builder (online) and it doesn't works.  
The builder and survey js work with different code and I only can be sure test it via API?

**Comment by tsv2013** [comment]
I've tested the above JSON in the online builder, in the "Test Survey" mode. Yes, it doesn't work like inputmask - you still able to enter more than 5 digins after separator. But if you want to complete survey or goto text page - the validation triggers and velidation message appears.

If you want to use the input mask functionality you can check this demo - https://surveyjs.io/Examples/Library/?id=custom-widget-inputmask&platform=jQuery&theme=default
It shows how to integrate the jQuery.imputmask (https://robinherbots.github.io/Inputmask/) into SurveyJS library

**Comment by NafanyaVictorovna** [comment]
@tsv2013 Input mask is good solution - thank you,  it helped.
