### ISSUE TITLE
Certain input components force following lines to shift right

### ISSUE THREAD

**Issue by firedraco** [surveyjs/surveyjs#1314]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
Certain input components such as dropdowns cause strange wrapping in some cases when later elements are on new lines (that is, startWithNewLine is set to true). Specifically, it seems like the dropdown element at least causes following lines to begin shifted to the right due to the float: left applied to them causing them to be shoved over by the dropdown extending downwards farther than expected. 

### What is the expected behavior?
Elements on each line are not impacted by elements on the previous lines.

### How would you reproduce the current behavior (if this is a bug)?
See following test data

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
`https://surveyjs.io/builder`

Test code
```
{
 title: "Test",
 pages: [
  {
   name: "you",
   elements: [
    {
     type: "dropdown",
     name: "you_prefix",
     title: "Prefix",
     titleLocation: "top",
     choices: [
      "Mr.",
      "Mrs.",
      "Ms."
     ]
    },
    {
     type: "text",
     name: "you_first",
     startWithNewLine: false,
     title: "First Name",
     isRequired: true,
     titleLocation: "top"
    },
    {
     type: "text",
     name: "you_middle",
     startWithNewLine: false,
     title: "M. I.",
     titleLocation: "top",
     size: 1
    },
    {
     type: "text",
     name: "you_last",
     startWithNewLine: false,
     title: "Last Name",
     isRequired: true,
     titleLocation: "top"
    },
    {
     type: "text",
     name: "you_title",
     title: "Job Title",
     isRequired: true,
     titleLocation: "top"
    },
    {
     type: "text",
     name: "you_phone",
     startWithNewLine: false,
     title: "Phone Number (Preferred)",
     titleLocation: "top",
     inputType: "tel"
    },
    {
     type: "text",
     name: "you_email",
     startWithNewLine: false,
     title: "Email",
     validators: [
      {
       type: "email"
      }
     ],
     titleLocation: "top"
    }
   ],
   questionTitleLocation: "top",
   title: "Your Information",
   description: "You, the person completing the form"
  }
 ],
 sendResultOnPageNext: true,
 showQuestionNumbers: "off",
 questionErrorLocation: "bottom",
 showProgressBar: "top",
 startSurveyText: "Start",
 pagePrevText: "Previous",
 pageNextText: "Next"
}
```

### Browser info
For Internet Explorer 11, this bug showed up in our local environments which was using SurveyJS 1.0.29 for React. It did not show up in Firefox, Chrome, or Edge.
I also tested for this bug in IE 11 and Firefox using the surveyjs online builder at `https://surveyjs.io/builder`. This I believe uses knockout and SurveyJS 1.0.41. The bug appears in both Firefox and IE 11 (at least, I did not test other browsers), and also shows up in the editor itself.

**Comment by dmitrykurmanov** [comment]
_Reproduced in the online builder, with local surveyjs lokk ok in bootstrap and default themes_

**Comment by Chris-Boe** [comment]
@dmitrykurmanov Can you explain your comment? You were able to reproduce the bug but then closed the issue?

**Comment by dmitrykurmanov** [comment]
@Chris-Boe @firedraco I am sorry. I forgot about clarifications :). I've fixed it via the https://github.com/surveyjs/surveyjs/commit/20c8b503c2df6a52b106a7b76293f33942c7bf52  Fix will be available in the next minor update.
