### ISSUE TITLE
Setting minRowCount = rowCount does not hide delete buttons when adding a row

### ISSUE THREAD

**Issue by summumeng** [surveyjs/surveyjs#1315]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

I want to remove the delete buttons from a dynamic matrix, and replace them with new delete buttons, for this I implement the code below:

    surveyModel.onMatrixRowRemoved.add(function(sender, options) { 
        options.question.minRowCount = options.question.rowCount;
    });
    surveyModel.onMatrixRowAdded.add(function(sender, options) {         
        options.question.minRowCount = options.question.rowCount;        
    });

It will only work for surveyModel.onMatrixRowRemoved, but not for surveyModel.onMatrixRowAdded.
If I delete a row the delete-buttons do not show, if I add a row then the delete-buttons does show.

To solve this I modified the survey.angular.js file, I added the line: this.fireCallback(this.visibleRowsChangedCallback); to the QuestionMatrixDynamicModel.prototype.addRow function, see below:

    /**
     * Creates and add a new row.
     */
    QuestionMatrixDynamicModel.prototype.addRow = function () {
        var options = { question: this, canAddRow: this.canAddRow };
        if (!!this.survey) {
            this.survey.matrixBeforeRowAdded(options);
        }
        if (!options.canAddRow)
            return;
        var prevRowCount = this.rowCount;
        this.rowCount = this.rowCount + 1;
        if (!this.isValueEmpty(this.defaultRowValue)) {
            var newValue = this.createNewValue(this.value);
            if (newValue.length == this.rowCount) {
                newValue[newValue.length - 1] = this.defaultRowValue;
                this.value = newValue;
            }
        }
        if (this.data) {
            this.runCellsCondition(this.getDataFilteredValues(), this.getDataFilteredProperties());
        }
        if (this.survey) {
            if (prevRowCount + 1 == this.rowCount)
                this.survey.matrixRowAdded(this);
                this.fireCallback(this.visibleRowsChangedCallback); // Added line !!!!!!
        }
    };

### What is the expected behavior?

When setting: minRowCount = rowCount, this should hide the delete buttons

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by dmitrykurmanov** [comment]
@summumeng I've added the code changes above to the project via the https://github.com/surveyjs/surveyjs/commit/14f91a19635cb86d0d9a205a638c0920691e5fc7. Thank you!

**Comment by summumeng** [comment]
Thanks,

I still have a question: I do not seem to be able to get this commit, what I did was:

In the package.json file I set for dependencies:

  "dependencies": {
    "@types/knockout": "3.4.46",
    "package": "git+https://github.com/surveyjs/surveyjs.git#14f91a1"
  }

When I do an npm install in the node_modules\survey-angular directory the reply is:

survey-angular@1.0.42 C:\ionic\testionicsurveyjs\myApp\node_modules\survey-angul
ar
`-- surveyjs@1.0.37  extraneous (git+https://github.com/surveyjs/surveyjs.git#14
f91a19635cb86d0d9a205a638c0920691e5fc7)

Which does not seem to update the survey.angular.js file.

**Comment by dmitrykurmanov** [comment]
The fix will be available in the next patch update, so it will be 1.0.43.

**Comment by summumeng** [comment]
Thanks!
