### ISSUE TITLE
Mobile display of matrix q flows over

### ISSUE THREAD

**Issue by frankwo1** [surveyjs/surveyjs#1323]
### Are you requesting a feature, reporting a bug or asking a question?

question

Hi, How can I make the mobile matrix question display better
I only have 4 choices and it expands beyond the screen
I have set width of q to 90% but not change
Have also tried this
https://github.com/surveyjs/surveyjs/issues/453

<img width="204" alt="screen shot 2018-09-07 at 9 37 31 am" src="https://user-images.githubusercontent.com/19366310/45222215-e2c6ba00-b281-11e8-9298-15cb13bec76f.png">

ios/iphone 6

**Comment by dmitrykurmanov** [comment]
@frankwo1 Does it contain horizontal scroll ?

**Comment by frankwo1** [comment]
In my css, I have 
.sv_body {
  overflow: scroll;
}

**Comment by frankwo1** [comment]
@dmitrykurmanov,
Is it possible to set it up so it will replace this with dropdown on mobile width?
Thanks
Frank

**Comment by frankwo1** [comment]
Hi @dmitrykurmanov,
I'm trying to make it more mobile friendly since more than 60% of surveys now are done on mobile - Aside from the horizontal scroll - is there a css/js solution in the future?

**Comment by andrewtelnov** [comment]
@frankwo1 We are going to spend more time on improving the mobile rendering. Could you send here or me directly your survey json? We play with it and see what we can do.

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
ok I will check

**Comment by dmitrykurmanov** [comment]
We've impoved it via the https://github.com/surveyjs/surveyjs/commit/c1e42064bef9c472928f13c8d795ccdf6b601b3b

Changes will be available in the next minor update (very likely today)

**Comment by HarunKARATAS** [comment]
Hello,
This is library's original example. Im just changed library's path latest cdn.
![image](https://user-images.githubusercontent.com/7129948/45428985-038c7680-b6ab-11e8-9b72-d10944b3e45d.png)

And Matrix question shows up with scroll. Can you explain how we can use as a responsive matrix question?

**Comment by HarunKARATAS** [comment]
also same behaviour on the official page. 
https://surveyjs.io/Examples/Library/?id=questiontype-matrix&platform=jQuery&theme=default

**Comment by tsv2013** [comment]
@HarunKARATAS As you can see from the commit, we've removed the `min-size` constraint for a matrix column. This allows to see more columns at the same time on the small screens.

At the moment SurveyJS hasn't have responsive widgets, that look different on different screens.
Creating responsive widgets is a large task. And we'll discuss it with the team.

Can you also share your thoughts - how SurveyJS responsive widgets should be implemented in your opinion?

**Comment by HarunKARATAS** [comment]
@tsv2013 I think maybe you can get ideas from Devexpress Js Components [Devexpress ](https://js.devexpress.com/Demos/WidgetsGallery/) . They have lots of widgets like yours. As you said it's a large task but it's extremly important and it can be reason for choice.

**Comment by tsv2013** [comment]
@HarunKARATAS Thank you for the information. Could you share your thoughts - what we can do for example with survey matrix questions in order to make them responsive?

**Comment by BarryGibson** [comment]
Using the example @SlowburnAZ gave as a starting point, I have come up with the following layout option to display a matrix question as individual questions on the mobile and matrix on desktop/tablet which is something I want to be able to achieve.
**Desktop view:**
![image](https://user-images.githubusercontent.com/15335262/45734797-2083f500-bc29-11e8-9175-d2296176e7c1.png)
**Mobile view:**
![image](https://user-images.githubusercontent.com/15335262/45734843-427d7780-bc29-11e8-8354-a1dce8233b22.png)

I have created a Plunker of the matrix example: [https://plnkr.co/edit/aKuuB9ZnDHTWgrd7BEu0](https://plnkr.co/edit/aKuuB9ZnDHTWgrd7BEu0)

I hope this helps others out in their quest for responsive matrices, and maybe adds an opinion on future responsiveness.
Also as a note, if something like this was added, I would prefer it to be optional.

**Comment by tsv2013** [comment]
@BarryGibson Thank you for sharing your solution!

**Comment by tsv2013** [comment]
We've added responsive behaviour in 1.0.45.

**Comment by szakalq** [comment]
> We've added responsive behaviour in 1.0.45.
not work in bootstrap theme ?

**Comment by tsv2013** [comment]
@szakalq Absolutely right. We'd like to get feedback.

**Comment by szakalq** [comment]
@tsv2013 In default theme works great, thanks for add :)

**Comment by szakalq** [comment]
In matrix question, in mobile view text in option it's not clickable (only click on input works)
```
<td data-bind="attr: { headers: $data.locText.renderedHtml }" headers="Codziennie">
    <label data-bind="css: question.getItemCss(row, $data)" class="sv_q_m_label">
        <input type="radio" data-bind="css: question.koCss().itemValue, attr: {name: row.fullName, 'aria-label': question.locTitle.renderedHtml, value: $data.value, id: ($index() == 0) &amp;&amp; ($parentContext.$index() == 0) ? question.inputId : ''}, checked: row.koValue, enable: !question.koIsReadOnly()" name="sq_105_Lidl" aria-label="2.&amp;nbsp;JAK CZĘSTO ROBI PAN/I ZAKUPY?" value="1" id="">
        <span class="circle"></span>
        <span class="check"></span>
        <span style="display: none" data-bind="text: $data.locText.text">Codziennie</span>
    </label>
</td>
```

**Comment by tsv2013** [comment]
We've supported bootstrap theme and fixed matrix label non-clicable.
Thank you all for the feedback!
