### ISSUE TITLE
Rubric matrix - does not respect display/read only

### ISSUE THREAD

**Issue by madceb** [surveyjs/surveyjs#1325]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
Rubric matrix question example allows to click in options when is in display mode

### What is the expected behavior?
it shouldn't allow to click/change options when in display mode (read only)

### How would you reproduce the current behavior (if this is a bug)?
using site's example https://surveyjs.io/Examples/Library/?id=questiontype-matrix-rubric&platform=jQuery&theme=default in plunker just add survey.mode = 'display'

### Specify your

* browser: Chrome, IE11, Edge
* browser version: 69
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.41

**Comment by andrewtelnov** [comment]
@madceb I have fixed it. We should release a new minor version tomorrow.

Thank you,
Andrew

**Comment by madceb** [comment]
Hello @andrewtelnov it seems that this generated another bug, it now does not allow to do changes in edit mode. 
Site Example seems not to work:
https://surveyjs.io/Examples/Library/?id=questiontype-matrix-rubric&platform=jQuery&theme=default
Regards,

**Comment by andrewtelnov** [comment]
@madceb Damn, sorry about that. There was a missing bracket. I have fixed the issue.

Thank you,
Andrew
