### ISSUE TITLE
How to add choices programmatically?

### ISSUE THREAD

**Issue by moldoe** [surveyjs/surveyjs#1326]
Looking at the API is not clear to me how I can add programmatically item values(value and text) to the choices property for a question. I'm using the Knockout version.
Can you please provide an example?

Thank you,

Daniel

**Comment by andrewtelnov** [comment]
@moldoe Here is [the example](https://next.plnkr.co/edit/lglp7vWhVGghystY)

Thank you,
Andrew

**Comment by moldoe** [comment]
Thank you!
