### ISSUE TITLE
custom css class for single panel instance

### ISSUE THREAD

**Issue by moldoe** [surveyjs/surveyjs#1333]
Basically it's the same issue like this one https://github.com/surveyjs/surveyjs/issues/396 but for panels.

Also, I'm not sure why, when changing options.cssClasses in onUpdatePanelCssClasses, it has impact on all the panel instances in the survey. If that is the case, then what is the purpose of calling onUpdatePanelCssClasses on each panel. And I actually have noticed it's called multiple times even on the same panel.

Thanks,

Daniel

**Comment by tsv2013** [comment]
This event is fired in the getter of the `cssClasses` property:
```JS
  public get cssClasses(): any {
    var classes = { error: {} };
    this.copyCssClasses(classes, this.css);
    this.copyCssClasses(classes.error, this.css.error);
    if (this.survey) {
      this.survey.updatePanelCssClasses(this, classes);
    }
    return classes;
  }
```
As you can see, each time a new copy of CSS classes is created and customizations are appplied for the each call. That's why this event fires many times, probably too many.

Two arguments are being passed as otions of this event:
```JS
   {
      panel: panel,
      cssClasses: cssClasses
    }
```
so you can patch css classes for the cretain panel.

**Comment by moldoe** [comment]
I created a Plunker example:
https://plnkr.co/edit/Ko9Trw?p=preview

Maybe I'm doing something wrong, but in this example I want only "panel1" to have a red border.
As you can see changing cssClasses will apply the custom style to both panels.

**Comment by tsv2013** [comment]
I see the issue now. Probably it's a bug. I'll take a look.

**Comment by tsv2013** [comment]
We've fixed the issue. Fix will be available in the nearest update, most likely tomorrow.
