### ISSUE TITLE
Programmatically run a SurveyJS condition

### ISSUE THREAD

**Issue by xiaohutai** [surveyjs/surveyjs#1336]
[Question] Hi!

Is it possible to programmatically run a condition and get a `true` or `false` value?

For example, I want to check `{q1} = 'a'` or `{q2} = 'b'` in the `onComplete` function and base my result on that.

Or: should I go for `survey.valuesHash.q1 == 'a'` instead?

**Comment by dmitrykurmanov** [comment]
Hello! Sure, please check our tests : https://github.com/surveyjs/surveyjs/blob/master/tests/conditionstests.ts#L336-L344

**Comment by xiaohutai** [comment]
Very nice! Thanks!
