### ISSUE TITLE
showNavigationButtons property does not work correctly when changed in onValueChanged event

### ISSUE THREAD

**Issue by KLC215** [surveyjs/surveyjs#1338]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
![survey-checkbox](https://user-images.githubusercontent.com/15123751/45619468-f48f3500-baab-11e8-9ae6-871f206e7517.gif)
1. The default of  `showNavigationButtons` property is `false`
2. Turn `showNavigationButtons` to `true` in `onValueChanged event` but it doesn't show *Next* button

### What is the expected behavior?
Change `showNavigationButtons` property in `onValueChanged event` and show navigation buttons

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: [https://next.plnkr.co/edit/agxHqOnhqyWeb1T9](https://next.plnkr.co/edit/agxHqOnhqyWeb1T9)

### Specify your

* browser: `Google Chrome`
* browser version: `69.0.3497.92 (Official Build) (64-bit)`
* surveyjs platform (angular or react or jquery or knockout or vue): `survey-react`
* surveyjs version: `1.0.38`

**Comment by tsv2013** [comment]
Thank you for the report. We've fixed the issue. Fix will be available in the next minor update, most likely tomorrow.

**Comment by KLC215** [comment]
It works perfectly. Thank you @tsv2013 :)
