### ISSUE TITLE
Use same validation logic on the server to validate the whole survey

### ISSUE THREAD

**Issue by soulchild** [surveyjs/surveyjs#1340]
### Are you requesting a feature, reporting a bug or asking a question?

Question/Feature

### What is the expected behavior?

First of all: Thanks for your great survey framework! 👏 

I'd like to know if it's possible to re-use the same validations on the server to validate the survey results on submission? Given a moderately big survey it would be painful to write another layer of validation logic in the backend (probably using `express-validator` or similar) when everything has already been declared sufficiently in the survey definition. I have to make sure that the survey results pass all validations before storing them in a database.

**Comment by tsv2013** [comment]
I think you can reuse our validation node on a server side. You can check our validators unit tests code - https://github.com/surveyjs/surveyjs/blob/master/tests/surveyvalidatortests.ts

**Comment by soulchild** [comment]
Cool, I'll give that a try. Thanks!

**Comment by SamMousa** [comment]
@soulchild did you figure out a good solution for this?

**Comment by soulchild** [comment]
@SamMousa I haven't touched that project in a long time, but as far as I remember, we ended up not validating the survey again on the backend because it wasn't THAT important to have consistent data.
