### ISSUE TITLE
Bug with number + maxLength

### ISSUE THREAD

**Issue by NafanyaVictorovna** [surveyjs/surveyjs#1346]
Bug

If I create field with input limit and input type they do not work together correcly
When I open survey assessment on the window I can input only numbers and have no input limitations

Must be input limit, which I selected

I have that type of field:
```
{"type":"text","name":"Zip Code4","title":"Zip Code","maxLength":5,"inputType":"number"}

```

### Specify your

* browser: Chrome
* surveyjs platform jquery
* surveyjs version: 1.0.44

**Comment by andrewtelnov** [comment]
@NafanyaVictorovna We can add two string properties: min and max. It will work as in [this example](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_max_min).
Will it work for you?

Thank you,
Andrew

**Comment by NafanyaVictorovna** [comment]
@andrewtelnov Yes, it will be fine, thanx!

**Comment by dmitrykurmanov** [comment]
@NafanyaVictorovna as an alternative you can use regexp validator, please check: 

```json
{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "text",
     name: "question2",
     validators: [
      {
       type: "regex",
       text: "Please type exactly 5 digits",
       regex: "^\\d{5}$"
      }
     ]
    }
   ]
  }
 ]
}
```

**Comment by NafanyaVictorovna** [comment]
@dmitrykurmanov I want check my fields immediately and prevent input more than it should be, for example no more then 6 digits for zip field

**Comment by andrewtelnov** [comment]
@dmitrykurmanov @tsv2013 Lets add min and max properties into QuestionText.

Thank you,
Andrew

**Comment by tsv2013** [comment]
@andrewtelnov min+max don't fit @NafanyaVictorovna requirements. These settings allow to enter more than min/max number and validation works on form submit only.
I think this task can be solved via the input mask custom widget

**Comment by tsv2013** [comment]
@andrewtelnov We've tested these attributes with @dmitrykurmanov and the result didn't look ok for us.

**Comment by NafanyaVictorovna** [comment]
@tsv2013 ok, Please, can you give me some example with input mask, if it will require to show hint - it will be fantastic!

**Comment by NafanyaVictorovna** [comment]
@tsv2013 ok, I see. Thank you!

**Comment by NafanyaVictorovna** [comment]
@tsv2013 Yes, I'd checked. It is good alternative for me - Thank you much.
