### ISSUE TITLE
Add/remove properties in run-time

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#135]
Two new methods have been added:
```
JsonObject.metaData.addProperty(className, propertyDescription);
JsonObject.metaData.removeProperty(className, propertyName);
```
The property will be added into the class: className (string, case sensitive) and all it's descendants.
propertyDescription it can be string or json object.
For example: "mynewProperty" = {name: "mynewProperty"} the default type is string,
"mynewProperty:boolean" = {name: "mynewProperty", type: "boolean"}.
The following types are available:
"string" - default type, "boolean", "numeric", "text" (large text), "html", "itemvalues" (to edit ItemValue array).
```
{ name: "showProgressBar", default: "off", choices: ["off", "top", "bottom"] }
```
The following example shows a string property with default value "off" and 3 choices "off", "top" and "bottom". Survey editor will use dropdown input to edit it.

**Comment by andrewtelnov** [comment]
[The demo](http://editor.surveyjs.io/examples/addproperties.html) was added.

**Comment by fabien** [comment]
I cannot see the demo code when I follow that link - it appears not to load correctly. The other customization demos won't load for me either.

**Comment by andrewtelnov** [comment]
@fabien Does this link work for you? http://editor.surveyjs.io/examples/addproperties.html#code 
It works fine for me and there is the similar issue, https://github.com/surveyjs/surveyjs/issues/234, which is closed already.

Thank you,
Andrew

**Comment by LA95** [comment]
What if I want to remove the '*' in a matrixtype questionnaire?
