### ISSUE TITLE
url validation for inputType = "url"

### ISSUE THREAD

**Issue by jasan-s** [surveyjs/surveyjs#1350]
### Are you requesting a feature, reporting a bug or asking a question?

Maybe a bug. 

### What is the current behavior?

non-urls are allowed without any errors

### What is the expected behavior?
should show an error for non urls. 

### How would you reproduce the current behavior (if this is a bug)?

type in a random string that is not an url in the text field

#### Provide the test code and the tested page URL (if applicable)

https://plnkr.co/edit/9JhipkJbJCqZy9ny9M4f?p=preview

I am assuming the url validation is built in maybe this needs to have a regex applied manually ?

**Comment by tsv2013** [comment]
For the text question we are using standard html input with type attribute and we don't change default behabiour for this inputs in different browsers.
You can add a regexp validator to this question

**Comment by jasan-s** [comment]
sweet: used the following:
```
 validators: [
        {type: "regex",
        regex: "(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9]\.[^\s]{2,})",
          text: "Please enter a valid url i.e https://www.google.com"
       }
   ]
```
