### ISSUE TITLE
Expression of equality for more fields

### ISSUE THREAD

**Issue by RomeoDavide91** [surveyjs/surveyjs#1351]
I am building a platform using ANGULAR where you need to fill out a form, there are several fields including email.

This field requires verification, that is, inserting the same email in a different field.

Then the following validation is entered in the verification field:

validators:
          [{
            type: "email",
            text: "Invalid email"
          }, {
            type: "expression",
            text: "Different email",
            expression: "{form_email_verify} == {form_email}"
          }]

The "Different email" validation is ignored, while in the SurveyBuilder it works 100%.
I tried with "==", "=", "equal" but it does not work anyway.
I've tried using multipletext but it does not work.

package.json:
     "survey-angular": "^ 1.0.20",
     "surveyjs-widgets": "^ 1.0.27",

How to solve?
Thank you.

**Comment by tsv2013** [comment]
I've created a live sample for you with Angular - https://plnkr.co/edit/1Sbxug8cVsp8jzoxBwDH?p=preview
It works ok for me

**Comment by RomeoDavide91** [comment]
Thanks so much!
I understood that the problem was the version, updating the surveyjs from 1.0.20 to 1.0.44 everything worked.

Davide R.
