### ISSUE TITLE
Custom CSS Classes Documentation Question

### ISSUE THREAD

**Issue by rachel-flux** [surveyjs/surveyjs#1353]
### Are you requesting a feature, reporting a bug or asking a question?

I have a question about customizing the CSS, not using Bootstrap.  I found this example here which has been very helpful:
https://surveyjs.io/Examples/Library/?id=survey-cssclasses&platform=jQuery&theme=default

But I'm wondering if there is documentation somewhere that specifies all of the class options that can be overwritten beyond the ones included in the example.

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: survey-vue version 1.0.38

**Comment by tsv2013** [comment]
You van fin this info in the sorce code. Here it is - https://github.com/surveyjs/surveyjs/blob/master/src/defaultCss/cssstandard.ts

**Comment by rachel-flux** [comment]
Thanks @tsv2013 !

I had seen that file before in the source code, but I wasn't sure if each of the items was supposed to be customizable or not.  The first item I was trying to customize is the next button in the navigation.  When I apply the following code...

`     survey.onUpdateQuestionCssClasses.add(function (survey, options) {
        var classes = options.cssClasses;
        classes.root = "custom-root";
        classes.title = "custom-title";
        classes.item = "custom-item";
        classes.label = "custom-label";
        classes.navigationButton = "custom-navigationButton";
        classes.navigation.complete = "custom-complete";
        classes.navigation.prev = "custom-prev";
        classes.navigation.next = "custom-next";
        classes.navigation.start = "custom-start";
      });
`

... I can see the custom CSS classes for root, title, item, and label.  But navigationButton and the other navigation elements don't seem to work.  That's why I thought perhaps there was documentation showing which elements could have custom CSS applied.  Or do I just have a syntax error or something simple that is causing this not to work?

Thanks!
Rachel

**Comment by tsv2013** [comment]
The `onUpdateQuestionCssClasses` function updated CSS classes for the current question. Navigation button is not related to any question. That's why you wasn't able to customize it. You can just assign statis values as shown in this example - https://surveyjs.io/Examples/Library/?id=survey-customcss&platform=jQuery&theme=default

**Comment by rachel-flux** [comment]
That seems to be working!  Thanks for your help answering my questions.
