### ISSUE TITLE
The influence of third party plug-ins

### ISSUE THREAD

**Issue by fengzhihenxs** [surveyjs/surveyjs#1356]
Hello, I have a requirement to use jquery. nicescroll. min. js, and then click on the question title after the Comment button will have about 2 seconds delay, before the input box appears, why is this?

[surveyjs_angular.zip](https://github.com/surveyjs/surveyjs/files/2415077/surveyjs_angular.zip)

**Comment by tsv2013** [comment]
I'll take a look

**Comment by tsv2013** [comment]
I've checked it. It looks like re-rendeing works too slow for KnockoutJS and related platforms (Angular and jQuery). We're starting to improve this behaviour. I'll update this thread once I'll receive any results.

**Comment by tsv2013** [comment]
By the way, third-party plugins was not the source of the preformance issue in this case.

**Comment by fengzhihenxs** [comment]
But when I didn't use jquery. nicescroll. min. js, there was no delay in clicking the button to re-render, and soon.

**Comment by tsv2013** [comment]
@fengzhihenxs I've reproduces the issue with pure surveyjs-knockout library

**Comment by tsv2013** [comment]
@fengzhihenxs If there is another performance issue we can check it after fixing the first one

**Comment by tsv2013** [comment]
We've decided to re-render the affected markup only then one changes some property of a survey element. I've implemented this behaviour. So now you needn't to call `survey.render();` function. If some property changes will not reflected in UI, we'll fix it.
This fix will be available in the nearest update.

**Comment by tsv2013** [comment]
This enchancement further progress can be tracked in this thread - [Use native component update approaches for Knockout and React](https://github.com/surveyjs/surveyjs/issues/1361)
