### ISSUE TITLE
Split panel row asymmetric

### ISSUE THREAD

**Issue by Evertude** [surveyjs/surveyjs#1360]
### Are you requesting a feature, reporting a bug or asking a question?
question

### What is the expected behavior?
Is it possible to split a row asymmetrically when using startWithNewLine=false?
When I ask for Street/Nr, I want the street field to be larger than the number

'elements': [
    {
        'type': 'text',
        'name': 'street',
        'isRequired': true
    }, {
        'type': 'text',
        'name': 'houseNr',
        'isRequired': true,
        'position': {
            'startWithNewLine': false,
            'size': 0.2
        }
    }
]

**Comment by andrewtelnov** [comment]
@Evertude Will [this work](https://next.plnkr.co/edit/MZeq5TibrlOl3Oy7) for you?

Thank you,
Andrew

**Comment by Evertude** [comment]
Thank you for your feedback. I'll verify it next week since I'm only able to access it from my phone and it's displayed in two rows

**Comment by andrewtelnov** [comment]
@Evertude Yes, we are ignoring startWithNewLine property for mobiles, starting from the latest build.

Thank you,
Andrew

**Comment by Evertude** [comment]
Thank you very much, that did the trick.
