### ISSUE TITLE
Extend contains and notcontains

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/surveyjs#1366]
### Are you requesting a feature, reporting a bug or asking a question?
Feature

### What is the current behavior?
Contains and not contains act on an array and a scalar.

### What is the expected behavior?
Intuitively they should work on a pair of scalars as well.

### Contains
Contains could be read as subset, which can easily be applied to 2 sets. 
```
["a","b"] contains "a" ==> true
["a","b"] contains ["a"] ==> true
["a","b"] contains ["a", "b"] ==> true
```

Alternatively, one could add some more, similar functions: `containsAny`, `containsAll`.
These allow for more flexible conditions while still being easy to implement.

**Comment by andrewtelnov** [comment]
@SamMousa Yes, it was not hard to implement.
The functionality will be available in the next minor release on this week.

Thank you,
Andrew
