### ISSUE TITLE
Negation operator is not documented

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/surveyjs#1367]
### Are you requesting a feature, reporting a bug or asking a question?
Documentation bug / omission.

### What is the current behavior?
https://surveyjs.io/Documentation/LibraryParameter?id=QuestionBase&parameter=visibleIf is missing `!` and `not` which were added in 1.0.46 
https://github.com/surveyjs/surveyjs/commit/87b63cdf352f5b578f3e633ab405c0aa41fc4cd2

### What is the expected behavior?
All operators should be listed.

**Comment by andrewtelnov** [comment]
@SamMousa It will be here with the next web site update on this week.

Thank you,
Andrew
