### ISSUE TITLE
Surveyjs-react Compatibility with Typescript 

### ISSUE THREAD

**Issue by kholibri3** [surveyjs/surveyjs#1371]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug

### What is the current behavior?

The index.d.ts file generated for react are not exposed in the source code, so it's difficult to tell if types are aligned. I'm seeing the following errors when I try to compile my project with survey-js version 1.0.48 dependencies. 

This function does not have explicit types: 
`iteratePropertiesHash(func: (hash, key) => void): void;`

```
ERROR in [at-loader] ./node_modules/survey-react/survey.react.d.ts:1249:38
    TS7006: Parameter 'hash' implicitly has an 'any' type.

ERROR in [at-loader] ./node_modules/survey-react/survey.react.d.ts:1249:44
    TS7006: Parameter 'key' implicitly has an 'any' type.

ERROR in [at-loader] ./node_modules/surveyjs-editor/node_modules/survey-knockout/survey.ko.d.ts:1145:38
    TS7006: Parameter 'hash' implicitly has an 'any' type.

ERROR in [at-loader] ./node_modules/surveyjs-editor/node_modules/survey-knockout/survey.ko.d.ts:1145:44
    TS7006: Parameter 'key' implicitly has an 'any' type.
ℹ ｢wdm｣: Failed to compile.

```
### What is the expected behavior?

The parameters `hash` and `key` in the aforementioned function (`iteratePropertiesHash(func: (hash, key) => void): void;`) in survey.react.d.ts are explicitly typed. 

### How would you reproduce the current behavior (if this is a bug)?

Compile a typescript project with survey-js dependencies. 

### Specify your

* browser: Chrome
* browser version: 69.0.3497.92 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.0.48
* typescript version: 2.9.2

**Comment by dmitrykurmanov** [comment]
I think that the problem may be in typescript version. In SurveyJS we are using  `"typescript": "2.6.1" ` . We will investigate it.

**Comment by kholibri3** [comment]
Great, please keep us posted!

**Comment by kholibri3** [comment]
Hi, just curious-- any updates on this issue?

**Comment by dmitrykurmanov** [comment]
@kholibri3 We are working on it in the separate branch: https://github.com/surveyjs/surveyjs/tree/1371. There are many small changes here. 

ps: may be you can use `"noImplicitAny": false,` in your `tsconfig.json` file as a workaround

**Comment by dmitrykurmanov** [comment]
@kholibri3  hello! We've changed our ts config file to "noImplicitAny": true and saw all this errors. We've fixed it and merged to the master branch. I believe that it solves your problem. Fix will be available in the next minor update.

**Comment by dmitrykurmanov** [comment]
@kholibri3 no it will be in the 1.0.51 but if you need I can generate new d.ts file and share it here
