### ISSUE TITLE
Add all custom properties on itemvalues to the 'choices' array

### ISSUE THREAD

**Issue by lady3bean** [surveyjs/surveyjs#1372]
### Are you requesting a feature, reporting a bug or asking a question?

Feature

### What is the current behavior?
When you do:
`survey.onAfterRenderQuestion.add((sender, options) => { console.log(options.question.choicesValues); }`

`options.question.choicesValues` is an array of the choices that are objects with these properties: `{ visibleIfValue: "", isVisibleValue: true, itemValue: "example"}`

(Similarly, in the survey editor, if you do `editor.onQuestionAdd.add(sender, options) => {
console.log(options.question.propertyHash.choices);
}`, the choices object only has the visibleIfValue, isVisibleValue, and itemValue props.)

I have added other properties to itemvalues like so:
`Survey.JsonObject.metaData.addProperty("itemvalue", {
      name: "itemColor",
      type: "dropdown",
      choices: [
        "red",
        "blue",
        "yellow"]
});
`

These properties are not available in the choices object. 
### What is the expected behavior?

Since there is no way to use "getPropertyValue" on an itemvalue like there is for a property on a question, I need some way to be able to access properties I've added to itemvalues. In my case, I want users to be able to select the color for item values in order to display that color for the input area for each choice. Having all properties and their respective values available in the `choices` would be great, and I'd appreciate if if you could add this! Open to alternative means of getting at these values as well if there's something I'm not seeing in the API.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
Do I understand you right - you want to add custom property to the itemvalue object and modify this property in the SurveyJS Builder?

Here is the working sample how to add custom property to an itemvaalue and show it in the choices aditor via custom widget - https://plnkr.co/edit/jRjZcQQRzLZReJuE2Kgp?p=preview
It was discussed in this thread - https://surveyjs.answerdesk.io/ticket/details/T1084

Does it fit your needs?

**Comment by lady3bean** [comment]
Thanks for the quick reply - it turns out no fix is needed. The values of custom properties when they have values set are available in the choicesValues -- when I was trying to find them earlier, I had added the properties but hadn't set any values. As soon as I did, I saw them there.
