### ISSUE TITLE
Javascript error "Object doesn't support property or method 'forEach'" Microsoft Edge

### ISSUE THREAD

**Issue by rustyoz** [surveyjs/surveyjs#1378]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
Rendering error with the current online survey builder. Visible JavaScript error in developer console. 

![capture](https://user-images.githubusercontent.com/1628200/46589020-d0de6e00-caf0-11e8-8672-da63729c0f67.PNG)
![capture](https://user-images.githubusercontent.com/1628200/46589026-df2c8a00-caf0-11e8-9d23-dab0e0a55f1c.PNG)

### How would you reproduce the current behavior (if this is a bug)?
Add a question to a new page using Microsoft Edge

### Specify your

* browser: Microsoft Edge
* browser version: 40.15063.674.0

**Comment by andrewtelnov** [comment]
@rustyoz It works fine in Microsoft Edge for us, but there is the error in IE11 indeed.
We will work on the fix.

Thank you,
Andrew

**Comment by tsv2013** [comment]
We've fixed this issue. Fix will be available in the nearest update, most likely tomorrow.
