### ISSUE TITLE
Populate assessment fields from system data

### ISSUE THREAD

**Issue by NafanyaVictorovna** [surveyjs/surveyjs#1383]
Question

### What is the current behavior?
Now I can populate some fields from system data use 
```
survey.setValue('questionName', newValue);
```
or
``` 
survey.data = {"question1": value1, "question2":value2};
```

### What is the expected behavior?
Can I populated fields by other way?

Current way not absolutely good, if I have more than 100 questions and should populated 30 of them

* browser: Chrome
* surveyjs version: surveyjs 1.0.48

**Comment by tsv2013** [comment]
Could you please specify - why current way is not good? And how do you think it should be done?

**Comment by NafanyaVictorovna** [comment]
@tsv2013 Because if field name in json will change, I need change js code the same, so, for my case it is not usable. But I thought, and now have some idea, how I can avoid hard code. I can use some json tag like a a property, which allow client now, about autopopulated fields, also should avoid using of field name, and use the tag as identification. I am planning to add fields server add mapping

**Comment by tsv2013** [comment]
What about my second question - how do you think it should be done?

**Comment by tsv2013** [comment]
I see your point and in this case you can use some fields mapping table, as you wrote.
