### ISSUE TITLE
Unable to programmatically toggle "readOnly" behaviour for "matrixdropdown" element properly

### ISSUE THREAD

**Issue by pralok** [surveyjs/surveyjs#1386]
### Are you requesting a feature, reporting a bug or asking a question?
Question(possible bug)

### What is the current behavior?
Unable to programmatically toggle "readOnly" behaviour for "matrixdropdown" element properly. It works fine when readOnly is set to _true_ from _false_ but doesn't if switched back from _false_ to _true_

### What is the expected behavior?
One should able to toggle readonly property for each of the columns of "matrixdropdown" programmatically. 

### How would you reproduce the current behavior (if this is a bug)?
Download this plunker zip and open index.html file =>
[plunk-Q5VV5y2mKdmWLvuXpTt1.zip](https://github.com/surveyjs/surveyjs/files/2464426/plunk-Q5VV5y2mKdmWLvuXpTt1.zip) 
or use this link : https://plnkr.co/edit/CdD8PFKA0l6Afty2Zrrm?p=preview

 
#### Provide the test code and the tested page URL (if applicable)
Zip Attached

### Specify your

* browser: Chrome 
* browser version: 69.0.3497.100
* surveyjs platform (angular or react or jquery or knockout or vue): JQuery/react
* surveyjs version: 1.0.41

**Comment by tsv2013** [comment]
Fixed. Fix will be available in the nearest update
