### ISSUE TITLE
Change position of remove button to be inside dynamic panel 

### ISSUE THREAD

**Issue by kholibri3** [surveyjs/surveyjs#1387]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

When I collapse the dynamic panel in my survey, the remove button is outside of the collapsed area.

Expanded dynamic panel: 
<img width="1670" alt="screen shot 2018-10-10 at 11 40 25 am" src="https://user-images.githubusercontent.com/7970167/46748484-acfe6200-cc81-11e8-8d85-1c96f2979117.png">

Collapsed dynamic panel:
<img width="1643" alt="screen shot 2018-10-10 at 11 40 36 am" src="https://user-images.githubusercontent.com/7970167/46748489-b2f44300-cc81-11e8-9b86-92a3df4c3e56.png">
### What is the expected behavior?

Is it possible to move the position of this remove button? I'm looking to move the button into the collapsed area, so when the dynamic panel is collapsed, you cannot see the remove button. That way, you would have to expand the dynamic panel to see the remove button.

**Comment by tsv2013** [comment]
SurveyJS at the moment doesn't allow this AFAIU. We'll discuss thia behavioral change with the team. @andrewtelnov @dmitrykurmanov

**Comment by kholibri3** [comment]
Great! Please let us know when the fix is available.

**Comment by andrewtelnov** [comment]
@kholibri3 The issues has been fixed. The fix will be available in the next minor update v1.0.53 on the next week.
You may build the library by yourself, please follow the instruction in the ReadMe file.

Thank you,
Andrew

**Comment by kholibri3** [comment]
Thank you @andrewtelnov!
