### ISSUE TITLE
How copy questions with answers for scoring page

### ISSUE THREAD

**Issue by NafanyaVictorovna** [surveyjs/surveyjs#1392]
Question
Good day.
I want create some scoring page after assessment finished and show there some question, for example with my flag.
For example I have flag 'showOnScoring' with true/false value, and I want show only true questions on scoring page.
How i can do it?

* browser: chrome
* surveyjs jquery v1.0.49

**Comment by andrewtelnov** [comment]
@NafanyaVictorovna If you want to create a survey copy and then to delete questions you do not need, you may do the following:
```
//Copy survey definition
var newSurvey = new Survey.Survey(survey.toJSON());
//Set the data
newSurvey.data = survey.data;
//Now you may delete all questions you do not need and show the survey
```

Thank you,
Andrew

**Comment by NafanyaVictorovna** [comment]
@andrewtelnov or @dmitrykurmanov Hello again. 
How I can get html code of question element, if I got questions via survey.getAllQuestions()?
Or maybe other way, which helps me get me specific questions and their html? I am out of afterRenderQuestion
So, the task is: get all questions by tag/specific html class and get their prev sibling and copy them to new survey

**Comment by tsv2013** [comment]
@NafanyaVictorovna You can create a dictionary question=>htmlElement in the `afterRenderQuestion` event. And use it after.

**Comment by andrewtelnov** [comment]
@NafanyaVictorovna Why do you need html?
Here is [the example](https://plnkr.co/edit/9PJsmF?p=info) that shows non-empty questions only as readOnly one one page after completing the survey.
I believe you need to change several lines of code to achieve what you need.

Thank you,
Andrew

**Comment by NafanyaVictorovna** [comment]
@andrewtelnov I have smth like that
```
{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "panel",
     name: "panel1",
     elements: [
      {
       type: "text",
       name: "question7",
       readOnly: true
      },
      {
       type: "html",
       name: "priorityquestion7",
       startWithNewLine: false,
       html: "<label class=\"priority-align\"><input type=\"checkbox\" name=\"priorityquestion7\" value=\"Priority\">Priority</label>"
      },
      {
       type: "expression",
       name: "question6",
       expression: "{question7} *2",
       displayStyle: "decimal",
       maximumFractionDigits: 4,
       minimumFractionDigits: 0
      },
     ]
    }
   ]
  },
  {
   name: "page2",
   elements: [
    {
     type: "text",
     name: "question1"
    }
   ]
  }
 ]
}
```
And want to show on result page only the question, which are marked like 'Priority'

**Comment by andrewtelnov** [comment]
Here is [the example](https://plnkr.co/edit/n9AFLy?p=preview)

Thank you,
Andrew

**Comment by NafanyaVictorovna** [comment]
@andrewtelnov Thanx, but I need only questions, where priority is checked (so, I need display priority question and previous question, because that check box is like a flag) - but now the html doesn't help me, as I expected, because all checked input have 'false' for 'checked' property/

**Comment by NafanyaVictorovna** [comment]
because it is more easily restyle html for me, and boolean has default state, but i think I can change it to false by deafult, and now have no idea how I can use boolean for my task

**Comment by NafanyaVictorovna** [comment]
@andrewtelnov, @dmitrykurmanov and @tsv2013 Thanks a lot!
I resolved it, thanx for your coll and useful advices.
