### ISSUE TITLE
Radiogroup question text wordwrap in middle of words

### ISSUE THREAD

**Issue by nametable** [surveyjs/surveyjs#1393]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug

### What is the current behavior?

If a radio-group question has text that extends beyond the horizontal space available, the text sometimes is wrapped breaking a word in two lines instead of wrapping between the words.

### What is the expected behavior?

Word wrap between words and do not split individual words unless that single word doesn't fit on a line by itself.

### How would you reproduce the current behavior (if this is a bug)?

Tested page URL: https://surveyjs.io/Examples/Library/?id=survey-quiz&platform=jQuery&theme=default

On the third question of the quiz make the browser width small enough that wrapping is required. Sometimes words are split midway and put on the next line.

### Specify your

* browser: Chrome
* browser version: 69.0.3497.100 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.50

**Comment by reclaimingmytime** [comment]
The solution is to add a `span { word-break: keep-all; }` in the CSS stylesheet.

**Comment by dmitrykurmanov** [comment]
@reclaimingmytime yes I've thought about something like that too, thank you. But I need to check what side effect it will create.

**Comment by reclaimingmytime** [comment]
I haven't noticed any after having this code in production for a few months.

Although being more precise with `.sv_main span { word-break: keep-all; }` instead of just `span` might avoid breaking other parts of the page not related to surveyjs.

**Comment by dmitrykurmanov** [comment]
Fix will be available in the next minor update
