### ISSUE TITLE
Radio box item with *value* = *other* behaves like "other" item

### ISSUE THREAD

**Issue by kaatula** [surveyjs/surveyjs#1395]
### Are you requesting a feature, reporting a bug or asking a question?
Bug report

### What is the current behavior?
For you Radiogroup, an item with id="other" behaves exactly in the same way as system **Other** item (adds a text box if selected)

### What is the expected behavior?
Only **Other** item should add a text box

### How would you reproduce the current behavior (if this is a bug)?
- add a Radiogroup
- click Edit
- open Choices section
- add an item with value="other"
![image](https://user-images.githubusercontent.com/939396/47284689-f2f7e600-d5f0-11e8-94ff-7734036bfa86.png)

- Run survey
- select "My other item"
![image](https://user-images.githubusercontent.com/939396/47284735-1458d200-d5f1-11e8-965f-e3c3d1bba782.png)

#### Provide the test code and the tested page URL (if applicable)

Test code

```json
{
     type: "radiogroup",
     name: "question5",
     hasOther: true,
     choices: [
      {
       value: "item1",
       text: "First Item"
      },
      {
       value: "other",
       text: "My Other Item"
      }
     ],
     otherText: "Other (please specify)"
    }
```

I would be if it just does not pass validation for ```other``` item key.

**Comment by tsv2013** [comment]
This is by design behaviour. The other item value can be changed programmatically via the [otherItem](https://surveyjs.io/Documentation/Library/?id=questioncheckboxmodel#otherItem) property of a question.
