### ISSUE TITLE
requiredText with Markdown

### ISSUE THREAD

**Issue by flowt-au** [surveyjs/surveyjs#1398]
### Are you requesting a feature, reporting a bug or asking a question?
Question (bug?)

### What is the current behavior?
I have a matrix dynamic question where the columns are required. I am passing all questions through the showdown markdown (v1.8.7) as per the docs.

    {
        "pages": [
            {
                "name": "page1",
                "elements": [
                    {
                        "type": "matrixdynamic",
                        "name": "itc_raters",
                        "title": "Please list your supporters",
                        "requiredErrorText": "You must add some supporters.",
                        "columns": [
                            {
                                "name": "firstname",
                                "title": "First name",
                                "isRequired": true,
                                "cellType": "text"
                            },
                            {
                                "name": "lastname",
                                "title": "Last name",
                                "isRequired": true,
                                "cellType": "text"
                            }
                        ],
                        "rowCount": 3,
                        "minRowCount": 1,
                        "maxRowCount": 10
                    }
                ]
            }
        ]
    }

If I use the default `"requiredText" : "*"`, the markdown pre processor converts the `* First name` into:

    <span style="position: static;" data-bind="html: koRenderedHtml">
      <ul>
        <li>First name</li>
      </ul>
    </span>

### Workaround
I am using  `"requiredText": "&#42;"` (HTML asterix entity) and I get the expected asterix rendered. 

This is fine but I wonder whether I am doing something wrong or missing some setting somewhere?

Thanks,
Murray

### Specify your

* surveyjs version: v1.0.50 (jquery version)

**Comment by dmitrykurmanov** [comment]
@flowt-au  We've added your workaround to our code. Thank you.

Fix will be available in the next minor update.

**Comment by dmitrykurmanov** [comment]
I've reverted the commit above because of https://stackoverflow.com/questions/3700326/decode-amp-back-to-in-javascript. We will try to find another decision.

**Comment by dmitrykurmanov** [comment]
@flowt-au unfortunately we didn't find fast way to fix it without braking changes. So if the workaround ok for you, we will recommend to use it. Thanks.

**Comment by flowt-au** [comment]
Thanks. All good. Works for me. :-)
