### ISSUE TITLE
How to change survey empty text

### ISSUE THREAD

**Issue by NafanyaVictorovna** [surveyjs/surveyjs#1402]
### Are you requesting a feature, reporting a bug or asking a question?
Question

I have no one visible field on survey and I want to change the survey empty text. 
How I can do it?
The survey has property emptySurveyText but only in read only state.

Expected:  I want to have possibility to change empty text

For example - that plunker, do not selected any priority check box

Tested page URL:
https://plnkr.co/edit/n9AFLy?p=preview

* browser: Chrome
* surveyjs version: surveyjs 1.0.52

**Comment by NafanyaVictorovna** [comment]
@dmitrykurmanov Yes, thank you a lot. I haven't found it in Survey API docs for Survey unit. Thank you!

**Comment by andFide** [comment]
> 
> 
> Hello if I understand you correctly you need to use this setting: https://surveyjs.io/Documentation/Library/#states-empty
> 
> ```js
> Survey.surveyStrings.emptySurvey = "The current survey is empty";
> ```
> 
> Also please check the example: https://plnkr.co/edit/nfx2D3xjJkc9lON11lgR?p=preview

Hello , i've got the same issue , Survey.surveyStrings.emptySurvey works but only in English , even if i configure my survey for another localization.
 i wanted to know how can i change surveyStrings for other languages

**Comment by andFide** [comment]
Nevermind , i got my answer here https://surveyjs.io/Documentation/Library/#localization
