### ISSUE TITLE
A way to disable user from editing the Name field in survey builder

### ISSUE THREAD

**Issue by prasadh13** [surveyjs/surveyjs#1407]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question -  I was wondering if there is a way to disable name field and allow the user to edit only the title field in the survey builder.

### What is the current behavior?
Able to edit the name field in the builder

### What is the expected behavior?
Should not allow user to edit the name field

**Comment by tsv2013** [comment]
Here is the code:
```JS
// For any question
Survey
    .JsonObject
    .metaData
    .findProperty("question", "name").readOnlyValue = true;
// For pages and panels
Survey
    .JsonObject
    .metaData
    .findProperty("panel", "name").readOnlyValue = true;
```

Here is the working sample - https://plnkr.co/edit/vj0eRKsIJBhXV5J4oaME?p=preview

**Comment by prasadh13** [comment]
@tsv2013 thank you for the super fast response! can this be extended to the value fields in the choices tab for all the questions that have choices? I tried by replacing question with 'selectbase' but it did not work. My aim is to allow the user only to modify the text field of a question of any kind.

**Comment by tsv2013** [comment]
Sure:
```JS
// For item values
Survey
    .JsonObject
    .metaData
    .findProperty("itemvalue", "value").readOnlyValue = true;
```
Updated plunk - https://plnkr.co/edit/vj0eRKsIJBhXV5J4oaME?p=preview

**Comment by prasadh13** [comment]
Thank you for the quick response. Looks like I missed it in the docs. Closing the ticket now.
