### ISSUE TITLE
How do I create a onComplete to trigger in Angular 6 ?

### ISSUE THREAD

**Issue by RachithaBR** [surveyjs/surveyjs#1408]
This code does not work as it is in angular 2

```
survey.onComplete.add(function (sender) {
    var mySurvey = sender;
    var surveyData = sender.data;
});
```

**Comment by tsv2013** [comment]
This is an event of a survey model. Thus it doesn't depend on the Angular version.
Here is the working sample - https://surveyjs.io/Examples/Library/?id=survey-data&platform=Angular2&theme=default

**Comment by RachithaBR** [comment]
So, in my code, I am trying to fetch the form data from database and adding the Survey Library's onComplete method as in the example. But the onComplete is being called before clicking Complete button in the form.
`
fetchData() {
 this._formService.getForm(id).subscribe((data) => {
       this.survey = new Survey.Model(data);
        this.survey.onComplete.add(this.sendDataToServer);
  });

}
`

**Comment by RachithaBR** [comment]
Hi, the problem was the <survey [json]="json"></survey> element was getting loaded before the 'json'  variable was assigned data from server. 
Currently added a div 
```
<div *ngIf="dataLoaded">
    <survey [json]="json"></survey>
</div>

```
