### ISSUE TITLE
Matrix Dynamic and Dropdown + Restful 

### ISSUE THREAD

**Issue by CelsoP** [surveyjs/surveyjs#1412]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

When I combine a Dropdown + Restful in Matrix Dynamic the Restful does not respond

### What is the expected behavior?

When change the first dropdown I expected to change the second

  var json = {
      pages: [
        {
          questions: [
            {
              type: "matrixdynamic",
              name: "matrix3",
              title: "Matrix Dynamic",
              columns: [
                {
                  celltype: "dropdown",
                  name: "region",
                  title: "Select the region...",
                  choices: ["Africa", "Americas", "Asia", "Europe", "Oceania"]
                },
                {
                  celltype: "dropdown",
                  name: "reg_country",
                  title: "Select the country...",
                  isRequired: true,
                  choicesByUrl: {
                    url: "https://restcountries.eu/rest/v2/region/{region}",
                    valueName: "name"
                  }
                }
              ],
              rowCount: 1
            }
          ]
        }
      ]
    };

    Survey.defaultBootstrapCss.navigationButton = "btn btn-primary";
    Survey.Survey.cssType = "bootstrap";
    Survey
      .StylesManager
      .applyTheme("default");

    onMatrixCellCreated = function (survey, options)
    {
      if (options.columnName == "reg_country")
      {
        options.cellQuestion.visible = options.rowValue["region"] ? true : false;
      }
    };

    onMatrixCellValueChanged = function (survey, options)
    {
      if (options.columnName = "reg_country")
      {
        var question = options.getCellQuestion("reg_country");
        question.visible = options.value ? true : false;

        question.choicesByUrl.run();
      };

      //survey.getQuestionByName('reg_country').choicesByUrl.run()
      //question.value = null;
      //if (options.value == "By Quater") question.choices = ["First quater", "Second quater", "Third quater", "Fourth quater"];
      //if (options.value == "By Month") question.choices = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November"];
    };

    window.survey = new Survey.Model(json);

    survey
      .onComplete
      .add(function (result)
      {
        document
          .querySelector('#surveyResult')
          .innerHTML = "result: " + JSON.stringify(result.data);
      });

    $("#surveyElement").Survey({
      model: survey,
      onMatrixCellCreated: onMatrixCellCreated,
      onMatrixCellValueChanged: onMatrixCellValueChanged
    });

**Comment by dmitrykurmanov** [comment]
plunker example: https://plnkr.co/edit/dH2N2izAhniIMhfDegT2?

**Comment by dmitrykurmanov** [comment]
@CelsoP hello! We need to change choicesByUrl config to 

```js
choicesByUrl: {
    url: "https://restcountries.eu/rest/v2/region/{row.region}",
    valueName: "name"
}
```

`region` to `row.region`

Could you please check the updated plunk: https://plnkr.co/edit/dH2N2izAhniIMhfDegT2?p=preview 
Does it cover your needs?

**Comment by CelsoP** [comment]
Many thanks! Worked like a charm!  Thanks a lot, I am new to Survey JS and I am enjoying in learning how to use it. My very best regards and thank you again for your prompt response!
