### ISSUE TITLE
Sometimes first question on a page does not auto-focus

### ISSUE THREAD

**Issue by ekim-novus** [surveyjs/surveyjs#1417]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

Sometimes, after clicking to go to the next survey page, the first question is not auto-focused.

I think this happens because the survey tries to determine which question to auto-focus by finding the first question object on the page with `visible=true`, but does not check if its parent object (page/panel) is `visible=true` as well.

So if a user set the `visibleIf` property for a **panel** in the survey JSON, even though its questions may technically be "hidden", the questions still have `visible=true` by default, and the survey tries to focus on it.

### What is the expected behavior?

The first question should be auto-focused.

### How would you reproduce the current behavior (if this is a bug)?

1) Go to any survey that shows different pages/panels depending on previous answers.
(I'm sorry in advance, since I don't have a sample URL on hand, and the survey I'm developing needs an account to access it).

2) When reaching a question where, for example, Option A displays Panel A on the next page, and Option B displays Panel B, choose Option B (the second or later options, not the first).

3) Notice that first question on next page is not auto-focused.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: none

Sample Survey JSON that would produce this issue

```
{
	"pages": [{
		"name": "page1",
		"elements": [{
			"type": "radiogroup",
			"name": "QUESTION1",
			"title": "Which unit of measurement do you prefer?",
			"isRequired": true,
			"choices": [{
					"value": "M",
					"text": "Metric"
				},
				{
					"value": "I",
					"text": "Imperial"
				}
			]
		}]
	}, {
		"name": "page2",
		"elements": [{
				"type": "panel",
				"name": "QUESTION2_CM",
				"elements": [{
					"type": "text",
					"name": "QUESTION2_CM_Q",
					"title": "Centimeters (cm)",
					"isRequired": true,
					"validators": [{
						"type": "numeric",
						"minValue": 60,
						"maxValue": 240
					}],
					"placeHolder": "Enter a number"
				}],
				"visibleIf": "{QUESTION1} = \"M\"",
				"title": "How tall are you?"
			},
			{
				"type": "panel",
				"name": "QUESTION2_FT",
				"elements": [{
						"type": "text",
						"name": "QUESTION2_FT_Q",
						"title": "Feet",
						"isRequired": true,
						"validators": [{
							"type": "numeric",
							"minValue": 2,
							"maxValue": 8
						}],
						"placeHolder": "Enter a number"
					},
					{
						"type": "text",
						"name": "CC_06_I_inches",
						"startWithNewLine": false,
						"title": "Inches",
						"isRequired": true,
						"validators": [{
							"type": "numeric",
							"minValue": 0,
							"maxValue": 11
						}],
						"placeHolder": "Enter a number"
					}
				],
				"visibleIf": "{QUESTION1} = \"I\"",
				"title": "How tall are you?"
			}
		]
	}]
}

```
If on Page 1, the 2nd option "Imperial" was chosen, when going to Page 2, the question is not focused.

### Specify your

* browser: Chrome
* browser version: 69.0.3497.100
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.0.53

**Comment by ekim-novus** [comment]
Just as a note, I think I found a fix and am about to create a PR.

**Comment by andrewtelnov** [comment]
@ekim-novus Unfortunately your PR doesn't fix the issue completely. Your fix doesn't work for nested panels. I have refactored the code completely to be able to add the unit test for it. The code was obvious initially and then became more complecated, so it requires a unit test.

Thank you,
Andrew
