### ISSUE TITLE
Dropdown + Restful: fill a text field after choose one item from dropdown

### ISSUE THREAD

**Issue by CelsoP** [surveyjs/surveyjs#1418]
Question (I am new to Survey JS)

### What is the current behavior?

Choose a country from a dropdown + restful

### What is the expected behavior?

I would like to, after doing the Restful, when choose a value like Country, be displayed the Country Code in a text field. I do not know how to link to fill the alpha2Code and alpha3Code  to the dropdown after choose the country.

### How would you reproduce the current behavior (if this is a bug)?

Survey
  .StylesManager
  .applyTheme("default");

var json = {
  elements: [{
      type: "dropdown",
      name: "country",
      title: "Select the country...",
      isRequired: true,
      choicesByUrl: {
        url: "https://restcountries.eu/rest/v2/all",
        valueName: "name"
      }
    }, {
      name: "alpha2Code",
      type: "text",
      title: "Alpha Code (2):",
      isRequired: true
    }, {
      name: "alpha3Code",
      type: "text",
      title: "Alpha Code (3):",
      isRequired: true
    }

  ]
};

window.survey = new Survey.Model(json);

survey
  .onComplete
  .add(function(result) {
    document
      .querySelector('#surveyResult')
      .innerHTML = "result: " + JSON.stringify(result.data);
  });

$("#surveyElement").Survey({
  model: survey
});

Example in plunk:
https://plnkr.co/edit/KM8Yl2t0daFgDXBHCeuI?p=preview

**Comment by andrewtelnov** [comment]
@CelsoP Here is [the example](https://surveyjs.io/Examples/Library/?id=trigger-runexpression) you are looking for. It uses expression trigger and does exactly what you need.

Thank you,
Andrew

**Comment by CelsoP** [comment]
Thanks a lot Andrew!
