### ISSUE TITLE
Validation fails on Comments in Edge

### ISSUE THREAD

**Issue by Zucka** [surveyjs/surveyjs#1424]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
User is not able to proceed to next page

### What is the expected behavior?
User should be able to proceed to next page

### How would you reproduce the current behavior (if this is a bug)?
Fill out comment.
While focus is still on comment !Important!
Press "Next"
Error in validation

If one should then click somewhere else to get focus off the comment input and then pressing "Next" it validates correctly.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: Survey Builder: https://surveyjs.io/Survey/Builder/

Test code

```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "comment",
     "name": "question1",
     "isRequired": true
    }
   ]
  },
  {
   "name": "page2",
   "elements": [
    {
     "type": "comment",
     "name": "question2",
     "isRequired": true
    }
   ]
  }
 ]
}

```

### Specify your

* browser: Edge
* browser version: Newest
* surveyjs platform (angular or react or jquery or knockout or vue): Builder, and jQuery
* surveyjs version: 1.0.43 and 1.0.53 tested to not work.

**Comment by dmitrykurmanov** [comment]
@Zucka Thank you for the reporting. Fix will be available in the next minor update.
