### ISSUE TITLE
Autopopulate form data for existing customers

### ISSUE THREAD

**Issue by harrisbaitalrayan** [surveyjs/surveyjs#1428]
Hi Sir,
I have a scenario, when a customer enters his phone number in a multipletext form, if the customer data is present in a separate CRM system, the remaining fields in the form ( Name , Email ID , Address etc) is auto filled. There is an api exposed by the CRM which takes phone number as input and gives the remaining customer data.
So when the user has entered the phone number, the CRM rest service should be called to check for user data in the background and if the user data is found, populate the rest of the form.

Hope above is clear. Please advise if more clarity is needed. Appreciate your help.

**Comment by andrewtelnov** [comment]
@harrisbaitalrayan Please take a look at [this example](https://surveyjs.io/Examples/Library/?id=trigger-runexpression). It implements exactly the same task.

Thank you,
Andrew

**Comment by harrisbaitalrayan** [comment]
Thanks for the quick response sir. I did it by implementing onValueChanged listener.
var surveValueChanged = function (sender, options) {
            var questionName = options.name;
            var newValue = options.value;
            console.log("-------------------------" + questionName);
           // console.log("-------------------------" + questionName.item);
            if (questionName == "Q8multipletextMQ") {                
                //newValue.name = 'Hello';
                //newValue.mobile = '0502808032';
                //newValue.email = 'test@test.com';
                $.ajax({
                    url  : "http://XXXXXXXXXXXXXXXX/getData",
                    type: "GET",
                    success: function (data) {
                        if (!data || data.length < 1) {
                            return;
                        } else {
                            var JSONData = JSON.parse(data);
                            console.log("JSONNNNNNNNNNNNN JSONData['Name'] ->" + JSONData['Name']);
                            newValue.name = JSONData[0].Name;
                            newValue.email = JSONData[0].EmailID;                           
                            //surveyModel.setValue('name', 'aSasasas');
                            return;
                        }                        
                    }
                });                               
            }
        }

**Comment by harrisbaitalrayan** [comment]
From the ajax method, the value change is not refreshed. The debugger goes to the code newValue.name = JSONData[0].Name;  . However the value of the text input on the screen is not refreshed.

**Comment by harrisbaitalrayan** [comment]
It does get very finely set on the screen outside the ajax call ( the commented lines
//newValue.name = 'Hello';
//newValue.mobile = '0502808032';
//newValue.email = 'test@test.com';)

**Comment by harrisbaitalrayan** [comment]
The other fields get refreshed with the data if I change the value in the mobile field once again .

**Comment by harrisbaitalrayan** [comment]
https://www.youtube.com/watch?v=K-hctVV-_wM&feature=youtu.be
a video of how the application is performing. The name and email is being set in the ajax call. But it behaves differently.

**Comment by andrewtelnov** [comment]
@harrisbaitalrayan The example I gave you show how to set the data via ajax call on changing a question value. In this example, if you change the country name to "spain" you will get info about the Spain, to "Portugues", you will get info about the Portugues, to "unknown", it will show that this country is not found.
Your task, as a programmer, is to write the function similar to setCapitalAndCurrency, I have know idea about your exact scenario, but you should get the idea.

Thank you,
Andrew

**Comment by harrisbaitalrayan** [comment]
Hi sir, yes I understood what you mentioned. I am able to get this working except for a small issue. I have created a plunker 

https://plnkr.co/edit/mJkvjybDR8Az5AzLVdZ1?p=preview

First enter a number in the phone field and click outside, nothing happens. If you enter once more and clicks outside the Name and Email fields are populated.

Sorry for too many comments sir. Its my first time communicating like this and first time using plunker.

**Comment by andrewtelnov** [comment]
@harrisbaitalrayan I have forked and modify [the plunker](https://next.plnkr.co/edit/8WCdQ8hFCzmU5zJo)

Thank you,
Andrew

**Comment by harrisbaitalrayan** [comment]
Hi sir @andrewtelnov , Perfect. Works like a charm now. Thank you very much sir.
