### ISSUE TITLE
Change styling of dialog box for remove panel button

### ISSUE THREAD

**Issue by kholibri3** [surveyjs/surveyjs#1430]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
When we click on the Remove button on our panel, the default browser dialog box pops up with default styles.

From the panel section of our json:
```
              "confirmDelete": true,
              "confirmDeleteText": "Would you like to delete this example?",
              "panelAddText": "Add Example",
              "panelRemoveText": "Remove Example"
```
### What is the expected behavior?
When we click on the Remove button on our panel, the default browser dialog box pops up but it has **our custom styles**. Is it possible to access the styles for this dialog box and change them?

**Comment by kholibri3** [comment]
Or is it possible to expose additional properties in the panel json besides `panelAddText`, `panelRemoveText` and `confirmDeleteText`?

**Comment by tsv2013** [comment]
It is not possible. This window is displayed by the browser using the platform's UI kit. It's not in the DOM, not visible from the CSS or Javascript, there's nothing you can do.

I'm treat this question as an improvement request: replace all confirmation dialog with custom (html+css+js) ones.

**Comment by kholibri3** [comment]
Thank you!

**Comment by csgchristian** [comment]
Any update on the status of this feature?
