### ISSUE TITLE
Dynamic question rendering on pages 2+ not working in react version 1.0.52 and newer

### ISSUE THREAD

**Issue by mjabl** [surveyjs/surveyjs#1436]
Hi, I noticed that dynamic question rendering in react version 1.0.53-55 is only working on the first page of a survey. On second page it's not working. To recreate:
1. Clone my gitlab repo: gitlab.com/amm.jablonscy/lite_surveys,
2. cd client,
3. Upgrade "survey-react" dependency in package.json to, say, 1.0.53,
4. npm install && npm run start
5. Survey should open in a browser window, on localhost:3000,
6. Answer question(s) on page 1 and click "Next",
7. Choose "Yes" in the "Do you use any MVVM framework?" question on page 2. "What MVVM framework do you use?" question should appear but it does not. In survey-react 1.0.52 everything works as expected.

I am using Ubuntu 18.04 plus recent Firefox and Chromium browsers, but I don't think that matters.
Best, 
Michał

**Comment by tsv2013** [comment]
Thank you for the report. It's a bug we're working on the fix.

**Comment by tsv2013** [comment]
I've fixed the issue. Fix will be available in the nearest minor update.
