### ISSUE TITLE
custom validator

### ISSUE THREAD

**Issue by lauradurandv** [surveyjs/surveyjs#1440]
Hello SurveyJS.

Are you requesting a feature, reporting a bug or ask a question?
Asking a question

I am creating a custom validator and I was wondering if it is possible to access values from the other questions within the survey, inside the custom validator ?, because right now I only know how to access the value of the question the custom validator function is under in the surveyJSON. 

Kind regards,
Laura

**Comment by lauradurandv** [comment]
thank you for responding so quick I have tried it and it returns Cannot read property 'survey' of undefined. 
Sorry I am new to surveyJS

**Comment by andrewtelnov** [comment]
@lauradurandv Could you please explain in more details your task? 
You may post your code here or better create a plunker example.

Thank you,
Andrew

**Comment by lauradurandv** [comment]
`class App extends Component {
    constructor(props) {
        super(props);

        var MyTextValidator = (function (_super) {
            Survey.__extends(MyTextValidator, _super);
            function MyTextValidator() {
                _super.call(this);
            }
            MyTextValidator.prototype.getType = function () {
                return "mytextvalidator";
            };
            MyTextValidator.prototype.validate = function (survey,question) {
                var stateChoosen = question.survey.getValue("state");

                if (stateChoosen === "AK") {
                    //report an error
                    return new Survey.ValidatorResult(null, new Survey.CustomError("error"));
                }
            };
        
            return MyTextValidator;
        })(Survey.SurveyValidator);
        Survey.MyTextValidator = MyTextValidator;
    //add into survey Json metaData
    Survey
        .JsonObject
        .metaData
        .addClass("mytextvalidator", [], function () {
            return new MyTextValidator();
        }, "surveyvalidator");
}

surveyJSON={
...
}
 render() {
    var model = new Survey.Model(this.surveyJSON);
    return (
      <div className="App">
        <div className="surveyComponent" > 
            <Survey.Survey model={model } onComplete={this.sendDataToServer} />
        </div>
      </div>
    );
  }
}

export default App;

`

**Comment by andrewtelnov** [comment]
@lauradurandv I gave you a wrong tip. Here is the [working example](https://next.plnkr.co/edit/gZxVRJEvcvyjyQIn)

Thank you,
Andrew

**Comment by lauradurandv** [comment]
Thank you so much, this has been super helpful!
