### ISSUE TITLE
Radiogroup & Checkboxes not auto-focused when going to next page

### ISSUE THREAD

**Issue by ekim-novus** [surveyjs/surveyjs#1444]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

Currently in the new version 1.0.56, after going to the next page, the first question is not auto-focused if it's a radiogroup or checkbox group (instead it focuses the Next button).

### What is the expected behavior?

First choice should be auto-focused.

### How would you reproduce the current behavior (if this is a bug)?

In the sample React survey in the `examples/react` folder, copy-paste the below JSON

#### Provide the test code and the tested page URL (if applicable)

Test JSON

```
{
	"pages": [{
			"name": "page1",
			"elements": [{
				"type": "text",
				"name": "CC_01",
				"title": "How old are you?",
				"isRequired": true,
				"validators": [{
					"type": "numeric",
					"minValue": 18,
					"maxValue": 99
				}],
				"placeHolder": "(years)"
			}]
		},
		{
			"name": "page2",
			"elements": [{
				"type": "radiogroup",
				"name": "CC_02",
				"title": "What is your sex?",
				"isRequired": true,
				"choices": [{
						"value": "M",
						"text": "Male"
					},
					{
						"value": "F",
						"text": "Female"
					}
				]
			}]
		},
		{
			"name": "page3",
			"elements": [{
				"type": "checkbox",
				"name": "CC_03",
				"title": "Favourite colours?",
				"isRequired": true,
				"choices": [{
						"value": "B",
						"text": "Blue"
					},
					{
						"value": "R",
						"text": "Red"
					}
				]
			}]
		}
	]
}

```

### Specify your

* browser: Chrome
* browser version: 70.0.3538.77
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.0.56

**Comment by ekim-novus** [comment]
Hey @tsv2013 , I tried the latest commit:  https://github.com/surveyjs/surveyjs/commit/a768489b9bee60292ce8e70868c6cb56b38d8a0c but the radio/checkboxes don't get auto-focused in my survey. However, the example React survey works now.

When I debug my local project I can see that `onCurrentPageChangedHandler` gets added in `setSurveyEvents()` from reactSurvey.tsx, but for some reason the handler doesn't get called when `currentPageChanged()` is called in survey.ts. So in `componentDidUpdate` in reactSurvey.tsx, `isCurrentPageChanged` is false.

**Comment by tsv2013** [comment]
@ekim-novus What version of the survey-react are you using?

**Comment by ekim-novus** [comment]
@tsv2013 I built survey-react locally at the latest commit mentioned above:
https://github.com/surveyjs/surveyjs/commit/a768489b9bee60292ce8e70868c6cb56b38d8a0c

**Comment by tsv2013** [comment]
@ekim-novus Can you share a sample to reproduce the issue on our side?

**Comment by tsv2013** [comment]
@ekim-novus  Thank you for investigations. You are absolutely right.
I've moved setSurveyEvents into updateSurvey method. If functional tests will be ok, I'll leave this solution.
