### ISSUE TITLE
clearInvisibleValues option for both onHidden and none

### ISSUE THREAD

**Issue by cliewdevelop** [surveyjs/surveyjs#1446]
Hi Andrew - is there a possibility to get valueHash of both versions?

Meaning I want both:
valueHash (for none)
valueHash (for onHidden)

The reason is, I have custom buttons for saving and submitting a survey.
I want to use valueHash (none) for navigating around the survey (so hidden stuff is cached),
but valueHash (onHidden) for when survey is saved. 

Thanks!

**Comment by andrewtelnov** [comment]
@cliewdevelop [clearInvisibleValues](https://surveyjs.io/Documentation/Library/?id=surveymodel#clearInvisibleValues) = "onComplete" will do what you need.

Thank you,
Andrew

**Comment by cliewdevelop** [comment]
Hi Andrew, actually it will not be what I need
The reason is, I want the onComplete version of the valueHash in the middle of the survey for when I save the survey (that does not go through the survey complete flow)

In other words, I have a custom save and complete flow that is outside the surveyjs complete.

Thoughts?

**Comment by andrewtelnov** [comment]
This code should work for you then:
```
var questions = survey.getAllQuestions();
for (var i= 0; i < questions.length; i++) {
   questions[i].clearValueIfInvisible();
}
```

Thank you,
Andrew

**Comment by cliewdevelop** [comment]
Thanks Andrew! This worked beautifully. Cheers.
