### ISSUE TITLE
expression validator doesn't work

### ISSUE THREAD

**Issue by MugiwaraNoMehdi** [surveyjs/surveyjs#1475]
### Are you requesting a feature, reporting a bug or asking a question?

I think it's a bug

### What is the current behavior?

I am trying to use expression validators like here : 
https://www.surveyjs.io/Examples/Library/?id=validators-expression&platform=Angular2&theme=default
but it seems that it doesn't work on your example too... 

### What is the expected behavior?

expected to work ^^

### How would you reproduce the current behavior (if this is a bug)?

test it in your example

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://www.surveyjs.io/Examples/Library/?id=validators-expression&platform=Angular2&theme=default then click on edit in plunker

**Comment by andrewtelnov** [comment]
@MugiwaraNoMehdi Could not find what is wrong here.
"expression": "{serviceRate} < 7 or {serviceComment} notempty" - it doesn't generate an error if rate is less than 7 or comment is not empty, so it shows error if rate is 7 or higher and comment is empty.

Thank you,
Andrew

**Comment by MugiwaraNoMehdi** [comment]
Thank you for your answer it's my brain that is not working the right way...
