### ISSUE TITLE
play with description and error on server validation

### ISSUE THREAD

**Issue by MugiwaraNoMehdi** [surveyjs/surveyjs#1478]
### Are you requesting a feature, reporting a bug or asking a question?

asking a question

I have a survey with Id input text, what I need is that when I enter an Id it will do a rest call to find Id correspondance, if found it will show details in option.description, if not found fire error.

### What is the current behavior?

what I've found now is that I can call server validation with onServerValidateQuestions.
but it works only for validating current page when someone click on next button, I want to use it onblur, and I can't change description with it.

what I need is something like : 

surveyModel.onValueChanged.add((survey, options) => {
     callApi().subscribe(
          data => {
                survey.getQuestionByName(options.name).description = data;
                Survey.SurveyNG.render("surveyElement", survey);
          },
          error=> {
                options.error = "Id not found";  // this does nothing, don't have options.complete()
          } 
     )
 });

Is there anyway to do it ? Sorry if it is not well explained.

**Comment by MugiwaraNoMehdi** [comment]
I created a plnkr to explain the issue : https://plnkr.co/edit/489lS6qS3zzheZdOA4rY

**Comment by MugiwaraNoMehdi** [comment]
found it myself in a disgusting way
thank you for your help

**Comment by andrewtelnov** [comment]
@MugiwaraNoMehdi I don't know your solution, but you may use [onValueChanging](https://surveyjs.io/Documentation/Library/?id=surveymodel#onValueChanging) event and call options.question.hasErrors(true) function to validate the value and show/clear errors.

**Comment by MugiwaraNoMehdi** [comment]
thank you for your answer, I did it that way with onValueChanging, I think it's not a good way because it's okay for one field, but when you have 10 fields like that on a survey you have also 10 custom validators... 
If you want to see my example it's in the plunker https://plnkr.co/edit/489lS6qS3zzheZdOA4rY

**Comment by andrewtelnov** [comment]
@MugiwaraNoMehdi You have to move the validatating code into   MyTextValidator.prototype.validate function and leave validate function as:
```js
function validate(survey, options) {
  if(options.name == "country") options.question.hasErrors(true);
}
```
or just set the property:
`survey.checkErrorsMode = "onValueChanged";`

Thank you,
Andrew

**Comment by MugiwaraNoMehdi** [comment]
I can't move it in  MyTextValidator.prototype.validate  because I cant change description there

**Comment by MugiwaraNoMehdi** [comment]
Thank you very much I think it's the answer I was looking for !
