### ISSUE TITLE
How to get the current question ftom onValueChanged?

### ISSUE THREAD

**Issue by flowt-au** [surveyjs/surveyjs#1481]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
I want to track which was the last answered question. i.e. the last one whose value changed. So, of course, I am using the onValueChanged event listener.

BUT… my survey has dynamic panels and when a question value changes the options parameter passed to the listener is for the **whole dynamic panel**, not the question that triggered the value change!

I have trawled through the docs and the debugger and cannot find the way to know which actual question input changed that triggered the onValueChanged() event.

I must be missing something obvious, sorry.

Thanks,
Murray

### What is the expected behavior?
onValueChanged passes the question rather than the whole panel.

### Specify your

* surveyjs platform: jquery 
* surveyjs version: 1.0.59

**Comment by andrewtelnov** [comment]
@flowt-au Please use the [onDynamicPanelItemValueChanged](https://surveyjs.io/Documentation/Library/?id=surveymodel#onDynamicPanelItemValueChanged) event.

Thank you,
Andrew

**Comment by flowt-au** [comment]
Ah ha! I missed that one. I also notice there is a onMatrixCellValueChanged too. 

Thanks!
