### ISSUE TITLE
First page does not display when firstPageIsStarted is true

### ISSUE THREAD

**Issue by reclaimingmytime** [surveyjs/surveyjs#1482]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug.

### What is the current behavior?
Starting with version v1.0.60, when the attribute _firstPageIsStarted_ is set to _true_, the first page is simply ignored. Only the start button is shown, but not the first question.

### What is the expected behavior?
The first question is shown completely above to "start" button. This was working up to v1.0.59 and is even used at a [demonstration for a history quiz](https://jsfiddle.net/surveyjs/5ud8y1gs) officially by surveyJS.

### How would you reproduce the current behavior (if this is a bug)?
Use surveyJS 1.0.60. 
Create at least two pages with content and set _firstPageIsStarted_ to _true_. You'll notice the first page will magically disappear. Then set _firstPageIsStarted_ to _false_, and you'll notice the first page isn't gone.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
v1.0.60 (not working): https://jsfiddle.net/hs67nfzy/2/
v1.0.59 (working): https://jsfiddle.net/2up6tbck/2/

Test code

```
<div id="surveyElement"></div>
```

```
Survey.Survey.cssType = "bootstrap";

var json = {
    firstPageIsStarted: true,
    pages: [
        {
            questions: [
                {
                    type: "html",
                    html: "This <abbr>HTML</abbr> should be <strong>displayed</strong>."
                }
            ]
        }, {
            questions: [
                {
                    type: "radiogroup",
                    title: "How are you?",
                    choices: [
                        "Great"
                    ]
                }
            ]
        }
    ]
};

var survey = new Survey.Model(json);

$("#surveyElement").Survey({
  model: survey
});
```
### Specify your

* surveyjs platform: jQuery
* surveyjs version: 1.0.60

**Comment by andrewtelnov** [comment]
@reclaimingmytime The bug has been fixed, a unit test has been modified to reproduce the issue.
The issue was introduced due perfomance optimization.

Thank you,
Andrew
