### ISSUE TITLE
When onValueChanged() returns a dynamic panel, isPanel is false

### ISSUE THREAD

**Issue by flowt-au** [surveyjs/surveyjs#1483]
### Are you requesting a feature, reporting a bug or asking a question?
Bug, I think.

### What is the current behavior?
As per Andrew's answer to issue #1481, I am now using onDynamicPanelItemValueChanged to get the actual question that triggered the change. Cool.

For dynamic panels the onValueChanged still fires and passes the the whole panel as described in #1481, and onValueChanged also fires for "normal" page questions which is also what I want.

In onValueChanged I need to differentiate between a "normal" question and a dynamic panel because I want to ignore the dynamic panel. 

However, in the case of a dynamic panel, `options.question.isPanel == false` when I would have thought it should be `true`. ?

### What is the expected behavior?
`options.question.isPanel == true ` when the `options` passed to onValueChanged() is a dynamic panel.

* surveyjs platform: jquery 
* surveyjs version: 1.0.59

**Comment by flowt-au** [comment]
My workaround is:

    function setLastChangedQuestion(options){
        var lastChangedQuestion = {};

                    // Will be called from a question on a page (onValueChanged),
                    // or a question on a dynamicpanel (onDynamicPanelItemValueChanged)
                    // or a question on a matrix dropdown or dynamic (onMatrixCellValueChanged).
                    // Capture the actual QUESTION that triggered the change.

                    // If options is a dynamicpanel we want to ignore it.
                    // This will have been called from onValueChanged() because 
                    // a question on the dynamic panel changed. onDynamicPanelItemValueChanged()
                    // will also be fired which is the actual question and we want that one.

        if (options.question.allowAddPanel && options.itemIndex == undefined) {
                    // Is a dynamic panel called from onValueChanged(). Ignore it
        } else {
            lastChangedQuestion = {
                name        : options.name,
                panelName   : (options.question.name === options.name) ? null : options.question.name,
                panelIndex  : options.itemIndex
            }

        }     

        return lastChangedQuestion;
    }

**Comment by andrewtelnov** [comment]
@flowt-au options.question.isPanel returns true for a Panel container only.
You may use `options.question.getType() === "paneldynamic"`
I understand, that it doesn't sounds right, but there are three types of visual elements in SurveyJS:
Pages, Panels and Questions.
Questions are elements that has value.
Panels are containers that may contain other panels and questions. They do not have a value property.
Pages contains Panels and Questions.
Library treats PanelDynamic as a question. It is parent of a Question type

Thank you,
Andrew

**Comment by flowt-au** [comment]
Thanks Andrew. That explanation helps me get my head around it. This is where I settled and all seems to work.

    if (options.question.getType() === "paneldynamic" && options.itemIndex == undefined) {
        // Is a dynamic panel called from onValueChanged() so options.question 
        // is the dynamic panel that **contains** the question that changed, 
        // not the actual question that changed. Ignore it.
    } else {
        // Is a "real" question. This becomes the remembered LastChangedQuestion ...
    } 

Thanks again for your great work. :-)

**Comment by flowt-au** [comment]
My workaround is:

    function setLastChangedQuestion(options){
        var lastChangedQuestion = {};

                    // Will be called from a question on a page (onValueChanged),
                    // or a question on a dynamicpanel (onDynamicPanelItemValueChanged)
                    // or a question on a matrix dropdown or dynamic (onMatrixCellValueChanged).
                    // Capture the actual QUESTION that triggered the change.

                    // If options is a dynamicpanel we want to ignore it.
                    // This will have been called from onValueChanged() because 
                    // a question on the dynamic panel changed. onDynamicPanelItemValueChanged()
                    // will also be fired which is the actual question and we want that one.

        if (options.question.allowAddPanel && options.itemIndex == undefined) {
                    // Is a dynamic panel called from onValueChanged(). Ignore it
        } else {
            lastChangedQuestion = {
                name        : options.name,
                panelName   : (options.question.name === options.name) ? null : options.question.name,
                panelIndex  : options.itemIndex
            }

        }     

        return lastChangedQuestion;
    }
