### ISSUE TITLE
Show several errors if several validators failed

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#1486]
Right now, we are showing the error for the first validator that failed. It is better to show all errors at once, to let the end-user correct the value one time, based on showing errors.

**Comment by Miletes** [comment]
Hello Andrew,
a couple of ours ago my project (with surveyjs) was working fine and now when loading the page it can't load some file "index.js" from "https://unpkg.com/survey-knockout". The file simply doesn't exist in any version. Can you help me pelase?
Thanks in advance
Miguel

**Comment by dmitrykurmanov** [comment]
@Miletes plese see https://github.com/surveyjs/surveyjs/issues/1487
