### ISSUE TITLE
Custom message for correct submissions in quiz mode.

### ISSUE THREAD

**Issue by craigsands** [surveyjs/surveyjs#1489]
### Are you requesting a feature, reporting a bug or asking a question?
Feature

### What is the current behavior?
None

### What is the expected behavior?
I would like to display a custom message such as 'Correct!' along the same lines as specifying a question.error would display 'Incorrect!'.

```
survey
  .onValidateQuestion
  .add(function (s, options) {
    options.question.readOnly = true;

    if (options.value != options.question.correctAnswer) {
      options.error += "The correct answer is '${options.question.correctAnswer}'.";
    }

    if (options.value == options.question.correctAnswer) {
      options.correct+= "You got it right!";
    }
  });
```

**Comment by andrewtelnov** [comment]
@craigsands Unfortunately, it would not work. The library will beleive that there is an error in this question and would not allow to go to the next page or complete the survey untill the user correct the value and the error is disappeared.
I guess, you may use [onAfterRenderQuestion event](https://surveyjs.io/Examples/Library/?id=survey-afterrender). You may generate the html + javascript code.

Thank you,
Andrew

**Comment by craigsands** [comment]
In case anyone is curious, I ended up using the [toastr](https://codeseven.github.io/toastr/) library instead to do this:

```javascript
function addToastOnCorrect(survey) {
  survey
    .onValidateQuestion
    .add(function (sender, options) {
      if (options.value == options.question.correctAnswer) {
        toastr.success('Correct!');
      }
    });
}
```
