### ISSUE TITLE
remove browser.js depending

### ISSUE THREAD

**Issue by b166er** [surveyjs/surveyjs#1491]
### Are you requesting a feature, reporting a bug or asking a question?
feature/enhancement

### What is the current behavior?
browser.js is deprecated: https://stackoverflow.com/questions/36696601/why-is-browser-min-js-needed-in-reactjs#43940268 and broken: https://github.com/babel/babel/issues/5108#issuecomment-272603948

### What is the expected behavior?
replace browser.js with something up to date or own code

#### Provide the test code and the tested page URL (if applicable)
https://surveyjs.io/Examples/Library/?id=questiontype-text&platform=Reactjs

### Specify your

* browser: Google Chrome
* browser version: v71
* surveyjs platform: react v16.7.0
* surveyjs version: v1.0.61

**Comment by dmitrykurmanov** [comment]
@b166er hello! Thank you for the suggestion! We are using "browser.js" in our react examples not in the source code so I think that it is not so dangerous. But anyway could you please suggest to us an alternative dependency for using in the es5 way.

**Comment by dmitrykurmanov** [comment]
I've tried `babel-standalone` package and it seems like ok. Here an example: https://plnkr.co/edit/GcLOEJhARXoKeRCfEhQf?p=preview . We can upgrade our examples I think.

**Comment by dmitrykurmanov** [comment]
@b166er  is [babel-standalone](https://github.com/babel/babel-standalone) ok ? I've updated our site and it looks ok.

**Comment by b166er** [comment]
i think this version is more up to date: https://github.com/babel/babel/tree/master/packages/babel-standalone (Website: https://babeljs.io/docs/en/next/babel-standalone.html)

CDN is: https://unpkg.com/@babel/standalone/babel.min.js

**Comment by dmitrykurmanov** [comment]
@b166er ok thank you! I've updated the cdn link. It will be available in the next minor release.
