### ISSUE TITLE
Server Validators

### ISSUE THREAD

**Issue by AnnemiekeNL** [surveyjs/surveyjs#1492]
Hi guys,

There seems to be a bug in the example for server validation (https://surveyjs.io/Examples/Library/?id=validators-server&platform=Vue&theme=default).

The error in the console is: Uncaught TypeError: Cannot read property 'add' of undefined.

I can't get the server validation to work.

* browser: chrome
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version:  1.0.61

**Comment by MugiwaraNoMehdi** [comment]
you can test it on the example you posted with this  : 
survey.onIsValidatingOnServerChanged = surveyValidateQuestion;

It was working not long ago... it seems there is a bug...

**Comment by tsv2013** [comment]
Thank you for the report. We'll work on the fix.

**Comment by andrewtelnov** [comment]
We have to fix our example.
Please use [the following example](https://plnkr.co/edit/LGhJClrLVpwy8FZ0PtrN?p=preview) for now.

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
We've fixed the issue. Fix will be available in the next minor update.

**Comment by AnnemiekeNL** [comment]
Thanks for the quick fix!!
