### ISSUE TITLE
functionality to change to a specific page

### ISSUE THREAD

**Issue by agelospanagiotakis** [surveyjs/surveyjs#150]
Is there any functionality to render a specific page by page number?
moreover page.numValue is not available when showPageNumbers is false

**Comment by andrewtelnov** [comment]
@agelospanagiotakis you may use 
`survey.currentPage = survey.pages[myPageNumber];
`
or 
`survey.currentPage = survey.visiblePages[myVisiblePageNumber];`
The first page number index is 0.

Do you want to have something like: survey.currentPageNo on get and set?

Thank you,
Andrew

**Comment by agelospanagiotakis** [comment]
i was using 
  survey.currentPageValue = survey.getPage(pageNumber);
   survey.render();

it would be lovely to have currentPageNo 
Thank you,
I also want to translate to greek your tool.

**Comment by andrewtelnov** [comment]
@agelospanagiotakis Yes, I will add the currentPageNo property shortly. I will let you know.
 And It would be great if you create a pull request with the Greek localization!

**Comment by andrewtelnov** [comment]
@agelospanagiotakis currentPageNo property is added. It returns/set the page visible index, starting from 0 to visiblePageCount - 1.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Show of using this property in the [navigation demo](http://surveyjs.org/examples/jquery/survey-customnavigation.html)

**Comment by andrewtelnov** [comment]
@omkardusane Here is the link on the new web site: https://surveyjs.io/Examples/Library/?id=survey-customnavigation

Thank you,
Andrew

**Comment by omkardusane** [comment]
Hi @andrewtelnov , 

The example you shared seems to work exactly as I need, 
but my implementation doesn't and it throws the exception in browser. 

Details: 
This is the code
```                
                           /** ksrv is  new Survey.Model(someJson)
                                This doesn't work  */
                            ksrv.currentPageNo(index);
                            /* This Works */
                            ksrv.currentPage = ksrv.visiblePages[index];
```

`ksrv.currentPageNo(index)` throws following error
```
vue.js:529 TypeError: ksrv.currentPageNo is not a function
```

The library version I am using is 1.0.1 from 
https://github.com/surveyjs/surveyjs/releases/tag/v1.0.1

The survey.vue.min.js even has a reactiveGetter registered as following:
 ```
   Object.defineProperty(t.prototype,"currentPageNo",{get:function(){return this.visiblePages.indexOf(this.currentPage)},set:function(e){this.visiblePages;e<0||e>=this.visiblePages.length||(this.currentPage=this.visiblePages[e])},enumerable:!0,configurable:!0})    
```
