### ISSUE TITLE
VueJs File Upload `Clean` button acts as a submit button

### ISSUE THREAD

**Issue by exnihilo-creatio** [surveyjs/surveyjs#1506]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

Building from the File input VueJS example. Using the 'Clean' button for the File input tag refreshes the page.

The feature uses a `button` without a specified `type` attribute. However, `buttons` default to type `submit`. Hence, clicking on this feature works just as a submit button. With the current library, it refreshes the page.

### What is the expected behavior?

The page is not refreshed after clearing out the documents.

### How would you reproduce the current behavior (if this is a bug)?

Set `storeDataAsText: true` and click on the `Clean` button.

https://next.plnkr.co/edit/LBmfTtHf1qhDo0ln

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://next.plnkr.co/edit/LBmfTtHf1qhDo0ln

Test code

``` javascript
var json = {
    questions: [
        {
            type: "file",
            title: "Please upload your photo",
            name: "image",
            storeDataAsText: true,
            showPreview: true,
            imageWidth: 150,
            maxSize: 102400
        }
    ]
};
```

### Specify your

* browser: Chrome
* browser version: 71
* surveyjs platform (angular or react or jquery or knockout or vue): vuejs
* surveyjs version: latest

**Comment by dmitrykurmanov** [comment]
@exnihilo-creatio  Hello! Thanks for the reporting. We've fixed the issue. Please check https://surveyjs.answerdesk.io/internal/ticket/details/T1468
