### ISSUE TITLE
[Survey][React] event handlers as react props works incorrectly

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/surveyjs#1509]
related to https://github.com/surveyjs/surveyjs/issues/1504

see @stsiushkevich  's plunk: https://plnkr.co/edit/kXddaSc9zD9BwCX7Z71w?p=preview

**Comment by dmitrykurmanov** [comment]
we add new event handler with every props update: https://github.com/surveyjs/surveyjs/blob/master/src/react/reactSurvey.tsx#L255

so handlers accumulate and the behavior become unexpected

**Comment by dmitrykurmanov** [comment]
@stsiushkevich I thinks that the fix : https://github.com/surveyjs/surveyjs/commit/23d7e9eed207a55b0f1bf8f6b319174a18a7f28b will solve the problem 

please check the plunk with latest build  https://plnkr.co/edit/Fo4J1s7nrw7onpowfSWX?p=preview

**Comment by stsiushkevich** [comment]
> @stsiushkevich I thinks that the fix : [23d7e9e](https://github.com/surveyjs/surveyjs/commit/23d7e9eed207a55b0f1bf8f6b319174a18a7f28b) will solve the problem
> 
> please check the plunk with latest build https://plnkr.co/edit/Fo4J1s7nrw7onpowfSWX?p=preview

It works fine.
