### ISSUE TITLE
Internet explorer 11 issue with the image picker

### ISSUE THREAD

**Issue by remytesta** [surveyjs/surveyjs#1516]
Hi everyone,

**Are you requesting a feature, reporting a bug or asking a question?**

There is a bug on Internet Explorer 11 with the "Image picker"

**What is the current behavior?**

Its hard to select the good choice with the mouse. Indeed you have to click closed from the border to select.

**What is the expected behavior?**

You should select the image with a click anywhere on the picture

**How would you reproduce the current behavior (if this is a bug)?**

On internet explorer 11

**Provide the test code and the tested page URL (if applicable)**

Here the fix I found.

.sv_main .sv_container .sv_body .sv_p_root .sv_q .sv_q_imgsel label > div > img { 
	pointer-events : none; 
}

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by dmitrykurmanov** [comment]
and it works in the IE9 and IE10 emulation LOL

**Comment by dmitrykurmanov** [comment]
related issue on SO: https://stackoverflow.com/questions/20524815/ie-11-bug-image-inside-label-inside-form
