### ISSUE TITLE
Inconsistency with visibleIf in survey result

### ISSUE THREAD

**Issue by andreacappadona17** [surveyjs/surveyjs#152]
If you compile a survey answering in a way that some questions with visibleIf property would show, when you invalidate the condition, the answers to the questions with visibleIf are still written in the result.
You can see that even on the documentation page.

http://surveyjs.org/examples/condition-kids.html

Here is a not valid result: 
The results are: {"haveKids":"No","kids":3,"kid1Age":5,"kid2Age":3,"kid3Age":6}

**Comment by andrewtelnov** [comment]
@andreacappadona17 
survey doesn't clean the value of an invisible question. You may make it visible at any moment and your users would expect to have the value they have entered before.
There is a property however, that will help you: clearInvisibleValues. It is false by default. Just set it to true, and you will be fine. I will add a note to the example.  
`survey.clearInvisibleValues = true;`

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Update the demo: http://surveyjs.org/examples/jquery/condition-kids.html
