### ISSUE TITLE
prefix or rename "progress" and "progress-bar" classes

### ISSUE THREAD

**Issue by avkieu** [surveyjs/surveyjs#1520]
### Are you requesting a feature, reporting a bug or asking a question?
Bug/Feature

### What is the current behavior?
survey.jquery.min.js will add a style tag to the page containing`.progress { width: 60%; } .progress-bar: {width: auto; margin-left: 2px; margin-right: 2px; }`, This can apply to other unintended elements considering the name is generic enough to be on many sites and/or other libraries.

[Line 35 stylesmanager.ts](https://github.com/surveyjs/surveyjs/blob/adbd095a0fffd2a6f75439f06d1c707480c9f6bb/src/stylesmanager.ts#L35)

### What is the expected behavior?
Class names replaced or prefixed with "sv" like everything else, therefore other page elements are not effects by surveyjs's CSS. 

### How would you reproduce the current behavior (if this is a bug)?
Create a webpage with an element with class "progress", `.progress: { width: 100% }` in a stylesheet, and  loading survey.jquery.min.js. The progress elements will have width of 60%.

**Comment by dmitrykurmanov** [comment]
@avkieu thank you for the reporting. This styles need only for the "Bootstrap" theme and they should be isolated. Fix will be available in the  next minor update.
