### ISSUE TITLE
Matrixdropdown : impossible to specify other text

### ISSUE THREAD

**Issue by nelero** [surveyjs/surveyjs#153]
In matrixdropdown question,
on survey editor : we can specify "has other item" but we can't precise otherText, otherTextError. (see screenshot here https://www.dropbox.com/s/etmqbr96qpag6ra/Capture.PNG?dl=0 )
in JSON, even if we precise those properties, nothing happened (it display always "other")

**Comment by andrewtelnov** [comment]
@nelero Yes, there is no way to do it right now. You may change it via localization for all questions in the survey:
Survey.surveyStrings.otherItemText = "my new other";
Survey.surveyStrings.otherRequiredError = "new other required error";
Here is a [demo](http://surveyjs.org/examples/survey-localization.html)

I may do it on the question (matrixdropdown) level or on the column level (in case you need different text for different columns). What do you need for your survey? I do not want to over complicate the library, if there is no a need for this.

Thank you,
Andrew
