### ISSUE TITLE
upgrade guidelines

### ISSUE THREAD

**Issue by masciugo** [surveyjs/surveyjs#1533]
I need to upgrade from 1.0.33 to the latest version (1.0.67). Is there any guideline to follow? I think the changelog file is rather useless when the gap between the two version is wide. Or maybe semantic versioning is in use so that breaking changes should not have been added?

**Comment by andrewtelnov** [comment]
@masciugo We try our best do not make any breaking changes. I do not remember that we do any.
We are going to introduce one in a week, but again it would not effect 99% of our users.
We are going to separate question/page title and numbering. It will let survey looks cool.

PS: We are going to release v1.0.68 tomorrow, we have fixed couple bugs our customers found.

Thank you,
Andrew

**Comment by glumb** [comment]
What about using the de facto standard Semantic versioning (https://semver.org):

 MAJOR.MINOR.PATCH
- MAJOR version when you make incompatible API changes,
- MINOR version when you add functionality in a backwards compatible manner, and
- PATCH version when you make backwards compatible bug fixes.

This way one can safely update all Patch and Minor versions. 🙂

**Comment by andrewtelnov** [comment]
@glumb This is what we have in other projects/companies: Major.Minor.Patch. To be honest, we do not know a good way of doing it.
For example, if you are releasing a major update, lets say every 6-24 month and have minor update every 2-12 weeks and fix severity bugs as patchs, it makes perfect sense.
Here we use to release every week, commonly on Tuesday. If the functionality is big enough and it could not be coded/tested during one week iteration, then it continues to exists in a separate branch and our task to merge it into master ASAP. It is hard to support several branches at once.
We was thinking to go with year.month.day or year.week.patch, but it can confuse users even more.

PS: Today we are releasing a large update for SurveyJS Creator, something that was in separate branch for several months. We merged it about a week ago into master. It will come as 1.5.0
