### ISSUE TITLE
choicesVisibleIf not working

### ISSUE THREAD

**Issue by masciugo** [surveyjs/surveyjs#1534]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

choicesVisibleIf seems not working with matrixdynamic or at least with my model

### What is the expected behavior?

should work like this https://surveyjs.io/Examples/Library/?id=condition-choicesVisibleIf

#### Provide the test code and the tested page URL (if applicable)

https://plnkr.co/edit/tcmJiLB7uJLdgTiefkE2?p=preview

**Comment by tsv2013** [comment]
Fixed
