### ISSUE TITLE
SurveyJS resetting state in React in the Quiz mode

### ISSUE THREAD

**Issue by StephanMeijer** [surveyjs/surveyjs#1535]
### Are you requesting a feature, reporting a bug or asking a question?
Bug.

### What is the current behavior?

![bug](https://user-images.githubusercontent.com/3169264/52359761-d4e8b100-2a3a-11e9-8662-9e33868ef6d4.gif)

### What is the expected behavior?

To not reset form

### How would you reproduce the current behavior (if this is a bug)?

???

I am using last versions of the packages, but I am still not sure why this error occurs.

### Specify your

* browser: Safari, Chrome and Firefox
* surveyjs platform react
* surveyjs version: 1.0.67

**Comment by dmitrykurmanov** [comment]
Hello! Thank you for the reporting. I don't manage to reproduce it. Could you please provide an example or json to reproduce the problem.

**Comment by StephanMeijer** [comment]
@dmitrykurmanov Will come back at this.

**Comment by StephanMeijer** [comment]
```
this.model = new Survey.Model(intake());
// ...
this.model.startTimer();
// ...
this.model.stopTimer();
```

Removed the timers. Fixed it.

**Comment by StephanMeijer** [comment]
> Call this method to start timer that will calculate how much time end-user spends on the survey or on pages

https://surveyjs.io/Documentation/Library/?id=surveymodel#startTimer

Hmm, why would this fix anything at all?

**Comment by dmitrykurmanov** [comment]
@StephanMeijer Hello! Thank you for the comment https://github.com/surveyjs/surveyjs/issues/1535#issuecomment-462466472

You are using quiz and I've reproduced the bug.

**Comment by dmitrykurmanov** [comment]
We've fixed the bug. Fix will be available in the next minor update.

**Comment by StephanMeijer** [comment]
@tmvnk 🎉

**Comment by StephanMeijer** [comment]
Glorious! Thank you so much <3
