### ISSUE TITLE
Checkbox with one choice / inconsistency in JSON

### ISSUE THREAD

**Issue by nelero** [surveyjs/surveyjs#154]
If we have a checkbox question with one choice, like  "[x] i accept the terms & conditions", JSON value returned by survey.data is an object {0:'yes'} and if we set survey data with this value, an indexOf exception is thrown : 
val.indexOf is not a function in   survey.ko.js line 4658

**Comment by andrewtelnov** [comment]
@nelero I have failed to reproduce the issue :-( Could you please send me the JSON that doesn't work and JavaScript code, if you modify survey somehow.
Right now, I can see that the value 0 (numeric) converts to value "0" (string) for the question:
`{ type: "checkbox", name: "q1", isRequired: true, choices: [{value: 0, text: "Yes"}] }`.
 Probably this is the reason or maybe just a separate bug.

Thank you,
Andrew
