### ISSUE TITLE
columnsVisibleIf makes matrixdynamic crashes

### ISSUE THREAD

**Issue by masciugo** [surveyjs/surveyjs#1540]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?
I would like to hide a matrixdynamic column by using columnsVisibleIf but it crashes. Just comment out `"columnsVisibleIf": "{item} != 'id'"` in the example to have it working

### What is the expected behavior?

hide the id column

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/66sWH6azGMc81l9GmE3K?p=preview

**Comment by andrewtelnov** [comment]
@masciugo The fix will be available in the next minor update, most likely tomorrow.

Thank you,
Andrew
