### ISSUE TITLE
clearInvisibleValues directive exceptions

### ISSUE THREAD

**Issue by masciugo** [surveyjs/surveyjs#1542]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

I'd like to keep some invisible field in the survey.data. I know I can use clearInvisibleValues: 'none' but I actually need to clear invisible values most of the times so I use clearInvisibleValues: 'onHidden'. In few words I need to add exceptions to the above rule

**Comment by andrewtelnov** [comment]
@masciugo I was trying to make an example with onValueChanging event. However, it doesn't work in the current build. We have change the way we are working with question.value to improve the performance. We will fix it, by adding new unit test(s) and I will comeback. 

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
From the next minor version you will be able to use the following code:
```
  survey.onValueChanging.add(function(sender, options){
    if(options.name == "yourQuestionValueName" && !options.value) {
      //if the value is null or underfined, set the old value back
      options.value = options.oldValue;
    }
  });
```

Thank you,
Andrew

**Comment by masciugo** [comment]
Thanks Andrew. I tried to recap my need in simple terms but use case is more complex. I have a matrixdynamic and its first column need to be hidden but kept in the data. By your snippet I guess is not feasible as the value of the question is the whole matrixdynamic value object

**Comment by masciugo** [comment]
Maybe it's too complex and specific to my use case. What about hiding it by css? In the end I only need to keep it hidden to the user and not invisible along with its logical consequences.  
I tried this way:
```
survey.onUpdateQuestionCssClasses.add(function (survey, options) { //to be removed after
  if (options.question.name == 'id') {
    options.cssClasses.root = 'hidden'
  }
});
```
but the td element is still visible

**Comment by masciugo** [comment]
moreover the css solution is not 100% satisfying as I need to hide the _id_ question when, and only when, its a column of a matrix/panel dynamic whose name end with __attributes_. I could not find a way to check the "wrapping question" once I catch the question named _id_

**Comment by andrewtelnov** [comment]
I have added onMatrixCellValueChanging event. You may use it as:
```
    survey.onMatrixCellValueChanging.add(function(sender, options) {
      if (options.columnName == "experience" && !options.value) {
        options.value = options.oldValue;
      }
    });
```
I hope we will release a new version today.

Thank you,
Andrew

**Comment by masciugo** [comment]
@andrewtelnov thanks for your effort. I tried with the new release but as you can see from the following plunk https://plnkr.co/edit/66sWH6azGMc81l9GmE3K?p=preview if the survey is preloaded with some data which is not visible (the id column) it then gets lost after some edits. For example if I try to change the first member role from collaborator to co-investigator its id column value disappears  

![screen shot 2019-02-14 at 15 59 15](https://user-images.githubusercontent.com/454321/52795681-96727800-3072-11e9-832e-d8693c42c40e.png)

and I cannot find a way to revert the change: the 146 line never gets executed

**Comment by masciugo** [comment]
I ended up adding some logic to recognise the data value that need to be kept. I added the logic in the `onValueChanging` callback for matrixdynamic question 

```
        if (options.oldValue.length == options.value.length) { // it's not an addition or deletion: its an row update
          _.forEach(options.oldValue, (row,index) => {
            if (row.id) {  // keep the old id if it exists
              options.value[index].id = row.id
            }
          })
        }
```

**Comment by andrewtelnov** [comment]
@masciugo Sorry, I missed your comment. Anyway, I'm glad that it works for you, finally.

Thank you,
Andrwe
