### ISSUE TITLE
Bug - Submit events not fired when pressing "enter" (vuejs)

### ISSUE THREAD

**Issue by kaphert** [surveyjs/surveyjs#1544]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
When pressing "enter" within a form the form is submitted but it is ignoring all events. 

### What is the expected behavior?
Submitting a form in what ever way should fire the same events. So pressing 'enter' should fire the `onComplete()` event for example. 

### How would you reproduce the current behavior (if this is a bug)?
https://next.plnkr.co/edit/Bm0KtPbOOZV1SUHY

### Specify your
* browser: chrome
* surveyjs platform: vuejs
* surveyjs version: Plnkr is with v1.0.63 but on v1.0.53 it has the same problems

**Comment by dmitrykurmanov** [comment]
Thank you for the reporting. Fix will be available in the next minor update.

**Comment by kaphert** [comment]
The fix you suggests is disabling the "enter" button at all I think. Wouldn't it be better (UX wise) to capture the submit event and do: 

- are we on the last page? -> complete form
- is there a next page? -> go to next page 

This is currently my work around for this issue: 
```
this.$refs['content'].querySelector('form').addEventListener('submit', (e) => {
    e.preventDefault();
    if (survey.isLastPage) {
        this.complete();
    } else {
        this.goToNextPage();
    }
    return false;
});
```

where `complete()` and `goToNextPage()` are my own methods in a wrapper around the surveyjs component.

**Comment by dmitrykurmanov** [comment]
@kaphert  thank you. It looks like enhancement: please follow to the https://github.com/surveyjs/surveyjs/issues/1545
