### ISSUE TITLE
dropdown question - showOptionsCaption = false

### ISSUE THREAD

**Issue by ratneshraval** [surveyjs/surveyjs#1547]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
For `dropdown` question `showOptionsCaption = false` does not remove 'Choose' from the list

### What is the expected behavior?
option 'Choose' should not show up

### How would you reproduce the current behavior (if this is a bug)?
https://next.plnkr.co/edit/yGEovEQu56u9Zrb0

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://next.plnkr.co/edit/yGEovEQu56u9Zrb0

### Specify your

* browser: Chrome, Safari
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.0.69

**Comment by tsv2013** [comment]
Fix will be available in the nearest update

**Comment by ratneshraval** [comment]
That's awesome! thank you.
