### ISSUE TITLE
State setting of nouislider sometimes bugs

### ISSUE THREAD

**Issue by StephanMeijer** [surveyjs/surveyjs#1552]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

![state-setting](https://user-images.githubusercontent.com/3169264/53024154-c220a400-345e-11e9-804e-b5e0e041c880.gif)
![state-setting2](https://user-images.githubusercontent.com/3169264/53024456-699dd680-345f-11e9-934f-44574bbb14e4.gif)

### What is the expected behavior?

It should just work :tm:

### How would you reproduce the current behavior (if this is a bug)?

???

### Specify your

* browser: Chrome (on Mac)
* browser version: `Version 72.0.3626.109 (Official Build) (64-bit)`
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: `1.0.71`
* slider: `nouislider`

**Comment by tsv2013** [comment]
I've checked our online demo - https://surveyjs.io/Examples/Library/?id=custom-widget-nouislider&platform=Reactjs&theme=default and haven't managed to reproduce the issue.

Could you provide steps to reproduce or a sample to reproduce this behavior?

**Comment by StephanMeijer** [comment]
I'll look into it.

**Comment by StephanMeijer** [comment]
Error happens due to failed initialisation of state. Missing properties made the thing bug.
