### ISSUE TITLE
defaultValue for matrix 

### ISSUE THREAD

**Issue by MugiwaraNoMehdi** [surveyjs/surveyjs#1555]
### Are you requesting a feature, reporting a bug or asking a question?
reporting a bug 

### What is the current behavior?
There is a bug with matrix, if I put a "defaultValue" in it, it is well displayed, but if I change the value and complete my survey, the answer sent is the defaultValue... 

### What is the expected behavior?
replace defaultValue by the current value 

### How would you reproduce the current behavior (if this is a bug)?
https://next.plnkr.co/edit/LaMRHD4oMK0Pl8lf

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://next.plnkr.co/edit/LaMRHD4oMK0Pl8lf

**Comment by andrewtelnov** [comment]
@MugiwaraNoMehdi Your defaultValue is incorrect.
Here is [the updated example](https://next.plnkr.co/edit/KICERYlPFCirmgtg)

Thank you,
Andrew

**Comment by MugiwaraNoMehdi** [comment]
Thank you Andrew
