### ISSUE TITLE
survey-react using matrixdynamic question minRowCount validation message not displaying correctly.

### ISSUE THREAD

**Issue by jamesparker01** [surveyjs/surveyjs#1559]
### Are you requesting a feature, reporting a bug or asking a question?

reporting a bug

### What is the current behavior?

On survey-react when creating a matrixdynamic question with a minRowCount:1 property, when you click continue, the validation kicks in and the validation message shows: `Please fill in at least {0} rows.`

### What is the expected behavior?

The validation message should be: `Please fill in at least 1 row.` This behaviour is correct when using just surveyjs without the react wrapper.

### How would you reproduce the current behavior (if this is a bug)?

Using the example code, just click the continue button when the page loads. This was using the latest version of `create-react-app`, and then running `npm i survey-react`.
 
#### Provide the test code and the tested page URL (if applicable)
Test code

repo: https://github.com/jamesparker01/survey-react-issue-1559

```
import React, { Component } from 'react';
import * as Survey from "survey-react";
import "survey-react/survey.css";

class App extends Component {
  get questions() {
    return [
        {
            name: "questionname",
            type: "matrixdynamic",
            title: "questiontitle",
            minRowCount: 1,
            columns: [
                {
                    name: "Col1"
                }
            ],
            cellType: "text"
          }
      ];
  }

  render() {
    const survey = new Survey.Model({
      questions: this.questions
    });

    return (
      <div>
         <Survey.Survey
              model={survey} />
      </div>
    );
  }
}

export default App;

```

### Specify your

* browser: Chrome
* browser version:72.0.3626.109
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: survey-react 1.0.71

**Comment by tsv2013** [comment]
Fix will be available in the nearest update

**Comment by jamesparker01** [comment]
Thank you! 👍
