### ISSUE TITLE
value change callbacks wrongly fired on empty question value when using react

### ISSUE THREAD

**Issue by masciugo** [surveyjs/surveyjs#1564]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

onValueChanged and onValueChanging are fired when question value change from undefined to empty or similar

### What is the expected behavior?

should not be called 

### How would you reproduce the current behavior (if this is a bug)?

correct behaviour with jquery https://plnkr.co/edit/xb8FxHYjwLbeGnGfa759?p=preview
wrong behaviour with react https://plnkr.co/edit/wEt22IAI8nVf23RNCZYH?p=preview

**Comment by tsv2013** [comment]
What should I enter into text input as `undefined` value?

**Comment by masciugo** [comment]
Sorry. if you jump from a field to the other without typing anything you'll see in the console that in the second plunk the callbacks are called but nothing is actually changed

**Comment by tsv2013** [comment]
@masciugo Thanks

**Comment by tsv2013** [comment]
@masciugo Unfortunately I've not managed to reproduce the issue in Chrome: I enter one input by mouse and then go to another input bu mouse, - and my console is clean. I guess I miss something...

**Comment by masciugo** [comment]
mmm .. my chrome should be the last one: Version 72.0.3626.119 (Official Build) (64-bit)



![mar-01-2019 11-11-50](https://user-images.githubusercontent.com/454321/53631498-f2acce80-3c12-11e9-8dab-2d8c59bc940b.gif)

**Comment by tsv2013** [comment]
@masciugo I'm doing exactly the same. Do you have any browser extensions that can affect inputs? Can you turn all extenstions off and try again?

**Comment by dmitrykurmanov** [comment]
@masciugo may be react dev extension or autofill extension

**Comment by masciugo** [comment]
mmm.. no extension. I got the same with firefox which I don't use and it's clean install

**Comment by masciugo** [comment]
I looked into the source code and I found [this](https://github.com/surveyjs/surveyjs/blob/286b8bcb460cba497440ff9e4f115edcad038df8/src/react/reactquestiontext.tsx#L25-L28). I was not able to find any ref to the blur event apart from react version. Can it help?

**Comment by masciugo** [comment]
ended up with this hack:

```
  valueChanged = (survey, options) => {
    if (options.question.oldValue != options.value) {
      this.props.handleChange(survey.data)
    }
  }
  valueChanging = (survey, options) => {
    options.question.oldValue = options.oldValue // keep track of oldValue in order to decide whether run handleChange() in valueChanged callback
    // set blank field to undefined
    if (_.isEmpty(options.value)) {
      options.value = undefined
    }
  }
```
it works even I don't like at all adding a prop (_oldValue_) to a surveyjs core object (_options.question_)

**Comment by dk981234** [comment]
@masciugo  We've found the issue and fixed it (at least one part - extra onValueChanged event call). As for the onValueChanging event - we've discussed it with @andrewtelnov and decided that is should be called on every set value attempt.

Will it fit your needs?

**Comment by masciugo** [comment]
yes it will do the job. thanks a lot and sorry for my late reply
