### ISSUE TITLE
Question error validations do not display

### ISSUE THREAD

**Issue by willgdjones** [surveyjs/surveyjs#1571]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question

### What is the current behaviour?

The question error validations do not appear when I click the 'Complete' button, and I'm not sure why.

### What is the expected behaviour?

The error validations should appear.

### How would you reproduce the current behavior (if this is a bug)?

Hard to suggest - as this works correctly in online Plunkers.

My survey is below:
```
your_code_here

{
   "title":"Survey",
   "pages":[
      {
         "name":"page1",
         "elements":[
            {
               "type":"radiogroup",
               "name":"lunch_yesterday",
               "title":"Stop and think for a second. What did you eat for lunch yesterday? Do you remember?",
               "isRequired":true,
               "choices":[
                  "Yes",
                  "No"
               ],
               "colCount":0
            },
            {
               "type":"checkbox",
               "name":"remember_names",
               "title":"In general, how would you describe your ability to remember names of people you recently met?",
               "isRequired":true,
               "choices":[
                  "Almost always forget",
                  "Not exceptionally good or poor",
                  "Almost always remember"
               ]
            },
            {
               "type":"text",
               "name":"age",
               "title":"How many years old are you?",
               "isRequired":true,
               "requiredErrorText":"some",
               "inputType":"integer"
            },
            {
               "type":"comment",
               "name":"other",
               "title":"Is there anything else you consider interesting or peculiar about your memory?"
            },
            {
               "type":"radiogroup",
               "name":"research_report",
               "title":"",
               "isRequired":true,
               "choices":[
                  "Yes",
                  "No"
               ]
            }
         ]
      }
   ]
}
```

```

<template>
    <survey :survey="survey_obj"></survey>
</template>

...

import * as SurveyVue from "survey-vue";
import * as SurveyEditor from "surveyjs-editor";
import * as Select2 from "select2";
import * as showdown from "showdown";
import * as widgets from "surveyjs-widgets-willgdjones";
window.$ = window.jQuery = require('jquery');
...

methods: {
        loadSurveyObj(survey) {
            var survey_obj = new SurveyVue.Model(survey.definition);
            if (survey.response) {
                survey_obj.data = survey.response.data;
            }
            survey_obj.sendResultOnPageNext = true;
            survey_obj.onCompleting.add(this.completing);
            survey_obj.onPartialSend.add(this.pageChanged);
            survey_obj.onValueChanged.add(this.valueChanged);
            survey_obj.onTextMarkdown.add(this.markdownAdd);
            survey_obj.showCompletedPage = false;
            survey_obj.cssType = "bootstrap";
            survey_obj.css = {
                matrix: {root: "table table-striped"},
                navigationButton: "button--brand survey-button",
                body: "SurveyJsText",
                header: "SurveyJsText",
                footer: "text-center",
                radiogroup: "text-center survey-radio"
            };
            return survey_obj
        },
        markdownAdd(survey, options) {
            var converter = new showdown.Converter();
            var str = converter.makeHtml(options.text);
            str = str.substring(3);
            str = str.substring(0, str.length - 4);
            options.html = str;
        },
        completing(sender, options) {
            console.log('completing')

        },
        pageChanged(result) {
            console.log("survey page changed");
        },
        valueChanged(sender, options) {
            console.log("value changed");
            this.$store.dispatch('sendResponse', {
                data: this.survey_obj.data,
                survey_id: this.survey_id,
                completing: false,
                ask: false
            })
        },
```

* browser: Chrome
* browser version: latest
* surveyjs platform vue:
* surveyjs version: 1.0.72

**Comment by dmitrykurmanov** [comment]
Hello! You wrote:

> Hard to suggest - as this works correctly in online Plunkers.

So I think you could fork and modify our quickstart repo (https://github.com/surveyjs/surveyjs_vue_quickstart). For example on codesandbox: https://codesandbox.io/s/github/surveyjs/surveyjs_vue_quickstart/tree/master/

**Comment by willgdjones** [comment]
I tracked down the issue - it seemed to be a problem with loading the survey definition reactively being loaded from Vuex as opposed to from the server directly. I will dig in today to try and give a reproducible example.

**Comment by willgdjones** [comment]
So - here is a reproducible example. It, in fact, wasn't because it was reading the JSON from Vuex, but because the survey object was a computed property. In this example, you'll see that in the survey when you try to complete the survey without answering the question, the survey fails to complete because the question is required, but there does not display an error message.

https://codesandbox.io/s/829x75319

**Comment by dmitrykurmanov** [comment]
@willgdjones thank you. I will check it.

**Comment by dmitrykurmanov** [comment]
It seems the problem exist if we use a vuejs computed property. If we moved survey model creation in data it will be ok. Looks strange I am not very big specialist in vuejs any suggestiong are welcome

**Comment by willgdjones** [comment]
Yep - that does seem to be the issue.

The reason why I was using computed properties is that I first check if I can load the survey from Vuex, while at the same time requesting the definition from the server. The idea is that if the survey definition does not exist, the component updates when the result is retrieved from the server. If the survey definition does exist, then it is loaded from Vuex and then updated seamlessly when the result is retrieved from the server.

However, since I encountered some problems I stopped trying to retrieve the survey definition from Vuex and I retrieve it from the server each time. It means there is a small wait time for the user but it's negligible.

I think it is because in the example I made above we are passing a prop to the <survey> component which then changes, and these changes might not be passed seamlessly when the prop changes.

**Comment by dmitrykurmanov** [comment]
@willgdjones  please check this answer on SO : https://stackoverflow.com/a/50239808/6623551 So we need to use `data` for that task. Because computed property triggers UI update only when the variables used within it changes.

**Comment by rsiasat00** [comment]
@dmitrykobets By using data it causes issues like $attrs is readonly and $listeners is readonly.

Also, there are some forms where it causes an issue where it's stuck on loading the json form and nothing is returned when viewing it via network.

Sample Code:

`props: {
        json: {
            type: Object,
            required: true
        }
    },
    
    data() {
        return {
            survey: new SurveyVue.Model(this.json)    
        }
    },`
