### ISSUE TITLE
Apostrophes in answers break VisibleIf

### ISSUE THREAD

**Issue by lady3bean** [surveyjs/surveyjs#1575]
See https://plnkr.co/edit/3UG0Vk3KaRyUovWW7EiQ?p=preview - I took the SurveyJS demo and added correlating apostrophes in an answer and a visibleIf setting using that answer. Having apostrophes in answers breaks visibleIf, because of how the quotes work.

### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
Using apostrophes in answers breaks the visibleIf functionality for those answers

### What is the expected behavior?
That users can use apostrophes within answers

### How would you reproduce the current behavior (if this is a bug)?
https://plnkr.co/edit/3UG0Vk3KaRyUovWW7EiQ?p=preview

#### Provide the test code and the tested page URL (if applicable)
https://plnkr.co/edit/3UG0Vk3KaRyUovWW7EiQ?p=preview

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
You nned to escape quotas in conditions.
Here is the fixed plunk - https://next.plnkr.co/edit/bRuXkYM1seoXAEFz

**Comment by lady3bean** [comment]
General users don't know about escaping and will try to use apostrophes without espcaing. Could a fix to the library be to use backticks?

**Comment by andrewtelnov** [comment]
@lady3bean Do you mean in SurveyJS Editor? 
I think yes, we should.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@lady3bean Here is the bug in [Editor repo](https://github.com/surveyjs/editor/issues/476)

Thank you,
Andrew

**Comment by tsv2013** [comment]
Duplicetd of the fixed https://github.com/surveyjs/editor/issues/476
