### ISSUE TITLE
Question validation (right answer)

### ISSUE THREAD

**Issue by davlind87** [surveyjs/surveyjs#158]
Hi,

So I´ve been playing around with Survey.js and Knockout for SharePoint integration project.
This is just superb job in creating a awesome framework. 

One thing that Ive been trying to figure out is to validate which answer my user picks. As per example: 

pages: [
        { title: "Which animal lives in water?",
            questions: [
                {type:"checkbox", name:"animalwater", title: "Animals",  isRequired: true, 
                    choices:["Monkey", "Zebra", "Whale"]}
            ]  
        },

What if I want to force the User to pick the right answer before User can move on? I planned to add some informational text before hand so the User has to read and the find the answer to the question. So in this ex. Whale would be the correct answer. But how to check the answer?

Any ideas?

**Comment by andrewtelnov** [comment]
@davlind87 There are two choices right now.
Validate on the client, please look at the [demo](http://surveyjs.org/examples/validators-event.html) or using ajax request and validate on the server, another [demo](http://surveyjs.org/examples/validators-server.html).
Please, let me know, does it help.

Thank you,
Andrew

**Comment by davlind87** [comment]
@andrewtelnov  Thanks for quick response. I´ve reviewed all of these examples. But I think I´m having it hard to convert or adapt these codings for checkboxes rather than input fields (Form). I understand how to validate if its a Form with Min. Max. or High or Low values. But when the value are already present, how can I make one checkbox in my Ex. Whale the right one? 

Any demo or dummy code so that I can understand and adapt my code. 

Cheers.

**Comment by andrewtelnov** [comment]
@davlind87 In your particular example, I would use radiogroup. 

```
survey.onValidateQuestion.add(function (s, options) {
   if (options.name == 'animalwater') {
       if(options.value != 'Whale') {
            options.error = "The answer is not correct. Please give another answer";
        }
    }
});

```
Thank you,
Andrew

**Comment by davlind87** [comment]
Wow thanks @andrewtelnov !! You should add that to your examples for us "newbies" 

Thanks again.

**Comment by andrewtelnov** [comment]
The demo is here: http://surveyjs.org/examples/jquery/validators-event.html
