### ISSUE TITLE
Prevent moving to next dynamic panel if first dynamic panel has unanswered required questions

### ISSUE THREAD

**Issue by ajien** [surveyjs/surveyjs#1581]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

### What is the current behavior?
When using dynamically created panels, it is possible to move from one panel to another without answering all the required fields from the previous panel.

### What is the expected behavior?
I'd like to prevent moving to the next dynamically created panel if required fields in the first panel have not been answered yet.

### How would you reproduce the current behavior (if this is a bug)?
Here's the example provided on the website:
https://surveyjs.io/Examples/Library/?id=questiontype-paneldynamic&platform=Reactjs#

I'd like to know how I could prevent clicking the Next button if the required fields in the first panel have not been filled yet.

Is there a way to run some kind of validation when clicking the Next button before moving to the next panel dynamic?

**Comment by dmitrykurmanov** [comment]
@ajien thank you for the suggestion. We've discussed it with the team and decided that it make sense. We will implement this feature out of the box.

**Comment by ajien** [comment]
@dmitrykurmanov Thanks! I'll be waiting for it to be implemented.

**Comment by dmitrykurmanov** [comment]
@ajien Could you please tell what version of SurveyJS do you use? I've found that PanelDynamic doesn't work in SurveyJS 0.74 for react (https://github.com/surveyjs/surveyjs/issues/1586)

**Comment by ajien** [comment]
I am currently using version 1.0.66.

**Comment by dmitrykurmanov** [comment]
Feature will be available in the next minor update.
