### ISSUE TITLE
Continue survey from a particular time on the survey timer

### ISSUE THREAD

**Issue by willgdjones** [surveyjs/surveyjs#1588]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

### What is the current behavior?
I am unsure how to continue a survey at a particular time on a timer. It would be great to allow users to continue where they left off on a particular timed survey if they interrupted due to e.g. network issues. 

### What is the expected behavior?

It would be great to be able to continue a survey from a particular time on the timer.

### How would you reproduce the current behavior (if this is a bug)?

N/A

Thanks!

**Comment by andrewtelnov** [comment]
@willgdjones Please look at [this example](https://surveyjs.io/Examples/Library/?id=real-patient-history). It does what you are looking for.
Here is the code:
```
var storageName = "survey_patient_history";
function saveSurveyData(survey) {
    var data = survey.data;
    data.pageNo = survey.currentPageNo;
    window.localStorage.setItem(storageName, JSON.stringify(data));
}
survey.onPartialSend.add(function (survey) {
        saveSurveyData(survey);
});
survey.onComplete.add(function (survey, options) {
    saveSurveyData(survey);
});

survey.sendResultOnPageNext = true;
var prevData = window.localStorage.getItem(storageName) || null;
if (prevData) {
    var data = JSON.parse(prevData);
    survey.data = data;
    if (data.pageNo) {
        survey.currentPageNo = data.pageNo;
    }
}
```

Thank you,
Andrew

**Comment by willgdjones** [comment]
Hi @andrewtelnov - thanks for the response. I think this continues the survey from the current page rather than from the current time if I'm not mistaken? 

Will

**Comment by andrewtelnov** [comment]
@willgdjones Yes, sorry- 
You need survey.timeSpent property:
```
  /**
   * Returns the time in seconds end-user spends on the survey
   * @see startTimer
   * @see PageModel.timeSpent
   */
  public timeSpent = 0;

```
Thank you,
Andrew

**Comment by willgdjones** [comment]
Great - I will try this out! Thanks

**Comment by willgdjones** [comment]
This all worked out.
