### ISSUE TITLE
Question type where the rows are also defined as questions

### ISSUE THREAD

**Issue by vraghu1983** [surveyjs/surveyjs#159]
I really am liking the survey js plugin - however I would like to know if there is a way to make the dymanic rows matrix question type - like a label and text next to it.

The multiple text control suits this - but if i have a header to the table - i cant seem to put it as the second control is always a text. I want 2 labels only for the first row.

**Comment by andrewtelnov** [comment]
@vraghu1983 to be honest, I am not sure I follow you, could you please  post a link to an image?
Do you want some thing like?
| Header 1 | Header 2 | Header 3|
------------------------------------
| label 1     | label 2     | label 3    |
| textinput | textinput | textinput |
------------------------------------
| textinput | textinput | textinput |

Thank you,
Andrew

**Comment by vraghu1983** [comment]
![screenshot - 12_21_2016 10_52_30 am](https://cloud.githubusercontent.com/assets/11383924/21378332/aaeafba8-c76b-11e6-8537-bdcd6c21baf6.png)

**Comment by andrewtelnov** [comment]
@vraghu1983 Great, Now it is clear. 
I am thinking, how from one side make the solution works in your case, and from other side make it useful for other users, including non technical people, and make sure it is simple to use.

I am thinking about adding the categoryName: string property to the column.
To achieve your goal, your columns definition will be: 
{name: "numberYear1", title: "Number", categoryName: "Year - 1"},
{name: "costYear1", title: "Total Cost", categoryName: "Year - 1"},
{name: "numberYear2", title: "Number", categoryName: "Year - 2"},
{name: "costYear2", title: "Total Cost", categoryName: "Year - 2"}
...
Will this solution work for you?

Thank you,
Andrew

**Comment by vraghu1983** [comment]
Ok - how do i tackle the number and total cost columns in that case ?

**Comment by andrewtelnov** [comment]
@vraghu1983 You may use prefix or suffix: Year1_number, Year1_cost/number_Year1/cost_Year1.
In fact instead of:
{Year1: {number: 1, cost: 5 }}, you will have {Year1_number1: 1, Year1_cost: 5}

Thank you,
Andrew

**Comment by vraghu1983** [comment]
Could you help me with a small JSON for just the top row and all columns - rest i can fig out.

**Comment by andrewtelnov** [comment]
@vraghu1983 Here is the example: http://surveyjs.org/builder/index.html?surveyid=fd004830-8b7c-4a7e-8a3b-99cf0ec1b99d

**Comment by vraghu1983** [comment]
Awesome - this is what i required :)
