### ISSUE TITLE
[survey-vue] Input textbox for "other" checkbox hides in safari when clicking on it

### ISSUE THREAD

**Issue by LauBarda** [surveyjs/surveyjs#1592]
### Are you requesting a feature, reporting a bug or asking a question?

reporting a bug

### What is the current behavior?
Checkbox questions have an "Other" text input box. When clicking on the input it hides. Working Ok in Chrome. Hiding in Safari
Working ok for Radio group

### What is the expected behavior?

When clicking on the input it hides the user can enter text and the choice remains checked. 
Working Ok in Chrome. Hiding in Safari

### How would you reproduce the current behavior (if this is a bug)?
Choose other checkbox in safari.
Click on input text  for entering text.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://surveyjs.io/Examples/Library/?id=questiontype-checkbox&platform=Vue&theme=default
https://jsfiddle.net/m5b1gc86/

### Specify your

* browser: Safari
* browser version: Version 12.0
* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version: 1.0.74

**Comment by andrewtelnov** [comment]
@LauBarda We will investigate the issue.

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
Reproduced with Mac and Safari 12.0.3

**Comment by LauBarda** [comment]
Thanks for looking at this so fast!!! :) you are the best!

**Comment by dmitrykurmanov** [comment]
Fix will be available in the next minor update.

Here the example with the latest build: https://plnkr.co/edit/tHKBj4RV5XBz6LmEkwEa?p=preview

**Comment by LauBarda** [comment]
Many thanks!!!! :D is working in the example
