### ISSUE TITLE
onValueChanged is called on keypress for comment questions in Knockout version

### ISSUE THREAD

**Issue by gitslacker** [surveyjs/surveyjs#1594]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug. Note that this issue looks similar to #175 but for knockout. I tested the React version, which does not have this issue.

### What is the current behavior?
On every keypress, onValueChanged is called for comment fields

### What is the expected behavior?
onValueChanged should only be called on blur, as with other question types (e.g. single text)

### How would you reproduce the current behavior (if this is a bug)?
Create a survey with a comment field; bind an onValueChanged function; type in the comment field (the function will be called on each keypress).

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://embed.plnkr.co/dzSq1DPJDL9y6MYiyj3J/

### Specify your

* browser: Chrome
* browser version: 72.0.3626.121
* surveyjs platform (angular or react or jquery or knockout or vue): knockout
* surveyjs version: 1.0.74

**Comment by gologames** [comment]
Thanks for the report, we have fixed the issue. Fix will be available in the nearest minor update.
