### ISSUE TITLE
Edit tab title not updating automatically

### ISSUE THREAD

**Issue by paulocesarpcfj** [surveyjs/surveyjs#1595]
### Are you requesting a feature, reporting a bug or asking a question?

It's a bug

### What is the current behavior?

After editing a survey tab title, it doesn't reflect the change. Just after toggle into tabs the update occurs.

### What is the expected behavior?

The ideal behavior is to edit the Tab Title and update automatically.

Tested page URL: https://surveyjs.io/Survey/Builder/

### Specifications

* Browser: Chrome
* Browser Version: Latest
* SurveyJS Platform: React (But happens on the demo page as well)
* SurveyJS Version: 1.0.75

### How to reproduce

![ezgif com-optimize](https://user-images.githubusercontent.com/7551163/54710159-d3c09e80-4b25-11e9-9359-f785d0d3180f.gif)

**Comment by andrewtelnov** [comment]
@paulocesarpcfj I have fixed it. The fix will be availabe in the next minor update on the next week.

Thank you,
Andrew

**Comment by paulocesarpcfj** [comment]
Awesome!!! Thanks for the quick response. I will wait for the update, then! :)
