### ISSUE TITLE
multiple columns of webservice in valueName

### ISSUE THREAD

**Issue by xCozmox** [surveyjs/surveyjs#1597]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
In Typescript I want to have a dropdownlist with choicesByUrl with a valueName based upon a concatenation. 

### What is the expected behavior?
q1.choicesByUrl.valueName = 'contract' +' '+ 'modification';

Is there any possibility to achieve this?

**Comment by andrewtelnov** [comment]
@xCozmox We do not have functionality from the box. You may use [survey.onLoadChoicesFromServer](https://surveyjs.io/Documentation/Library/?id=surveymodel#onLoadChoicesFromServer) event to modify your item.value as you wish.

Thank you,
Andrew

**Comment by xCozmox** [comment]
@andrewtelnov Thanks. I changed the underlying webservice to provide the data as well in the required format.

Thank you,
xCozmox
