### ISSUE TITLE
Reacting to triggers in custom controls?

### ISSUE THREAD

**Issue by dogwith1eye** [surveyjs/surveyjs#1599]
I have the following trigger setup to change the value of a custom control

`{
      "type": "setvalue",
      "name": "radio",
      "operator": "equal",
      "value": "Yes",
      "setToName": "custom",
      "setValue": "Hello"
}`

I notice the questionValue property on the Question prototype gets triggered, but the value property never does. The value property is what actually fires the valueChangedCallback, which lets a custom control handle changes to values.

As it stands now, the underlying value changes, but i don't get a callback, and so the value is out of sync with the display of the control.

Any ideas on how to fix this discrepancy?

thanks

**Comment by andrewtelnov** [comment]
@dogwith1eye Could you please share an example in plunker or somewhere for investigation?
Do you use custom widget for your custom control and I assume, you are using the latest or close to the latest version (I remember we fixed something related to triggers and values).

FYI: We have an "expression" trigger, it provides more flexibility. Here is [the example](https://surveyjs.io/Examples/Library/?id=trigger-runexpression).

Thank you,
Andrew

**Comment by dogwith1eye** [comment]
[Here's a link](https://plnkr.co/edit/GXM96GIKUjRo39Dh790d) to a the where I'm having the issue.

Basically i want the radio button to trigger the click event on the custom timestamp control. I'm using a trigger to set the value of the timestamp to 'click'. I then handle this in the valueChangedCallback handler. Except the handler never fires even though the value has been modified by the trigger.

**Comment by andrewtelnov** [comment]
@dogwith1eye Indeed there is a bug. survey.setValue(questionName, newValue) doesn't trigger valueChangedCallback. We have rewrote the way we store values in question/survey couple months ago and this one stops to work correctly.
I have added a new unit test, fix it and make a new commit. You can see it.
We will release a new version 1.0.76 on the next week.
You may build it from sources by following instruction in the readme file.

Thank you,
Andrew

**Comment by dogwith1eye** [comment]
Thanks a lot Andrew!

One quick follow up question. If i was to put these controls in a dynamic matrix, would i have to generate a new trigger every time a new row is added to the matrix? Or can you index the trigger so it can be reused for each row of the matrix?

thanks

**Comment by andrewtelnov** [comment]
@dogwith1eye It would be hard to setup these triggers. I would suggest to write a code [onMatrixCellValueChanged](https://surveyjs.io/Documentation/Library/?id=surveymodel#onMatrixCellValueChanged) event.

Here is the [example](https://embed.plnkr.co/plunk/r80ZfA) of using it.

Thank you,
Andrew
