### ISSUE TITLE
Unable to customize editor toolbar css

### ISSUE THREAD

**Issue by vandole** [surveyjs/surveyjs#1600]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
Every toolbar item is only able to be one bootstrap class

![surveyJS plunker](https://user-images.githubusercontent.com/45013707/54784225-4f3b5200-4bf1-11e9-8e55-46ea1115be8e.jpg)

### What is the expected behavior?
Able to set any toolbar item to any bootstrap class we need -- unable to remove the already existing bootstrap class

![surveyJS plunked expected](https://user-images.githubusercontent.com/45013707/54784298-7abe3c80-4bf1-11e9-99d7-9859b6a4adde.jpg)

### How would you reproduce the current behavior (if this is a bug)?
I'm adding a custom button to the toolbar, and then pushing it as i can understand in the examples on the surveyjs site.

when i add my own innerCSS to id "custom-preview" it's not replacing the innerCSS that is already there, so if i'm adding an innerCSS of btn-secondary or btn-danger I am completely unable to remove the btn-primary that is already there.

Test code

https://plnkr.co/edit/aApUBRacErHvlkL78k1o?p=preview

**Comment by andrewtelnov** [comment]
Duplicated. @vandole created [the issue](https://github.com/surveyjs/editor/issues/486) in the correct Repo.

Thank you,
Andrew
