### ISSUE TITLE
Custom widget issue.

### ISSUE THREAD

**Issue by kyparyt** [surveyjs/surveyjs#1601]
I have an issue with adding custom widget to survey toolbox.

I'm trying to create a component with some logic. For the first i had an issue with components names, but after I've read [this](https://github.com/surveyjs/surveyjs/issues/1298) article I've decided to create custom widget.

### Are you requesting a feature, reporting a bug or asking a question?
Asking a question.

### What is the current behavior?
I've already added a widget (according to [this](https://plnkr.co/edit/HdnYE5?p=preview) example), but when i'm trying to select it from toolbox i have a type error
![image](https://user-images.githubusercontent.com/29044474/54842255-25118f00-4cda-11e9-8a82-4f2649250f86.png)

### What is the expected behavior?
Understand how to add custom widgets into my toolbox, for next usage.

#### Provide the test code and the tested page URL (if applicable)

Test code
Widget code the same as in [example](https://plnkr.co/edit/HdnYE5?p=preview);

Adding to toolbar:
```
    editor.toolbox.addItem({
        name: "customitem",
        category: "Waivers",
        iconName: "icon-text",
        isCopied: false,
        title: "custom item",
        json: {
            type: "textwithbutton",
            name: "q1",
            placeHolder: "put some text here",
            buttonText: "Custom button text"
        },
    });
```

### Specify your
* surveyjs platform: jQuery:
* surveyjs version: 1.0.64 - 1.0.74

**Comment by tsv2013** [comment]
@andrewtelnov Do we need to transfer this issue to the corresponding repository?

**Comment by andrewtelnov** [comment]
@kyparyt I have added your code into our custom widget example and it works fine. Here is [the example](https://plnkr.co/edit/zOxrb1LPSi1HexkDoPle?p=preview)

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@kyparyt You are getting the error, because in your code, for some reason, this line is not executed:
`Survey.JsonObject.metaData.addClass("textwithbutton", [], null, "text");`
It registered a new class in the library.

Thank you,
Andrew

**Comment by kyparyt** [comment]
Thank you. It helped me to find solution for my project ;)
