### ISSUE TITLE
iterate result data with matrix type survey

### ISSUE THREAD

**Issue by arifsudibyo** [surveyjs/surveyjs#1604]
### Are you requesting a feature, reporting a bug or asking a question?
question

### What is the current behavior?

I want to use matrix type survey. the sample result is follow:
result: {"car":["Ford"],"Q001001":{"ID4":"1","ID62":"1","ID119":"1"},"Q001002":{"ID4":"5","ID62":"5","ID119":"5"}}

### What is the expected behavior?

I want to take questionid (Q001001,Q001002,etc), id and its value, and then display it. how can i achieve this.
this is piece of code:
survey
                .onComplete                
                .add(function (result) {
                    document
                        .querySelector('#surveyResult')
                    .innerHTML = "result: " + JSON.stringify(result.data);          
                                        
                    $.each(result.data.Q001001, function (i, item) {
                        alert(i + ' : ' + item)                        
                    });

                  $.each(result.data.Q001002, function (i, item) {                       
                        alert(i + ' : ' + item)
                    });

I don't want to repeat writing code like this result.data.Q001001 ... result.data.Q001099.
thank you for your help

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
Because of the complex nature of the matrix and dynamic panel questions it's necessary to iterate through it's inner structure.

You can check whether the question's value is an array(`Array.isArray(...)`) or an object (https://stackoverflow.com/questions/8511281/check-if-a-value-is-an-object-in-javascript) and iterate through it content.

**Comment by arifsudibyo** [comment]
alert(Array.isArray(result.data)) generate false. so, how do i can iterate from result.data.Q001001 to result.data.Q001099 and retrieve their content?

**Comment by tsv2013** [comment]
The `result.data` is an object. You can use the `$.each` in any case:
```JS
$.each(result.data, function (i, item) {
       alert(i + ' : ' + item)                        
});
```
And so on recursively for arrays and objects

**Comment by arifsudibyo** [comment]
thanks, it is work now
`$.each(result.data, function (i, item) {                                                
                        if (i.substring(0,4)=='Q001') {
                            for (var key in item) {
                                var jwb = {};
                                jwb.idEmployee = key;
                                jwb.question = i;
                                jwb.Likertscale = item[key];

                                $.ajax({
                                    url: 'MyService.asmx/AddAnswer',
                                    method: 'post',
                                    contentType:'application/json;charset=utf-8',
                                    data: '{jawaban:' + JSON.stringify(jwb) + '}',                                        
                                    success: function () {                                        
                                        alert('success');
                                    },
                                    error: function (err) {
                                        alert(err);
                                    }
                                });
                            }

                            //
                        }                                                
                    });`
