### ISSUE TITLE
Checkbox 'hasnone' no longer works after 1.0.66

### ISSUE THREAD

**Issue by CarolinaLi** [surveyjs/surveyjs#1609]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
When I click on 'none' in a checkbox question, it doesn't clear any of my previously checked answers. Similarly, if I have 'none' checked, and click on any other option, 'none' isn't cleared. This was working up until version 1.0.66, but breaks in 1.0.67

### What is the expected behavior?
Clicking on 'none' should clear any other checked option. Clicking on another option should clear the 'none' checkbox.

### How would you reproduce the current behavior (if this is a bug)?
On a checkbox question, select any of the options. Then click on 'none' and see that the previous options aren't cleared.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: 
https://surveyjs.io/Examples/Library/?id=questiontype-checkbox&platform=Reactjs&theme=default

### Specify your

* browser: Chrome
* browser version: Latest
* surveyjs platform: React
* surveyjs version: 1.0.73

**Comment by andrewtelnov** [comment]
@CarolinaLi We will work on the fix.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@CarolinaLi I have fixed it. We will add a function test for this functionality.

Thank you,
Andrew

**Comment by tsv2013** [comment]
Functional test has been added via the https://github.com/surveyjs/surveyjs/commit/4b0448fc6944aa2463e1f3e173b4d1a1d4191c7e commit

**Comment by CarolinaLi** [comment]
@andrewtelnov @tsv2013 Thank you!
