### ISSUE TITLE
Custom CSS Class Weird Behavior with Multiple Survey Instances

### ISSUE THREAD

**Issue by jezaman** [surveyjs/surveyjs#1610]
### Are you requesting a feature, reporting a bug or asking a question?

question

### Question

Is Custom CSS somehow "shared" between different survey instances? I'm experiencing unexpected behavior. 

Basically: 
I initialize two variables survey1 and survey2 using two calls of  new Survey.Model(value);
survey1 does not overwrite the navigation: { complete: "" } css, while survey2 overwrites the css class to hide the button using bootstrap's d-none class. 

survey1 is rendered and everything is fine and button is showing. survey2 is rendered and everything is fine, with the send button not showing as intended. 

If i then click on the submit button of survey1, which i implemented to just use .clear() and .render(), the submit button disappears. Inspecting the html reveals that survey1's button also used the d-none class, which was only applied to survey2.

How is this happening? How do i prevent it? 

How can survey2.css = {...} possibly affect what was specified using survey1.css = {..}
 
Below is a demo:

First i submit the survey1 2x to demonstrate it works fine and resets the form as intended. When survey2 is added, it affects survey1's css?

![Survey](https://user-images.githubusercontent.com/7126922/55001687-73be7200-4fd5-11e9-965d-c2314d0920fd.gif)

**Comment by tsv2013** [comment]
If you are using the approach from this sample - https://surveyjs.io/Examples/Library/?id=survey-customcss&platform=Reactjs&theme=default
then I admit this CSS is shared for all surveys.

You can try different approach demonstrated in another sample - https://surveyjs.io/Examples/Library/?id=survey-cssclasses&platform=Reactjs&theme=default

Hope it fit your needs

**Comment by jezaman** [comment]
Thanks for your reply.
Your second approach seems to only allow me to chance css classes of questions, not the entire survey as a whole (container, etc.) 

Any plans for making the CSS not shared between all surveys? Or is this the intended behavior? 
I'm probably one of the only ones who actually needs this.

**Comment by andrewtelnov** [comment]
@jezaman We have [survey.onUpdateQuestionCssClasses](https://surveyjs.io/Documentation/Library/?id=surveymodel#onUpdateQuestionCssClasses) that you may use for your task.

**Comment by jezaman** [comment]
@andrewtelnov That is correct, but it does not do exactly the same thing. 
You can only customize each question with that. 

i.e.

comment: "form-control"
description: "small"
error: {root: "alert alert-danger", icon: "glyphicon glyphicon-exclamation-sign", item: "", locationTop: "sv_qstn_error_top", locationBottom: "sv_qstn_error_bottom"}
flowRoot: "sv_q_flow sv_qstn"
hasError: "has-error"
indent: 20
mainRoot: "sv_qstn px-0"
number: "sv_q_num"
required: ""
root: "form-control"
title: ""
titleLeftRoot: "sv_qstn_left"
titleRequired: "

I want to be able to customize the entire survey css.  i.e.

{
	"root": "sv_main sv_bootstrap_css",
	"header": "panel-heading card-header",
	"body": "panel-body card-block mt-4",
	"footer": "panel-footer card-footer",
	"navigationButton": "button btn-lg",
	"completedPage": "",
	"navigation": {
		"complete": "btn sv_complete_btn",
		"prev": "btn sv_prev_btn",
		"next": "btn sv_next_btn",
		"start": "btn sv_start_btn"
	},
	"progress": "progress center-block mx-auto mb-4",
	"progressBar": "progress-bar",
	"page": {
		"root": "",
		"title": "",
		"description": ""
	},
	"pageTitle": "",
	"pageDescription": "small",
	"row": "sv_row",
	"question": {
		"mainRoot": "sv_qstn",
		"flowRoot": "sv_q_flow sv_qstn",
		"titleLeftRoot": "sv_qstn_left",
		"title": "",
		"number": "sv_q_num",
		"description": "small",
		"comment": "form-control",
		"required": "",
		"titleRequired": "",
		"hasError": "has-error",
		"indent": 20
	},
	"panel": {
		"title": "sv_p_title",
		"description": "small sv_p_description",
		"container": "sv_p_container"
	},
	"error": {
		"root": "alert alert-danger",
		"icon": "glyphicon glyphicon-exclamation-sign",
		"item": "",
		"locationTop": "sv_qstn_error_top",
		"locationBottom": "sv_qstn_error_bottom"
	},
	"boolean": {
		"root": "sv_qbln form-inline checkbox",
		"item": "",
		"label": "",
		"materialDecorator": "checkbox-material"
	},
	"checkbox": {
		"root": "sv_qcbc sv_qcbx form-inline",
		"item": "checkbox",
		"itemControl": "",
		"controlLabel": "",
		"materialDecorator": "checkbox-material",
		"other": "sv_q_checkbox_other form-control"
	},
	"comment": "form-control",
	"dropdown": {
		"root": "",
		"control": "form-control",
		"other": "sv_q_dd_other form-control"
	},
	"matrix": {
		"root": "table table-striped",
		"label": "sv_q_m_label",
		"cellText": "sv_q_m_cell_text",
		"cellTextSelected": "sv_q_m_cell_selected bg-primary",
		"cellLabel": "sv_q_m_cell_label"
	},
	"matrixdropdown": {
		"root": "table"
	},
	"matrixdynamic": {
		"root": "table",
		"button": "button",
		"buttonAdd": "",
		"buttonRemove": "",
		"iconAdd": "",
		"iconRemove": ""
	},
	"paneldynamic": {
		"root": "",
		"button": "button",
		"buttonPrev": "",
		"buttonNext": "",
		"buttonAdd": "",
		"buttonRemove": ""
	},
	"multipletext": {
		"root": "table",
		"itemTitle": "",
		"itemValue": "sv_q_mt_item_value form-control"
	},
	"radiogroup": {
		"root": "sv_qcbc form-inline",
		"item": "radio",
		"label": "",
		"itemControl": "",
		"controlLabel": "",
		"materialDecorator": "circle",
		"other": "sv_q_radiogroup_other form-control",
		"clearButton": "sv_q_radiogroup_clear button"
	},
	"imagepicker": {
		"root": "sv_imgsel",
		"item": "sv_q_imgsel",
		"label": "sv_q_imgsel_label",
		"itemControl": "sv_q_imgsel_control_item",
		"image": "sv_q_imgsel_image",
		"itemText": "sv_q_imgsel_text",
		"clearButton": "sv_q_radiogroup_clear"
	},
	"rating": {
		"root": "btn-group",
		"item": "btn btn-default btn-secondary",
		"selected": "active",
		"minText": "sv_q_rating_min_text",
		"itemText": "sv_q_rating_item_text",
		"maxText": "sv_q_rating_max_text"
	},
	"text": "form-control",
	"expression": "form-control",
	"file": {
		"root": "sv_q_file",
		"placeholderInput": "sv_q_file_placeholder",
		"preview": "sv_q_file_preview",
		"removeButton": "sv_q_file_remove_button",
		"fileInput": "sv_q_file_input",
		"removeFile": "sv_q_file_remove"
	},
	"saveData": {
		"root": "",
		"saving": "alert alert-info",
		"error": "alert alert-danger",
		"success": "alert alert-success",
		"saveAgainButton": ""
	},
	"window": {
		"root": "modal-content",
		"body": "modal-body",
		"header": {
			"root": "modal-header panel-title",
			"title": "pull-left",
			"button": "glyphicon pull-right",
			"buttonExpanded": "glyphicon pull-right glyphicon-chevron-up",
			"buttonCollapsed": "glyphicon pull-right glyphicon-chevron-down"
		}
	}
}

**Comment by andrewtelnov** [comment]
@jezaman I see. Unfortunately, we do not have solution for your scenario at the current moment.
We did not expect that somebody decides to have different css classes for different surveys on the same page. 

Thank you,
Andrew
