### ISSUE TITLE
startTimer() from survey.currentPageNo == 1 not rendering timer text

### ISSUE THREAD

**Issue by massimomazzariol** [surveyjs/surveyjs#1616]
### Are you requesting a feature, reporting a bug or asking a question?

Asking question regarding startTimer() function rendering

### What is the current behavior?

I would like to startTimer and render the text from this snippet of code:

survey.onCurrentPageChanged.add((sender, options) => {
        const currentPage = sender.currentPageNo;
        console.log("Current page: " + currentPage);
        if (currentPage == 1) {
            survey.showTimerPanel = 'top';
            survey.showTimerPanelMode = 'page';
            survey.showProgressBar = "bottom";
            survey.startTimer();
        }
    });

Actually the timer works perfectly but it doesn't show up on the page

### What is the expected behavior?

Render the text with the timer on the page

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
survey.onCurrentPageChanged.add((sender, options) => {
        const currentPage = sender.currentPageNo;
        console.log("Current page: " + currentPage);
        if (currentPage == 1) {
            survey.showTimerPanel = 'top';
            survey.showTimerPanelMode = 'page';
            survey.showProgressBar = "bottom";
            survey.startTimer();
        }
    });

```

### Specify your

* browser: Chrome
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.71

**Comment by andrewtelnov** [comment]
@massimomazzariol Please add survey.render(); call after survey.startTimer();

Here is [the example](https://plnkr.co/edit/KqJ6iP6EClJh4m7uzx0P?p=preview).

Thank you,
Andrew

**Comment by massimomazzariol** [comment]
Thank you! It works perfectly!

**Comment by frankwo1** [comment]
Hi Andrew, How do I save the value of the timer in the dataset?
Thanks
Frank

**Comment by andrewtelnov** [comment]
@frankwo1 Please use [survey.timeSpent](https://surveyjs.io/Documentation/Library?id=surveymodel#timeSpent) read-only property.

Thank you,
Andrew
