### ISSUE TITLE
onTimerPanelInfoText use html instead of simple text

### ISSUE THREAD

**Issue by massimomazzariol** [surveyjs/surveyjs#1620]
### Are you requesting a feature, reporting a bug or asking a question?

Requesting a feature

### What is the current behavior?

Actually when you override default text of onTimerPanelInfoText you can only write a simple text without html tags

### What is the expected behavior?

I would like to assign html text in order to change color and font type of the text, if possible

### How would you reproduce the current behavior (if this is a bug)?

Check the code below

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
survey.onTimerPanelInfoText.add((sender, options) => {
        if (sender.currentPage.isReadOnly) {
          options.text = '';
        } else {
          options.text = 'YOU HAVE <span style="color: #red;">15</span> SECONDS!<br />TIME SPENT: <span style="color: #red;">' + survey.currentPage.timeSpent + ' SECONDS, HURRY UP!</span>';
        }
    });

```

### Specify your

* browser: chrome
* browser version: lastest
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.71

**Comment by andrewtelnov** [comment]
@massimomazzariol We may add markdown support for this string. Will it work for you?
Here is [the example](https://surveyjs.io/Examples/Library/?id=survey-markdown-radiogroup).

Thank you,
Andrew

**Comment by massimomazzariol** [comment]
Hi Andrew, thanks for the answer!
I've tried to look deeper into markdown and how to convert it in a way I can use colors or some specific HTML tags like suggested here: https://stackoverflow.com/questions/35465557/how-to-apply-color-in-markdown.

I included the code from your example:

```
//Create showdown mardown converter
var converter = new showdown.Converter();
survey
    .onTextMarkdown
    .add(function (survey, options) {
        //convert the mardown text to html
        var str = converter.makeHtml(options.text);
        //remove root paragraphs <p></p>
        str = str.substring(3);
        str = str.substring(0, str.length - 4);
        //set html
        options.html = str;
    });

```
But I couldn't get it to work - I think I'm missing something?
(Showdown library js is loaded - it doesn't report any report any errors on the code)

Thanks

**Comment by andrewtelnov** [comment]
@massimomazzariol timerInfoText did not support markdown. I have added this functionalty by the commit that you have to see above.
It will be available in the next minor version that we will release on the next week,

Thank you,
Andrew

**Comment by massimomazzariol** [comment]
Dear @andrewtelnov,
I've just tried the new commit and now it converts the markdown placed inside onTimerPanelInfoText into HTML but the HTML is not yet rendered by the library but it shows plain text - am I missing something?

Thank you!
