### ISSUE TITLE
radiogroup defaultValue doesn't work since 1.0.7

### ISSUE THREAD

**Issue by MugiwaraNoMehdi** [surveyjs/surveyjs#1621]
### Are you requesting a feature, reporting a bug or asking a question?
reporting a bug

### What is the current behavior?
defaultValue not rendering for radiogroup if it is set to 0

### How would you reproduce the current behavior (if this is a bug)?

here is an example in plunker : 
https://next.plnkr.co/edit/i4Qk6NBt5JcG5DKq?preview

if you take the versions from 1.0.77 to 1.0.71 it doesn't work
<script src="https://surveyjs.azureedge.net/1.0.77/survey.jquery.js"></script>
if you switch to 1.0.7 or 1.0.69 it works.

tested with angular and jquery

**Comment by andrewtelnov** [comment]
@MugiwaraNoMehdi We have migrated from pReact to knockout for jQuery library.
Knockout has two-way binding. Since radio value can be string only, knockout doesn't recognize that 0 is "0" and doesn't select it.
The easy fix for you is to set both defaultValue and value to string,  to "0", for example.

We will investigate the issue further, but I am not sure, will we be able to fix it or not.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@MugiwaraNoMehdi In fact, knockout has an [additional parameter checkedValue](https://knockoutjs.com/documentation/checked-binding.html) to support this scenario.
We are using it now in our checkbox and radiogroup question templates.

The fix will be available in the next minor version. We will release it on this week.

Thank you,
Andrew

**Comment by MugiwaraNoMehdi** [comment]
Thank you Andrew nice work

**Comment by MugiwaraNoMehdi** [comment]
Sorry Andrew, just updated to 1.0.79, still doesn't work, 
In 1.0.79, matrix values doesn't work too. I am using it already in our product, I have saved old data, the old data doesn't render when upgrading to 1.0.79, to make it work, I have to downgrade to 1.0.69

**Comment by andrewtelnov** [comment]
@MugiwaraNoMehdi It works fine to me. Here is [the example](https://next.plnkr.co/edit/vsnqNbW5kkpPeYej).

Thank you,
Andrew

**Comment by MugiwaraNoMehdi** [comment]
Yes so the issue still remains... 
if you take my example https://next.plnkr.co/edit/i4Qk6NBt5JcG5DKq?preview and you change from 1.0.69 (where it works) to 1.0.81, and if you change your example from 1.0.81 to 1.0.69 your example doesn't work, it doesn't work, because you have put defaultvalue : 0 and in my case it was defaultvalue: '0'... I must stay in 1.0.69 to make all my data works

**Comment by MugiwaraNoMehdi** [comment]
I have the same issue with matrix

**Comment by andrewtelnov** [comment]
@MugiwaraNoMehdi knockout believes that 0 and '0' are different values. We made that knockout do not convert 0 to '0' when it renders elements.
Why can't you just change the defaultValue from '0' to 0, while your item values are numbers?

Thank you,
Andrew
