### ISSUE TITLE
Updating the template choices for a panel dynamic question result in numerous callbacks

### ISSUE THREAD

**Issue by dogwith1eye** [surveyjs/surveyjs#1622]
For questions in a panel dynamic, updating a choice results in a single event being fired in the custom control. However new questions that are added with the new row button will not have this new value.

Updating the templateQuestion will fix this issue but it results in a large number of events firing that slows down the ui. Here is a plunk that shows the issue.

https://embed.plnkr.co/l2vLc5NK1kkpxPlYigoy/

**Comment by andrewtelnov** [comment]
@dogwith1eye Yes, I see the issue.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@dogwith1eye I have added a [unit test](https://github.com/surveyjs/surveyjs/blob/master/tests/question_matrixdynamictests.ts#L2012) and fixed it.
It should be fine in the next version, one notification about change should come.

Thank you,
Andrew
