### ISSUE TITLE
Can't prevent focus on first question with error

### ISSUE THREAD

**Issue by CarolinaLi** [surveyjs/surveyjs#1623]
### Are you requesting a feature, reporting a bug or asking a question?
Requesting a feature / reporting a bug

### What is the current behavior?
If the survey triggers error messages, the first question gets focused despite setting focusFirstQuestionAutomatic to false.

### What is the expected behavior?
Setting focusFirstQuestionAutomatic to false should prevent the first question from getting focused even after it triggers an error message.

### How would you reproduce the current behavior (if this is a bug)?
Set isRequired to true on the first question and focusFirstQuestionAutomatic to false. Click 'next' without answering to cause the error message to show up, and see that the first question is automatically focused. (Used Survey Builder)

### Specify your

* browser: Chrome
* browser version: Latest
* surveyjs platform: React
* surveyjs version: 1.0.77

**Comment by andrewtelnov** [comment]
@CarolinaLi focusFirstQuestionAutomatic is about focusing the first questioin on the page on showing a new page. We will need a new option to prevent focusing a question with an error.
Do you have any particular reason, why do you need this functionality?
I beleive the most users would love to see what is wrong immediately.

Thank you,
Andrew

**Comment by CarolinaLi** [comment]
Hi @andrewtelnov,

This is for WCAG compliance; when the user tabs to a question, the screen reader reads out the question and associated error message. But when the focus is on the first question automatically, the error message isn't read out. If the user presses tab, it'll jump to the 2nd question.

We tried to override the focus and set it to a heading above so the user could then tab to the first question, but the automatic focus seems to prevent this.

Thanks,
Carolina

**Comment by andrewtelnov** [comment]
@CarolinaLi Ok. I have added survey.focusOnFirstError property (default is true). You will have to set it to false. This property will be available in the next minor update that we will release on this week, most likely tomorrow.

Thank you,
Andrew

**Comment by CarolinaLi** [comment]
@andrewtelnov Thanks so much!
