### ISSUE TITLE
Panel Dynamic with Expression with isSinglePage = true

### ISSUE THREAD

**Issue by gitslacker** [surveyjs/surveyjs#1625]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug.

### What is the current behavior?
If an expression question exists within a panel dynamic question, all other questions in the panel are cleared (i.e. the answers are deleted) in single-page mode. In normal mode it works fine.

### What is the expected behavior?
Single-page mode should not delete answers in dynamic panels containing an expression.

### How would you reproduce the current behavior (if this is a bug)?
Create a survey with a dynamic panel, and a single-text field and an expression field within that dynamic panel. Enter information into the survey. Set isSinglePage = true.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://embed.plnkr.co/9H9PjSvDQY3Ik2IZxNE7/

### Specify your

* browser: Chrome
* browser version: 73.0.3683.86
* surveyjs platform (angular or react or jquery or knockout or vue): Knockout and jQuery
* surveyjs version: 1.0.77

**Comment by andrewtelnov** [comment]
@gitslacker I have added a new unit test based on your example and fix it.
The fix will be availabe in the next minor update on the next week.

Thank you,
Andrew
