### ISSUE TITLE
Is it possible to return a method when add an attachment on the File input?

### ISSUE THREAD

**Issue by paulocesarpcfj** [surveyjs/surveyjs#1627]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
When adding an Attachment, nothing happens on the callback, so I never know when something new was added.

### What is the expected behavior?
Maybe return a state to be possible to change something on the UI based on an attachment added.

### How would you reproduce the current behavior (if this is a bug)?
I have to use iframe on my project, and I have a method to resize the iframe (as you know about dynamic heights on iframes), but in the case of answer and testing a survey with some questions and 1 File input, after add a file/image, the iframe height is not updated because I dont have any difference on my props to dispatch the resize frame method. Is it possible to do this somehow?

### Specify your

* browser: Chrome
* browser version: LTS
* surveyjs platform: React (with iframe)
* surveyjs version: 1.0.77

**Comment by tsv2013** [comment]
Probably you can find [this thread](https://surveyjs.answerdesk.io/ticket/details/T1821) useful. Especially this example - https://plnkr.co/edit/Cw2rclm4aq3JLRKduM4r?p=preview

**Comment by paulocesarpcfj** [comment]
Awesome! I will try here and close the issue.

Thanks!
