### ISSUE TITLE
Embedding with Wordpress plugin or Embedding with HTML & JS code directly

### ISSUE THREAD

**Issue by SpikePiegal** [surveyjs/surveyjs#1628]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question?

### What is the current behavior?

Wondering whats the best way to embed surveyjs either the wordpress plugin or hard coded it

### What is the expected behavior?

I am currently trying to embed using the HTML and JS direct embed but having trouble and wonder how easy it is to use the Wordpress plug in 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
Have you seen SurveyJS Wordpress plugin? - https://wordpress.org/plugins/surveyjs/
