### ISSUE TITLE
npm install survey-angular is not working

### ISSUE THREAD

**Issue by Aventrue** [surveyjs/surveyjs#164]
The command npm install survey-angular is not working: 
Registry returned 404 for GET on https://registry.npmjs.org/survey-angular

How can I install the angular version?

Full output:
C:\Git\>npm install survey-angular
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "survey-angular"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/survey-angular
npm ERR! 404
npm ERR! 404  'survey-angular' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Git\ApolloMobile\ApolloMobile\npm-debug.log

**Comment by andrewtelnov** [comment]
@Aventrue We have updated the web pages, before we have published npm packages. It was our mistake. Sorry about that.
It should be fine now.

Thank you,
Andrew

**Comment by Aventrue** [comment]
Thank you for your help and your great work!

**Comment by Aventrue** [comment]
I'm sorry but somehow I don't bring it to work. I get a lot of error messages. Which says something with react, but I want to use the angular version. I followed your guid on your homepage. Here are several messages which I get:
[default] C:\Git\ApolloMobile\ApolloMobile\node_modules\survey-angular\dist\typings\react\reactSurvey.d.ts:9:37
    Type 'any' is not a constructor function type.
[default] C:\Git\ApolloMobile\ApolloMobile\node_modules\survey-angular\dist\typings\react\reactSurvey.d.ts:16:15
    Cannot find namespace 'JSX'.

error_handler.js:48 EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'children' of null
TypeError: Cannot read property 'children' of null
    at Object.o [as render] (http://localhost:3000/main.bundle.js:1719:4575)
    at Function.webpackJsonpac__name_../node_modules/survey-angular/js/survey.angular.min.js.t.SurveyNG.t.render (http://localhost:3000/main.bundle.js:1721:13086)
    at http://localhost:3000/main.bundle.js:4879:37
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.bundle.js:15310:26)
    at Object.onInvoke (http://localhost:3000/vendor.bundle.js:35731:37)
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.bundle.js:15309:32)
    at Zone.run (http://localhost:3000/polyfills.bundle.js:15192:43)
    at http://localhost:3000/polyfills.bundle.js:15580:57
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.bundle.js:15343:35)
    at Object.onInvokeTask (http://localhost:3000/vendor.bundle.js:35722:37)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.bundle.js:15342:40)
    at Zone.runTask (http://localhost:3000/polyfills.bundle.js:15232:47)
    at drainMicroTaskQueue (http://localhost:3000/polyfills.bundle.js:15479:35)
    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/polyfills.bundle.js:15417:25)

**Comment by dmitrykurmanov** [comment]
@Aventrue Hello, thank you for your report. I think the problem in our typings files, we should exclude typings files for react version. I'll try to fix it soon.

**Comment by dmitrykurmanov** [comment]
@Aventrue I can't reproduce this bug. Could your share your code please? May be in fiddle or github project. 

As a workaround you can try to add "jsx": "react" in tsconfig.json. But it would be much better if you could give me example. Thanks.

**Comment by Aventrue** [comment]
Can it be that this issue is connected with failing of npm install dependencies?

C:\Git\>npm install survey-angular
angular2-webpack-starter@5.1.1 C:\Git\ApolloMobile\ApolloMobile
+-- UNMET PEER DEPENDENCY rxjs@5.0.0-rc.1
+-- survey-angular@0.10.3
`-- UNMET PEER DEPENDENCY tslint@4.0.0-dev.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/core@2.1.1 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/http@2.1.1 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/router@3.1.1 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN angular2-jwt@0.1.26 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN codelyzer@1.0.0-beta.3 requires a peer of tslint@^3.9.0 but none was installed.
npm WARN tslint-loader@2.1.5 requires a peer of tslint@^3.0.0 but none was installed.

**Comment by dmitrykurmanov** [comment]
@Aventrue I don't think it is because of npm install.  I've created the repo https://github.com/dmitrykurmanov/survey-angular-example with my survey-angular example based on angular2 "QuickStart seed". And it works. Could you check it please?

**Comment by Aventrue** [comment]
@dmitrykurmanov Than you very much for your help. I checked out your sample, but somehow I still don't bring mine to work. Im very sorry, but I'm not allowed to shared the project. I still get a lot of this messages: 
[at-loader] node_modules\survey-angular\dist\typings\react\reactSurvey.d.ts:9:37
    Type 'any' is not a constructor function type.
I added  "jsx": "react" in tsconfig.json without success.
Would it be possible to make a short teamviewer session to look for these problem? That would be so great :)
Best regards
Thomas

**Comment by Aventrue** [comment]
@dmitrykurmanov I tried it now with your example, but I also didn't brought this to run. I have done following steps:
1. Git clone https://github.com/dmitrykurmanov/survey-angular-example.git
2. npm install
3. npm start where I got this errors

c:\Git\survey-angular-example>npm start

> angular-quickstart@1.0.0 start c:\Git\survey-angular-example
> tsc && concurrently "tsc -w" "lite-server"

node_modules/@types/node/index.d.ts(70,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'main' must be of type 'any', but here has type 'NodeModule'.
node_modules/@types/node/index.d.ts(81,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'parent' must be of type 'any', but here has type 'NodeModule'.
node_modules/@types/node/index.d.ts(82,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'children' must be of type 'any[]', but here has type 'NodeModule[]'.
node_modules/@types/node/index.d.ts(102,6): error TS2300: Duplicate identifier 'BufferEncoding'.
node_modules/@types/node/index.d.ts(256,9): error TS2403: Subsequent variable declarations must have the same type.  Variable 'errno' must be of type 'string', but here has type 'number'.
node_modules/@types/node/index.d.ts(263,18): error TS2300: Duplicate identifier 'EventEmitter'.
node_modules/@types/node/index.d.ts(559,26): error TS2300: Duplicate identifier 'Buffer'.
node_modules/@types/node/index.d.ts(559,50): error TS2300: Duplicate identifier 'SlowBuffer'.
node_modules/@types/node/index.d.ts(603,5): error TS2309: An export assignment cannot be used in a module with other exported elements.
node_modules/@types/node/index.d.ts(748,18): error TS2300: Duplicate identifier 'Agent'.
node_modules/@types/node/index.d.ts(806,18): error TS2300: Duplicate identifier 'Worker'.
node_modules/@types/node/index.d.ts(1487,17): error TS2300: Duplicate identifier 'CompleterResult'.
node_modules/@types/node/index.d.ts(1524,18): error TS2300: Duplicate identifier 'Script'.
node_modules/@types/node/index.d.ts(2476,22): error TS2451: Cannot redeclare block-scoped variable 'F_OK'.
node_modules/@types/node/index.d.ts(2479,22): error TS2451: Cannot redeclare block-scoped variable 'R_OK'.
node_modules/@types/node/index.d.ts(2482,22): error TS2451: Cannot redeclare block-scoped variable 'W_OK'.
node_modules/@types/node/index.d.ts(2485,22): error TS2451: Cannot redeclare block-scoped variable 'X_OK'.
node_modules/@types/node/index.d.ts(2490,22): error TS2451: Cannot redeclare block-scoped variable 'O_RDONLY'.
node_modules/@types/node/index.d.ts(2493,22): error TS2451: Cannot redeclare block-scoped variable 'O_WRONLY'.
node_modules/@types/node/index.d.ts(2496,22): error TS2451: Cannot redeclare block-scoped variable 'O_RDWR'.
node_modules/@types/node/index.d.ts(2499,22): error TS2451: Cannot redeclare block-scoped variable 'O_CREAT'.
node_modules/@types/node/index.d.ts(2502,22): error TS2451: Cannot redeclare block-scoped variable 'O_EXCL'.
node_modules/@types/node/index.d.ts(2505,22): error TS2451: Cannot redeclare block-scoped variable 'O_NOCTTY'.
node_modules/@types/node/index.d.ts(2508,22): error TS2451: Cannot redeclare block-scoped variable 'O_TRUNC'.
node_modules/@types/node/index.d.ts(2511,22): error TS2451: Cannot redeclare block-scoped variable 'O_APPEND'.
node_modules/@types/node/index.d.ts(2514,22): error TS2451: Cannot redeclare block-scoped variable 'O_DIRECTORY'.
node_modules/@types/node/index.d.ts(2517,22): error TS2451: Cannot redeclare block-scoped variable 'O_NOATIME'.
node_modules/@types/node/index.d.ts(2520,22): error TS2451: Cannot redeclare block-scoped variable 'O_NOFOLLOW'.
node_modules/@types/node/index.d.ts(2523,22): error TS2451: Cannot redeclare block-scoped variable 'O_SYNC'.
node_modules/@types/node/index.d.ts(2526,22): error TS2451: Cannot redeclare block-scoped variable 'O_SYMLINK'.
node_modules/@types/node/index.d.ts(2529,22): error TS2451: Cannot redeclare block-scoped variable 'O_DIRECT'.
node_modules/@types/node/index.d.ts(2532,22): error TS2451: Cannot redeclare block-scoped variable 'O_NONBLOCK'.
node_modules/@types/node/index.d.ts(2537,22): error TS2451: Cannot redeclare block-scoped variable 'S_IFMT'.
node_modules/@types/node/index.d.ts(2540,22): error TS2451: Cannot redeclare block-scoped variable 'S_IFREG'.
node_modules/@types/node/index.d.ts(2543,22): error TS2451: Cannot redeclare block-scoped variable 'S_IFDIR'.
node_modules/@types/node/index.d.ts(2546,22): error TS2451: Cannot redeclare block-scoped variable 'S_IFCHR'.
node_modules/@types/node/index.d.ts(2549,22): error TS2451: Cannot redeclare block-scoped variable 'S_IFBLK'.
node_modules/@types/node/index.d.ts(2552,22): error TS2451: Cannot redeclare block-scoped variable 'S_IFIFO'.
node_modules/@types/node/index.d.ts(2555,22): error TS2451: Cannot redeclare block-scoped variable 'S_IFLNK'.
node_modules/@types/node/index.d.ts(2558,22): error TS2451: Cannot redeclare block-scoped variable 'S_IFSOCK'.
node_modules/@types/node/index.d.ts(2563,22): error TS2451: Cannot redeclare block-scoped variable 'S_IRWXU'.
node_modules/@types/node/index.d.ts(2566,22): error TS2451: Cannot redeclare block-scoped variable 'S_IRUSR'.
node_modules/@types/node/index.d.ts(2569,22): error TS2451: Cannot redeclare block-scoped variable 'S_IWUSR'.
node_modules/@types/node/index.d.ts(2572,22): error TS2451: Cannot redeclare block-scoped variable 'S_IXUSR'.
node_modules/@types/node/index.d.ts(2575,22): error TS2451: Cannot redeclare block-scoped variable 'S_IRWXG'.
node_modules/@types/node/index.d.ts(2578,22): error TS2451: Cannot redeclare block-scoped variable 'S_IRGRP'.
node_modules/@types/node/index.d.ts(2581,22): error TS2451: Cannot redeclare block-scoped variable 'S_IWGRP'.
node_modules/@types/node/index.d.ts(2584,22): error TS2451: Cannot redeclare block-scoped variable 'S_IXGRP'.
node_modules/@types/node/index.d.ts(2587,22): error TS2451: Cannot redeclare block-scoped variable 'S_IRWXO'.
node_modules/@types/node/index.d.ts(2590,22): error TS2451: Cannot redeclare block-scoped variable 'S_IROTH'.
node_modules/@types/node/index.d.ts(2593,22): error TS2451: Cannot redeclare block-scoped variable 'S_IWOTH'.
node_modules/@types/node/index.d.ts(2596,22): error TS2451: Cannot redeclare block-scoped variable 'S_IXOTH'.
node_modules/@types/node/index.d.ts(2827,18): error TS2300: Duplicate identifier 'TLSSocket'.
node_modules/@types/node/index.d.ts(3201,10): error TS2300: Duplicate identifier 'Utf8AsciiLatin1Encoding'.
node_modules/@types/node/index.d.ts(3202,10): error TS2300: Duplicate identifier 'HexBase64Latin1Encoding'.
node_modules/@types/node/index.d.ts(3203,10): error TS2300: Duplicate identifier 'Utf8AsciiBinaryEncoding'.
node_modules/@types/node/index.d.ts(3204,10): error TS2300: Duplicate identifier 'HexBase64BinaryEncoding'.
node_modules/@types/node/index.d.ts(3205,10): error TS2300: Duplicate identifier 'ECDHKeyFormat'.
node_modules/@types/node/index.d.ts(3556,5): error TS2300: Duplicate identifier 'export='.
node_modules/@types/node/index.d.ts(3639,5): error TS2300: Duplicate identifier 'export='.
node_modules/@types/node/index.d.ts(3661,18): error TS2300: Duplicate identifier 'Domain'.
node_modules/@types/node/index.d.ts(3953,5): error TS2300: Duplicate identifier 'export='.
node_modules/@types/node/index.d.ts(3997,5): error TS2300: Duplicate identifier 'export='.
node_modules/protractor/built/browser.d.ts(258,37): error TS2503: Cannot find namespace 'webdriver'.
node_modules/protractor/built/browser.d.ts(265,55): error TS2503: Cannot find namespace 'webdriver'.
node_modules/protractor/built/browser.d.ts(265,78): error TS2503: Cannot find namespace 'webdriver'.
node_modules/protractor/built/browser.d.ts(357,31): error TS2503: Cannot find namespace 'webdriver'.
node_modules/protractor/built/browser.d.ts(368,26): error TS2503: Cannot find namespace 'webdriver'.
node_modules/protractor/built/browser.d.ts(452,36): error TS2503: Cannot find namespace 'webdriver'.
node_modules/protractor/built/ptor.d.ts(13,29): error TS2503: Cannot find namespace 'webdriver'.
typings/globals/node/index.d.ts(78,6): error TS2300: Duplicate identifier 'BufferEncoding'.
typings/globals/node/index.d.ts(234,18): error TS2300: Duplicate identifier 'EventEmitter'.
typings/globals/node/index.d.ts(519,9): error TS2502: 'BuffType' is referenced directly or indirectly in its own type annotation.
typings/globals/node/index.d.ts(520,9): error TS2502: 'SlowBuffType' is referenced directly or indirectly in its own type annotation.
typings/globals/node/index.d.ts(521,26): error TS2300: Duplicate identifier 'Buffer'.
typings/globals/node/index.d.ts(521,50): error TS2300: Duplicate identifier 'SlowBuffer'.
typings/globals/node/index.d.ts(705,18): error TS2300: Duplicate identifier 'Agent'.
typings/globals/node/index.d.ts(763,18): error TS2300: Duplicate identifier 'Worker'.
typings/globals/node/index.d.ts(1349,22): error TS2300: Duplicate identifier 'CompleterResult'.
typings/globals/node/index.d.ts(1389,18): error TS2300: Duplicate identifier 'Script'.
typings/globals/node/index.d.ts(2286,22): error TS2451: Cannot redeclare block-scoped variable 'F_OK'.
typings/globals/node/index.d.ts(2289,22): error TS2451: Cannot redeclare block-scoped variable 'R_OK'.
typings/globals/node/index.d.ts(2292,22): error TS2451: Cannot redeclare block-scoped variable 'W_OK'.
typings/globals/node/index.d.ts(2295,22): error TS2451: Cannot redeclare block-scoped variable 'X_OK'.
typings/globals/node/index.d.ts(2300,22): error TS2451: Cannot redeclare block-scoped variable 'O_RDONLY'.
typings/globals/node/index.d.ts(2303,22): error TS2451: Cannot redeclare block-scoped variable 'O_WRONLY'.
typings/globals/node/index.d.ts(2306,22): error TS2451: Cannot redeclare block-scoped variable 'O_RDWR'.
typings/globals/node/index.d.ts(2309,22): error TS2451: Cannot redeclare block-scoped variable 'O_CREAT'.
typings/globals/node/index.d.ts(2312,22): error TS2451: Cannot redeclare block-scoped variable 'O_EXCL'.
typings/globals/node/index.d.ts(2315,22): error TS2451: Cannot redeclare block-scoped variable 'O_NOCTTY'.
typings/globals/node/index.d.ts(2318,22): error TS2451: Cannot redeclare block-scoped variable 'O_TRUNC'.
typings/globals/node/index.d.ts(2321,22): error TS2451: Cannot redeclare block-scoped variable 'O_APPEND'.
typings/globals/node/index.d.ts(2324,22): error TS2451: Cannot redeclare block-scoped variable 'O_DIRECTORY'.
typings/globals/node/index.d.ts(2327,22): error TS2451: Cannot redeclare block-scoped variable 'O_NOATIME'.
typings/globals/node/index.d.ts(2330,22): error TS2451: Cannot redeclare block-scoped variable 'O_NOFOLLOW'.
typings/globals/node/index.d.ts(2333,22): error TS2451: Cannot redeclare block-scoped variable 'O_SYNC'.
typings/globals/node/index.d.ts(2336,22): error TS2451: Cannot redeclare block-scoped variable 'O_SYMLINK'.
typings/globals/node/index.d.ts(2339,22): error TS2451: Cannot redeclare block-scoped variable 'O_DIRECT'.
typings/globals/node/index.d.ts(2342,22): error TS2451: Cannot redeclare block-scoped variable 'O_NONBLOCK'.
typings/globals/node/index.d.ts(2347,22): error TS2451: Cannot redeclare block-scoped variable 'S_IFMT'.
typings/globals/node/index.d.ts(2350,22): error TS2451: Cannot redeclare block-scoped variable 'S_IFREG'.
typings/globals/node/index.d.ts(2353,22): error TS2451: Cannot redeclare block-scoped variable 'S_IFDIR'.
typings/globals/node/index.d.ts(2356,22): error TS2451: Cannot redeclare block-scoped variable 'S_IFCHR'.
typings/globals/node/index.d.ts(2359,22): error TS2451: Cannot redeclare block-scoped variable 'S_IFBLK'.
typings/globals/node/index.d.ts(2362,22): error TS2451: Cannot redeclare block-scoped variable 'S_IFIFO'.
typings/globals/node/index.d.ts(2365,22): error TS2451: Cannot redeclare block-scoped variable 'S_IFLNK'.
typings/globals/node/index.d.ts(2368,22): error TS2451: Cannot redeclare block-scoped variable 'S_IFSOCK'.
typings/globals/node/index.d.ts(2373,22): error TS2451: Cannot redeclare block-scoped variable 'S_IRWXU'.
typings/globals/node/index.d.ts(2376,22): error TS2451: Cannot redeclare block-scoped variable 'S_IRUSR'.
typings/globals/node/index.d.ts(2379,22): error TS2451: Cannot redeclare block-scoped variable 'S_IWUSR'.
typings/globals/node/index.d.ts(2382,22): error TS2451: Cannot redeclare block-scoped variable 'S_IXUSR'.
typings/globals/node/index.d.ts(2385,22): error TS2451: Cannot redeclare block-scoped variable 'S_IRWXG'.
typings/globals/node/index.d.ts(2388,22): error TS2451: Cannot redeclare block-scoped variable 'S_IRGRP'.
typings/globals/node/index.d.ts(2391,22): error TS2451: Cannot redeclare block-scoped variable 'S_IWGRP'.
typings/globals/node/index.d.ts(2394,22): error TS2451: Cannot redeclare block-scoped variable 'S_IXGRP'.
typings/globals/node/index.d.ts(2397,22): error TS2451: Cannot redeclare block-scoped variable 'S_IRWXO'.
typings/globals/node/index.d.ts(2400,22): error TS2451: Cannot redeclare block-scoped variable 'S_IROTH'.
typings/globals/node/index.d.ts(2403,22): error TS2451: Cannot redeclare block-scoped variable 'S_IWOTH'.
typings/globals/node/index.d.ts(2406,22): error TS2451: Cannot redeclare block-scoped variable 'S_IXOTH'.
typings/globals/node/index.d.ts(2637,18): error TS2300: Duplicate identifier 'TLSSocket'.
typings/globals/node/index.d.ts(3011,10): error TS2300: Duplicate identifier 'Utf8AsciiLatin1Encoding'.
typings/globals/node/index.d.ts(3012,10): error TS2300: Duplicate identifier 'HexBase64Latin1Encoding'.
typings/globals/node/index.d.ts(3013,10): error TS2300: Duplicate identifier 'Utf8AsciiBinaryEncoding'.
typings/globals/node/index.d.ts(3014,10): error TS2300: Duplicate identifier 'HexBase64BinaryEncoding'.
typings/globals/node/index.d.ts(3015,10): error TS2300: Duplicate identifier 'ECDHKeyFormat'.
typings/globals/node/index.d.ts(3366,5): error TS2300: Duplicate identifier 'export='.
typings/globals/node/index.d.ts(3449,5): error TS2300: Duplicate identifier 'export='.
typings/globals/node/index.d.ts(3471,18): error TS2300: Duplicate identifier 'Domain'.
typings/globals/node/index.d.ts(3763,5): error TS2300: Duplicate identifier 'export='.
typings/globals/node/index.d.ts(3789,5): error TS2300: Duplicate identifier 'export='.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "tsc -w" "lite-server"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Git\survey-angular-example\npm-debug.log

**Comment by Aventrue** [comment]
Can it be that it doesen't work because I use windows?

c:\Git\survey-angular-example>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: **Unsupported platform** for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (**current: {"os":"win32","arch":"x64"}**)
npm WARN angular-in-memory-web-api@0.1.17 requires a peer of rxjs@5.0.0-rc.4 but none was installed.
npm WARN angular-in-memory-web-api@0.1.17 requires a peer of zone.js@^0.7.2 but none was installed.

**Comment by dmitrykurmanov** [comment]
@Aventrue, Hello! I don't think it is because of windows. I am using windows too. I will try to clone my repo and reproduce the problem.

**Comment by dmitrykurmanov** [comment]
@Aventrue, I found the problems. It is typings. So, we will update our npm package. As a workaround you can install react typings into npm:

**Comment by dmitrykurmanov** [comment]
@Aventrue have you tried it?

**Comment by Aventrue** [comment]
Sorry for the late answer! Yes now it works perfect. Thanks a lot for your help.

**Comment by andrewtelnov** [comment]
@Aventrue @dmitrykurmanov Great!
