### ISSUE TITLE
Add externally built plugin example #enhancement

### ISSUE THREAD

**Issue by kbrown** [surveyjs/surveyjs#167]
I'd prefer to keep my domain specific question types in a separate package so I don't have to build and keep in sync surveyjs.

**Comment by kbrown** [comment]
I may provide an example if I decide to go this route.

**Comment by dmitrykurmanov** [comment]
@kbrown Hello! I will try to create examples for that task.

**Comment by dmitrykurmanov** [comment]
@kbrown I've added examples:

http://surveyjs.org/examples/knockout/custom-question.html
http://surveyjs.org/examples/react/custom-question.html

Could you check it, please?
