### ISSUE TITLE
why not add this library to cdn like jsdelivr?

### ISSUE THREAD

**Issue by cloudstoneme** [surveyjs/surveyjs#171]
Hi,

This is a great library, I just wonder that why not add this library to some CDN like jsdelivr?

**Comment by dmitrykurmanov** [comment]
@cloudstoneme, thanks we will think about it.  You could also try to use https://unpkg.com/#/, for example:

https://unpkg.com/survey-react@0.11.1

**Comment by andrewtelnov** [comment]
@cloudstoneme We are using azure cdn from today. You may use it as: https://surveyjs.azureedge.net/0.12.0/[filename]

Thank you,
Andrew
