### ISSUE TITLE
Review Answers

### ISSUE THREAD

**Issue by rgilchrist** [surveyjs/surveyjs#172]
Hi 
When the user complete's the survey, Is it possible on the 'Thank You' page to give them a review of the answers they have given and the ability to go back to the start to amend an answer?

Cheer R

**Comment by rgilchrist** [comment]
Hi
Sorry just realised it's possible using the syntax {question_name}. But I am struggling to output the values of a "multipletext" question. I have tried 
{question_name.sub_question}
{question_name['sub_question']}

Can somebody point me in the right direction?

Thanks

**Comment by andrewtelnov** [comment]
@rgilchrist I doesn't work right now, since the "multipletext" question stores as an json object itself. 
As a workaround, please use two (or more) separate "text" questions with the "startWithNewLine" property equals to false. So all these questions will be in one line. Here is a [demo](http://surveyjs.org/examples/jquery/survey-startwithnewline.html).

**Comment by rgilchrist** [comment]
Hi Andrew
Thanks for the answer and the workaround. Is there another question types that you can't access using the {} syntax?

Also is there a way to back thru the survey from the completedHtml?

Thanks
Rob

**Comment by andrewtelnov** [comment]
@rgilchrist you will have to create an html button and onclick event call. You may make it as a function:
```
function reRunSurvey(fromQuestionName) {
  //this will set survey to the first page.
  //survey.currentPageNo = 1; 
  //set the survey to the page where the question is located.
  survey.currentPage = survey.getPageByQuestion(survey.getQuestionByName(fromQuestionName));
  //There is a need to set this private flag to false. I will do something about it, for example make it false on change the currentPage
  survey["isCompleted"] = false;
  //re-run the survey.
  survey.render();
}

```

**Comment by andrewtelnov** [comment]
Start to work on: https://github.com/andrewtelnov/surveyjs/issues/177

**Comment by andrewtelnov** [comment]
@rgilchrist The new version that implements the require functionality has been released.
