### ISSUE TITLE
Set "goNextPageAutomatic" to "true" and strange behaviour with "Single Input"/"Matrix" fields

### ISSUE THREAD

**Issue by anzellai** [surveyjs/surveyjs#173]
Strange behaviour if "goNextPageAutomatic" is set to "true":

- if "Single Input" is the last (or only) question of the page, upon typing any character, next page automatically renders; just a thought, we should stop next page "triggers" if "input" field is "on focus" 

- for Matrix question, next page will not automatically render even rows are completed

**Comment by andrewtelnov** [comment]
@anzellai Yes, indeed, there is the bug with the input question for react (jQuery, angular) versions. I have fixed it.
About matrix question. At the current moment matrix questions do not support goNextPageAutomatic. The reason - it is not always obvious. For example, checkbox question will never support this feature, since there is no way to see, when a user is done setting the value of this question.
Could you explain your scenario with the matrix question. We may reconsider our decision about matrix.

Thank you,
Andrew

**Comment by anzellai** [comment]
@andrewtelnov thanks for your prompt response!

And your fix is similar to what I have done locally in my fork, except I actually check if the `document.activeElement` type is `text` or `textarea`, then bind once for the `onblur` event to re-run the `tryGoNextPageAutomatic`.
Anyway, I will pull and test again and feedback.

Re the matrix question, I think one use case to allow `goNextPageAutomatic` is for single matrix question -- given that no **checkbox** is involved and `isAllRowRequired` is set to true.

Think about a simple scenario if using single matrix with a bunch of pure radio group questions, if that makes sense?

I do understand the logic/validation checks could be complicated, but such flexibility will be greatly helpful to users building something truly amazing.

I'm not too familiar to typescript or else I can help create a PR, but the pseudo code would be something like:

- add `supportGoNextPageAutomatic()` returns **true** on `question_matrix`
- check if `isAllRowRequired` is **true**, or return
- check each row question has `goNextPageAutomatic` or return
- check each row and return if there is any validation error (custom error shouldn't push to **errors**)

That should cover the most simple use cases, what do you think?

**Comment by andrewtelnov** [comment]
@anzellai Yes, it should not be that hard to implement this functionality to matrix questions. Hopefully, I will have time to work on it this week.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
The fix for "multipletext" and "comment" questions by using onBlur event is added: https://github.com/andrewtelnov/surveyjs/issues/175

**Comment by andrewtelnov** [comment]
Matrix, MatrixDropdown and MultipleText questions support this functionality now.
Checkbox, File, Html, Comment and MatrixDynamic questions still do not support it.
Probably Comment question still make sense, while others are not.

Thank you,
Andrew

**Comment by anzellai** [comment]
@andrewtelnov  - I have rebuilt from the latest master, tested and confirmed that #175 has fixed the strange behaviour.

Thank you for your good job and fast response!
