### ISSUE TITLE
Test Survey

### ISSUE THREAD

**Issue by april2017** [surveyjs/surveyjs#174]
I am new to this and trying to create a survey. In the test survey mode , I am unable to enter anything for the single input fields. please help.

**Comment by andrewtelnov** [comment]
@april2017 Yes, there was a bug that I have introduced several days ago.
It is fixed now and the site is updated.

Thank you,
Andrew

**Comment by april2017** [comment]
Thanks!!
Also could you suggest some sites from where I can learn how to incorporate the code generated in your website to make a web survey. 
Sorry for the trouble but all this new to me as I am not a software professional.
Appreciate your help.
Regards,

Sent from Yahoo Mail on Android 
 
  On Wed, Jan 4, 2017 at 6:06 PM, Andrew<notifications@github.com> wrote:   
@april2017 Yes, there was a bug that I have introduced several days ago.
It is fixed now and the site is updated.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@april2017 the main page of http://surveyjs.org/ contains the step by step instruction.

Thank you,
Andrew

**Comment by april2017** [comment]
Hi,

I tried doing as per the instructions but somehow its not working. Appreciate if you could take a look and let me know what I am doing wrong. I saved the file as HTML and when I open in chrome, its blank.

[test.txt](https://github.com/andrewtelnov/surveyjs/files/688859/test.txt)

**Comment by andrewtelnov** [comment]
@april2017 The survey looks fine to me, as well as the page.
Do you have the survey.ko.min.js in your "js" directory and survey.css in your "css" directory. Please make sure that the paths are correct.

Thank you,
Andrew

**Comment by april2017** [comment]
Hi,

All the folders are kept on the desktop itself.  Are you able to view the survey when you open its as a  web page?

thanks

**Comment by andrewtelnov** [comment]
@april2017 yes, another problem, your javascript performed before the div is rendered. As result it is not "surverContainter" is not in DOM when the rendering is performed.
Here is the correct html: http://surveyjs.org/issues/174.html

**Comment by april2017** [comment]
Thank you so much !!
Appreciate all the help and guidance

Regards

**Comment by Jlmcconchie** [comment]
I would have loved to see the solution where you wrote:  Here is the correct html: http://surveyjs.org/issues/174.html.  However, the url is no longer active.  Can you reactivate it or put the solution at the end of some other hyperlink?

**Comment by dmitrykurmanov** [comment]
@Jlmcconchie, hello! We don't have this section of the site now. So The problem was in incorrect scripts order. I've created an example in the plnkr with surveyJSON above and it is works fine. Please check:  https://plnkr.co/edit/XmttEV6NhkNRvzFVavsl?p=preview
