### ISSUE TITLE
Add support for arrays and nested values in condition text (visibleIf property) and text pre-processing (for example completeHtml)

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#177]
Multiple text and matrix values can't be used in visibleIf and text pre-processing at the current moment, since their values contains nested properties and arrays.
For example "{bestPrice.minPrice} >= 10" will do nothing right now.
However, it should work.

**Comment by andrewtelnov** [comment]
Implemented.

**Comment by nelero** [comment]
is this available in the latest version on surveyjs.org ?
i'd like to have a visibleIf condition based on a matrix value

**Comment by andrewtelnov** [comment]
@nelero I have just updated the zip on surveyjs.org, but do not update the npm packages yet.

Thank you,
Andrew

**Comment by GuiAfonso** [comment]
@andrewtelnov I have an array of number result of a checkbox, can I check if one number is in array using a visibleif condition?
`{"variable":["1","2","3"]}`
`{variable}.contains('1')`
Something like that

**Comment by andrewtelnov** [comment]
@GuiAfonso sure you may use contains:
`{variable} contains '1'`

Thank you,
Andrew

**Comment by GuiAfonso** [comment]
@andrewtelnov thanks bro, works perfectly. 

Have a documentation with all conditions? To don't ask this silly question again.

**Comment by andrewtelnov** [comment]
Will do :-)

**Comment by andrewtelnov** [comment]
@GuiAfonso Here it is: http://surveyjs.org/docs/QuestionBase/visibleIf.html

**Comment by GuiAfonso** [comment]
Awesome
