### ISSUE TITLE
Date field for older browsers

### ISSUE THREAD

**Issue by vraghu1983** [surveyjs/surveyjs#180]
Hi Andrew - the older browser versions dont support HTML Date field - so how i do achieve this functionality of a date picker in the questions ?

**Comment by andrewtelnov** [comment]
You may create a new question. Here is the example to add a question as a plugin: http://surveyjs.org/examples/knockout/custom-question.html
Another way, include new question into the library: https://github.com/andrewtelnov/surveyjs/tree/master/src/plugins

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@vraghu1983 We support third party widgets now. Here is the demo with jQuery date picker widget: http://surveyjs.org/examples/jquery/custom-widget-datepicker.html
