### ISSUE TITLE
Multiple classes in a label btn 

### ISSUE THREAD

**Issue by Daggb** [surveyjs/surveyjs#185]
Hello, I'm changing the selected radio btn class to active when selected, I managed to do it with:

data-bind="css:{active: $data.value == question.koValue()}

But also need to add $data.value as a css class I managed to do it like this:

new Survey.SurveyTemplateText().replaceText('<div class="btn-group"> <label class="btn btn-default" data-bind="css: $data.value, style:{width: question.koWidth}"> <input type="radio" style="display:none;" data-bind="attr: {name: question.name, value: item.value}, checked: question.koValue" /> <span data-bind="text: item.text"></span></label><div data-bind="visible:question.hasOther"><div data-bind="template: { name: \'survey-comment\', data: {\'question\': question, \'visible\': question.koOtherVisible } }"></div></div></div>', "question", "radiogroup"); new Survey.SurveyTemplateText().replaceText('<div class="btn-group"> <label class="btn btn-default" data-bind="css: $data.value, style:{width: question.koWidth}"> <input style="display:none;" type="checkbox" data-bind="attr: {name: question.name, value: item.value}, checked: question.koValue" /> <span data-bind="text: item.text"></span></label><div data-bind="visible:question.hasOther"><div data-bind="template: { name: \'survey-comment\', data: {\'question\': question, \'visible\': question.koOtherVisible } }"></div></div></div>', "question", "checkbox");

Now that I'm using

data-bind="css:{active: $data.value == question.koValue()}

I can't add the second class, I tried to add it in the attr: but it overwrites the class="btn btn-default"

What could be the best approach to add the $data.value as a class?

**Comment by andrewtelnov** [comment]
@Daggb I could not understand what you are trying to achieve :-( You have implemented "active" absolutely correctly. Probably we will add "active" class for radio group and checkbox. It seems quite reasonable. But what do you try to implement with $data.value?

**Comment by Daggb** [comment]
@andrewtelnov I'm trying to implement different style for some buttons, different backgrounds and colours, assigning a class depending on the $data.value. 

Is this achievable?

**Comment by andrewtelnov** [comment]
@Daggb are you fighting with knockoutjs? If yest, then there is the example:
http://stackoverflow.com/questions/14255339/how-to-add-a-dynamic-class-in-knockoutjs
http://jsfiddle.net/vyshniakov/gKaRF/
I am not sure I got it correctly.

Thank you,
Andrew
