### ISSUE TITLE
Create a display mode

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#187]
A typical scenario you want to have the ability to review the answers other people on your website without ability to modify results.
Solution: introduce a new property survey.mode with two possible values: "edit" (default) and "display".
Do not check on errors for display mode and do not send results into the server.

**Comment by andrewtelnov** [comment]
It is implemented. The demo is required.

**Comment by vraghu1983** [comment]
Thanks a lot - do i need an updated version of the surveyjs library now to my project ?

**Comment by andrewtelnov** [comment]
I do not upload the latest version to surveyjs.org and do not update npm packages yet.
However, you may build the library by yourself, just do the steps described in the readme file: https://github.com/andrewtelnov/surveyjs

**Comment by andrewtelnov** [comment]
Demo has been created: http://surveyjs.org/examples/jquery/survey-displaymode.html
