### ISSUE TITLE
Combine partial results and send as one result to render on the survey

### ISSUE THREAD

**Issue by vraghu1983** [surveyjs/surveyjs#191]
Hi - below is the scenario : 

Step 1 - I have 7 sections of my survey as one whole survey is too lengthy. Have buttons for each section and store the json for each section individually. 
Step 2 - User comes in - sees a section and then answers and submits 
Step 3 - Answers stored in local DB for that section 
Step 4 - User can come and I have another button where he can just view the questions submitted for review / printout. 
Step 5 - Very end of the screen - have a button for viewing the entire 7 sections 
Step 6 - Just have consolidated the entire 7 section JSON for the questions to be displayed one shot, so the survey loads ok with all 7 sections shown OK 
Step 7 - How do i load all JSON answers - what is the best approach ?

**Comment by andrewtelnov** [comment]
@vraghu1983 dxsurvey.com service implements this task. There should be "clientId" (string) attribute in the json result. Typically it is a unique user id (GUID or e-mail). After every submit the service merge the new  results with previous.
I would suggest to implement something similar.

Thank you,
Andrew
