### ISSUE TITLE
Question: Can a survey be displayed with previously entered data and edited?

### ISSUE THREAD

**Issue by deztech** [surveyjs/surveyjs#198]
My surveys will be ongoing entities whereby operators will enter new data AND edit previous data over time. I want to know if a previous completed survey can be displayed with the original data, edited, and re-saved.

Thanks!

**Comment by andrewtelnov** [comment]
@deztech Of course you can. Here is the example: http://surveyjs.org/examples/jquery/survey-data.html
You have to set the survey.data = YourPreviousSurveyData;

If you want to disable editing and make the survey read-only then set survey.edit = "dispay"; 

Thank you,
Andrew

**Comment by deztech** [comment]
Great, Andrew, thanks for the quick response!
-Aaron
