### ISSUE TITLE
Question JSON throwing error 

### ISSUE THREAD

**Issue by vraghu1983** [surveyjs/surveyjs#199]
Hi - here is part of my JSON which throws an error as 
Uncaught SyntaxError: Unexpected token / in JSON at position 3205 

 {
     "type": "multipletext",
     "name": "CE4",
     "title": "What are  the various  value-added  courses/enrichment programmes offered to ensure holistic development of students?",
     "items": [
      {
       "name": "Moral and Ethical values"
      },
      {
       "name": "Employable and Life skills"
      },
      {
       "name": "Better Career Options"
      },
      {
       "name": "Community Orientation"
      }
     ]
Do I need to escape any special characters ?

**Comment by vraghu1983** [comment]
Forgot to mention - this is stored in local DB and am using C# to retrieve the value from DB 
![screenshot - 1_25_2017 4_52_43 pm](https://cloud.githubusercontent.com/assets/11383924/22288844/b9c2ba34-e31e-11e6-8abc-c207e935a78f.png)

**Comment by andrewtelnov** [comment]
@vraghu1983 the json looks fine to me. What do you do in your aspx page? As I understand QuestionJSON is rendering as JSON object. Why do you need to parse it to get the JavaScript object?

Thank you,
Andrew

**Comment by vraghu1983** [comment]
![screenshot - 1_30_2017 9_09_22 am](https://cloud.githubusercontent.com/assets/11383924/22411619/d19f3492-e6cb-11e6-8bf3-844bcd72f4ea.png)

**Comment by vraghu1983** [comment]
![screenshot - 1_30_2017 9_10_22 am] Corresponding HTML (https://cloud.githubusercontent.com/assets/11383924/22411633/f382c7cc-e6cb-11e6-906f-55e462eaf793.png)

**Comment by vraghu1983** [comment]
Complete JSON as attached 
[json.txt](https://github.com/surveyjs/surveyjs/files/738126/json.txt)

**Comment by andrewtelnov** [comment]
@vraghu1983 I am using the following code in dxsurvey.com:
<script type="text/javascript">
.....
var modelData = @Html.Raw(JsonConvert.SerializeObject(this.Model));
....
</script>
Where this.Model is a c# class that contains string, int and Guid properties only.
I hope it helps. However, I believe, you will find plenty examples and help on stackoverflow.com. 

Thank you,
Andrew

**Comment by vraghu1983** [comment]
![screenshot - 1_31_2017 12_07_34 pm](https://cloud.githubusercontent.com/assets/11383924/22454726/0f513622-e7ae-11e6-8ce9-36285a496e03.png)
![screenshot - 1_31_2017 12_07_42 pm](https://cloud.githubusercontent.com/assets/11383924/22454727/121494da-e7ae-11e6-942b-51f796d81736.png)
![screenshot - 1_31_2017 12_07_53 pm](https://cloud.githubusercontent.com/assets/11383924/22454728/148aaa2e-e7ae-11e6-995b-5bebb8ca9bf3.png)

**Comment by vraghu1983** [comment]
Found this example which has no errors - the alert shows the parsed JSON correctly -- however the view says "There is no any visible page or visible question in the survey"

**Comment by vraghu1983** [comment]
![screenshot - 1_31_2017 12_11_07 pm](https://cloud.githubusercontent.com/assets/11383924/22454777/6620922c-e7ae-11e6-8f43-7ba6ac08590e.png)
![screenshot - 1_31_2017 12_11_15 pm](https://cloud.githubusercontent.com/assets/11383924/22454780/67fb28aa-e7ae-11e6-89f0-99058be1d9fc.png)

**Comment by andrewtelnov** [comment]
@vraghu1983 You are passing the parsedJSON as a string. It should be the JSON. Please correct the line: 
survey = new Survey.Survey(JSON.stringify(parsedJSON), "surveyContainer");

**Comment by vraghu1983** [comment]
![screenshot - 1_31_2017 1_48_21 pm](https://cloud.githubusercontent.com/assets/11383924/22457115/15c96304-e7bc-11e6-9a6c-6b62c14b4506.png)

Still the same :( alerted the JSON.stringify - and attached the result set

**Comment by andrewtelnov** [comment]
@vraghu1983 Sorry, my bad. JSON.parse(parsedJSON) should be used of course.

**Comment by vraghu1983** [comment]
![screenshot - 1_31_2017 2_56_53 pm](https://cloud.githubusercontent.com/assets/11383924/22459190/a5c16cbe-e7c5-11e6-82a2-2489c3e50006.png)
![screenshot - 1_31_2017 2_57_38 pm](https://cloud.githubusercontent.com/assets/11383924/22459202/ab67dbda-e7c5-11e6-8258-455919e8f036.png)
Had tried that - and results in this :(

**Comment by andrewtelnov** [comment]
Did you try to insert the json as static variable? You are sending images, so I could not try it.

**Comment by vraghu1983** [comment]
Yes - i tried -  same result . 

parsed JSON from the page is in here -- 
[parsedJson.txt](https://github.com/surveyjs/surveyjs/files/741545/parsedJson.txt)

If i input this same JSON without the parsing in surveyjs site - the questions render ok. Attached the JSON file
[json.txt](https://github.com/surveyjs/surveyjs/files/741550/json.txt)

**Comment by andrewtelnov** [comment]
@vraghu1983 You have double quotes in the beginning and on the end:
'" ...."'. Remove ' from the beginning and end and everything will be fine. I just tried it.

**Comment by vraghu1983** [comment]
Awesome Est - silly me - :)

**Comment by vraghu1983** [comment]
Just when i thought all was well - the same code if i test out as a popup - it does not work - shows the survey does not have visible questions. The popup script is as below - am i missing anything? 
I pass the JS from viewbag from home controller and catch it in a javascript variable here. I noticed the popup source and JSOn is indeed passed. 

@{
    ViewBag.Title = "Survey";
    var jss = new System.Web.Script.Serialization.JavaScriptSerializer();
    var QJSON = jss.Serialize(ViewBag.QuestionJSON);
}

<script src="~/Scripts/jquery-3.1.0.min.js"></script>
<script src="~/Scripts/jquery-ui-1.8.20.js"></script>
<script src="~/Scripts/knockout.js"></script>
<script src="~/Scripts/survey.bootstrap.min.js"></script>
<link href="~/Content/survey/survey.css" type="text/css" rel="stylesheet" />

<div id="surveyContainer"></div>

<script type="text/javascript">

    $(document).ready(function () {
        var survey = new Survey.Survey(JSON.parse(@Html.Raw(QJSON)), "surveyContainer");
    });
</script>

**Comment by vraghu1983** [comment]
![screenshot - 2_1_2017 11_21_36 am](https://cloud.githubusercontent.com/assets/11383924/22496541/9d138632-e870-11e6-8adf-bd20695a7684.png)
Attaching screenshot as some portion of the code is ommitted when i copy paste it

**Comment by andrewtelnov** [comment]
@vraghu1983 It is hard to say what is going on in your project. Please try to recreate the problem on a simpler page. 
I also noticed that you are using the old version of the survey. I renamed survey.bootstrap.min.js to survey.ko.min.js that supports two bootstrap and no bootstrap css classes several months ago.
Please read the update page: http://surveyjs.org/index.html

**Comment by vraghu1983** [comment]
Ok - i have a simple page - on click of a button - introduced the same code - and it works. 
However, when i return a partial view or something, it shows no visible questions in the survey. I will read the update page and add the modifications and try it out.
