### ISSUE TITLE
Buttons for answers

### ISSUE THREAD

**Issue by BIGANDYT** [surveyjs/surveyjs#202]
It would be great if instead of adding radio list or checkboxes you could just add a list of buttons where the label is the asnwer, So instead of having to click twice to select the radio or checkbox and then next, you just click the relevant answer button and it goes to the next page.

**Comment by andrewtelnov** [comment]
@BIGANDYT I believe that you are talking about this functionality: http://surveyjs.org/examples/jquery/survey-autonextpage.html

**Comment by BIGANDYT** [comment]
Sort of, but i wouldn't want radio buttons, i want an actual click button, where the answer is rendered as the text of the button. The use case is a touch screen type survey its more user friendly to click a button rather than click a radio element. Thanks for the response.

**Comment by andrewtelnov** [comment]
@BIGANDYT You may change the rendering: http://surveyjs.org/examples/knockout/survey-customtemplate.html
Though, It is supported in react and knockout versions only.

**Comment by BIGANDYT** [comment]
Perfect thanks
