### ISSUE TITLE
Release "download" contains old file?

### ISSUE THREAD

**Issue by ryancwalsh** [surveyjs/surveyjs#203]
When I try to download the latest release (0.10.4) at https://github.com/surveyjs/surveyjs/releases, I open the surveyjs.tar.gz to see that the js files still say 0.10.3 at the top, and this bug still exists: https://github.com/surveyjs/surveyjs/issues/200

I'm wondering if I'm doing something wrong or if the "downloads" listed in that release are just outdated somehow?

Thanks!

**Comment by andrewtelnov** [comment]
@ryancwalsh I have update the library on http://surveyjs.com. You may download the library at: http://surveyjs.org/downloads/surveyjs.zip
I remember @dmitrykurmanov have created a script that should re-build the library on every successful travis build. 
@dmitrykurmanov Could you check what is going on here?

Thank you,
Andrew

**Comment by ryancwalsh** [comment]
@andrewtelnov Thanks. That was helpful. By the way, the main http://surveyjs.org/ has been offline today, but subpages like http://surveyjs.org/examples/jquery/ work.

**Comment by andrewtelnov** [comment]
@ryancwalsh That is strange, but thank you! The website is hosted by github. It is run on [jekyll](https://jekyllrb.com/). I will google what can it be.

**Comment by ryancwalsh** [comment]
@andrewtelnov @dmitrykurmanov The latest [release page](https://github.com/surveyjs/surveyjs/releases/tag/0.11) offers `surveyjs.tar.gz`, which contains `survey.jquery.min.js`, which is still `v0.10.4`. So I guess the script that updates the Downloads on Github still doesn't work.

**Comment by andrewtelnov** [comment]
@ryancwalsh Yes, we will work on it on the next week.
@dmitrykurmanov and @tsv2013 let's fix it!

**Comment by dmitrykurmanov** [comment]
@ryancwalsh, we fixed it
