### ISSUE TITLE
Page title

### ISSUE THREAD

**Issue by mcaple** [surveyjs/surveyjs#204]
I was hoping to have a survey title of the form

Hello {name} you have {dogs} dogs

by passing in a data prop  { "name": "John", "dogs": "3" }.  Is this possible?

**Comment by mcaple** [comment]
For a required field can we remove the trailing semi colon? For a rating question for example you may have 

_Tell us if you agree

Your dogs are happy (*)

Strongly agree 1 2 3 4 5 Strongly disagree_ 

Just looks weird when the sentence in structured as a statement as above and not a question to have a trailing ':' as in 'Your dogs are happy(*) :'

**Comment by andrewtelnov** [comment]
@mcaple The page title may be set exactly as you described: "Hello {name} you have {dogs} dogs".
Here is the example: http://surveyjs.org/examples/jquery/survey-processtext.html
If you are talking about Survey.title - it is not possible at the current moment. Do you need this functionality for the survey title or page title?

Thank you,
Andrew

**Comment by mcaple** [comment]
Sorry Andrew it is the Survey Title I want to change dynamically. I could always hide it and add my own title but hoped it could be done within the component

**Comment by andrewtelnov** [comment]
@mcaple I have added text processing for survey.title. I did not update npm packages. You may download the updated version from: http://surveyjs.org/downloads/surveyjs.zip.

Thank you,
Andrew

**Comment by mcaple** [comment]
I notice @andrewtelnov you have released this change in 0.11 so have updated to that with the following

`
const surveyalt = new Survey.Model({
  ...
  title: 'Hello {name} you have {dogs} dogs',
});

const data = { "name": "John", "dogs": "3" };

render() {
    return (
      <Survey.Survey
        model={surveyalt}
        data={data}
        ...
      />
    );
  }
`

but the title is 'Hello {name} you have {dogs} dogs' with no replacement. Is that how I should do things?

Mark

**Comment by andrewtelnov** [comment]
@mcaple Yes, there is a bug. As a workaround, please sue the following code:

```
 surveyalt.setValue("name", "John");
 surveyalt.setValue("dogs", 3);

render() {
return (
<Survey.Survey
model={surveyalt}
...
/>
);
}
```

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
I have fixed the issue. In the next minor release you will be able to use the data as well.

Thank you,
Andrew
