### ISSUE TITLE
Required field

### ISSUE THREAD

**Issue by mcaple** [surveyjs/surveyjs#205]
For a required field can we remove the trailing semi colon? For a rating question for example you may have

_Tell us if you agree

Your dogs are happy (*)

Strongly agree 1 2 3 4 5 Strongly disagree_

Just looks weird when the sentence in structured as a statement as above and not a question to have a trailing ':' as in 'Your dogs are happy(*) :'

**Comment by mcaple** [comment]
@andrewtelnov I want to keep a required indicator but not the ':'. In the example you show can I have

Please type your name (*)

and not 

Please type your name (*):

Thanks
Mark

**Comment by andrewtelnov** [comment]
@mcaple Sure you can do it. Here is the example: http://surveyjs.org/builder/index.html?surveyid=f6cca18a-7c2f-45aa-8c4e-5f32de0ad3bf
Please take a look at json (JSON Editor tab).

Thank you,
Andrew

**Comment by mcaple** [comment]
Thanks @andrewtelnov I stupidly had

  questionTitleTemplate: '{no}) {title} {require} :',

from the  [http://surveyjs.org/examples/react/survey-processtext.html](url)  sample

and there was a ':' in my template :(. Must admit didn't really understand the {no}) {title} {require} bit at first thought they were attributes of data passed in. Not a big fan of magic strings. 

Mark
