### ISSUE TITLE
Feature requests: placeholder values and "email" input type

### ISSUE THREAD

**Issue by ryancwalsh** [surveyjs/surveyjs#207]
It would be great to support "email" as an input type because people answering surveys on their mobile phones will then be shown a keyboard optimized for typing their email address.

- See https://davidwalsh.name/html5-email

It would also be great to support the 'placeholder' attribute to make forms easier to understand.

- See https://davidwalsh.name/demo/html5-placeholder.php

What do you think?

Thanks for all of your hard work!

**Comment by andrewtelnov** [comment]
@ryancwalsh it makes sense. We will discuss it and comeback to this thread.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@ryancwalsh I will implement the placeHolder. It makes perfect sense: https://github.com/surveyjs/surveyjs/issues/210

**Comment by andrewtelnov** [comment]
inputType is already implemented: http://surveyjs.org/examples/jquery/questiontype-text.html

**Comment by ryancwalsh** [comment]
@andrewtelnov Sweeeet! I don't know how I didn't see that you already supported 'email' as an inputType. Fantastic!  You are on the ball! THANKS!
