### ISSUE TITLE
Urgent Enquiry

### ISSUE THREAD

**Issue by Peeyou** [surveyjs/surveyjs#209]
Can I use surveyjs to build an application like surveymonkey or google forms?

**Comment by andrewtelnov** [comment]
@Peeyou Sure you can.
However surveyjs library is under MIT license and you may do what ever you want with the code and the library, but surveyJS editor has the commercial license: http://editor.surveyjs.io/license.html.
Unless you are not going to sell surveyJS editor as it is or as part of other library to other software developers, you are fine. In other words, you may create your own surveymonkey service.

PS: We are working hard on new features for surveyJS editor. For example: we are working on question Editors at the current moment.  SurveyMonkey editor has the similar question.

**Comment by Peeyou** [comment]
Thank you very much for your prompt response.

I am elated at your response. We do not intend to sell; we just want to
customize it to suit our brand and likely develop it further. Are the
tutorials on the Survey.js homepage sufficient to guide me through
developing this service or do i require more. Also do i have right to full
customization to suit my need.

Thank you


*Uche Okocha*
Innovator - Web Developer - UI/UX Designer
Impossible Is Impossible

**Comment by andrewtelnov** [comment]
@Peeyou As I wrote before: surveyjs is under [MIT license](https://opensource.org/licenses/MIT). It means you may do what ever you want.
[SurveyJS Editor](http://editor.surveyjs.io/) is under the [commercial license](http://editor.surveyjs.io/license.html). You may add the editor into your website and modify the code under this license. The license page describes the term of usage.

PS: Before adding new features into Editor, I would suggest  you to contact our team. We are working on the editor pretty hard and there is a possibility we will include features you need into the next version.

Thank you,
Andrew
