### ISSUE TITLE
Add placeHolder property into text, comment and multiple text questions.

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#210]

**Comment by ryancwalsh** [comment]
Awesome. And 'placeholder' is all lowercase.

**Comment by andrewtelnov** [comment]
@ryancwalsh It is implemented. The property is placeHolder, but the attribute is rendered as 'placeholder' of course. The updated library can be downloaded at: http://surveyjs.org/downloads/surveyjs.zip

**Comment by ryancwalsh** [comment]
@andrewtelnov Thanks!!

**Comment by andrewtelnov** [comment]
Examples for text and comment questions were updated.
