### ISSUE TITLE
Text validator for open questions - setting maxLenght  or regEx alternative?

### ISSUE THREAD

**Issue by cnx90** [surveyjs/surveyjs#211]
For open questions it could be nice to define a validator for the maximum length of characters (maxLenght) - for example limit of 30 characters per question. For now it's possible to set minLenght as validator, but maxLenght option is missing.

Alternatively, is it possible to add this functionality via regex editor? For example to accept the answers that are containing between 1 and 30 characters? I cannot make it working via this regex :

`^(?=.{1,30}$)[\S]+\-[\S]+$ `

or placing a html maxlength?

Thank you for any suggestions! 
Great job with the script!

**Comment by andrewtelnov** [comment]
@cnx90 At the current moment there are only two options:
[Custom Validator](http://surveyjs.org/examples/jquery/validators-custom.html), you may extend the current TextValidator or [write code on event](http://surveyjs.org/examples/jquery/validators-event.html)

You suggestion makes sense. regex and maxLength properties can be added into the library. We will add in the next update.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@cnx90  The maxLength property was added into textvalidator. There is regexvalidator. You may have several validators in a question. The updated library can be downloaded at: http://surveyjs.org/downloads/surveyjs.zip
