### ISSUE TITLE
Single Input - validation for currency

### ISSUE THREAD

**Issue by bowtree00** [surveyjs/surveyjs#212]
I'm hoping to set up validation on a 'single input' field that checks that a value entered includes a $ and numbers (e.g., $123.30, or at least $123).  Are there any plans to include a validator for this?

Thanks

**Comment by andrewtelnov** [comment]
@bowtree00 You may use inputType: "number" for text question and/or add regex 
validators: [{ type: "regex", regex: "^[+-]?[0-9]{1,3}(?:,?[0-9]{3})*(?:\.[0-9]{2})?$", text: "Please enter a number" }]

**Comment by bowtree00** [comment]
Great, thank you!
