### ISSUE TITLE
'Back' button to re-open a completed survey

### ISSUE THREAD

**Issue by bowtree00** [surveyjs/surveyjs#213]
I am looking to be able to go 'back' into a completed survey so a user can revise their input after submitting.  Is this currently possible? If not, are there any plans to provide this functionality?

Thank you

**Comment by andrewtelnov** [comment]
@bowtree00 You will have to call the following function: survey.clear(false, true);
//public clear(clearData: boolean = true, gotoFirstPage: boolean = true);

Thank you,
Andrew

**Comment by bowtree00** [comment]
Thanks Andrew, I'll give that a try. Cheers.
