### ISSUE TITLE
Calculate product of two numbers entered in separate input fields

### ISSUE THREAD

**Issue by bowtree00** [surveyjs/surveyjs#214]
I would like to be able to ask a user to enter in two numbers and then show them the product of those two numbers immediately after they are entered (rather than after the survey is submitted). Is there a way to get the values from input fields as they are entered?

Thanks for your help

**Comment by andrewtelnov** [comment]
@bowtree00 I am not sure I got the task correctly. Are you looking for something like this? http://surveyjs.org/examples/jquery/survey-data.html

**Comment by dmitrykurmanov** [comment]
@bowtree00 or may be you need to try "visibleif" http://surveyjs.org/examples/jquery/condition-kids.html

**Comment by bowtree00** [comment]
Sorry, I'll clarify. I want to be able to calculate a number for a user off to the side of the page that is the product of two numbers entered into two different text input fields.  So if one question asks: "How many widgets do you have?" and another says "How much does each widget cost?", then I want to be able to take those two numbers, multiply them, and display the total cost of widgets for them elsewhere on page in real time (before they submit the survey). I'm wondering if I can grab the values from the input fields as they are being typed?

Thanks for your help

**Comment by andrewtelnov** [comment]
@bowtree00 You are definitely should take a look at [this demo](http://surveyjs.org/examples/jquery/survey-data.html). It does exactly what you need.

**Comment by bowtree00** [comment]
Thanks Andrew, this looks promising, I'll play around with it. It currently only updates in the box on the right of the page after you click outside of the text entry box, but I'd like for it to update as the user is typing. I see the code uses survey.onValueChanged - I haven't played around with it, but I'm assuming I can change this to something like .keydown?
