### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by mcaple** [surveyjs/surveyjs#215]
The progress bar appears in the centre. Is it possible to justify this left/right or centre?

The progress bar shows 'Page 1 of 8' for instance but when the screen width becomes too narrow it displays 'Page 1' and 'of 8' is cut off, could the survey progress bar drop the word 'Page' below a certain size so that it displays '1 of 8' which is more relevant?

Thanks
Mark

**Comment by andrewtelnov** [comment]
@mcaple Are you using bootstrap or non-bootstrap version and which library knockout/react/jQuery/angular? I will try to correct the rendering.
As a workaround you may override progress and progressBar survey css properties by adding/setting your own css class. Here is the example: http://surveyjs.org/examples/jquery/survey-customcss.html

**Comment by mcaple** [comment]
@andrewtelnov bootstrap and react

**Comment by andrewtelnov** [comment]
@mcaple Here is the example of code that does what you need:

```
Survey.surveyStrings.progressText = "{0} of {1}";
var myCss = {progress: "progress pull-left"};
ReactDOM.render(
        <Survey.Survey json={json} data={surveyData} css={myCss} />, document.getElementById("surveyContainer"));

```

**Comment by mcaple** [comment]
Thanks @andrewtelnov you are always quick to respond
