### ISSUE TITLE
Conditional Pages?

### ISSUE THREAD

**Issue by ericdmessick** [surveyjs/surveyjs#218]
Is there a way to set up conditional pages of questions.  I'm building a rather large survey where several sections of questions are dependent on proceeding answers.  It's sort of a complex decision tree.  Thank you.

**Comment by andrewtelnov** [comment]
@ericdmessick We are working on improving our surveyJS Editor right now. At the current moment there is nothing what you are looking for.
However, what do you want to have? We may consider to implement this.
Do you want to have a dependencies tree? - that is pretty advanced task, but of course it is doable.
Do you want to have logs in the Test Running Survey? - that is easy enough, you will be able to see all values and visibility changes - one by one.
Do you want to have all visibleIf question text in one Window?

Thank you,
Andrew

**Comment by ericdmessick** [comment]
What I want to do is similar to questions appearing depending on the previous answer.  In my case, I would like if a user answers a question "Yes", for a page of follow up questions to appear.  If no, skip that page and go to the next page of questions.  I got the idea while doing my taxes online.  In the beginning, the tax application asked some basic questions.  Then, base on those answers, it presented pages of follow up questions that were applicable.  I got to skip all the pages that were not applicable.

**Comment by andrewtelnov** [comment]
@ericdmessick the page object has visibleIf property. It works exactly as question.visibleIf property. If the expression return true, the page becomes invisible and the end user will skip it. If all questions become invisible on a page, it becomes invisible as well. 
I think we need more demos for visibleIf property. The current [demo](http://surveyjs.org/examples/jquery/condition-kids.html), we have,  is not enough.

Thank you,
Andrew

**Comment by ericdmessick** [comment]
Thanks you Andrew.  After I posted the other day, I continued playing and figured out just what you said.  

I got the survey working, and it works very well.
