### ISSUE TITLE
Delete some property from questions

### ISSUE THREAD

**Issue by EminYasarturk** [surveyjs/surveyjs#221]
Hi everybody,

I want to be passive some options from 'page' and 'questions'. I can delete like this

Survey.JsonObject.metaData.removeProperty("page", "visibleIf");
Survey.JsonObject.metaData.removeProperty("page", "visible");

Survey.JsonObject.metaData.removeProperty("questionbase", "visibleIf");
Survey.JsonObject.metaData.removeProperty("questionbase", "choicesByUrl");

Is there any way loop condition like this for 'page' and 'questions': 

	var editor = new SurveyEditor.SurveyEditor();
	editor.onCanShowProperty.add(function(sender, options){
		if(options.obj.getType() == "survey") {
			options.canShow = options.property.name == "title";
		}
	});

**Comment by andrewtelnov** [comment]
@EminYasarturk onCanShowProperty works for page and questions as well.
However, what exactly doesn't work with visible/visibleIf properties removing? These properties have to disappear from the property editor / question Editors. Editor will stop save them in survey JSON and the library will not load them from JSON. The default value will be always used: visible: true and visibleIf (empty string).

The difference between making a property invisible onCanShowProperty event and removing it completely. onCanShowProperty hides properties in editor UI, but they are still exists and you may load them from JSON or set them by yourself.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
I mean you may have the following code:
```
var editor = new SurveyEditor.SurveyEditor();
editor.onCanShowProperty.add(function(sender, options){
    options.canShow = !options.property.name.startWith("visible");
});
```

**Comment by EminYasarturk** [comment]
Hi @andrewtelnov ,

I guess, I didn't use onCanShowProperty function correctly. I don't want to show some property in Property Ares like Visible, visibleIf, choicesByUrl, trigger,storeOthersAsComment etc.

I mean, onCanShowProperty can use for 'Survey' not 'page' or 'question'. But you say I can use 'Survey','page' and 'questions'.

I research it for loop

**Comment by andrewtelnov** [comment]
@EminYasarturk I am not sure what loop you are taking about. It is an event. It calls before rendering a property in the property grid. If canShow will be false, then a property is not rendered.
Here is the code you have to write:
```
var editor = new SurveyEditor.SurveyEditor();
editor.onCanShowProperty.add(function(sender, options){
    var propName = options.property.name;
    options.canShow = !propName.startWith("visible") && propName != "choicesByUrl" && propName != "triggers" &&  propName != "storeOthersAsComment";
});
```
Or are you talking about creating an array of properties that you want to hide and then use them? It can be done as well, of course.
However, I would suggest an opposite, since at any time, we may add a new property to any object, you may create a list of properties that you are allowing to show and use it.
```
var editor = new SurveyEditor.SurveyEditor();
var allowedProperties = ["name", "title"];//all properties that you want to show
editor.onCanShowProperty.add(function(sender, options){
    var propName = options.property.name;
    var isFound = false;
   for(var i = 0; i < allowedProperties.length; i ++)  
      if(propName == allowedProperties) { isFound = true; break;}
   options.canShow = isFound;
});
```

**Comment by tucq88** [comment]
Examples above seem all out-of-date, as `propName` is now `options.propertyName` and delete properties isn't working :( 
I also can't find any document mentions about deleting properties, Could you help please @andrewtelnov ?
