### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by mcaple** [surveyjs/surveyjs#222]
If I am using react and setting the following

Survey.Survey.cssType = 'bootstrap';

should I be able to use a theme from

[Themes](https://www.bootstrapcdn.com/bootswatch/)

such as

`<link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cyborg/bootstrap.min.css" rel="stylesheet" integrity="sha384-D9XILkoivXN+bcvB2kSOowkIvIcBbNdoDQvfBNsxYAIieZbx8/SI4NeUvrRGCpDi" crossorigin="anonymous">`

I see no changes at the moment

Thanks
Mark

**Comment by andrewtelnov** [comment]
@mcaple Probably there is no visible changes because this theme is close to the default one. 
There is no any magic here. Please take a look at the [following demo](http://surveyjs.org/examples/jquery/survey-customcss.html). It shows the css classes used by surveyjs. You may change them. I guess, these css classes are the same in default bootstrap theme and in your themes.
One surveyjs user has used a bootstrap theme that supports material design. He has override the css classes however, as shown in the demo. It looked pretty cool.

Thank you,
Andrew

**Comment by mcaple** [comment]
I looked at that @andrewtelnov and you are correct. It's just that the theme I chose is predominantly white text on a black background so I thought I could see the difference straight away.

**Comment by mcaple** [comment]
Sorry @andrewtelnov but as I said the cyborg theme I selected was basically white text on a black background. If I include this theme I can see the CSS in the browser but all the styling is being overridden by the inline styling for the survey component. If I bump the cyborg style with a '!' or deselect the inline style in dev tools I see what I want. I must be missing something. Didn't want to create a complete CSS object and pass that in was hoping just to include theme as mentioned in initial question.

**Comment by andrewtelnov** [comment]
@mcaple I just go through all knockout templates (react rendering is absolutely the same and angular and jQuery are based on react version). There are some inline style settings, but they are for setting width, visibility and overflow mostly. We need to control it.
Maybe I am missing something. 
We want to make sure that surveyjs supports different bootstrap themes out of the box. 
Could you please send us a link on a page, so we could play with it? Or an html code and tell us what inline style should we turn-off.

Thank you!

**Comment by mcaple** [comment]
I wanted to make this super easy so basically my index.html is

`<!DOCTYPE HTML>
<html>
  <head>
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cyborg/bootstrap.min.css" rel="stylesheet" integrity="sha384-D9XILkoivXN+bcvB2kSOowkIvIcBbNdoDQvfBNsxYAIieZbx8/SI4NeUvrRGCpDi" crossorigin="anonymous">

    <meta charset="utf-8">
    <title>React Hello World</title>
  </head>
  <body>

    <div id='root'></div>

    <script src="https://fb.me/react-15.0.1.js"></script>
    <script src="https://fb.me/react-dom-15.0.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>

    <script src="scripts.js" type="text/babel"></script>
  </body>
</html>
`

Now because you do not have a CDN repository and I did not want to download the full source for surveyjs for this sample my scripts.js will show the hello message using the cyborg css linked above. You can see the White on Black. If you uncomment the second half and comment the first you will see basically what I am trying to do. I have no CSS prop here although I have tried that also. Obviously you will have to include the survejs code into the sample but like I said I have tried to make this as small as possible.

`
var HelloMessage = React.createClass({
  render: function () {
    return <p>Hello {this.props.message}!</p>;
  }
});

ReactDOM.render(<HelloMessage message="World" />, document.getElementById('root'));

// Survey.defaultBootstrapCss.navigationButton = 'btn btn-primary';
// Survey.Survey.cssType = 'bootstrap';
// const surveyalt = new Survey.Model({
//   questionTitleTemplate: '{no}) {title} {require}',
//   title: 'Know yourself {name}',
//   requiredText: '(*)',
//   pages: [
//     { title: 'Asset Management',
//       questions: [
//         { type: 'rating',
//           name: 'asset-1',
//           title: 'You have too many dogs',
//           mininumRateDescription: 'Strongly agree',
//           maximumRateDescription: 'Strongly disagree',
//           isRequired: true,
//         },
//         { type: 'rating',
//           name: 'asset-2',
//           title: 'Fred is your favourite dog',
//           mininumRateDescription: 'Strongly agree',
//           maximumRateDescription: 'Strongly disagree',
//           isRequired: true,
//         },
//       ],
//     },
//   ],
// });
//
// surveyalt.showProgressBar = 'bottom';
// surveyalt.completedHtml = 'Complete';
//
// ReactDOM.render(<Survey.Survey model={surveyalt} />, document.getElementById('root'));
`

**Comment by andrewtelnov** [comment]
@mcaple What version of surveyJS are you using? The current version is v0.11.0 - it works just fine.
![chrome](https://cloud.githubusercontent.com/assets/5655108/22688423/4c17fc6e-ed3d-11e6-98c2-43d5b124b116.png)
Here is the html file:
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>

    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cyborg/bootstrap.min.css" rel="stylesheet" integrity="sha384-D9XILkoivXN+bcvB2kSOowkIvIcBbNdoDQvfBNsxYAIieZbx8/SI4NeUvrRGCpDi" crossorigin="anonymous">
    <script src="https://fb.me/react-15.0.1.js"></script>
    <script src="https://fb.me/react-dom-15.0.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>
    <script src="../../js/survey.react.js"></script>
</head>
<body>
    <div id='root'></div>
    <script   type="text/babel">
         Survey.defaultBootstrapCss.navigationButton = 'btn btn-primary';
         Survey.Survey.cssType = 'bootstrap';
         const surveyalt = new Survey.Model({
            questionTitleTemplate: '{no}) {title} {require}',
            title: 'Know yourself {name}',
            requiredText: '(*)',
            pages: [
                { title: 'Asset Management',
                questions: [
                { type: 'rating',  name: 'asset-1',  title: 'You have too many dogs', mininumRateDescription: 'Strongly agree',  maximumRateDescription: 'Strongly disagree',  isRequired: true, },
                { type: 'rating',  name: 'asset-2',  title: 'Fred is your favourite dog', mininumRateDescription: 'Strongly agree', maximumRateDescription: 'Strongly disagree',  isRequired: true, } ]}
            ]});
         surveyalt.showProgressBar = 'bottom';
         surveyalt.completedHtml = 'Complete';
         ReactDOM.render(<Survey.Survey model={surveyalt} />, document.getElementById('root'));
    </script>
</body>
</html>

```

**Comment by mcaple** [comment]
@andrewtelnov  If you leave this open I will check tomorrow as I am using v0.11.0 but my survey component is rendered a few levels down through a structure similar to the following

`    const hasCompleted = this.props.hasCompleted;
    let surveypart = null;

    if (!hasCompleted) {
      surveypart = <SurveyQuestions />;
    } else {
      surveypart = <SurveyChart />;
    }

    return surveypart;` 

I will firstly render as we have done above then see if anything changes as I introduce layers and let you know.

Thanks

**Comment by andrewtelnov** [comment]
@mcaple Sure, no problem. I will keep it open as long as you need it.

Thank you!

**Comment by mcaple** [comment]
Doh!  @andrewtelnov in refactoring I had moved everything to seperate components but had missed 

`import Bootstrap from 'bootstrap/dist/css/bootstrap.css';
`

in my original app.jsx as it was between other commented lines

Thanks Andrew. Thought I was going mad.
