### ISSUE TITLE
Ability to set a default answer for any question

### ISSUE THREAD

**Issue by lionelmace** [surveyjs/surveyjs#224]
I'd like to set a default answer for each question, so the user can click next without selecting anything if the default answer is good enough. Is this currently possible? If not, are there any plans to provide this functionality?

By the way, surveyjs is awesome!!

**Comment by andrewtelnov** [comment]
@lionelmace you may set the data for your questions that have default answers. Here is [the example](http://surveyjs.org/examples/jquery/survey-data.html) that shows how to do it.

Thank you,
Andrew
