### ISSUE TITLE
Support for Angular v1.6.1

### ISSUE THREAD

**Issue by kialam** [surveyjs/surveyjs#226]
Hi there,
Is there support for Angular v1.x.x?

**Comment by andrewtelnov** [comment]
@kialam Unfortunately, we are not planning to add support for angularjs v1.x. I personally do not think it is logical to work on it when Angular v2 was released.
You may use knockout or jQuery version in your angularjs project.

Thank you,
Andrew

**Comment by tsv2013** [comment]
@kialam We've discussed this issue with @andrewtelnov and prepared a boilerplate to start Angular 1.6.2 support (survey-ng) in the "feature/ng" brunch: build infrastructure, survey component, page component, navigation bar and implemented a couple of questions.
Build command is "npm run build_ng_dev".
The sample code to run is in the "/examples/ng/" folder.

Please feel free to commit, we'll provide all possible assistance.

**Comment by tsv2013** [comment]
I'm closing this since nobody interested for a year.

**Comment by kgunturu** [comment]
Is there a branch available for the ng support somewhere?

**Comment by jducobu** [comment]
I'm also interrested by the feature !

**Comment by tsv2013** [comment]
We've deleted this branch since nobody interested and wanted to commited into it for more than 2 years.

**Comment by kgunturu** [comment]
If you could find source code somewhere and upload it. We would reallly appreciate it. I will make the neccessary changes to get it working.
