### ISSUE TITLE
Support for custom question widgets

### ISSUE THREAD

**Issue by eladh** [surveyjs/surveyjs#227]
Hi there,

we exploring a survey based solution and wanted to know if there is a possibility to extend/change or create new custom question widgets in the Jquery /AngularJS versions.

best,
Elad.

**Comment by andrewtelnov** [comment]
@eladh At the current moment you may create it in react or knockutjs versions only :-(
Another solution, fork the repo and create a custom question in typescript for react and build your own library. Here is [the example of the plugin](https://github.com/surveyjs/surveyjs/tree/master/src/plugins)
We are using [preact](https://preactjs.com/) to get angular and jquery versions from react code. 

Thank you,
Andrew

**Comment by eladh** [comment]
thanks,  @andrewtelnov .
any plans for the next versions for angular2/jquery?
also -is it the same answer for supporting another styling system such as material.

best,
elad.

**Comment by andrewtelnov** [comment]
@eladh We do support angular2 and jquery. There are only couple limitation, that you are not able to write the custom questions using this frameworks.
Are your talking about material design? There are several bootstrap themes that supports material design guidelines: https://www.google.com?q=bootstrap+material+design+template. You may try any of them.

By the way, what questions do you want to add into the library?

Thank you,
Andrew

**Comment by eladh** [comment]
thanks, @andrewtelnov .

we developing angular 1 app with bootstrap and angular material for most of our UI components.
as part of our solution we need a stationary/survey component that can be displayed as chat modal (solution to chat based bot) and as a UI widget inside our wizard/flow system.

Our needs may contain - creating custom widgets as special input forms , and custom designed select widgets , creating response like questions and more.

we also have some kind of MD Editor and we wanted to integrate surveyjs.

do you have any paid based plan we can talk about ?


best,
elad

**Comment by andrewtelnov** [comment]
@eladh We get some funds to develop [SurveyJS project](surveyjs.io). There are three developers, including me right now. We are working on features that will make surveyjs project popular. Out TODO list is huge. We are not interesting to work on functionality that does not move us forward. Rendering for chat based bot maybe interesting for us, in case it will be useful for many other users.

Thank you,
Andrew

**Comment by eladh** [comment]
Great .
Any chance we can speak / chat offline ?
