### ISSUE TITLE
Results are doubled

### ISSUE THREAD

**Issue by gregordimi** [surveyjs/surveyjs#228]
First, I have to disclose I am not experienced in programming at all. Yet, I don't think the issue comes from my side.

I get every result doubled once submitted. Screenshot attached.

![image](https://cloud.githubusercontent.com/assets/22796693/22753675/400ad120-ee3d-11e6-8908-e337fa38d132.png)

PS: Using angular version on local server

Best,
Grigor

**Comment by andrewtelnov** [comment]
@gregordimi Indeed there is a bug that I have introduced some times ago. I have added a new unit test.
As a workaround, please remove the code onComplete event and just set surveyPostId property.
survey.surveyPostId = 'youpostid_GUID';

Thank you,
Andrew
