### ISSUE TITLE
Can't import surveyjs to angular 2

### ISSUE THREAD

**Issue by daitd58** [surveyjs/surveyjs#229]
I've followed the tutorial in the documentation but it's not working with angular. Any advance?

**Comment by andrewtelnov** [comment]
@dmitrykurmanov could you please help @daitd58 ?

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
@daitd58 @andrewtelnov , ok I will try to understand whats going wrong.

**Comment by dmitrykurmanov** [comment]
@daitd58 I've created an example for angular2 https://github.com/dmitrykurmanov/survey-angular-example and I've checked it with
`git clone https://github.com/dmitrykurmanov/survey-angular-example`
`npm install`
`npm run start`
and it is ok. Could you check it please? Or may be create your own example with error. Thanks.

**Comment by daitd58** [comment]
Thanks. It works.

**Comment by dmitrykurmanov** [comment]
@daitd58, you are welcome.

**Comment by tommygaessler** [comment]
I am having the same problem.

<img width="644" alt="screen shot 2017-02-13 at 1 31 30 pm" src="https://cloud.githubusercontent.com/assets/5123292/22901989/c48c3c16-f1f0-11e6-8184-e9fef8374d89.png">

<img width="596" alt="screen shot 2017-02-13 at 1 31 03 pm" src="https://cloud.githubusercontent.com/assets/5123292/22901992/c775426a-f1f0-11e6-9f7f-61344922dc80.png">

**Comment by dmitrykurmanov** [comment]
@tommygaessler, may be you need to try add something like this:

`    map: {
      ...
      'survey-angular':            'node_modules/survey-angular/dist/survey.angular.min.js'
    },`

in your systemjs.config.js file. I've done that in my example https://github.com/dmitrykurmanov/survey-angular-example. Maybe I'm wrong, I'm not very familiar with SystemJs.

**Comment by tommygaessler** [comment]
Thanks @dmitrykurmanov I got it figured out!

**Comment by Nicosoft** [comment]
Hi everyone,

I have exactly the same issue:
![image](https://cloud.githubusercontent.com/assets/4625910/23982210/1133a2e8-0a60-11e7-9d31-8f91d97e393c.png)

I'm using angular CLI.
I don't have 'systemjs.config.js' file in my project.
Does anyone know how to fix it?

**Comment by Nicosoft** [comment]
After I did >
![image](https://cloud.githubusercontent.com/assets/4625910/23982458/aa9646e2-0a61-11e7-8481-b75a8dd58bf9.png)

I import surveyjs in my component:
![image](https://cloud.githubusercontent.com/assets/4625910/23982437/859d2d74-0a61-11e7-9dbf-6da7874bbaa7.png)

then, I get this error message:
![image](https://cloud.githubusercontent.com/assets/4625910/23982443/93d43694-0a61-11e7-98a3-dc44cf38a0ac.png)

:(  it doesn't compile! Am I doing something wrong?

**Comment by Nicosoft** [comment]
:) I fixed the issue.
I went into tsconfig.app.json.
And, in "types" I added "survey-angular".
![image](https://cloud.githubusercontent.com/assets/4625910/23983177/9b691820-0a66-11e7-9586-8cee5c5f0ab6.png)
