### ISSUE TITLE
Ability to add category to survey question

### ISSUE THREAD

**Issue by jasonracey** [surveyjs/surveyjs#234]
I'm using survery-react. I need to add a "category" field to each question in my survey, optionally display it on the screen, and send to the backend when storing survey results. I don't see any obvious way to do it. Is this supported? Something like the example below:

`
var surveyJSON = {pages:[{name:"Sample Survey",questions:[{type:"checkbox",choices:[{value:"1",text:"good"},{value:"2",text:"ok"},{value:"3",text:"not good"}],name:"How are you?",category:"mood"}]}]}`

**Comment by andrewtelnov** [comment]
@jasonracey  You have to add a new property into survey question meta data.
Survey.JsonObject.metaData.addProperty("questionbase", "category");
Here is [the full description](http://editor.surveyjs.io/examples/addproperties.html#code) about adding properties into survey classes.
onComplete method, you may create the data JSON you need and send it to your server.

Thank you,
Andrew

**Comment by jasonracey** [comment]
Thanks Andrew. Using `Survey.JsonObject.metaData.addProperty("questionbase", "category");` I found my custom field here `survey.pages[0].questions[0].category` so it appears to be working as described.

**Comment by noorball** [comment]
Thanks for the responces.
@andrewtelnov I tried the code in the demo, but failed to have a new property in question/page.
```
Survey.JsonObject.metaData.addProperty("survey", "tag:number");
//add a property to the page object
Survey.JsonObject.metaData.addProperty("page", {name: "tag:number", default: 1});
//add a property to the base question class and as result to all questions 
Survey.JsonObject.metaData.addProperty("questionbase", {name: "tag:number", default: 0});
```
What may cause the problem?

@jasonracey Could you please clarify what do you mean by 

> "I found my custom field here survey.pages[0].questions[0].category" ?

**Comment by andrewtelnov** [comment]
@noorball Where do you put this code? It should be placed before creating the survey.

Thank you,
Andrew

**Comment by noorball** [comment]
@andrewtelnov This code is put as in the demo code. As we see it doesn't create survey object explicitly. 
```
Survey.Survey.cssType = "bootstrap";
Survey.defaultBootstrapCss.navigationButton = "btn btn-green";
//add a property to the survey object
Survey.JsonObject.metaData.addProperty("survey", "tag:number");
//add a property to the page object
Survey.JsonObject.metaData.addProperty("page", {name: "tag:number", default: 1});
//add a property to the base question class and as result to all questions 
Survey.JsonObject.metaData.addProperty("questionbase", {name: "tag:number", default: 0});
var editorOptions = { };
var editor = new SurveyEditor.SurveyEditor("editorElement", editorOptions);
```

```
<body>
    <div id="surveyContainer">
    <div id="editorElement"></div>
</div>
```
My problem is I don't have 'tag' property in my view like in the screenshot below :( 
![surveyjs-add-property](https://user-images.githubusercontent.com/3434216/31755004-588f3096-b4bd-11e7-8e14-17128ac63a7c.png)

**Comment by andrewtelnov** [comment]
@noorball Could you please create a demo in plunker or fiddle?
We have a lot of examples with adding properties and I have never seen this issue.

Thank you,
Andrew

**Comment by noorball** [comment]
@andrewtelnov Ahh, I fixed it. The problem occured because of adding the needless survey.jquery script.
    `<script src="https://surveyjs.azureedge.net/0.12.32/survey.jquery.js"></script>`
Once I removed it, everything worked like a charm.
Thanks!
