### ISSUE TITLE
Doesn't work example trigger-setvalue at surveyjs.org (except knockout)

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/surveyjs#235]
http://surveyjs.org/examples/jquery/trigger-setvalue.html

Doesn't work for react, jQuery, angular

**Comment by andrewtelnov** [comment]
@dmitrykurmanov it should be fixed now.

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
@andrewtelnov it is ok except vue js, we'll check it

**Comment by dmitrykurmanov** [comment]
I've opened specific Vue.js issue #250
