### ISSUE TITLE
Using Matrix single choice for scale questions 

### ISSUE THREAD

**Issue by harpsicord86** [surveyjs/surveyjs#236]
Hi there,

I've been looking into using survey.js for helping to generate surveys and this certainly does do a lot of stuff we are looking for!  However, I do have one question.

Is it possible to add another header row on top of the Matrix template as it would be useful to show what certain headers mean i.e. 0 - Not important, 5 - Very Important

Ideally something like this:
![image](https://cloud.githubusercontent.com/assets/12445814/22974942/9221ff3a-f37c-11e6-9b58-ed050123a485.png)

Hope this makes sense,

Steve

**Comment by andrewtelnov** [comment]
@harpsicord86 At the current moment the only way to do it, is using onAfterRenderQuestion event: https://github.com/surveyjs/surveyjs/issues/219, in options event variable you will have a question and element properties, where element is the html element associated with the question.
Unfortunately, there is no a demo yet. We may try to use this example as a demo for custom rendering.
You may try to use the custom css feature, here is [the demo](http://surveyjs.org/examples/jquery/survey-customcss.html) and create a style of table.th element.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@harpsicord86 We add markdown support into surveyjs. Here is the example of using markdown for your question: http://surveyjs.org/examples/jquery/survey-markdown-matrix.html
