### ISSUE TITLE
Can still press submit button when survey mode is set to 'display'

### ISSUE THREAD

**Issue by JonBetts** [surveyjs/surveyjs#237]
Not sure if this is just me, but when I set a survey to be read-only, all the survey inputs are disabled except the submit button. Pressing that in my application causes an issue, and I don't really want to have to deal with it server-side if I can help it.

Is this a known issue?

Thanks.

**Comment by andrewtelnov** [comment]
@JonBetts In fact, I just have not decided what to do. There should be an another flow:
 "End" button and onEndDisplay event. I was not sure about the button and event names and as result did nothing :-) 
By the way what is your flow?

Thank you,
Andrew

**Comment by JonBetts** [comment]
Hi Andrew,

I've created a pull request for this issue - I thought it might make it more clear to you what I mean :relaxed: It is #243. Basically I don't think the 'complete' button should ever show when you're viewing a survey in 'display' mode.
Let me know what you think.

Thanks,
Jon

**Comment by andrewtelnov** [comment]
@JonBetts :-) ok, for my flow hiding the button works as well. I have added the code for knockout and vue versions as well.

Thank you,
Andrew

**Comment by JonBetts** [comment]
Excellent. Thanks so much Andrew.

**Comment by dkoffler** [comment]
I am still seeing the "Complete" button when in display mode.

**Comment by andrewtelnov** [comment]
@dkoffler Could you please give us an example that shows the issue?
Here is [the example of display mode](https://surveyjs.io/Examples/Library/?id=survey-displaymode)
I have just checked for all platforms: angular2+, jQuery, react, knockout and vue.
It works as expected.

Thank you,
Andrew
