### ISSUE TITLE
Can not show data on IE 11

### ISSUE THREAD

**Issue by LeBaThuan** [surveyjs/surveyjs#239]
When I try with Angular 2 in the IE 11 (win 8.1) 
[http://plnkr.co/edit/OJkKlUn1oxzWYtnruXir?p=preview](http://plnkr.co/edit/OJkKlUn1oxzWYtnruXir?p=preview)
can not show the quesion

**Comment by tsv2013** [comment]
According to https://github.com/angular/zone.js/issues/316 we can not load polyfills before zone.
