### ISSUE TITLE
AllowRequired on matrix question not translated

### ISSUE THREAD

**Issue by nelero** [surveyjs/surveyjs#240]
In french, when we use AllowRequired, the error message is still in english
" Please answer questions in all rows."

Translation : "Toutes les lignes sont obligatoires"

**Comment by andrewtelnov** [comment]
@nelero The french translation was created some times ago and new strings have been added. Here is the  localization file: https://github.com/surveyjs/surveyjs/blob/master/src/surveyStrings.ts and here is the french translation: https://github.com/surveyjs/surveyjs/blob/master/src/localization/french.ts
For example, addRow and removeRow strings are not translated either. 

PS: I have added the translation for "requiredInAllRowsError".

Thank you,
Andrew
