### ISSUE TITLE
isVisible not working in IE and subsequent ordering issues

### ISSUE THREAD

**Issue by Ryidale** [surveyjs/surveyjs#242]
Hey, 
I have an issue with jquery version of surveyJs 0.12.0 'isVisable' in IE 11 (win 8.1).  All conditional fields are permanently hidden even when the correct options are selected. (This seems to work in firefox and chrome)

An example of the issues 
[http://plnkr.co/edit/4ckw4U35EMtSjeMlmbCv?p=preview](http://plnkr.co/edit/4ckw4U35EMtSjeMlmbCv?p=preview)

Another issue related to this is that the ordering of hidden fields after being displayed once is inverted.
An example of this using the link above would be: -
-  Select 'Application / Web' (note order of subsequent questions)
- Then change select to 'Database' 
- Finally revert option back to 'Application / Web' noting the new order.

**Comment by andrewtelnov** [comment]
@Ryidale indeed, it works in all browsers I have tried, except IE. We will see what is wrong here.

Thank you,
Andrew
