### ISSUE TITLE
Preview Mode

### ISSUE THREAD

**Issue by EminYasarturk** [surveyjs/surveyjs#247]
Hi everybody,

I have a question about preview mode not test mode. Can i add a button to TollBar , after the last 'li' element which has svd_actions classes. If i add this button, i wanna open a modal with ajax which contains questions. Maybe if i can add this option test mode can be useless.

**Comment by andrewtelnov** [comment]
@EminYasarturk Do you want to have a custom elements in Toolbar for editor? Am I right?

Thank you,
Andrew

**Comment by EminYasarturk** [comment]
@andrewtelnov 

![1](https://cloud.githubusercontent.com/assets/25570274/23105228/3b436a80-f6e4-11e6-9928-fa68db129e9f.png)


When i click Preview button, i will open this modal. 

![2](https://cloud.githubusercontent.com/assets/25570274/23105204/c69265d8-f6e3-11e6-9995-f8fa1d654854.png)

I embed Preview Button with jquery. Is there a function which is standartly.

**Comment by EminYasarturk** [comment]
This form language is Turkish. I forget change this and examples :)

'Geri Al' means Undo, Formu Kaydet means 'Save Form'

**Comment by andrewtelnov** [comment]
@EminYasarturk I believe you are looking the following functionality: https://github.com/surveyjs/editor/issues/49
Am I right?

Thank you,
Andrew

**Comment by tsv2013** [comment]
We've implemented toolbar customization functionality recently ([Version 0.12.10](https://github.com/surveyjs/editor/releases/tag/v0.12.10)). @EminYasarturk You can check [example "how to add custom button in the editor's toolbar to show test survey in the separate popup window"](http://editor.surveyjs.io/examples/toolbarcustomization.html).
