### ISSUE TITLE
checkbox and radio with colors

### ISSUE THREAD

**Issue by xibman** [surveyjs/surveyjs#254]
Hi all,

it could be interesting to use this lib : http://flatlogic.github.io/awesome-bootstrap-checkbox/demo/

to color checkbox or radio in survey

**Comment by andrewtelnov** [comment]
@xibman You may do it right now, using custom widget feature: http://surveyjs.org/examples/jquery/custom-widget-tagbox.html

You may add a new property "isAwesome:boolean", and use it in the isFit function.

Thank you,
Andrew

**Comment by SlowburnAZ** [comment]
@andrewtelnov , Interesting.  How, though, would one go about integrating something like iCheck (http://icheck.fronteed.com/) to style the checkboxes and radios?

**Comment by SlowburnAZ** [comment]
Also, I've noticed that the labels for checkboxes and radios don't have the 'for' attribute set.  So, if we wanted to style the checkboxes and radios purely with CSS, the technique of hiding the checkbox or radio itself wouldn't work, right, as making the label control the checkbox or radio element requires that the 'for' attribute be set?

**Comment by andrewtelnov** [comment]
@SlowburnAZ I have added in our TODO list the task to discuss using the "for" attribute.
And yes, we are going to make more examples with custom-widget feature. I personally want to make an example with select2. I have added the iCheck widget in our list of examples we have to create.

Thank you,
Andrew

**Comment by SlowburnAZ** [comment]
@andrewtelnov Awesome.  Thanks!  Would love to be able to use that library.

**Comment by andrewtelnov** [comment]
@SlowburnAZ About "for" attribute. I have looked at the code. I definitely had to do it early, so sorry for the delay.
We are using the following rendering:
<label>
 <input [radio or check] /> <span>Text for check or radio item</span> 
</label>

"for" attribute is needed when label is separated from the input. For example:
<label for="MyInputId">Text for check or radio item</label>
 <input [radio or check]  id="MyInputId"/> 

In our case, when input tag inside the label, "for" attribute doesn't do anything and doesn't provide any help.

PS: You may find interesting this discussion:  https://github.com/surveyjs/surveyjs/issues/281
We are going to show, how to use the most popular JavaScript widgets instead of the current rendering.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@SlowburnAZ Here is the example with icheck widget: http://surveyjs.org/examples/jquery/custom-widget-icheck.html

**Comment by SlowburnAZ** [comment]
@andrewtelnov In looking at the "renderAs", I could simply leave that as "standard", correct?  Meaning, I could not add the "icheck" renderAs property to metaData, not add the renderAs prop to the questions, and then in the "isFit" function, return true if renderAs = "standard", correct?

**Comment by SlowburnAZ** [comment]
@andrewtelnov I've run into a quirk with the Matrix questions and using iCheck:  If you select an answer for one of the matrix questions, all answers of that type are then selected for all questions in the matrix.

Is there any way to pass the actual Matrix question whose radio button was clicked into the "afterRender" function?  Seems that currently only the entire question's <div> element is being passed, so every input with the same value is being selected.

**Comment by andrewtelnov** [comment]
@SlowburnAZ Yes, you may do not use "renderAs" property, but use isFit as:
`isFit : function(question) { return question.getType() === 'radiogroup'; }`
So, it will use iCheck for all radiogroup questions.

Let us check, how does it work for matrix. We have not tried it yet.
@dmitrykurmanov Could you try it out?

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
@andrewtelnov ok

**Comment by dmitrykurmanov** [comment]
vue version: https://plnkr.co/edit/hTu6MYsWgObUUPmxfG1G?p=preview

**Comment by SlowburnAZ** [comment]
@dmitrykurmanov Much appreciated, sir.

**Comment by dmitrykurmanov** [comment]
@SlowburnAZ you are welcome!
