### ISSUE TITLE
Dynamic Matrix Dropdown JQuery Strange Behaviour

### ISSUE THREAD

**Issue by athad** [surveyjs/surveyjs#255]
I'm currently using the jQuery version and ran into a problem with the dropdowns randomly firing off, displaying old values, triggering changes on other dropdown rows and/or columns. 

See an example here: http://plnkr.co/edit/qg7dhMt76BIYWqaAJEc6?p=preview. Try changing the selected values in columns one or two. When I reduce to one dropdown and one row, the dropdown always selects the previously selected value. It's not simply a drawing problem, either, I checked the created DOM element in the console and it carries the old value. I tested this under both Chrome and Firefox. Let me know if I can provide other info.

**Comment by tsv2013** [comment]
Thank you, @athad, the problem is is rather clear for me. It's defenitely a bug, we'll fix it.

**Comment by dmitrykurmanov** [comment]
This bug is also in angular2, so it is preact.

**Comment by dmitrykurmanov** [comment]
So... we need just update preact and preact-compat versions :)
