### ISSUE TITLE
maximumRateDescription not Displaying

### ISSUE THREAD

**Issue by AndehWong** [surveyjs/surveyjs#256]
maximumRateDescription for the survey is not displaying correctly. The issue is evident on the example page as well. 

http://surveyjs.org/examples/react/real-productfeedback.html

Note that for the "satisfied" question, the minimumRateDescription shows, but the maximumRateDescription does not show.

**Comment by dmitrykurmanov** [comment]
@AndehWong this is bug. Thank you for reporting it!

**Comment by dmitrykurmanov** [comment]
@AndehWong it is fixed in master branch

**Comment by AndehWong** [comment]
Awesome, thanks a lot!
