### ISSUE TITLE
Issues with "isRequired" field for multipletext input

### ISSUE THREAD

**Issue by AndehWong** [surveyjs/surveyjs#257]
Hello, I'm having an issue, and I'm not sure if this is a bug or not. I'm trying to create a survey with a multipletext type question, and I have selected that isRequired: true. However, the fields can be left blank, and the user can submit the survey. Is this something that has not been implemented yet or is it a bug or do I need to change the JSON to suit the question?

**Comment by andrewtelnov** [comment]
@AndehWong I think we have to add isRequired property to the text item. I have added a new issue: https://github.com/surveyjs/surveyjs/issues/258
At the current moment, you may use the onValidateQuestion event: http://surveyjs.org/examples/jquery/validators-event.html

Thank you,
Andrew
