### ISSUE TITLE
Where do I exactly change the styling of the survey itself?

### ISSUE THREAD

**Issue by AndehWong** [surveyjs/surveyjs#259]
I'm wondering if it is possible to change the styling of the survey itself. In particular, I want to make it possible to add more spacing between questions, and maybe change the size of the text input boxes for a few of my questions. I'm currently using React and React-Bootstrap, and I'm fairly new to React.

**Comment by andrewtelnov** [comment]
@AndehWong Please take a look at this demo: http://surveyjs.org/examples/react/survey-customcss.html
You will have to change the myCss to 
```
var myCss = {
        row: "YourClassNameWithNewSpacing"
   };
```

Thank you,
Andrew

**Comment by AndehWong** [comment]
Awesome, I didn't see that row what editable in the css. Thank you!

Last question, is it possible to stylize specific choices (like a specific radio choice)?

**Comment by andrewtelnov** [comment]
@AndehWong Unfortunately there is no easy way to do it. Thre is onAfterRenderQuestion event that passed question and htmlElement as properties in options parameter:

```
survey.onAfterRenderQuestion.add(function(survey, options) {
  var q = options.question;
  if(q.name != "myName") continue;
  var el = options.htmlElement;
 //Correct the DOM
});
```

The following thread maybe interesting for you as well: https://github.com/surveyjs/surveyjs/issues/254

Thank you,
Andrew
