### ISSUE TITLE
Some files seem to miss in survey-knockout@0. 11.0

### ISSUE THREAD

**Issue by sufuf3** [surveyjs/surveyjs#262]
Hi @surveyjs , 
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs). We are going to host this library.
But there is only css file in the v0.11.0 of survey-knockout form npm.

So, is there any files that the 0.11.0 version of the survey-knockout should include? 
eg. `survey.ko.js`,   `survey.ko.min.js`

If you have any suggestions, please let me know.

Thank you.

[cdnjs/cdnjs#10153](https://github.com/cdnjs/cdnjs/pull/10153)

**Comment by andrewtelnov** [comment]
@sufuf3 Yes, indeed the npm survey-knockout v0.11.0 is corrupted. There is no way to update the packages in npm since February 2014. 

I may share these files to you, if you need them for some reason.

Thank you,
Andrew

**Comment by sufuf3** [comment]
I need them to make should that the files of v0.11.0 in cdnjs is work. 
So please share these files. 
Thank you.

**Comment by tsv2013** [comment]
@sufuf3 I've added corresponding packages.zip file to the 0.11.0 release, you can get them from https://github.com/surveyjs/surveyjs/releases/tag/0.11

**Comment by sufuf3** [comment]
@tsv2013 Thank you! 
I will host this library ASAP.
