### ISSUE TITLE
is question.hasTitle functional?

### ISSUE THREAD

**Issue by bennettrogers** [surveyjs/surveyjs#263]
I can see that rendering of the question title is conditional on the `question.hasTitle` property, but setting that to `false` in the survey JSON doesn't seem to change anything. I'm trying to follow the flow of the parameters, and it looks like hasTitle is just hardcoded to `false` in the questionBase, and hardcoded to `true` in the question class itself.

Is the intention that this property can be used to toggle rendering of individual question titles?

**Comment by andrewtelnov** [comment]
@bennettrogers Yes, it is a virtual property. It returns false in the base question and html question. It returns true in all other questions.
As you may see there is no title property in the html question, and base question.

Thank you,
Andrew

**Comment by bennettrogers** [comment]
Gotcha. I was hoping to use it to disable rendering of the title for individual questions, but I've figured out a CSS solution that works for now. It's not pretty, but it works!

**Comment by andrewtelnov** [comment]
@bennettrogers If you give us a good scenario, where this functionality is required, then we will implement it. It is not that hard to make hasTitle property writable with default value and make it a JsonProperty. Probably there is not need to change the rendering since hasTitle is already there.
The only question. Should we count this questions or not? html question doesn't change  numbers (no) of other questions.
Anyway, if you give us a scenario and we can see it makes sense, then we will implement it.
I hate unpretty code :-)

Thank you,

Andrew

**Comment by bennettrogers** [comment]
To be honest, the reason I'm even trying to hide the title in the first place is to approximate a multi-text type of control. The built-in multitext question type seems harder to work with (tables), so I was instead putting two text inputs side-by-side on the same line, and trying to merge them into a pretty "combined" input. Something like the height and blood pressure controls in the attached screenshot.

Ultimately I think the right solution here would be a fully custom question component, but it doesn't appear that's possible in Vue yet, so I was trying to get creative!

![image](https://cloud.githubusercontent.com/assets/933251/23342686/a62c79de-fc13-11e6-8a05-105ad45c4e8e.png)

**Comment by andrewtelnov** [comment]
@bennettrogers I think it is possible.
I guess you have seen [the startWithNewLine property](http://surveyjs.org/examples/vue/survey-startwithnewline.html).
and nothing stops you to use a custom widgets for Date of Birth, Height and Blood pressure: http://surveyjs.org/examples/vue/custom-widget-datepicker.html

Thank you,
Andrew

**Comment by bennettrogers** [comment]
Yep, I'm using startWithNewLine to get the 2 textboxes to display together, then using CSS to remove the space between them.

Thanks for the recommendation - I'll take a look at using custom widgets instead. Is there more documentation for them somewhere?

**Comment by andrewtelnov** [comment]
@bennettrogers Unfortunately we do not have any documentation at the current moment. We will work on it later.
If you have any question about custom widgets, just ask them here and we will answer them.

Thank you,
Andrew
