### ISSUE TITLE
Add image type  to choices

### ISSUE THREAD

**Issue by ojpeters** [surveyjs/surveyjs#264]
I really like the surveyjs but it appears like If I create a question that needs user to choice between some options, instead of having text  choices, Can I have them choice image(s)

. I would like to have the user choice answer by clicking on an image. Any examples will help

![image_options](https://cloud.githubusercontent.com/assets/7523661/23336739/8ea8f17e-fba6-11e6-9ab6-61c8c04a9d8f.PNG)

**Comment by andrewtelnov** [comment]
@ojpeters At the current moment, you may do it by using custom-widget feature only: http://surveyjs.org/examples/jquery/custom-widget-tagbox.html

We will discuss image question. Probably we will implement it in the future.

Thank you,
Andrew

**Comment by ojpeters** [comment]
Hi Andrew,
Is there any further documentation on the choiceByURLproperty? I cant seem to connect to a local url like ./img/berries.png
Or are you saying that its not possible yet to list images as a choice. I will appreciate any little code snippet no matter how rough. Ability to choose by image(radio or checkbox) is holding me from using the awesome tool in my project.I couldn't get my head around how to get around it.

**Comment by andrewtelnov** [comment]
@ojpeters It was created for another purpose. Here is [the demo] (http://surveyjs.org/examples/jquery/questiontype-dropdownrestfull.html).
To fill checkboxes, radiogroup and dropdown with choices/options from restful API.

Thank you,
Andrew

**Comment by mellogarrett** [comment]
I would also love to be able to use images, but to implement a custom Rating implementation with clickable stars like so: 

<img width="281" alt="screen shot 2017-02-27 at 2 22 54 pm" src="https://cloud.githubusercontent.com/assets/9908831/23375969/5834b2d8-fcf8-11e6-8f85-e384ac9f750b.png">

**Comment by andrewtelnov** [comment]
@mellogarrett  I have added this rating implementation into out TODO list. We will implement it by using the custom-widgets.

Thank you,
Andrew

**Comment by mellogarrett** [comment]
Awesome, thanks @andrewtelnov. Being able to do half-stars would be great as well.

**Comment by andrewtelnov** [comment]
@mellogarrett The demo with bar ratting widget was added: http://surveyjs.org/examples/jquery/custom-widget-barrating.html

**Comment by mellogarrett** [comment]
1) Destroy the widget first thing in the `afterRender` function with:  `$(el).find('select').barrating('destroy');` to allow re-rendering of the widget on `previous` as noted by @tsv2013 in #281 

2) remove the space after `isFit` in the line `isFit : function(...`

Thanks @andrewtelnov !

**Comment by dmitrykurmanov** [comment]
@ojpeters we've implemented select-image custom widget: http://surveyjs.org/examples/knockout/custom-widget-image-picker.html
