### ISSUE TITLE
[Vue] text inputs do not remember their value across page changes

### ISSUE THREAD

**Issue by bennettrogers** [surveyjs/surveyjs#265]
It looks like f6bbca410b73ed17d28d8e1364678cc0b5e7a219 breaks the ability of text inputs to store their value when changing pages. I'm looking into how to fix it without re-breaking the trigger functionality, but submitting this anyway in case you fix it faster. :)

**Comment by andrewtelnov** [comment]
@dmitrykurmanov and @tsv2013 Guys, could you please take a look?

Thank you,
Andrew

**Comment by bennettrogers** [comment]
Sorry, got distracted by a yarn caching issue (and lunch). I think #266 should fix it? Yay for one-line fixes.

**Comment by tsv2013** [comment]
@bennettrogers We are working on the vue components enhancements right now. Looks like Vue can reuse existing components w/o remount them, just updating properties. We're going to watch `question` property of the compoent to update initial value and keep track on model changes. You are welcome to share your experience with Vue!

**Comment by bennettrogers** [comment]
Great! I'm glad to hear that Vue is getting some love. I was excited when I saw that you guys released a Vue version of SurveyJS.

I'm happy to share what I can (and will continue to submit pull requests when I find things I can help with), but I'm pretty new with Vue myself!

**Comment by tsv2013** [comment]
Thank you, @bennettrogers!
