### ISSUE TITLE
Make SurveyJS Knockout compatible with it being used as a component.

### ISSUE THREAD

**Issue by emilianionascu** [surveyjs/surveyjs#268]
When using SurveyJS as a knockout component, it fails because it tries to access the $root view model to get values. Can it be refactored to support a parent context and not call applyBindings by itself?

**Comment by tsv2013** [comment]
Sure, it can. We need to discuss time estimation with @andrewtelnov and @dmitrykurmanov.

**Comment by tsv2013** [comment]
It's a good proposal. We've added corresponding card to our todo list.

**Comment by emilianionascu** [comment]
Thank you for the fast response.

**Comment by tsv2013** [comment]
I've got rid of $root in the 813b3af61db08806af76f67c695420f1ef4dfa8c commit. @emilianionascu , you can try it in master brunch or wait for the nearest update (in a week I think).

**Comment by emilianionascu** [comment]
Thank you for taking the time to implement this. I've tried it and now it's complaining about css.root. After adding a fake css.root to the scope it complains about a lot of other things so I guess that the model doesn't get set properly. Do you think you have time to look into this? Perhaps we can talk on gitter and I can explain what I am trying to use the library for.

**Comment by tsv2013** [comment]
Could you provide me your JSON to reproduce your issue locally? Probably I missed somthing.

**Comment by emilianionascu** [comment]
Perhaps a flag that says that if the survey is inside a knockout context already, then don't call applybindings as it will be called by the parent context anyway. Something like "survey.isComponent = true" maybe?

**Comment by tsv2013** [comment]
@emilianionascu Thank you for provided sources!
I've implemented KnockoutJS <survey> component and tested it in your scenario.
To use it you need:
- comment render function call:
`   //model.render('surveyElement');`
- use <survey> component in the markup, e.g.:
```
<div id="parentElement" data-bind="css: otherData.someStyle">
    <survey params="survey: model"></survey>
</div>
```
- your binding context, of course, should contain `model` to pass to the component
```
      function ParentViewModelExample() {
          ..... // some code
         const model = new Survey.Model(json);
          ..... // some code
          return {
              model: model,
              otherData: { someStyle: "some-style-name" }
          };
       }
```

I'll add corresponding example to our site.

**Comment by emilianionascu** [comment]
Thank you! I will give it a spin! You rock!

**Comment by emilianionascu** [comment]
Works like a charm! Thank you again!

**Comment by emilianionascu** [comment]
Can you think of any reason why the component would not render itself properly at times? It randomly does that and instead of replacing ```<survey params="survey: model"></survey>``` with the survey DOM it just stays like that.
