### ISSUE TITLE
Question about having two seperate onComplete screens

### ISSUE THREAD

**Issue by AndehWong** [surveyjs/surveyjs#269]
Hello, I was wondering if it was possible to have two possible survey completed screens. As of right now, I know it is possible by:
survey.completedHtml = "<html goes here">;

for one survey completion screen. Is it possible to have a trigger that shows a separate completed screen depending on how the user answers their questions?

**Comment by andrewtelnov** [comment]
@AndehWong Unfortunately, there is no such a trigger at the current moment.
You have to create it or use survey.onValueChanged event, [here is a demo](http://surveyjs.org/examples/jquery/survey-data.html) and change completedHtml property on this event.

Thank you,
Andrew
