### ISSUE TITLE
wysiwyg editor?

### ISSUE THREAD

**Issue by fredle** [surveyjs/surveyjs#27]
Any chance of a wysiwyg editor? I have implemented one using tinymce and this binding handler.

https://github.com/michaelpapworth/tinymce-knockout-binding

**Comment by andrewtelnov** [comment]
Are you talking about this?
http://surveyjs.org/builder/
https://github.com/andrewtelnov/surveyjs.editor

Thank you,
Andrew

**Comment by fredle** [comment]
No, like a comment but accepts html. 

I managed to implement it duplicating the 'comment' files and changing the binding handler from "value" to wysiwyg. but it would be nice to have one in the master branch.

**Comment by andrewtelnov** [comment]
I am afraid, I missed something.
Should I look closely at: https://github.com/michaelpapworth/tinymce-knockout-binding
or do you have a surveyjs branch that may look at?

**Comment by fredle** [comment]
Looks like I am not authorised to create a branch..

**Comment by andrewtelnov** [comment]
https://github.com/andrewtelnov/surveyjs/tree/knockout-binding

**Comment by andrewtelnov** [comment]
I will accept all your pull requests to this branch.

**Comment by fredle** [comment]
Sorry, I am not too familiar working with github, am I doing anything wrong, or is it a permissions issue for the project

$ git push origin origin/knockout-binding
Username for 'https://github.com': fredle
Password for 'https://fredle@github.com':
remote: Permission to andrewtelnov/surveyjs.git denied to fredle.
fatal: unable to access 'https://github.com/andrewtelnov/surveyjs.git/': The requested URL returned error: 403

**Comment by andrewtelnov** [comment]
No problem.
You may fork my repo. You will have the full copy of my repo under your account. You may modify the new repo as you wish.
The idea, that you modify the "knockout-binding" branch.
You may commit from your repo to my (original) repo by doing pull requests. As I told, I will accept all your pull requests to the knockout-binding branch as soon as I see a request. It will synchronize the branch in two repos (my and yours).

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
I have accepted the request. Now you should convince me to include it into the master branch :-)
I do not see any harm to have this. 
I will move the code to the knockout version only: https://github.com/andrewtelnov/surveyjs/tree/master/src/knockout. So reactjs doesn't have this code. 
Do you have any example, so I understand what it is? :-)

Thank you,
Andrew

**Comment by xibman** [comment]
A simple editor: https://www.froala.com/
https://github.com/helpbase/vue-froala
https://github.com/froala/vue-froala-wysiwyg

**Comment by andrewtelnov** [comment]
@xibman Here is the example of implementing editor by using custom widgets: https://surveyjs.io/Examples/Library/?id=custom-widget-ckeditor

Thank you,
Andrew
