### ISSUE TITLE
[Vue] Do custom properties work on questions in Vue?

### ISSUE THREAD

**Issue by bennettrogers** [surveyjs/surveyjs#270]
I'm trying to follow the [guide](http://editor.surveyjs.io/examples/addproperties.html#code) to add custom properties to my question in Vue, but I'm not seeing  them appear. The guide only has a tab for Knockout for this feature, but #234 indicates that it's also available for React. Are these new properties accessible in Vue as well?

**Comment by andrewtelnov** [comment]
@bennettrogers It should work for all versions.
jsonProperties/objects are implemented in the core/platform independent part.
You have added a new property, add it to the json and it doesn't there, am I right?

Thank you,
Andrew

**Comment by bennettrogers** [comment]
That's right. I have this in my app where I import the Survey module:
```
Survey.JsonObject.metaData.addProperty('questionbase', {
  name: 'tag:number', default: 0,
});
```
I'm using the Vue debug tools and inspecting the question instance, and I don't see a "tag" property. I'm also trying to console.debug the object, but it's not showing up there either.

I have done some console.log debugging from inside the SurveyJS files themselves, and the property is definitely getting added to the model, so I'm not sure where it's getting lost.

**Comment by andrewtelnov** [comment]
The property itself doesn't show in the questionbase. 
This code tells surveyjs Json serialization/deserialization code to save/restore this property in/from json, if it is not null/undefined and doesn't equal to 0.

Further, SurveyJS Editor will show this property in the Property Editor, and survey creator will be able to see and modify it.

Do you expect that SurveyJS serialization code would set tag property to 0 to all questions by default? That probably makes sense.

Thank you,
Andrew

**Comment by bennettrogers** [comment]
Ah, that makes sense! I didn't even consider that the property wouldn't appear unless I added it to the JSON data for the survey. As soon as I do that for a specific question, my custom property shows up as expected! Thank you!

For custom properties that have a default value, yes, I think it would make sense for them to be set on all questions. If no default value is specified (or implied), then maybe it wouldn't make sense to create the property.

This can be closed, unless you'd like to leave it open regarding the setting of default properties?

**Comment by andrewtelnov** [comment]
If somebody has a similar problem, I will think about implementing setting default value for the custom properties. It will require to write some amount of code, since making a loop for all properties and check if this property set or not for every object, may kill the performance.

Thank you,
Andrew

**Comment by davebradley14620** [comment]
I have the same exact issue.   It would be great to have that in there.   Thank you.   Also, if I add a custom property, am I no longer able to edit my JSON using the survey builder at dxsurvey?

Thanks.
Dave

**Comment by andrewtelnov** [comment]
@davebradley14620 Do you mean you need an ability to set the default value on creating the survey? There is now [survey.onQuestionAdded event](http://surveyjs.org/docs/api_surveymodel.html#onQuestionAdded). You may use it to set the default value. I may create an example on plunker if you need one.

About dxsurvey or surveyjs.org builder/editor. Unfortunately there is no such functionality. We would have to run your JavaScript to customize the library.
We may add a declarative way to modify the editor (add/remove properties, add new question types), but it is not on our radar at the current moment. Here is what we are working at the current moment: https://github.com/surveyjs/surveyjs/issues/487#issuecomment-313761432

The only way, is to use our editor as a library on your web site, but unfortunately, it is not a free for non commercial project. 

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@bennettrogers @davebradley14620 I am re-writing the way we are working with properties. 
As result custom properties now get/set value using getPropertyValue and setPropertyValue.
The default value is returned if the default value is set.
The onPropertyChanged event is fired.
Vue is observed the propertyHash value, where all properties values are stored.

Thank you,
Andrew

**Comment by semiomant** [comment]
you still have to use "Survey.JsonObject.metaData.addProperty" or the custom property will be serialized away in the library. And its really frustrating if this is only documented in 2 year old issue.

**Comment by andrewtelnov** [comment]
@semiomant I am not sure I follow you. The issue has been closed two years ago. What issues do you have with custom property + vue.

Thank you,
Andrew
