### ISSUE TITLE
Could I able to assign IDS for each field - I am using ReactJS

### ISSUE THREAD

**Issue by svemula09** [surveyjs/surveyjs#271]

**Comment by andrewtelnov** [comment]
@svemula09 Sure, you may add a new property to any question or to all questions:
Here is the example for adding IDS field to all questions:
Survey.JsonObject.metaData.addProperty("questionbase", {name: "ids"}); 
Here is the complete document [about adding custom properties](http://editor.surveyjs.io/examples/addproperties.html#code).

Thank you,
Andrew
