### ISSUE TITLE
Is there a property to not show  Thank you for completing the Survey! Page

### ISSUE THREAD

**Issue by svemula09** [surveyjs/surveyjs#272]

**Comment by andrewtelnov** [comment]
@svemula09 There is no such a property right now. You may make the survey invisible using onComplete event. Just make your div where survey is rendered invisible.
However, you are right, it makes sense to add a property (show Thank you page (default) or make the survey invisible). I've added this request into our TODO list.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@svemula09 I have added this functionality: https://github.com/surveyjs/surveyjs/issues/283
It will be in the next update.

Thank you,
Andrew
