### ISSUE TITLE
Rating - minimum/maximumRateDescription

### ISSUE THREAD

**Issue by mellogarrett** [surveyjs/surveyjs#276]
I am using Bootstrap for styling. 

Can we move these descriptions out of the button and instead put it under (or above) the button on each end of the spectrum?

Ex:
<img width="461" alt="screen shot 2017-03-01 at 2 06 03 pm" src="https://cloud.githubusercontent.com/assets/9908831/23476278/4537f172-fe88-11e6-9655-c324c7f7e171.png">

**Comment by dmitrykurmanov** [comment]
@mellogarrett, Hello! Thanks for your interest! It is not easy to customize existing rating as you want. But you may use "custom-widget" conception. And do whatever you want. We've created an jquery example for you:
https://plnkr.co/edit/PQd56O4jsFpLomOb5I1Q?p=preview could you check it please? 
_we can implement this example for any supported framework_

As alternative you may try to use matrix with single row, for example:
http://plnkr.co/edit/G9RzkELFuhG6ooeyLn3D?p=preview

**Comment by dmitrykurmanov** [comment]
Here is all examples of this widget:

jquery: https://plnkr.co/edit/PQd56O4jsFpLomOb5I1Q?p=preview
angular:  https://plnkr.co/edit/1rLpmX2FU32rbiW3vt0q?p=preview

**Comment by dmitrykurmanov** [comment]
please also see https://github.com/surveyjs/surveyjs/issues/281
