### ISSUE TITLE
Adding options to the custom widgets?

### ISSUE THREAD

**Issue by alexmc6** [surveyjs/surveyjs#277]
(Probably just a support request)
I like the fact that I can use the jQuery Datepicker widget to help answer date questions, but the returned value is in the US format and my app is exclusively for UK users. 

I beleive that the date picker plugin has an "altFormat" where I can specify, for example, "dd-mm-yyyy" but I don't see where to specify that sort of option in Survey.JS (Reference http://api.jqueryui.com/datepicker/#option-altFormat )

Can we pass options to custom widgets yet?

Thanks

**Comment by andrewtelnov** [comment]
@alexmc6 sure, you may add a new property:
`Survey.JsonObject.metaData.addProperty("text", {name: "altFormat"});`
then use it on afterRender:
afterRender: function(question, el) {
...
//if question altFormat is set use it or use the default value.
var q_altFormat = question.altFormat ? question.altFormat : "dd-mm-yyyy";
//set q_altFormat to the widget.
...
}

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@dmitrykurmanov Let's modify our datepicker demo and add this option.

**Comment by alexmc6** [comment]
Thanks for the swift response. I will try this out and report back on how it goes for the next person with the same problem.
