### ISSUE TITLE
Any Thoughts of Provisioning skip functionality just like on Complete which can be invoked from any page

### ISSUE THREAD

**Issue by svemula09** [surveyjs/surveyjs#282]
I am Using ReactJS

**Comment by andrewtelnov** [comment]
@svemula09 I am sorry, I do not quite understand your suggestion :-(
Could you please describe it in more detail?

Do you want to have a trigger that may skip visible pages and go to particular page directly? 

Right now, question and page objects have two properties: visible and visibleIf (expression).
If visible is false or visibleIf returns false, then question/page is invisbile.
If page invisible or there is no visible question on the page, then the page is skipped.

Do you have any particular reason why you could not use visible/visibleIf properties? 
If you have a scenario that give us a reason to implement this gotoPage trigger functionality, it would be great if you share it here.
We want to make surveyjs easy to use, from one side, but from another side, we do not want to make it over-complicated. 
It looks to me, that you are asking for a duplicate functionality. I may be wrong. I may do not understand your request at all. Please provide us with more info.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
No reply in several months. I am closing the issue.
