### ISSUE TITLE
Do not show Completed Page

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#283]
Add showCompletedPage boolean property
if showCompletedPage is true (the default value) the completed page is shown on survey completing.
if showCompletedPage is false - the survey renders nothing on survey completing.

**Comment by andrewtelnov** [comment]
The example is updated: http://surveyjs.org/examples/jquery/survey-options.html

**Comment by benirose** [comment]
Sorry to revive this old issue, but is it possible to not display a blank page if you chose not to display the completed page? I just want it to continue displaying the last page while it saves.

**Comment by tsv2013** [comment]
You can use the `completedHtml ` property:
```JS
survey.completedHtml = "<span></span>";
```
Here is the working sample - https://plnkr.co/edit/q3p9eauZItqiAOMGwHcf?p=preview
And here is the documentation - https://surveyjs.io/Documentation/Library/?id=surveymodel#completedHtml

**Comment by seawave23** [comment]
Is there a possibility to just display the survey again (so completely skip this page)?

**Comment by andrewtelnov** [comment]
@seawave23 Sure, here is the code:
```
survey.onComplete.add(function (result) {
  survey.clear();
});
```
and [example](https://plnkr.co/edit/lHVEX6rfXFrQY2w626Sp?p=preview)

**Comment by samuelwx** [comment]
Is is possible to change just the survey mode to "display"? So the questions are still displayed but not editable.

**Comment by andrewtelnov** [comment]
@seawave23 ```survey.mode = 'display';``` Here is [the example](https://surveyjs.io/Examples/Library/?id=survey-displaymode)

PS: You are asking a question that unrelated to the original issue and this issue is closed two years ago.

Thank you,
Andrew

**Comment by samuelwx** [comment]
@andrewtelnov What I want is for the completed page not to be displayed after the user submits. Instead the question should remain displayed but become uneditable. I can't get that behavior with any of the examples above. Thanks!

**Comment by mjhoefer** [comment]
@samuelwx did you end up making an issue and getting it resolved? I have the same issue:

"Instead the questions should remain displayed with the user's answers but the survey become uneditable."

I would appreciate a link to how to do this! Thank you!

**Comment by gavin771** [comment]
Was able to accomplish with the following config.

```

 const surveyComplete = useCallback((sender: any) => {
    survey.clear(); // This seems to do the trick
    saveSurveyResults("https://your-web-service.com/" + SURVEY_ID, sender.data);
  }, []);

  survey.onComplete.add(surveyComplete);

...

<Survey 
     model={survey}
     // showCompletedPage={false} // this doesn't seem required
/>

```

**Comment by gavin771** [comment]
The documentation for the `clear` function pretty much outlines how it works, and it's exactly what is needed :)

```javascript
/**
 * Resets the survey [`state`](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#state) and, optionally, [`data`](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#data). If `state` is `"completed"`, it becomes `"running"`.
 * @param clearData *Optional.* Specifies whether to clear survey data. Default value: `true`.
 * @param goToFirstPage *Optional.* Specifies whether to switch the survey to the first page. Default value: `true`.
**/
```
