### ISSUE TITLE
progressText "Page {0} of {1}" - attribute to change the text in progress bar

### ISSUE THREAD

**Issue by cnx90** [surveyjs/surveyjs#284]
Hello,

I am refering to the progressText  - text that is appearing on the progress bar. All the values for different languages / locales are stored in the source survey.js file. Sometimes - especially in the beginning of the survey, the progress bar is to narrow to show the full text properly. I can always change the text values in the source file - but... 

Could it be possible to modify the text this not only in the source file - but as an attribute in the html - like for pageNextText: "text value for next button", pagePrevText: text value for prev button". 
In the same way I would like to modify progressText.

Best,
cnx

**Comment by andrewtelnov** [comment]
@cnx90 Unfortunately there is no such a property yet. However, this string is localized and you may change the localization string: Survey.surveyStrings.progressText = "Page {0} of {1}";
Here is more information about localization: http://surveyjs.org/examples/jquery/survey-localization.html

Thank you,
Andrew

**Comment by rivettp** [comment]
How about another mechanism to address the lack of visibility of the complete text when the progress bar has not advanced sufficiently? It can be a real problem especially on narrow devices such as phones. In fact it made us abandon the progress bar completely. Shrink the font size? Or maybe not display the text **within** the bar at all?

**Comment by nathanvoller** [comment]
I've been facing these issues recently too, and agree the text can't be seen in full if the survey has not progressed far enough.

Had a quick play with the css to get around this, as shown, but its not perfect. 

JavaScript
`Survey.defaultBootstrapCss.progressBar = "bar-custom";`

CSS
`.bar-custom span {
  white-space: nowrap;
}`

**Comment by andrewtelnov** [comment]
@cnx90 @rivettp @nathanvoller Hi all, I have fixed the issue in the following way:
Bootstrap .progress-bar style sets width to 0. Before bind the progress div to width in %.
Now, I am setting width to auto and set the min-width in %. As result the progress background display in % from done or by text content.
I guess it solves the issue.

Thank you,
Andrew
