### ISSUE TITLE
Angular and JQuery versions - Random settting of dropdown values (with plunkr)

### ISSUE THREAD

**Issue by ltex** [surveyjs/surveyjs#285]
I've forked the Angular plunkr to demonstrate. See http://plnkr.co/edit/heUR0cEUNGEbfMECuXWK?p=preview

To demonstrate I've just changed the radiogroup input types to dropdown.

Navigating between pages ie navigate back and forwards a few times between pages produces the effect of randomly selecting a dropdown choice.

I've checked this out with the jquery version and the same behaviour applies.

**Comment by dmitrykurmanov** [comment]
@ltex this is a bug. Thanks!

**Comment by dmitrykurmanov** [comment]
@ltex it is fixed now in 0.12.3 version. Could you check it please?
