### ISSUE TITLE
Cannot set a comment input value before rendering

### ISSUE THREAD

**Issue by andradobritoiu** [surveyjs/surveyjs#288]
I'm creating a survey model, using knockoutjs, and my code looks something like this:
 `var myObject =  {
            title: '',
            questions: myArray.map((item) => {
                return {
                    type: 'radiogroup',
                    name: item.Id,
                    title: item.Name,
                    colCount: Math.min(colCount, 5),
                    choices: item.choices.map((choice) => {
                        return {
                            value: choice.Id,
                            text: choice.Name
                        };
                    }),
                    commentText: 'Comment',
                    hasComment: true,
                    hasOther: false,
                    comment: 'this is my comment'
                };
            })
        };
 var surveyModel = new survey.Model(myObject));`

The value that i set in the comment doesn't bind to the koComment observable. If I use the `setComment` function eg `question.setComment('this is my comment')` then it binds correctly. Am I missing something?

**Comment by tsv2013** [comment]
@andradobritoiu  I'm sorry for delayed answer!

```
    var myObject1 = { title: '',
        questions: [
            { type: "radiogroup", name: "price to competitors",
                title: "Compared to our competitors, do you feel the Product is",
                choices: ["Less expensive", "Priced about the same", "More expensive", "Not sure"], hasComment: true, commentText: 'Comment', hasOther: false
            }
        ]
    };
    var model = new Survey.Model(myObject1);
    model.data = { "price to competitors-Comment": 'this is my comment' }

```

You can set initial comment value via `data` property of the model, as shown above.
The key name -  `price to competitors-Comment` consists of two parts - question name ("price to competitors") and question comment suffix - "-Comment".

**Comment by andrewtelnov** [comment]
There is no followup for over 3 months. I am closing the issue.
