### ISSUE TITLE
Add question properties with name and title

### ISSUE THREAD

**Issue by ZenHiro** [surveyjs/surveyjs#290]
Hi, I'm on researching this useful survey framework. I have a problem when adding property for question, as example: 

`Survey.JsonObject.metaData.addProperty("page", {name: "tag:number", default: 1});`
I want to add a property "Tag", but I want that show up in view with a title in my current language (Japanese), how can I do that? Thanks.
`Survey.JsonObject.metaData.addProperty("page", {name: "tag:number", title:"Insert_here" ,default: 1});`

**Comment by andrewtelnov** [comment]
@ZenHiro Are you talking about editor? 
There is no title attribute in JsonProperty object at the current moment. Probably it is a good idea to have it.
I guess, you have done the japanese localization for defaultStrings object: 
https://github.com/surveyjs/editor/blob/master/src/editorLocalization.ts

`editorLocalization.locales["jp"] = japaneseStrings; //your translation of defaultStrings object.`

In this case you have to add into your string objects your tag property:
`japaneseStrings.p.tag = "Your tag property in Japanese";`


PS: If you have translated the survey localized strings, it would be great to have it here: https://github.com/surveyjs/surveyjs/tree/master/src/localization

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@ZenHiro I have added a editor localization demo: http://editor.surveyjs.io/examples/localization.html#code
Here is the survey js localization demo: http://surveyjs.org/examples/jquery/survey-localization.html

**Comment by andrewtelnov** [comment]
There is no reply for several months. I am closing the issue.
