### ISSUE TITLE
matrixdymanic knockout doesn't show comment field

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/surveyjs#292]
http://surveyjs.org/examples/knockout/questiontype-matrixdynamic.html here is two comment fields instead of three

![d25b23ee3c](https://cloud.githubusercontent.com/assets/22315929/23889798/e1fab118-089f-11e7-981a-e2f2a85b623d.jpg)

**Comment by tsv2013** [comment]
Fixed with #293
