### ISSUE TITLE
Pre-populate with values?

### ISSUE THREAD

**Issue by dsteinbach** [surveyjs/surveyjs#294]
I went through the docs and issues and could not find my answer but does SurveyJS allow a way to pre-populate the form values? For instance, if I save the user's response to a db and later the user wants to make changes to their survey answers...

Thanks and sorry if this was clearly stated somewhere.

**Comment by andrewtelnov** [comment]
@dsteinbach You have to set the survey.data property:
`mysurvey.data = {myQuestionName1: value1, myQuestionName2: value2, ...};`
or 
`mysurvey.setValue("myQuestionName1", value1);`
Here are two demos: 
[Get/Set Survey Data](http://surveyjs.org/examples/jquery/survey-data.html)
[Survey in Display Mode](http://surveyjs.org/examples/jquery/survey-displaymode.html)
For the last demo, just comment this line, to make the survey editable (default mode):
`survey.mode = "display";`

Thank you,
Andrew

**Comment by dsteinbach** [comment]
Thank you very much

**Comment by buckelieg** [comment]
The http://surveyjs.org/examples/jquery/survey-data.html link is broken :(

**Comment by andrewtelnov** [comment]
@dsteinbach The correct links are:
[Get/Set Survey Data](https://surveyjs.io/Examples/Library/?id=survey-data)
[Survey in Display Mode](https://surveyjs.io/Examples/Library/?id=survey-displaymode)

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
@buckelieg  hello! Now you can find this examples here: 
[Get/Set Survey Data](https://surveyjs.io/Examples/Library/?id=survey-data&platform=jQuery&theme=default) 

[Survey in Display Mode](https://surveyjs.io/Examples/Library/?id=survey-displaymode&platform=jQuery&theme=default)
