### ISSUE TITLE
"cannot read property 'fn' of undefined"

### ISSUE THREAD

**Issue by jnicholea** [surveyjs/surveyjs#296]
We've followed every step you outlined for setting this up, but we keep getting this error. I'm not very experienced, but it seems like the issue is with a line of code in your survey.jquery.min.js and that is preventing everything else from functioning. (We can't get anything to display on the page). 

![Uploading Screen Shot 2017-03-15 at 4.53.51 PM.png…]()

**Comment by andrewtelnov** [comment]
@jnicholea Unfortunately the image is not uploaded correctly. Could you please check that jQuery library is loaded. It should be used before survey.jquery.min.js?
You should have something like this:
```
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>        
<script src="https://surveyjs.azureedge.net/0.12.3/survey.jquery.min.js"></script>
```
Thank you,
Andrew

**Comment by tavakyan** [comment]
Not sure if its related, but I have an issue with the vue client:

```
Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.n [as b] (survey.vue.min.js:6)
    at survey.vue.min.js:20
    at Object.defineProperty.value (survey.vue.min.js:20)
    at t (survey.vue.min.js:6)
    at Object.<anonymous> (survey.vue.min.js:6)
    at t (survey.vue.min.js:6)
    at Object.<anonymous> (survey.vue.min.js:25)
    at t (survey.vue.min.js:6)
    at t.constructor (survey.vue.min.js:6)
    at survey.vue.min.js:6
```

**Comment by dmitrykurmanov** [comment]
@jnicholea @tavakyan hello! Could you share your example? Or may be create new example on plunker? 

You can fork it from here:
Angular2 http://plnkr.co/edit/OJkKlUn1oxzWYtnruXir?p=preview
jQuery http://plnkr.co/edit/DH4vJWSBtza7bSCDm2r9?p=preview
Knockout http://plnkr.co/edit/JKy5wwiAhaBTMze3fOO0?p=preview
React http://plnkr.co/edit/qXdeQa6x2FHRg0YrOlPL?p=preview
Vue http://plnkr.co/edit/aTYVAiDvMWOf3zDReayE?p=preview

So that we can check it.

**Comment by tavakyan** [comment]
Hey @dmitrykurmanov strangely enough I get the same problem when running: https://github.com/surveyjs/surveyjs_vue_quickstart .  I just git clone the repo, npm install and npm run dev (I had some missing font dependencies which I had to put into the npm_modules folder for the survey editor to work).  I still get the uncaught type error.  I'm on a OS X using npm 3.10.10 node version 7.3.0.  I'm not sure how to put it on plnkr.com, but my code atm is identical to the surveyjs_vue_quickstart.

**Comment by dmitrykurmanov** [comment]
@tavakyan ok we'll check https://github.com/surveyjs/surveyjs_vue_quickstart, thanks.

**Comment by dmitrykurmanov** [comment]
@tavakyan , we fixed https://github.com/surveyjs/surveyjs_vue_quickstart, could you check it please?

**Comment by tavakyan** [comment]
@dmitrykurmanov it looks like everything works now.  Thank you!
