### ISSUE TITLE
Clearing invisible values not working if user backtracks

### ISSUE THREAD

**Issue by bjdani** [surveyjs/surveyjs#299]
If the user backtracks and changes the answer to a question which then hides a subsequent question, the value of the answer for that subsequent question is not being cleared even though I have the survey prop clearInvisibleValues ticked. This behaviour occurs both in the Survey Editor - Test Survey section on the survey.js website and my local web app.

**Comment by andrewtelnov** [comment]
@bjdani Could you please help to reproduce it? I beleive I am missing something.

I used this link: http://surveyjs.org/builder/index.html?surveyid=d5220f76-4802-40cf-ad67-61d7e55608e5

I set clearInvisibleValues to true and go to Test Survey tab, choose "Yes" for the first question and select a framework, then go to the next page, choose "Yes" again and select "MVVM" framework, then go to the next page. After that comeback to the first page and choose "No" for both questions and complete the survey. I have the following values in the result:
Survey Result: {"frameworkUsing":"No","mvvmUsing":"No"}

Thank you,
Andrew

**Comment by bjdani** [comment]
Ah I see. It does indeed clear the values from invisible questions in the JSON result. I was assuming that it would clear the values in the questions on the page as well. Can it do both?

**Comment by andrewtelnov** [comment]
@bjdani It clears values, but on completing the survey. It doesn't nothing during survey running.
You may use onVisibleChanged event:
```
survey.onVisibleChanged = function(survey, options) {
  if(options.visible === false) options.question.value = null;
}
```
However, as an end-user, I would expect to see my previous answer if I make a question invisible and then visible. In fact, I would consider this is as a bug.

Thank you,
Andrew

**Comment by bjdani** [comment]
You make a good point. It is better to leave the values in the invisible questions.
Thanks for your prompt reply to my issue.
