### ISSUE TITLE
Add input-group-addon for Text Input Types

### ISSUE THREAD

**Issue by grunt121** [surveyjs/surveyjs#300]
For single input types add the option of setting input-group-addon for them

**Comment by andrewtelnov** [comment]
@grunt121 Are you talking about bootstrap group addons?

**Comment by grunt121** [comment]
Yes thats right

**Comment by andrewtelnov** [comment]
What kind of addons do you need?
The problem, that many of surveyjs users do not use bootstrap.
We may create an example of implementing bootstrap addons by using the custom widgets: http://surveyjs.org/examples/jquery/custom-widget-select2-tagbox.html

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
There is no followup for a long time. I am closing the issue.

**Comment by AWIXOR** [comment]
Hello from the future, 
I searched for how to use inputs with addons in surveyjs but I didn't find anything.
