### ISSUE TITLE
Feature request: highlight words in questions

### ISSUE THREAD

**Issue by robertoyus** [surveyjs/surveyjs#301]
It would be great if I could highlight some words in the questions. This could be achieved, for example, by using some html marking in the json. Something like:

var survey = new Survey.Model( { questions: [
     {name:"name", type:"text", title: "Please enter your < strong>name< /strong>:", placeHolder:"Jon Snow", isRequired: true}
]});

To get the following:

Please enter your **name**:

Or in the case of a matrix:

var survey = new Survey.Model({questions: [
{ type: "matrix", name: "Quality", title: "Please indicate if you agree or disagree with the following statements",
   columns: [{ value: 1, text: "Strongly Disagree" }, 
              { value: 2, text: "Disagree" }, 
              { value: 3, text: "Neutral" }, 
              { value: 4, text: "Agree" }, 
              { value: 5, text: "Strongly Agree" }],
    rows: [{ value: "affordable", text: "Product is < strong>affordable< /strong>" }, 
           { value: "does what it claims", text: "Product < strong>does what it claims< /strong>" },
           { value: "better then others", text: "Product is < strong>better< /strong> than other products on the market" }, 
           { value: "easy to use", text: "Product is < strong>easy to use< /strong>" }]}
]});

regards

**Comment by robertoyus** [comment]
I created a custom widget to have this functionality. It highlights the text but the validation of the question gets messed up and the selected answers are not detected.

var widget2 = {
		name: "highlight",
		isDefaultRender: true,
		isFit : function(question) { return question.getType() === 'matrix'; },
		afterRender: function(question, el) {
			$(el).find("td").html(function(index, text) {
				return text.replace("ABC", "< strong>ABC< /strong>");
			});
		}
	}
	Survey.CustomWidgetCollection.Instance.addCustomWidget(widget2);

**Comment by andrewtelnov** [comment]
@robertoyus The custom widget is about input part only. Titles, errors and all other question rendering parts are not touched.
Somebody has already asked about this functionality. It absolutely makes sense. I'm adding this into our TODO list.

Markup support for question/page/panel/survey titles.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@robertoyus We have added the mardown support. Here is the examples of using:
http://surveyjs.org/examples/knockout/survey-markdown-radiogroup.html
http://surveyjs.org/examples/knockout/survey-markdown-matrix.html

We are using [showdown markdown ](https://github.com/showdownjs/showdown) in these examples. It uses double asterisks for bold "**Bold text**".

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
There is no reply for several months. I am closing the issue.
