### ISSUE TITLE
Wrong result on Conditions and Triggers

### ISSUE THREAD

**Issue by FBlade** [surveyjs/surveyjs#302]
Click "yes", select nº of kids and then click "No". 
![image](https://cloud.githubusercontent.com/assets/6547619/24227369/841fe858-0f64-11e7-88a8-f721fa520331.png)

**Comment by bjdani** [comment]
I think you have to check the clearInvisibleValues checkbox on that page over on the right which then causes the kids value to no longer appear in the results.

**Comment by dmitrykurmanov** [comment]
@bjdani thanks that's right! @FBlade, could you check it please? 

![344ac88a93](https://cloud.githubusercontent.com/assets/22315929/24243251/8a3e0fb4-0fcb-11e7-814c-74659542b684.jpg)

**Comment by FBlade** [comment]
@dmitrykurmanov and @bjdani Thx.   

Thats right! My fault!  
Thx again!
