### ISSUE TITLE
Visible Triggers not checking the visibility of the question being evaluated

### ISSUE THREAD

**Issue by bjdani** [surveyjs/surveyjs#303]
If I have a hierarchy of questions (e.g. three levels) and set up Visible Triggers so that the correct child questions appear based on the value of the parent questions, if the user backtracks and changes their answer to an earlier question higher up in the hierarchy, some of the child questions are still shown even though their direct parent is invisible.

Steps to recreate the issue:
1. Run the survey for the attached [test.txt](https://github.com/surveyjs/surveyjs/files/863708/test.txt)
2. Answer "Second Item" to Question 1
2. Answer "Second Item" to Question 2 (child of Question 1), Question 2a appears
3. Change answer to Question 1 to "First Item"
4. Question 2a is still shown

I think this is caused by the Visible Triggers still evaluating the value of Question 2 (which causes Question 2a to be shown) even when Question 2 is invisible.

**Comment by andrewtelnov** [comment]
@bjdani Yes, right. It is a limitation of the triggers. It executes on changing value only.
 Please use visibleIf property. Here is [the example](http://surveyjs.org/examples/jquery/condition-kids.html) that does exactly what you need.

Thank you,
Andrew

**Comment by bjdani** [comment]
Hi Andrew,

Thanks for the feedback.
I tried using VisibleIf's but I couldn't get it to work for complex rules such as something like the following (not related to the json survey I attached above):
`{question1} = "somevalue" and {question2} = "someothervalue" and ({question3} = 4 or {question3} = 7 or {question3} = 13)`
Is this syntax correct for a VisibleIf rule?
Do you have any examples of complex VisibleIf rules?

Thanks,
Bruce

**Comment by andrewtelnov** [comment]
@bjdani Yes, the VisibleIf Editor is far from being perfect. We will work on it later.
The condition looks good to me, could you check question names ?  If everything is fine, Could you pass the example that doesn't work. I will check it out. 
Here are some Unit Tests we have (at the end of the file): https://github.com/surveyjs/surveyjs/blob/master/tests/conditionstests.ts

**Comment by bjdani** [comment]
Hi Andrew,
Sorry my example earlier was inaccurate. In using the VisibleIf's I've found the same behaviour as the Visible Triggers where the VisibleIf rules will evaluate a question's value even if that question is invisible (see attached [fruit-example-simple.json.txt](https://github.com/surveyjs/surveyjs/files/866648/fruit-example-simple.json.txt) - if the user first chooses Apple and Red Delicious then the last question appears, then if the user backtracks and chooses Orange and Navel, the last question still appears even though it is not expected based on the last question's VisibleIf rules and the choices made)
To get around this I was trying to create more complex VisibleIf rules (see attached [fruit-example.json.txt](https://github.com/surveyjs/surveyjs/files/866641/fruit-example.json.txt) - only want the last question to be shown if the user chooses Apple & Red Delicious or Orange & Blood)
In this way I am testing for values all the way up the hierarchy to ensure the user had chosen certain paths that are completely visible. This seems to work for the first part of the last question's VisibleIf rule (Apple & Red Delicious) but not for any subsequent combinations in the rule (Orange & Blood).
Is this sort of complex rule (i.e. more than one set of round brackets) possible for VisibleIfs?
Hope this has made sense...
Thanks,
Bruce

**Comment by andrewtelnov** [comment]
@bjdani You visibleIf property should be the following:
`({question-fruit} = 'fruit-apple' and {question-apple-variety} = 'apple-variety-red-delicious') or ({question-fruit} = 'fruit-orange' and {question-orange-variety} = 'orange-variety-blood')`

Unfortunately, it doesn't work either. I have fixed it and committed the fix. We will release a new updated today or early next week.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@bjdani The following visibleIf value will work in the current version. I just check it out.

`{question-fruit} = 'fruit-apple' and {question-apple-variety} = 'apple-variety-red-delicious' or {question-fruit} = 'fruit-orange' and {question-orange-variety} = 'orange-variety-blood'
`

Thank you,
Andrew

**Comment by bjdani** [comment]
Thanks Andrew for your quick reply and fix.
So, until the next update is released, the following structure (without round brackets) will work because the 'and' operators take precedence over the 'or' operators in the evaluation of the rule?
`{question-fruit} = 'fruit-apple' and {question-apple-variety} = 'apple-variety-red-delicious' or {question-fruit} = 'fruit-orange' and {question-orange-variety} = 'orange-variety-blood'`

**Comment by andrewtelnov** [comment]
> So, until the next update is released, the following structure (without round brackets) will work because the 'and' operators take precedence over the 'or' operators in the evaluation of the rule?

Yes, exactly.

Thank you,
Andrew

**Comment by tsv2013** [comment]
Please check 0.12.5 release

**Comment by bjdani** [comment]
This looks good now! Thanks!
