### ISSUE TITLE
How can I save the answer as json and render it to survey ? with knockout

### ISSUE THREAD

**Issue by JayLu921212** [surveyjs/surveyjs#304]

**Comment by andrewtelnov** [comment]
@JayLu921212 There is a survey.data property (get/set) you may set your previous saved json into this property.
Here are two examples: 
http://surveyjs.org/examples/knockout/survey-data.html
http://surveyjs.org/examples/knockout/survey-displaymode.html

In the last demo, please comment the line, that makes the survey read-only:
`survey.mode = "display";`

Thank you,
Andrew

**Comment by JayLu921212** [comment]
Thank you very much ! 
Sorry for taking your time , I should read the example  code carefully .  
You have done a great job !
