### ISSUE TITLE
Error in Matrix with iCheck for JQuery

### ISSUE THREAD

**Issue by robertoyus** [surveyjs/surveyjs#305]
I've noticed a bug when using the Matrix with iCheck and JQuery which messes up the options available for each row. This error also happens in the example in the website (http://surveyjs.org/examples/jquery/custom-widget-matrix-icheck.html). Just select some options for each row:

![image](https://cloud.githubusercontent.com/assets/5199634/24235757/ea6d2e4e-0f5b-11e7-9fd7-c197d9db9ceb.png)

Then click on "Complete" and then on "re-run survey" and you will see the error:

![image](https://cloud.githubusercontent.com/assets/5199634/24235679/a655a006-0f5b-11e7-84c0-7a2747e307f5.png)

In my survey I have multiple pages with a matrix question in each of them. When I click on "Next" I experience the exact same issue.

**Comment by tsv2013** [comment]
I've reproduced the issue with Angular2 and jQuery iCheck custom widget implementation.

**Comment by tsv2013** [comment]
Under some circumstances we need to remove iCheck data for input elements:
`        $el.find('input').data({"iCheck": undefined});
`
I've updated demo on our site. @robertoyus could you please check it?
