### ISSUE TITLE
Error "Out of stack space" when run with Angular 2 production mode

### ISSUE THREAD

**Issue by LeBaThuan** [surveyjs/surveyjs#306]
I built the angular 2 seed app using **npm** installed surveyjs when
I build the production mode. It's working fine with chomre but got the error "Out of stack space" in IE 11
[image](https://drive.google.com/file/d/0B08L0biCW2ARTklyYk9pdzNTeUk/view?usp=sharing)

**Comment by tsv2013** [comment]
This can be related to the order of loading zone/shim scripts. The order should exact as on our [Angular2 demo on Plunker](http://plnkr.co/edit/OJkKlUn1oxzWYtnruXir?p=preview). Could you check it?

**Comment by LeBaThuan** [comment]
Thank you for quick response.
Yes, Tried it with exact the order. but I this error `Unhandled promise rejection Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)
`

**Comment by LeBaThuan** [comment]
I tried to change using the shim.js to es6-shim.js. It's working fine with Angular 2 development mode in IE and Chrome, but es6-shim.js cannot build production mode to work on IE, so I must be changed to shim.js
I got that error when i load the component using surveyjs, for the other component, It's work fine. Plz, help

**Comment by tsv2013** [comment]
I've just checked our plunker example in IE11 and it works for me.

Can you try to put script tags from our [Angular2 demo on Plunker](http://plnkr.co/edit/OJkKlUn1oxzWYtnruXir?p=preview) on your web page? Or can you prepare sample on plunker (or github repo) to reproduce the issue on our side?

**Comment by tsv2013** [comment]
You can also try the [SurveyJS Angular2 Quickstart](https://github.com/surveyjs/surveyjs_angular_quickstart) boilerplate, created by [Angular2 app setup guidelines](https://angular.io/docs/ts/latest/guide/setup.html).

**Comment by LeBaThuan** [comment]
My project using [Angular seed](https://github.com/mgechev/angular-seed). Could you me check it with the production mode. Thank you.

**Comment by tsv2013** [comment]
Sure, we'll take a look with @dmitrykurmanov .

**Comment by dmitrykurmanov** [comment]
@LeBaThuan, hello! I've created a repo: https://github.com/dmitrykurmanov/surveyjs-angular-seed. It is angular-seed with our survey and it is ok in production mode. Could you check it plese?

**Comment by dmitrykurmanov** [comment]
@LeBaThuan 
![c1874a922c](https://cloud.githubusercontent.com/assets/22315929/24294603/4bcf183a-10a8-11e7-9fa4-e38e6df4bcb1.jpg)

**Comment by LeBaThuan** [comment]
That great! Thank @tsv2013 and @dmitrykurmanov . I checked the repo and found the cause of the issue. My issue came from the version of survey-angular, just need an update to ver "0.12.4" in package.json.
