### ISSUE TITLE
Auto-refresh after survey is finished?

### ISSUE THREAD

**Issue by AndehWong** [surveyjs/surveyjs#308]
Hello, I was wondering if there is an option to automatically refresh the page (so that the survey restarts) every time the survey completes. I tried looking for something in the triggers, but the triggers are more for a quick complete of the survey, or triggering specific questions.

**Comment by andrewtelnov** [comment]
@AndehWong You may do it onComplete event:
```
survey.onComplete.add(function (s) {
   //public clear(clearData: boolean = true, gotoFirstPage: boolean = true)
   // keep the data, go to the first page.
   survey.clear(false, true);
});

```

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
There is no followup for a long time. I am closing the issue.
