### ISSUE TITLE
Survey result contains values for invisible "Other" comments

### ISSUE THREAD

**Issue by bjdani** [surveyjs/surveyjs#309]
If the survey contains questions where "Has other item" is checked and the user fills out one of these values and then backtracks and goes down another path through the questions and fills in another question with "Has other item" checked, all the comment fields appear in the survey result even though some are not visible.
See attached [fruit-example-other.json.txt](https://github.com/surveyjs/surveyjs/files/871496/fruit-example-other.json.txt)

1. Choose 'Apple' for 'Which fruit?' question
2. Choose 'Other (describe)' for 'What variety?' question and enter a comment value.
3. Backtrack and change the answer to 'Orange' for 'Which fruit?' question then choose 'Other (describe)' for what variety and enter a comment value.
4. Complete the survey.
5. The survey results json contains the 'Other' comments for both Apple and Orange even though Apple 'Other' is invisible.

**Comment by andrewtelnov** [comment]
@bjdani Yes, it is a bug. I have added a unit test and fixed it.

Thank you,
Andrew

**Comment by tsv2013** [comment]
Please check 0.12.5 release

**Comment by bjdani** [comment]
Hi,

Thanks for adding the fix!

Following the steps in my initial comment above does yield correct results now, but I've noticed there are still comments showing in the results if I use the following steps:

1. Choose 'Apple' for 'Which fruit?' question
2. Choose 'Other (describe)' for 'What variety?' question and enter a comment value.
3. Backtrack and change the answer to 'Red Delicious' for 'What variety?'.
4. Complete the survey.
5. The survey results json contains the 'Other' comments for Apple even though Apple 'Other' was not finally chosen.

**Comment by andrewtelnov** [comment]
@bjdani Yes, it is a bug. However, it is a completely different issue. I have created a new topic: https://github.com/surveyjs/surveyjs/issues/311

Thank you,
Andrew

**Comment by bjdani** [comment]
Thanks Andrew!
