### ISSUE TITLE
Survey Editor returns 404 on a couple of assets

### ISSUE THREAD

**Issue by bjdani** [surveyjs/surveyjs#310]
Hi,
Just noticed when using the Survey Editor on the site that it returns 404 status for the following items:
- http://surveyjs.org/builder/theme-monokai.js
- http://surveyjs.org/builder/worker-json.js

**Comment by andrewtelnov** [comment]
@bjdani I have fixed a problem: https://github.com/surveyjs/editor/commit/e82f07e6bfe61fd8c2b23940e295fe84e5af7451
The issue will be resolved with the coming update.

Thank you,
Andrew

**Comment by tsv2013** [comment]
Please check 0.12.5 release

**Comment by bjdani** [comment]
Looks good now! Thanks!
