### ISSUE TITLE
Programmatic Validation

### ISSUE THREAD

**Issue by mehrdadarvin** [surveyjs/surveyjs#313]
Let's say I complete a survey (which passes the client side validation) and POST the results to my server. I would like to validate the said results on the server as well before inserting it into my db.

Is there a way to programmatically validate the results, given the survey object and the results?

**Comment by andrewtelnov** [comment]
@mehrdadarvin The survey results is a typical JSON object.  There are plenty examples for all popular platforms on [stackoverflow](http://stackoverflow.com).
Or just google it: https://www.google.com/webhp?#q=how+to+validate+json+object+on+the+server-side&*

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
There is no followup for a long time. I am closing the issue.
