### ISSUE TITLE
Is there an event that is fired after a question's value changes and the question is re-rendered?

### ISSUE THREAD

**Issue by SlowburnAZ** [surveyjs/surveyjs#316]
So, in my survey, I'm using a jQuery translation plugin that let's me define a dictionary of phrases, and the translations for each in each language.  The plugin basically looks for a class ("trn"), and then matches the text against the dictionary for things to translate.  This all works great for me in my surveys.

The problem I'm running into, though, is that after a question is answered, the question seems to re-render, at which time, all the text in that question goes back to English.  Is there an event that can be listened to that fires after that happens?  I've tried the "onAfterRenderQuestion" event, but it only fires once for each question, and not after the value is changed.  I've also tried the "onValueChanged" event, but the question seems to re-render itself after that event.

Any help would be great!

**Comment by andrewtelnov** [comment]
@SlowburnAZ Could you please describe your task in more detail?
What exactly do you need to translate to English? question and page titles?
Probably we will find/create a better solution. I guess the task, to have multiple language support for a survey, is a popular scenario. 

Thank you,
Andrew

**Comment by SlowburnAZ** [comment]
Sure..

So, the jQuery translator library I'm using looks for any element with a class of "trn", and compares the contents of that element against a JS object that contains different translations and replaces the content with translated text.  In my case, after the survey is rendered, I manually apply the 'trn' class to things such as the survey title, the text for each question and the question's choices, etc.  I then show a dropdown of the different available languages on screen along with the survey.  When the dropdown value changes, a call is made to the translator library, and the translations are applied.

Example dictionary:
`
var dict = {
  "What is Your Age?": {
    "english": "What is Your Age?",
    "spanish": "¿Cuantos años tiene?"
  }
};
`

Example translator call:
`
translator.lang("spanish");
`

After that call, it will look at all elements with the class 'trn', and update the text to the text specified in that dictionary for the selected language.

That part works fine.  The problem occurs when an answer for a survey question is selected.  The question gets re-rendered, and the text for each element of the question returns to the default as specified by the survey model.

I'm looking to be able to catch an event that is triggered after the answer selection is made and the question is re-rendered, so I can then call the translator to translate the text again.


Does that help?

**Comment by andrewtelnov** [comment]
@SlowburnAZ What is your deadline? I may try to find the the reason why it doesn't work. Are you talking about this library? https://github.com/wsidl/jquery-translate

However, the best solution, it is to have the translated JSON.
Here is what we can do:
1) add a new property to JsonProperty object, isLocalizable, default is false.
2) Mark all required properties as IsLocalizable, for example question.title is localizable, but question.name is not, choices is localizable, where only text is localizable.
3) Add ability to store the localizable string together with the json, in the same object or as a separate dictionary. I am not sure the best way to do it. For example:
```
{
     type: "radiogroup",
     name: "favoritePet",
     title: "What is your favorite pet?",
     title-de: "Was ist dein Lieblingshaustier?",
     choices: [
      {
       value: "cat",
       text: "Cat",
       text-de: "die Katze"
      },
      {
       value: "dog",
       text: "Dog"
       text-de: "der Hund"
      }
     ]
    }
```
4) add ability to edit localizable text in the editor
5) use the right text on changing the survey.locale

I do not think that it will take a lot of time. Probably (4) will take some time, but I may release it without support it in the Editor.
What do yo think?

Thank you,
Andrew

**Comment by SlowburnAZ** [comment]
@andrewtelnov 
The library I'm using is here:  http://www.openxrest.com/translatejs/

My deadline is about 2 weeks from now.  I think that in the short term, if some event could be made to fire after the re-render, that would be perfect for my uses (example of the behavior for reference):
![survey_spanish_example](https://cloud.githubusercontent.com/assets/5659169/24717560/bdd28e74-19e7-11e7-8d6e-4d93fc0892a5.gif)

But longer term, I think what you're proposing is ideal:  To ultimately be able to configure all of this in the editor.  I assume that changing the survey.locale could be done on-the-fly, in response to something like what I've done, where you choose the language from a dropdown, and then make a call to change the survey.locale.

**Comment by SlowburnAZ** [comment]
Sounds good, Andrew.

**Comment by andrewtelnov** [comment]
I have created a new issue: https://github.com/surveyjs/surveyjs/issues/320

**Comment by andrewtelnov** [comment]
@SlowburnAZ The feature is implemented: https://github.com/surveyjs/surveyjs/issues/320
You may build the library by yourself (see the Readme) and give a try.

All properties, that should be localizable, support the following syntax:
`title: "The first question" or title: {"default": "The first question", "de": "Die erste Frage"} or title: {"en": "The first question", "de": "Die erste Frage"}.`

We will publish the next version in several days. I have updated the Editor, it supports multiple languages as well. On changing the survey.locale property different from empty, the library starts to treat localizable strings as an object, with multiple values as shown above.

If you have any issue, please let me know.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@SlowburnAZ surveyjs 0.12.7 is released. Here is the demo: http://surveyjs.org/examples/jquery/survey-multilanguages.html

Thank you,
Andrew

**Comment by SlowburnAZ** [comment]
@andrewtelnov Awesome!  Thanks.  I'll give it a try.

**Comment by SlowburnAZ** [comment]
@andrewtelnov Do I need to update to the latest Survey Builder as well?  It seems the structure of the surveys may have changed a bit.  When I updated to v0.12.9 of surveyjs, using survey model data created in v0.10.3 of the editor, and I select an answer to a question, the title is then displayed twice:

![survey_title_doubling](https://cloud.githubusercontent.com/assets/5659169/25100971/2eb3c6b6-2367-11e7-869a-2828af990ea5.gif)

I also noticed that in the example of the multiple languages that you've provided, there's a difference in the structure of the survey model JSON.  For example, from v0.10.3 of the editor, it produces JSON that begins as such:
```javascript
{
 "pages": [
  {
   "name": "page1",
   "questions": [
    {
     "type": "radiogroup",
     "name": "Visit Location",
     "choices": [
      "Lordsburg Clinic",
      "Animas Clinic",
      ...
```

The 'questions' property seems to have been changed to 'elements' in the multi-language example:
```javascript
{
  locale: "de",
  pages: [ 
  { 
    name: "page1", 
    elements: [
    {
      type: "matrixdropdown",
      choices: [
      {
        value: 5,
        text: {
          default: "5 (the best)",
          de: "5 (Das beste)"
          ...
```

Lastly, will the "name" property for each question or choice also take an object with the localization strings in it, or does it have to be the "title" property?

**Comment by andrewtelnov** [comment]
@SlowburnAZ  The surveyjs should run all versions of models.
The first issue seems like a bug to me, could you share your model with me, so I can investigate the issue?

We have changed "questions" to "elements" after introducing the Panel in v0.12.7. Panel may contains questions and other panels. The old versions (v0.12.6-) of surveyjs could not understand the "elements" tag, but new versions of surveyjs could understand both "questions" and "elements".

Of course, only the latest versions of Survey Editor understands multi languages. After you change the survey.locale in the editor, editor starts to create the multi-languages tags.
So yes, you have to use v0.12.8 or higher editor and surveyjs library.
If you would use v0.12.7, for example, the multi-languages strings could not be read. It would expect a string and not an object.

name doesn't support multi-language, so it can be only a string. And I think it should not. 

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
> The first issue seems like a bug to me, could you share your model with me, so I can investigate the issue?

And what version and platform do you use?

**Comment by SlowburnAZ** [comment]
@andrewtelnov I'd rather not post the whole model publicly, so I'll send you the model to your email address directly.  

I've updated the editor to 0.12.9, so that model will reflect that,  Running this all from Node on Ubuntu 16.04, latest Chrome browser.

**Comment by andrewtelnov** [comment]
Yes, I've got it. I will look at it tomorrow.
And what platform version of surveyjs do you use? JQuery, knockout, angular, react or vue?
Do you have handle any survey events?

**Comment by SlowburnAZ** [comment]
For the Editor, I'm using Knockout.  For the Viewer side of things, I'm using jQuery.

**Comment by andrewtelnov** [comment]
@SlowburnAZ I have sent a link to plunker by e-mail.

Except this title duplication issue, do have other issues? I am very interesting in making sure that our multi language support works and I want to make sure you can use it successful.

Thank you,
Andrew

**Comment by SlowburnAZ** [comment]
So sorry to waste your time, guys ...  it looks like both this and the [issue](https://github.com/surveyjs/surveyjs/issues/338) with the matrix row.value not being set were caused by the translator plugin I had been using before you added multiple language support.

**Comment by andrewtelnov** [comment]
@SlowburnAZ No problem. I am glad that everything works fine!

Thank you,
Andrew
