### ISSUE TITLE
Values from drop down list not being saved

### ISSUE THREAD

**Issue by cjnorth513** [surveyjs/surveyjs#318]
When I submit the survey in Firefox and Internet Explorer, the values from the drop down list are not being saved to the results.  However, the results are being saved in Chrome.

**Comment by andrewtelnov** [comment]
@cjnorth513 What version firefox and IE do you use?
Firefox 52.0.2 and IE 11.0.10240.x work fine.

Thank you,
Andrew

**Comment by cjnorth513** [comment]
IE 9.0.8112.16421 and Firefox version 31.5.0

**Comment by tsv2013** [comment]
@cjnorth513 Could you specify your operating system version? I've not managed to reproduce the issue with IE9 over Windows 7. (You can check screencast: https://www.screencast.com/t/qhJkqDmhpu - probaply I've missed something.)

**Comment by cjnorth513** [comment]
I decided to use radio buttons and they work fine.

Thanks for your help.

**Comment by tsv2013** [comment]
@cjnorth513 I beleive we should fix this issue. And I'm working on it.
I'd like to ask - why are you staying on Firefox version 31.5.0? The current version is 52.0.

**Comment by tsv2013** [comment]
@cjnorth513 I've fixed dropdown for FF v < 51. Fix will be available in 0.12.7. What about IE? We already have the same code to make dropdown work in IE, and I've checked it. If you are experiencing troubles with dropdown in IE, can you share some additional info to reproduce the issue on our side? I'm going to fix it.

**Comment by cjnorth513** [comment]
@tsv2013...thanks!!!  I will download that version when it is ready.

**Comment by tsv2013** [comment]
@cjnorth513 Is it ok now? Do you think we can close the issue?

**Comment by cjnorth513** [comment]
Yes, it is ok now.  You can close the issue.

Thank you for your help,
