### ISSUE TITLE
POM for org.webjars.npm:types__react:jar:0.0.0 is missing, no dependency information available

### ISSUE THREAD

**Issue by efotopoulou** [surveyjs/surveyjs#319]
Thanks for adding surveyjs at webjars!!! 

After compiling my code i get that message: 
The POM for org.webjars.npm:types__react:jar:0.0.0 is missing, no dependency information available
could you check the validity of the pom file.

I have the same error with both available versions 0.12.0 & 0.12.1

**Comment by dmitrykurmanov** [comment]
@efotopoulou Hello! As I know, we did't add our library into webjars. Someone else have done it. Actually version of surveyjs is 0.12.6. And I don't see _survey-react_ on webjars.org. There are only _survey-jquery_ and _survey-vue_ there. So we will discuss it tomorrow. And we are welcome any help with it.

**Comment by dmitrykurmanov** [comment]
@efotopoulou we have `dependencies: { '@types/react': '0.0.0' }` in jquery version may be the problem in `0.0.0` version. We'll updated version to  `dependencies: { '@types/react': '15.0.21' }` it may help.

**Comment by dmitrykurmanov** [comment]
@efotopoulou but in fact `dependencies: { '@types/react': '0.0.0' }` is ok too. I don't know how to webjar works with dependensy of npm package.

**Comment by andrewtelnov** [comment]
There is no followup for a long time. I am closing the issue.
