### ISSUE TITLE
Firefox compatibility

### ISSUE THREAD

**Issue by pierrecharlesp** [surveyjs/surveyjs#322]
Thanks for great job.
Which version of firefox is compatible with survey.js ?
I meet issues with VisibleIf property and firefox ESR 45.3.
VisibleIF isn't working. Page doesn't appear.

Many thanks.

**Comment by tsv2013** [comment]
I've checked "VisibleIf" for pages on the http://surveyjs.org/builder/ page in Firefox 40.0 with the following json:

```
{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "radiogroup", name: "question1",
     choices: [
      { value: "1", text: "first item" },
      { value: "2", text: "second item" },
      { value: "3", text: "third item" }
     ]
    }
   ]
  },
  {
   name: "page2",
   elements: [
    {
     type: "dropdown", name: "question2",
     choices: [
      { value: "1", text: "first item" },
      { value: "2", text: "second item" },
      { value: "3", text: "third item" }
     ]
    }
   ],
   visible: false, visibleIf: "{question1} = 2"
  },
  {
   name: "page3",
   elements: [
    { type: "text", name: "question3" }
   ]
  }
 ]
}
``` 

It works ok for me: "page2" is visible only if "{question1} = 2". Could you test this json?

We have the issue related to the dropdown question in the early versions of Firefox (https://github.com/surveyjs/surveyjs/issues/318) - it has been fixed and fix will be available in 0.12.7 version.

**Comment by tsv2013** [comment]
I've tested this json in the Firefox ESR 45.3.0 and it wotks for me also.

**Comment by tsv2013** [comment]
@pierrecharlesp And answering your question - we are trying to support Firefox >= 40.0
