### ISSUE TITLE
Hidden Values

### ISSUE THREAD

**Issue by alexmc6** [surveyjs/surveyjs#324]
I am not sure if there is a way of doing this already - if so I cannot see it. 

I want to pass into the survey a value which then gets returned to me when the survey is submitted. eg a "surveyversion" with a value of "1.0". 

I tried creating a text value which is visible:false but 
a) I can't seem to define a default value - only a placeHolder
b) The visible false questions do not seem to be posted back to me even though I have explicitly set clearInvisibleValues to false. (I know its default value is supposed to be false based upon Issue 35

Is there a proper way of doing this?

Thanks

**Comment by andrewtelnov** [comment]
@alexmc6 sure, you may do it onComplete event:
```
survey.onComplete.add(function(survey, options) {
   survey.setValue("surveyversion", "1.0");
  //Send data to the server.
});
```

Thank you,
Andrew

**Comment by alexmc6** [comment]
That is really helpful. Thanks!
