### ISSUE TITLE
Disabling Questions

### ISSUE THREAD

**Issue by cjnorth513** [surveyjs/surveyjs#326]
Is there a way to disable certain questions?

**Comment by andrewtelnov** [comment]
@cjnorth513 There is no this functionality yet. Could you describe your scenario, so we can discuss it internally?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@cjnorth513  I forgot to mention.
There is a html question. It doesn't have any input elements and title. 
It supports text pre-processing: http://surveyjs.org/examples/jquery/survey-processtext.html
Will it work for you?

Thank you,
Andrew

**Comment by cjnorth513** [comment]
I know that you can set the survey mode to "display" and then set the data of the survey to particular values.  This makes the questions of the survey read-only.  But I get the impression that the entire survey would be in display mode.  I would only like certain questions in the survey to be read-only, but the other questions to able to be entered.  Can this be done?

**Comment by andrewtelnov** [comment]
@cjnorth513 Unfortunately you may make read-only the whole survey only. I do not mind to add this functionality, however, I would love to know why exactly you do not want to use question html or make a question invisible? What is your scenario?
The reason I'm asking, we would love to introduce functionality that really necessary. Otherwise the product becomes over-complicated and it will be hard to support/develop and more important use it. 

PS: adding readonly property is not that a big deal, but we will likely have to add readonlyIf (similar to visibleIf) and so on.

Thank you,
Andrew

**Comment by cjnorth513** [comment]
I have a survey that a user enter values.  But there a few questions that I am hard coding answers.  I would like for the user to see the answers to the questions, but not be able to change the answers.  I thought if there was a way that I could disable the questions in the survey default answers that could take care of it.  But there is no way to disable a question or make just a question read-only.  This could be a helpful functionality.  

Thank you for your response,

Cory

Cory

**Comment by andrewtelnov** [comment]
@cjnorth513 Ok, I got it, thank you.
Are these read-only questions are always the same? Do you need to make on one run, one questions read-only and on another run other questions read-only?
I mean, what is the particular reason do not use the QuestionHtml?
You may set html property to:
`myHtmlQuestion.html ="Your answer on question 'My question' should be: <b>{myQuestionName}</b>.";
`
PS: However, I have added the read-only question functionality to our TODO list. We may  consider to implement it.

Thank you,
Andrew

**Comment by cjnorth513** [comment]
Yes, these read-only questions are always the same.

Thanks for adding this to the TODO list.  Hopefully I am not the only one that will think this functionality will be useful.

**Comment by andrewtelnov** [comment]
@cjnorth513 It should be really easy to implement and support, so we decided to go with it: https://github.com/surveyjs/surveyjs/issues/327

**Comment by andrewtelnov** [comment]
@cjnorth513 the latest release, v0.12.8 includes this functionality, question.readOnly: boolean property, it is false by default.

Thank you,
Andrew

**Comment by cjnorth513** [comment]
Thanks @andrewtelnov

**Comment by shashikant-lokare** [comment]
@andrewtelnov - have you developed it? if yes how to use it? It would be very helpful if you can give an example.

-Thanks in advance

**Comment by tsv2013** [comment]
@shashikant-lokare You can find examples on the project site - https://surveyjs.io/Examples/Library/?id=condition-enable-kids&platform=jQuery&theme=default
