### ISSUE TITLE
Trigger (visibleIf) doesn't work when multiple checkboxes are checked ?

### ISSUE THREAD

**Issue by boitaumail** [surveyjs/surveyjs#330]
### Are you requesting a feature, reporting a bug or ask a queation?
Hi,

I'm not sur this is a bug, perhaps I'm doing it the wrong way. But it's pretty simple and It's all about a boolean expression to keep a page visible. I want to set up a condition of visibility based on a question with checkboxes (multiple answer available).

### What is the current behavior?
I set up the "visibleIf" property to {question1}='2' for a page.
The element "question1" is on another page. It is a checkbox type.
When I test the survey :
If I check the value 2 on "question 1" >> Yes, my page is visible !
If I check both value 1 AND value 2 >> oups... my page stay hidden.

### What is the expected behavior?
I want my page to be shown when value 2 is checked event if another value is also checked !
If I check the value 2 on "question 1" >> Page VISIBLE
If I check both value 1 AND value 2 >> Page VISIBLE
If I check value 1 >> Page HIDDEN

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: I test it with http://surveyjs.org/builder/

Test code :
{
 pages: [
  {
   elements: [
    {
     type: "checkbox",
     choices: [
      {
       value: "1",
       text: "first item"
      },
      {
       value: "2",
       text: "second item"
      },
      {
       value: "3",
       text: "third item"
      }
     ],
     name: "question1"
    }
   ],
   name: "page1"
  },
  {
   elements: [
    {
     type: "html",
     html: "Hello World !",
     name: "question2"
    }
   ],
   name: "page2",
   visible: false,
   visibleIf: "{question1}='2'"
  }
 ],
 showProgressBar: "bottom"
}

### Specify your

* browser: Chrome
* surveyjs platform: http://surveyjs.org/builder/

Thank you very much !

**Comment by andrewtelnov** [comment]
Hello @boitaumail, contains operator will make a trick:
`"{question1} contains 2"`

PS: There is not good docs about this functionality, sorry about this.

Thank you,
Andrew

**Comment by boitaumail** [comment]
Thank you @andrewtelnov , it works like a charm ! :)
