### ISSUE TITLE
Inverting Matrix Questions

### ISSUE THREAD

**Issue by Kichi93** [surveyjs/surveyjs#332]
Is it possible to invert a matrix (specifically a multiple choice matrix) so that the questions can be in rows and the subjects are in the columns? e.g.

. | Person 1 | Person 2 | Person 2      
---------- | ------------------ | ----------------- | ----------------- 
Name | [Text Field] | [Text Field]  |  [Text Field] 
Age | [Numeric Field] | [Numeric Field  |  [Numeric Field] 
Gender  |   [Radio Group]   |   [Radio Group]  |   [Radio Group]  
Children|    [Dropdown]     |    [Dropdown]    |    [Dropdown]    

The reason I'm trying to do this is that with a lot of questions but only a few subjects it displays a lot nicer going down the page rather than along it.

**Comment by andrewtelnov** [comment]
@Kichi93 I have looked at the code, unfortunately, I do not see an easy solution right now. 

As I see, this feature makes sense, when you have a long list of parameters and from two up to five objects (Persons in your case). I have added it into our TODO list and we will keep this feature in mind. However, to be honest, I'm doubt we will implement it any time soon, unless we have many requests about it.

Thank you,
Andrew

**Comment by Kichi93** [comment]
@andrewtelnov, thanks for your response. I did have a look to see if I could do anything myself but came to the same conclusion as you, i.e. there is no easy way to do it, so don't worry if it doesn't get looked at for a while.

If I come across a way of achieving it, however hacky it might be, I'll post it in here so others can share it until it can be implemented properly :)

**Comment by andrewtelnov** [comment]
@Kichi93 Please take a look at new functionality I have just added:
The event description: https://github.com/surveyjs/surveyjs/issues/400
A plunker demo: http://plnkr.co/edit/eCNxoNUjNylXebBlEuDX?p=preview

**Comment by andrewtelnov** [comment]
@Kichi93 We are starting to work on this functionality.
Please refer to: https://github.com/surveyjs/surveyjs/issues/1116

Thank you,
Andrew
