### ISSUE TITLE
Is there a list of all event names?

### ISSUE THREAD

**Issue by Starojitski** [surveyjs/surveyjs#333]
What is the name of event that is fired when survey is completed. I spent last 10 minutes looking through all examples and could not find it. Quite possibly it's there but i missed it.

**Comment by dmitrykurmanov** [comment]
@Starojitski, hello, thanks for your question. We should create an example about it. In fact it is onComplete option and can be find in this example: http://surveyjs.org/examples/jquery/service-oneperuser.html

**Comment by Starojitski** [comment]
Thanks! That's what i was looking for.
I realize just how difficult it is to create good documentation. On one hand you want to provide people with usage scenarios and on the other half of the time people need a reference. And when your project is rapidly growing you need to make sure that both "views" are still correct. 
Anyway good luck with your endeavour

**Comment by dmitrykurmanov** [comment]
@Starojitski, You are absolutly right, thanks. I am going to add "onComplete" example. And we think about "documentation" page.

**Comment by dmitrykurmanov** [comment]
@Starojitski, This example will appear in the new version of the library. Thanks again.

**Comment by dmitrykurmanov** [comment]
http://surveyjs.org/examples/jquery/survey-oncomplete.html
