### ISSUE TITLE
automatically cast checkbox widget value to array

### ISSUE THREAD

**Issue by Starojitski** [surveyjs/surveyjs#334]
we store selected checkbox values as separate database table records 

```
{
  questionName: "question1",
  value: 1
},
{
  questionName: "question1",
  value: 2
}
```

In order to display the survey with entered values we loop through array and if we find multiple same `questionName`s we combine the values into an array: `{"question1" : [1, 2]}`. This works fine and one can modify question without any problem. 
However this does not work when there is only one selected value. Since we don't keep track of question types we supply `{"question1" : 1}` and the question displays just fine with the corresponding value selected. But if you try adding another value, exception is thrown at line 10561 of survey.jquery.js 

```
SurveyQuestionCheckboxItem.prototype.handleOnChange = function (event) {
        var newValue = this.question.value;
        if (!newValue) {
            newValue = [];
        }
        var index = newValue.indexOf(this.item.value);
        if (event.target.checked) {
            if (index < 0) {
                newValue.push(this.item.value);  <----  EXCEPTION IS THROWN HERE !!!
            }
        }
        else {
            if (index > -1) {
                newValue.splice(index, 1);
            }
        }
        this.question.value = newValue;
        this.setState({ value: this.question.value });
    };
```
I suggest you add some form of checking for array to the beginning of the handler

```
SurveyQuestionCheckboxItem.prototype.handleOnChange = function (event) {
        var newValue = this.question.value;
        if (!newValue) {
            newValue = [];
        }
        // NEW CODE STARTS HERE 
        if (newValue.constructor !== Array) {
            newValue = [newValue];
        }
        // NEW CODE ENDS HERE 
        
      ....
```

**Comment by andrewtelnov** [comment]
@Starojitski I have implemented this functionality on the Model level.
If checkbox get non array value, it will convert it into Array.
Please check the commit and the Unit Test: "QuestionCheckbox if single value set then convert it to array, #334" for more information.

Thank you,
Andrew

**Comment by Starojitski** [comment]
Seems fine to me. When will the updated version will be available?

**Comment by andrewtelnov** [comment]
@Starojitski I hope, we will do it on Tuesday/Wednesday.
Do you have a deadline?

**Comment by Starojitski** [comment]
In a couple of weeks
