### ISSUE TITLE
JSON created by Surveyjs Editor is not valid

### ISSUE THREAD

**Issue by ceenz** [surveyjs/surveyjs#335]
### What is the current behavior?
JSON produced by survey.js editor does not validate
[collection keys are not enclosed in quotes]

### What is the expected behavior?
JSON should validate

### How would you reproduce the current behavior (if this is a bug)?
1. Copy JSON from the Output of the default Survey Editor example.

2. Paste it at http://jsonlint.com/
3. Click Validate JSON

#### Provide the test code and the tested page URL (if applicable)

default survey example in the Survey Editor
Tested page URL:
http://surveyjs.org/builder/index.html?surveyid=d5220f76-4802-40cf-ad67-61d7e55608e5

```
your_code_here

```

### Specify your

* browser: Edge & Chrome 57
* browser version:
* surveyjs platform: vue
* surveyjs version: 0.12.8

**Comment by andrewtelnov** [comment]
Hello @ceenz, we are using [JSON5](http://json5.org/) by default. You may use the standard JSON, by set the clicking on the Option button (the right button in the toolbar) in the editor http://surveyjs.org/builder/ and turn on "Generate Valid JSON".
If you are integrating the Editor into your web site, the following page would be helpful: http://editor.surveyjs.io/examples/options.html#code

Thank you,
Andrew

**Comment by ceenz** [comment]
Thank you :-)
