### ISSUE TITLE
Radiogroup root element type is form

### ISSUE THREAD

**Issue by ceenz** [surveyjs/surveyjs#336]
### What is the current behavior?
questions with radio input groups outputs with <form> as root element type

### What is the expected behavior?
expected root element to be <div>

### Specify your

* browser: Chrome 57
* surveyjs platform: vue
* surveyjs version: 0.12.8

**Comment by andrewtelnov** [comment]
@tsv2013 and @dmitrykurmanov, Guys, could you please take a look at this?

Thank you,
Andrew

**Comment by tsv2013** [comment]
@ceenz could you please specify - what the root element should be? Looks like github markdown removed the tag you have written...

**Comment by andrewtelnov** [comment]
There is no followup for a long time. I am closing the issue.
