### ISSUE TITLE
Move localisation options & strings from main js to seperate file

### ISSUE THREAD

**Issue by ceenz** [surveyjs/surveyjs#337]
### Are you requesting a feature
To help reduce size of main js file is it possible to remove all localisation options and strings to separate localisation js.

**Comment by andrewtelnov** [comment]
@ceenz I have built the current developed version with localization and without localization.
To build without localization you have to comment all (or unneeded) links in this file: https://github.com/surveyjs/surveyjs/blob/master/src/entries/chunks/localization.ts

I've got the following results:
Without localization files, minimized  react version: 198321 bytes (194k)
With localization files,  minimized react version: 215093 bytes (210k)
The difference is 16772 bytes (16.3k) or 7.8%.
If your web server gzips files, we are talking about 30k-35k in total and < 3k for localization part.

Does it really make a difference to you? :)
Of course, we would have to do it when we have more translations. Unfortunately, we do not have even Spanish at the current moment :-(
Localization files: https://github.com/surveyjs/surveyjs/tree/master/src/localization 

Thank you,
Andrew
