### ISSUE TITLE
When using iCheck custom widget, row.value is undefined for Matrix questions

### ISSUE THREAD

**Issue by SlowburnAZ** [surveyjs/surveyjs#338]
So, using a slightly modified version of the iCheck Custom Widget example (which really just combines the Matrix example with the Checkbox and Radio example), 
```javascript
row.value
``` 
is undefined for each row.

Example of my custom widget code is here:
```javascript
var widget = {
  name: 'icheck',
  isFit: function(question) { 
    var iCheckQuestionTypes = [
      'radiogroup',
      'checkbox',
      'matrix'
    ]
    return iCheckQuestionTypes.indexOf(question.getType()) >= 0;
  },
  isDefaultRender: true,
  afterRender: function(question, el) {
    $(el).find('input').data({"iCheck": undefined});
    $(el).find('input').iCheck({
      checkboxClass: 'icheckbox_flat-green',
      radioClass: 'iradio_flat-green'
    });

    $(el).find('input').on('ifChecked', function(event) {
      if(question.getType() === 'radiogroup' || question.getType() === 'checkbox') {
        question.value = event.target.value;
      }
      if(question.getType() === 'matrix') {
        question.generatedVisibleRows.forEach(function(row, index, rows) {
          if(row.fullName === event.target.name) {
            row.value = event.target.value
          }
        });
      }
    });

    var select = function() {
      if(question.getType() === 'radiogroup' || question.getType() === 'checkbox') {
        $(el).find('input[value="' + question.value + '"]').iCheck('check');
      }
      if(question.getType() === 'matrix') {
        question.generatedVisibleRows.forEach(function(row, index, rows) {
          if(row.value) {  // row.value is always 'undefined', even though I know that values are specified in the editor for this question...  see below
            $(el).find('input[name="' + row.fullName.replace(/\'/g, "\\'") + '"][value="' + row.value + '"]').iCheck('check');
          }
        });
      }
    }

    question.valueChangedCallback = select;
    select();
  }
}
```

The definition of this matrix question is as follows:
```javascript
{
  "type": "matrix",
  "name": "Please give a rating for the items below",
  "title": "Please give a rating for the items below",
  "columns": [
    "Very Dissatisfied",
    "Dissatisfied",
    "Neither Satisfied or Dissatisfied",
    "Satisfied",
    "Very Satisfied"
  ],
  "rows": [
    "I feel that my health care team gives me easy to understand health care instructions.",
    ...
  ]
},
...
```

### Specify your

* browser:  Chrome Browser
* browser version:  57.0.2987.133
* surveyjs platform:  Knockout for Editor
* surveyjs version:  0.12.9

**Comment by andrewtelnov** [comment]
@tsv2013 and @dmitrykurmanov Please take a look.

Thank you,
Andrew

**Comment by tsv2013** [comment]
I've created a plunk with your code - http://plnkr.co/edit/LKOGI0kxKmIZKTOUymtm?p=preview . It works like a charm for me: checkboxes are shown and values as saved in data object. Do I miss something?

**Comment by andrewtelnov** [comment]
@tsv2013 Chris is talking about SuveyJS editor. Here is the demo: http://editor.surveyjs.io/examples/customwidgets.html

**Comment by tsv2013** [comment]
@andrewtelnov Yes, I've missed it. I'll check it now.

**Comment by tsv2013** [comment]
@SlowburnAZ I've created a plunk with Editor - http://plnkr.co/edit/8pK9eil1gxFycS3AlyFT?p=preview and haven't found any issues. Can you check whether it works for you?
@andrewtelnov told me you were working under Ubuntu. I'll check my plunk under this OS.

**Comment by SlowburnAZ** [comment]
So sorry to waste your time, @andrewtelnov ...  it looks like both this and the [issue](https://github.com/surveyjs/surveyjs/issues/316) with the matrix row.value not being set were caused by the translator plugin I had been using before you added multiple language support.
