### ISSUE TITLE
Checkbox widget afterRender code undone on value change

### ISSUE THREAD

**Issue by WimWidgets** [surveyjs/surveyjs#339]
@dmitrykurmanov same issue as #329 goes for checkboxes:
[http://codepen.io/Wimski/pen/wdKPmG](http://codepen.io/Wimski/pen/wdKPmG)

It would be great if widgets for ALL kinds of types would not re-render after value change.

**Comment by dmitrykurmanov** [comment]
@WimWidgets hello! We've fixed it.  We are going to release new patch version this week. And you can get prerelease build https://surveyjs.azureedge.net/dev/survey.jquery.min.js And pen example : http://codepen.io/anon/pen/vmNadw
