### ISSUE TITLE
MAX row in Matrix Dynamic (question)

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#340]
It's possible to add a new properties in Matrix Dynamic, in particular "max row", to control the maximun number off row added by the user?
Today there is only the properties MIN ROW :)

**Comment by andrewtelnov** [comment]
@care46 Yes, make sense. We will do it.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@care46 It is done. It will be available in the next minor update.

Thank you,
Andrew

**Comment by care46** [comment]
Awesome! Thanks!!! ;)
