### ISSUE TITLE
Anyone written a d.ts file for SurveyJS?

### ISSUE THREAD

**Issue by SosaWiseHome** [surveyjs/surveyjs#342]
### Are you requesting a feature, reporting a bug or ask a queation?
Question

### What is the current behavior?
I'm using Type Script.  And my transpiler is having issues with finding the Model class.  Having said that the library is working fine and the surveys come up beautifully.  But the transpiler complains.  I want to be able to help the transpiler by creating a d.ts file for SurveyJs.  Wondering if anyone has done that already.

* browser:  Chrome
* browser version: 57.0.2987.133
* surveyjs platform:  Meteor running on TS
* surveyjs version: ^0.12.1

**Comment by tsv2013** [comment]
SurgeyJS is written in TypeScript and .d.ts files are shipped within npm packages,

**Comment by dmitrykurmanov** [comment]
@SosaWiseHome, hello! For example you can find it here https://unpkg.com/survey-jquery@0.12.9/ . Could you check it please? Is it what you need?

**Comment by andrewtelnov** [comment]
There is no reply for several months. I am closing the issue.
