### ISSUE TITLE
[Vue] placeholder not appearing in dropdown question

### ISSUE THREAD

**Issue by duscarroll** [surveyjs/surveyjs#343]
The placeholder for dropdown questions is not appearing in the Vue implementation. This can be seen when comparing the following examples:

http://surveyjs.org/examples/jquery/questiontype-dropdown.html

vs

http://surveyjs.org/examples/vue/questiontype-dropdown.html

**Comment by tsv2013** [comment]
Thank you @duscarroll , we'll fix it.

**Comment by duscarroll** [comment]
Hi, thanks for the prompt response!

I see the fixed label has been added, but I still see the issue on http://surveyjs.org/examples/vue/questiontype-dropdown.html.

**Comment by tsv2013** [comment]
0.12.11 has been released
