### ISSUE TITLE
When field is required and inputType is number, zero (0) is not accepted as an answer

### ISSUE THREAD

**Issue by emerbrito** [surveyjs/surveyjs#345]
When using a number input (type: `text`, inputType: `number`), if field is required it will accept any negative number, any number greater than zero but, not zero.

Since zero (0) is a number, there are instances where it might be the appropriated answer.

Is this behavior by design or am Im missing something?

**Comment by andrewtelnov** [comment]
@emerbrito It is not an expected behavior. There is a simple check if(!value) and it returns true for null and undefined + for 0 and false values as well.
I will work on the fix.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@emerbrito The bug is fixed, the unit test ("Do not show required error for value 0 and false") is added .

Thank you,
Andrew

**Comment by emerbrito** [comment]
Sounds aggregate. 
Thanks a lot.
