### ISSUE TITLE
Add parameters to choices ? get result from HTML element ?

### ISSUE THREAD

**Issue by traquall** [surveyjs/surveyjs#348]
Hi,
Would it be possible to add parameters to response choices ? 
For example with a radio button, I'd like to have value, text and another text parameter that I can get in the json result.

And I have another question : Is it possible to get result value with an HTML element ? It would be great if that's the case !

Thanks !

**Comment by andrewtelnov** [comment]
@traquall Yes, you can. You will not be able to edit it in the Survey Editor. However, you should be able to get access to it in the custom widget.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@traquall From v0.12.24, you may add a property into itemvalue and it will be appear in the Editor:
for example:
`Survey.JsonObject.metaData.addProperty("itemvalue", {name: "imageLink", choices: ["Item 1", "Item 2"]})`

Thank you,
Andrew
