### ISSUE TITLE
Multiple Language support in the Editor UI?

### ISSUE THREAD

**Issue by SlowburnAZ** [surveyjs/surveyjs#349]
* Requesting a feature *

Now that multiple languages are supported, are there any plans to have the ability to enter the language translations for each supported string (question title, choice text, matrix column headers, etc.) into the survey editor UI, rather than just in the raw JSON?

**Comment by andrewtelnov** [comment]
@SlowburnAZ It is already done.
Change survey.locale to the language you need and start to edit the titles, choices text and so on.
After you are done, change to another survey.locale and repeat.
You may see the result in the JSON.

Thank you,
Andrew

**Comment by SlowburnAZ** [comment]
Ah, okay.  I guess I didn't put 2 and 2 together because it still showed my English wording when I changed the locale:

![survey_lang_problem](https://cloud.githubusercontent.com/assets/5659169/25242092/4a4ea6a0-25ad-11e7-98bb-5de531013534.gif)

The UI doesn't seem update the choices when you change the locale.  For me, to get the editor to update the text for the choices, I've had to select the question, then bring up the choice editor, then click OK.  Not a huge deal, but it might confuse other people as it did me.

In any case, is Spanish support coming at some point?

**Comment by andrewtelnov** [comment]
@SlowburnAZ Choices have to be updated. It works before and even unit tests are still there, but after markdown support, we start to use another rendering mechanism for strings. I forgot to check the localization. I will work on the fix.

About Spanish localization. As soon as somebody add the Spanish localization here: https://github.com/surveyjs/surveyjs/tree/master/src/localization, we will have it. It can be you :-)

Thank you,
Andrew

**Comment by SlowburnAZ** [comment]
@andrewtelnov 
I'd be happy to provide the Spanish translations.  Do you have the list of the original English strings for each?

**Comment by andrewtelnov** [comment]
It would be great!
Localized strings in English:
https://github.com/surveyjs/surveyjs/blob/master/src/surveyStrings.ts

**Comment by andrewtelnov** [comment]
@SlowburnAZ The bug was fixed. 
FYI: @tsv2013 is working on examples with custom widgets + multiple language support. At the current moment custom widget doesn't re-render itself on locale change. We will change it.

Thank you,
Andrew

**Comment by SlowburnAZ** [comment]
@andrewtelnov Here's the Spanish localization code:

```javascript
import {surveyLocalization} from "../surveyStrings";

export var spanishSurveyStrings = {
    pagePrevText: "Anterior"
    pageNextText: "Siguiente",
    completeText: "Completo",
    otherItemText: "Otro (describa)",
    progressText: "Pagina {0} de {1}",
    emptySurvey: "No hay pagina visible o pregunta en la encuesta.",
    completingSurvey: "Gracias por completar la encuesta!",
    loadingSurvey: "La encuesta se esta cargando...",
    optionsCaption: "Seleccione...",
    requiredError: "Por favor conteste la pregunta.",
    requiredInAllRowsError: "Por favor conteste las preguntas en cada hilera.",
    numericError: "La estimacion debe ser numerica.",
    textMinLength: "Por favor entre por lo menos {0} symbolos.",
    textMaxLength: "Por favor entre menos de {0} symbolos.",
    textMinMaxLength: "Por favor entre mas de {0} y menos de {1} symbolos.",
    minRowCountError: "Por favor llene por lo menos {0} hileras.",
    minSelectError: "Por favor seleccione por lo menos {0} variantes.",
    maxSelectError: "Por favor seleccione no mas de {0} variantes.",
    numericMinMax: "El '{0}' debe de ser igual o mas de {1} y igual o menos de {2}",
    numericMin: "El '{0}' debe ser igual o mas de {1}",
    numericMax: "El '{0}' debe ser igual o menos de {1}",
    invalidEmail: "Por favor agrege un correo electonico valido.",
    urlRequestError: "La solicitud regreso error '{0}'. {1}",
    urlGetChoicesError: "La solicitud regreso vacio de data o la propiedad 'trayectoria' no es correcta",
    exceedMaxSize: "El tamaño der archivo no debe de exceder {0}.",
    otherRequiredError: "Por favor agrege la otra estimacion.",
    uploadingFile: "Su archivo se esta subiendo. Por favor espere unos segundos y intente de nuevo.",
    addRow: "Agrege hilera",
    removeRow: "Retire", 
    choices_firstItem: "primer articulo",
    choices_secondItem: "segundo articulo",
    choices_thirdItem: "tercer articulo",
    matrix_column: "Columna",
    matrix_row: "Hilera"
};

surveyLocalization.locales["es"] = spanishSurveyStrings;
```

**Comment by andrewtelnov** [comment]
@SlowburnAZ Great, thank you!
We will release new version on Monday. Spanish translation will be included.

**Comment by dmitrykurmanov** [comment]
v0.12.11 is released
