### ISSUE TITLE
[Vue] Markdown titles don't work on first page

### ISSUE THREAD

**Issue by duscarroll** [surveyjs/surveyjs#350]
When creating a survey with multiple pages in Vue, Markdown titles are not rendered on the first page of the survey and only work on subsequent pages.

**Comment by dmitrykurmanov** [comment]
@duscarroll hello, I can't reproduce it. What version of survey-vue do you use? Could you check this fiddle: https://jsfiddle.net/734e71at/ please?

**Comment by duscarroll** [comment]
Hello,

Sorry, this was erroneous.

Thanks!
