### ISSUE TITLE
Saving intermediate results when "Next" is pressed?

### ISSUE THREAD

**Issue by alexmc6** [surveyjs/surveyjs#351]
Asking a question:

### What is the current behavior?

Currently the survey is only saved to the server when the "Complete" button is pressed. But this might result in nothing being saved if the user quits part way through the survey. 

### What is the expected behavior?

What I would like is for the survey to be [optionally] saved to the server whenever next is submitted - perhaps with an extra flag saying that it is partially completed. 

I had a look at the tests in the source and thought maybe the solution is to do something like this...

document.getElementById('surveyNext').onclick = function() { mycodegoeshere(); survey.nextPage(); };

but I am not sure what that should be - and whether this is the best approach.  

### How would you reproduce the current behavior (if this is a bug)?

* browser: any
* browser version:
* surveyjs platform jquery for me.
* surveyjs version: latest (as of yesterday :-)

Thanks for all your hard work on this.

**Comment by dmitrykurmanov** [comment]
@alexmc6, hello! You can try `onCurrentPageChanged `event:

`survey.onCurrentPageChanged.add( mycodegoeshere() );`

**Comment by andrewtelnov** [comment]
@alexmc6 You have to set survey.sendResultOnPageNext to true and use survey.onPartialSend event.

Thank you,
Andrew

**Comment by alexmc6** [comment]
THANKS!
(Sorry I missed that)

**Comment by gstkenpo** [comment]
I understand that onPartialSend is a feature for large survey. However, it is possible only send the "current" page result?
I have gone though the methods in survey model. I can't find suitable methods. Am I missing sth?

**Comment by andrewtelnov** [comment]
@gstkenpo Please call [survey.sendResult method](http://surveyjs.org/docs/api_surveymodel.html#sendResult)

Thank you,
Andrew
