### ISSUE TITLE
When posting to server on complete event, go back to edit mode if an error is returned

### ISSUE THREAD

**Issue by emerbrito** [surveyjs/surveyjs#353]
I'm posting `survey.data` to my server api on complete, at which point the complete message get's displayed by surveyjs and the survey disappears.

If the server return an error or if there is a network issue or something similar, is there a way to go back to the survey instead so the user can try the "Complete" button again?

**Comment by andrewtelnov** [comment]
@emerbrito Sure, you may use the following code:
```
//Parameters: clearData: boolean = true, gotoFirstPage: boolean = true, make them all false
survey.clear(false, false);
survey.render();
```
However, I would suggest you to write an error message, above/under a survey that something goes wrong and ask to resubmit the data by pressing a button. In this case your users know what is going on.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@emerbrito I think we will add one more state (submitError). It will show another customizable page, similar to complete and there will be a button that will call the data submission one more time.
On error, you will have to set the survey.state to:
sumitStarted, submitError and submitSuccess. Something like that.
I've just added this into our TODO list.

Thank you,
Andrew

**Comment by emerbrito** [comment]
Thanks for the prompt response.
The code snippet is exactly what I was looking for. 
Glad yo hear you will make it even easier in the future.
You guys have a great project going on in here. Congrats.

**Comment by avium** [comment]
Ideally there would also be a way to inform the user that data is being submitted so they don't close the page too soon.

**Comment by andrewtelnov** [comment]
@avium Yes, we have it in our TODO list. I will likely work on it on this or next week. 

Thank you,
Andrew
