### ISSUE TITLE
Timing how long a user takes to complete the survey? (Question)

### ISSUE THREAD

**Issue by alexmc6** [surveyjs/surveyjs#355]
I have a question which I think is of interest to many surveyJS users. 

I have a number of surveys on my site, some of which are quite long. I would like to know how long people take to answer questions (and if possible) notice when they started a survey but didn't finish it. I could then honestly say something like "This survey takes an average of 6 minutes to complete"

One solution might be to put some kind of timer into SurveyJS so that as the survey gets saved it also submits the total time the survey took. This might not be the best solution though, but it has the advantage of being stored in the same database as all the other survey submission data.

Another suggested solution might be to put Google Analytics (or Snowplow) JS code in each survey so that each time the user moves on that is recorded. 

I am guessing that in either case we might add some javascript into an html question - or possibly add in a custom widget which does the timing for us. 

Is there a standard/best practice way of doing this which I should be copying, or should I come up with a way which works for me. 

* browser: all
* browser version: all
* surveyjs platform (angular or react or jquery or knockout or vue): jquery (but probably of interest to all)
* surveyjs version: latest as of three days ago.

**Comment by andrewtelnov** [comment]
@alexmc6 We have introduced the following functions/properties:
survey.startTimer(), survey.stopTimer(), [survey.timeSpent](https://surveyjs.io/Documentation/Library/?id=surveymodel#timeSpent), page.timeSpent.

Thank you,
Andrew
