### ISSUE TITLE
How do you show previous answers to a survey?

### ISSUE THREAD

**Issue by tavakyan** [surveyjs/surveyjs#358]
### Are you requesting a feature, reporting a bug or ask a queation?
This is likely a feature request as I haven't seen an example of this.  Say I create a survey and the survey viewer is used in order for the user to answer the survey.  At a later time can I reload previous answers to a survey if I have made changes to the survey builder template?  Does the user-interface have a way of populating the values given a response or do I have to somehow use the placeholder (ie map the JSON results to optional fields manually)?  

### What is the current behavior?
The current behavior seems to be a placeholder field needs to be populated.  

### What is the expected behavior?
If there was a method inside the component to which I could pass in the previous survey results and it would show the answers that were inputted beforehand.  

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@tavakyan There is no UI for setting the previous data. 
`yousurvey.data = yourpreviousSavedJSONObject;`
Here two examples how to make it in JavaScript:
http://surveyjs.org/examples/jquery/survey-displaymode.html
http://surveyjs.org/examples/jquery/survey-data.html

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
There is no followup for a long time. I am closing the issue.
