### ISSUE TITLE
ChoicesByURL not working in drop-downs within MatrixDynamic questions from release 0.12.6 onwards

### ISSUE THREAD

**Issue by bjdani** [surveyjs/surveyjs#359]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug.

### What is the current behaviour?
When the drop-down is hooked up to a working URL (via Choices from Web) that returns the following JSON results, the drop down list is initially filled with the correct items, I choose one of the items and the drop-down field is blanked out (my choice is gone), if I then add another row and try and choose another item from the drop-down list, the list contains nothing...

Here is the JSON being returned to the drop-down from the API:
`{
  "results": [
    {
      "id": "1",
      "value": "Site 1"
    },
    {
      "id": "2",
      "value": "Site 2"
    },
    {
      "id": "3",
      "value": "Site 3"
    }
  ]
}`

And here is the JSON config of the question (API URL replaced to protect the innocent):
`{
	type: "matrixdynamic",
	addRowText: "Add site",
	columns: [
		{
			name: "site",
			title: "Site",
			cellType: "dropdown",
			choicesByUrl: {
				url: "<<API URL>>",
				path: "results",
				valueName: "id",
				titleName: "value"
			}
		}
	],
	indent: 1,
	isRequired: true,
	name: "question-site",
	removeRowText: "Remove site",
	rowCount: "0",
	title: "Which sites?"
}`

### What is the expected behaviour?
The drop-down should list the items from the JSON and when I choose one of the items it should be shown in the drop-down field.

### How would you reproduce the current behaviour (if this is a bug)?
Running my application and referring to the survey CDN for release 0.12.5 produces a correctly behaving drop-down list, if I increase the CDN version the bug presents itself.

#### Provide the test code and the tested page URL (if applicable)
Difficult to provide the URL as the API is running locally inside my organisation.

### Specify your
* browser: Chrome
* browser version: 57.0.2987.133 (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.12.6 onward

**Comment by bjdani** [comment]
I have also now tested this using the URL "http://services.groupkt.com/country/get/all" from the "Dropdown + restfull" example and it doesn't work either when the dropdown is inside a MatrixDynamic question.
However, a question that is just a Dropdown question type, works fine.
The problem seems to be related to the dropdown when it is part of a MatrixDynamic question type since release 0.12.6.

**Comment by andrewtelnov** [comment]
@bjdani There is another issue. When we are using restful API for matrix dropdown, we send a lot of requests to the server. The requests are the same. We should cache the result during a survey running. 

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@bjdani I have fixed the issue. Adding the cache on restful requests fix the issue.

Thank you,
Andrew

**Comment by gnimmelf** [comment]
Nice timing, I just bumped into the same issue. What is the quickest way to get the fix?; I am now running `https://surveyjs.azureedge.net/0.12.9/survey.jquery.min.js`.

**Comment by andrewtelnov** [comment]
@gnimmelf I have updated the dev build.
You may use `https://surveyjs.azureedge.net/dev/survey.jquery.min.js` for a while.

Thank you,
Andrew

**Comment by bjdani** [comment]
Thank you Andrew for quickly addressing this issue. I can confirm that it is working for me when I use the dev build. Any estimate on when 0.12.12 will be released?
Thanks again,
Bruce

**Comment by andrewtelnov** [comment]
@bjdani We've scheduled the next minor on May 2 or May 3. 

Thank you,
Andrew

**Comment by bjdani** [comment]
Thanks again Andrew!
