### ISSUE TITLE
Implements an option like "visibleIf" for the option "isRequired"

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#360]
It's possible to have an option like "visibleIf" for the option "isRequired"? 

For example an option called "requiredIf", that allow users to specify a condition for the "required option"

thanks

**Comment by andrewtelnov** [comment]
@care46 I would recommend you to have to two questions with the same name.
The first one will be required and the second is not. They will have different visibleIf properties.
When one is visible, another is invisible and vise versa. 
That will make a trick.

Thank you,
Andrew

**Comment by care46** [comment]
ook!

**Comment by murrah** [comment]
+1 for the original idea though! ;-)

If you have a number of questions that are "requiredif" that could be a lot of duplication. For me there is only 1 duplicated question but extrapolating ...

**Comment by masciugo** [comment]
I think It could be a good workaround (you need to add _clearInvisibleValues: "none"_ though) and so it remains. 

@andrewtelnov 

without adding a new property (requiredIf), from an API point of view, you can make isRequired _expressionable_ so that you can write things like:
```
isRequired: "{otherBooleanQuestion} = true"

my two cents

**Comment by andrewtelnov** [comment]
@masciugo It would be hard to implement an UI, where the most people expect to have a checkbox in Builder/Editor and you are offer them an expression editor as an option.
However, from programming point of view, it has a perfect sense of course.

Thank you,
Andrew

**Comment by cinziasala** [comment]
I tried to use the workaround suggested by Andrew in my survey, but as mentioned by masciugo, the *clearInvisibleValues:* "none" has to be set in order to get the value. This is not applicable to my survey where I need to set *clearInvisibleValues:* "onHidden".
I am not a developer and I am wondering if it is feasible to add the option *"requiredif"* that can be used like the "visibleif" question.
