### ISSUE TITLE
Architectural Question: Class inheritance

### ISSUE THREAD

**Issue by hyndsite** [surveyjs/surveyjs#363]
After spending quite a bit of time in your code, I am curious how much you would have avoided the very deep class taxonomies created through class inheritance, especially relating to questions types - as opposed to another less coupling/binding code reuse pattern (e.g. object composition..etc.)?

**Comment by andrewtelnov** [comment]
@hyndsite We use different patterns for different frameworks.
Are you talking about composition vs inheritance in general?

About 8-10 months ago we had knockoutjs version only. After that we have divided the code on core (platform independent) and knockout code.
I personally feel that moving to composition would bring us some benefits. However, I do not want to change a working code without a really good reason.

**Comment by hyndsite** [comment]
Thanks for the answer.  This is definitely not a feature-request, but simply a question on reflection after you have worked on the project for a number of years.
