### ISSUE TITLE
Going back to a page and Looping over pages

### ISSUE THREAD

**Issue by garunski** [surveyjs/surveyjs#365]
### Are you requesting a feature, reporting a bug or ask a question?
Question/Feature
Is it possible to create loops in the survey? One case would be going back a page for a particular answer. Another case would be going back over a number of pages based on the user input for the loop count.
I know I can programatically add the questions to the survey based on answers as in #186 but was hoping for a simpler method.

#### Provide the test code and the tested page URL (if applicable)
See image
![examples](https://cloud.githubusercontent.com/assets/1002770/25567177/f7aa1464-2d9c-11e7-992f-8b50ccc68d5f.jpg)

**Comment by andrewtelnov** [comment]
@garunski You may change the currentPage onValueChanged event. However, I do not see how it helps you. The person will fill the same fields, just override them. I mean you still should have something like:
firstName1, lastName1, firstName2, lastName2 and so on. 
You may do not created them and make firstName(N) and lastName(N) invisible by default and make it visible if a person answer 'No' on isYouLastName(N).

Another solution, use the QuestionMatrixDynamic with two fields: FirstName and LastName. Where both columns and a question have isRequired property set to true. But I guess, you are doing something mobile...

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Got one more idea. You may on onValueChanged, check if it is "isYourLastName" question and the answer is no, then set "isYourLastName" to 'nul' (survey.clearValue("isYourLastName").
Then change the name of you firstName1 and lastName1 to firstName2 and lastNam2 and go back on two pages: survey.currentPageNo = survey.currentPageNo  - 2;

Thank you,
Andrew

**Comment by garunski** [comment]
Is it possible to create a feature that would take a "where" parameter and a "condition". which could navigate to a particular question based on the condition.
for example. goto {question2} if {question1}==2 or something like that.

**Comment by andrewtelnov** [comment]
@garunski Yes, we can. It will be something similar to complete trigger: http://surveyjs.org/examples/jquery/trigger-complete.html

**Comment by andrewtelnov** [comment]
No reply for several months. I am closing the issue.
