### ISSUE TITLE
"Default" locales are disappearing after editing a question.

### ISSUE THREAD

**Issue by SlowburnAZ** [surveyjs/surveyjs#366]
There seems to be a problem with the editor when a locale other than a default is defined.

For example, if you have a "default" locale defined, and a Spanish ("es") locale defined, and then you edit a question, the "default" locale entries disappear.  Here's an example of that happening:

![survey_lang_problem_editor](https://cloud.githubusercontent.com/assets/5659169/25596755/b31c0940-2e7f-11e7-917e-17050aa84681.gif)

### Specify your

* browser:  Google Chrome
* browser version:  57.0.2987.133
* surveyjs platform (angular or react or jquery or knockout or vue):  jQuery
* surveyjs version:  0.12.11

**Comment by andrewtelnov** [comment]
@SlowburnAZ I have seen what happens. The default locale string equals to value. The editor doesn't store the text when it equals to the value. 
It makes sense when there is only one language, but it leads to a bug one there are several languages. I will fix it.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@SlowburnAZ I have fixed the bug. Here is a workaround, that will make the current version working:
`editor.alwaySaveTextInPropertyEditors = true;`

We will release the update likely tomorrow.

Thank you,
Andrew

**Comment by SlowburnAZ** [comment]
@andrewtelnov Adding the
`
editor.alwaySaveTextInPropertyEditors = true;
`
didn't help.  I'll wait for the fix.

**Comment by andrewtelnov** [comment]
@SlowburnAZ I have just checked the work-around and it works fine.
Could you make sure that you set this property right after calling the constructor?
The fix works similar:
```
if (!alwaySaveTextInPropertyEditors && !this.isMultipleLocaleInText(editorItem.item) && editorItem.koText() == editorItem.koValue()) {
 text = null;
}
```
I have added the check: `!this.isMultipleLocaleInText(editorItem.item)`

Thank you,
Andrew

**Comment by SlowburnAZ** [comment]
@andrewtelnov Yes, I'm calling it just after the constructor:
```javascript
...
// Initialize Survey Editor
editor = new SurveyEditor.SurveyEditor('surveyBuilder', editorOptions);
// Fix for disappearing 'default' locale choices
editor.alwaysSaveTextInPropertyEditors = true;
...
```

![survey_lang_problem_editor](https://cloud.githubusercontent.com/assets/5659169/25632824/f95e9e36-2f29-11e7-9705-f6cc6a86938a.gif)

**Comment by andrewtelnov** [comment]
@SlowburnAZ Right, alwaySaveTextInPropertyEditors  doesn't work for Rows/Columns in matrix (nested property editor). I will fix it as well.
Sorry about that.

**Comment by andrewtelnov** [comment]
@SlowburnAZ I have just realized, that my fix doesn't work correctly either.
The better solution will be to change the way localization string is working.
Right now if there is no default value in the localization string, then we are using the first locale. For example: {"de": "Deutsch"} will return "Deutsch" for all locales. That means that the following itemValue
{value: "My Value", text: {"de": "Deutsch"}} will return "Deutsch" for all locales, while it should return "My Value" for all locales except "de".
I will better fix this issue.
In your case you will not have the default locale as well. However, the text from value will be taken.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@SlowburnAZ It should be fixed now. I will do more tests. Added several unit tests and a property and a new callback to LocalizationString object.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@SlowburnAZ I have tested and it seems everything is fine. The new release is launched. Could you please try it?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
There is no followup for a long time. I am closing the issue.
