### ISSUE TITLE
Triggers on range of values

### ISSUE THREAD

**Issue by mellogarrett** [surveyjs/surveyjs#368]
On a Rating question type how can I have a trigger show visible if the value is in a range? For example, if the rating value is 3/5 or lower, I want to show a followup question.

**Comment by dmitrykurmanov** [comment]
@mellogarrett  hello, please check this example: https://jsfiddle.net/surveyjs/o5vhduwz/ Is it what you need?

**Comment by mellogarrett** [comment]
@dmitrykurmanov that example is not working

**Comment by andrewtelnov** [comment]
It works correctly. Anyway the idea is to use visibleIf property.
Here is another example: http://surveyjs.org/examples/jquery/questiontype-panel.html

**Comment by mellogarrett** [comment]
Should I be using `visibleIf` everywhere in place of triggers?

**Comment by andrewtelnov** [comment]
@mellogarrett yes. visibleIf is the better way in the most scenarios.
