### ISSUE TITLE
It's possible to have "startWithNewLine" option on PANEL element?

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#370]
I think it might be interesting... I would need to pair two panels, as it does today for questions...

Thanks

**Comment by andrewtelnov** [comment]
@care46 Yes, it makes sense. I have added it to our TODO list.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@care46 added the support in run-time.
Drag&drop for panel + startWithNewLine doesn't work as expected. I have to modify code in the Survey Editor as well.

**Comment by care46** [comment]
@andrewtelnov HI, i'm testing this feature on the editor online and it seems to be ok, but if i try with the same json with 0.12.15 jquery version of the library in my local machine, the result is not the same and the second panel go in new line... probably this feature is not included in the latest jquery version?

**Comment by andrewtelnov** [comment]
@care46 It should be the same, current editor is using v0.12.15( src="https://surveyjs.azureedge.net/0.12.15/surveyeditor.js"). 
The editor use the knockout version of the surveyjs library.

I am working on panel + startWithNewLine + Editor right now, at the very moment. 

Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov ok, but probably I explained to you badly... with the editor online, my json work perfectly, in my local machine instead i don't use the editor, i'm testing the survey using 0.12.15 of survey.jquery.min.js...

**Comment by andrewtelnov** [comment]
@care46 You are right. Editor is using knockout version, that works fine.
I have fixed the issue in react/jQuery. We will check vue as well.

Thank you,
Andrew

**Comment by tsv2013** [comment]
@andrewtelnov I've added code for VueJS.

**Comment by andrewtelnov** [comment]
@care46 I have fixed the bugs with editor and dragging Panel with startWithNewLine = false finally.

Thank you,
Andrew
