### ISSUE TITLE
Unable to process binding "template: function (){return { name:'survey-content',afterRender:koEventAfterRender} }"

### ISSUE THREAD

**Issue by nelero** [surveyjs/surveyjs#374]
With the latest version, i got : 
```
Uncaught ReferenceError: Unable to process binding "template: function (){return { name:'survey-content',afterRender:koEventAfterRender} }"
Message: Unable to process binding "if: function (){return koState() =="running" }"
Message: Unable to process binding "template: function (){return { name:'survey-page',data:koCurrentPage,afterRender:koAfterRenderPage} }"
Message: Unable to process binding "text: function (){return koNo() + processedTitle }"
Message: koNo is not defined
    at text (eval at parseBindingsString (knockout-min.js:61), <anonymous>:3:129)
    at update (knockout-min.js:91)
    at function.a.j.q (knockout-min.js:66)
    at l (knockout-min.js:44)
    at Object.a.w.a.j (knockout-min.js:47)
    at knockout-min.js:66
    at Object.o (knockout-min.js:10)
    at g (knockout-min.js:65)
    at h (knockout-min.js:63)
    at k (knockout-min.js:63)
```

**Comment by tsv2013** [comment]
@nelero  There is no `koNo` property in our code since 0.12.9. Can you check your 'survey.ko.min.js' version? The actual version should be 'v0.12.12' in the header inside the file.

**Comment by nelero** [comment]
i use the CDN with 0.12.12 in the url, so  yes it's the last version :(

**Comment by tsv2013** [comment]
@nelero  Can you share this url?

**Comment by nelero** [comment]
in private ?

**Comment by tsv2013** [comment]
@nelero  If it's not a private url and doesn't contain any private data, as far as I understand it's a link to some public cdn, you can post it here.

**Comment by nelero** [comment]
yes but this is a page which is available only by an email link, so i don't want to display it on a github thread which is public :(

**Comment by tsv2013** [comment]
@nelero you can mail on surveyjs.org@gmail.com

**Comment by nelero** [comment]
@tsv2013 : Thanks ! email sent

**Comment by tsv2013** [comment]
@nelero I've got it. I've seen the error.

**Comment by tsv2013** [comment]
@nelero I've sent you answer via email. Please check it.

**Comment by nelero** [comment]
@tsv2013 : perfect ! it works !
thanks for your reactivity !

**Comment by tsv2013** [comment]
You are welcome :-)

**Comment by ussainaugment** [comment]
please share the solution. I'm also getting the same error.
usainrasvi@gmail.com

**Comment by dmitrykurmanov** [comment]
maybe we need a public example which solves this problem

**Comment by dmitrykurmanov** [comment]
@ussainaugment it was a problem with custom knockout templates and our new version of library. We can't share customer's information here.
Do you have any custom templates? If yes it probably need to be updated according to our current version. Or you can create a plunker example illustrating the issue and we will check it.

**Comment by alekhraut** [comment]
Hi @dmitrykurmanov ,

I am too facing the same issue, while integrating it with ionic.
Could you please help me out as it is acting as a blocker for me.

Please find the below demo repo: https://github.com/alekhraut/ionicDemoSlider.git

-Thanks in Advance.

**Comment by tsv2013** [comment]
@alekhraut We've checked your code. Issue was not related to the SurveyJS code. You got wrong element for slider. For more details you can check my pull request - https://github.com/alekhraut/ionicDemoSlider/pull/1

**Comment by alekhraut** [comment]
Thanks @tsv2013  it was much helpful.

**Comment by kowthalganesh** [comment]
![image](https://user-images.githubusercontent.com/5681640/40730873-580fcbae-644d-11e8-8fc7-81d063594f41.png) I was getting the above error. If am trying to create a custom widget nouislider inside matrix dynamic 
![image](https://user-images.githubusercontent.com/5681640/40730919-7cacdfd8-644d-11e8-95b9-6ec518ad515b.png) Html templates are not loading Properly

**Comment by andrewtelnov** [comment]
@kowthalganesh What platform and version do you use?

Thank you,
Andrew

**Comment by kowthalganesh** [comment]
**Platform**: Angular5 (Angular-cli)
**Versions**:
"@types/knockout": "^3.4.55",
"survey-angular": "^1.0.2",
"surveyjs-editor": "^1.0.2",
"surveyjs-widgets": "^1.0.2",

**Note**: SurveyJs working fine without custom widgets

**Comment by kowthalganesh** [comment]
Now. I fixed the issue by making isDefaultRender: false, Before rendering the DOM. Its trying to create the slider.. But NouiSlider handles are going outside of the base surface
![image](https://user-images.githubusercontent.com/5681640/40778636-7b8d1a8a-64ef-11e8-8da4-a315e75bfb93.png)
```
Survey.JsonObject.metaData.addProperty("checkbox", {
      name: "renderAs",
      default: "nouislider",
      choices: ["standard", "nouislider"]
    });
    let widget = {
      name: "nouislider",
      htmlTemplate: "<div id='slider'></div>",
      isFit: function(question) {
       return question["renderAs"] === 'nouislider';
      },
      isDefaultRender: false,
      afterRender: function(question, el) {
        let slider = el.querySelector("#slider");
        noUiSlider.create(slider, {
          start: 0,
          behaviour: 'tap',
          connect: true,
          step: 1,
          range: {
            'min': 0,
            'max': 5
          },
          tooltips: true
        });
        slider.noUiSlider.on('set', function() {
          question.value = slider.noUiSlider.get();
        });
      },
      willUnmount: function(question, el) {
        let slider = el.querySelector("#slider");
        slider.noUiSlider.destroy();
      }
    };
    Survey.CustomWidgetCollection.Instance.addCustomWidget(widget);
    let surveyModel = new Survey.Model(value);

```

**Comment by andrewtelnov** [comment]
@kowthalganesh Have you seen [this repo](https://github.com/surveyjs/surveyjs_angular_cli)
It supports our custom widgets.
You will have to include noUIslider only.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Arh, ok

**Comment by KhanUzair01** [comment]
I added custom jquery date  question, which works fine in surveyjs package. And I got the date picker too.
Then I installed SurveyJs package in Survey Editor, I dragged the date question and got the date properties on the right side. But when I click on preview, it throws me error. I debugged to see where it does, it throws error at this point SurveyEditor.tsx => onPreview () => this.editor.showTestSurvey();
<img width="950" alt="DateSurveyJs" src="https://user-images.githubusercontent.com/46099585/60668309-4b25fe00-9e89-11e9-8475-e29525efc4dc.PNG">

**Comment by andrewtelnov** [comment]
@KhanUzair01 It is very likely, that there is a JavaScript error in your custom widget code. Please debug and fix it.

Thank you,
Andrew

**Comment by chandu-magento** [comment]
Hi Folks,
I am getting this Error when I added a product in Cart,

![image](https://github.com/surveyjs/survey-library/assets/128086556/4fd711a9-4c3c-48d6-9dc8-35644c86e86e)

Is there anyone facing this Error, Please let me know how to resolve this console error.

Thanks in advance for your help.

**Comment by andrewtelnov** [comment]
@chandu-magento Is it code related to our libraries? I believe it is related to  require.js file from the framewokr you are using.

Thank you,
Andrew
