### ISSUE TITLE
Multi page survey with multitext component in first page

### ISSUE THREAD

**Issue by wcancino** [surveyjs/surveyjs#375]
### Are you requesting a feature, reporting a bug or ask a queation?
reporting a possible bug

### What is the current behavior?
I have a multipage survey, on the first page I have several questions,
one of them of type "multitext'". I load survey data directly from a json.

survey.data = myjson.

All values display correctly, except the one of multitext type, no values
are shown. However, when I go to the next page and then come back;
these values are showed correctly.

### What is the expected behavior?

Display correct values when display for the first time.

### How would you reproduce the current behavior (if this is a bug)?
- Create a multi page survey with at least one multitext type question on the first page
- load data from code

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

surveyjs last version (happens in older version too)
any browser have the same behaviour
jquery 3.2.1

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@wcancino It works in knockout platform, but doesn't work for jQuery for example. We will take a look.
For now, as a workaround set data in survey definition as for jQuery platform:
```
var survey = new Survey.Model(json);
$("#surveyContainer").Survey({
    model: survey,
    data : {"question1":{"text1":"1","text2":"2"},"question2":["1"]}
});

```

Thank you,
Andrew

**Comment by wcancino** [comment]
Thank you for your quick answer. It kind of works for me, but if I try to do it a second time (my app is a very long survey that can be loaded if not finished to be completed later), previous values remains on  multitext components (first page, others are ok). 

Regards

**Comment by wcancino** [comment]
OK, if I clear the div surveyContainer before recreate a survey, it works. Hope this helps.

**Comment by andrewtelnov** [comment]
@wcancino @tsv2013 I've just fixed the bug.

Thank you,
Andrew

**Comment by wcancino** [comment]
U welcome
