### ISSUE TITLE
Condition for VisibleIf

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#377]
Hi, i have a question... my survey's page is something like this:

- question1 (one checkbox with value "S" if it's checked)
- question2 (with visibleIf condition like "{question1} <> 'S'")

When the survey start, the second question will be visible, but is hidden, when i put the flag on question1 and then i remove this flag, the second question be shown

Why when the survey start, the condition not work? 

Thanks :)

**Comment by andrewtelnov** [comment]
@care46 Yes, we do not support <> yet. It makes sense to add it as well.
Please use !=, "{question1} != 'S'"

Thank you,
Andrew

**Comment by care46** [comment]
I have already try with !=, but it's the same.... i try with the online editor...
Maybe i miss something?

**Comment by andrewtelnov** [comment]
@care46 I just found a bug. It doesn't work when the {question1} is not setup. It will return false. I am working on the fix.

**Comment by care46** [comment]
Thanks! ;)

**Comment by andrewtelnov** [comment]
@care46 and in fact support for '<>' is already there. Sorry about misleading.
The fix will be in the next minor update, likely on this week.

Thank you,
Andrew

**Comment by care46** [comment]
Fantastic! ;)
Thanks!

**Comment by andrewtelnov** [comment]
@care46 Could you please check, if everything is fine with the new version?

Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov it's OK!!!!
