### ISSUE TITLE
 Is it possible to get the text of the response instead of its value?

### ISSUE THREAD

**Issue by fred433** [surveyjs/surveyjs#378]
I would like to use the text of a response instead of the value assigned to use it in the title of a next question.

Example:
Why did you respond {textquestion1} in the previous question?

Thanks :)

**Comment by andrewtelnov** [comment]
@fred433 Here is the example for jQuery version:
http://plnkr.co/edit/Xb2X8EOkz8lMrbuvOBE0?p=preview

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
There is no followup for a long time. I am closing the issue.
