### ISSUE TITLE
Nested matrixdynamic functionality

### ISSUE THREAD

**Issue by Kuhax** [surveyjs/surveyjs#380]
Hello. I would like to ask how to implement (or mimic) a nested matrixdynamic behaviour. Basically, for each row I would like to select an option from a dropdown and to add few other options by inserting more rows into the parent row.

<table>
<tr>
<td><b>Select a location</b></td>
<td><b>Select a supermarket</b></td>
<td><b>How often do you visit it ?</b></td>
</tr>
<tr>
<td>One neghbourhood</td>
<td>MonsterMart</td>
<td>Daily</td>
</tr>
<tr>
<td></td>
<td>Farmer's stall</td>
<td>Once a week</td>
</tr>
<tr>
<td></td>
<td><i>Add supermarket</i></td>
<td></td>
</tr>
<tr>
<td><i>Add location</i></td>
<td></td>
<td></td>
</tr>
</table>   

Current solution may be the following:

<table>
<tr>
<td><b>Select a location</b></td>
<td><b>Select a supermarket</b></td>
<td><b>How often do you visit it ?</b></td>
</tr>
<tr>
<td>One neghbourhood</td>
<td>MonsterMart</td>
<td>Daily</td>
</tr>
<tr>
<td>One neghbourhood</td>
<td>Farmer's stall</td>
<td>Once a week</td>
</tr>
<tr>
<td><i>Add row</i></td>
<td></td>
<td></td>
</tr>

</table>   

The issue with this approach is that you have to choose the same location for each supermarket, which takes a question much longer to complete. Also if you have another column for a department, for example, the question is even larger since you need to select same location and same supermarket for each department.

Is there another way to implement such behaviour using panels, maybe ? Or any other ideas ?

Thank you very much.

**Comment by andrewtelnov** [comment]
@Kuhax Unfortunately, there is no way to have the first variant. An end-user have to set the "Select a location". 
I may add an event onMatrixDymanicRowAdded - it will allow you to set the "Select a location" column value into new added row, based on the previous entered row value, for example.

Thank you,
Andrew

**Comment by Kuhax** [comment]
@andrewtelnov, your proposal of _onMatrixDynamicRowAdded_ event sounds good to me.

**Comment by andrewtelnov** [comment]
@Kuhax I've just added the event. Here is the example of using it:

```
    survey.onMatrixRowAdded.add(function(survey, options) {
        var q = options.question;
        var newValue = {};
        //from the previous row till the first one
        for(var i = q.rowCount - 2; i >= 0; i --) {
            var rowValue = q.getRowValue(i);
            //if the value in this row is set then 
            if(rowValue && rowValue["col1"]) {
                newValue["col1"] = rowValue["col1"];
                //set the value into the last, just added row
                q.setRowValue(q.rowCount - 1, newValue);
                break;
            }
        }
    });
```

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@Kuhax You may be interesting in this new functionality:

**Comment by andrewtelnov** [comment]
There is no followup for a long time. I am closing the issue.
