### ISSUE TITLE
Can you add specific CSS classes to specific elements created in the survey to be able to target and customize them?

### ISSUE THREAD

**Issue by mymagicalpants** [surveyjs/surveyjs#382]
### Are you requesting a feature, reporting a bug or ask a question?
I'm requesting a feature enhancement. I'd like to be able to give unique styling to elements like required questions, and the different types of buttons (previous, next and complete). But without specific CSS classes associated with them, I have to work very hard to target those elements.

### What is the current behavior?
Currently these elements are created without specific CSS classes.

### What is the expected behavior?
I would expect that these elements would have specific CSS classes associated with them.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version: 58.0.3029.96 (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.12.13

**Comment by andrewtelnov** [comment]
@mymagicalpants I am thinking about introducing an event, where you may specify the needed CSS classes and likely remove the default. Will event work for you?

Thank you,
Andrew

**Comment by mymagicalpants** [comment]
Hi Andrew,

Thanks for responding so quickly. I guess I should have included an example
of the dynamically created code. Currently these elements don't have a
default CSS class to remove:

REQUIRED QUESTION:
<div class="sv_row"><div id="sq_108" class="sv_q" style="display:
inline-block; vertical-align: top; width: 100%;"><h5
class="sv_q_title"><span>1. Who is your favorite coach of all time?
*</span></h5><input id="sq_108i" class="" type="text" size="25"
placeholder=""></div></div>

Currently, there is NO CSS class associated with this question either as a
whole or just within the <h5> that would designate it as required.

NAVIGATION:
<div class="sv_nav"><input class="" type="button" value="< Previous"
style="margin-right: 5px;"><input type="button" value="Complete" class=""
style="margin-right: 5px;"></div>

Currently, there is NO CSS class associated with either the Previous or
Complete button, so I have to do extra work to target them to give them
unique styling.

Preferred code would add the following example CSS classes: sv_q_required,
sv_prev, sv_complete.

<div class="sv_row"><div id="sq_108" class="sv_q *sv_q_required*"
style="display: inline-block; vertical-align: top; width: 100%;"><h5
class="sv_q_title"><span>1. Who is your favorite coach of all time?
*</span></h5><input id="sq_108i" class="" type="text" size="25"
placeholder=""></div></div>

<div class="sv_nav"><input class="*sv_prev*" type="button" value="<
Previous" style="margin-right: 5px;"><input type="button" value="Complete"
class="*sv_complete*" style="margin-right: 5px;"></div>

I would think this would be fine rather than having to add in functionality
to override default classes, but I'm sure some people would love that extra
level of customization.

Thanks again,
Scott

**Comment by dmitrykurmanov** [comment]
@mymagicalpants thanks for your proposal. We will add needed classes. 

As a workaround for naviagtion buttons you may set your own classes :
```
Survey.defaultBootstrapCss.navigation.complete = "my-complete-btn";
Survey.defaultBootstrapCss.navigation.prev = "my-prev-btn";
Survey.defaultBootstrapCss.navigation.next = "my-next-btn";
```

or for standard :

```
Survey.defaultStandardCss.navigation.complete = "my-complete-btn";
Survey.defaultStandardCss.navigation.prev = "my-prev-btn";
Survey.defaultStandardCss.navigation.next = "my-next-btn";
```

For example: https://jsfiddle.net/3yj61tv4/

And we will implemented special class for required questions.

**Comment by tsv2013** [comment]
We already have marker classes for navigation buttons:
{ complete: "sv_complete_btn", prev:"sv_prev_btn", next: "sv_next_btn" }

**Comment by tsv2013** [comment]
@mymagicalpants Can you specify - what exact html element of the question markup should be marked with "sv_q_required" class? I guess it should be the root `div` element of the question. Am I right?

**Comment by john1625b** [comment]
Hello has the feature to put specific classes/ids on certain questions been implemented?
If so how would I go about adding an id/class to a specific question or to the container of a specific page?

**Comment by jyclam** [comment]
I would also like to know if it's now possible to add an id/class to specific elements.

**Comment by andrewtelnov** [comment]
@mymagicalpants You may change page/panel/question id: myQuestion.id = "myUniqueId";
We are generating a unique id by using a static numeric property.

@tsv2013 Could you please comment about class element.

Thank you,
Andrew

**Comment by tsv2013** [comment]
@jyclam Probably this [example](https://surveyjs.io/Examples/Library/?id=survey-cssclasses) can help you.
