### ISSUE TITLE
Bug with "startWithNewLine" option

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#383]
HI,

i think there is a bug with the option "startWithNewLine"... i have a Json like this:

{
 pages: [
  {
   elements: [
    {
     type: "checkbox",
     choices: [
      {
       value: "S",
       text: "N.V."
      }
     ],
     indent: 1,
     name: "question1"
    },
    {
     type: "comment",
     name: "question2",
     startWithNewLine: false
    }
   ],
   name: "page1",
   navigationButtonsVisibility: "show"
  }
 ],
 showProgressBar: "bottom",
 showQuestionNumbers: "off"
}

There are 2 question, and the second have the option "startWithNewLine: false"

If the first question have not the option "indent:1", the survey work perfectly, but if the first question (like in my survey) have the option "indent:1", the second survey appear in new line and not in the same line...

I try this with online editor and survey.js 0.12.14

**Comment by andrewtelnov** [comment]
@care46 Yes, the problem with indent.
We will take a look at it.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@care46 I have fixed the bug. I am now using padding-left, instead of margin-left for indent. It solves the issue. 

Thank you,
Andrew

**Comment by care46** [comment]
In the online editor will be ok in this version 0.12.14? Or the fix will be included in 0.12.15?

**Comment by andrewtelnov** [comment]
@care46 Yes, it should be fixed with the next update. We will likely release it today.

There are still some issues with drag&drop panel when panel.startWithNewLine = false. I will fix it later.

Thank you,
Andrew
