### ISSUE TITLE
Bug : Title doesn't appear in survey (window mode) when using dxService

### ISSUE THREAD

**Issue by rsauvage** [surveyjs/surveyjs#385]
Hi Andrew,

The header of the window remains blank whereas the JSON returned by dxService contains a string in its "title" property. 
The title appears correctly when initializing the model directly with the said JSON in Survey.Model constructor. I'm not sure where it comes from yet but I'll keep looking and let you know otherwise.

Thanks

* browser: Chrome 58.0.3029.110 (64-bit) (Last version as of now I think)
* surveyjs platform : jQuery
* surveyjs version: 0.12.14

**Comment by andrewtelnov** [comment]
@rsauvage Yes, indeed it was a bug. I have fixed it.

Thank you,
Andrew

**Comment by rsauvage** [comment]
Great, many thanks Andrew !

Romain
