### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by gnchiesa** [surveyjs/surveyjs#386]
### Are you requesting a feature, reporting a bug or ask a question?
ask a question

### What is the current behavior?
I can't find any official doc on the library, event hooks, parameters, configuration options etc.

### What is the expected behavior?
Provide some kind of API description for library users/developers. Would you be so kind to put it up somewhere? maybe as part of the Readme.MD ? Thanks in advance! 

### How would you reproduce the current behavior (if this is a bug)?
-

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:-

Test code: -

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version: 58
* surveyjs platform (angular or react or jquery or knockout or vue): jquery (all?)
* surveyjs version: all

**Comment by andrewtelnov** [comment]
@gnchiesa We are working on it. I hope we will have the first draft on the next week.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@gnchiesa The first row documentation is ready. We are going to improve it greatly in the next months. We will add a large description for some topics, add links on demos and so on.
http://surveyjs.org/docs/
