### ISSUE TITLE
How do you start the project?

### ISSUE THREAD

**Issue by chrisformula** [surveyjs/surveyjs#387]
I have followed everything on the git page to install the project but it refuses to run can you please assist?

I have tried npm start, npm run and nothing works. Well karma start works but it does not give me the project view.

Please assist?

**Comment by dmitrykurmanov** [comment]
@chrisformula hello, what exactly went wrong? 
Do you have any error or stacktrace?
`npm run build_prod`  was successful?

**Comment by chrisformula** [comment]
Sweet thanks @dmitrykurmanov that worked but how can I get the Editor to work and actually start building surveys?

**Comment by dmitrykurmanov** [comment]
@chrisformula if I understand you correctly, [editor](https://github.com/surveyjs/editor) is another project. You can build it and use as well as surveyjs. It contains _example_ folder too.

**Comment by chrisformula** [comment]
do I use the same npm i live-server to build it?

**Comment by dmitrykurmanov** [comment]
@chrisformula you could install _live-server_ globally:  `npm i live-server -g` and use it in any folder.

**Comment by chrisformula** [comment]
awesome thanks ill try that

**Comment by dmitrykurmanov** [comment]
@chrisformula ok feel free to reopen this issue or post something else

**Comment by tsv2013** [comment]
I've implemented `npm start` command. @chrisformula - you can use after `npm i` (dev dependencies now contain `live-server` reference).
