### ISSUE TITLE
Integration with Angular js 1.x

### ISSUE THREAD

**Issue by bhaidar** [surveyjs/surveyjs#388]
Question:
Can I integrate this project with Angular js 1.x? 

Thanks

**Comment by tsv2013** [comment]
We discussed Angular 1.x integration in this thread -  [Support for Angular v1.6.1](https://github.com/surveyjs/surveyjs/issues/226)

**Comment by tsv2013** [comment]
We've decided to create an example how to integrate survey-knockout and survey editor into Angular 1.x application. It will be done in a nearest couple of days. @bhaidar Does it fit your needs?

**Comment by tsv2013** [comment]
@bhaidar  I've created a [repo](https://github.com/surveyjs/angular-seed), forked from angular-seed, and integrated survey-knockout library and [surveyjs-editor](https://github.com/surveyjs/editor).

**Comment by jducobu** [comment]
@tsv2013 , the repo you mention seems do not exist !

**Comment by andrewtelnov** [comment]
@jducobu We have removed this repo. After we created this repo, nobody really interested in it, so we stopped to support it and merge with changes from master repo.
It is easy to create a new repo using the latest sources from the current master branch.

Thank you,
Andrew

**Comment by jducobu** [comment]
@andrewtelnov , I didn't find angularjs in master repo !
I want to create a directive to integrate surveyjs, can you help me ?

**Comment by tsv2013** [comment]
We've deleted this branch since nobody interested and wanted to commited into it for more than 2 years.

**Comment by tsv2013** [comment]
@jducobu You can take as a start point this file - https://github.com/surveyjs/survey-library/blob/master/src/entries/angular.ts

The survey-angular is a wrapper over the survey-knockout library

**Comment by jducobu** [comment]
@tsv2013, i don't use angular 2+ as described in the file but angularjs 1.6

**Comment by tsv2013** [comment]
@jducobu I wanted to say that the wrapper for ng 1.x will be quite similar.
