### ISSUE TITLE
iCheck widget breaks survey navigation and data integrity

### ISSUE THREAD

**Issue by fz6** [surveyjs/surveyjs#389]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behaviour?

Using the icheck widget (described [here](http://surveyjs.org/examples/jquery/custom-widget-icheck.html)), the survey breaks in numerous ways:

- In my attached example, the third page of the survey becomes unreachable from the beginning. In another survey (with more questions on each page), the third (and final) page is initially reachable, but after navigating the pages (i.e. 1 -> 2 -> 3 -> 2 -> 1 -> 2 -> 3 -> 2 -> 1 -> 2), the third page becomes unreachable (no next button, as in the example provided).
 - The icheck bindings seem to get messed up after navigating the pages. For example, in the attached example, navigate back and forth between pages 1 and 2 half a dozen times without making a selection. Then, make a selection on page 1 and observe the fact the question on page 2 has also been updated with this value (this is also reflected in survey.data)

### What is the expected behaviour?

Navigation works correctly (page 3 is reachable), answering question 1 doesn't change the value of question 2 (and vice versa), as it does when the icheck widget is not used.

In the Plunker provided, toggle boolean `useICheck` at the beginning of `index.js` to see normal behaviour.

### How would you reproduce the current behaviour (if this is a bug)?

Explained in first section (current behaviour)

#### Provide the test code and the tested page URL (if applicable)

http://plnkr.co/edit/03qYXuwww4ZD5kWPYSfc?p=preview

### Specify your

* browser: Chrome
* browser version: ` 57.0.2987.133` (**edit** - fixed typo)
* surveyjs platform (angular or react or jquery or knockout or vue): `jquery`
* surveyjs version: `0.12.14`

**Comment by tsv2013** [comment]
It looks like the thing was in the proper icheck removing. I've made changes in the widget code:

```
var widget = {
    name: "icheck",
    isFit : function(question) { return question["renderAs"] === 'icheck'; },
    isDefaultRender: true,
    afterRender: function(question, el) {
        var $el = $(el);
        var select = function() {
          $el.find("input[value='" + question.value + "']").iCheck('check');
        }
        $el.find('input').iCheck({
          checkboxClass: 'iradio_square-blue',
          radioClass: 'iradio_square-blue'
        });
        $el.find('input').on('ifChecked', function(event){
          question.value = event.target.value;
        });
        question.valueChangedCallback = select;
        select();
    },
    willUnmount: function(question, el) {
        var $el = $(el);
        $el.find('input').iCheck('destroy');
    } 
}
```

I've tested it in your plunkr (thanks for providing it) and it works ok for me. I'll made corresponding changes in our examples.

**Comment by tsv2013** [comment]
I've updated example (http://surveyjs.org/examples/jquery/custom-widget-icheck.html).
