### ISSUE TITLE
Any better way to use matrixdynamic rows as input to another question's dropdown?

### ISSUE THREAD

**Issue by Gary-Mansell** [surveyjs/surveyjs#391]
### Are you requesting a feature, reporting a bug or ask a question?
Question/feature request.

### What is the current behaviour?
Can't find anything in the docs which mention doing this but using the onValueChanged and setting the choices property can get rather tedious with multiple questions.

### What is the expected behaviour?
By dynamically adding rows to question 1 (a matrixdynamic) have a particular column's input value appear within a dropdown for question 2. I'm not sure if I'm doing this the right way so if there's a better way please let me know.

#### Example code (my current approach):
```
onValueChanged: function (sender, options) {      
  var questionName = options.name;
  if (questionName === "question1") {
    var value = [];
    survey.getValue("question1").forEach(element => {
      value.push({ value: element.name});
    });
    survey.getQuestionByName("question2").choices = value; 
    survey.render();  // A .setChoices() which would handle single question redraws would be nice too
  } else if (anotherQuestion) { ... etc }
}
```

### Specify your

* browser: **Chrome**
* browser version: **57.0.2987.133 (64-bit)**
* surveyjs platform (angular or react or jquery or knockout or vue): **Angular**
* surveyjs version: **0.12.14 (Latest)**

**Comment by andrewtelnov** [comment]
@Gary-Mansell Could you please describe in more details your scenario. At the very moment, I am re-writing the matrix row generation and I want to implement some other features  in matrix dynamic/dropdown: cell visibility(cellVisibleIf), ability to show different questions types in the same column and some others. I would love to understand your scenario as well.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@Gary-Mansell Could you please take a look at new events I have introduced?

**Comment by andrewtelnov** [comment]
A plunker demo: http://plnkr.co/edit/eCNxoNUjNylXebBlEuDX?p=preview

**Comment by Gary-Mansell** [comment]
Hi Andrew, sorry for my slow reply and thanks for your quick one. 

The scenario I have is changing the dropdown for question 2 based on the values provided by question 1. The first question is a _matrixdynamic_ question so each row added by the user corresponds with a new value in a drop-down for question 2. It was quite tedious to do this using the _onValueChanged_ event for a question (especially when dealing with many questions) but the changes in #400 are very helpful, particularly the _onMatrixCellCreated_ event.

Thanks a lot for your help - I'll close this now as it looks like it'll be sorted in the next release.
