### ISSUE TITLE
Dynamic choicesByUrl in matrixdynamic dropdowns

### ISSUE THREAD

**Issue by Kuhax** [surveyjs/surveyjs#393]
Hello

I'm trying to implement a dynamic way to obtain data from restful service for different dropdowns scattered around my survey. I can't embed the URL in <b>choicesByUrl</b> field in the survey itself because it will be the same for all dropdowns. 

However, there is a (theoretical) way to do this via:
 
`var q = survey.getQuestionByName('country');
q.choicesByUrl.url = 'http://yourrestfullserviceurl';
q.choicesByUrl.run();`

but this approach won't work if 'country' is inside matrixdynamic.

Is there any way to set <b>choicesByUrl</b> via property or assigning an URL to a certain dropdown in a dynamic fashion ?

Example - the context of this can be the following: you want to implement different dropdowns filled with countries. Instead of obtaining all the countries from a web service, I would like to obtain them by continent via different URL.  Each survey is continent-wise, so first I would like to obtain a list of countries for any given continent assigning an URL to all matrixdynamic dropdowns dynamically.

**Comment by andrewtelnov** [comment]
@Kuhax It can be done on the column level: 
http://surveyjs.org/builder/#48323384-676a-46b6-b4be-8c10c8b5c0fb

**Comment by Kuhax** [comment]
@andrewtelnov yes, that's how I'm using it right now, but this way is static, since there is no way to change the URL afterwards, without editing the survey.

I'm asking for a way to change choicesByUrl of "Country" dropdown which is embedded in "question1".

In this example I can't set the value of state depending on the country -> http://surveyjs.org/builder/#10b18a9e-a03c-4576-bcc3-29b92f56467c

**Comment by andrewtelnov** [comment]
Aha, Do you want to have an ability to set the parameters in the URL?
like country -> state -> city?
I was thinking to add this functionality from the beginning, but then decided to wait until somebody actually ask for it :)
If the parameter is empty undefined, I was thinking do not run the service and if the parameters changed re-run it automatically.
Do you need parameters in URL only?

**Comment by Kuhax** [comment]
@andrewtelnov yes, the ability to set parameters in the URL works for me. I can get the parameter from my session scope.

**Comment by andrewtelnov** [comment]
@Kuhax hm, I was thinking about using a question value, like
http://myserviceurl.com/getCities?country={countryquestion}&state={statequestion}
it will run, when country question and state question are set.
I have another question, where do you want to use choicesByUrl, in standalone questions or in matrix column?
I'm thinking about adding value/parameter as {row.columnName}. It will return the value of columnName in the current row. It will work for matrix cells only.
Do you need it or it can be done later?

Thank you,
Andrew

**Comment by Kuhax** [comment]
@andrewtelnov using variables in the URLs is certainly useful, but I'm not sure it may be used by everyone, since it's kind of specific case. Imagine if URLs for getting countries and states would be totally different. There would be no way to use {countryquestion} or {statequestion} value to set a different URL to city selection dropdown.

So, the way I see it, overriding choicesByUrl with a specific URL is a more generic approach. In my case, the issue is that there is no way to set choicesByUrl to dropdown which is inside matrixdynamic coulmn. I would like to be able to set an URL to {matrixdynamic.column.dropdown} by code.

Finally, adding value/parameter as {row.columnName} makes sense, but in my case it wouldn't be useful, since I'm using matrixdynamic only throughout all my surveys.

**Comment by andrewtelnov** [comment]
@Kuhax In fact, as I understand, you need different editors in one column. There are already several requests that actually can be solved by having another editor in a particular cell based on value of other questions or column value in the same row.
It means there is a need in an event, that will allow to do it. Will it work for you?

Thank you,
Andrew

**Comment by Kuhax** [comment]
@andrewtelnov I'm not sure what do you mean by different editors per column. In this issue I'm referring to dropdowns embedded in matrixdynamic rows only.  I would like to set manually the property <b>choicesByUrl</b> for a dropdown column of a certain matrixdynamic.

Thanks

**Comment by andrewtelnov** [comment]
@Kuhax Do you need to change choicesByUrl for all editors in the column, for all rows, or you may have different choicesByUrl for different rows. I got the impression that you need to have different choicesByUrl for different rows in the same column.
Because if changing the choicesByUrl for all rows in one column doesn't work, it certainly a bug to me...

Thank you,
Andrew

**Comment by Kuhax** [comment]
@andrewtelnov I think I have resolved my issue partially because it's possible to change choicesByUrl for all editors in the column using 

`var q = survey.getQuestionByName('my_dropdown');`
`q.columns[0].choicesByUrl.url = "http://services.groupkt.com/state/get/IND/all";`
`q.columns[0].choicesByUrl.path = "RestResponse;result";`
`q.columns[0].choicesByUrl.valueName = "name";`
`q.columns[0].choicesByUrl.run();`

However, changing URLs of editors for other columns dynamically may require an event as suggested by you previously. After capturing newly selected value from one column via this event makes possible assigning certain choicesByUrl to another column.

**Comment by andrewtelnov** [comment]
@Kuhax We have add the ability to edit choicesByUrl for columns some times ago.

Thank you,
Andrew
