### ISSUE TITLE
Ability to add background color/image on pages.

### ISSUE THREAD

**Issue by smps2005** [surveyjs/surveyjs#394]
### Are you requesting a feature, reporting a bug or ask a question?
Requesting a feature.

### What is the current behavior?
Not possible to add background color/image on pages.

### What is the expected behavior?
Ability to add background color/image on pages.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
I like it.

**Comment by smps2005** [comment]
Thank you!

**Comment by tsv2013** [comment]
@smps2005 We discussed this issue and created a sample - how to change background color of whole survey or set background image via css: http://plnkr.co/edit/1iqtiLbJkIUdMtrufy06?p=preview . You can check `index.css` file. Does it fit your needs?

**Comment by andrewtelnov** [comment]
No reply for several months. I am closing the issue.

**Comment by ehtishamzaki** [comment]
@tsv2013 the above liink not working giving me 502 Bad gateway, Can you please provide new link.

**Comment by tsv2013** [comment]
Here is the updated plunker sample - http://plnkr.co/edit/PPklcV1iAhTqxDCh
