### ISSUE TITLE
It's possibile to add different css classes to question and answer?

### ISSUE THREAD

**Issue by enrico-dont** [surveyjs/surveyjs#397]
Hi! I'm trying to setup a survey like a text session (whatsapp or similar) and i have to separate questions and answers in two different classes, something like:

.questions {float: left;}

.answers {float: right;}

If I made any error please forgive me, i'm new here

Thanks a lot

E.

**Comment by andrewtelnov** [comment]
@enrico-dont Unfortunately, I can't see a way to do it. We may to implement it in multiple text question. Do you have a text inputs only?

Thank you,
Andrew
