### ISSUE TITLE
JSON data with "COMMENT" question

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#399]
Hi,

i have a survey (jquery version) with a "COMMENT" question... when i save the survey, JSON data response with:

{"question1":"2013-01-01","question2":"hello","question3":"text text\nnew line new line\nhello hello"}

If i open the survey passing this JSONData, the survey don't load the answers, if i modify the response and i open the survey with a JSON like this

{"question1":"2013-01-01","question2":"hello","question3":"text text new line new line hello hello"}

where i have removed the "\n" character, the survey was opened correctly and the answers was loaded

Maybe there is a bug with COMMENT QUESTION where the users write in multiline?

Thanks ;)

**Comment by andrewtelnov** [comment]
@care46 Hm, I have just tried. It works fine to me:
http://plnkr.co/edit/naIDI7mXTmkkYnI2j0sN?p=preview

Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov sorry, i see your test and i made a mistake! Now it work correctly!!

Thanks

**Comment by care46** [comment]
@andrewtelnov now the answers was initialized correctly, but in "display" mode, "COMMENT" question was displayed like in one row... i try with your example...

**Comment by andrewtelnov** [comment]
@care46 Yes, this one is a bug. We are using span to render "comment" question in display mode. It is better to add read only attribute.
I will correct this.

Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov ok no problem, now i use a workaround, i open survey in edit mode an then at event "afterPageRendered" i set only input/select/textarea in readonly..

Thanks

**Comment by andrewtelnov** [comment]
@care46 It is fixed.

Thank you,
Andrew
