### ISSUE TITLE
Converting Results and Questions into Word or PDF or Excel

### ISSUE THREAD

**Issue by krishnathamisetty** [surveyjs/surveyjs#401]
### Are you requesting a feature, reporting a bug or ask a question?
Question Feature

### What is the current behavior?
We would like to download the user response into Word or PDF or Excel questions and along with user response.
Like we need same as is along with Download (options: PDF, Word, Excel) http://surveyjs.org/examples/jquery/survey-displaymode.html
by clicking on download user should get the above link output in  PDF, Word, Excel.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@krishnathamisetty I am not sure what do you mean to save results in pdf/excel/word. Do you mean all survey results or just for one user?
We have http://www.dxsurvey.com service. You may use it. It is free for now, . You may export all data to Excel. Here is the public result page of one our surveys: https://dxsurvey.com/Results/Survey/d5220f76-4802-40cf-ad67-61d7e55608e5. There is the Export button and export to Excel in the popup menu.

Anyway, surveyjs library gives you result as Json you are free to do with it what you want. The integration with dxsurvey.com is easy and straight forward. Of course you are free to use any other services or create your own.

Thank you,
Andrew

**Comment by nategasm** [comment]
Not sure if this is what you're after, but if you want an offline solution, I'm using docxtemplater for one of my projects with surveyjs. https://docxtemplater.readthedocs.io/en/latest/index.html
You just feed it the Json and a pre-defined word template with the questions and response tags. Then when you "Download" after the survey is completed it will give you the generated word document with responses.

**Comment by SaharDastitash** [comment]
Hello,

I don't see the javascript/code part of the export button. How can I use it ?

**Comment by SaharDastitash** [comment]
Or Is there any features that I can print the result of my questions and it's answers?

**Comment by andrewtelnov** [comment]
@SaharDastitash Here is the [example of exporting to PDF](https://plnkr.co/edit/riq0aC5BCQRDYZiK?p=preview)
What do you mean by "export button"?

Thank you,
Andrew
