### ISSUE TITLE
It's possible to setValue in matrix?

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#402]
This function

survey.setValue('questionName', newValue);

is applicable to matrixdropdown or matrixdynamic? 
How can I do this to specify  the row to set the value?

Thanks

**Comment by andrewtelnov** [comment]
@care46 sure. it is pretty much the same.
matrixdynamic - it is an array of objects. To set the first and third row you have to:
`[{"myFirstColumn": value1_1, "mySecondRow": value1_2}, {}, {"myFirstColumn": value3_1, "mySecondRow": value2_2}]`
For matrix dropdow there is a value for a row, so you have:
`{"myFirstRowValue": {"myFirstColumn": value1_1, "mySecondRow": value1_2}, "myThirdRowValue": {"myFirstColumn": value3_1, "mySecondRow": value2_2}}`

I hope it is more clear now.

Thank you,
Andrew

**Comment by care46** [comment]
ook! i understand ;)

**Comment by maltacon** [comment]
I'm trying to set value to a matrixdynamic programatically without success.
I tried: `survey.setValue('LastMatrix',[{"TimeUnit":"min"},{"TimeUnit":"min"},{"TimeUnit":"min"}]);`
But nothing happens, not even errors.
Any suggestions?

**Comment by andrewtelnov** [comment]
@maltacon Set some values into your matrix and look at the survey.data property in console, you will see the JSON data for your matrix dynamic question. You may misspell a question name or column name(s) and so on.

Thank you,
Andrew

**Comment by maltacon** [comment]
I don't think that's the case. My result is as follows:
```
result:{  
   "CustomDisk":[  
      {  
         "Layer":1
      }
   ],
   "LastMatrix":[  
      {  
         "ID":1,
         "TimeUnit":"min",
         "VariableVolume":11,
         "VariableWaitTime":111
      },
      {  
         "ID":2,
         "TimeUnit":"min",
         "VariableVolume":22,
         "VariableWaitTime":222
      },
      {  
         "ID":3,
         "TimeUnit":"hour",
         "VariableVolume":33,
         "VariableWaitTime":333
      }
   ],.........
```

**Comment by andrewtelnov** [comment]
@maltacon It works fine in [my example](https://plnkr.co/edit/TPthwxhPESZcpgavYhwe?p=preview)

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
>  I see the following error: Uncaught TypeError: Cannot convert undefined or null to object

Could you please provide a full stack trace or json to reproduce the error?

**Comment by dmitrykurmanov** [comment]
@maltacon I am sorry I've missed your plunker link. I've saw the error. We will work on it.

**Comment by dmitrykurmanov** [comment]
@maltacon we've fixed the issue, fix will be available in the next minor update.
