### ISSUE TITLE
Example jQuery code on surveyjs.org/examples doesn't work

### ISSUE THREAD

**Issue by batmanbury** [surveyjs/surveyjs#403]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug

### What is the current behavior?

Example on http://surveyjs.org/examples/jquery/custom-widget-image-picker.html doesn't render images as choices. I get the following error:
```
Uncaught TypeError: $el.imagepicker is not a function
```

### What is the expected behavior?

The provided example code should render images as choices.

### How would you reproduce the current behavior (if this is a bug)?

Copy the code provided here to setup: http://surveyjs.org/examples/jquery/custom-widget-image-picker.html

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: 
http://surveyjs.org/examples/jquery/custom-widget-image-picker.html

### Specify your

* browser: Chrome
* browser version: 58
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery
* surveyjs version: 0.12.15

**Comment by tsv2013** [comment]
Probably you need to include image-picker library code on your page:
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/image-picker/0.3.0/image-picker.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/image-picker/0.3.0/image-picker.css" />
```

**Comment by batmanbury** [comment]
Of course! That was not immediately obvious to me. Thanks!
