### ISSUE TITLE
Matrix (dynamic rows) and Custom Widgets

### ISSUE THREAD

**Issue by ImanuelRichter** [surveyjs/surveyjs#404]
### Are you requesting a feature, reporting a bug or ask a question?
question, requesting a feature

### What is the current behavior?
Custom Widgets like select2 and select2tagbox work fine on other pages but not in dynamic Matrix

### What is the expected behavior?
Custom Widgets like select2 and select2tagbox are rendered within dynamic Matrix like usual

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code
{
 "type": "matrixdynamic",
 "addRowText": {
  "de": "Hinzufügen"
 },
 "columns": [
  {
   "name": "usedTPM",
   "title": "Genutzte Transportmittel",
   "choices": [
    {
     "value": "pedestrian",
     "text": "Zu Fuß"
    },
    {
     "value": "bike",
     "text": "Fahrrad"
    },
    {
     "value": "train",
     "text": "Bahn"
    },
    {
     "value": "bus",
     "text": "Bus"
    },
    {
     "value": "publicCar",
     "text": "Taxi/Car sharing/Mietauto"
    },
    {
     "value": "privateCar",
     "text": "Privates Auto"
    },
    {
     "value": "motorbike",
     "text": "Motorrad, Moped, Mofa"
    }
   ],
   "cellType": "dropdown",
   "renderAs": "select2tagbox",
   "isRequired": true,
   "hasOther": true
  },
  {
   "name": "destination",
   "title": "Ziel",
   "cellType": "dropdown",
   "renderAs": "select2",
   "isRequired": true,
   "choicesOrder": "asc",
   "choicesByUrl": {
    "url": "de/locations.json",
    "valueName": "name",
    "titleName": "name"
   }
  }
 ],
 "isRequired": true,
 "minRowCount": "1",
 "name": "diary",
 "removeRowText": {
  "de": "Entfernen"
 },
 "rowCount": "1",
 "title": {
  "de": "Läuft nicht wie es soll..."
 }
}

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.12.15

**Comment by tsv2013** [comment]
@ImanuelRichter Can you check the https://github.com/surveyjs/surveyjs/issues/384 thread? It looks like we've solved almost all the problems.

**Comment by tsv2013** [comment]
The http://plnkr.co/edit/KDQZBx3zvJTtprzpQvd4?p=preview plunk illustrates salest2tagbox custom question in the matrix dynamic.

**Comment by ImanuelRichter** [comment]
wow thx for your very quick response! i'll check that out. Sorry if i wasted your time.
You are doing a great job here!

**Comment by tsv2013** [comment]
It's ok, @ImanuelRichter! You are always welcome!
