### ISSUE TITLE
Problem with selector at page change

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#405]
Hi, i have this problem... i have a survey on 2 page.. in first page i have a matrix (2 row 2 column)... i use question selector to view the item in chrome console like this

a = $('#sq_117i')     --> first row column 2

If i print this in console, the result is:
[input#sq_117i.form-control, context: document, selector: "#sq_117i"]

Now i go to second page of the survey, if i print var a in console, i get the same result like before:
[input#sq_117i.form-control, context: document, selector: "#sq_117i"]

Now i come back to first page.... now there is a problem.. if i print var a in console, i get this:
[input#sq_116i.form-control, context: document, selector: "#sq_117i"]

WHY the selector is the same "#sq_117i" but the associated object was changed in "#sq_116i"????

Thanks for all

bye

**Comment by dmitrykurmanov** [comment]
@care46 hello! thanks for your interest. Could you please provide a plunker example with the same behaviour?

You can get plnkr examples at:
* Angular2 http://plnkr.co/edit/OJkKlUn1oxzWYtnruXir?p=preview
* jQuery http://plnkr.co/edit/DH4vJWSBtza7bSCDm2r9?p=preview
* Knockout http://plnkr.co/edit/JKy5wwiAhaBTMze3fOO0?p=preview
* React http://plnkr.co/edit/qXdeQa6x2FHRg0YrOlPL?p=preview
* Vue http://plnkr.co/edit/aTYVAiDvMWOf3zDReayE?p=preview

**Comment by care46** [comment]
In this example there is not a problem... if i try to get in console a = $('#sq_103'), the return value is

[input#sq_103i.form-control]

There is no context and selector like in my survey... 

Probably something different in library or in jquery version?

**Comment by dmitrykurmanov** [comment]
@care46 What version of survey-jquery do you use ? You may try to use last version of survey-jquery in your example 
`<script src="https://unpkg.com/survey-jquery"></script>` or from our cdn
`<script src="https://surveyjs.azureedge.net/0.12.15/survey.jquery.js"></script>`

or you can modify plunkr example with your json and reproduce it.

**Comment by care46** [comment]
Now i try with your link of library... the problem is the same.... then, i try to put my json in your jquery example... i have a problem also in this... then probabily the bug is related to my json definition...
My json is this..

var json = {"locale":"it","pages":[{"name":"PAGINA         1","elements":[{"title":"aaaaaa","name":"HAU0000000000000001","innerIndent":1,"type":"panel","elements":[{"name":"pdsdlwfjjdanhjteaxta","innerIndent":0.0,"startWithNewLine":true,"type":"panel","elements":[{"name":"HAU0000000000000001HTML","html":"<div class='cerchio'><\/div><div class='maintitlequestion'>Quando è nato il tuo primo animale domestico?<\/div>","type":"html"},{"name":"HAU0000000000000001INFO_HTML","html":"<div class='magginfo'><a href=\"javascript:void(0)\" onclick=\"javascript:if(document.getElementById('fbkntrnpym').style.display == 'none'){document.getElementById('fbkntrnpym').style.display = 'block';document.getElementById('vedmegotsq_IMG').src = '..\/images\/hiqm_icollapse.png'} else {document.getElementById('fbkntrnpym').style.display = 'none';document.getElementById('vedmegotsq_IMG').src = '..\/images\/hiqm_iexpand.png'}; \" > <span id = 'vedmegotsq' class = 'infosurvey'>Maggiori informazioni<\/span> <img id='vedmegotsq_IMG' src='..\/images\/hiqm_iexpand.png' tabindex='-1' style='vertical-align: middle;'><\/a><\/div><div id='fbkntrnpym' class = 'infoaggsurv' style = 'display:none';>blA BLA BLA VBLAS VBLA+\nGVJMASDOPCVNWSV\nSDIOVNASDOVAS+ùDFVJOQGVOAERBasùrgasrg\nqaerg\nardg\nadrg\nadr\ngadr\nga\ndrga\ndrg\nadrg\nadrg\narg\narg\nadrg\narg\ng<\/div>","type":"html"},{"title":"Inserire la data","placeHolder":"","isRequired":false,"inputType":"date","name":"HAU00000000000000011","startWithNewLine":true,"visibleIf":"","type":"text"}]},{"name":"wewswkxlmlbizpowpslb","innerIndent":0.0,"startWithNewLine":true,"type":"panel","elements":[{"name":"HAU0000000000000002HTML","html":"<div class='cerchio'><\/div><div class='maintitlequestion'>Domanda data e ora<\/div>","type":"html"},{"name":"HAU0000000000000002REM_HTML","html":"<div class='specifiche'><p>ciao ciao<br \/>prova prova<br \/>pippo pippo<\/p><\/div>","type":"html"},{"title":" ","placeHolder":"","isRequired":false,"inputType":"datetime-local","name":"HAU00000000000000021","startWithNewLine":true,"visibleIf":"","type":"text"}]}]},{"title":"Area per matrici","name":"HAU0000000000000004","innerIndent":1,"type":"panel","elements":[{"title":"Area figlia","name":"HAU0000000000000005","innerIndent":1,"type":"panel","elements":[{"name":"jvcedhukemqyekabaiwh","innerIndent":0.0,"startWithNewLine":true,"type":"panel","elements":[{"name":"HAU0000000000000009HTML","html":"<div class='cerchio'><\/div><div class='maintitlequestion'>Matrice data e testo senza intestazione<\/div>","type":"html"},{"title":" ","isRequired":false,"name":"HAU00000000000000091_MATFIX","columns":[{"title":" ","cellType":"text","name":"HAU00000000000000091","inputType":"date"},{"placeHolder":"","title":" ","cellType":"text","validators":[{"maxLength":"150","type":"text"}],"name":"HAU00000000000000092"}],"startWithNewLine":true,"rowCount":2.0,"visibleIf":"","type":"matrixdropdown","rows":[{"text":" ","value":"ROW0"},{"text":" ","value":"ROW1"}]}]}]}]}]},{"name":"PAGINA         2","elements":[{"title":"Area per matrici","name":"HAU0000000000000004","innerIndent":1,"type":"panel","elements":[{"name":"rrejabtaricigxbmavqr","innerIndent":0.0,"startWithNewLine":true,"type":"panel","elements":[{"name":"HAU0000000000000010HTML","html":"<div class='cerchio'><\/div><div class='maintitlequestion'>Matrice con titoli<\/div>","type":"html"},{"title":" ","removeRowText":"Rimuovi","isRequired":false,"name":"HAU00000000000000101_MATREP","columns":[{"title":"Colonna 1","cellType":"checkbox","choices":[{"text":"Primo valore checkbox","value":"0000000001"},{"text":"Secondo valore checkbox","value":"0000000002"}],"name":"HAU00000000000000101","colCount":1},{"placeHolder":"","title":"Colonna 2","cellType":"comment","name":"HAU00000000000000102"},{"title":"Colonna 3","cellType":"text","name":"HAU00000000000000103","inputType":"datetime-local"}],"startWithNewLine":true,"rowCount":1.0,"visibleIf":"","type":"matrixdynamic","minRowCount":0.0,"maxRowCount":2.0,"addRowText":"Aggiungi"}]},{"title":"Area figlia","name":"HAU0000000000000005","innerIndent":1,"type":"panel","elements":[{"name":"zngzbzwfykudstqjnkrt","innerIndent":0.0,"startWithNewLine":true,"type":"panel","elements":[{"name":"HAU0000001000000009HTML","html":"<div class='cerchio'><\/div><div class='maintitlequestion'>Matrice fissa con intestazione<\/div>","type":"html"},{"title":" ","isRequired":false,"name":"HAU00000010000000091_MATFIX","columns":[{"cellType":"radiogroup","placeHolder":"","title":"colonna 1","choices":[{"text":"Primo valore checkbox","value":"0000000001"},{"text":"Secondo valore checkbox","value":"0000000002"}],"name":"HAU00000010000000091","colCount":2.0},{"cellType":"radiogroup","placeHolder":"","title":"colonna 2","choices":[{"text":"Primo valore checkbox","value":"0000000001"},{"text":"Secondo valore checkbox","value":"0000000002"}],"name":"HAU00000010000000092","colCount":1}],"startWithNewLine":true,"rowCount":2.0,"visibleIf":"","type":"matrixdropdown","rows":[{"text":" ","value":"ROW0"},{"text":" ","value":"ROW1"}]}]}]}]},{"title":"'frfrffrfr'","name":"0000000000000000001","innerIndent":1,"type":"panel","elements":[{"name":"djzcdcqdukgijnatrkum","innerIndent":0.0,"startWithNewLine":true,"type":"panel","elements":[{"name":"HAU0000000000000007HTML","html":"<div class='cerchio'><\/div><div class='maintitlequestion'>Domanda radio orizzontale<\/div>","type":"html"},{"title":" ","placeHolder":"","isRequired":false,"choices":[{"text":"Primo valore checkbox","value":"0000000001"},{"text":"Secondo valore **checkbox","value":"0000000002"}],"name":"HAU00000000000000071","startWithNewLine":true,"visibleIf":"","colCount":4,"type":"radiogroup"}]}]}]}],"clearInvisibleValues":true};** 

If i use this definition in your jquery example and in chrome console i try to print
 a = $('#sq_115i')

the value of a is 
[input#sq_115i.form-control]

then if i change to second page and return to first, if a reprint the valie of a, the result is
[input#sq_105i.form-control]

I don't know why!!

**Comment by dmitrykurmanov** [comment]
@care46 ok thanks for the explanations, we'll try to solve it with your json.

**Comment by dmitrykurmanov** [comment]
@care46 I copy and paste your json and it is not valid:

http://plnkr.co/edit/tuCR8vI9BK6uWqf5ZGMI?p=preview

Could you please fix it and give a fixed link on plunker?

**Comment by care46** [comment]
@dmitrykurmanov  sorry, copy and paste for my json not work correctly because there is some html in thst string..

This is the plunker link correct

http://plnkr.co/edit/uexUcVUDrEXoeMWuNBEe?p=preview

thanks

**Comment by dmitrykurmanov** [comment]
@care46 we are using preact for jquery and angular. So this behaviour is caused by preact chaching algorithm. It doesn't recreate dom and uses existing dom elements if it possible.

You are holding the reference to the dom element `a = $('#sq_115i')` . After page changed pareact stores this element to the internal cache. After another re-rendering preact takes this input element from cache, assigns another properties including id, and put this element into dom. At the same time you are holding the reference to this element which is now have another attributes - another id.

So after page change you need to recall `a = $('#sq_115i')`  to get this element. What is your use case?

**Comment by care46** [comment]
@dmitrykurmanov My problem is this ...

At the "onAfterRenderQuestion" event, I call a function to set a specific css class to a specific element, in particular I set a class to "date" elements with document.getElementById (idtmp) .className = "form-control inputDate";

Then, when I change the page and go back to the first, for this problem of the selector, the survey renders another element with the "date" class and not just the element that I worked with my function ...

**Comment by care46** [comment]
@dmitrykurmanov i have make an example

http://plnkr.co/edit/c86LjAIMlFr6mP3L255h?p=preview

when the survey was rendered at first time, you can see that the first and the second question have my class (InputDate), but the matrix at the and of the page have not this class (in particular the second column in second row)... then if you go to second page and come back to the first, you can see that the first and the second question have the class (like before), but the field in second row/second column of the matrix have the class, but i don't apply this class to that element..

**Comment by tsv2013** [comment]
In this case I'd recommend you the following widget customizer:

```
	var widgetCustomizer = {
	  name: "customizer",
	  isDefaultRender: true,
	  isFit: function(question) {
	    return question.getType() === 'text';
	  },
	  afterRender: function(question, el) {
	    if(question.inputType === 'date') {
	      $(el).find("input.form-control").addClass("inputDate");
	    }
	    if(question.inputType === 'datetime-local') {
	      $(el).find("input.form-control").addClass("inputDateTime");
	    }
	  },
    willUnmount: function(question, el) {
      $(el).find("input.form-control").removeClass("inputDate").removeClass("inputDateTime");
    } 
	}
	Survey.CustomWidgetCollection.Instance.addCustomWidget(widgetCustomizer);

var model = new Survey.Model(json);

model.onComplete.add(function(result) {
  document.querySelector('#result').innerHTML = "result: " + JSON.stringify(result.data);
});

$("#surveyElement").Survey({
  model: model,
  //onAfterRenderQuestion: doOnAfterRenderQuestion
});

```

And I've commented `onAfterRenderQuestion` event handler. Does it fit your needs?

**Comment by care46** [comment]
@tsv2013 Thanks! I'll try this way!

**Comment by tsv2013** [comment]
@care46 Here is updated plunk - http://plnkr.co/edit/TZjijQupMPrSvke9Dr3g?p=preview
