### ISSUE TITLE
Question: Is surveyjs compatible with Bootstrap 4?

### ISSUE THREAD

**Issue by batmanbury** [surveyjs/surveyjs#406]
### Are you requesting a feature, reporting a bug or ask a question?
Ask a question:

Is surveyjs compatible with Bootstrap 4? (currently v4.0.0-alpha.6)

* surveyjs platform (angular or react or jquery or knockout or vue): **jquery**
* surveyjs version: **0.12.15**

**Comment by dmitrykurmanov** [comment]
@batmanbury hello! We need to try it. Thanks.

**Comment by thomas-gt** [comment]
+1
