### ISSUE TITLE
Indecisive user, two dependent questions with same name, wrong output

### ISSUE THREAD

**Issue by onlyjsmith** [surveyjs/surveyjs#407]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug (on an awesome set of tools!)

### What is the current behavior?
To navigate a wide tree of response options, we're using the response to an initial question to conditionally (`visibleIf`) show one of two dependent questions. We only ever want one answer from the dependent questions, so both have the same `name` (not sure if this approach is recommended, but it's possible and doesn't throw any errors, except for this bug!)

Currently, there's a difference between what's displayed using the `visibleIf` logic, and what's collected in the survey output. This happens if you change your mind a couple of times filling in the survey.

In the sample below, click 'true' on first Q, 'trueA' on second Q, then back to 'false' on first Q, now 'falseA' on second Q, and finally back to 'true' on first Q. 

- What you _see_ on the survey interface is 'true' and 'trueA'.
- When you complete, the response is ` {"initial_question":"true","dependent_question":"falseB"}`
- The response should be {"initial_question":"true","dependent_question":"trueA"}`

#### Provide the test code and the tested page URL (if applicable)

Sample survey code (also [published as this](https://dxsurvey.com/published?id=50212349-100b-45a7-8a6e-829be571b002))

```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "radiogroup",
     "choices": [
      "true",
      "false"
     ],
     "name": "initial_question",
     "title": "True or false"
    },
    {
     "type": "dropdown",
     "choices": [
      "trueA",
      "trueB"
     ],
     "name": "dependent_question",
     "title": "Show this if true",
     "visible": false,
     "visibleIf": "{initial_question} = 'true'"
    },
    {
     "type": "dropdown",
     "choices": [
      "falseA",
      "falseB"
     ],
     "name": "dependent_question",
     "title": "Show this if false",
     "visible": false,
     "visibleIf": "{initial_question} = 'false'"
    }
   ]
  }
 ]
}

```

### Specify your

* browser: Chrome 58
* surveyjs platform (angular or react or jquery or knockout or vue): SurveyJS editor online, survey-vue
* surveyjs version: ?? for editor online, 0.12.15 for survey-vue

**Comment by dmitrykurmanov** [comment]
@onlyjsmith hello! Questions should not have the same name. @andrewtelnov @tsv2013 may be we need to add this info into docs.

**Comment by Nicolaidavies** [comment]
@dmitrykurmanov First of all, thank you for creating a great library.

I work with @onlyjsmith, we have and issue where a dependent question’s options needs to change in response to another question.

An example of this would be choosing a state in the first question and a city name in the second question.  The city names would change depending on which state you choose.

Our current approach has multiple questions called “city” and are shown with visibleIf depending on the state selected. What is the recommended way to achieve this without having questions with the same name?

Using the examples provided we tested our form with multiple questions with the same name. We found that the Vue version did not work with questions with the same name, but the jQuery version did.

**Comment by dmitrykurmanov** [comment]
@Nicolaidavies yes, I see the problem. @andrewtelnov could you help with it please?

**Comment by dmitrykurmanov** [comment]
@onlyjsmith  @Nicolaidavies  as @andrewtelnov says we could use same name for questions, so it is bug. We'll fix it. Thanks for your interest.

**Comment by andrewtelnov** [comment]
@Nicolaidavies They bug is in the vue version and it should be fixed. 
However, I have a question to you guys. Are you going to use some kind of restful API to get the list of countries -> states -> cities ?
I want to introduce a feature, for restful API: http://surveyjs.org/examples/jquery/questiontype-dropdownrestfull.html, where a question value can be used in a parameter in the url.
for example: myapiwebsite.com/getAllCities/state={stateQuestion}. If the stateQuestion is empty, the city question choices is empty, as soon as the state is changed, the library will call the restful service to get cities for this state.
Do you need this functionality?

Thank you,
Andrew

**Comment by Nicolaidavies** [comment]
@andrewtelnov Thank you very much. 

Right now I don't think we are in need of such functionality, as we are building an offline application. I definitely can see how that functionality would be useful in other contexts.

**Comment by andrewtelnov** [comment]
@Nicolaidavies I am afraid we will not be able to fix this issue in vuejs.
Here is what happens: The value is changed in the 'dependent_question' dropdown and survey is sending the notification about value changing to all questions with this name 'dependent_question'. When another 'dependent_question' dropdown gets the notification it looks in it's choices, finds no item for it and as result set the value to null. The survey get notification that 'dependent_question' becomes null and again sends a notification about value changed to all question with the 'dependent_question' name. As result the initial question will get a null value as well.
In other platforms, we wrote a code that will not allow to call set value in the question object twice (recursive). Vuejs doesn't call the change immediately, like knockout for example, and the second set value is called after the initial set value call has completely finished it's work. 

Anyway here is my suggestion: onValueChanged assign to 'dependent_question' dropdown question a different choices based on the "initial_question" like:
```
survey.onValueChanged.add(function(survey, options) {
  if(options.question.name !== "initial_question") return;
  var q = survey.getQuestionByName("dependent_question");
  if(options.question.value == "true") q.choices = ["trueA", "trueB"];
  if(options.question.value == "false") q.choices = ["falseA", "falseB"];
});
```
Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@Nicolaidavies We have the question.valueName property now. If it is set then this property use instead of question.name. It means you may have questions with different names, but they may share the same data if they have the same valueName.

Thank you,
Andrew
