### ISSUE TITLE
Bug on event onVisibleChanged

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#408]
Hi, with the last version of the library (jquery version), the event onVisibleChanged do not start when question visibility change... with the previous version works fine..

I have also a question: with this event i can do an action when a question change visibility, there is also an event that i can use when i add a row in matrixdynamic?

Thanks

**Comment by andrewtelnov** [comment]
@care46 http://plnkr.co/edit/ixreiariosLIPSoJVeMx?p=preview
Please change the second question, "2. How satisfied are you with the Product?".
You can't set onVisibleChanged in definition. I will fix it, however, it always worked this way.

Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov 

Thanks.. my js definition is something like this:

		model.Survey({	
			onComplete:sendDataToServer,
			onCurrentPageChanged: doOnCurrentPageChanged,
			onAfterRenderQuestion: doOnAfterRenderQuestion,
			onVisibleChanged: doOnVisibleChanged,
			onAfterRenderPage: doOnAfterRenderPage,
		});

I wrote this issue because the function doOnVisibleChanged wasn't fire in 0.12.15, but in previous version work fine...

In this example, there is also an event then i can define to show an alert where the user add a row in matrixdynamic?
 
Thanks very much

**Comment by andrewtelnov** [comment]
@care46 Sure: http://surveyjs.org/docs/api_surveymodel.html#onMatrixRowAdded

Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov  Thanks, it will be available in 0.12.16 like the "startWithNewLine" option in "panel" right?

**Comment by andrewtelnov** [comment]
@care46 yes, you are right. We will release today or tomorrow or definitely after tomorrow :)
