### ISSUE TITLE
Hide answered rows in Matrix and store answers before completing.

### ISSUE THREAD

**Issue by GreatEarl** [surveyjs/surveyjs#409]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
I have Matrix question with about 30 rows and 10 radiobuttons in each row. 
Everything works fine.

### What is the expected behavior?
Is there any way to hide row which was answered? 
I mean - when user picks one of ten radiobuttons (answers) in row - that row should be hided.

And by the way - is there any method to take Matrix rows answers "on-the-fly" before completing survey? 
### How would you reproduce the current behavior (if this is a bug)?
it is not a bug

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
Test code
```
your_code_here
```
### Specify your
* browser: Chrome
* browser version: 58.0.3029.110 (64-bit)
* surveyjs platform -  jquery 
* surveyjs version: latest

**Comment by andrewtelnov** [comment]
@GreatEarl Are you talking about this? http://plnkr.co/edit/hDXPsZk3HhpyxnBqGoRO?p=preview 

Thank you,
Andrew

**Comment by GreatEarl** [comment]
@andrewtelnov  Thanks Andrew, that's it!  And is there any way to reset answers of question like this? I'll explain - I want to hide rows when user answers but I need to give him ability to reset answers only on current question if he think that some answers were wrong. May be there is a method to reinit question not all syrvey.

**Comment by andrewtelnov** [comment]
@GreatEarl You may show the same question, with the same name and properties (just copy it) on the next page. The value for this questions will be stored in the same place data["questionName"], so they will share it.

Thank you,
Andrew

**Comment by GreatEarl** [comment]
@andrewtelnov  Ok, I've got the point but actually, I have 6 pages, and the page with matrix is 3-rd. Right now I don't imagine how it'll work, need to be tested ))  
If interesting - I want to implement a kind of ratings. When User has to spread let say 15 points of rating between 4  positions (rows) assessing from 1 to 5 each. And when user can't set maximum rating of 5 for each position - in this case the sum of pionts will be 20 but user has only 15. So user must evenly distribute 15 points between positions. And when he thinks that there was an error in answers - I want to reset all answers. 
--
Best,
Ravil.

**Comment by andrewtelnov** [comment]
@GreatEarl Then you may have a button outside the survey "Reset answers", it will be shown when the question/page is visible and actually it will reset the rows: survey.getQuestionByName("myMatrix").rows = savedRows;

**Comment by GreatEarl** [comment]
@andrewtelnov Andrew thanks for the direction and explanation I'll play around it )  btw
survey.getQuestionByName("matrix").rows  - returnt list of objects when "question" itselft accepts array in rows. Or do I need to save my rows as object before?

**Comment by andrewtelnov** [comment]
Yes, it is better to save the rows before survey starts. However, on setting rows property, the library will convert the array of strings into ItemValue array anyway.

**Comment by GreatEarl** [comment]
Thank you Andrew, the rest I need - to find proper way to store rows and re-assign them on reset.
