### ISSUE TITLE
Need to add additional text below the title or the question

### ISSUE THREAD

**Issue by geoffreyspencer** [surveyjs/surveyjs#410]
### Are you requesting a feature, reporting a bug or ask a question?
ask a question or feature request

### What is the expected behavior?
After the question is display, I need to add "help" text below it. For example:
1. No limitations of physical activity
   (climbing one flight of stairs with no symptoms)
2. Slight limitation of physical activity
    (excessive fatigue or shortness of breath with one flight of stairs)
etc...

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Safari, IE, any browser
* browser version: latest versions
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: latest version

**Comment by andrewtelnov** [comment]
@geoffreyspencer You may use markdown. In the following example, we are using showdown:
http://surveyjs.org/examples/jquery/survey-markdown-radiogroup.html
You may use all it's features: http://showdownjs.github.io/demo/

Thank you,
Andrew

**Comment by geoffreyspencer** [comment]
Hi Andrew,

Thanks for replying. The markdown is the answer but can I move it to the next line? Would <br /> work? 

FYI, I am working on medical questionnaires for the patients in my clinic I work at.

Geoffrey Spencer
3014 Southmore DR E
Ottawa, ON
K1V 6Z4
H: 613-733-6880 (no phone calls and no voicemails please)
M: 613-263-6170 (text only please)
E: geoffreyspencer@me.com
FYI, I am (profoundly) deaf and cannot use the telephone.

**Comment by andrewtelnov** [comment]
@geoffreyspencer Yes, <br /> will work. What version of SurveyJS are using, jQuery, knockout, react...?
We will make an example on plunker.

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
@geoffreyspencer, hello! Thanks for your interest. Here is an example: 

http://jsfiddle.net/a2cw321x/

**Comment by andrewtelnov** [comment]
@geoffreyspencer We have the question.description property now.

Thank you,
Andrew
