### ISSUE TITLE
Show survey answers progress

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#411]
Hi, i have to show at the top of the survey the "user progress"... In particular I should show the percentage of completion and the number of responses relative to the total..

Example:

answers: 10 of 100 (counting only compiled answers)
percentage: 10%

is there any way to do this? Even if there is no default method, are there any variables that I can retrieve through the js?

Thanks for all ;)

**Comment by andrewtelnov** [comment]
@care46 Theoretically you may override progressText function. 
```
Object.defineProperty(SurveyModel.prototype,"progressText",{get: function() { return yourValue;},
        enumerable: true,
        configurable: true
    });
```
A better way - we have to calculate the progress by questions, not by pages. 
Are you going to modify the progress bar on the current page? Right now it is changed on page changing.

Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov the progress bar is ok, because the progress show the number o total pages and the user page (and it's ok), I need to show a further element that informs user about how many questions the survey has (only visible questions) and how many questions users answered

**Comment by andrewtelnov** [comment]
@care46 Where do you want to show it? You may have it outside the survey area and in this case you may show what ever you want. `Object.keys(survey.data.).length` - it will return the number of answering questions, `survey.getAllQuestions().length` - the number of questions, `survey.getAllQuestions(true).length` - the number of visible questions.

Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov yesss... i want to show it outside the survey.. These variables you've suggested to me are just what I was looking for! Thank you!

**Comment by care46** [comment]
@andrewtelnov another question, the function survey.getAllQuestions() return all questions, also the HTML question that not have an answer... there is a parameter to specify to have only questions with answer?

Thank you

**Comment by andrewtelnov** [comment]
@care46  Unfortunately not. You will have to go through the array and count questions which return true for hasInput.
```
var counter = 0;
var questions = survey.getAllQuestions();
for(var i = 0; i < questions.length; i ++) if(questions[i].hasInput) counter ++;
```

**Comment by care46** [comment]
@andrewtelnov ok thanks!
