### ISSUE TITLE
src/react/reactquestioncheckbox.tsx

### ISSUE THREAD

**Issue by gperreymond** [surveyjs/surveyjs#416]
In the react version, you will have issues with this semantic : 

<span className="checkbox-material" style={{"**margin-right**": "5px"}}>

The correct syntax has to be : 

<span className="checkbox-material" style={{"**marginRight**": "5px"}}>

Result : 
Warning: Unsupported style property margin-right. Did you mean marginRight? Check the render method of `t`.

**Comment by abibao** [comment]
A lot of CI consider warnings like those, as error.

**Comment by tsv2013** [comment]
@gperreymond Thank you! We'll fix it.
