### ISSUE TITLE
Bug inserting rows in matrixdynamic

### ISSUE THREAD

**Issue by Kuhax** [surveyjs/surveyjs#417]
Hello

I have encountered a weird behaviour of matrixdynamic. When "Add row" button is clicked, 10 rows get added instead of just one. Not sure why this happens. I'm using the latest version 0.12.16.

Here is the issue: [http://surveyjs.org/builder/#32464444-dc2b-457d-a268-64501ddb88f9](http://surveyjs.org/builder/#32464444-dc2b-457d-a268-64501ddb88f9)

It happens in Survey Designer as well as in my application.

Thanks

**Comment by dmitrykurmanov** [comment]
@Kuhax thank you for found this. As a workaround you can change your code from `rowCount: "1"` to `rowCount: 1` (number instead of string).  And we'll think how to fix it.

**Comment by Kuhax** [comment]
@dmitrykurmanov Thanks for the tip
