### ISSUE TITLE
Make choicesByUrl dynamic, support text pre-processing

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#418]
choicesByUrl.url and choicesByUrl.path should be able to support "{QuestionName}" text processing.
The typical example. The user choose a country from the first dropdown, the second drop down, should send a request on the restful service to get regions/states for this country and on choosing the region/state  the third dropdown "city" should send a request to get all cities in this region/state.
It should work without any code in JavaScript.

**Comment by bjdani** [comment]
Hi Andrew,
I'm also in need of implementing this. Any chance you could provide a comment with a sample showing how to implement?
Thanks,
Bruce

**Comment by andrewtelnov** [comment]
@bjdani Sure, here is the demo: https://plnkr.co/edit/0sZFOKzlAlWUujDpgQuN?p=preview

**Comment by gaurav-singhal** [comment]
Ok I have another issue. If the choices are dependent on previous filled answer, then its an issue as previous value is not picked by url.

[sample plunk code](https://plnkr.co/edit/hBcORIh9cSvbWw3bTj4Y?p=preview)

**Comment by andrewtelnov** [comment]
@gaurav-singhal Here is the answer: https://github.com/surveyjs/surveyjs/issues/657#issuecomment-336525940 :)
