### ISSUE TITLE
goNextPageAutomatic skips server validation on final question

### ISSUE THREAD

**Issue by batmanbury** [surveyjs/surveyjs#419]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug

### What is the current behavior?

If the survey uses `goNextPageAutomatic` and has a validation on the final question, that validation is skipped. In my plnkr, I'm validating an email on the server (mocked). Only one string should be accepted, but any valid email string will skip the server validation, and not log an error to `options.errors`

### What is the expected behavior?

It should validate the email address with the server and display the error before completing the survey.

### How would you reproduce the current behavior (if this is a bug)?

Create a survey with `survey.goNextPageAutomatic` and add a server validation on the final question (email in this case). You can turn off goNextPageAutomatic to see that the validation occurs as it should.

I have a plnkr: [http://plnkr.co/edit/e8BUgofcZJX7aAr4xklK?p=preview](http://plnkr.co/edit/e8BUgofcZJX7aAr4xklK?p=preview)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

[http://plnkr.co/edit/e8BUgofcZJX7aAr4xklK?p=preview](http://plnkr.co/edit/e8BUgofcZJX7aAr4xklK?p=preview)

### Specify your

* browser: Chrome
* browser version: 58
* surveyjs platform **jQuery**
* surveyjs version: 0.12.15

**Comment by andrewtelnov** [comment]
@batmanbury I have fixed the issue.
Here is your example with the dev version: http://plnkr.co/edit/iK4YypXTf2cATEZwDg7h?p=preview

Thank you,
Andrew

**Comment by batmanbury** [comment]
The commit you referenced does in fact fix my issue, so I made that same change locally. But that full dev version has other changes which don't seem to play well with my current set up. I have identical answer choices across every page of the survey, with unique names for each question. Somehow when goNextPageAutomatic triggers, the new question copies the previous question's selection and it is already made. I haven't pinpointed the reason yet.

**Comment by andrewtelnov** [comment]
@batmanbury Could you please explain the issue in more details? Do you mean the input focus? You may turn off the first input focusing: http://surveyjs.org/docs/api_surveymodel.html#focusFirstQuestionAutomatic 

Thank you,
Andrew

**Comment by batmanbury** [comment]
@andrewtelnov  `focusFirstQuestionAutomatic` had no effect for me. I made a gif of what's I'm seeing. Each subsequent question has an answer preselected. The preselected answer is always the same "value" as the value selected on the previous question:

![survey](https://cloud.githubusercontent.com/assets/5461429/26681016/90d58478-46a9-11e7-8d91-fe0101c0ac44.gif)

**Comment by andrewtelnov** [comment]
@batmanbury Are you using image picker as a custom widget? 
http://surveyjs.org/examples/jquery/custom-widget-image-picker.html

**Comment by batmanbury** [comment]
Yes, image picker. @andrewtelnov

**Comment by andrewtelnov** [comment]
@batmanbury Does it work fine in v0.12.16 and has an issue in dev?  Could you share your custom widget code? I have tried this one: http://surveyjs.org/examples/jquery/custom-widget-image-picker.html. I can't see an issue in dev version. 

Thank you,
Andrew

**Comment by batmanbury** [comment]
@andrewtelnov Yes, the issue is only in **dev**. I tried each of these:
* `https://surveyjs.azureedge.net/0.12.15/survey.jquery.js`
* `https://surveyjs.azureedge.net/0.12.16/survey.jquery.js`
* `https://surveyjs.azureedge.net/dev/survey.jquery.js`

`0.12.15` and `0.12.16` _do not_ produce the above effect.

**Comment by andrewtelnov** [comment]
@batmanbury Here is the example: http://plnkr.co/edit/wuTTznoIBTSJLuny3wor?p=preview

**Comment by batmanbury** [comment]
@andrewtelnov I reproduced the effect with a fork of that plnkr. All I did was add more questions so it would occur:

[http://plnkr.co/edit/Owf84AAUWCvjztJLxhju?p=preview](http://plnkr.co/edit/Owf84AAUWCvjztJLxhju?p=preview)

**Comment by andrewtelnov** [comment]
@batmanbury Yes, I can see a problem now. Thank you!

**Comment by andrewtelnov** [comment]
@batmanbury 
FYI: I have tracked down that the issue in the [preact](https://github.com/developit/preact) that we are using to get jQuery version without react dependencies.
I have not find the workaround yet, but we are working on it.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@batmanbury I have fixed a small issue in react dropdown, updated the dev version and changed the plunker: http://plnkr.co/edit/zZy1JLcAMaO2NekO4r3x?p=preview
I have added one line in the custom widget:
```
    for (var i = 1; i < options.length; i++) {
      options[i].dataset["imgSrc"] = options[i].text;
      options[i].selected = question.value == options[i].value; //<< the added line
    }

```

Thank you,
Andrew
