### ISSUE TITLE
Customising result view

### ISSUE THREAD

**Issue by chris-ti8m** [surveyjs/surveyjs#420]
### Ask a question
Is it possible and how to customise the result view, which can be enabled to show at the end of the survey? There are certain questions with free text fields which I do not want to show up in the result view.

**Comment by tsv2013** [comment]
SurveyJS object has [onComplete](http://surveyjs.org/examples/jquery/survey-oncomplete.html) event. You cna handle it, get survey results, remove some items from survey data object and then show results in any custom form.

**Comment by chris-ti8m** [comment]
Is there any other solution, so that sensitive data can already be excluded on serverside?

**Comment by tsv2013** [comment]
Do you mean survey results view on dxsurvey.com ?

**Comment by chris-ti8m** [comment]
Yes, it is about filtering the results view on dxsurvey.com. Any chance to customise the view?

**Comment by andrewtelnov** [comment]
@chris-ti8m It would make sense to filter by submit date/time. What else do you want to filter?

Thank you,
Andrew

**Comment by chris-ti8m** [comment]
Hi Andrew, I would also like to filter out questions/answers of the survey which are not relevant or sensitive. For example free text fields where every answer is different.

**Comment by tsv2013** [comment]
You can use "Customize Columns" in the survey results list view:
![image](https://cloud.githubusercontent.com/assets/3013415/26669351/33ca0878-46b6-11e7-90c5-192c13e0b3b5.png)

You can set `Visibility` option to `Private` (never show cloumn in result view) or `Hidden` (hide column for public result link only) to hide sensitive data on survey results page.

**Comment by chris-ti8m** [comment]
That might do the trick. I will give it a try. Thank you very much for support!
