### ISSUE TITLE
Question on SurveyVerbs usage

### ISSUE THREAD

**Issue by hyndsite** [surveyjs/surveyjs#423]
Scouring the code base, I am having a hard time understand the use of the SurveyVerbs and related classes.  Can you shine some light on exactly the purpose of this functionality?

Thanks

**Comment by andrewtelnov** [comment]
@hyndsite I guess you are talking about Survey Editor. 
You may see them under the object property editor. It allows to change the question page and for dropdown, checkbox and radiogroup questions change their types.

Do you want to create your own SurveyVerbItem? I do not make them as a plug-in yet. However, it should not be hard to implement.

Thank you,
Andrew

**Comment by hyndsite** [comment]
Thanks.  I don't need that feature.  I wanted to just have a better understanding.
