### ISSUE TITLE
Defining Other value

### ISSUE THREAD

**Issue by nategasm** [surveyjs/surveyjs#424]
~~Wondering if this behavior is intentional. If a question is not visible then shouldn't it always be undefined in the result? However if it is visible at one point and populated and then made not visible after then the value will stay.~~

~~See this example http://surveyjs.org/builder/#ce656743-17de-4fd1-bc1c-6e0f5dde191b
If I pick item 1 and complete question 2, but change my mind and pick item 2 instead, the result will still be: `{"question1":"item2","question2":"answer"}`
Whereas I would logically be expecting the result to be only:
`{"question1":"item2"}`~~

Edit: Sorry I didn't see the clearInvisibleValues property

I also have another unrelated question: is it possible to change the output hasOther value in checkboxes/radiogroups? ie. right now the result value is "other", but I want to change it to something else while keeping the comment value separate at the same time.

**Comment by andrewtelnov** [comment]
@nategasm Are you looking for this property: http://surveyjs.org/docs/api_surveymodel.html#storeOthersAsComment?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
No replay for several months. I am closing the issue.
