### ISSUE TITLE
addCustomWidget brokens function for visibileif

### ISSUE THREAD

**Issue by xiuzhen1103** [surveyjs/surveyjs#425]
visibileif attribute it is not working since I combined customised css

```
function RatingWidget(target, question, valueChangedHandler) {
  var inputs = [];
  this.updateValue = function(newVal) {
    inputs.forEach(function(inputElement) {
      if(inputElement.value === newVal) {
        inputElement.checked = true;
      }
      else {
        inputElement.checked = false;
      }
    });
  }

  question.choices.forEach(function(choice, index) {
    var labelText = index > 0 && index > question.choices.length - 1 ? "" : choice.text;
    var label = document.createElement("span");
    label.className = "ov-radio-lg";
    var content = "";
    if(!!labelText) {
      content = content.concat("<label class='test-label'" + "' for='satisfaction_" + choice.value + "'>" + labelText + "</label>");
    }
    label.innerHTML = ("<input type='radio' name='" + question.name + "' value='" +  + choice.value + 
     "' id='satisfaction_" + choice.value + "'>").concat(content);
    inputs.push(label.childNodes[label.childNodes.length - 1]);
    target.appendChild(label);
    console.log(target);

  });
  inputs.forEach(function(inputElement) {
    inputElement.addEventListener('click', function(event) {
      valueChangedHandler(event.target.value);
    }, false);
  });
  this.updateValue(question.value);
}

Survey.defaultBootstrapCss.navigationButton = "btn btn-primary";
Survey.Survey.cssType = "bootstrap";
var survey = new Survey.Model({
   showQuestionNumbers: "off", questions: [
     {  
       type: "radiogroup",
        title: "Customer satisfaction degree",
        name: "radiogrouptest",
        choices: [{value: 1, text: "Yes"}, {value: 2, text: "No"},{value: 3, text: "N/A"}]},
        { type: "checkbox", name: "car", title: "What car are you driving?", isRequired: true, visibleIf: "{radiogrouptest} > 1",
     colCount: 4, choices: ["None", "Ford", "Vauxhall", "Volkswagen", "Nissan", "Audi", "Mercedes-Benz", "BMW", "Peugeot", "Toyota", "Citroen"] },
     
                {  type: "radiogroup",
                title: "Education degree",
                name: "radiogroup1",
                choices: [{value: 4, text: "Educate Test test"}, {value: 5, text: "Educate Test test"}]},
   
            { type: "comment", name: "suggestions", title:"Educate Test test 2?", }
        ]}  
);


var widget = {
    name: "customrating",

    isFit : function(question) { return question.name.includes('radiogroup'); },
    afterRender: function(question, el) {
        el.className = "span-radio-row col-sm-8";
        var widget = new RatingWidget(el, question, function(newVal) {
        question.value = newVal;
      });
        question.valueChangedCallback = function() {
          widget.updateValue(question.value)
        }
    }
}
Survey.CustomWidgetCollection.Instance.addCustomWidget(widget);
var myCss = {
      "row": "row-question",
      "root": "container",
      "question": {
        "title": "col-sm-4",
      }
      
   };

ReactDOM.render(<Survey.Survey model={survey}  css={myCss}/>, document.getElementById("surveyElement"));



```

**Comment by andrewtelnov** [comment]
@xiuzhen1103 I am getting an error: oneviewArrangeForm is not a function.
Could you please create jsFiddle or plunker version?

Thank you,
Andrew

**Comment by xiuzhen1103** [comment]
@andrewtelnov you can remove this function, its only used for internal function. It still dosen't work with visibleIf attribute. 

  /*  $('#sq_page').arrangeForm({
            maxLabelLetters : 10,
            maxLineChars : 30,
            maxHorizontalAnswers : 6,
            outerClass : '.row-question',
            minWidth : '70px',
            leftMargin : '160px', //160px //beans.. use 222px
            useRadioBeans : 'true',
            animateRadioBeans: 'true'
            
        });*/

**Comment by andrewtelnov** [comment]
@xiuzhen1103 The following code doesn't work as expected:
```
  inputs.forEach(function(inputElement) {
    inputElement.addEventListener('click', function(event) {
      valueChangedHandler(event.target.value);
      alert(event.target.value);
    }, false);
  });
```
It shows alert with undefined and only on label click. That is incorrect.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
I mean the issue that question.value doesn't change properly, it is undefined and not 1, 2 or 3 as expected.

**Comment by xiuzhen1103** [comment]
May I ask if you have working version survey js for react?  I can provide it with my code.

**Comment by xiuzhen1103** [comment]
Hi, I tried to reproduce it, unfortunately, in JsFiddle console error message appear to be "Uncaught SyntaxError: Unexpected token <" 

ReactDOM.render(<Survey.Survey model={survey}  css={myCss}/>, document.getElementById("surveyElement"));

Is there any syntax error associate with this, please? I can run it in visual studio code. Do I need to include babel or any file?

http://jsfiddle.net/v3nLfLpm/

![image](https://cloud.githubusercontent.com/assets/6764095/26802271/cd92d794-4a37-11e7-9a1e-08472bb02093.png)

**Comment by xiuzhen1103** [comment]
Hi, please find jsFiddle here: 
http://plnkr.co/edit/V3c5ljeQQ9PJA32wPHxH?p=preview
If you comment out line 76 which is for add customised style, you can see hide/show function it's working when you click yes in first question. I believe this might be a bug, would you please have look, please? 
![image](https://cloud.githubusercontent.com/assets/6764095/26804435/df009bd0-4a3f-11e7-8602-1abc137c837b.png)

**Comment by andrewtelnov** [comment]
@xiuzhen1103 
I have modified your plunker by binding label/span element (radio+label) together with value:
http://plnkr.co/edit/YA7JfnlDccYPnbkYxTyO?p=preview

Thank you,
Andrew
