### ISSUE TITLE
problem in onPartialSend !

### ISSUE THREAD

**Issue by nooralahzadeh** [surveyjs/surveyjs#426]
Hi, Thanks for your effort!
I have implemented a survey app for my project using react+redux+ surveyjs.
In module regarding to survey, I would like to save data partially in each step. I have just matrix type question. I have set following properties and methods:

model.sendResultOnPageNext=true
<Survey.Survey model={mdl} onPartialSend ={this.savePartailToServer.bind(this)} onComplete={this.sendDataToServer.bind(this)}  />

savePartailToServer(survey) {
       var {dispatch,surveys,discipline} = this.props;
       var current_survey = surveys.filter(element=> {if (element.discipline === discipline) return element});
       var id =current_survey[0].id
      dispatch(actions.startUpdate(id,survey.data));
  }

when I click on Next, the server is updated but the current page is not updated and the survey stays in the first page! However when I commented the dispatch which is update my db, I can navigate to next pages. I have checked my action in dispatch and there is no any problem in that part, and it just update state and db side.
I am wondering if you could help me in this matter. 
Thanks

**Comment by andrewtelnov** [comment]
@nooralahzadeh Unfortunately, I have not played with redux yet. I want to. Is dispatch performed in the same thread?
I mean your method savePartailToServer should performed immediately, without waiting callback from the server. The code for doNextPage method is straight forward:
```
    protected doNextPage() {
        this.checkOnPageTriggers();
        if (this.sendResultOnPageNext) {
            this.sendResult(this.surveyPostId, this.clientId, true);
        }
        var vPages = this.visiblePages;
        var index = vPages.indexOf(this.currentPage);
        this.currentPage = vPages[index + 1];
    }
```
I am sure there is no errors in your console. Correct?

Thank you,
Andrew

**Comment by nooralahzadeh** [comment]
Yes, There is no error in console! I have my saved data in the db ( which is in firebase ), But I can't navigate!

**Comment by andrewtelnov** [comment]
@nooralahzadeh Could you use the non minimized version and debug it? Set the breakpoints into doNextPage method on this.SendResult(... and on vPages =..
survey.postId is empty, correct?
For some reason doNextPage doesn't go to vPages = ...

I do not know why :(

**Comment by nooralahzadeh** [comment]
@andrewtelnov is there any way to initiate the doNextPage on minimized version ?
Yes, survay.postId is empty.
I will try the minimized version.

**Comment by andrewtelnov** [comment]
@nooralahzadeh Could you add alert just after your dispatch and see if it calls immediately?

```
savePartailToServer(survey) {
var {dispatch,surveys,discipline} = this.props;
var current_survey = surveys.filter(element=> {if (element.discipline === discipline) return element});
var id =current_survey[0].id
dispatch(actions.startUpdate(id,survey.data));
alert("I'm here!");
}
```

**Comment by nooralahzadeh** [comment]
Yes I have the alert immediately when I click "Next" as well as the data in my db!
<img width="938" alt="screen shot 2017-06-03 at 10 22 41" src="https://cloud.githubusercontent.com/assets/1093791/26752032/008487c6-4847-11e7-9082-f22dbbf61614.png">

**Comment by andrewtelnov** [comment]
@nooralahzadeh So, if comment this line `dispatch(actions.startUpdate(id,survey.data));` the doNextPage method is working fine and if remove a comment it stops working, right?
Probably, it does something with survey state?

**Comment by nooralahzadeh** [comment]
Yes, if I comment the dispatch line , the doNextPage works! However my action doesn't do anything with survey state, It saved only the survey.data into db.

**Comment by andrewtelnov** [comment]
@nooralahzadeh Maybe redux does something? Could you ask a question on stackoverflow.com? Probably somebody will give you an idea? I would love to know what is the reason of this behavior as well. 
I just did a test, without redux, only onPartialSend in react version. Everything works fine.
Maybe the issue in our code and not in redux and we should do something different in our react components. In this case, It would be great to fix the issue.

PS: If you ask, could share a link here? 

Thank you,
Andrew

**Comment by nooralahzadeh** [comment]
[https://stackoverflow.com/questions/44346995/react-redux-and-surveyjs](url)

**Comment by nooralahzadeh** [comment]
@andrewtelnov  [Post in stackoverflow! ](https://stackoverflow.com/questions/44346995/react-redux-and-surveyjs)

**Comment by Franzandr** [comment]
@nooralahzadeh Did you find a solution? I'm facing the same problem. Do you have the source code for the firebase integration?

**Comment by nooralahzadeh** [comment]
look at here, I dont remember how I solved it : https://github.com/nooralahzadeh/surveyApp.ES6
