### ISSUE TITLE
Dates in "Text" question type allowing years with more than 4 digits

### ISSUE THREAD

**Issue by bjdani** [surveyjs/surveyjs#429]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
When the user enters a date into a Text question type that is set to an input type of "date", they can enter more than 4 digits for the year. Depending on the number of extra digits entered the results may or may not even match what was entered.

### What is the expected behavior?
They can only enter 4 digits for the year.

### How would you reproduce the current behavior (if this is a bug)?
1. Create a new survey in the survey builder
2. Add a Single Input question.
3. Configure the question as input type "date"
4. Test the survey.
5. Enter a date of 01/01/201799
6. Complete the survey
7. The results are {"question1":"201799-01-01"}
8. Test the survey again.
9. Enter a date of 01/01/2017999999
10. Complete the survey
11. The results are {"question1":"275760-01-01"}

#### Provide the test code and the tested page URL (if applicable)
Survey JSON:
`{
 pages: [
  {
   elements: [
    {
     type: "text",
     inputType: "date",
     name: "question1"
    }
   ],
   name: "page1"
  }
 ]
}`

### Specify your
* browser: Chrome
* browser version: 58.0.3029.110 (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.12.16 (and using the builder on the survey.js website)

**Comment by andrewtelnov** [comment]
@bjdani the year 999999 is still a valid year :-) 
Here is the plunker example to deal with it: http://plnkr.co/edit/k9OTTyqN3deCEqDmVWRH?p=preview

Thank you,
Andrew

**Comment by bjdani** [comment]
Sorry, I didn't realise.
Thanks for the info and link. I'll implement the plunker example.
