### ISSUE TITLE
"hasOther" property on select2tagbox dropdowns

### ISSUE THREAD

**Issue by Kuhax** [surveyjs/surveyjs#431]
Hello. I'm looking for a way to implement a multiple selection of choices from a list with an option to add custom text.

Taking [Select2 Tag Box](http://surveyjs.org/examples/jquery/custom-widget-select2-tagbox.html) example allows you to choose several countries from a given list but does not allow you to add your own option like "hasOther" option in normal dropdown. 

Adding `"hasOther": true` to select2tagbox adds one more option to the list, but the behaviour is not the expected since you're unable to add text.

What are your thoughts about this matter ?

Thank you in advance.

**Comment by tsv2013** [comment]
[Select2 Tag Box](http://surveyjs.org/examples/jquery/custom-widget-select2-tagbox.html) example replaces original dropdown question markup via the following line:
`htmlTemplate: "<select multiple='multiple' style='width: 100%;'></select>"`
And this markup does not contain `input` for "other" value.

You can change the markup and sample code according your needs. If you need some assistance from our side, please describe your scenario in greater details.

**Comment by Kuhax** [comment]
@tsv2013 I'm looking forward to implement the tagging functionality of select2 widget. Notice that the widget itself allows you to select from pre-existing options or create a new entry as shown in their [example page](https://select2.github.io/examples.html#tags)

Looks like this feature can be turned on by adding `tags: true` to the widget, but I wasn't able to make it work so far in my matrixdynamic.

**Comment by tsv2013** [comment]
@Kuhax Thank you for the clarification! I'll take a look.

**Comment by Kuhax** [comment]
@tsv2013 I think I have a temporary fix (at least). Please check out this [plunk](http://plnkr.co/edit/stwtMd) (made by you originally)

I have modified `question.choicesChangedCallback` by adding `tags: true` (line 62). Please notice that now you can either select several options from the list as well as add your own text just typing it and pressing enter.

Not sure if it's the solution, but at least it's the behaviour I'm expecting

Cheers

**Comment by tsv2013** [comment]
@Kuhax It looks like select2 resets the "tags" option after "data" option has been changed. I've not found any objections to set `tags: true` on each "data" option update. If it works for you now - why wouldn't use this workaround?
