### ISSUE TITLE
Left-aligning the labels

### ISSUE THREAD

**Issue by faso** [surveyjs/surveyjs#435]
### Are you requesting a feature, reporting a bug or ask a question?
Question
### What is the current behavior?
Right now I don't see a way to do something like this in a centralized global fashion:

![form_left_aligned](https://user-images.githubusercontent.com/19239918/26870052-f93e8838-4b6e-11e7-974a-51c58b22ed58.PNG)

Since SurveyJS claims good support of Bootstrap it would be amazing if we could use the Bootstrap grid system to achieve similar results.

### Specify your

* browser: Chrome
* browser version: 59
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery
* surveyjs version: 0.12.16

**Comment by faso** [comment]
Updated the picture a little to remove unnecessary confusing fields

![img_07062017_112446_0](https://user-images.githubusercontent.com/19239918/26871610-19bf7d88-4b74-11e7-8a38-5d240c77f8e9.png)

**Comment by andrewtelnov** [comment]
@faso The suggestion makes sense. I have added it to our TODO list. Unfortunately, I can't promise we will do it soon. However, we will definitely discuss it every time we are getting new tasks from the Baglog.

Thank you,
Andrew

**Comment by faso** [comment]
Is there some sort of a hack right now that I could apply? Or does it take too much bending of SurveyJS?

**Comment by andrewtelnov** [comment]
@faso you may fork the project and based on your platform, make the necessary changes. It should not take too much time if you need it to do for one platform only.

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
@faso hello I think it is possible to implement it with css. We'll think about adding css classes for all components (like titles) and states (like isRequired).
