### ISSUE TITLE
Using imagepicker as custom widgets in Internet explorer 10

### ISSUE THREAD

**Issue by xiuzhen1103** [surveyjs/surveyjs#437]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
Custom widget for image picker is not working in Internet explorer 10+
error message on console appears "Unable to set property 'imgSrc' of undefined or null reference"
Image pickers support IE9 and IE10 version, when it integrated with surveyJs, it has this problem. 

### What is the expected behavior?
Custom widget for image picker is working in Internet explorer 9 and 10

### How would you reproduce the current behavior (if this is a bug)?
http://surveyjs.org/examples/react/custom-widget-image-picker.html
in Emulation select document mode: 10, User agent string: Internet Explorer 10

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: http://surveyjs.org/examples/react/custom-widget-image-picker.html

* browser: Internet explorer
* browser version: Internet explorer 10
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version: 0.12.16

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103 we'll fix it, thanks.

**Comment by xiuzhen1103** [comment]
@dmitrykurmanov Thanks for replying me and providing solution on it, may I find out when is next release, please?

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103 it should be tomorrow

**Comment by xiuzhen1103** [comment]
@dmitrykurmanov thanks so much for your help.

**Comment by xiuzhen1103** [comment]
Hi Dimitry, how to update the version?

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103 Hello! You can get last version from npm or from our cdn `https://surveyjs.azureedge.net/0.12.17/survey.jquery.js`

**Comment by xiuzhen1103** [comment]
Hi Dmitry,
may I ask you how to update it in npm, please?

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103, hello. You can use `npm install survey-jquery` or `npm update survey-jquery ` if it already installed

**Comment by xiuzhen1103** [comment]
Unfortunately, this issue still insist. Any idea with it, please?  Unable to set property 'imgSrc' of undefined or null reference

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103 do you change your code to `$(options[i]).data("imgSrc", options[i].text);` ? Here an our fixed example  http://surveyjs.org/examples/jquery/custom-widget-image-picker/
