### ISSUE TITLE
Send Ajax request to your web server

### ISSUE THREAD

**Issue by LEGrecc** [surveyjs/surveyjs#438]
### Are you requesting a feature, reporting a bug or ask a question?
Ask Question

Hello, 

I am on the Step 6 of the integration process. ( http://surveyjs.org/docs/integration.html) 
I am trying to send my result to my localhost server. Could you please let me know the code to do that ? 
Is it the following code ? I am a beginner. 

function sendDataToServer(survey) {
  var resultAsString = JSON.stringify(survey.data);
  alert(resultAsString);
   survey.sendResult('mysql:dbname=tuto;host=localhost', 'root', '')
   //send Ajax request to your web server.
}

Also, I have a sessionstart ()  with a login (i.e pseudo and password). Data are located in my localhost server dbname=tuto. Is it possible to include the pseudo or mail of the client in the results to link each survey answer to a name ? 

Thank you for you help.

**Comment by andrewtelnov** [comment]
@LEGrecc [survey.sendResult](http://surveyjs.org/docs/api_surveymodel.html#sendResult) is the method to store the data in the dxsurvey.com service. 
You should write some code to store it in your database. That really depends on platform you are using on the server side. We probably should make some examples for most popular platforms/databases, here is some links: 
https://stackoverflow.com/search?q=javascript+save+json+in+mysql+database

Thank you,
Andrew
