### ISSUE TITLE
Matrix Dynamic question adding 10 rows when question row count set to 1

### ISSUE THREAD

**Issue by bjdani** [surveyjs/surveyjs#439]
### Are you requesting a feature, reporting a bug or ask a question?
Bug
First appears in v0.12.15.
Works fine in v0.12.14.

### What is the current behavior?
When using a Matrix Dynamic question type, if the Row Count setting for the question is set to 1, when running the survey, as soon as the user presses the Add button for the question, 10 new rows are added instead of just one row.

### What is the expected behavior?
Only one row should be added to the question when the Add button is pressed.

### How would you reproduce the current behavior (if this is a bug)?
This bug shows up in the Survey Builder on the website as well as locally in my survey.

1. Go to Survey Builder on the survey.js website.
2. Create a new survey.
3. Add a Matrix Dynamic question type.
4. Edit the options for the question and change the Row Count setting from 2 to 1.
5. Test the survey.
6. Press the add button.
7. 10 additional rows are added to the question.

### Specify your

* browser: Chrome
* browser version: 58.0.3029.110 (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.12.15 & 0.12.16

**Comment by Kuhax** [comment]
This issue was mentioned in #417 

Temporary solution is to change your code from rowCount: "1" to rowCount: 1 (number instead of string)

**Comment by andrewtelnov** [comment]
@bjdani @Kuhax yea, it is time to fix the issue. I will work on it.

**Comment by andrewtelnov** [comment]
Fixed.

Thank you,
Andrew

**Comment by bjdani** [comment]
Thanks Andrew!
