### ISSUE TITLE
Custom CSS class issue

### ISSUE THREAD

**Issue by xiuzhen1103** [surveyjs/surveyjs#440]
### Are you requesting a feature, reporting a bug or ask a question?

Requesting a feature

### What is the current behavior?
When I use survey custom CSS function in radiogroup, "other" attribute is not class added in to HTML
There is an parent div element, can it add a class to it, I marked in the screenshot that I attached.
Is there any chance that I can add extra div with class wrap item element, please?

### What is the expected behavior?
"other " should appear and add class into raidogroup HTML

#### Provide the test code and the tested page URL (if applicable)

```
your_code_here
"radiogroup": {
        "root": " col-sm-7",
        "item": "radio-outer col-sm-5",
         "label": "labelClass",
        "other": "otherClassTextOn"
        
        },
```

![image](https://user-images.githubusercontent.com/6764095/26939804-64af4628-4c70-11e7-95b4-df8b28c7ca32.png)

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103 hello! We are going to provide special classes for all needs. We will try to implement it next week.

**Comment by xiuzhen1103** [comment]
@dmitrykurmanov thanks for let me know, may I find out if would be available next week?

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103 yes of course, we'll notify you in this issue.

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103 and feel free to describe what else classes you need

**Comment by xiuzhen1103** [comment]
That would be great, thanks a lot. I have added my desired result with text in red. 
![image](https://user-images.githubusercontent.com/6764095/26973424-7318f29c-4d0e-11e7-8912-cb1e67dbcff1.png)

**Comment by xiuzhen1103** [comment]
hi Dmitry,
May I find out if this request has been released, please?

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103, hello! I apologize for the late reply. We've released _cssClasses_ feature for every question. I will create an example.

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103 could you check this example  https://plnkr.co/edit/aIz4bdA0pFVw7WttInVF?p=preview please? Is it ok for you?  And why do you need to add class for root parent? For icheck you could use custom widget, here an example: http://surveyjs.org/examples/jquery/custom-widget-icheck/

**Comment by xiuzhen1103** [comment]
hi Dimitry,
` if(options.question["renderAs"] === "icheck") {`
I can see there is no problem with ` if(options.question.name == "car"), but I can not work with 
` if(options.question["renderAs"] === "icheck") {`

Is there any chance that if I could use 
```
classes.root = "my_root";
classes.item = "my_item";
classes.label = "my_label";
```
for class inside label tag, please? 
![image](https://user-images.githubusercontent.com/6764095/29067545-fa7b3b8c-7c2a-11e7-8ef1-4833a11b29b1.png)

I have issue with jquery icheck lin my project, may be use icheck library
please find in plunker
https://plnkr.co/edit/SPAHMZUgz52ydFPfVS7x?p=preview

**Comment by xiuzhen1103** [comment]
can you do  
`if(options.question.visibile == false) { }`

**Comment by xiuzhen1103** [comment]
![image](https://user-images.githubusercontent.com/6764095/29070234-57e12970-7c36-11e7-882a-c94d6c183254.png)
I would like to add custom class into parent root by ` classes.mainRoot = "mainRoot";`
Please find in the following screenshot
![image](https://user-images.githubusercontent.com/6764095/29070273-8b5965f6-7c36-11e7-84ca-70c75dc2f16a.png)

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103 hello! Ok let's try to solve these problems:

- about renderAs, ICheck and cssClasses:  I've got example from surveyjs.org and added cssClasses and it works fine, please check the example https://plnkr.co/edit/03iNZC3W81FCvu7534Ad?p=preview. (in your example you missed `Survey.JsonObject.metaData.addProperty `definition and `<link rel="stylesheet" href="https://unpkg.com/icheck@1.0.2/skins/square/blue.css">`  link for ICheck. Anyway we will think about better and easier custom widget implementation).

- about class for visible questions:  I've created a separate issue for it: #548

- about move mainRoot class into row-question:  What is your use case? Could you describe it please? May be we could reach it with existing functionality. It would be great if you create issue for that question/enhancement. Thanks.
