### ISSUE TITLE
Customised read-only/display mode

### ISSUE THREAD

**Issue by xiuzhen1103** [surveyjs/surveyjs#441]
### Are you requesting a feature, reporting a bug or ask a question?
Are you requesting a feature/ ask a question

### What is the current behavior?
read-only/display mode provides same layout as a survey question form

### What is the expected behavior?
I am wondering if I could customise this read-only/display mode, so only display question with answer both inside a div/html, rather than answer in disabled textarea/input/radiogroup

### How would you reproduce the current behavior (if this is a bug)?
http://surveyjs.org/examples/react/survey-displaymode.html
Please find it in SurveyJs library

* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version:  0.12.16

**Comment by andrewtelnov** [comment]
@xiuzhen1103 I was thinking about this feature. However, what happens, if a user doesn't response on a question? Let's say you have 10 questions on the page, only 2 has been answered. Should you show only these two questions? What question index should be 1 and 2 or preserved their indexes, for example: 3 and 9. In both cases it would look strange, IMHO.

Thank you,
Andrew

**Comment by xiuzhen1103** [comment]
Hi Andrew,
The purpose of disabled/read-only is for rendering saved information from database and display it to the page.  From UI perspective, survey form should different from history(or for printing purpose) in order to reviewing and maintaining.

If 10 questions, it do not matter if only two has answered, user's has knowledge to mark question as required force to answer it. If you worry about index, you can hide the question number. IMHO 

Thank you
Xiuzhen

**Comment by andrewtelnov** [comment]
@xiuzhen1103 You may simple go throw the JSON data and display it as one page.
Probably we will make as a feature. However, it is pretty easy to do on your side. One loop throw all data, label and data, without indexes. It does not make a lot of sense to divide it by pages, because you may have empty pages - all questions are unanswered. 

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@xiuzhen1103 It has been implemented. Here is [the example](https://surveyjs.io/Examples/Library/?id=survey-displaymode&platform)

Thank you,
Andrew
