### ISSUE TITLE
Feature request: currently when the user is done a section, only a json of the answers are outputted, can the questions also be paired with the answers?

### ISSUE THREAD

**Issue by john1625b** [surveyjs/surveyjs#442]
Right now when the user is done a setion, only a json of the answer is outputted with no question title paired with them. When making a front-end for the summary, it would be easier to have the questions title in the same object as the answer title.

for example
instead of the current
```
{
"Q_01_0": "Male"
}
```
do something like:
```
{
"Q_01_0": ["Male", "what is your sex"]
}

**Comment by dmitrykurmanov** [comment]
@john1625b hello maybe it should be something like :
```
{
"what is your sex": ["Male"]
}
```
or I don't understand it

**Comment by andrewtelnov** [comment]
@john1625b You may a write a simple code onComplete event to change the question value into question title.
However, the easiest solution - remove question title and name question as you need.
For example: here is your question json: 
`{ type: "text", name: "question2", title: "Please enter your name" }`
change it to:
`{ type: "text", name: "Please enter your name" }`
question title will be rendered by using question name if question title is empty.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
No reply for several months. I am closing the issue.
