### ISSUE TITLE
Hide certain pages from progress bar

### ISSUE THREAD

**Issue by grinfax** [surveyjs/surveyjs#443]
Currently the progress bar shows every page in the survey. I am structuring my survey as follows: 

Question -> feedback -> Question -> feedback -> Question -> feedback 

I hide/show Question HTML for the feedback and the flow works. However, the progressbar counts every page and I was wondering if there was a way to get it to only count the Question pages?

**Comment by andrewtelnov** [comment]
@grinfax I guess we may add this feature as an option, but it may mislead an end-user. Let's say, I have two pages without questions in the middle. End-user press 'Next' and the number of pages doesn't change. I personally, would consider this as a bug. The knowledge that pages without questions do not count, it is something I may not understand. I still read the text, I have to spend my time, why should not it count?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
No replay for several months. I am closing the issue.
