### ISSUE TITLE
Widget flexibility

### ISSUE THREAD

**Issue by rogereriksen** [surveyjs/surveyjs#445]
### Are you requesting a feature, reporting a bug or ask a question?

Question:

I´m considering surveyjs & editor for a project.
I would need to create some custom widgets for my project.  First I would need to be able to have a widget that will populate user information without user intervention - like department name.  This is to be used with IF condition.  In our solution we of course have the user info already.

Also would it be possible to create a widget for taking pictures?

Roger

**Comment by andrewtelnov** [comment]
@rogereriksen About your first question. You may set the question value, like in this [demo](http://surveyjs.org/examples/jquery/survey-data/).
About the second question. You may find a widget that you need and we may help you to integrate it into the survey. The custom widget may based on [File Question](http://surveyjs.org/examples/jquery/questiontype-file/)

Thank you,
Andrew

**Comment by rogereriksen** [comment]
Thanks Andrew for fast response.  Demo explains how to set value, but can you make a single question read only?

Roger

**Comment by andrewtelnov** [comment]
@rogereriksen a question has readOnly serializable property. You have to set it to true.

Thank you,
Andrew
