### ISSUE TITLE
Custom locale corrupts matrixdynamic contents.

### ISSUE THREAD

**Issue by Kuhax** [surveyjs/surveyjs#446]
I have noticed that setting custom locale deletes all the contents from certain matrixdynamic. Please take a look at this [plunk](http://plnkr.co/edit/Qky2UU?p=preview).

Notice that it restores previous answers from `var data`.

On lines 216 and 217 there is a locale customization:
`//model.locale = "es";` 
`//model.render();`

If you uncomment those and re-run the survey, you'll see the contents of the first matrixdynamic disappear.

**Comment by andrewtelnov** [comment]
@Kuhax As a workaround, please set rowCount from 0 to 2 and it will start to work:
http://plnkr.co/edit/PXgfBDT4mzHvhapDxlbs?p=preview

I found a unit test ("Matrixdynamic adjust rowCount on setting the value") that adjust increase the rowCount on setting value when necessary, for some reason it doesn't work with different locale. I will try to find the reason.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@Kuhax  I have found the reason why it doesn't work and fix it.

Thank you,
Andrew
