### ISSUE TITLE
Add ability to define css classes for particular questions

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#447]
At the current moment, there is no an easy way to set css classes to a particular question or group of questions, for example use an additional class in the tittle for required questions.

**Comment by andrewtelnov** [comment]
survey.onUpdateQuestionCssClasses event is added.
options.question and options.cssClasses.
It will give the ability to set the css classes for a question based on it's value or attributes in the code.

**Comment by gperreymond** [comment]
It's a litlle late perhaps, but here my solution, working for me :

```js
this.afterRenderQuestion = (s, options) => {
      debug('SurveyPlayer', 'afterRenderQuestion')
      options.htmlElement.className += ' ' + options.question.name
```
