### ISSUE TITLE
In-field templating & pickers missing for question input types in IE/Chrome

### ISSUE THREAD

**Issue by bjdani** [surveyjs/surveyjs#449]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
Questions of type "single input" and input type of any of the following don't display the in field templating or pickers when run in IE11:
- color
- date
- datetime
- datetime-local
- month
- time
- week

Also, the "datetime" input type doesn't show the in-field templating in Chrome either.

### What is the expected behavior?
Each of these question/input types should behave in a similar way when they are run in IE/Chrome/Firefox and display the in-field templating and/or pickers.

### How would you reproduce the current behavior (if this is a bug)?
Using the following JSON in the Survey Editor on the survey.js website running in IE/Chrome:

#### Provide the test code and the tested page URL (if applicable)
Tested page URL:
http://surveyjs.org/builder

Test code:

```
{
 pages: [
  {
   elements: [
    {
     type: "text",
     inputType: "color",
     name: "question-color"
    },
    {
     type: "text",
     inputType: "date",
     name: "question-date"
    },
    {
     type: "text",
     inputType: "datetime",
     name: "question-datetime"
    },
    {
     type: "text",
     inputType: "datetime-local",
     name: "question-datetime-local"
    },
    {
     type: "text",
     inputType: "month",
     name: "question-month"
    },
    {
     type: "text",
     inputType: "time",
     name: "question-time"
    },
    {
     type: "text",
     inputType: "week",
     name: "question-week"
    }
   ],
   name: "page1"
  }
 ]
}
```

### Specify your
* browser: Chrome & IE
* browser version:
    - Chrome v58.0.3029.110 (64-bit)
    - IE v11.0.9600.18639
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.12.17

**Comment by andrewtelnov** [comment]
@bjdani we are setting input type html attribute. Unfortunately, it doesn't support completely by all browsers: https://www.wufoo.com/html5/
If you need a specific type, so it would work for all browsers, you may use a custom widget feature.

It will require a lot of work to support all input types in all browsers you have mentioned. We would have to create our own widgets for every of them. 
By the time we finish with them, all popular browsers will likely support them out of the box :-)

Thank you,
Andrew

**Comment by bjdani** [comment]
Hi Andrew,
I've gone ahead and followed your advice and tried implementing a custom widget to handle inputmasks for my date fields but have run into problems with the widget being assigned to other fields when question visibility is toggled on/off. See #465.
Any tips on what I can do to get around this or is it a bug?

Thanks for your assistance. You guys are doing a great job!

Regards,
Bruce

**Comment by bjdani** [comment]
With Dmitry's plunker example which included the willUnmount I was able to resolve my issue with implementing the inputmask widgets.
Thanks!
