### ISSUE TITLE
Problem with "visibleIf" on panel element (JQUERY version)

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#450]
Hi, i have a problem with "visibleIf" properties on panel elements..

In Knockout version works well, but in jquery version maybe there is a bug...

Knockout exemple (work)

http://plnkr.co/edit/XYQ4FUa1oCbJ0YkJcTZz

JQuery example (bug)

http://plnkr.co/edit/zmJOcaqLMWeoKXLIAOvh

I have 2 panel, on the second panel i set property VisibleIf = {question1} = 'c'...
In jquery version, the second panel wasn't display...

Thanks

**Comment by dmitrykurmanov** [comment]
@care46 thanks for your interest, the bug is fixed and will be in next release.

**Comment by care46** [comment]
Hi, I'm sorry for being late but I was on holiday...

Now question2 appears, but not on the same line .. the second question is shown on another line ...

If I have 2 pages in the survey, when the condition shows the question, a new line is created, if I change the page and return to the first, the question is correctly displayed in the same line

**Comment by care46** [comment]
@dmitrykurmanov  The problem was also in 0.12.9 version

**Comment by dmitrykurmanov** [comment]
@care46, hello, sorry for late response, could you provide an example with two pages and lines bug, please?

**Comment by care46** [comment]
@dmitrykurmanov the problem is not only with two page, also in your plunker example there is a bug.. the second question (hidden) has attribute startwithnewline=false but when i put in the first question the value='c', the second question appear in a new line, not in the same line of first question
