### ISSUE TITLE
Is there a way to create calculated Questions?

### ISSUE THREAD

**Issue by zerovirus23** [surveyjs/surveyjs#451]
I'm trying to create a survey where there are some questions that are just the result of previous questions e.g.:
Question 1: How tall are you (cm)? 
Question 2: What is your weight (kg)? 
#### then I want to have a 
Question 3 (calculated value from expression) = {Question 1} * {Question 2} - {Question1}
Question 3 could or couldn't be displayed (using the visible property) but I need the value of Question 3 be evaluated before send to the backend. 

Is there any way to accomplish that requirement?
If not, Can I define those question types in the JSON with visible = false and maybe a new attribute "calculatedQuestion=true" to be evaluated in the backend without affect the survey framework?

Thanks in advance guys, you are doing a great job with this framework!.

**Comment by andrewtelnov** [comment]
@zerovirus23 Here is the demo: http://plnkr.co/edit/ElQzlHdpa2LVE833DD54?p=preview

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
No reply for several months. I am closing the issue.
