### ISSUE TITLE
Custom question  and matrix

### ISSUE THREAD

**Issue by felixcuneo** [surveyjs/surveyjs#453]
Hi there, 
I am using surveyJS (jquery) for psychological testing, in particular matrix question (with strongly disagree- strongly agree). 

And I find myself with some troubles :

1) As a psychometrician I can tell that having different "column width" in a matrix question is an important bias for participant. They would probably be biased with the distance and put a psychological interpretation on it while there is not. In fact "Strongly disagree" is longer than "disagree".

Can you think of a way to force column width to be identical ? (For isntance Strongly disagree would be on two rows).

2) I did not manage to find how to increase the text size in the questions. AND Could it be possible that the matrix question takes two rows ? (it's more clear for the eyes).

Thanks in advance,
Félix

**Comment by andrewtelnov** [comment]
@felixcuneo You may use the [custom css](http://surveyjs.org/examples/jquery/survey-customcss/) feature. Take a look at the plunker example, I have created: https://plnkr.co/edit/bHuE7VJALQpbygPQyA1Z?p=preview

I have added a matrixtable class:
```
.matrixtable tr { height: 50px; }
.matrixtable td:first-child {
  width: 3%;
}
.matrixtable td:not(:first-child) {
  width: 1%;
}
```
and apply it:
```
var myCss = {
    matrix: {root: "table table-striped matrixtable"},
};
$("#surveyElement").Survey({
    model: survey,
    css: myCss
});
```

Let me know if it works for you or not?

Thank you,
Andrew

**Comment by felixcuneo** [comment]
Hi @Andrew, it works fine thank you very much. 
For web noobs like me, you can add style="font-size:180%" in your div section to increase question text size.
Thanks !

**Comment by bramson** [comment]
Okay, the height and alternate shading are great, but how do we set the width of the columns of the matrix question?  There is no example of using the custom css feature to actually change the formatting of anything.

**Comment by tsv2013** [comment]
It's can be achieved via the following CSS:

```CSS
.matrixtable td:nth-child(2) {
  width: 150px;
}
```

For more details you can check the [documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/%3Anth-child)

**Comment by bramson** [comment]
Thank you.  Actually, I knew the CSS for the formatting I want, but I can't figure out from the above plnkr, [this example](https://surveyjs.io/Examples/Library/?id=survey-cssclasses&platform=jQuery&theme=default) or [this example](https://surveyjs.io/Examples/Library/?id=survey-customcss&platform=jQuery&theme=default) how to get a survey to use any formatting that I specify.  I like the matrixtable shading etc, and I just want to add the column widths, but I can't figure out how to get the survey to use that styling.  Actually, I can't even adapt the "CSS classes" example and make the text of my required question red.  My CSS is just ignored no matter how I try to implement it.
