### ISSUE TITLE
Limiting nº of selections in select2 widget

### ISSUE THREAD

**Issue by Kuhax** [surveyjs/surveyjs#454]
Hello.

I would like to change dynamically the maximum number of selections of select2tagbox widget. This behaviour is explained in select2 [documentation](https://select2.github.io/examples.html#multiple-max)

In order to be able to change this value dynamically in a survey I am using `onMatrixCellValueChanged` event. 

Please take a look at this [plunk](https://plnkr.co/edit/L2q4a52Lzk6Illw3vAu6?p=preview). I am not sure if the procedure is correct or rather it's a bug.

Thanks

**Comment by tsv2013** [comment]
@Kuhax I've modified your [plunk](https://plnkr.co/edit/3GqBKQioLchtmVjxHMFq?p=preview). Can you check whether it fit your needs?

**Comment by Kuhax** [comment]
@tsv2013 I have tried your plunk but I can't make it work. To explain you the context I have modified the [plunk](https://plnkr.co/edit/1bcO3k?p=preview) by adding `onMatrixCellCreated` and `onMatrixCellValueChanged` events. 

Please notice that `onMatrixCellCreated` won't work in the plunk for some reason. Actually it works well in my survey.

What really concernes me is that `question.maximumSelectionLength = 1;` doesn't seem to work.

Thanks in advance.

**Comment by tsv2013** [comment]
@Kuhax Your original [plunk](https://plnkr.co/edit/L2q4a52Lzk6Illw3vAu6?p=preview) did not contain matrixdynamic widget, and the `onMatrixCellValueChanged` event wasn't called at all.
I've modified your new [plunk](https://plnkr.co/edit/62cKrN?p=preview), adding `question.choicesChangedCallback()` in order to force update select2 options. Does it fit your needs?

**Comment by Kuhax** [comment]
@tsv2013 thanks !  It worked for me. Although I got an exception on `question.choicesChangedCallback();` but finally found the issue. A tip for guys out there: in case you have some more logic involved, `question.choicesChangedCallback();` should always follow either `question.maximumSelectionLength = 1;` or `question.maximumSelectionLength = undefined;` otherwise you'll get an exception.

@tsv2013 I have one more question lef when you select more than 1 element a generic message in english appears: "You can only select one item". Going through select2 [documentation](https://select2.github.io/examples.html#language) it appears that there is a way to localize this message. I have tried adding `language: "es"` to `$el.select2({` but it won't work

**Comment by tsv2013** [comment]
@Kuhax I've found [this section in the select2 codumentation](https://select2.github.io/options-old.html#language) concerning localization. According to it,

> Heads up! When using translations provided by Select2, you must make sure to include the translation file in your page after Select2.

I've also updated your [plunk](https://plnkr.co/edit/62cKrN?p=preview) with cusom message.
