### ISSUE TITLE
Do choicesByUrl title name supports multiple language?

### ISSUE THREAD

**Issue by AxelRamiro** [surveyjs/surveyjs#459]
### Are you requesting a feature, reporting a bug or ask a question?

Question: Do choicesByUrl title name supports multiple language?

### What is the current behavior?

I set choicesByUrl like this:
`
choicesByUrl: {
      url: "MY_URL",
      valueName: "id",
      titleName: "name"
     }
`

With results of my API like: 

`
[
 {
  name: {
    en: "English",
    es: "Spanish"
  },
  id: 1
}
 ]
`

And the survey renders only "id" values in the dropdown options.

### What is the expected behavior?

I expect to see choice title according to survey's locale

### Specify your

* browser: Opera
* browser version:	45.0.2552.898
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 0.12.17

**Comment by andrewtelnov** [comment]
@AxelRamiro Unfortunately not. It makes perfect sense to add this functionality.
At the current moment you will have to modify the name property in run-time:
`myquestion.choicesByUrl.titleName = "name.en";`

However, I am not sure "name.en" will work. I have to check.

Thank you,
Andrew

**Comment by AxelRamiro** [comment]
@andrewtelnov Thank you for answering. I'll try with your suggestion.

**Comment by andrewtelnov** [comment]
@AxelRamiro the current version doesn't support the complex property for valueName and titleName. I have added this functionality. It will be available in the next minor release.

Thank you,
Andrew

**Comment by jbrou015** [comment]
Hello. I cannot get this to work. Can you help. 

My Institution service is returning:

_[{"value":"1","locName":{"en":"My Institution","fr":"Mon institution"}},{"value":"2","locName":{"en":"Second Instit","fr":"Deuxieme institution"}},{"value":"3","locName":{"en":"Third","fr":"Troizieme"}}]_

And in my json:

 "choicesByUrl": {
            "url": "/api/Institution",
            "titleName": {
              "en": "locName.en",
              "fr": "locName.fr"
            },
            "valueName": "value"
          }

Thanks.
