### ISSUE TITLE
Ability to provide secure question hints

### ISSUE THREAD

**Issue by mbeynon** [surveyjs/surveyjs#46]
I would like to use surveyjs to conduct tests of student knowledge.  The problem is I want to separate out survey takers with greater knowledge that can answer the question with no extra help.  Others may need a hint (or two) to be able to get started and then can make progress on their own.  Still others may need several hints before they can do anything with a question.  At a high level, the scoring we have to perform afterward will need to take the level of hinting required to get to a correct answer.

It's important that the survey model on the client does NOT contain the hints until they are asked for.  It would be easy to bring up browser developer tools and see the additional hints in memory, thereby invalidating the meaning of the test because the taker had hints that were unaccounted for.  The hard requirement is any hints must be dynamically added to the model on the client.  In general a hint could change the question and the multiple choice answers, but to keep it simple we could probably limit it to just a more descriptive question and leave the answers the same.

It would be great if surveyjs supported this notion natively, with a user-defined callout like the validation code does now, but instead to ask the server for the hinted question title and call a surveyjs API to update the question title and hint level, and for the completed report to indicate the level of hint shown for each question.  From looking at the examples and code it does not currently support this, so I'm looking for a workaround.

Is it possible to implement a parent React component that feeds the surveyjs component?
- Parent component presents the hinting UI.  When click on hint, need to know from surveyjs component which page/question is current.
- Parent communicates with the server to request a hint-level enhanced question title, and then updates the model props passed into surveyjs.
- Q: Would surveyjs be able to handle such changes to the model and still maintain it's state correctly for past page questions and the current page?

I don't see question responses being stored as state in the react components, so I presume this just lives in the DOM until advancing to the next page.

**Comment by andrewtelnov** [comment]
Hi,

I understand what you are trying to implement here.

If you would not worry about showing survey json, then you would have something like that:
Question N: Question title and a  radio group: (hard) – (easy).
Question N (hard): visible by default. It may not have a title and it has question.indent > 0
Question N (easy): invisible by default and it has question.indent > 0

Using “setValue” trigger (http://surveyjs.org/examples/trigger-setvalue.html) , you may set an invisible question value that a student actually look at the easy question. Another way is to hide Question N and Question N (hard) completely on choosing (“easy”) and make the easy question visible, so a student will not be able to return to the hard question and use a tip(s) to answer it.

So, now the question to you :-). If you would get the full json from the server, then surveyjs will built the survey based on the json metadata and json will be disappeared. Do you concern that your student may intercept the json when it passed from the server? 

About “Quiz” – I am thinking to add this functionality directly into surveyjs and dxsurvey.com. 
For example, currently I have an idea to pass encrypted corrected answers to a client. However, a client (surveyjs lib) will not able to decrypt the answer, there will be the ability to check, if the answer correct or not, by encrypting the given answer and compare the result with the encrypted correct answer. 
If you have any requirements, I would be happy to learn them.

Thank you,
Andrew

**Comment by kbrown** [comment]
> However, a client (surveyjs lib) will not able to decrypt the answer, there will be the ability to check, if the answer correct or not, by encrypting the given answer and compare the result with the encrypted correct answer. 

@andrewtelnov what's to stop someone form running the compare code from the console on each of the choices?  

I think this is something that has to be done server side.

-- kevin

P.S. "Quiz" is not a requirement for me.
