### ISSUE TITLE
Question title doesn't show variables

### ISSUE THREAD

**Issue by AxelRamiro** [surveyjs/surveyjs#461]
### Are you requesting a feature, reporting a bug or ask a question?

I think it is a bug

### What is the current behavior?

When a variable is set from code, ie.

`
survey.setVariable('foo', 'bar')
`

and is referenced in a question title

`
{
  title: "Lorem ipsum {foo}", ...
}
`

the title doesn't show the "bar" value.

If a value is set instead:

`
survey.setValue('foo', 'bar')
`

The title works.

### What is the expected behavior?

When a variable reference is used on question title its value should be rendered.

### How would you reproduce the current behavior (if this is a bug)?

Setting a variable in some event handler, for example "onValueChanged" and using it on a question title

### Specify your

* browser: Opera
* browser version: 45.0.2552.898
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 0.12.17

**Comment by andrewtelnov** [comment]
@AxelRamiro Yes, I have found other issues as well.
I have added a unit test and fix the issue. It should be fine from the next minor.

Thank you,
Andrew
