### ISSUE TITLE
Numeric validator does not validate negative numbers if minValue: 0

### ISSUE THREAD

**Issue by dmitrykobets** [surveyjs/surveyjs#462]
### Are you requesting a feature, reporting a bug or ask a question?

reporting a bug

### What is the current behavior?

Setting a numeric validator with a minValue: 0 does not give validation error for negative numbers.

### What is the expected behavior?

A numeric validator with a minValue: 0 should give validation error for any number < 0

### Specify your

* browser: Chrome
* browser version: 58.0.3029.110
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.12.17

**Comment by dmitrykobets** [comment]
I have a fix for this so if you add me as a collaborator I could throw it in.

**Comment by gruz** [comment]
At least in 0.12.23 the validation is still broken in this case.

Here is my form
```
{
 pages: [
  {
   elements: [
    {
     type: "text",
     inputType: "number",
     isRequired: true,
     name: "email",
     title: "Enter number",
     validators: [
      {
       type: "numeric",
       maxValue: 100,
       minValue: 1
      }
     ]
    }
   ]
  }
 ]
}
```

It allows to complete the form when entering zero.

And if I set minValue to zero in the form JSON, then the survey editor strips the parameter.
At my test site in this case it treats non-numbers as nothing, as if there is nothing entered. But it should show an error message.

So with minValue=1 it allows to enter zero.
With minValue=0 it allows to enter non-numbers.

**Comment by andrewtelnov** [comment]
@gruz Yes, there was a bug. The unit test is added and fixed. The fix will be available in the next minor update, likely next week.

Thank you,
Andrew

**Comment by tyzzzon** [comment]
Maybe I'm doing something wrong but number min/max validation doesn't work for me at all. I tried it in v 1.7.5 and v 1.8.4. I tried it in survey creator.
My element is 
```
{
    "type": "text",
    "name": "1",
    "title": "Number of times per week =",
    "titleLocation": "left",
    "min": 0,
    "max": 100,
    "requiredErrorText": "Please enter a value of 0 or greater",
    "inputType": "number"
}
```
It accepts any number. But it doesn't allow you to enter letters(as expected)

**Comment by andrewtelnov** [comment]
@tyzzzon Please put min and max bellow inputType and it will work.
I will investigate the issue.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@tyzzzon FYI: I have fixed [the issue](https://github.com/surveyjs/survey-library/issues/2414). I added one more unit test and fixed it.

Thank you,
Andrew

**Comment by tyzzzon** [comment]
Now it doesn't allow me to select a number below zero if I click arrows. But if I type -100, the value is accepted. If I type something like "0-100", error won't appear as well.

**Comment by andrewtelnov** [comment]
@tyzzzon  It is the way text input works in browser. We set inputType, min and max attributes. The behavior depends from browser. You have to use validators. Here is [the example](https://plnkr.co/edit/1c9G8mwVhwgcXo2r).

Thank you,
Andrew

**Comment by tyzzzon** [comment]
This works, thank you

**Comment by BabuBahir** [comment]
any progress on this... if min=0 ...it still accepts negative number

**Comment by andrewtelnov** [comment]
@BabuBahir Have you seen the example? It works. The property is `minValue`.

Thank you,
Andrew
