### ISSUE TITLE
Trying to implement adding an input mask via widget - strange behaviour

### ISSUE THREAD

**Issue by bjdani** [surveyjs/surveyjs#465]
### Are you requesting a feature, reporting a bug or ask a question?
Probably asking a question but could be a bug...
Is this a bug or am I not implementing my input mask correctly using the widget?
Trying to implement an input mask so date fields work better in non-HTML5 browsers.

### What is the current behavior?
When I add an inputmask to a 'text' question via a widget the behaviour of other questions is affected but only if the other question's visibility is switched on/off. Seems like the inputmask is being applied to other questions (including radio buttons).

### What is the expected behavior?
The input mask should be applied to only the question I specify in the isFit of the widget.

### How would you reproduce the current behavior (if this is a bug)?
See this Plunker demo http://plnkr.co/edit/vrdaruWul2Lpz0mUQm5q?p=preview

Steps to replicate the issue:
1. Choose "Yes" for first question
2. The second and third questions are then displayed. Second question shows correct input mask for date. Third question radio buttons can be selected.
3. Then go back and choose "No" for the first question, then choose "Yes" for the first question again.
4. The second and third questions are then displayed again. Second question shows correct input mask for date. But the third question radio buttons can't be selected.

In my local implementation it throws the following error when I press the "Yes" option in question3:
```
Uncaught DOMException: Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('radio') does not support selection.
    at M (http://localhost:7304/Scripts/inputmask/dist/min/jquery.inputmask.bundle.min.js:9:21568)
    at http://localhost:7304/Scripts/inputmask/dist/min/jquery.inputmask.bundle.min.js:10:2881
```
It's strange because I'm not applying the inputmask to question3 at all...

#### Provide the test code and the tested page URL (if applicable)
http://plnkr.co/edit/vrdaruWul2Lpz0mUQm5q?p=preview

### Specify your
* browser: Chrome
* browser version: 58.0.3029.110 (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery
* surveyjs version: 0.12.17

**Comment by dmitrykurmanov** [comment]
@bjdani hello! I'll fix it. Thanks!

**Comment by dmitrykurmanov** [comment]
@bjdani so, you just need to remove inputmask in willUnmount. Here an examle: http://plnkr.co/edit/8OZJ88DIurm5OgAEA9Eq?p=preview

**Comment by bjdani** [comment]
Thank you so much Dmitry!
Adding the willUnmount has resolved it for me.

**Comment by alekhraut** [comment]
Hi @dmitrykobets,

I am trying to implement input mask for time i.e for hh:mm for ionic app, somehow the component is getting rendered as normal text field.

Could you please check and let me know if am missing out any thing?

Repo: https://github.com/alekhraut/ionicDemoInputMask

-Thanks

**Comment by dmitrykobets** [comment]
Hi @alekhraut I think you confused me with @dmitrykurmanov

**Comment by dmitrykurmanov** [comment]
@alekhraut, hello! I've created a small example with time inputmask: https://plnkr.co/edit/CbMV9qYPN579qg7Zlgbx?p=preview and it looks ok. I don't have any experience in Ionic but in your sample I can't find `surveyjs-widgets` string. Do you include widgets to the project? As I know Ionic works with Angular so you could check our Angular repo: https://github.com/surveyjs/surveyjs_angular_cli/blob/master/src/app/app.component.ts we have all widget examples there.
