### ISSUE TITLE
Possible to insert a Google Map into a survey question?

### ISSUE THREAD

**Issue by andimiya** [surveyjs/surveyjs#466]
This is an amazing product, great job!
QUESTION:
Wondering if it's possible to embed a script in a survey question? In particular, I'm trying to add a Google Map to one of the survey questions.

I tried adding it to the HTML question type but it seems to not accept the script portion. Is there any other way using your tool?

Sample Google Maps HTML (please insert your own API key)

```
<!DOCTYPE html>
<html>
  <head>
    <style>
      #map {
        height: 400px;
        width: 100%;
       }
    </style>
  </head>
  <body>
    <h3>My Google Maps Demo</h3>
    <div id="map"></div>
    <script>
      function initMap() {
        var uluru = {lat: -25.363, lng: 131.044};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 4,
          center: uluru
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap">
    </script>
  </body>
</html>
```

**Comment by andimiya** [comment]
It appears to have worked suddenly!
Closing this issue.

**Comment by dmitrykurmanov** [comment]
@andimiya, hello! Thanks for your interest! Could you create an example on plunker or fiddle to share your experience with community. If you don't mind, we'd like to add correcponding example on our site, of course with mention of your efforts.
