### ISSUE TITLE
isRequired text questions allow user to enter just whitespace

### ISSUE THREAD

**Issue by bjdani** [surveyjs/surveyjs#468]
### Are you requesting a feature, reporting a bug or ask a question?
Bug (or is there an alternative way of validating this without having to write extra javascript?)
I tried using regex validator on the question but could not get it to fire correctly for answers that only contain spaces.

### What is the current behavior?
If the users enters 1 or more spaces as their answer to a question that has isRequired = true, the answer is valid.

### What is the expected behavior?
Since the survey results are trimmed, I would expect this answer to trigger the isRequired validation.

### How would you reproduce the current behavior (if this is a bug)?

1. Create a question of input type "text"
2. Change it's isRequired flag to true
3. Run the survey
4. Enter "   " (one or more spaces) for the answer to the question
5. Complete the survey.
6. The survey results contain the answer to the question as a single space char. No validation message is show for the question so prompt the user that they have not filled it in.

### Specify your
* browser: Chrome
* browser version: 58.0.3029.110 (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.12.18

**Comment by andrewtelnov** [comment]
@bjdani Yes, it is a bug and I have fixed it.

Thank you,
Andrew

**Comment by bjdani** [comment]
Hi Andrew,

Thank you! Any estimate on when that will make it into the next release?

Thanks,
Bruce

**Comment by andrewtelnov** [comment]
Sure, We will release it on Friday or more likely early next week.

You may use dev version for a while if it is urgent: https://github.com/surveyjs/builds

Thank you,
Andrew
