### ISSUE TITLE
version 0.12.18 Angular4 webpack compilation error

### ISSUE THREAD

**Issue by gdaniels13** [surveyjs/surveyjs#470]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug with angular4 and survey.  version 0.12.17 works 

### What is the current behavior?
Webpack fails to compile.
### What is the expected behavior?
Webpack should compile.

### How would you reproduce the current behavior (if this is a bug)?
- Use angular cli to create new project `ng new surveyjsBug`
- Use npm to add surveyjs as a dependency `npm install -save survey-angular`
- `npm install`
- add `import * as Survey from 'survey-angular';` as an import in `surveyjsBug/src/app/app.component.ts`
- `npm start`
At this point webpack will fail to compile with the following output
```PS C:\code\surveyjsBug> npm start

> surveyjs-bug@0.0.0 start C:\code\surveyjsBug
> ng serve

** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
Hash: 9000c28a33d0e956ba98
Time: 6616ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 160 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 5.34 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 10.5 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.18 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in C:/code/surveyjsBug/node_modules/survey-angular/survey.angular.d.ts (379,22): Duplicate identifier 'SurveyElement'.

ERROR in C:/code/surveyjsBug/node_modules/survey-angular/survey.angular.d.ts (734,22): Duplicate identifier 'SurveyElement'.
webpack: Failed to compile.
```

If you modify the package.json to pull in version 0.12.17 webpack will compile successfully. 

### Specify your

* browser: NA
* browser version: NA
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version:  0.12.18
* npm/node versions: 4.1.2/7.5.0 and 5.0.3/6.10.3

**Comment by dmitrykurmanov** [comment]
The problem appear in react, jquery and angular dts.

**Comment by dmitrykurmanov** [comment]
@gdaniels13 hello! Thanks for your interest. We've fixed the bug and this fix will include in next release. And if you need fast workaround you could copy and paste this [code ](https://gist.github.com/dmitrykurmanov/6f21f71582fc998f4db1d9d5289ba2bb) to _*/surveyjsBug/node_modules/survey-angular/survey.angular.d.ts_

**Comment by gdaniels13** [comment]
@dmitrykurmanov Thanks for getting that fixed so fast.  (For some reason I never saw any notifications from github).
