### ISSUE TITLE
Reload answer into blank survey form

### ISSUE THREAD

**Issue by nadialo** [surveyjs/surveyjs#471]
Is there any function that we can reload the answer into the blank form? (i.e. draft-saved the form and reload the draft answer back to the survey)
Thanks!

**Comment by andrewtelnov** [comment]
@nadialo Sure, take a look at these demos:
http://surveyjs.org/examples/jquery/survey-data/
http://surveyjs.org/examples/jquery/survey-displaymode/

Thank you,
Andrew

**Comment by nadialo** [comment]
Thank you so much!
