### ISSUE TITLE
VisibleIf for every answer choice

### ISSUE THREAD

**Issue by pietervdheuvel** [surveyjs/surveyjs#472]
Question/feature request:

Is there a way to toggle the visibility of answer options based on answers in previous questions? I.e. i only want to show a brand name for an _ownership_ multiple choice question, if a respondent has indicated they are _aware_ of the brand in a previous multiple choice question.

I could not find this in the editor or in any other feature requests.

**Comment by andrewtelnov** [comment]
@pietervdheuvel Do you want to have the different choices for different answers in another question, am I right?
It this case, I would suggest to have two different questions with different choices and visibleIf propeties, but with the same name/title.

Thank you,
Andrew

**Comment by pietervdheuvel** [comment]
Hi Andrew,

Thanks for the fast response. I suppose that is a workaround on the technical side. The forced displaying of a question name/title does clog the UI however. The example below (2,3,4,5  being the workaround, and 6 being the ideal situation) is using four brands as an example, but the lists for brand research usually go up to max 20-30.

![image](https://user-images.githubusercontent.com/11663953/27585827-0a33211a-5b3e-11e7-8a8b-3cecf56f0d8a.png)

**Comment by andrewtelnov** [comment]
@pietervdheuvel Here is the demo: https://plnkr.co/edit/FfYvPB?p=preview

**Comment by andrewtelnov** [comment]
No reply for several months. I am closing the issue.

**Comment by dprogaki** [comment]
Hello! Is there any possibility this will be implemented another way? The reason I'm asking is I need this for more than one questions and each question will have to add more text to each choice.

So if the user has chosen Nissan and Peugeot in the first question, the second question would have Nissan micra and Peugeot 308 but the third question could have Nissan quashkai and Peugeot 2008 and so on...

Thanks in advance

**Comment by andrewtelnov** [comment]
@dprogaki Theoretically we can add ability to use the visible question property inside the visibleIf
So it will be `visibleIf = "{nissan.visible} && {nissan} = 'micra'";`
However, it is something for the future.
I do not have any other ideas.

Thank you,
Andrew
