### ISSUE TITLE
Widget and CSS class 

### ISSUE THREAD

**Issue by LEGrecc** [surveyjs/surveyjs#474]
### Are you requesting a feature, reporting a bug or ask a question?

Features

### What is the current behavior?

Hi,

 I would like to know if it is possible to edit some widget questions directly in the survey editor and if so how to do it. It seems I have only access to the basic questions and I cannot add widget questions . Is it because I have to do it manually for each widget ? 

Also I would like to know what are the class names  in css for the progress bar in order to change colors. I have tried .sv_progressBar but the all Bar is fulfilled and I would like to have only the part that is completed in the survey. (i.e. Page 1 of 5) 

Thank you in advance. 

Best, 

Thomas  

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@LEGrecc What do you mean to change the css classes? 
Do you want to have the different css classes for different questions?
Here is the example of using the custom css classes for all questions: http://surveyjs.org/examples/jquery/survey-customcss/

Take a look at names: progress and progressBar you may set/add your own class to change the color.

Thank you,
Andrew

**Comment by LEGrecc** [comment]
Thank you for your answer. No I just want to change the colour of my progress bar. I have tried with "sv_progress" with :
```
 .sv_progress {
  background-color: lightgreen;
  color:red; }
```
As the color of **all** the progressbar has changed in lightgreen,  I am not able to show to a user how far along he/she is in a process. It is not a progress bar anymore. 
 I would like to color only the part that is completed in the survey. (i.e. Page 1 of 5) .

In the survey.jquery.js you have:
```
var defaultStandardCss = {
    root: "sv_main",
    header: "",
    body: "sv_body",
    footer: "sv_nav",
    navigationButton: "", navigation: { complete: "sv_complete_btn", prev: "sv_prev_btn", next: "sv_next_btn" },
    progress: "sv_progress", progressBar: "",
    pageTitle: "sv_p_title",
    row: "sv_row", 
```

I have tried to change  progressBar in CSS as well but it does not work.

**Comment by andrewtelnov** [comment]
@LEGrecc Do you use a standard css and not bootstrap? Is it correct?

**Comment by LEGrecc** [comment]
yes I am using standard CSS and I am not using bootstrap. I have downloaded the file called survey.css

**Comment by andrewtelnov** [comment]
@LEGrecc Here is the demo: https://plnkr.co/edit/O2jTBO?p=preview

Thank you,
Andrew

**Comment by LEGrecc** [comment]
Hi Andrew thank you for your answer. That is exactaly the problem I have. In your demo, the progress bar is all green and it does not change when you answer questions. Instead of that, I would like to have a progress bar like in this example : http://surveyjs.org/examples/jquery/survey-autonextpage/ 
Is it possible ? Thank you, Thomas

**Comment by andrewtelnov** [comment]
@LEGrecc I see the problem now. I was not able to come up with a good solution. Right now we are using width: auto and min-width: {progress}%. If I change it to width: {progress}% it would solve this issue. However, another issue will comeback: the progress text becomes invisible for some surveys (a lot of pages + small survey width). 
Let me think about it.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@LEGrecc I have updated the css in the demo on plunker. It looks fine now:
https://plnkr.co/edit/O2jTBO?p=preview

Thank you,
Andrew

**Comment by LEGrecc** [comment]
Thank you Andrew. It works perfectly now.



2017-07-02 10:54 GMT-04:00 Andrew <notifications@github.com>:
