### ISSUE TITLE
Matrix question type and visibleIf

### ISSUE THREAD

**Issue by nithinM** [surveyjs/surveyjs#475]
### Are you requesting a feature, reporting a bug or ask a question?
Question

I want to know is that possible to implement below scenario. If so please let me know how I do it

**Scenario** 
When I select a value form row in the Matrix I need to show a specific question related to it.

Thank you!

**Comment by andrewtelnov** [comment]
@nithinM Here is the demo: https://plnkr.co/edit/PojiUA?p=preview

Thank you,
Andrew

**Comment by nithinM** [comment]
Thank you so much @andrewtelnov. It works.

**Comment by murrah** [comment]
It would be great to add the example ([https://plnkr.co/edit/PojiUA?p=preview](https://plnkr.co/edit/PojiUA?p=preview)) to the documention [https://surveyjs.io/Documentation/LibraryParameter?id=questionbase&parameter=visibleif](https://surveyjs.io/Documentation/LibraryParameter?id=questionbase&parameter=visibleif). It took a while to find the syntax for using a matrix as a trigger.

Thanks!

**Comment by andrewtelnov** [comment]
@murrah Yes, I have added your example: https://surveyjs.io/Examples/Library/?id=condition-complexquestions and two other examples with visibleIf.

Thank you,
Andrew

**Comment by murrah** [comment]
Thanks Andrew!
