### ISSUE TITLE
Angular 2 examples - result and settings

### ISSUE THREAD

**Issue by rroeneman** [surveyjs/surveyjs#476]
### Are you requesting a feature, reporting a bug or ask a question?
Question: I worked with your Angular examples and get the survey running. However how to reach the result data? Sorry, my limited knowledge of Angular didn't help. 

### What is the current behavior?
Can't get the result into a custom function (leading to an Angular service).

### What is the expected behavior?
To obtain the results in a variable, and to be able to insert settings.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
export class SurveyComponent implements OnInit, OnDestroy  {
    private surveyJSON: any;
        
    constructor(){}
    
    ngOnInit() {
        let params: any = this.activatedRoute.snapshot.params;
        this.surveyJSON = this._drpService.getSuveyJson(+params.id);
        const survey = new Survey.ReactSurveyModel(this.surveyJSON);
        Survey.SurveyNG.render('surveyElements', { model: this.survey });
    }
```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version: 0.12.17

THANK YOU!
Best, Roeneman

**Comment by dmitrykurmanov** [comment]
@rroeneman hello! You can get your result this way: 
```
...
const survey = new Survey.ReactSurveyModel(this.surveyJSON);
survey.onComplete.add(function(result) {
	console.log("Survey Result: " + result.data);
});
```

**Comment by rroeneman** [comment]
Thank you, and now the probably very much newby question: How to access 'oncomplete' outside of the Oninit function? I tried to make a variable with public etc., but lack knowledge to do this right.... sorry and thanks for this next step.

**Comment by dmitrykurmanov** [comment]
@rroeneman maybe changing `const survey =` to `this.survey = ` will help. Anyway if I understand you right this is angular2 problem, not surveyjs.

**Comment by dmitrykurmanov** [comment]
@rroeneman you could create an example in plunker based on one of our examples (https://plnkr.co/edit/?p=preview) and we will try to help you.

**Comment by rroeneman** [comment]
Thank you, got it sorted. This is my solution:


`
...
export class ...
  private mysurvey:any;
  private surveyJSON:any;
    ngOnInit() {
        this.surveyJSON = .... get the surveyJSON out of a service or just copy it here ....
        this.mysurvey = new Survey.ReactSurveyModel(this.surveyJSON);
        Survey.SurveyNG.render('surveyElements', { model: this.mysurvey });

HERE STARTS THE DIFFERENCE, CALL EXTERNAL FUNCTION FROM NESTED FUNCTION WITH THE ARROW 
        this.mysurvey.onComplete.add(() => { 
           this.surveyResult(); 
        });
    }

   surveyResult(){
      //ACCESS DATA LIKE THIS
      console.log(this.mysurvey.data);
  }
}
`


Thanks for your help, so indeed it was not surveyJs but actually I believe a typescript issue.
Best, Roeneman
