### ISSUE TITLE
Calling rest to make calculations on for example "multipletext" type

### ISSUE THREAD

**Issue by towojtek** [surveyjs/surveyjs#478]
### Are you requesting a feature, reporting a bug or ask a question?

Feature

### What is the current behavior?

For now just a dropdown questions can use rest calls.

Example json:
{ type: "dropdown", name: "country", title: "Select the country...", isRequired: true,
choicesByUrl: {url: "https://restcountries.eu/rest/v2/all", valueName: "name"} }

### What is the expected behavior?

Possibility to call rest on other types like : "multipletext".

Example:
{ type: "multipletext", name: "animals", title: "Animals",
items: [{ name: "question_1", title: "How many cats do you have?",isRequired: true },
{ name: "question_2", title: "How many dogs do you have?", isRequired: true },
{ name: "question_3", title: "How many cows do you have?", isRequired: true },
// expected : call rest to receive number of animals and print it as 4th item ( I know that there is //possiblity to make calculations on front-end side but I want all of calculations to be made on backend //side
//example of 4th imagined item (it got to reacts on changes in previous 3)
// { name: "sum_Of_Animals", title: "Total amount of animals",
// visibleIf: "{animals.question_1} > 0 and {animals.question_2} > 0 and {animals.question_3} >0"},
// valueByUrl : { url : "address to rest service which takes 3 values from previous items and respond with sum of them", valueName : "title of json respond "sum" when response is {"sum" : "4"}"
]},

### How would you reproduce the current behavior (if this is a bug)?

It's not a bug, it's a feature ;)

Duplicated on Editor branch too.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@towojtek I have created a demo: https://plnkr.co/edit/x7T4XW?p=preview
Unfortunately, I had to make a small fix in the library. The demo is working with the "dev" version of the library. We will release next minor version early next week.

Thank you,
Andrew

**Comment by WojciechDob** [comment]
I see, you didn't get my point. I wanted an example which makes for example mathematical operations on answers.

Answer of 1st question: 5
Answer of 2rd question: 4
Answer of 3th question: 10
ITEM WITH SUM OF THOSE QUESTIONS : 19  <------ this is what I wanted. Not to generate items :P
After inserting all of those calculations there would be an sum in for example comment

**Comment by dmitrykurmanov** [comment]
@WojciechDob, hello! Thanks for your interest! I've created small example: 
https://plnkr.co/edit/dHDyRAEIGbmdPJLbSkYe?p=preview
is it ok for you?

**Comment by WojciechDob** [comment]
Hi again! Unfortunately this example fails after changing values for more then one time.
For example, 1st = 5, 2rd = 5, 3th = 5 then, you change 1st = 7. The sum should be 17 but it gives 22 :/

**Comment by dmitrykurmanov** [comment]
@WojciechDob, hello! In fact _custom widgets_ it is just API for your creation. Your can do what you need with it. So this example was just fast showcase.

PS anyway I've updated the example: https://plnkr.co/edit/dHDyRAEIGbmdPJLbSkYe?p=preview
PPS we think about better positioning of _custom widgets_ . May be it will be just collections of surveyjs questions with something like that:  `import someWidget from surveyjs-widgets;`
