### ISSUE TITLE
Dropdown question type displays "value" instead of "text" in Display mode

### ISSUE THREAD

**Issue by grnsphere** [surveyjs/surveyjs#483]
If a drop down question is setup with choices like: 
 [{ value: 1, text: "Value 1" }, { value: 2, text: "Value 2" }]

and user data is passed to the survey and the survey is in display mode, then the rendered div shows the dropdown "value" instead of the associated "text.

Perhaps, in display mode, the dropdown should be rendered as a disabled SELECT rather than a DIV (similar to how radiogroups are handled). 

i.e. 

    SurveyQuestionDropdown.prototype.renderSelect = function () {
       this.question.inputId, className: this.css.control }, this.question.value));
        var options = [];
        for (var i = 0; i < this.question.visibleChoices.length; i++) {
            var item = this.question.visibleChoices[i];
            var key = "item" + i;
            var option = __WEBPACK_IMPORTED_MODULE_1_react__["createElement"]("option", { key: key, value: item.value }, item.text);
            options.push(option);
        }
        var onChange = null;
        if (__WEBPACK_IMPORTED_MODULE_5__utils__["a" /* browser */].msie || (__WEBPACK_IMPORTED_MODULE_5__utils__["a" /* browser */].firefox && __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_5__utils__["b" /* compareVersions */])(__WEBPACK_IMPORTED_MODULE_5__utils__["a" /* browser */].version, '51') < 0)) {
            onChange = this.handleOnChange;
        }
        return (__WEBPACK_IMPORTED_MODULE_1_react__["createElement"]("select", { id: this.question.inputId, className: this.css.control, value: this.state.value, onChange: onChange, onInput: this.handleOnChange, disabled: this.isDisplayMode },
            __WEBPACK_IMPORTED_MODULE_1_react__["createElement"]("option", { value: "" }, this.question.optionsCaption),
            options));
    };

Instead of:

    SurveyQuestionDropdown.prototype.renderSelect = function () {
        if (this.isDisplayMode)
            return (__WEBPACK_IMPORTED_MODULE_1_react__["createElement"]("div", { id: this.question.inputId, className: this.css.control }, this.question.value));
        var options = [];
        for (var i = 0; i < this.question.visibleChoices.length; i++) {
            var item = this.question.visibleChoices[i];
            var key = "item" + i;
            var option = __WEBPACK_IMPORTED_MODULE_1_react__["createElement"]("option", { key: key, value: item.value }, item.text);
            options.push(option);
        }
        var onChange = null;
        if (__WEBPACK_IMPORTED_MODULE_5__utils__["a" /* browser */].msie || (__WEBPACK_IMPORTED_MODULE_5__utils__["a" /* browser */].firefox && __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_5__utils__["b" /* compareVersions */])(__WEBPACK_IMPORTED_MODULE_5__utils__["a" /* browser */].version, '51') < 0)) {
            onChange = this.handleOnChange;
        }
        return (__WEBPACK_IMPORTED_MODULE_1_react__["createElement"]("select", { id: this.question.inputId, className: this.css.control, value: this.state.value, onChange: onChange, onInput: this.handleOnChange },
            __WEBPACK_IMPORTED_MODULE_1_react__["createElement"]("option", { value: "" }, this.question.optionsCaption),
            options));
    };

**Comment by andrewtelnov** [comment]
@grnsphere select would not look great in display mode. I would better add a displayValue function and will use it. 
I will work on the fix tomorrow.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@grnsphere I have fixed the issue. I may update the "dev" version if you need the urgent fix.

Thank you,
Andrew

**Comment by grnsphere** [comment]
Thanks Andrew!

The fix is not super urgent. Our time frame to start fully testing our
SurveyJs integration is early August.

Chris

**Comment by andrewtelnov** [comment]
ok then.
