### ISSUE TITLE
Survey does not set isvisible property on text field

### ISSUE THREAD

**Issue by ZachStoltz** [surveyjs/surveyjs#486]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug/ requesting an enhancement to  visibleIf logic.

### What is the current behavior?
My scenario is we have 3 questions:
Q1 -> Q2 ->Q3

Q2 visibleIf: {Q1}='Yes'
Q3 visibleIf: {Q2}='Yes'

When you select Yes for Q1 and Q2 to have Q3 appear.  If that user changes Q1's answer, Q2 and Q3 should become invisible again as the condition is no longer met.

Q1 & Q3 are visible after this state change

### What is the expected behavior?
With the given scenario above.  Q1 should only be visible if it's state changes after the nested occurrence happens.

### How would you reproduce the current behavior (if this is a bug)?
https://plnkr.co/edit/nvz06XkRdXBtGg0jYFMg?p=info

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/nvz06XkRdXBtGg0jYFMg?p=info

### Specify your
* surveyjs platform (angular or react or jquery or knockout or vue):
react
* surveyjs version:
0.12.18

**Comment by ZachStoltz** [comment]
**UPDATE**: I am able to work around this if I set Q3's visibleIf to {Q1}='Yes' and {Q2}='Yes'.   Is there an API property that I can set to Clear if the variable is set to invisible immediately and not to wait for the onComplete event?

**Comment by andrewtelnov** [comment]
@ZachStoltz Yes, {Q1}='Yes' and {Q2}='Yes' is correct.
Use [clearInvisibleValues property](http://surveyjs.org/docs/api_surveymodel.html#clearInvisibleValues).

`survey.clearInvisibleValues = true;`

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
No reply for several months. I am closing the issue.
