### ISSUE TITLE
dxSurvey API POST results: Silent errors & clarification on parameters

### ISSUE THREAD

**Issue by JSafaiyeh** [surveyjs/surveyjs#487]
Currently, testing posting results to `http://api.dxsurvey.com/api/Survey/post`.

The example on http://api.dxsurvey.com/Help/Api/POST-api-Survey-post shows `PostId` and `SurveyResult`.

My current understanding is that the `PostId` is the id of the survey. For `SurveyResult`, I do not understand the format. How should it be formatted relative to the Survey format JSON?

A failed POST will return a 200 with no response. Not very helpful for identifying problems in the request itself.

**Comment by andrewtelnov** [comment]
@JSafaiyeh Could you please re-check your survey PostId? It is a typical error, wrong PostId. There are 3 Guid for each survey: Id, ResultId and PostId.
We do not any check, if the survey with this PostId exists or not, we just create a file with this postId (if it doesn't exists yet) and write a new JSON there. It allows us to keep the server load on saving results to minimum.

You may take a look at JavaScript implementation, method "sendResult": https://github.com/surveyjs/surveyjs/blob/master/src/dxSurveyService.ts 

Thank you,
Andrew

**Comment by JSafaiyeh** [comment]
Where do I get the PostId of my survey?

**Comment by andrewtelnov** [comment]
Please expand the survey on My Surveys page

**Comment by JSafaiyeh** [comment]
Perfect. Got it working.

Can I suggest updating the docs to be more clear. The example parameters do not match the service code. For example, stringifying the JSON result.

**Comment by andrewtelnov** [comment]
@JSafaiyeh Yes. At the current moment, we are working on it. We will have one site for developers: surveyjs.io with 3 main sections:
surveyjs.io/library, surveyjs.io/editor and surveyjs.io/service.
We will improve docs for library and add docs for editor and service. 
At the current moment, it is a mess. Totally agree.
dxsurvey.com will become a site for end-users without any link on libraries, API or GUID. 
A developer version will be surveyjs.io/service. It will the current dxsurvey.com with a focus on software developers. 
Data/accounts will be shared between two websites.

Thank you,
Andrew

**Comment by JSafaiyeh** [comment]
Good to hear it is being prioritized.

Thanks for the help!
