### ISSUE TITLE
Can I do Enableif just like VisibleIf ?

### ISSUE THREAD

**Issue by lalitkhanna** [surveyjs/surveyjs#490]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@lalitkhanna Somebody has already asked about this functionality. I have to agree it makes sense, if you do not want allowing editing, but do not want to hide a question. It may destroy the layout, for example.
I have added this to our TODO list: "Add question.ifReadOnly/question.ifEnabled property. Similar to ifVisible".

Thank you,
Andrew

**Comment by lalitkhanna** [comment]
Thanks, Andrew, waiting for this feature.

**Comment by andrewtelnov** [comment]
@lalitkhanna question.enableIf property is added.

**Comment by lalitkhanna** [comment]
I just test this in Editor(site) but still I didn't find EnableIf Property? I'm missing anything ?

**Comment by andrewtelnov** [comment]
@lalitkhanna it will come with the next update. We have not released it yet. 

Thank you,
Andrew

**Comment by lalitkhanna** [comment]
Thanks @andrewtelnov. Any idea when will have next released ?

**Comment by andrewtelnov** [comment]
@lalitkhanna  We may do it on Friday or early next week. Do you need it urgent?
@tsv2013 @dmitrykurmanov Let's release it after adding the Chinese localization: https://github.com/surveyjs/surveyjs/pull/506/commits

Thank you,
Andrew

**Comment by lalitkhanna** [comment]
I'm OK for Friday.

Thankyou
Lalit

**Comment by andrewtelnov** [comment]
@lalitkhanna We did not release on Friday. We have spent a lot of time by fixing a new bug: https://github.com/surveyjs/surveyjs/issues/511. Our testcafe tests reported an error with a new version of vue.
We will will release on Monday.

Thank you,
Andrew

**Comment by lalitkhanna** [comment]
Thanks. Great Job!!
But just wondering in case user wants to bring some default data from server & he/she don't want to make editable , I guess for this reason we need  to have'Enable' property as well. ?

**Comment by andrewtelnov** [comment]
@lalitkhanna There is already readOnly boolean property of get/set. Actually enabledIf change this property.
There is also isReadOnly property: 
`return this.readOnly || (this.survey != null && this.survey.isDisplayMode);`

Thank you,
Andrew

**Comment by lalitkhanna** [comment]
Gotcha :)

Thanks
Lalit
