### ISSUE TITLE
Please make breaking changes more apparent --  "conventional-changelog"

### ISSUE THREAD

**Issue by c0bra** [surveyjs/surveyjs#491]
This commit: https://github.com/surveyjs/surveyjs/commit/df88fba62e14feeea7a15368308573f65c163ecd which moved questions from `questions` to `elements` within the survey JSON was a breaking change for us, which was surprising since we were upgrading from 0.12.1 to 0.12.18 which is patch-level versioning according to semver.

I know that technically since this library is not on a 1.0 release yet nothing should be stable and anything can change, but there's nothing about breaking changes in the changelog and it would be really really handy to have that listed somewhere.

Thanks for a good project, though! And maybe look at something like https://github.com/conventional-changelog/conventional-changelog

**Comment by andrewtelnov** [comment]
@c0bra To be honest I hate breaking changes myself. I know how painful they are. That is why, I have written a code to make sure all old json are working and "questions" property is still there, as well as addQuestion/addNewQuestion methods.
I have rename the methods for "QuestionRowModel" class. However, it is for internal use. I still did not remove questions property from there:
```
    public elements: Array<IElement> = [];
    //TODO remove after updating react and vue
    public get questions(): Array<IElement> { return this.elements;}
```
Do you use this class? It uses in SurveyJS Editor during drag&drop. That's why I have made it public/export.

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
@c0bra, thanks a lot for your interest and for the "conventional-changelog" link. We'll think about it.

**Comment by c0bra** [comment]
@andrewtelnov so I'm taking the JSON from the editor and storing it in a database. I believe I'm manually pulling the JSON from the editor via the `.text` property, so some stuff pre-upgrade is under `questions` and post upgrade it's under `elements`. I think the survey.js front-end works fine.

However I have some aggregate reporting tooling that was processing survey result information and that was using the raw JSON by itself and relying on the `questions` prop. If I had dumped that into an instance of the editor and used the API it probably would have saved me. I just didn't consider doing that.

**Comment by andrewtelnov** [comment]
@c0bra Yes, you are right. "questions" will be converted to "elements" on survey serializing. 
Ok, we  had to create a breaking changes page or something like that.

Thank you,
Andrew

**Comment by c0bra** [comment]
@andrewtelnov Thanks very much for your response. Cheers!
