### ISSUE TITLE
get current page data

### ISSUE THREAD

**Issue by gstkenpo** [surveyjs/surveyjs#492]
I understand that onPartialSend is a feature for large survey. However, it is possible only send the "current" page result?
I have gone though the methods in survey model. I can't find suitable methods. Am I missing sth?

**Comment by andrewtelnov** [comment]
@gstkenpo Please call [survey.sendResult method](http://surveyjs.org/docs/api_surveymodel.html#sendResult)

Thank you,
Andrew

**Comment by gstkenpo** [comment]
just find my own way.

  //Only retrieve the results which are in current page
  var partialData = result.data;
  Object.keys(result.data).forEach(function(key) {
   var name = $.grep(survey.currentPage.questions, function(e){ return e.name == key || key.indexOf(e.name) >= 0; /*to cater key likes A1b-Comment*/})
   if (name.length === 0){
     delete partialData[key];
   }
  });
  console.log(JSON.stringify(partialData));
