### ISSUE TITLE
JSON result incorrect

### ISSUE THREAD

**Issue by nithinM** [surveyjs/surveyjs#493]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
Final JSON results contains wrong answers.
```josn
{
    "q1": "6",
    "q2": {
        "Row1": "Column1",
        "Row2": "Column1",
        "Row3": "Column3",
        "Row4": "Column3",
        "Row5": "Column3",
        "Row6": "Column3"
    },
    "q3": "q7item2",
    "q4": [
        "other",
        "q4item1",
        "q4item2",
        "q4item3",
        "q7item3"
    ],
    "q4-Comment": "Other 1",
    "q7": [
        "other",
        "q7item3",
        "q7item2",
        "q7item1",
        "q9item3"
    ],
    "q7-Comment": "Other",
    "q8": "other",
    "q9": "q9item3",
    "q8-Comment": "other 3"
}
```
In above results Q4 contains Q7 answer and Q7 contains Q9 answer.

### What is the expected behavior?
Final output should be
```json
{
    "q1": "6",
    "q2": {
        "Row1": "Column1",
        "Row2": "Column1",
        "Row3": "Column3",
        "Row4": "Column3",
        "Row5": "Column3",
        "Row6": "Column3"
    },
    "q3": "q7item2",
    "q4": [
        "other",
        "q4item1",
        "q4item2",
        "q4item3",
    ],
    "q4-Comment": "Other 1",
    "q7": [
        "other",
        "q7item3",
        "q7item2",
        "q7item1",
    ],
    "q7-Comment": "Other",
    "q8": "other",
    "q9": "q9item3",
    "q8-Comment": "other 3"
}
```

### How would you reproduce the current behavior (if this is a bug)?
Just navigate in the below demo and check the final result with the actual selected answers.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:  [Demo](https://plnkr.co/edit/0ZFOO5lCogYEcurLxvWI?p=preview)

### Specify your

* browser: Google Chrome
* browser version: Version 59.0.3071.115 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery
* surveyjs version: 0.12.19

**Comment by nithinM** [comment]
Hi @dmitrykurmanov, is there way to fix this issue?

**Comment by dmitrykurmanov** [comment]
@nithinM, hello i am sorry for the late response, I'll figure it out

**Comment by dmitrykurmanov** [comment]
withoit custom widgets it works fine

**Comment by nithinM** [comment]
Yeah that is true. But I need to used with custom widget. :(

**Comment by dmitrykurmanov** [comment]
@nithinM, of course, I understand, it is just note

**Comment by dmitrykurmanov** [comment]
@nithinM, hello!  This is the bug in our examples, we should add `willUnmount` method in it. Like in this example: https://surveyjs.io/Examples/Library/?id=custom-widget-icheck&platform=jQuery

I've updated your plnkr: https://plnkr.co/edit/NWOJvBIVxqnva7NfXpKO?p=preview, could you check it please?

In fact we are working on version 1.0. And you could just import widget and use it. So these bug will abandone.

**Comment by nithinM** [comment]
Hi, @dmitrykurmanov ! Yeah perfect it's working now. Thank you so much for get back with the solution for this. 
Cool so waiting for the new release!!!
