### ISSUE TITLE
Customize item before question title 

### ISSUE THREAD

**Issue by kangkurap** [surveyjs/surveyjs#494]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

Numerical item before title
1. Question 1
2. Question 2
3. Question 3
.
.
.

### What is the expected behavior?

Can I have options to displaying alphabetical or numerical  or completely remove the item before default question title

A. Question 1
B. Question 2
C. Question 3
.
.
.
OR 
Question 1
Question 2
Question 3
.
.
.
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version: 59.0.3071.115 
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.12.19

**Comment by andrewtelnov** [comment]
@kangkurap Please take a look at the following properties: [survey.showQuestionNumbers](http://surveyjs.org/docs/api_surveymodel.html#showQuestionNumbers) and  [survey.questionStartIndex ](http://surveyjs.org/docs/api_surveymodel.html#questionStartIndex)

Thank you,
Andrew

**Comment by kangkurap** [comment]
Perfect!
Thank you so much!
