### ISSUE TITLE
NPM's package.json "main" field references the min.js file

### ISSUE THREAD

**Issue by sylido** [surveyjs/surveyjs#495]
When building a meteor application it seems like the minifier uses the "main" field for the package to know which file needs mnification. We use a lot of npm packages and all of them seem to be referencing their non-minified .js file.
I am wondering if this is an accepted best practice and if so, could we make the change that for the survey-* packages as well ?

Current behavior uses the .min.js file, tries to be uglified+minified again, but the resulting file throws errors, i.e. it's not proper javascript.

Expected behavior is that even when uglified/minified 2+ times it should generate a valid javascript file.

The error doesn't show up when running a meteor app in developer mode.
Only when building the app, when meteor minifies the libraries's files and subsequently you run the app the browser throws an error in the console.
A simple example meteor project with survey-jquery included as an npm package in the package.json file should demonstrate the problem.

**Comment by dmitrykurmanov** [comment]
@sylido, hello! Thanks for your interest. I didn't know about this best practice and this is true for that popular packages like **jquery** or **vuejs** or many others. So we will change our package.json

**Comment by dmitrykurmanov** [comment]
this will be in next release

**Comment by dmitrykurmanov** [comment]
@sylido, please feel free to reopen issue or make some comments

**Comment by sylido** [comment]
@dmitrykurmanov thanks for the fast response, will do if there are any problems. Currently we deploy things by just modifying the field and it seems to work as intended.
