### ISSUE TITLE
survey js submit survey with api call

### ISSUE THREAD

**Issue by xiuzhen1103** [surveyjs/surveyjs#497]
### Are you requesting a feature, reporting a bug or ask a question?

requesting a feature

### What is the current behavior?
When survey is completed shows the html text indicating survey is completed

### What is the expected behavior?
when submit a survey, may I have a customized post api call inside it, please?
Is there any chance that I could add a cancel button beside it, or do you have this function provided?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code
```
 model.onComplete.add(function(result) {
  document.querySelector('#container').innerHTML = "<div class='panel'><h2>Survey has been submitted</h2>" ;
}
```
```

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103 hello! If I understood you correctly, you need to control "onclick" of "complete" button?

**Comment by andrewtelnov** [comment]
@xiuzhen1103 Please take a look at [survey.completedHtml property](http://surveyjs.org/docs/api_surveymodel.html#completedHtml)
Here is the demo of using it: http://surveyjs.org/examples/jquery/survey-processtext/

**Comment by xiuzhen1103** [comment]
control "onclick" of "complete" button was one question, 
second one is :
do you provide cancel button? to confirm if cancel , something like this
![image](https://user-images.githubusercontent.com/6764095/28206647-9dbfbb44-687e-11e7-96a2-416194ac281d.png)

**Comment by dmitrykurmanov** [comment]
I think it makes sense. We could optionally provide "сonfirmation dialog" when "complete" button "onclick" from the box or just give event and possibility to handle it. @xiuzhen1103, @andrewtelnov what do you think about it?

**Comment by xiuzhen1103** [comment]
hi Dmitry,
Thanks for the suggestion , is there any chance that I could have a cancel button beside submit button for our project. 
![image](https://user-images.githubusercontent.com/6764095/28207332-3f69f818-6881-11e7-849b-4c1ea794f11e.png)

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103 hello! And what will "cancel" button do? Will it go to the first page and clean all answers or something like that?

**Comment by xiuzhen1103** [comment]
cancel button pop up a dialog modal as the screenshot I posted, provides two option Yes and No, when click no return to survey form, click yes, direct to other page.

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103 as a workaround you could try to do it by yourself. Here an example: https://plnkr.co/edit/DYmf4jOSSDWEu7uwHB7a?p=preview

**Comment by dmitrykurmanov** [comment]
and we will think about this feature

**Comment by xiuzhen1103** [comment]
Thanks Dmitry,

unfortunately, this is not working
![image](https://user-images.githubusercontent.com/6764095/28208746-330264d8-6887-11e7-86bd-6419977a1934.png)

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103 that is strange, I can't reproduce this problem in chrome, which browser do you use?

**Comment by xiuzhen1103** [comment]
chrome

**Comment by xiuzhen1103** [comment]
Version 60.0.3112.66

**Comment by xiuzhen1103** [comment]
It worked now, very strange.

**Comment by xiuzhen1103** [comment]
Is there any chance that I could rename button "complete" to "submit"

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103 yes, you can use localization http://surveyjs.org/examples/jquery/survey-localization/

**Comment by xiuzhen1103** [comment]
localization is not working 
https://plnkr.co/edit/DYmf4jOSSDWEu7uwHB7a?p=preview

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103 you forget about `survey.locale = "my"` and it should be defined before render: https://plnkr.co/edit/ZWAxird0m4PPZMucddEB?p=preview

**Comment by andrewtelnov** [comment]
@xiuzhen1103 Another way to implement it is to use the custom navigation. You may turn off showing the standard navigation button and use your own. Here is the demo: http://surveyjs.org/examples/jquery/survey-customnavigation/
As for button text, there is an easy solution as well. Here is the list of properties to change the buttons text:
survey.pagePrevText, survey.pageNextText and survey.completeText.

Thank you,
Andrew

**Comment by xiuzhen1103** [comment]
@andrewtelnov, thanks millions!!!  this would make more sense, and works perfectly. I have tried in my local project, localization not work for me, error message its locales is not defined.

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103 yes, I forgot about custom navigation! By the way, for using custom localization you need to redefine (or copy-past and modify) all strings, so it is more complex solution.

**Comment by dmitrykurmanov** [comment]
working excample with custom locale for someone else from issues search: https://plnkr.co/edit/ZWAxird0m4PPZMucddEB?p=preview

**Comment by xiuzhen1103** [comment]
Thanks for all the help!!! @dmitrykurmanov  @andrewtelnov
