### ISSUE TITLE
Get text instead of value by using {question1} syntax into a title ?

### ISSUE THREAD

**Issue by boitaumail** [surveyjs/surveyjs#499]
### Are you requesting a feature, reporting a bug or ask a question?
Hi everyone, I would like to ask a question.

### What is the current behavior?
I know how to show a value into a title by using the {question_name} syntax.

### What is the expected behavior?
I would like to get the text used to label the choices instead of the value itself. Is that possible ?

#### Provide the test code and the tested page URL (if applicable)

Test code

{
 pages: [
  {
   elements: [
    {
     type: "radiogroup",
     choices: [
      {
       value: "value1",
       text: "text1"
      },
      {
       value: "value2",
       text: "text2"
      },
      {
       value: "value3",
       text: "text3"
      }
     ],
     name: "question1"
    },
    {
     type: "text",
     name: "question2",
     title: "Hello {question1}"
    }
   ],
   name: "page1"
  }
 ]
}

Thank you.

**Comment by andrewtelnov** [comment]
@boitaumail I would say, it is an expected behavior. Yes, it would require some refactoring, but I would consider this as a bug. I will work on the fix.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@boitaumail I have fixed the bug at last. 

Thank you,
Andrew
