### ISSUE TITLE
Load pre-saved result into the survey

### ISSUE THREAD

**Issue by buddhika23** [surveyjs/surveyjs#501]
### Specify your

* browser: Chrome
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version: 0.12.19

**Comment by Kuhax** [comment]
@buddhika23 This feature is well documented in [http://surveyjs.org/examples/jquery/survey-data/](http://surveyjs.org/examples/jquery/survey-data/)

These two lines will get the job done.

```
//Use setValue to set the value of the question
survey.setValue('questionName', newValue);

//Use data property to get/set survey data as json
survey.data = {"youquestion1": value1, "youquestionN":valueN};
```

setting partially filled JSON to `survey.data` will do the trick
