### ISSUE TITLE
Change options of 2nd dropdown depending on the choice of the 1st

### ISSUE THREAD

**Issue by DulceRusso** [surveyjs/surveyjs#502]
Hello there, I'm testing this tool in order to check if I use it on the project I'm currently working on. However, there's something that I think it's still uncovered or if it isn't, then it hasn't been specified in the documentation.

I have two dropdowns: the first one has a list of countries and the second a list of provinces. Depending on the country I choose, I make an ajax request to retrieve the provinces that belong to the selected country. 

However, I don't find a way to implement this on the survey. Anyone knows how? If I can achieve this, then I'll be able to use it on my project, otherwise maybe I'd use it when I don't require to ask this.

Thank you for your attention :)

**Comment by dmitrykurmanov** [comment]
@DulceRusso, Hello thanks for your interest. I think, that we already have this enhancement. Please check #393:

from Andrew Telnov:
> country -> state -> city?
> I was thinking to add this functionality from the beginning, but then decided to wait until somebody actually ask for it :)

 Is it the same feature?

**Comment by andrewtelnov** [comment]
@DulceRusso Are you using a web rest service?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@DulceRusso I have found a plunker demo: https://plnkr.co/edit/0sZFOKzlAlWUujDpgQuN?p=preview

Thank you,
Andrew

**Comment by DulceRusso** [comment]
Hello. Thank you for your answer. That's what I was looking for. And nope, I'm not using a web rest service. I have the information stored in a database and I retrieve it with Ajax. This returns an array of <option>choice</option> html elements to add them in a select.

But, I think by just returning a json the drop down can read it correctly, right? Advice on this part would be very welcome. Once again, thank you.

And, actually I do this with three drop downs:
Country->Province->Community

**Comment by andrewtelnov** [comment]
@DulceRusso you have to use survey.onValueChanged event. Here is the example on plunker: http://plnkr.co/edit/FfYvPB?p=preview
You have to call your ajax request onValueChanged and then on ajax call back set the updated choices to the dropdown question.

Thank you,
Andrew

**Comment by xraywu** [comment]
Hi @andrewtelnov, looking at your example on plunker - is it possible to use `{variable}` when using matrix dropdown questions? E.g Column2 depend on Column1.

**Comment by andrewtelnov** [comment]
@xraywu Sure, you should have to use [survey.onMatrixCellValueChanged](http://surveyjs.org/docs/api_surveymodel.html#onMatrixCellValueChanged) event.
Here is the example: http://plnkr.co/edit/r80ZfA?p=preview

**Comment by xraywu** [comment]
@andrewtelnov many thanks! Actually I mean importing the choices via a restful api with variable embedded in the url (example in https://plnkr.co/edit/0sZFOKzlAlWUujDpgQuN?p=preview). But I guess `onMatrixCellValueChanged` can do the trick 👍

**Comment by andrewtelnov** [comment]
@xraywu Yes, it is better to use the event at the current moment. You may use the variable, like {mytrixquestion[rowIndex].columnName}, but unfortunately there is no currentRow value, so you may write {currentRow.columnName}. You may only to use the absolute row index and it is tricky.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@xraywu We have implemented the row variable, it returns the current row values. You may use the following syntax: {row.columnName}

Thank you,
Andrew
