### ISSUE TITLE
Refresh to 1st page after click submit button

### ISSUE THREAD

**Issue by Hafees89** [surveyjs/surveyjs#505]
Hi, I try to refresh my survey page after I click submit button. I did search some code just now but seem like not like what I need. Submit > Show result > Refresh back to 1st page. It is possible?
your_code_here

```
		questions: [
		{ type: "radiogroup", name: "survey1", title: "Staff Service & Attitude", 
		colCount: 1, choices: ["Excellent", "Good", "Can improve further"] },
		{ type: "radiogroup", name: "survey2", title: "Are you an existing PA Membership?",
		colCount: 1, choices: ["Yes", "No"] },
		{ type: "radiogroup", name: "survey3", title: "Would you like to hear more about PA Benefits?", isRequired: true, choices:["Yes", "No"], colCount: 1},
		{ type:"text", inputType:"email", title: "If yes, Please enter your email address here", visibleIf: "{survey3}='Yes'",
        isRequired: false, validators: [{type:"email"}] },	
			]

		} 
		
	],
	completedHtml: "<p align='center'>Thank you for completing the survey. Have a nice day!</p>"
}
);

survey.onComplete.add(function(result) {
   //document.querySelector('#surveyResult').innerHTML = "result: " + JSON.stringify(result.data);
   //public clear(clearData: boolean = true, gotoFirstPage: boolean = true)
   // keep the data, go to the first page.
   //survey.clear(false, true);
});

**Comment by andrewtelnov** [comment]
@Haffes89 survey.clear() will do the trick.
survey.clear(false) will keep the data.

Thank you,
Andrew

**Comment by Hafees89** [comment]
@andrewtelnov  still didn't preview the survey page, it directly jump to 1st page instead going to completeHtml. Mind to advice on this matter? Thank you.

**Comment by Hafees89** [comment]
I figure out how to make it refresh by putting on meta http-equiv='refresh' content='2'. Everytime I click Submit and page will refresh in 2 second. Thank you @andrewtelnov for ur suggestion.

Regards,
Hafees

**Comment by IAmSequestered** [comment]
This is probably the correct solution to the problem I am having but I don't know how to implement it.

I don't know where to put in "meta http-equiv='refresh' content='2'". I'm not regularly a java script developer. Is it in the onComplete event or under somewhere else?

I'm using surveyjs on a kiosk. I want the survey to complete, save the data, go to the thank you page, and then after a moment or two it will 'refresh' back to the beginning of the same survey and be ready for the next user.

What's happening now is it gets to the thank you page and sits there. I've attempted to use the survey.clear(true, true) method but the data doesn't get saved, there's no thank you page and the survey doesn't get cleared.

Thanks.

**Comment by tsv2013** [comment]
@IAmSequestered  The `meta http-equiv='refresh'` (this is added to the head meta info) will refresh the whole page and all data will be lost.
You should use the `survey.clear(false, true);` as @andrewtelnov recommended earlier.

**Comment by IAmSequestered** [comment]
Thanks for the reply @tsv2013. using survey.clear I'm ending up with either the data getting lost and it not getting to the back end after submit or the data not clearing but the post is successful. 

What I thought could be done was for the meta http-equiv='refresh' command to be added to the head by using the onCompleted event. That intent being, that the page would send the data to the back end, the thank you message would be displayed for a couple of seconds and then the page would refresh ONCE causing the survey to restart without the meta http-equiv='refresh' argument as it's not part of the base html header.

There might be behavior issues because I'm using c# mvc as the back end. A sample I got here: https://github.com/surveyjs/surveyjs-aspnet-mvc

**Comment by tsv2013** [comment]
If understand you right, you want to show "Thank you" page and in a couple seconds start survey again with keep entered data.
I've created a sample for you - https://plnkr.co/edit/FIk71vKz7avJqAUDyWgZ?p=preview
Does it fit your needs? Or do I miss something?

**Comment by IAmSequestered** [comment]
I think you're my newest hero. I'll put it in my code and see if it works.
