### ISSUE TITLE
showNavigationButtons not working based on radio group question choice

### ISSUE THREAD

**Issue by bjdani** [surveyjs/surveyjs#508]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
I'm wanting to turn off the Complete button on a survey if the user chooses a "No" answer to a radio group question which means they do not need to continue filling it out.
I'm checking the radio group question's answer via onValueChanged
The current behaviour is that if the user chooses No, the Complete button continues to be displayed when it shouldn't be.

### What is the expected behavior?
If the user chooses "No" to the radio group question it should hide the "Complete" button straight away.

### How would you reproduce the current behavior (if this is a bug)?
See this Plunker demo http://plnkr.co/edit/73E72SUGXaTHn89cKk27?p=preview

Steps to replicate the issue:
1. Choose "No" for first question
2. The HTML message is then displayed but Complete button is still displayed (incorrect behaviour).
3. Then go back and choose "Yes" for the first question, then choose "No" for the first question again.
4. The HTML message is then displayed again. This time the Complete button is not displayed.

#### Provide the test code and the tested page URL (if applicable)
http://plnkr.co/edit/73E72SUGXaTHn89cKk27?p=preview

### Specify your
* browser: Chrome
* browser version: 59.0.3071.115 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.12.19

**Comment by dmitrykurmanov** [comment]
@bjdani, Hello! Thanks for your interest, could you please try to add `survey.render();` into your  `surveyQuestionValueChanged` handler?

here an example: http://plnkr.co/edit/w2WAJXq3M3HOlZWLYZiq?p=preview

**Comment by andrewtelnov** [comment]
@bjdani I would recommend to call survey.doComplete() method to complete the survey: http://surveyjs.org/docs/api_surveymodel.html#doComplete

Thank you,
Andrew

**Comment by bjdani** [comment]
Thanks to you both. I'll roll with the `survey.render();` which solves it.
