### ISSUE TITLE
Using "Survey.JsonObject.metaData.addProperty" in matrix

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#510]
Hi,

there is a possibility to use a code similar to this

Survey.JsonObject.metaData.addProperty("text", {name: "renderAs", default: "standard", choices: ["standard", "modify"]});

for add a property in a matrixdynamic or matrixdropdown cell?

Thanks

**Comment by tsv2013** [comment]
I think yes. It should work. Similar task was discussed in the https://github.com/surveyjs/surveyjs/issues/384#issuecomment-303948715 thread. As far as I remeber I added code to eliminate `onMatrixCellCreated` event subscription.

**Comment by care46** [comment]
@tsv2013 wooow works!!! thanks!!
