### ISSUE TITLE
Make matrix questions mandatory (ie via isRequired)

### ISSUE THREAD

**Issue by mrmayfield** [surveyjs/surveyjs#512]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
When I mark a matrix as isRequired, I can go through without filling out all the options

### What is the expected behavior?
Hopefully, I can't go to the next page until all questions are answered correctly

### How would you reproduce the current behavior (if this is a bug)?
Make a matrix as isRequired and then click to the next page before they're all filled

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

Is there a way to do this? Couldn't necessarily find anything in the documentation, I want the matrix questions to have to be answered before the user can go to the next page, the screenshot should be illustrative of what I'm trying to accomplish. 
<img width="1406" alt="screen shot 2017-07-22 at 7 54 13 pm" src="https://user-images.githubusercontent.com/7200471/28495344-90cd2418-6f17-11e7-9b74-8b407035f9eb.png">

**Comment by andrewtelnov** [comment]
@mrmayfield Are you talking about [this question type ](http://surveyjs.org/examples/jquery/questiontype-matrix/)?

Thank you,
Andrew

**Comment by mrmayfield** [comment]
Yes that's correct, thanks @andrewtelnov

**Comment by andrewtelnov** [comment]
@mrmayfield We will have to add a new property to handle this scenario. I would agree it should be quite common. I do not want to change the behavior of the current isRequired property, since it will be a break change. isRequired raise an error if the question answer is empty.

I will try to implement it on this week.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@mrmayfield Sorry, that I did not come back early. I have forget to write a message here.
There is already an option matrix.isAllRowRequired boolean, false by default.

Thank you,
Andrew

**Comment by mrmayfield** [comment]
Fantastic thanks a lot!

**Comment by Lynn42** [comment]
I noticed that the matrix.isAllRowRequired and the requiredErrorText don't work together as you might expect. 
You would expect requiredErrorText, if specified, to overwrite the standard error message, just like it does combined with isRequired. However, with matrix.isAllRowRequired the standard text is shown when not all rows are filled, not the text specified in requiredErrorText. Is this something that can be added?

**Comment by andrewtelnov** [comment]
@Lynn42 It is an another error type. You may change it as the following:
Survey.surveyStrings.requiredInAllRowsError = "Your error text";
The default text is "Please answer questions in all rows.", if you are using the default, "en", locale.

Thank you,
Andrew
