### ISSUE TITLE
Logic

### ISSUE THREAD

**Issue by Hafees89** [surveyjs/surveyjs#513]
your_code_here

	{ title: "How did we do today?", 
		questions: [
		{ 
			type: "dropdown", isRequired: true, name: "choosepicture", renderAs: "imagepicker", title: "People satisfaction degree!", 
			choices: [
						  {value: "Awesome", text: "./img/1.png"},
						  {value: "Good", text: "./img/2.png"},
						  {value: "NotGreat", text: "./img/3.png"},
						  {value: "Awful", text: "./img/4.png"}
					]
		}
	]},

Example I have 4 survey question. It is possible if I click Awesome it will directed to end page "Thank you for feedback etc etc" but when you click on value Good-Awful it will directly to next page which is my questionnaire. 

Thank you.

**Comment by tsv2013** [comment]
You can use "Complete Trigger" to accomplish your task. Please check [corresponding example](http://surveyjs.org/examples/jquery/trigger-complete/).

**Comment by Hafees89** [comment]
Thank you @tsv2013, this is what I'm looking for.
