### ISSUE TITLE
Matrix- "isRequired" not working for all sub-question

### ISSUE THREAD

**Issue by nadialo** [surveyjs/surveyjs#514]
[Question] Is it possible to applied "isRequired" to all rows in the matrix? The current behavior is that the error message only prompts out when I have answer no question in the matrix. If I have answer any of the question, the error message would not prompt out. 
What should I do if I want to mark all rows of the matrix as mandatory question? Thanks! 

* browser: Chrome, IE
* browser version: Chrome Version 59.0.3071.115; IE 11
* surveyjs platform: jquery
* surveyjs version: 0.12.20

**Comment by tsv2013** [comment]
I'd use valitation event as shown in [this example](http://surveyjs.org/examples/jquery/validators-event/). I've created a [plunk](http://plnkr.co/edit/ekET2zK0W3SpJ7NPflAI?p=preview) with the following code responsible for matrix question validation checking all rows are answered:

```
    function surveyValidateQuestion(s, options) {
        if (options.name === 'Quality') {
            var question = s.getQuestionByName("Quality");
            if(!question.rows.every(function(row) { return (options.value || {})[row.itemValue] !== undefined; })) {
                options.error = "All rows should be answered.";
            }
        }
    }

    $("#surveyElement").Survey({
        model: model,
        onValidateQuestion: surveyValidateQuestion
    });
```

**Comment by andrewtelnov** [comment]
@nadialo If you are talking about Matrix question with radio groups, then we will add a new property to handle this scenario without writing the code: https://github.com/surveyjs/surveyjs/issues/512
If you are taking about matrix dynamic/dropdown, then simple set isRequired to column(s) and all rows become required.

Thank you,
Andrew

**Comment by nadialo** [comment]
@andrewtelnov yes, #512 is exactly what I need. Will it be implemented in the near future? or else, I can implement the work around first. 

Thanks a lot!!

**Comment by andrewtelnov** [comment]
@nadialo There is already an option matrix.isAllRowRequired boolean, false by default.

Thank you,
Andrew

**Comment by vandrieu** [comment]
@andrewtelnov Works great, just one inconvenient:
`isRequired` has a `requiredErrorText` that allows to change the error text.
But `isAllRowRequired` doesn't have a similar customization option, we can't set something other than "Please answer questions in all rows".
