### ISSUE TITLE
SurveyJs in display only mode

### ISSUE THREAD

**Issue by xiuzhen1103** [surveyjs/surveyjs#517]
### Are you requesting a feature, reporting a bug or ask a question?
Requesting a feature, or ask a question

### What is the current behavior?
When it is in display mode, it looks exactly same as edit mode, the only difference is textarea is disabled
This is currently behaviour on the page: http://surveyjs.org/examples/jquery/survey-displaymode/

### What is the expected behavior?

would there be there any chance that you could provide example of disable mode not with disabled textbox/radio group, please? but it is a div tag for example as following: 
Question on the left and answer in the right.
![image](https://user-images.githubusercontent.com/6764095/28535723-4f16ba34-709d-11e7-9b65-0cc83aac6918.png)

* surveyjs version: latest version

**Comment by tsv2013** [comment]
Hi, @xiuzhen1103 ! I've prepared a sample for you with "readonly" custom widget - [this plunk](http://plnkr.co/edit/EDpk1P01Zw9i6RCBfAXK?p=preview). This widget just puts sttingified question's value in a div. Does it fit your needs? You can implement more elaborated output for questions of different kind.

**Comment by xiuzhen1103** [comment]
that is great, very helpful! is there any chance  that I could customize question itself not only answer, too?

**Comment by tsv2013** [comment]
@xiuzhen1103 I've updated the [plunk](http://plnkr.co/edit/EDpk1P01Zw9i6RCBfAXK?p=preview).
Here is the code to access question's label and change it's  style:
```
        var $label = $(el).parent().find('h5');
        $label.css({"display": "inline-block", "font-weight": "bold"});
```

**Comment by xiuzhen1103** [comment]
@tsv2013  thanks you for providing plunk for me, I found answer has quotation marks wrap on it. Would you have a look, please?
![image](https://user-images.githubusercontent.com/6764095/29405874-2dbdbeb2-8337-11e7-984e-a632bad4e873.png)

**Comment by xiuzhen1103** [comment]
in display mode, in there any chance that if I could show all the questions? it do not matter if question has been set as visible:false.

**Comment by tsv2013** [comment]
I've used the
`$el.text(JSON.stringify(question.value));`
code to get string representation of the question value. That's why quotation marks are present in the output. You can write your own values processing.

**Comment by tsv2013** [comment]
As far as I know there is no built it option to show all questions of the survey - no matter whether they are visible or not.
I think in this case you need to programmatically clear all visibility conditions for the survey you are using to display results. If you provide a sample JSON of such a survey (with hidden questions), I can try to do it in the plunker.

**Comment by xiuzhen1103** [comment]
@tsv2013  may I check each question type on before render it to the page?

**Comment by andrewtelnov** [comment]
@xiuzhen1103 question.getType() will return you the question type, like: "text", "dropdown" and so on.

Thank you,
Andrew

**Comment by xiuzhen1103** [comment]
@andrewtelnov great help, may I check if question type is comment, I would like to have textarea box with comment value inside and disabled, is this possible?

**Comment by andrewtelnov** [comment]
question.getType() should return "comment" for QuestionComment

**Comment by xiuzhen1103** [comment]
may I do this?  
let stringifyAnswer = JSON.stringify(question.value);
$el.contents("<textarea type='text' value=" +  JSON.parse(stringifyAnswer) + "></textarea>");

error message says Uncaught Error: Syntax error, unrecognized expression: <textarea type='text' value='cccccccccccc'></textarea>
