### ISSUE TITLE
problem with VisibleIf condition where question is empty

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#518]
Hi,

if i have a text question and a second question that i want to show only if first question is not empty, how i have to set "visibleIf" condition?

I have try with {question1} != '', {question1} != 'undefined', {question1} != null, {question1} != 'null', {question1} != 'undefined'

but the second question is always shown if first question is empty

Thanks

**Comment by tsv2013** [comment]
@care46 It looks like a bug for me. We'll fix it.

**Comment by Grimmer20** [comment]
@tsv2013 Thank you. This is also an issue for me currently too. 

I need conditional logic where if a user provides a value in {question1} then make visible {question2}

**Comment by andrewtelnov** [comment]
@care46 @Grimmer20 "{question1} empty" should work.

Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov  YESSSS!!! perfect!

thank you!

**Comment by tsv2013** [comment]
I've added support for `undefined` literal.
