### ISSUE TITLE
Move to next page with required fields empty

### ISSUE THREAD

**Issue by Grimmer20** [surveyjs/surveyjs#519]
### Are you requesting a feature, reporting a bug or ask a question?
Requesting a feature. Possibly a question if solution exists.

### What is the current behavior?
You must complete all required fields before moving to next page. If this is already possible please share details.

### What is the expected behavior?
We are using surveyJS for credit applications in an accounting application. In order to complete the application the user may need to get information from different co-workers in their company such as "monthly sales" from the Sales Department and "banking information" from the Finance department.

Allowing users to navigate through pages while not completing all required fields will allow them to understand what is required without losing the aesthetics and user experience of having different pages.

Of course keep validation for all required fields to be complete in order to submit/complete.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version: Current

**Comment by andrewtelnov** [comment]
@Grimmer20 If an user may submit a survey/page without require question, maybe just make it non required at the current moment?
Because the only reason to have the require question is to prevent an end-user from submitting information without answering this question. Otherwise the question becomes non-required :-)

I mean maybe you may have several stages in your survey and on the first stage some questions are not required, but they will become required on later stage, after initial submit?

Thank you,
Andrew

**Comment by tsv2013** [comment]
@Grimmer20 You can perform custom validation using [onValidateQuestion](http://surveyjs.org/examples/jquery/validators-event/) event. Event handler can perform validation flexible, depending on some conditions.

**Comment by andrewtelnov** [comment]
No reply for a long time. I am closing the issue.

**Comment by mahmoud-said** [comment]
> @Grimmer20 If an user may submit a survey/page without require question, maybe just make it non required at the current moment?
> Because the only reason to have the require question is to prevent an end-user from submitting information without answering this question. Otherwise the question becomes non-required :-)
> 
> I mean maybe you may have several stages in your survey and on the first stage some questions are not required, but they will become required on later stage, after initial submit?
> 
> Thank you,
> Andrew

Yes Andrew, I have the same problem ,
on the first stage some questions are not required, but they will become required on later stage.

**Comment by andrewtelnov** [comment]
@mahmoud-said You may use the following code wiht the latest version (1.1.20)
```survey.checkErrorsMode = "onComplete";```
or question.requiredIf property where you put a boolean expression. Based on this expression the question becomes required or not requried.

Thank you,
Andrew
