### ISSUE TITLE
Support for autocomplete?

### ISSUE THREAD

**Issue by willgdjones** [surveyjs/surveyjs#521]
Hi everyone!
### Are you requesting a feature, reporting a bug or ask a question?

This is most likely a feature request.

### What is the current behaviour?

I would like to add autocompletion to the input fields generated by survey.js. Currently, when I use 
jQuery typeahead on an input field which has been given an id by survey.js, e.g:

<img width="413" alt="screen shot 2017-07-25 at 20 30 34" src="https://user-images.githubusercontent.com/1719848/28587658-39c5f4f2-7178-11e7-981f-43f82e31633f.png">

When I add the necessary and javascript:
```
    $(document).ready(function(){
        $('#sq_104i').typeahead({
        source: ["item 1","item 2","item 3"]
    });
```
Nothing occurs.
### What is the expected behaviour?
What I would expect, is for items to appear in a dropdown menu, like so.

<img width="169" alt="screen shot 2017-07-25 at 20 34 31" src="https://user-images.githubusercontent.com/1719848/28587809-b7eb98e6-7178-11e7-8d1e-86e557167965.png">

I have tested a separate input field on the same page, with the same id, and the behavious is as I would expect. The problem seems to come with input fields generated by survey.js.

### How would you reproduce the current behaviour (if this is a bug)?

By the above steps.

#### Provide the test code and the tested page URL (if applicable)
n/a

### Specify your

* browser: Chrome
* browser version: Version 59.0.3071.115 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.12.3

Thanks for your help.

**Comment by dmitrykurmanov** [comment]
@willgdjones, hello! Sorry for late responce. We will create an example of customWidget with typeahead. If you have some another problems like "loading order" please create a new issue. Thanks for your interest!

**Comment by willgdjones** [comment]
No problem @dmitrykurmanov! This isn't a priority feature, just a nice to have :).

Thanks for getting back to me, looking forward to seeing your example.

**Comment by dmitrykurmanov** [comment]
@willgdjones and i forgot to tell that we already have some examples but without typehead.

devextreme tagbox: http://surveyjs.org/examples/jquery/custom-widget-tagbox/
select2: http://surveyjs.org/examples/jquery/custom-widget-select2/
select2 tagbox: http://surveyjs.org/examples/jquery/custom-widget-select2-tagbox/

could you check it please? may be someone is ok for you.

**Comment by andrewtelnov** [comment]
@willgdjones Here is another custom widget that may help you: https://surveyjs.io/Examples/Library/?id=custom-widget-autocomplete

Thank you,
Andrew
