### ISSUE TITLE
ColCount bug

### ISSUE THREAD

**Issue by willgdjones** [surveyjs/surveyjs#522]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug

### What is the current behavior?

Specifying colCount should change the number of columns used to display a long list of items. However, in my current setup setting colCount to any value gives the same response of a single linear list of my elements.

### What is the expected behavior?

I expect the number of columns to change.

### How would you reproduce the current behavior (if this is a bug)?

Hard to exactly reproduce, but it is irrelevant of my input data. The other js libraries that I use in the order that they appear are:
```
<script src="/static/inspinia/js/jquery-3.1.1.min.js"></script>
<script src="/static/inspinia/js/bootstrap.min.js"></script>
<script src="/static/inspinia/js/plugins/metisMenu/jquery.metisMenu.js"></script>
<script src="/static/inspinia/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

<!-- Custom and plugin javascript -->
<script src="/static/inspinia/js/inspinia.js"></script>
<script src="/static/inspinia/js/plugins/pace/pace.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/10.0.0/nouislider.js"></script>
<script type="text/javascript" src="https://surveyjs.azureedge.net/0.12.3/survey.jquery.min.js"></script>
```
#### Provide the test code and the tested page URL (if applicable)

n/a

### Specify your

* browser: Chrome
* browser version: Version 59.0.3071.115 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.12.3

**Comment by tsv2013** [comment]
@willgdjones Could you please specify the question type, in which the `colCount` property is not working? I've just checked [`radiogroup`](http://surveyjs.org/examples/jquery/questiontype-radiogroup/) and [`checkbox`](http://surveyjs.org/examples/jquery/questiontype-checkbox/) questions - colCount works fine for me. Or have I missed something?

**Comment by cguzzo** [comment]
Hi @tsv2013 ,

Answering for @willgdjones as I am working on the same project. The question type is checkbox. See code below:

`            {
                    type: "checkbox",
                    name: "Disease",
                    title: "Which of the following conditions have you been diagnosed with?",
                    visibleIf: "{haveHistory}='Yes'",
                    isRequired: true,
                    ColCount: 2,
                    choices:[ "Cancer","Heart disease", "Pulmonary/Lung disease", "Diabetes", "Immune disorders", "Neurological disease", "Psychiatric disorder", "Digestive disease", "Endocrine disease", "Gynaecological conditions", "Genetic condition", "Other"],
                },`

The choices are still displayed in one single column no matter what value we put after ColCount. Are we missing anything? 

Thanks for your help

**Comment by willgdjones** [comment]
@tsv2013 I will update to version 0.12.20 and see if that fixes.

**Comment by tsv2013** [comment]
@cguzzo Thank you for the provided JSON. I've checked it. You should write `colCount: 2` instead of `ColCount: 2`.

**Comment by cguzzo** [comment]
Thanks @tsv2013 - updating the new version worked thanks!
