### ISSUE TITLE
Website header does not make sense.

### ISSUE THREAD

**Issue by willgdjones** [surveyjs/surveyjs#523]
Not really a bug - but just wanted to let you know that this doesn't really make any sense. It appears on https://dxsurvey.com/.

<img width="432" alt="screen shot 2017-07-25 at 20 51 22" src="https://user-images.githubusercontent.com/1719848/28588581-4d3f7924-717b-11e7-9be7-8ca059b226c7.png">

I think you mean:

"At the moment, the service is completely free. It will continue to be free until the load/number of requests grows significantly."

**Comment by tsv2013** [comment]
@willgdjones Thank you! I've updates the site.
