### ISSUE TITLE
how to show questions based on users answers ?

### ISSUE THREAD

**Issue by hackertron** [surveyjs/surveyjs#526]
### Are you requesting a feature, reporting a bug or ask a question?

how can i show questions based on users answers ?

**Comment by andrewtelnov** [comment]
@hackertron Do you mean [this functionality](http://surveyjs.org/examples/jquery/condition-kids/)

Thank you,
Andrew

**Comment by hackertron** [comment]
Yes exactly this !! . Thank you !!
