### ISSUE TITLE
Mapping other choice to custom name field

### ISSUE THREAD

**Issue by indran** [surveyjs/surveyjs#527]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

Regarding the radio group question type - for other choice you provide:
1. hasOther = true
2. otherText = 'If other please describe why.'
3. storeOthersAsComment = false - store as the name field 
4. commentPrefix = "-prefix" - change prefix (from 'name-Comment' to 'name-prefix') ?

### What is the expected behavior?

{
        type: "radiogroup",
	name: "eatBreakfast",
	title: "Do you eat breakfast?",
	isRequired: true,
	choices: ["Yes", "No"],
	hasOther: true,
	otherText: 'If other please describe why.',
	colCount: 0
}

Using the question above, depending on the options I use, when completing the survey my data will be either be: {"eatBreakfast","something"} or {"eatBreakfast":"other", "eatBreakfast-Comment":"something"}

Is there a way to set the name of the what the other comment text is mapped to instead, for example:

{"eatBreakfast":"other", "eatingOtherField":"... other reason..."} ?

{
        type: "radiogroup",
	name: "eatBreakfast",
	choices: ["Yes", "No"],
	hasOther: true,
	otherText: 'If other please describe why.',
	otherName: 'eatingOtherField' <--- maybe something like this??
}

**Comment by andrewtelnov** [comment]
@indran The current solution is to change the survey.data on survey.onComplete event.

There were at least couple issues where value mapping would help. At the current moment question name and value name are always the same.
However, there are scenarios when you may have two different question with different properties map on the same value name.
I have updated our TODO item about value mapping.

Fortunately, you may solve your issue by couple lines of code in survey.onComplete event:
```
if(survey.data["questionName" + survey.commentPrefix]) {
  survey.data["newOtherName"]  = survey.data["questionName" + survey.commentPrefix];
  delete survey.data["questionName" + survey.commentPrefix];
}
```
Thank you,
Andrew

**Comment by indran** [comment]
@andrewtelnov Thank you for replying so quick, very cool of you!

While the current solution is quite useful this could become tricky depending on the size of the survey and number of question with "other choice" available. Additionally what about when you are loading existing data:

 {"email": "jon.snow@nightwatch.org", "eatBreakfast": "0", "eatBreakfast-Comment": "something"}

You would have to create "other choice" name field with prefix, so basically the reverse of the onComplete solution correct?

**Comment by indran** [comment]
I was experimenting with Vue and Survey JS, unfortunately I am still learning Vue so apologies if there is some weird looking code! 

Here is a plunk of something which sort-of does what I was looking to do:
https://plnkr.co/edit/YOeOzgbcgQK8C9pZRdwi?p=preview

**Comment by andrewtelnov** [comment]
@indran I would write the following code:

```
//your mapping, question name as a key and  desired other name as a value
var changeOtherFields = {
  "satisfaction" : "otherSatisfaction"
}

survey.onComplete.add(function(result) {
  for(var key in changeOtherFields) {
    var otherName = key + result.commentPrefix;
    if(result.data[otherName]) {
      result.data[changeOtherFields[key]] = result.data[otherName];
      delete result.data[otherName];
    }
  }
});
```
If you want to set the saved data to the survey (survey.data = yourData), you should do reverse first.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
No reply for a long time. I am closing the issue.
