### ISSUE TITLE
Visible if function for columns in matrix 

### ISSUE THREAD

**Issue by cguzzo** [surveyjs/surveyjs#529]
### Are you requesting a feature, reporting a bug or ask a question?

Asking a question 
I am trying to create a matrix survey that includes different relatives as rows and different questions regarding these relatives as column (See model below). I would like column C's scroll down menu to change on the basis of what has been answer in question B. For example, if the user answers Mother - Suffered condition = yes,   Which condition = cancer -> I would like the precise type scroll down menu to list several types of cancers but if Which condition = Heart disease, then i'd like for precise type to scroll down several types of heart disease. 

I've tried to implement the visible if condition but doesn't seem to be working. Anything else I can do?

                            Have suffered a condition?       Which condition?        Precise type   

Mother                      Yes/No                                      Scroll down                 Scroll down

Father                       Yes/No                                       Scroll down                 Scroll down 
 

### How would you reproduce the current behavior (if this is a bug)?

N/A

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@cguzzo Do you use the dev version? column.visibleIf is not released yet.
Probably this functionality will be interested to you as well: https://github.com/surveyjs/surveyjs/issues/525

Thank you,
Andrew

**Comment by cguzzo** [comment]
column.visibleIf sounds like what i need! Where can i find the dev version?

**Comment by andrewtelnov** [comment]
@cguzzo You may use access it [via CDN](https://github.com/surveyjs/builds). For dev version: https://surveyjs.azureedge.net/dev/{ filename }  
For example: `<script src="https://surveyjs.azureedge.net/dev/survey.jquery.js"></script>`

Here is [the demo](https://plnkr.co/edit/SYJBdx7AkjqOnXXrqTmV?p=preview)

Thank you,
Andrew
