### ISSUE TITLE
onComplete function check failed or success

### ISSUE THREAD

**Issue by xiuzhen1103** [surveyjs/surveyjs#530]
### Are you requesting a feature, reporting a bug or ask a question?
ask a question

### What is the current behavior? and ### What is the expected behavior?
At moment if survey completed add customized message, what if submit failed, how to check if is not successful by api call? how to insert it and check?   

```
survey.onComplete.add(function(result) {
	document.querySelector('#surveyResult').innerHTML = "result: " + JSON.stringify(result.data);
});

```

**Comment by andrewtelnov** [comment]
@xiuzhen1103 Do you store in your own database?

Thank you,
Andrew

**Comment by xiuzhen1103** [comment]
Yes store in my own database.

**Comment by andrewtelnov** [comment]
@xiuzhen1103 We have added options parameter into onComplete event. Here is the demo: https://plnkr.co/edit/75nXj6?p=preview

Thank you,
Andrew
