### ISSUE TITLE
$el.find(...).iCheck is not a function

### ISSUE THREAD

**Issue by xiuzhen1103** [surveyjs/surveyjs#531]
### Are you requesting a feature, reporting a bug or ask a question?
reporting a bug or asking a question

### What is the current behavior?
when using icheck plugin should update radiogroup UI

### What is the expected behavior?
error message on console is following, however I have installed and imported icheck from react, why is error message still appears as following:
$el.find(...).iCheck is not a function

```
import { iCheck } from 'icheck';
### How would you reproduce the current behavior (if this is a bug)?
 var radioGroupWidget = {
 name: "icheck",
    isFit : function(question) { return question["renderAs"] === 'icheck'; },
    isDefaultRender: true,
    afterRender: function(question, el) {
        var $el = $(el);
        var select = function() {
          $el.find("input[value=" + question.value + "]").iCheck('check');
        }
        $el.find('input').iCheck({
          checkboxClass: 'iradio_square-blue',
          radioClass: 'iradio_square-blue'
        });
        $el.find('input').on('ifChecked', function(event){
          question.value = event.target.value;
        });
        question.valueChangedCallback = select;
        select();
    },
    willUnmount: function(question, el) {
        var $el = $(el);
        $el.find('input').iCheck('destroy');
    }
 }
CustomWidgetCollection.Instance.addCustomWidget(radioGroupWidget);
```

### Specify your

* browser: latest version
* browser version:  chrome
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: latest version

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103, hello! Could you please provide an example on plnkr or any other sandboxes? Here is a good article about it https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff. Thank you!

**Comment by andrewtelnov** [comment]
No reply for a long time. I am closing the issue.
