### ISSUE TITLE
Documentations of 'VisibleIf'?

### ISSUE THREAD

**Issue by haoxi911** [surveyjs/surveyjs#532]
Hello all,

Can anyone please tell me where can we find the full documentations of syntax like `VisibleIf`? I am currently **guessing** these syntaxes (though I have got all I needed..)

For example, I want to show question B only when a specific option was selected in question A (the question A is a checkbox question, which has multiple options and can be multi-selected)

I used `VisibleIf: "{questionA} contains 'optionA'"` and it seems work well, but I can't find any documents that list these syntaxes: `contains` `has` etc.

Thanks!

**Comment by andrewtelnov** [comment]
@haoxi911 Here is the doc: http://surveyjs.org/docs/QuestionBase/visibleIf.html

You may find more information in the unit tests: https://github.com/surveyjs/surveyjs/blob/master/tests/conditionstests.ts

Thank you,
Andrew

**Comment by haoxi911** [comment]
Thank you @andrewtelnov!
