### ISSUE TITLE
warn message on console on Image picker used

### ISSUE THREAD

**Issue by xiuzhen1103** [surveyjs/surveyjs#533]
### Are you requesting a feature, reporting a bug or ask a question?

bug or ask question

### What is the current behavior?

I have used 20 of image picker in my project, warn message on console for Image picker appeared 20 times.

### What is the expected behavior?
no warn message

### How would you reproduce the current behavior (if this is a bug)?
http://surveyjs.org/examples/react/custom-widget-image-picker/
Open console, will see warn message
react-dom.js:18371 Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:  http://surveyjs.org/examples/react/custom-widget-image-picker/

Test code
react-dom.js:18371 Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>
```

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103, thank you, we'll fix it.

**Comment by xiuzhen1103** [comment]
Thanks Dimitry, would you let me know when it's done, please? need it for this sprint.

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103 it will be in the next release. I've updated dev build and you may use it as workaround: 

` <script src="https://surveyjs.azureedge.net/dev/survey.jquery.js"></script>`

**Comment by xiuzhen1103** [comment]
@dmitrykurmanov may I ask when is next release, please?

**Comment by dmitrykurmanov** [comment]
@xiuzhen1103 we've released 0.12.21 3 days ago, so the fix is there.
