### ISSUE TITLE
add new value into survey.state: completedbefore

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#534]
"completedbefore" state means that the survey has been already completed by the user.
At the current moment this functionality is working if you are using dxsurvey.com service.
On creating the survey model you have to pass the surveyId and clientId or call loadSurveyFromService(surveyId: string, clientId: string = null) method

If clientId is not null, the library will check if there is a record with the completed state. If there is, the survey on loading from the server will go into completedbefore state and completedBeforeHtml will be shown. By default:  "Our records show that you have already completed this survey."

**Comment by andrewtelnov** [comment]
Let us know if you need the similar functionality without binding to dxsurvey.com service.

Thank you,
Andrew

**Comment by jas2288** [comment]
> Let us know if you need the similar functionality without binding to dxsurvey.com service.
> 
> Thank you,
> Andrew

Hi, having this functionality would really help. Thanks.

**Comment by PeterHassaballah** [comment]
@singhnjas check completedBeforeHtml property
