### ISSUE TITLE
JQuery DatePicker and required field

### ISSUE THREAD

**Issue by luca76** [surveyjs/surveyjs#535]
When I'm using JQuery DatePicker for a date field and I make that field as required, when I click on "Next", Surveyjs warns that that required field isn't filled.

To reproduce this:

1) go to http://surveyjs.org/examples/knockout/custom-widget-datepicker/
2) click on "Edit in Plunker"
3) replace the line 

`{name:"date", type:"text", inputType:"date", title: "Your favorite date:", dateFormat: "mm/dd/yy"}`
with 
`{name:"date", type:"text", inputType:"date", title: "Your favorite date:", dateFormat: "mm/dd/yy", isRequired: true}`

4) Click on next...

**Comment by andrewtelnov** [comment]
@luca76 By default the date picker shows the current date.  You may add a code to clear the date picker after it creating or set question  value to the current date. 
For example you may add the following line
```
        question.valueChangedCallback();
        question.value = new Date(); // <---- a new line
},
```

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
https://plnkr.co/edit/wrzNfGBUgoEiFIaWHNCo?p=preview

**Comment by luca76** [comment]
Great! This fixed my problem.

Can you include it in the official example? It's a very useful fix.

**Comment by andrewtelnov** [comment]
@dmitrykurmanov Let's modify the example.

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
@andrewtelnov done
