### ISSUE TITLE
Custom Widget Questions not retaining values on page navigation

### ISSUE THREAD

**Issue by eddie1459** [surveyjs/surveyjs#536]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
Fill out a survey question created with custom widget logic and navigate to next page and back and value does not show up in the input.

### What is the expected behavior?
Value would be in the input

### How would you reproduce the current behavior (if this is a bug)?
Enter value in input, click next, then click previous.

#### Provide the test code and the tested page URL (if applicable)

`{ type: "text", name: "avgRecvSugarContent", isRequired: true, inputType: "number", title: "What was your average recoverable sugar content in 2017?", renderAs: "percent-input-addon", validators: [{ type: "regex", regex: "^100$|^[123456789][0-9]$|^[0-9]$", text: "Please enter a percentage from 1 to 100" }]},`

`var percentInputWidget = {
    name: "percent-input-addon",
    htmlTemplate: "<div class='input-group'><input type='number' class='form-control' aria-describedby='basic-addon2'><span class='input-group-addon'>%</span></div>",
    isFit : function(question) { return question["renderAs"] === 'percent-input-addon'; },
    afterRender: function(question, el) {
        var $el = $(el);
        $($el.find('input')).on('blur', function(event){
          question.value = event.target.value;
        });
    }
}`

### Specify your

* browser: Chrome
* browser version: 59
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.12.20

**Comment by eddie1459** [comment]
Some more additional info:  I noticed when I watched the onAfterRenderQuestion event that each of my widget questions do have the data still intact in the SurveyModel.data object.  My only guess as to why the widget inputs are not populating is that I am loading the htmlTemplate incorrectly.

**Comment by eddie1459** [comment]
I found a workaround for now that should get me through.  In the onAfterRenderQuestion event I am simply using this line:  $("#" + options.question.name).val(options.question.value);
In my template I am giving my input an id that matches the question name and that allows me to populate the questions on navigation.

**Comment by eddie1459** [comment]
Here is the modified logic I have in the onAfterRenderQuestion that populates single and multitext input questions.

`if (options.question.itemsValues != undefined) {
            for (var multiIndex = 0; multiIndex < options.question.itemsValues.length; multiIndex++) {
                $("#" + options.question.itemsValues[multiIndex].name).val(options.question.itemsValues[multiIndex].value);
            }
        } else {
            $("#" + options.question.name).val(options.question.value);    
        }

**Comment by dmitrykurmanov** [comment]
@eddie1459, hello! Thanks for your interest. I've tried to reproduce this behaviour but without success. Here an example based on your code: https://plnkr.co/edit/BdvAekaG7ADfP9SyodQ0?p=preview. If I click _next_ and _prev_ I have value in the input. Could you please modify my example for reproduce the problem?

PS we will do big refactoring of custom widgets

**Comment by eddie1459** [comment]
Thank you for responding so quickly to me, I appreciate it!!  I see that your plunker code does indeed work with the code I pasted in here.  The only difference I am seeing is that in my code the % addon is showing and in yours it is not.  I have compared versions of bootstrap, jquery and the survey.js libs and they all match.  I can't for the life of me figure out why your code isn't showing the addon.

**Comment by dmitrykurmanov** [comment]
@eddie1459, could you please share your version of code?

**Comment by eddie1459** [comment]
Ok, I mocked up something that should show what is going on:  https://jsfiddle.net/eddie_d_2000/j1yr8jmd/

**Comment by dmitrykurmanov** [comment]
@eddie1459 thanks, now I understand the problem. I've fixed your example:

same name of questions (as in your example): https://jsfiddle.net/94jh58tq/
different name of questions: https://jsfiddle.net/6kffdh0f/

could you please check these examples?

PS: for more technical behaviour details please see: https://github.com/surveyjs/surveyjs/issues/405

PPS: we are thinking on new custom widgets implementation it will be much easier for surveyjs users

**Comment by eddie1459** [comment]
Ok, I see that your example is working correctly.  From what I can tell you are using the willUnmount function and I wasn't, is that the difference?

**Comment by dmitrykurmanov** [comment]
@eddie1459, yes I've added `willUnmount`. First of all I've fixed your jquery selector from `input` to '#id' (because of button "next" was selected sometimes :) ) And I've added input.val(question.value); in the end of `afterRender`, it needs for _two-way binding_  between widget and surveyjs core question.

**Comment by eddie1459** [comment]
Oh wow, sorry I didn't catch that, thank you for your help!!

**Comment by dmitrykurmanov** [comment]
@eddie1459 please feel free to reopen the issue or ask additional questions
