### ISSUE TITLE
InputType date (with no plugins) has no effect in Firefox 54

### ISSUE THREAD

**Issue by luca76** [surveyjs/surveyjs#537]
Hi, when I use a question with inputype set to date, it has no effect in checking valid dates on Firefox.
It seems like a inputtype text...

**Comment by dmitrykurmanov** [comment]
@luca76 hello! Could you create a plnkr example please?

**Comment by andrewtelnov** [comment]
@luca76 Unfortunately Firefox doesn't support input type property: https://stackoverflow.com/questions/22983013/how-to-get-html-5-input-type-date-working-in-firefox-and-or-ie-10
https://stackoverflow.com/questions/30503195/html-5-input-type-date-not-working-in-firefox

I am not sure that it makes sense to do something on the library level. We will discuss it.

Thank you,
Andrew
