### ISSUE TITLE
Move required * appears on the end of the question

### ISSUE THREAD

**Issue by xiuzhen1103** [surveyjs/surveyjs#539]
### Are you requesting a feature, reporting a bug or ask a question?

requesting feature or ask a question

### What is the current behavior?

required * appears on the left of the question

### What is the expected behavior?

Would there be any chance that if I could move * on the right of the question, please?  Also am able to style it to red color only for *? 

### How would you reproduce the current behavior (if this is a bug)?
http://surveyjs.org/examples/jquery/questiontype-text/

#### Provide the test code and the tested page URL (if applicable)
![image](https://user-images.githubusercontent.com/6764095/28925275-4c5de4a4-785c-11e7-8a3b-a05779e0cfb1.png)

Tested page URL: http://surveyjs.org/examples/jquery/questiontype-text/

**Comment by andrewtelnov** [comment]
@xiuzhen1103 Please use survey.questionTitleTemplate property:
`questionTitleTemplate : "{no}. {title} {require}"`
https://plnkr.co/edit/cABi9plYhJiadtpwfuIW?p=preview

Thank you,
Andrew

**Comment by xiuzhen1103** [comment]
thanks!

**Comment by andrewtelnov** [comment]
@xiuzhen1103 Sorry, I did not get you :( Could you explain it in more details?

**Comment by xiuzhen1103** [comment]
Hi Andrew,

Sorry not explain well in last post.

In survey option here you can find the method for requiredText method to customize required *
http://surveyjs.org/examples/jquery/survey-options/

I would to add span tag around it * for questionTitleTemplate
survey.requiredText = "<span>*</span>";

However its not allow me to to it

**Comment by xiuzhen1103** [comment]
Hi, another question, in surveyJs form, default format for question is h5, is there any chance that I can change h5 into a div tage, please? 

![image](https://user-images.githubusercontent.com/6764095/28929957-3eb87c6c-7869-11e7-8db6-31a825bf7fee.png)
http://surveyjs.org/examples/react/survey-processtext/

**Comment by andrewtelnov** [comment]
@xiuzhen1103 You have to use the markdown functionality. Here is the example: 
`requiredText: "<strong>(Required)</strong>"`
https://plnkr.co/edit/JJmu4lyluoMhnlc8aMdd?p=preview 

and for the second question, you may set the class you need to customize <h5> tag. What problem do you have with <h5> tag?

Thank you,
Andrew

**Comment by xiuzhen1103** [comment]
```
 model = new Model( json);	
 model.questionTitleTemplate = "{no} {title} {require}";
model.requiredText = "<strong>*</strong>"; 
```
Thanks Andrew, this is my code, but it appears on the page as 

![image](https://user-images.githubusercontent.com/6764095/28964044-1bc77650-7903-11e7-986b-45254e042252.png)

**Comment by xiuzhen1103** [comment]
Hi Andrew, this is what happened on the page, it is exactly html tag not the text

```
model = new Model( json);	
model.questionTitleTemplate = "{no} {title} {require}";
model.requiredText ="<span>test</span>"; 
```
![image](https://user-images.githubusercontent.com/6764095/28964829-69ac964a-7906-11e7-90dc-58c5c86d08aa.png)

**Comment by andrewtelnov** [comment]
@xiuzhen1103 Do you have this code on your page as in the plunker example?

```
var converter = new showdown.Converter();
survey.onTextMarkdown.add(function(survey, options){
    //convert the mardown text to html
    var str = converter.makeHtml(options.text);
    //remove root paragraphs <p></p>
    str = str.substring(3);
    str = str.substring(0, str.length - 4);
    //set html
    options.html = str;
});
```
Thank you,
Andrew

**Comment by xiuzhen1103** [comment]
showdown is not defined, which version and name of shutdown npm install

**Comment by andrewtelnov** [comment]
@xiuzhen1103 Here is the npm package: https://www.npmjs.com/package/showdown

Thank you,
Andrew

**Comment by xiuzhen1103** [comment]
thank you so much!
