### ISSUE TITLE
Spacing in survey questions

### ISSUE THREAD

**Issue by cguzzo** [surveyjs/surveyjs#540]
### Are you requesting a feature, reporting a bug or ask a question?

Ask a question

### What is the current behavior?

Survey question with several rows and two columns (radiogroup yes or no) - The yes column is very close to the rows and likewise the no column very close to the yes. How do I change the spacing? I would also like to have the "Complete" button lower (not stuck to the rows)  - Picture attached
<img width="384" alt="screen shot 2017-08-03 at 22 04 53" src="https://user-images.githubusercontent.com/30090592/28943809-09aefc4c-7898-11e7-9cbc-17833049fffe.png">
<img width="384" alt="screen shot 2017-08-03 at 22 04 53" src="https://user-images.githubusercontent.com/30090592/28943817-1171ac36-7898-11e7-9ef6-97ec6cda176d.png">

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
var MedicationUseJSON = {
    title: "Help us find out if your medications are right for you!",
    name: "medicationuse",
    pages: [
        {
            name: "page1",
            questions: [
              { type: "matrix", name: "medication", title: "Do you currently take any of the following medication?",
   columns: [{ value: "Yes" },
             { value: "No" }],
    rows: [{ value:"Cholesterol - statins (Zocor, Lipitor, Crestor)" },
           { value:"Blood pressure - Prinivil, Zestril, Norvasc" },
           { value:"Blood thinner - Plavix" },
           { value:"Thyroid - Levothyroxine (Synthroid)" },
           { value:"Antipsychotics - Abilify, Seroquel" },
           { value:"Antacids - Prilosec, Nexium"},
           { value:"Asthma - Ventolin"},
           { value:"Antidepressants - Prozac, Celexa, Lexapro"},
           { value:"Arthritis - Humira, Enbrel, Remicade"},
           { value:"Diabetes - Metformin(Glucophage), Actos"}]}

            ]
        }
    ]
}

var medicationuse = new Survey.Model(MedicationUseJSON);
medicationuse["name"] = "medicationuse"
$("#medicationuse").Survey({
    model:medicationuse,
    onComplete:sendDataToServer
});


```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@cguzzo Could you please check that survey.css is included into your page?
In the most examples we are using the bootstrap version, so you do not need to link survey.css file and use the bootstrap css.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
No reply for a long time. I am closing the issue.
