### ISSUE TITLE
survey-react fails at build

### ISSUE THREAD

**Issue by ndelacour** [surveyjs/surveyjs#541]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
Fails at build : 
ERROR in C:\Users\d217354\Documents\Visual Studio 2015\Projects\SafranSurvey\SafranSurvey.ux\node_modules\survey-react\survey.react.d.ts
(400,22): error TS2415: Class 'SurveyQuestionElementBase' incorrectly extends base class 'SurveyElementBase'.
  Property 'shouldComponentUpdate' is protected in type 'SurveyQuestionElementBase' but public in type 'SurveyElementBase'.
ERROR in C:\Users\d217354\Documents\Visual Studio 2015\Projects\SafranSurvey\SafranSurvey.ux\node_modules\survey-react\survey.react.d.ts
(432,22): error TS2415: Class 'SurveyQuestionCheckboxItem' incorrectly extends base class 'ReactSurveyElement'.
  Property 'shouldComponentUpdate' is protected in type 'SurveyQuestionCheckboxItem' but public in type 'ReactSurveyElement'.

### What is the expected behavior?
Build without errors

### How would you reproduce the current behavior (if this is a bug)?
Include library in react projet and build the react project

### Specify your
* browser: NA
* browser version: NA
* react
* surveyjs version: 0.12.20

(!) Changing the indicated properties in the .d.ts file towards public resolved the issue.

**Comment by dmitrykurmanov** [comment]
@ndelacour hello! Thanks for your proposal. It is strange but I can't reprocuse it in our [quickstart repo](https://github.com/surveyjs/surveyjs_react_quickstart) based on official **create-react-app**. But anyway `shouldComponentUpdate` is interface method, so it is public. I've changed our code and it will be public in next surveyjs version.
