### ISSUE TITLE
export {ReactQuestionFactory as QuestionFactory}

### ISSUE THREAD

**Issue by wastedUltimate** [surveyjs/surveyjs#543]
My team is using survey-react@0.12.18. Rather than use the custom-widget we are extending the survey classes directly.  For example we have extended the QuestionCheckboxModel as well as the SurveyQuestionCheckbox to create our own custom 'multiselect' type. We have ran into an issue trying to create a matrixdynamic that utilizes our multiselect.  We tracked the issue down to the fact that entries/react.ts does not export the base QuestionFactory class, instead it exports ReactQuestionFactory as QuestionFactory. This prevents us from registering our model to the appropriate creatorHash.  Your provided types get registered to both the ReactQuestionFactory as well as QuestionFactory. 

What we found is that an error is thrown in QuestionMatrixDropdownModelBase .createQuestionCore because question is null.  However if we change the exports such that QuestionFactory is the root QuestionFactory class there are no issues.

Is there a reason behind exporting ReactQuestionFactory as QuestionFactory

**Comment by andrewtelnov** [comment]
@wastedUltimate 
QuestionFactory is exported inside the model, platform independent part: https://github.com/surveyjs/surveyjs/blob/master/src/entries/chunks/model.ts
and then react export the model.ts file (the first line):
https://github.com/surveyjs/surveyjs/blob/master/src/entries/react.ts
react survey classes are actually wrappers around model survey classes. So yes, it requires to register a question in the model using QuestionFactory.  
Do you have an error by accessing Survey.QuestionFactory.Instance.registerQuestion method?

Thank you,
Andrew

**Comment by wastedUltimate** [comment]
The following are snippets of our two classes:

QuestionMultiselectModel
```
import { QuestionFactory, JsonObject, QuestionCheckboxBase, defaultBootstrapCss} from 'survey-react';

class QuestionMultiselectModel extends QuestionCheckboxBase {
// internal code
}

JsonObject.metaData.addClass('multiselect', [], function() {return new QuestionMultiselectModel('');}, 'checkboxbase');

QuestionFactory.Instance.registerQuestion('multiselect', 
  function(name) { 
    var q = new QuestionMultiselectModel(name); 
    q.choices = QuestionFactory.DefaultChoices;
    return q;
  });
```

SurveyQuestionMultiselect (the react wrapper)
```
import React from 'react';
import { SurveyQuestionElementBase, ReactQuestionFactory, SurveyQuestionCheckboxItem } from 'survey-react';

class SurveyQuestionMultiselect extends SurveyQuestionElementBase {
// internal code
}

ReactQuestionFactory.Instance.registerQuestion('multiselect', 
  function(props) { 
    return React.createElement(SurveyQuestionMultiselect, props);
  });
```

We do not have any errors during the initial loading. And questions that are of type multiselect function correctly.  We specifically have an error if we use multiselect as a 'cellType' in a 'matrixdynamic'.  This is because when we call QuestionFactory.Instance.registerQuestion in QuestionMultiselectModel it registers the question as part of the ReactQuestionFactory instance. 

Further testing found that the basic types ('text', 'checkbox', etc) have the base model registered to the QuestionFactory instance and the react wrapper classes registered separately in the ReactQuestionFactory instance.  So there are two separate creatorHashes.

You are correct that react.ts exports all of model.ts. However at the bottom of react.ts QuestionFactory is overwritten with the line 
```
export { ReactQuestionFactory as QuestionFactory} from "../react/reactquestionfactory";
```

We found that if we removed that line we were able to register the model correctly and load the matrixdynamic question without errors.

**Comment by andrewtelnov** [comment]
@wastedUltimate Yes, you are right. It is a bug. 
We had an example of creating new react question, however it just changes the rendering of the existing question in model. That is why we do not run into this problem. I will change the 
`export { ReactQuestionFactory as QuestionFactory} from "../react/reactquestionfactory";`
into
`export { ReactQuestionFactory} from "../react/reactquestionfactory";`
and change the code accordingly, to use ReactQuestionFactory singleton object.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@wastedUltimate We used ReactQuestionFactory singleton as QuestionFactory in one obsolete example, so the fix, removing the line should be absolutely save.

Thank you for bringing this to our attention.
Andrew
