### ISSUE TITLE
how to use doc generator

### ISSUE THREAD

**Issue by mohsen2014** [surveyjs/surveyjs#544]
### Are you requesting a feature, reporting a bug or ask a question?

ask a question

how to use doc generator ?
 
surveyjs version:
latest

**Comment by andrewtelnov** [comment]
@mohsen2014 doc generator has been developed for creating a JSON file that uses to show our documentation: http://surveyjs.org/docs/api_surveymodel.html 
I do not like any typescript doc creators and created my own.
Why do you need it? We may create a separate repo for it, so you may fork it if you need.

Thank you,
Andrew
