### ISSUE TITLE
Visibleif for "Other" option

### ISSUE THREAD

**Issue by nadialo** [surveyjs/surveyjs#547]
1a) Question1a
- Option1
- Option2
- Others

If I want question1b visible depends on the "Others" option (generated by hasOthers function), what should I input for the visibleif in question1b? 
I have tried "visibleif": "{Question1a}.isOtherSelected", but it seems like not in the right place.

 Thanks!

**Comment by andrewtelnov** [comment]
@nadialo This code should work
` "visibleif": "{Question1a} = 'other'" `

Thank you,
Andrew
