### ISSUE TITLE
icons in buttons

### ISSUE THREAD

**Issue by madceb** [surveyjs/surveyjs#550]
Is there a way of adding Icons to the Navigation and for Add/Remove buttons? I tried adding some fontAwesome icons with no success using the available properties. 
Example:
...
removeRowText: "&#xf014; Remove"
...
and classes fa fa-trash-o  (even if this one worked, it would be a little more complicated because is the same class for add and remove)

Thanks.

**Comment by andrewtelnov** [comment]
@madceb You may turn-off the default navigation: `survey.showNavigationButtons = false; `and create your own. Here is [the demo](http://surveyjs.org/examples/jquery/survey-customnavigation/)

Thank you,
Andrew

**Comment by madceb** [comment]
Thanks, that should be easy to add, but for the dynamic questions like the Add or Remove Buttons? is there something similar to disable the build in and add my own?

**Comment by andrewtelnov** [comment]
@madceb We do not have any easy way to implement it. Buttons do not support markdown feature yet :( http://surveyjs.org/examples/jquery/survey-markdown-radiogroup/
If we add markdown support for buttons would it work for you?
By the way, I have added this feature (add ability to render an icon/image in buttons) into our TODO list. I can give you any estimate time at the current moment. Is it urgent to you?

Thank you,
Andrew

**Comment by madceb** [comment]
Hello @andrewtelnov, no, it is not urgent, I was prototyping a form while using the Matrix the Remove Row button was to big that's why I tried to used a icon instead, the fontAwesome was just an example it can be anything that could add an icon and maybe a tooltip text in case you only have a icon in the button. When ever you could add it, it'll be great.
Regards.

**Comment by dmitrykurmanov** [comment]
We've added this functionality for maxtixdynamic questions. Please check the https://surveyjs.answerdesk.io/ticket/details/T1589

**Comment by madceb** [comment]
Awesome!!!!

**Comment by dmitrykurmanov** [comment]
@madceb please note, that we added it only for matrixdynamic. If it works ok we will think about using this approach in other places and in the Builder. Thanks

**Comment by Nawazsherif** [comment]
I would be happy if you add at least markdown support for the buttons.

**Comment by andrewtelnov** [comment]
@Nawazsherif We support icons in some buttons.

Thank you,
Andrew
