### ISSUE TITLE
matrix dynamic - key column 

### ISSUE THREAD

**Issue by madceb** [surveyjs/surveyjs#551]
Hello, Is there a way of restricting user adding more than one row with same dropdown selected option?
Thanks.

**Comment by andrewtelnov** [comment]
@madceb Yes, I was thinking about this functionality as well. Right now you may use onValidateQuestion event. Here is [the demo](http://surveyjs.org/examples/jquery/validators-event/). 
I was thinking about adding a validator for MatrixDymanic and PanelDymic questions - 
PreventDublicateValueValidator, you will have to set the columnName/questionName and it will show an error on pressing next page.
I may implement it on the next week.

Thank you,
Andrew

**Comment by madceb** [comment]
Hello @andrewtelnov in the onValidateQuestion event can I iterate a matrix or a paneldynamic? just in case could use it for something else, in this case having something like you mention for PreventDublicateValueValidator would be useful. Regards

**Comment by andrewtelnov** [comment]
@madceb It is implemented and it will be available in the next minor update: https://github.com/surveyjs/surveyjs/issues/557
matrixdynamic.value is an array. You may use the following code:
```
var rowValues = matrixdynamic.value;
for(var i = 0; i < rowValues.length; i ++) {
   cellValue = rowValues["columnName"]; //it can be undefined.
}
```
Thank you,
Andrew

**Comment by madceb** [comment]
Excellent @andrewtelnov, Thanks.

**Comment by madceb** [comment]
Works great! 👍
