### ISSUE TITLE
PanelDynamic - templateTitle & confirm remove?

### ISSUE THREAD

**Issue by madceb** [surveyjs/surveyjs#552]
Hello,
PanelDynamic was a great enhancement, just what I needed. 
I have two questions:

- is it possible to add the panel index in the templateTitle? ex:"templateTitle": "Information: {panelindex}"

- is it possible to add a confirmation when remove button is clicked? it is too easy to remove a panel by mistake after is already fill out.

- forgot a third one :p same as in the matrix dynamic, is it posible to add like a key question. a question that cannot have repeated value in other panel?

Thanks. 
Excellent job!!!

**Comment by andrewtelnov** [comment]
@madceb {panelIndex} - it will be easy to implement and it makes sense, from {1 to panelCount}. I will do it.
Confirmation question on delete - I wanted to implement it on the beginning, but then decided to add this functionality in the next minor release. Absolutely agree, it is a "must be" functionality.
key question/value - hm... I was thinking about adding a validator, but I think key name (column/question) is a better solution. I will do it, likely on the next week.

Thank you,
Andrew

**Comment by madceb** [comment]
Thanks @andrewtelnov this is already a great tool, this will make it event better. 
Excellent!

**Comment by andrewtelnov** [comment]
@madceb I have implemented these features:
https://github.com/surveyjs/surveyjs/issues/555
https://github.com/surveyjs/surveyjs/issues/556
https://github.com/surveyjs/surveyjs/issues/557

Thank you,
Andrew

**Comment by madceb** [comment]
Great!!! @andrewtelnov. Thanks  🥇

**Comment by madceb** [comment]
Looks and Works great! 👍  Excellent Job @andrewtelnov
