### ISSUE TITLE
Store data as text. 

### ISSUE THREAD

**Issue by nrhoffmann** [surveyjs/surveyjs#553]
### Are you requesting a feature, reporting a bug or ask a question?

I'm asking a question. 

What happened to the a file that the user uploads if I don't select "storeDataAsText" and I'm not using the dxService.

**Comment by nrhoffmann** [comment]
I'm using react.

**Comment by dmitrykurmanov** [comment]
@nrhoffmann hello! In that case you need to handle file uploading by yourself. Please find `onUploadFile` in the doc: http://surveyjs.org/docs/api_surveymodel.html. And for example something like that: https://plnkr.co/edit/W2gKg1EEVzgDDO2POniV?p=preview

**Comment by nrhoffmann** [comment]
If I modify `model.data`, will the change be reflected in `sender.data`?

**Comment by nrhoffmann** [comment]
To clarify: will that change be reflected in a subsequent event's sender / model?

**Comment by andrewtelnov** [comment]
@nrhoffmann model.data and sender.data in the events are the same instance.

It is better to use sender, because you may have more then one surveys instance on the page and event handler function may be used by several surveys.

However you may use any variant, since you have only one survey instance:
```
var survey = new Survey.Model({...});
```

```
survey.onComplete.add(function(result) {
      var data = survey.data;
});
survey.onUploadFile.add(function(model, options) {
    var data = survey.data;
});
```
==
```
survey.onComplete.add(function(result) {
      var data = result.data;
});
survey.onUploadFile.add(function(model, options) {
    var data = model.data;
});
```

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
No reply for a long time. I am closing the issue.
