### ISSUE TITLE
[survey-vue] All checkbox has input textbox, when "other" checked on survey-vue

### ISSUE THREAD

**Issue by astondihor** [surveyjs/surveyjs#558]
### There's a bug on survey-vue hasOther?
I tried to make a copy of the same example as in http://surveyjs.org/docs/integration.html using vue 2.4.2. But that example not playing nice. 

### What is the current behavior?
When i tried to check the "other" radio. Suddenly all checkboxes have it's input textbox.

### What is the expected behavior?
The expected behavior is only "other" radio, has the input textbox. Like when I use survey-vue v0.12.3

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://jsfiddle.net/astondihor/5f1drprL/1/

Test code

```js
var surveyJSON = { title: "Tell us, what technologies do you use?", pages: [
  { name:"page1", questions: [ 
      { type: "radiogroup", choices: [ "Yes", "No" ], isRequired: true, name: "frameworkUsing",title: "Do you use any front-end framework like Bootstrap?" },
      { type: "checkbox", choices: ["Bootstrap","Foundation"], hasOther: true, isRequired: true, name: "framework", title: "What front-end framework do you use?", visibleIf: "{frameworkUsing} = 'Yes'" }
   ]},
  { name: "page2", questions: [
    { type: "radiogroup", choices: ["Yes","No"],isRequired: true, name: "mvvmUsing", title: "Do you use any MVVM framework?" },
    { type: "checkbox", choices: [ "AngularJS", "KnockoutJS", "React" ], hasOther: true, isRequired: true, name: "mvvm", title: "What MVVM framework do you use?", visibleIf: "{mvvmUsing} = 'Yes'" } ] },
  { name: "page3",questions: [
    { type: "comment", name: "about", title: "Please tell us about your main requirements for Survey library" } ] }
 ]
}
```

### Specify your

* browser: Google Chrome
* browser version: 60.0.3112.90 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): VUE
* surveyjs version: 0.12.21

**Comment by dmitrykurmanov** [comment]
The bug appeared in 0.12.4 version.

**Comment by dmitrykurmanov** [comment]
@astondihor, thank you for finding the bug. I've fixed it. Fix will be in next release (we think about tomorrow). You can use dev version of our cdn (https://surveyjs.azureedge.net/dev/survey.vue.js). I've updated you fiddle https://jsfiddle.net/m5b1gc86/ could you check it please?

**Comment by astondihor** [comment]
@dmitrykurmanov, thank you so much, for the quick response. You're rock!
