### ISSUE TITLE
Image Picker with Option Groups

### ISSUE THREAD

**Issue by gaurav-singhal** [surveyjs/surveyjs#559]
Just a feature request or support...

How do we create a question with multiple image selection and Option group. I am looking for something similar to Grouped Options of http://rvera.github.io/image-picker/

**Comment by tsv2013** [comment]
You can create corresponding custom widget, like [this - Image Picker question](http://surveyjs.org/examples/jquery/custom-widget-image-picker/).

**Comment by gaurav-singhal** [comment]
But how to specify option grouping? I can create multiple but how will we specify option groups in question json?

**Comment by tsv2013** [comment]
As a strait forward approach I can suggest you to include group id as a part the question choice's value (separated via hyphen here):

```
{ type: "dropdown", name: "choosepicture", renderAs: "imagepicker", title: "What animal would you like to see first ?", 
     choices: [
        {value: "lion-group1", text: "http://surveyjs.org/images/image-picker/lion.jpg"},
        {value: "giraffe-group2", text: "http://surveyjs.org/images/image-picker/giraffe.jpg"},
        {value: "panda-group3", text: "http://surveyjs.org/images/image-picker/panda.jpg"},
        {value: "camel-group2", text: "http://surveyjs.org/images/image-picker/camel.jpg"}
     ]
  }
```

In this case you can parse choice value and find out group name or even get more info.

**Comment by tsv2013** [comment]
There is another available way to set group option:

```
{ type: "checkbox", name: "choosepicture", renderAs: "imagepicker", title: "What animal would you like to see first ?", 
     choices: [
        {value: "lion", group: "g1", text: "http://surveyjs.org/images/image-picker/lion.jpg"},
        {value: "giraffe", group: "g2", text: "http://surveyjs.org/images/image-picker/giraffe.jpg"},
        {value: "panda", group: "g3", text: "http://surveyjs.org/images/image-picker/panda.jpg"},
        {value: "camel", group: "g2", text: "http://surveyjs.org/images/image-picker/camel.jpg"}
     ]
  }
```

This option will be available in the `afterRender` function of the custom widget:

```
afterRender: function(question, el) {
    // question.choices[0].group // - will return "g1"

```

**Comment by gaurav-singhal** [comment]
Thanks it worked!
