### ISSUE TITLE
Not possible to set a trigger on a field inside a matrixdropdown

### ISSUE THREAD

**Issue by mattes3** [surveyjs/surveyjs#56]
If I have a matrixdropdown, I cannot trigger on a field, only on the result of the entire question which does not work. I tested with "contains" but this does not work, either.

Would be much better to have something like this:

{ type: "visible", name: "myMatrix.row[3].field[5]", value: "sedan", questions: ["Sedan"] },

**Comment by andrewtelnov** [comment]
I will think about it.
FYI:
I am going to change the trigger mechanism greatly. Several developers has already asked about multiple condition. I am working on binary expression right now. The main challenge is to create the binary expression editor that non-technical people could use. Not sure I will get something good, at least I will try.
The old trigger properties: name, operation and value will be converted into condition, for example: name: 'question1', operation: 'equals', value: 5, becomes condition: "‘question1’ = 5". You will be able to set the condition as: (‘question1’ > 2 || 3 = ‘question2’) and ‘question3’ != ‘aaa’

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Please refer to this: https://github.com/andrewtelnov/surveyjs/issues/60

**Comment by andrewtelnov** [comment]
Hi,
I've made some progress here. I have posted the changes into the repo. At the current moment your scenario doesn't work, but I would love to work on it. 
Could you provide me with a small example (survey json), so I do exactly what you need and do not work on a fancy nobody needed thing?

Thank you,
Andrew
