### ISSUE TITLE
In numeric validator how do you specify the {0} value for numericMin / numericMinMax

### ISSUE THREAD

**Issue by madceb** [surveyjs/surveyjs#560]
Hello,
In numeric validator how do you specify the {0} value?

- numericMinMax: "The '{0}' should be equal or more than {1} and equal or less than {2}",
- numericMin: "The '{0}' should be equal or more than {1}",

Regards,

**Comment by andrewtelnov** [comment]
@madceb It is a getValidatorTitle(): string function of IValidatorOwner interface.
Question class implements it and returns null, as result "value" is used in this case. I just realized that it is not localized. 
MutlipleText question Item implements  IValidatorOwner interface as well and returns the item title in getValidatorTitle().
Do you want to change or control it?

Thank you,
Andrew

**Comment by madceb** [comment]
Hello @andrewtelnov, I was testing a localized version and the {0} is always shown as "Value", there is the option for using your own validation message but if the "Value" could be localized would be cleaner than having a custom message for all numeric fields, worse case scenario I could add the custom "text" validation message, but I was curious if maybe I was missing something for that {0} to be replaced.
Regards

**Comment by andrewtelnov** [comment]
@madceb I have added 'value' into surveyStrings object. Please translate it in the language you need: https://github.com/surveyjs/surveyjs/tree/master/src/localization

Thank you,
Andrew

**Comment by madceb** [comment]
Great @andrewtelnov , Thanks.
