### ISSUE TITLE
input fields

### ISSUE THREAD

**Issue by h123eranga** [surveyjs/surveyjs#561]
How to add a default value to a input field?

<input type="text" name"firstName" value="Haris" />

It is not working in surrvey.js
{type: "text", name: "firstName", title: "Enter your name", value: "Haris"}

**Comment by dmitrykurmanov** [comment]
@h123eranga, hello, could you please check this feature: http://surveyjs.org/examples/jquery/survey-data/ and this example: https://plnkr.co/edit/ZFiyAyTzeLMB2hWwAEyK?p=preview

**Comment by h123eranga** [comment]
great!!! thanks you very much

**Comment by dmitrykurmanov** [comment]
@h123eranga, you are welcome.

**Comment by h123eranga** [comment]
Can I do the two way binding with this?

**Comment by andrewtelnov** [comment]
@h123eranga What do you mean? bind with survey.data? It works as two way binding.

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
@h123eranga, I think it is already two-way or maybe i don't understand you, could you get more details please and create an example?

**Comment by h123eranga** [comment]
I mean can I use this with angular 1and 2?
Like this

Angular 1
<input type="text" ng-model="name" />

Angular 2
<input type="text" [(ngModel)]="name" />

**Comment by dmitrykurmanov** [comment]
@h123eranga, surveyjs is 3-d party library. Think about it as "black box" with API. So you could integrate SurveyJS in angular2 project that way. For example, please see our qiuckstart repos, based on official Angular repos: https://github.com/surveyjs/surveyjs_angular_quickstart and https://github.com/surveyjs/surveyjs_angular_cli. Or please check any example on plnkr e.g. http://surveyjs.org/examples/angular/survey-data/ (ckick _edit in plunker_)

**Comment by h123eranga** [comment]
Thanks
