### ISSUE TITLE
select2 widget example and hasOther

### ISSUE THREAD

**Issue by madceb** [surveyjs/surveyjs#562]
Hello,
Could you give me some pointers on how I could add support for hasOther configuration in a widget?
Thanks and Regards,

**Comment by tsv2013** [comment]
In the select2 cusom widget [example](http://surveyjs.org/examples/jquery/custom-widget-select2/) the template is declared as:
`htmlTemplate: "<select style='width: 100%;'></select>",`
thus there is no input control for the other value here.
This control should be added to the templated and managed by the custom widget code: make it visible is case of "other" value selected and bind to the model.

**Comment by andrewtelnov** [comment]
@madceb This functionality has been implemented into select2 custom widget some time ago.

Thank you,
Andrew
