### ISSUE TITLE
How to modify isRequired error text

### ISSUE THREAD

**Issue by h123eranga** [surveyjs/surveyjs#563]
How to change the message getting in isRequired directive?

Current message
"Please answer the question."

Modified message
"Please enter your firstname"

**Comment by andrewtelnov** [comment]
@h123eranga Unfortunately there is no way to do it at the current moment.
I have added a new property into question object: requiredErrorText. It is empty by default and the default error text is used. If it is not empty, this text will be shown on the error.
It will be available in the next minor update. We will likely release it on the next week.

Thank you,
Andrew

**Comment by h123eranga** [comment]
Thank you very much and one more thing.

How to define a choices array based on the answer for another question?
I mean if there is a form asking age if age > 18
I want to display the following 
choices : option1, option2
otherwise
choices: option1, option3

I am asking how to add and remove elements from a choices array based on another answer.

**Comment by andrewtelnov** [comment]
@h123eranga I would suggest you to have two invisible questions with the same name. The first question will have visibleIf = "age < 18" the second visibleIf "age >= 18". They will have different choices properties.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Here is the example: http://plnkr.co/edit/4aw7vmjt1fIulspnCp5x?p=preview

**Comment by h123eranga** [comment]
ha ha...Thanks. I was having the angular 1 idea thats why I asked like that.

**Comment by sarn3792** [comment]
Is there any way to change this text?
![image](https://user-images.githubusercontent.com/9375416/54648050-76b3e280-4a6a-11e9-9a22-35cdb559cc21.png)

I want to display it in Spanish.

Thanks.

**Comment by andrewtelnov** [comment]
@h123eranga You may set the survey locale to spanish: "survey.locale = "es";" and it will take it from [here](https://github.com/surveyjs/surveyjs/blob/master/src/localization/spanish.ts#L13)
As alternative, you may set the question.requiredErrorText property.

Thank you,
Andrew
