### ISSUE TITLE
Visible if for checkbox value

### ISSUE THREAD

**Issue by xiuzhen1103** [surveyjs/surveyjs#565]
### Are you requesting a feature, reporting a bug or ask a question?

Ask question or reporting a bug

### What is the current behavior?
Example in checkbox has a, b, c, e options,
if comment box visible if e is elected. 

Visible if only can be set if value=e, but it dosen't work with checkbox,
if e value a is checked and a is selected, comment box invisible.

### What is the expected behavior?
From above, I would like to keep comment box visible dosen't matter if a, b, c has been selected.

### How would you reproduce the current behavior (if this is a bug)?
![image](https://user-images.githubusercontent.com/6764095/29407763-773678b2-833d-11e7-87b6-0320e5d628e4.png)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
http://plnkr.co/edit/cRG2Lu9NSWcZXpFJeAo7?p=preview

**Comment by andrewtelnov** [comment]
@xiuzhen1103 Please use contains operator: visibleIf: "{LR_15} contains 'Other' and {LR_14}='Yes'"
I have corrected the example: http://plnkr.co/edit/xkfaVERRr8CxCbRQW97D?p=preview

Thank you,
Andrew

**Comment by mellogarrett** [comment]
This is fantastic! I couldn't find this in the documentation on the website, though...

**Comment by andrewtelnov** [comment]
@mellogarrett Here is the link: https://www.surveyjs.io/Documentation/LibraryParameter?id=QuestionBase&parameter=visibleIf

Thank you,
Andrew

**Comment by mellogarrett** [comment]
How would I navigate to this without the link?

**Comment by andrewtelnov** [comment]
https://www.surveyjs.io/Documentation/Library/?id=questionbase#visibleIf
We will work on our docs usability and content. I know it sucks right now.

Thank you,
Andrew

**Comment by mellogarrett** [comment]
:) thanks @andrewtelnov

**Comment by StephanMeijer** [comment]
Can you maybe improve docs visibility on these?

**Comment by dmitrykurmanov** [comment]
@StephanMeijer  I think the correct link now is https://www.surveyjs.io/Documentation/Library/?id=questionbase#visibility
