### ISSUE TITLE
Display standard validation errors on the click of a custom button

### ISSUE THREAD

**Issue by sdg002** [surveyjs/surveyjs#566]
How I can make the Survey display the standard validation messages when I click a custom button.  I am not relying on the out of box "Complete" functionality to do the validations. I do not intend to validate on the server. 

Example of a survey: http://surveyjs.org/examples/jquery/validators-standard/
What if I had a custom button "Hi, click here to complete" . What code would I write in the click event handler to make the Survey display all the errors.

**Comment by andrewtelnov** [comment]
@sdg002 survey.completeLastPage() method, that you should call on your custom button should make the validation.
You may also call survey.isCurrentPageHasErrors() method. It will return true if there are errors.

Thank you,
Andrew

**Comment by sdg002** [comment]
Hi Andrew,
Thanks for getting back so quickly.

I tried calling invoking completeLastPage() but this hides all the questions and as though I have clicked on the Complete 

**My scenario:**
 I have custom buttons to navigate to each page. E.g. a button "Page 1" which will jump to "Page 1" by invoking the property **currentPageNo** .

As explained in my earlier post, I also have a custom "**My Custom Finish**" button which can be called from any context. The user need not have to be on the last page to see and click the "**My Custom Finish**" button. I could answer the questions on any Page 5 and jump back to Page 1. 

**Objective**

Any time, the user clicks on "**My Custom Finish**", 

1.  display all the standard validation errors on all the pages,
2.  take a snapshot of the response from the survey using the **data** property 
3.  save JSON it to my custom back end.  
4.  The user should be able to resume later by pulling the data from the back end.
5.

 

 

Is such a scenario supported by SurveyJS?

thanks,
Saurabh

**Comment by andrewtelnov** [comment]
@sdg002 Sure, it is doable
1. show all validation error
```
var hasError = false;
for(var i = 0; i < survey.visiblePages.length; i ++) {
    //the first parameter, fireCallback, is set it to true to show errors in UI
    hasError = survey.visiblePages[i].hasErrors(true) || hasError; 
}
if(hasError) alert('There is at least one error in the survey.');
```
2. survey.data returns the current survey data as JSON. You may get them at any moment
3. there should be your code to store the data JSON
4. 
5. create the survey as you commonly do and call survey.data = jsonSavedInYourDataBase;
I would suggest to store and then restore survey.currentPageNo, so the end-user will be on the same page as he close the survey.

Thank you,
Andrew

**Comment by sdg002** [comment]
Thank you Andrew. Yes, I can confirm your code snippet works. I would not have figured this without your help.

**Final question:**
On the click of our "**My Custom Finish**" button, we would like to present a list of errors to the end user and the user should be able to click on the error message and jump to the specific page.

**Getting the Error message?**
Using your approach above, we are now able to determine the total count of errors and the index of the page where the errors occurred. Is there a method/property that gives me each of the error message as well?

thanks,
Sau

**Comment by andrewtelnov** [comment]
@sdg002 You will have to create a list of errors with following parameters:
{page, question, error}
```
var errors = [];
for(var i = 0; i < survey.visiblePages.length; i ++) {
    var page =survey.visiblePages[i];
    var questions = page.questions; 
    for(var j = 0; j < questions.length; j ++) {
       questions[j].hasErrors(true); 
       var qErrors = questions[j].errors;
       for(var k = 0; k < qErrors.length; k ++) {
            errors.push({page: page, question: questions[j], error: qErrors[k]});
       }
    }
}

```
You may show the list of this errors on your page. 
The error object has error.getText(); function. So you may show the error text.
You may go to the specific page by calling survey.currentPage = page; 
And at last question has the question.focus(); method.

PS: I did not test the code snip, but it should work. Let me know if it works.

Thank you,
Andrew

**Comment by sdg002** [comment]
Hi Andrew,
Thanks again. This code is almost perfect. There is just one short coming. Observations below:

I created a survey and introduced 2 questions. 
**Question 1:** Single input. Validation rule minLength=3
**Question 2:** Matrix with dynamic rows. Validation rule minLength=3
These questions are on different pages.


**What works?**
The line  with **questions[j].errors**  gives me full error information I wanted for **Question 1**
The line **survey.visiblePages[i].hasErrors(true)** successfully gives me an error for both **Question 1** and **Question 2**

**What did not work?**
The line  with **questions[j].errors**  does not give me any errors for **Question 2**

**Comment by andrewtelnov** [comment]
@sdg002 I have added getAllErrors() function. It will be available with the next minor update (likely next week). Errors in Matrix question belongs to cell question errors, that is why Matrix.errors returns empty array. getAllErrors() will return all errors for Matrix and PanelDynamic questions.

Thank you,
Andrew

**Comment by sdg002** [comment]
Thanks so much Andrew for your proactive help.

**Comment by sdg002** [comment]
thank you Andrew.


________________________________
