### ISSUE TITLE
Locale formatting of number fields

### ISSUE THREAD

**Issue by enricribas** [surveyjs/surveyjs#567]
Is it possible to add commas to the display, not the final JSON ideally, of a field, so that users can more accurately enter large numbers? It would probably also be nice to add dollar sign, etc to fields. I think this would use .toLocaleString() since different languages format numbers differently

**Comment by dmitrykurmanov** [comment]
@enricribas, hello. I think it is a good proposal. We'll think about it. Thank you!

**Comment by dmitrykurmanov** [comment]
@enricribas @andrewtelnov @tsv2013 may be we can use something like that: https://github.com/nosir/cleave.js or https://github.com/RobinHerbots/Inputmask. We could create a custom widget for that functionallity. What do you think?

**Comment by enricribas** [comment]
Would be nice if people could choose whatever formatter they wanted. I would imagine a wrapper function around the display of fields that we could implement that gets called before displaying field would work. 

Personally, I'd just call ```toLocalestring()``` because different cultures format numbers differently. Ie in europe, periods are used for separators, not commas, but someone else could call something else.

**Comment by enricribas** [comment]
Is there anything we can do about at least getting commas in number fields? I'm not sure what I can other than loading some crazy js hack that listens to inputs and changes the value, and then strips out the commas before processing which is pretty gross.
Would be really appreciated, and I'm sure lots of people would like this for larger numbers. Can I get an upvote, people? :)

**Comment by andrewtelnov** [comment]
@enricribas I am thinking about adding mask custom widget based on  [vanilla-masker](http://vanilla-masker.github.io/vanilla-masker/). Will it solve your issue?

Thank you,
Andrew

**Comment by enricribas** [comment]
That would be great, seems like I could add commas and currency symbols. I'm sure that solves 90% of people's problems. Definitely solves mine. :)

**Comment by enricribas** [comment]
Any idea/ progress on this? Our management really, really, really wants commas, and I've tried a few very hacky ways to add them but nothing that I am comfortable releasing to production.

It can wait, but if you're not working on it any time soon, I might just release my hacky version to the wild. 

Thanks,

**Comment by andrewtelnov** [comment]
@enricribas We will make a new custom widget that will support a mask edit, including the currency.
@dmitrykurmanov will work on it.

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
@enricribas, I've created an example based on : https://github.com/RobinHerbots/Inputmask
https://plnkr.co/edit/KrROUQV2C3vF5SYrm3y5?p=preview
could you check it please? And I will add it in our examples.

**Comment by enricribas** [comment]
I think that looks great. Will set it up today. Thanks!

**Comment by dmitrykurmanov** [comment]
@enricribas, please check the example: https://surveyjs.io/Examples/Editor/?id=customwidgets and the license of the edtior https://surveyjs.io/Home/Licenses, thanks!

**Comment by dmitrykurmanov** [comment]
@enricribas, I've added examples on  the site : https://surveyjs.io/Examples/Library/?id=custom-widget-inputmask&platform=jQuery
