### ISSUE TITLE
move alert message to bottom of the row

### ISSUE THREAD

**Issue by xiuzhen1103** [surveyjs/surveyjs#568]
### Are you requesting a feature, reporting a bug or ask a question?
Ask a question

### What is the current behavior?
Alert message is under the question, is there any chance that if i could move alert message under form-inline class, please?
![image](https://user-images.githubusercontent.com/6764095/29421437-01e42930-836d-11e7-97ba-5b34acaa3aa4.png)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
http://surveyjs.org/examples/react/trigger-visible/
f12 on it, do not select anything, click submit button

**Comment by tsv2013** [comment]
Hi!
Thank you for the interest in our product!
We've not such a functionality yet. I've added this ticket to our todo list.
We're going to introduce an option `questionErrorLocation` with values `top` and `bottom` in the `Survey` object.
I'll update this ticket when it will be implemented.

**Comment by xiuzhen1103** [comment]
hi @tsv2013 
do you think its good idea for alert message to be disappear once user has answered question?

**Comment by xiuzhen1103** [comment]
one more request, is there any chance that If alert message appears, a question highlighted?
I would like to add red border wrap the question, if alert message appear. 
Example as following: 
----------------------------------------------------------------------
|question: test question?               answer1 answer 2
| * Please answer the question
----------------------------------------------------------------------------

**Comment by xiuzhen1103** [comment]
![image](https://user-images.githubusercontent.com/6764095/29454032-a1eabde0-8403-11e7-985d-665c6f299ea6.png)

**Comment by andrewtelnov** [comment]
@xiuzhen1103 We have added a new [property survey.questionErrorLocation](https://github.com/surveyjs/surveyjs/issues/578). Set it to bottom.
The functionality will be available in the next minor update. We will release it on this week.

Thank you,
Andrew

**Comment by xiuzhen1103** [comment]
Thnaks @andrewtelnov, Is there any chance that if I could add border red on the question is not answer, please?
