### ISSUE TITLE
widgets in paneldynamic

### ISSUE THREAD

**Issue by madceb** [surveyjs/surveyjs#569]
Hello,
It seems that widgets do not work  for questions inside a paneldynamic, at least for direct childs, because if I have a matrixdynamic inside a paneldynamic using matrixdropdowncolumn, dropdowns widget work, but dropdown as direct child of the paneldynamic doesn't, or am I missing something.

Survey.JsonObject.metaData.addProperty("matrixdropdowncolumn" .. works inside and outside of the matrix.

Survey.JsonObject.metaData.addProperty("dropdown".... direct child of paneldynamic doesnt get applied.

Regards,

**Comment by andrewtelnov** [comment]
@madceb Thank you, the bug is fixed. The fix will be available in the next minor.

Andrew
