### ISSUE TITLE
Can i use `<script>` with `vue.js`?

### ISSUE THREAD

**Issue by haeyon098** [surveyjs/surveyjs#570]
hi! I found `surveyjs` and i really wanna use it in my project. 
I use `vue.js`. I'm not good front-end programmer. So, I can't use `npm`.

I want to use `surveyjs` with `<script>` like : https://jsbin.com/voqetuduri/2/edit?html,js,output
I found this context your `Issues`. But, I can't use it because of it made of `knockout`.

Can I use `surveyjs` with `vue.js` and `<script>`?
If you reply, it help me a lot.

**Comment by tsv2013** [comment]
Hi!

We created a  [surveyjs_vue_quickstart repo](https://github.com/surveyjs/surveyjs_vue_quickstart) to demonstrate how to integrate SurveyJS and SurveyJS Editor into VueJS application. Could you check it?

Please feel free to contact us in case of any further questions.

Thanks, Serge

**Comment by haeyon098** [comment]
@tsv2013 Thank you for your answer.
I checked it already. Your `surveyjs_vue_quickstart repo` explains how to use it with`npm`. But, I already told you, I can't use `npm` in my project.
I really wanna use `surveyjs` with `<script>`(or `cdn`) and `vuejs`. 
Can I use it with `<script>`? If it possible, how can I use it?

**Comment by tsv2013** [comment]
In spite of SurveyJS editor is built with KnockoutJs, it can be used with almost any framework.
And it doesn't matter - how this framework compiled and bundled.

I'm a bit confused because of you are telling, that you have a VueJS application. Because probably you are writing Vue components and build and bundle them somehow and inject on the page.

Can I take a look at your project - as a github repo if it possible, and I'll try to help you.

Thanks, Serge

**Comment by haeyon098** [comment]
@tsv2013 Thank you!
At first, I don't understand about `koockout`.
I can use it now! Thanks to you!
Using surveyjs editor, I ask you other questions next time!!

**Comment by dmitrykurmanov** [comment]
@haeyon098  
**for library:** if you need an example without npm you could open any our example for vuejs (http://surveyjs.org/examples/vue/questiontype-radiogroup/) and you will see all code (html/js/css/result tabs) for start or you may open it in sandbox (plunker). 

**for editor:**  we will create same possibility for editor for example https://plnkr.co/edit/oTG18BKp5AqQLCP3fHca?p=preview

**Comment by haeyon098** [comment]
@dmitrykurmanov Thank you about your information!
If you create example, Can I see your homepage? (http://surveyjs.org/index.html)
Will you create example page like library example page (http://surveyjs.org/examples/vue/questiontype-radiogroup/) ?

**Comment by dmitrykurmanov** [comment]
@haeyon098, hello! You can find source code of surveyjs.org in our repo:  https://github.com/surveyjs/site. And you are right, we will create same examples for the editor like for the library.
