### ISSUE TITLE
How can I use Drag and Drop Function?

### ISSUE THREAD

**Issue by hskim1226** [surveyjs/surveyjs#571]
hi! 
I found  surveyjs  and i really wanna use it in my project.
 I use  vue.js .
I want to use  surveyjs   https://jsbin.com/tozewejezo/2/edit?html,js,output

 
Can I use  surveyjs  with  vue.js  and  Drag and Drop Function
 If you reply, it help me a lot.

**Comment by tsv2013** [comment]
Hi!

You can use SurveyJS and SurveyJS Editor in the VueJS project. [surveyjs_vue_quickstart](https://github.com/surveyjs/surveyjs_vue_quickstart) shows it in action.

Could you specify - what do you want to "Drag and Drop" in the survey?

Thanks, Serge

**Comment by hskim1226** [comment]
Thanks, I checked this url. But, I can't use surveyjs editor in my project.

https://jsbin.com/getopemibu/edit?html,css,js,output
In this url, I wanna change question's sequence to use `drag&drop` like this:
http://surveyjs.org/builder/#6fcff871-e4aa-4ad4-8063-023ade7eb364

**Comment by tsv2013** [comment]
Do I understand you right - you want to change the sequence of the questions in the running survey via drag and drop?
This functionality is not available in the SurveyJS library.

I beleive that order of the questions is defined once in the moment then survey is created and end-user, that passes the survey is not ususally allowed to change it.

**Comment by hskim1226** [comment]
Thanks, tsv2013  : )

**Comment by harshit-webnware** [comment]
Is this functionality available now? I need to re-order the questions sequence in a custom modal window and it should reflect the same order in the editor window
