### ISSUE TITLE
how to put visibleif condition based on the selection done on a type matrix

### ISSUE THREAD

**Issue by syash2015** [surveyjs/surveyjs#572]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?
how to put visibleif condition based on the selection done on a type matrix

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@syash2015 Here is the example: https://plnkr.co/edit/oOhqGi?p=preview

Thank you,
Andrew

**Comment by syash2015** [comment]
@andrewtelnov its done. thanks alot sir.
