### ISSUE TITLE
functions added to onAfterPanelRender not firing

### ISSUE THREAD

**Issue by rabidllama** [surveyjs/surveyjs#573]
Hi there, 

it seems that the onAfterPanelRender does not work when you add a new function to it.

I have added the following code, but the alert never shows. If I use the onAfterRenderQuestion.add with the same information, the message is displayed as expected.

```survey.onAfterRenderPanel.add((sender,` options) => {
alert('panel rendered');
});```

If I do not provide a function and instead use `survey.onAfterRenderPanel.add(alert('panel rendered'));` then the alert is shown.

each page that I am showing has two panels, one with a html question, and the other with a sortable question which is based on checkboxes.

currently I am using Firefox 54.0 with surveyjs for jquery (v 0.12.22).

Is this a case that it is not working properly, or am I just handling it all wrong?

Thanks,
Adam

**Comment by rabidllama** [comment]
I think I have found the problem - in the SurveyPanel part of the survey.jquery.js file at around line 6534, the `SurveyPanel.prototype.componentDidMount` calls `this.survey.afterRenderPage(el)` rather than `this.survey.afterRenderPanel(el)`

**Comment by tsv2013** [comment]
Thank you, @rabidllama ! I've fixed it via https://github.com/surveyjs/surveyjs/commit/0a2407bf9f6f7353045435991309c4b8330d48bc commit. Fix will be availbale in the nearest update.

**Comment by rabidllama** [comment]
No worries, I had to change a couple of other things as well to make sure that the afterRenderPage passed in the panel object as well as the html
