### ISSUE TITLE
Routing 

### ISSUE THREAD

**Issue by tthamel** [surveyjs/surveyjs#574]
is there any way to facilitate routing in React with surveyJS. ie the url would be http://localhost:3000/test/1 for question one and  http://localhost:3000/test/2 for question two

**Comment by andrewtelnov** [comment]
@tthamel What do you mean about question one and question two?
Probably you mean page no? I mean you may set routing to change the page no, it is possible.
There is survey.currentPageNo property. It should do a trick.

Thank you,
Andrew

**Comment by tthamel** [comment]
i mean like if i have a sruvey with say 3 questions i want the URL to show https://localhost:3000/1 for the first question and then change to https://localhost:3000/2 for the second question and then https://localhost:3000/3 for the third questions.

**Comment by andrewtelnov** [comment]
@tthamel What do you mean by show first question or changing to the second question? Do they placed on different pages? I just do not understand what do you try to achieve.

Thank you,
Andrew

**Comment by tsv2013** [comment]
@tthamel Do you want to show survey questions on appropriate (and different) pages of the react application?
Let's say the route  https://localhost:3000/1 leads to the 1st quesion and so on?

**Comment by tthamel** [comment]
@tsv2013  yes that is exactly what i want to do, if i have 20 questions in the JSON survey i want them to route to their own react pages https://localhost:3000/1  https://localhost:3000/2 https://localhost:3000/3  etc etc..   

right now i get all the questions 1-20 and the url stays https://localhost:3000/, i need each question to be its own page for routing purposes

**Comment by andrewtelnov** [comment]
@tthamel Here is the example, that does what you need: https://plnkr.co/edit/jhjCD0?p=preview
Just use gotoQuestion function in your route.

Thank you,
Andrew

**Comment by tthamel** [comment]
In the plunker its still a static index route of /

are you saying that if i hook that gotoQuestion function into my router it will work properly?

is gotoQuestion a hook exposed by the API? i didnt see it in the documentation

**Comment by andrewtelnov** [comment]
@tthamel I you may use the code from gotoQuestion method (it is in the plunker example) in your code.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
No reply for a long time. I am closing the issue.
