### ISSUE TITLE
Add question.description property

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#579]
If this property is not empty, show it under the question title.

**Comment by andrewtelnov** [comment]
The feature is almost implemented:
Use css.question.description property to set the class(es) for question description.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
The feature has been implemented. Probably it makes sense to add description for editing in the Question Editor, under the title property. It will require to add just one line of code, but I am not sure  it is needed. If somebody needs it, please let us know.

Thank you,
Andrew

**Comment by Lynn42** [comment]
Will this feature be available for all question types?

**Comment by andrewtelnov** [comment]
Of course, except html question. It doesn't have title.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@Lynn42 The new version has been released. Could you check, does it work for you?

Thank you,
Andrew

**Comment by Lynn42** [comment]
Hi Andrew,

Yes it works like I hoped it would! 
Below a screenshot of two questions in which the property is filled.

![afbeelding](https://user-images.githubusercontent.com/31244247/29704565-a5d27336-897a-11e7-8c6e-f577d7e66a7a.png)

Thanks!

**Comment by MugiwaraNoMehdi** [comment]
Hi !
I have just updated survey-angular to to 1.0.60.
I just don't have this feature... is it normal ?

**Comment by andrewtelnov** [comment]
@MugiwaraNoMehdi It works fine to me. Here is the [angular example](https://next.plnkr.co/edit/LCIH71BnwGzXqReL)

Thank you,
Andrew

**Comment by AndresBarreto-code** [comment]
Hi, there is any way to inject html as question description from javascript ?

**Comment by andrewtelnov** [comment]
@AndresBarreto-code You have to use markdown. Please review examples in [this section](https://surveyjs.io/Examples/Library?id=survey-markdown-radiogroup).

Thank you,
Andrew

**Comment by AndresBarreto-code** [comment]
Thanks you @andrewtelnov !

Indeed I used that resource, to further expand the solution if someone requires it, I attach a section of the code

`
const question = this.survey.getQuestionByName(questionName);
questionElement.description = `<button data-title="${questionName}" data-action="click->quiz#approve">Approve</button>`
survey.onTextMarkdown.add((suvey, options) => {
   if (options.name === "description") options.html = options.text;
 });`
 
 i'm using stimulusjs with rails (RoR)
