### ISSUE TITLE
Column size property for questiontype Matrix Dynamic

### ISSUE THREAD

**Issue by Lynn42** [surveyjs/surveyjs#580]
### Are you requesting a feature, reporting a bug or ask a question?

**Question**

I noticed there is no Size property (or similar, it seems) for the columns when questiontype = matrix dynamic. Is there another way to specify column size in the editor/in the JSON code? Especially when celltype = comment a columnsize property would help when programming the back-end validation.

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@Lynn42 There is column.winWidth property. 

Thank you,
Andrew
