### ISSUE TITLE
Branching support

### ISSUE THREAD

**Issue by dekhaus** [surveyjs/surveyjs#581]
HI

Does SurveyJS support 'branching' - aka the ability to change what future questions are shown to the user based on the answer to a given question ?

Thanks
Dave

**Comment by andrewtelnov** [comment]
@dekhaus Sure, please take a look at [this example](http://surveyjs.org/examples/jquery/condition-kids/).
visibleIf property is available in Question, Panels and Page elements. If a Page or Panel invisible then all their nested elements are invisible too.

Thank you,
Andrew
