### ISSUE TITLE
React components as custom widgets?

### ISSUE THREAD

**Issue by TWKDreamState** [surveyjs/surveyjs#584]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question

### What is the current behavior?
Stuck trying to use a react component as a custom widget

### What is the expected behavior?
Ability to use (for example)..
http://jedwatson.github.io/react-select/
..as a custom widget

Hi, I can't seem to work out how to use the custom widgets to utilise a react-component - not even sure if this is possible! Any thoughts would be appreciated.

**Comment by dmitrykurmanov** [comment]
@TWKDreamState, hello! I think it is possible. So I've created an example for you. And we think about big refactoring of custom widgets. So it will be easier.

**Comment by TWKDreamState** [comment]
@dmitrykurmanov Awesome! Thank you 👍

**Comment by dmitrykurmanov** [comment]
@TWKDreamState hello! I am a little bit confused about react-select. I've create an example according to its documentation and ui doesn't change, please see: https://www.webpackbin.com/bins/-KsObgseFPa7iraC-RMr may be I've missed something.

Anyway I've created an example for react-select (or another react component) as custom widget: https://www.webpackbin.com/bins/-KsNyYxsUGQ_X5t7NPvH

**Comment by TWKDreamState** [comment]
Thank you for this. I went with [react-selectize](https://github.com/furqanZafar/react-selectize)  but this example helped me no end!

I had a slightly more complex requirement - I'm using react-selectize to filter a huge database of suggestions, which updates the state and hence re-renders the component. So I did it in the following way - I'm very new to React so this might not be the best way to do it...

`let widget = {
    name: 'reactSelect',
    render: function(questionBase){
        function onChange(newVal) {
            console.log('Successfully triggered the callback and received: ', newVal)
            questionBase.value = newVal.id ? newVal.id : null;
        }
        return(<SelectPlaces callBackFromParent={onChange}/>)
    },
    isFit: function(question) {
        return question["renderAs"] === 'reactSelect';
    }
};`

I trigger the parent callback from the child. The only thing to do now is provide the data (if the question was previously completed) which I should be able to do by passing in a prop.

Thanks again for your help and if you have any thoughts on whether this is the best way to work it that would be appreciated!!

**Comment by dmitrykurmanov** [comment]
@TWKDreamState, we will do big refactor of custom widgets. So now if it works I think it is ok :) And please feel free post any problem if it will be.

**Comment by TWKDreamState** [comment]
Thanks for your help! Working fine.

**Comment by joeyk16** [comment]
I wanted a custom date picker so i done this
```
class Picker extends Component {
  constructor () {
    super();

    this.state = {
      date: moment(Date.now()),
    };
  }

  onChange = (date) => {
    this.setState({
      date,
    });
  }

  render () {
    const { date } = this.state;
    return <DatePicker onChange={this.onChange} selected={date}/>;
  }
}

export const datePicker = {
  name: "datepicker",
  render: () => <Picker />,
  isFit: function(question) {
      return question.getType() === 'text' && question.inputType === 'date';
  }
};
```

**Comment by tsv2013** [comment]
@joeyk16 And what is going wrong? Your code looks ok for me.
I guess this is not the full code and I can make assumptions only.
Probably you forgot to register this widget with the
`Survey.CustomWidgetCollection.Instance.addCustomWidget(widget);`
code line.

**Comment by ajien** [comment]
Do you have another example of using a react component as a custom widget? The links above are no longer working. I am trying to implement a custom widget using [React Places Autocomplete](https://www.npmjs.com/package/react-places-autocomplete).

**Comment by andrewtelnov** [comment]
@ajien Sure, here it is: https://surveyjs.answerdesk.io/ticket/details/T444

Thank you,
Andrew

**Comment by ajien** [comment]
Thanks, @andrewtelnov . I am trying to do what @TWKDreamState has done but it does not seem to work. Please [check this](https://stackblitz.com/edit/surveyjs-react-custom-component-widget) and let me know what is wrong.

**Comment by ajien** [comment]
Thanks, @andrewtelnov .

[Here's what I did](https://stackblitz.com/edit/surveyjs-react-custom-component-widget) to integrate [React Places Autocomplete](https://www.npmjs.com/package/react-places-autocomplete) into the survey as a custom widget. The widget works in terms of providing the location suggestions, but I am having a problem passing the value to the Survey. Can anyone help me figure out what to do? Thank you!

**Comment by bernardworthy** [comment]
@ajien Did you ever finish the React Place Autocomplete custom widget? I'm looking to do the same thing.

**Comment by ajien** [comment]
Yes I have. I'll show you how once I am back in front of my computer.

**Comment by supermacro** [comment]
ajien been away from his computer for a while 🤣

**Comment by dmitrykurmanov** [comment]
@supermacro we have the "official" example now ;) https://surveyjs.io/Examples/Library?id=custom-widget-react-select

**Comment by supermacro** [comment]
The usage of the API seems quite different from what is documented for simpler custom widgets: https://surveyjs.io/Documentation/Survey-Creator?id=Create-Custom-Widget

Why is there no reference to `CustomWidgetCollection` in the above React example?

**Comment by dmitrykurmanov** [comment]
@supermacro that is because it is a bit different type of Custom Widgets. All the rest are cross-frameworks, and to apply them, we need a pure JS implementation  (without frameworks) API (CustomWidgetCollection, etc...) 

But for the `react-select` one, we have only React framework. So the implementation was done in a "react way".

**Comment by supermacro** [comment]
Is there an example of how to add a custom React widget to the Creator? Been struggling with this.

**Comment by andrewtelnov** [comment]
@supermacro [Here](https://surveyjs.io/Examples/Survey-Creator?id=react-select) it is.

Thank you,
Andrew
