### ISSUE TITLE
How to set up that survey starts right away without having to click the sv_window_title element?

### ISSUE THREAD

**Issue by vanBersie** [surveyjs/surveyjs#586]
I couldn't find anything in the documentary about it but within the result tabs the survey was already rendered. When I created a survey there always appears a button first with the title that I have to click before the survey is shown (dropdown animation).

But I would like the survey initially rendered without having to click the Title Div. Is there already an option for it?

I tested this in my xampp environment.

This is the code I used:

```
var surveyJSON = {
				 cookieName: "Test-Voting",
				 title: "start survey",
				 focusFirstQuestionAutomatic: false,
				 completedHtml: "<p>Test finished!</p>",
				 questions: [{...}]
                             }

var survey = new Survey.Model(surveyJSON);
survey.showTitle = false;
survey.showPageTitles = false;
survey.pageNextText = 'bla';

$("#surveyContainer").SurveyWindow({
    model:survey,
    onComplete:sendDataToServer
});

survey.onTextMarkdown.add(function(survey, options){
    var str = converter.makeHtml(options.text);
    str = str.substring(3);
    str = str.substring(0, str.length - 4);
    options.html = str;
});
var converter = new showdown.Converter();

function sendDataToServer(survey) {
	survey.sendResult('<survey_id>');
}
```

It occures in all Desktop Browsers I used.

**Comment by andrewtelnov** [comment]
@vanBersie I am sorry, I could not understand the issue :(
Could you create a plunker example, something like this: https://plnkr.co/edit/9pXk3RvTsi1BgzwpEyOT?p=preview or describe it in another way?

Thank you,
Andrew

**Comment by vanBersie** [comment]
@andrewtelnov  Sure, I'll try again. This is the example: [https://plnkr.co/edit/Yw0tmaLBVj7mns3LaieD?p=preview](https://plnkr.co/edit/Yw0tmaLBVj7mns3LaieD?p=preview) As you can see you have to click the button before the survey starts. But I don't want the user to click the button to see the questions. I want that the questions displayed right at the beginning like in all the examples within the documentary. But I don't see that I used any option that explains this behaviour and within the documentary I couldn't find anything about this... Do you understand now what I try to achieve? Thanks in advance!

**Comment by andrewtelnov** [comment]
@vanBersie Arh I see. You are using SurveyWIndow and not Survey. I have updated the plunker: https://plnkr.co/edit/up48g53VuQBB1bm1AoVd?p=preview
Do you want to use SurveyWindow to be able show/hide the survey?

However, I did not find an easy way to show the window expanded by default. This functionality should be implemented. I will add in our TODO list.

Thank you,
Andrew

**Comment by vanBersie** [comment]
Ah, so that was it. Thanks!!! I copy and pasted that snippet somewhere. Using Survey instead of SurveyWindow shows the questions at the beginning. But within my example from above I removed some questions. But I use a radio buttons group with the markup converter and without the SurveyWindow the function `survey.onTextMarkdown.add(function(survey, options)` doesn't work anymore. It throws the error: 'Uncaught TypeError: Cannot read property 'makeHtml' of undefined'. I'll try to find a workaround for that, Besides that it works like a charm. ;)

**Comment by andrewtelnov** [comment]
@vanBersie Please include this script:
<script src="https://cdnjs.cloudflare.com/ajax/libs/showdown/1.6.4/showdown.min.js"></script>
showdown is not our library. We just use it in our example.

Thank you,
Andrew

**Comment by vanBersie** [comment]
I did, but without SurveyWindow it crashed. ;) But if I find a workaround I'll post it here.
