### ISSUE TITLE
How to change the default text value "choose" for dropdown select boxes?

### ISSUE THREAD

**Issue by vanBersie** [surveyjs/surveyjs#587]
I know that it's possible to change the following Text values of buttons:  pagePrevTextValue , pageNextTextValue, completeTextValue

But I wanted to create a survey in another language and wanted to replace the "choose" text with a translation or another text. Is that possible? If yes - how?

**Comment by andrewtelnov** [comment]
@vanBersie At first there is dropdownquestion.optionsCaption property
At second, what language do you need? The community has translated the surveyjs strings on many languages: https://surveyjs.io/Examples/Library/?id=survey-localization

Thank you,
Andrew

**Comment by vanBersie** [comment]
Ah, thank you very much! Adding `survey.locale = 'de';` did the trick. :)
