### ISSUE TITLE
Version 0.12.23 - event OnAfterRenderPanel not firing

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#588]
hi, in the last version (jquery package), in jquery.min.js there is no this part of code:

,e.onAfterRenderPanel && this.survey.onAfterRenderPanel.add(function (t, n)
{
	e.onAfterRenderPanel(t, n)
}
)

and then the event OnAfterRenderPanel is not firing

**Comment by andrewtelnov** [comment]
@care46 I have just checked it. Here is [the plunker example](https://plnkr.co/edit/uTgYFekjxYHibnroP37B?p=preview). It uses script: 
<script src="https://surveyjs.azureedge.net/0.12.23/survey.jquery.min.js"></script>

Thank you,
Andrew

**Comment by care46** [comment]
i see your plunker, the difference is this:

- your js

**survey.onAfterRenderPanel.add(function(result, options) {
  alert(options.panel.name);
});
$("#surveyElement").Survey({ 
    model: survey 
});**

- MY js

**$("#"+id).Survey({	
	model:this.model,
	onAfterRenderPanel: doOnAfterRenderPanel
});
function doOnAfterRenderPanel(model,options)
{
	debugger;
}**

with the other function "onAfterRenderPage, question ecc" also my way work correctly, i can't use the same way with OnAfterRenderPanel?

**Comment by andrewtelnov** [comment]
@care46 You are right. My bad. I have added required two lines of code.

Thank you,
Andrew

**Comment by care46** [comment]
Perfect! thanks ;)
