### ISSUE TITLE
Level 2 embedded question doesn't disappear.

### ISSUE THREAD

**Issue by Aymsu** [surveyjs/surveyjs#589]
### Are you requesting a feature, reporting a bug or ask a question?

Bug / feature ?

### What is the current behavior?

3 questions (radio button with yes/no answers)

if question 1 is answered yes ==> question 2 is displayed.
if question 2 is answered yes ==> question 3 is displayed.

Now if both question 1 and 2 are at yes, and you change question 1 to no, question 2 disappears but not question 3

### What is the expected behavior?

Question 3 disappears as well. Basically if possible when a question becomes invisible, answers to the said question should be deleted so no embedded question remains

### How would you reproduce the current behavior (if this is a bug)?

Json from your editor below. 

#### Provide the test code and the tested page URL (if applicable)

{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "panel",
     elements: [
      {
       type: "radiogroup",
       choices: [
        "yes",
        "no"
       ],
       name: "question1"
      }
     ],
     name: "panel1"
    },
    {
     type: "radiogroup",
     choices: [
      "yes",
      "no"
     ],
     name: "question2",
     visible: false,
     visibleIf: "{question1} = 'yes'"
    },
    {
     type: "radiogroup",
     choices: [
      "yes",
      "no"
     ],
     name: "question3",
     visible: false,
     visibleIf: "{question2} = 'yes'"
    }
   ]
  }
 ]
}

### Specify your

* browser: tested on both Chrome and IE (and reproduced on your editor)
* browser version:
* surveyjs platform : Angular 2/4
* surveyjs version:

**Comment by andrewtelnov** [comment]
@Aymsu It is correct behavior:
"Now if both question 1 and 2 are at yes, and you change question 1 to no, question 2 disappears but not question 3" - the value of question 2 did not changed, visible property was changed.
Please use the following visibleIf for question 3
`visibleIf: "{question1} = 'yes' and {question2} = 'yes'"`

Thank you,
Andrew

**Comment by Aymsu** [comment]
Okay that sounds good.

One last thing, is there a way to not submit the value of a question if it is invisible but answered?

**Comment by andrewtelnov** [comment]
@Aymsu 
set [survey.clearInvisibleValues](https://surveyjs.io/Documentation/Library/?id=surveymodel#clearInvisibleValues) to true.

Thank you,
Andrew

**Comment by Aymsu** [comment]
@andrewtelnov thanks a lot mate ! 

keep up the good work !
