### ISSUE TITLE
Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.

### ISSUE THREAD

**Issue by jpfiorilla** [surveyjs/surveyjs#590]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug.

### What is the current behavior?
Using Reactified npm package `survey-react`, loading any `Page` with a dropdown in it causes an error for each `<option>` on the page:

````warning.js?8a56:36 Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.````

### What is the expected behavior?
Using `value` on the `<select>` tag instead of `selected` on the selected `<option>`.

### How would you reproduce the current behavior (if this is a bug)?
Make a survey with a dropdown.

### Specify your

* browser: Chrome
* browser version: Version 53.0.2785.143 (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: "survey-react": "^0.12.19"

**Comment by dmitrykurmanov** [comment]
@jpfiorilla, hello, could you please update survey-react version to latest. We don't have the warnings in our current example, please check https://surveyjs.io/Examples/Library/?id=questiontype-dropdown&platform=Reactjs

**Comment by jpfiorilla** [comment]
Thanks boss, that did the trick
