### ISSUE TITLE
When trying to Generate Access Key for dxservice API there is a bug, access key won't be shown

### ISSUE THREAD

**Issue by vanBersie** [surveyjs/surveyjs#591]
Bug Report

On [https://dxsurvey.com/Help/Api/GET-api-MySurveys-getSurveyResults-id_accessKey](https://dxsurvey.com/Help/Api/GET-api-MySurveys-getSurveyResults-id_accessKey) when clicking the button "Generate new access key" the key can't be written in the div because the selector is looking for the id "access-key" but the div has the class "access-key" but not the id. 

You can get the access key from the network panel but most users won't find it.

**Comment by andrewtelnov** [comment]
@vanBersie  Thank you very much. 
We will fix it, @tsv2013. We are currently on process of moving dxsurvey.com into surveyjs.io/service.
dxsurvey.com will be for end-users only, without all these access key and GUIDs They scary normal people :)

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
@vanBersie, hello, we've fixed it in our new site, please check surveyjs.io
