### ISSUE TITLE
Is there some kind of backend validation for results stored at dxservice?

### ISSUE THREAD

**Issue by vanBersie** [surveyjs/surveyjs#593]
**Question**

With using a survey with the cookie option (for example: `var surveyJSON = {cookieName: "<cookie_name>", ... }`) I try to prevent that the same users participate more than once. But when the user deletes his cookies he could do it again. So what I want to do is collecting the users email address and make it impossible that a user with the same email address is sending a survey twice. 

So is there a way to make dxservice to ignore those posts if the email address already exists? Or as alternative is there a way to look for the email address via the api before sending? But it would have to be an api call that returns a boolean and not all email addresses because of privacy reasons.

Thanks in advance!

**Comment by andrewtelnov** [comment]
@vanBersie Sure, it is a common scenario. Please take a look at this demo: https://www.surveyjs.io/Examples/Library/?id=service-oneperuser
and clientId property.

Thank you,
Andrew

**Comment by vanBersie** [comment]
@andrewtelnov Thank you! I saw this example but it didn't look helpful to me. Do you mean that instead of the Hash I should use the value from the mail input field as client id? But I guess that won't work because you need the client id to init the survey, right? So how is this hash set? I don't get it :D

**Comment by andrewtelnov** [comment]
You are putting your customer/user ID, for example e-mail or better e-mail hash into clientId (you do not to restore the e-mail from hash, the only limitation, it should be unique for all your users),  and if you are using the service and post data via postId, you are done :-)

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Yes, you have to set the surveyId as well.
It works in the following way. If the surveyId is used without clientId, the library gets the survey JSON and load it into the survey model/widget.
If the surveyId and clientId is used, then library gets the survey JSON and information, if the current client has completed the survey. If the survey is completed the message about survey completion is shown.

Thank you,
Andrew

**Comment by vanBersie** [comment]
Ah ok, thank you very much! But in that case it won't work for me because the user is not logged in or something so I don't have the email address until he types it into the email input field. :D 

So there is no other way to filter that out?

The API also doesn't seem to have an option to delete single entries by id or replace all results with a json and on https://dxsurvey.com/Home/SurveyResults/<id> there doesn't seem to be an option for importing a result json. So I guess one can only clean the data afterwards. Or am I overlooking something?

**Comment by andrewtelnov** [comment]
@vanBersie There is not much you can do here. Browsers are working on client devices. They have the full control over them, we have not much control due security reason.
So you may use cokies or local storage  on the client, or create a unique identificator for a user and use it. IP want help either, since one IP address may be used by several clients.
The only good solution - the person who runs the survey should be somehow authorized, by log-in to your system or OAuth (facebook, google, twitter and so on).

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
There are two methods, delete by id or delete all:
https://dxsurvey.com/Help/Api/GET-api-MySurveys-deleteResult_accessKey_postId_instanceId
https://dxsurvey.com/Help/Api/GET-api-MySurveys-deleteAllResults-id_accessKey

**Comment by vanBersie** [comment]
@andrewtelnov: Thank you! That helps! I guess then I could create a script that runs one time a day to get all results and deletes doubles by id then.

**Comment by andrewtelnov** [comment]
@vanBersie Yes, you may do this. However, if you setup the clientId, then dxsurvey.com should merge the results. The latest result will override the previous values if needed.

Thank you,
Andrew
