### ISSUE TITLE
onMatrixRowAdded event

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#595]
Hi, in the survey events there is "onMatrixRowAdded", when i add a row in matrixdynamic, this event is fired...
There is the corrispective that i can call when i remove a row?

Thanks

**Comment by andrewtelnov** [comment]
@care46 We do not have it at the current moment. It is not hard to implement it.
However, why do you need it? What is the scenario?

Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov i have a counter for total row question in survey, and i have to refresh counter when i add/remove row in matrix

**Comment by andrewtelnov** [comment]
@care46 got it.

**Comment by andrewtelnov** [comment]
@care46  Do you have a deadline? I was going to add onMatrixRowRemove event, but then realized that you will be able to handle this by using [properties changed event](https://github.com/surveyjs/surveyjs/issues/596). I just started to work on it.

Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov i have to release this in next two month, i have not an immediatly deadline..

thank you

**Comment by andrewtelnov** [comment]
@care46 I believe I will be done in about a week. So let's go this way. You will have an event onPropertyChange on question level and probably on survey level and it will tell that matrix rows property has been changed (add/remove/clear or set).

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@care46 The followup: Here is [the issue](https://github.com/surveyjs/surveyjs/issues/596). It took longer than I have expected, since I was busy with other tasks. I just want to let you know, that I am working on it.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@care46 I have just realized that you need another type of event. I have added it.

Thank you,
Andrew
