### ISSUE TITLE
How to pass variables to survey from the webpage embedding it? 

### ISSUE THREAD

**Issue by rajeev-sudarsan** [surveyjs/surveyjs#597]
### Are you requesting a feature, reporting a bug or ask a question?

Question/Feature request

### How to pass variables to survey before rendering ?

I want use variables in survey definition like "Current date, last quarter, zip code/location" that webpage rendering the survey would know and pass it to survey engine before rendering. For example, as shown below, I would like to pass the values for {zipcode}, {Start_date} and {end_date} from webpage that is rendering the survey to survey engine.

### Example definition
{
 pages: [
  {
   elements: [
    {
     type: "rating",
     name: "How do you like grocery store near {zipcode} ? "
    },
    {
     type: "dropdown",
     choices: [
      "0-5",
      "5-30",
      "30+"
     ],
     name: "How many times have you visited the store between {Start_date} and {end_date} ?"
    }
   ],
   name: "page1"
  }
 ]
}

**Comment by dmitrykurmanov** [comment]
@rajeev-sudarsan, hello! Please check the example https://surveyjs.io/Examples/Library/?id=survey-data&platform=jQuery
