### ISSUE TITLE
How to show a summary page of questions and answers entered by user before submitting the survey?

### ISSUE THREAD

**Issue by rajeev-sudarsan** [surveyjs/surveyjs#598]
### Are you requesting a feature, reporting a bug or ask a question?

Question/Feature Request

### What is the current behavior?

Currently, I am able to submit the results with OnComplete function and show a "Thank you" at end. However, I would  like to show the answers entered by the user and ask them to confirm before submitting it.  I checked the display mode, but could not figure out how to configure before submission.

### What is the expected behavior?

SurveyEngine would have a special question type which would pull all question titles and response user entered before submitting the survey

**Comment by dmitrykurmanov** [comment]
@rajeev-sudarsan, hello! You could create your own custom complete button and do what you want. I've created an example: https://plnkr.co/edit/NkRan1sbD7TyalztZjlc?p=preview please check it. Thanks.

**Comment by andrewtelnov** [comment]
@rajeev-sudarsan I have added this suggest into our TODO list. I makes sense to add it as a built-in functionality. However, we will work on it later.
Right now, as @dmitrykurmanov suggested, you may use the [custom navigation functionality](https://surveyjs.io/Examples/Library/?id=survey-customnavigation) and show a new survey in display with the same questions on one page and same data before submitting the results.

Thank you,
Andrew

**Comment by Noino** [comment]
I would like to add to this one, not only would it be nice to have a built-in single page summary before submit for the one filling the form, but also for the admins a single page review/display mode to view the answers submitted by users.

**Comment by andrewtelnov** [comment]
@Noino to view the survey in readOnly mode set survey.isSinglePage property to true.

Thank you,
Andrew
