### ISSUE TITLE
Different onComplete screen depending on user response

### ISSUE THREAD

**Issue by AndehWong** [surveyjs/surveyjs#599]
### Are you requesting a feature, reporting a bug or ask a question?

Asking a question/requesting a feature (if not implemented)

### What is the current behavior?

On survey complete, there only exists one completedHtml possibility.

### What is the expected behavior?

Is it possible to have two different completedHtml scripts depending on how the user responds to the survey? Would I have to change the HTML using the surveyjs API? is there a possible way of doing this?

**Comment by dmitrykurmanov** [comment]
@AndehWong hello! Sure it is possible. You can do it by standard javascript way, please check the example: https://plnkr.co/edit/PnmUeuB8k1F0LLifGwNz?p=preview
