### ISSUE TITLE
Multiple conditions in triggers and trigger on a question

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#60]
It is time to re-work the current trigger mechanism in the library. There are several limitation at the current moment.
At first, there is no way to have a complex condition in the trigger. You may check only one question value. 
At second, sometimes, it is more convenient to have the visible trigger on the question/page level: make the question/page visible if: [Boolean expression].

The following tasks has to be implemented:
1.    Create a Boolean Expression parser to convert the expression into “Boolean” Graph/Tree.  Example of expression: {age} >= 21 and ({smoke} == ‘no’ or {beerlover} == ‘no’)
2.    Implement a runner. It will run through this “Boolean” tree, using the question values as variables to get the Boolean result (true or false).
3.    Replace the current “name”, “operator” and “value” attributes with a string “condition” attribute, for example name: “age”, operator: “greaterorequal”, value: “21” will become, condition: “{age} >= 21”. Make sure, the old attributes will continue to work (convert them on the fly).
4.    Create a new attribute in a question “visibleIf” with the type of the boolean expression (string).
5.    Create a visual editor for editing Boolean Expression.

**Comment by andrewtelnov** [comment]
visibleIf: string attribute into page and question objects is added.
The functional can be tested now. I am starting to work on visual editor.

**Comment by ItsJoeTurner** [comment]
How can I test this function?

**Comment by andrewtelnov** [comment]
I do not publish a new version yet. However, you may follow the instruction (readme.cmd) and build the library from sources. You will have a new property: visibleIf.

**Comment by andrewtelnov** [comment]
I am using  {youquestionName} for question names in expressions.

**Comment by git2g** [comment]
@andrewtelnov So I'm guessing this is incomplete?:
>Create a Boolean Expression parser to convert the expression into “Boolean” Graph/Tree. Example of expression: {age} >= 21 and ({smoke} == ‘no’ or {beerlover} == ‘no’)

**Comment by andrewtelnov** [comment]
@git2g Sorry, I did not get the question :-(
{age} >= 21 and ({smoke} == ‘no’ or {beerlover} == ‘no’)
The tree is:
<and>
1) {age} >= 21
2) <or>
  2.1) {smoke} == ‘no’
  2.2) {beerlover} == ‘no’

It looks fine to me.

**Comment by varunkumar** [comment]
It would be great to have this expression parser for setValue trigger as well.

**Comment by garybond** [comment]
Does the visibleIf conditional evaluation work where the operator is 'contains'? 
I need to make a question visible if one particular option is selected on a previous multi-select question. I've set it up using the triggers, but I wondered if the expression could be configured at the question rather than at survey level.

**Comment by andrewtelnov** [comment]
Here is the example of using contains:
https://plnkr.co/edit/vNDIFk?p=preview

Thank you,
Andrew
