### ISSUE TITLE
Unable to get HTML values

### ISSUE THREAD

**Issue by lalitkhanna** [surveyjs/surveyjs#602]
### Are you requesting a feature, reporting a bug or ask a question?
While using HTML control in editor, if I inserted like 
 "<"select">"
  <"option value"="volvo">Volvo<"/option">"
   <"option value"="saab">Saab<"/option">"
    <"option value"="vw">VW<"/option">"
   <"option value"="audi" selected>Audi<"/option">"
"</"select">"
After submitting the page, I'm not getting any values out of this.Please let me know.
Please note: While pasting the simple HTML here , complete text is not visible so I put double quote to display the actual values.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@lalitkhanna Please use dropdown question like in [this demo](https://www.surveyjs.io/Examples/Library/?id=questiontype-dropdown&platform=jQuery)

Thank you,
Andrew

**Comment by lalitkhanna** [comment]
This is not about drop down, I wanted to get value from HTML control (Editor) after we submitted.

Thanks
Lalit

**Comment by lalitkhanna** [comment]
https://plnkr.co/edit/41FgURBh0sUrOBUwnd2a?p=preview
Please check this, I've used some HTML control for checkbox but after submission I'm not getting value from HTML control.

Thanks
Lalit

**Comment by andrewtelnov** [comment]
@lalitkhanna Do you mean the results are not posted into the dxsurvey.com?
You have to use surveyPostId as well.
surveyId only load the survey from the service.

Please take a look at JavaScript tab: https://www.surveyjs.io/Examples/Library/?id=service-send&platform=jQuery

Thank you,
Andrew

**Comment by lalitkhanna** [comment]
No, I mean to say if you used HTML control from Editor & you add your some HTML tags in the control, then entering some data in this control after submit we're unable to get values.
In below example we used some checkbox in HTML control , but after submission the form we're not getting any value.

https://plnkr.co/edit/41FgURBh0sUrOBUwnd2a?p=preview

**Comment by andrewtelnov** [comment]
@lalitkhanna I finally got it, after I have looked at the JSON by Guid. 
You can't do it. SurveyJS doesn't control anything that you do in html question. You have to call survey.setValue("yourvalue", valueName); manually.
To be honest we are thinking about put some restriction on using html question.

Why do you use html question? Do you miss just one checkbox with simple Yes/No? We were thinking about adding Boolean question. Will it resolve the issue?

Thank you,
Andrew

**Comment by lalitkhanna** [comment]
Yes, That will solve the problem.Could we've some mechanism in survey to bring our custom control .. which will work simply as given control.

This will bring lot of relief.

Thanks
Lalit

**Comment by andrewtelnov** [comment]
@lalitkhanna We will add Boolean question for sure. There are a lot of scenarios, where it is better then a radiogroup with "Yes"/"No".
About custom widgets - you can use them. There are 12 examples of using different popular js widgets: https://www.surveyjs.io/Examples/Library/?id=custom-widget-select2-tagbox

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@lalitkhanna The QuestionBoolean is in the library now.

Thank you,
Andrew
