### ISSUE TITLE
Is it possible to set the requiredText position after the question?

### ISSUE THREAD

**Issue by vanBersie** [surveyjs/surveyjs#603]
**Question**

There is an option to set the requiredText which is by default '*'. It always appears before the question. I couldn't find an option to make it appear after the question instead of before it. Is there an option like requiredTextPosition or something to set the position or some workaround to force it?
Thanks in advance!

**Comment by andrewtelnov** [comment]
@vanBersie Please use survey.questionTitleTemplate property, here is [the demo](https://www.surveyjs.io/Examples/Library/?id=survey-processtext)

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Here is how you may change the required text:
`survey.requiredText = "😱";`

**Comment by vanBersie** [comment]
@andrewtelnov Awesome, that was what I was looking for. Thank you very much!
