### ISSUE TITLE
Jump back to a previous page depending on how a question is answered

### ISSUE THREAD

**Issue by AndehWong** [surveyjs/surveyjs#604]
### Are you requesting a feature, reporting a bug or ask a question?

Asking a question.

### What is the current behavior?

In my current survey, it's a linear survey where each question leads to the next. The onComplete results in one of two onComplete screens depending on how the user answers the survey questions.

### What is the expected behavior?

I added a question at the end of my survey that tells the user how they answered a specific question. Is it possible to jump back to another page of the survey if the user made a mistake and wants to go back?
This is what I have tried so far:

        survey.onValueChanged.add(function (sender, options){
	        if (options.name === "endOfSurveyCheck" && options.value === "No"){
		        survey.currentPageNo = 1;
	        }
        });

**Comment by dmitrykurmanov** [comment]
@AndehWong, hello! It is possible, please try `survey.currentPageNo = n` And you can find it in the doc: https://surveyjs.io/Documentation/Library/?id=surveymodel (please type "currentPageNo" in search field)

**Comment by dmitrykurmanov** [comment]
@AndehWong, hello! Could you please check this example https://plnkr.co/edit/5zYgb5Rc1jfAyA5U7MgL?p=preview. Will it help you?
