### ISSUE TITLE
bug: requiredErrorText does not actually change displayed text

### ISSUE THREAD

**Issue by enricribas** [surveyjs/surveyjs#605]
### Are you requesting a feature, reporting a bug or ask a question?

bug

### What is the current behavior?

setting 'requiredErrorText' to custom text would display that text

### What is the expected behavior?

it displays 'Please answer the question'

### How would you reproduce the current behavior (if this is a bug)?

create required question with requiredErrorText, then don't answer it and click next

```

### Specify your

* browser:
* browser version:
* surveyjs platform ( react o):
* surveyjs version:

**Comment by dmitrykurmanov** [comment]
@enricribas, hello. I've created an example with react and requiredErrorText and it works. Could you please check it? https://plnkr.co/edit/yE26SBylk2yqYR8QEgsH?p=preview May be you should update surrveyjs version?

**Comment by enricribas** [comment]
upgraded from 0.12.21 to 0.12.23 and it works now. Thanks. Closing...
