### ISSUE TITLE
React version for custom toolbar

### ISSUE THREAD

**Issue by frankwo1** [surveyjs/surveyjs#606]
### Are you requesting a feature, reporting a bug or ask a question?

Question
Can you provide the react version of customizing toolbar? (or assist)
"push" will not work for react

editor.toolbarItems.push({
        id: "custom-preview",
        visible: true,
        title: "Survey Preview",
        action: function() {
            var windowElement = document.getElementById("surveyContainerInPopup");
            var testSurveyModel = new Survey.Model(editor.getSurveyJSON());
            testSurveyModel.render("surveyContainerInPopup");
            $("#modalSurvey").modal("show");
        }

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):react
* surveyjs version:0.12.23

**Comment by dmitrykurmanov** [comment]
moved to editor repo https://github.com/surveyjs/editor/issues/129
