### ISSUE TITLE
Matrixdropdown value null in SurveyData

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#608]
Hi,

i have this case:

- one simple text question
- one matrixdropdown question

if i put a value in simple text question, survey.data at complete was like this:

{"question1":"hello"}

if i delete the value in simple text question, survey.data was like this:

{}

In matrixdropdown i have a problem, also if i don't put value in column, survey data was like this:

{"question1":[{"Column 1":null},{"Column 1":null}]}

why the survey data was compiled with null? there is a possibility to remove question in survey data if it was not compiled?

Thank you

**Comment by andrewtelnov** [comment]
@care46 Sounds as a bug to me.

Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov also with checkbox type, i i flag value and remove flag, survey.data was like this

{"question3":[]}

**Comment by andrewtelnov** [comment]
The fix will be available in the next minor update.

Thank you,
Andrew
