### ISSUE TITLE
How to parameterise question labels or descriptions?

### ISSUE THREAD

**Issue by murrah** [surveyjs/surveyjs#612]
### Are you requesting a feature, reporting a bug or ask a question?
Question

I am brand new to surveyjs and could not find an answer to this. I did look! ;-)

I have a HTML "question" that says "Welcome!" followed by some descriptive text. Is there a standard way in surveyjs to do something like:

"Welcome [firstname]!" and provide an object of parameter values that will substitute before the question renders?

Or do I need to handle that in my "pre-processing"?

Thanks!
surveyjs is very cool!

**Comment by andrewtelnov** [comment]
@murrah Yes, you have to use {} brackets: "Welcome {firstname}!".
Here is [the demo](https://www.surveyjs.io/Examples/Library/?id=survey-processtext).

Thank you,
Andrew

**Comment by murrah** [comment]
Awesome! Sorry I missed that in the examples.

So, to do what I needed was slightly more complicated but it works:

1. I added a text question to the survey with a name of "firstname", and set its visibility to `false`.
2. After loading the JSON from my server but before displaying it I set the answer to the `firstname` question to the participants's name:
eg `surveyModel.setValue("firstname", myServerRec.firstname);`
3. Added the {firstname} token eg "Welcome {firstname}!" or in question description text "{firstname}, please tell us ...."

Voila!
Thanks,
Murray

**Comment by andrewtelnov** [comment]
@murrah you do not need the text question.
surveyModel.setValue() is enough.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
I would suggest to use setVariable
surveyModel.setVariable("firstname", myServerRec.firstname);
The difference between variable and value - variable will not exist in survey.data - JSON result.

Thank you,
Andrew

**Comment by murrah** [comment]
Even more awesome!

Yes, I removed the hidden "question" then simply called `surveyModel.setVariable("firstname", myServerRec.firstname);` 

Thanks again Andrew!
Go well,
Murray

**Comment by murrah** [comment]
I have just come back to this and it seems that `setVariable()` does not set parameters in description fields. html and title fields, yes, but not description. Is that correct or am I missing something?

Thanks again,
Murray

**Comment by andrewtelnov** [comment]
@murrah Yes, indeed. There is a bug.
I have fixed it: https://github.com/surveyjs/surveyjs/issues/632
We will release the next minor likely tomorrow.

Thank you,
Andrew

**Comment by murrah** [comment]
Brilliant! Thank you Andrew for the fast response.
