### ISSUE TITLE
custom Html output

### ISSUE THREAD

**Issue by AvinashVarmaSagi** [surveyjs/surveyjs#613]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?
We had Html control and i am putting input tag as checkedbox. i need to find value of checked in html.

### What is the expected behavior?
how to fetch value in html control.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:https://surveyjs.io/Editor/Editor/#1a13c97f-26cd-41ac-ba69-7af60ddd9251

Test code

```
your_code_here

```

### Specify your

* browser:chrome
* browser version: Version 60.0.3112.113
* surveyjs platform : jquery 
* surveyjs version:

**Comment by andrewtelnov** [comment]
@AvinashVarmaSagi Somebody from your team has already asked this question. If you go with html control and pure html, you are on your own. Use survey.setValue and survey.getValue functions, here is [the demo](https://www.surveyjs.io/Examples/Library/?id=survey-data&platform=jQuery).
You may wait until we implement [QuestionBoolean](https://github.com/surveyjs/surveyjs/issues/610). We are working on it.

Thank you,
Andrew
