### ISSUE TITLE
How to set Header & Footer while Printing

### ISSUE THREAD

**Issue by lalitkhanna** [surveyjs/surveyjs#614]
### Are you requesting a feature, reporting a bug or ask a question?
I'm printing the survey page with header footer but getting great difficulties to that .Do we have some example to perform this.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@lalitkhanna To be honest, I think that is not what SurveyJS library does. I believe you will find or get an answer faster on stackoverflow.com.

Thank you,
Andrew
