### ISSUE TITLE
Choices restfull: other properties from json response are not available in afterRender method

### ISSUE THREAD

**Issue by gaurav-singhal** [surveyjs/surveyjs#615]
### Are you requesting a feature, reporting a bug or ask a question?
Not sure: probably a feature or question

### What is the current behavior?
https://github.com/surveyjs/surveyjs/issues/559
The answer mentioned in the thread works fine if we go with choices but what if we are using choicesByUrl (Choices Restfull). Then the group is not available in afterRender method. How can we access those in afterRender method?

> There is another available way to set group option:
> 
> ```
> { type: "checkbox", name: "choosepicture", renderAs: "imagepicker", title: "What animal would you like to see first ?", 
>      choices: [
>         {value: "lion", group: "g1", text: "http://surveyjs.org/images/image-picker/lion.jpg"},
>         {value: "giraffe", group: "g2", text: "http://surveyjs.org/images/image-picker/giraffe.jpg"},
>         {value: "panda", group: "g3", text: "http://surveyjs.org/images/image-picker/panda.jpg"},
>         {value: "camel", group: "g2", text: "http://surveyjs.org/images/image-picker/camel.jpg"}
>      ]
>   }
> ```
> This option will be available in the afterRender function of the custom widget:
> 
> ```
> afterRender: function(question, el) {
>     // question.choices[0].group // - will return "g1"
> ```
> 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@gaurav-singhal I am going to work on improvement ItemValue class, It uses in choices, matrix columns/rows.
Our customers want to extend ItemValue and be able to edit the additional properties inside the Property Editor / Question Editor.

Thank you,
Andrew

**Comment by gaurav-singhal** [comment]
Thanks Andrew. Will look forward to it. If we can assign an object just like in choices in ItemValue. That will serve the purpose.

**Comment by andrewtelnov** [comment]
@gaurav-singhal I am going to work on [this functionality](https://github.com/surveyjs/editor/issues/132), right now.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@gaurav-singhal I have implemented this functionality. You will have to add a new property into itemvalue class: 
`Survey.JsonObject.metaData.addProperty("itemvalue", "myCustomProperty");`

Thank you,
Andrew

**Comment by gaurav-singhal** [comment]
Thanks!

**Comment by gaurav-singhal** [comment]
The latest build 0.12.34 is not supporting this and value returned is undefined.

**Comment by andrewtelnov** [comment]
@gaurav-singhal Choices restfull doesn't work correctly for your code. I have fixed this issue. The next version should be fine.

Thank you,
Andrew
