### ISSUE TITLE
How to apply Styles

### ISSUE THREAD

**Issue by AvinashVarmaSagi** [surveyjs/surveyjs#619]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

Enable to apply styles.

### What is the expected behavior?
How to apply style to each html.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform :jquery
* surveyjs version:

**Comment by dmitrykurmanov** [comment]
@AvinashVarmaSagi, hello please check these examples:
https://surveyjs.io/Examples/Library/?id=survey-customcss&platform=jQuery
https://plnkr.co/edit/aIz4bdA0pFVw7WttInVF?p=preview

**Comment by dmitrykurmanov** [comment]
the same question https://github.com/surveyjs/editor/issues/131
