### ISSUE TITLE
Keyboard control is different for checkboxes and radios

### ISSUE THREAD

**Issue by mattes3** [surveyjs/surveyjs#62]
When I use the TAB and CURSOR-DOWN keys in my Chrome browser on the Mac, I get different results for checkboxes and radio groups.

In a checkbox...
- TAB key goes to the next checkbox in the same group
- CURSOR-DOWN key stays on the same checkbox but scrolls the window up

In a radiogroup...
- TAB key jumps out of the radiogroup, into the next question
- CURSOR-DOWN goes to the next radiobutton in the same group

As a user, I expect that both radiogroup and checkbox behave the same way.

**Comment by andrewtelnov** [comment]
Unfortunately, I am not sure that it is a bug. It is a standard behavior of these html elements.
[Please take a look at this](https://jsfiddle.net/AndrewTelnov/aa00n3Lh/)
Unless, I have missed something, I would stick with the default behavior. If there are some attributes, that I have to set, I may play with them.

Thank you,
Andrew
