### ISSUE TITLE
One field validation

### ISSUE THREAD

**Issue by obitohub** [surveyjs/surveyjs#623]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
By using "validators": [{ type: "numeric" }] e.g. fields are validated only after clicking "complete" or "next" button.

### What is the expected behavior?
I want to validate particular field on Survey.SurveyQuestionText.prototype.handleOnBlur or on Survey.SurveyQuestionText.prototype.handleOnChange so that you don't have to finish all first page and validate it on the fly.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by dmitrykurmanov** [comment]
@obitohub hello! Could you please check the example: https://plnkr.co/edit/v3XldtmTbFeYEzhWBrg4?p=preview ?

**Comment by obitohub** [comment]
Thanks, but is it possible to validate only one value because now it gets validated on all current page and other fields are also validated ?

**Comment by dmitrykurmanov** [comment]
@obitohub sure you could do something like this: 
```
survey.onValueChanged.add(function(survey, options) {
  var q = options.question;
  if (q.name === "email") {
    options.question.hasErrors();
  }
});
```

and I've updated the plunker https://plnkr.co/edit/v3XldtmTbFeYEzhWBrg4?p=preview

**Comment by andrewtelnov** [comment]
@obitohub I have corrected the @dmitrykurmanov plunker example: https://plnkr.co/edit/Bn1KHaDFQDmdt0ruBark?p=preview

It should be correct now.
I think we will add an option, so the library may optionally call validation on value change.

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
@andrewtelnov , @obitohub oh yes, I am sorry I've forgot update my plunker. Fixed version (validation only one question by name) https://plnkr.co/edit/sEkM583IkhgGDxkfucjf?p=preview

**Comment by obitohub** [comment]
Thank you very much guys for the effort you are doing :) The most precise answer is from @andrewtelnov because in @dmitrykurmanov answer and example the code is hardcoded to check email while on @andrewtelnov validation is done on particular field but not hardcoding it with the name itself - that is exactly what I strived for. Thank you again guys :)

**Comment by dmitrykurmanov** [comment]
@obitohub ok please feel free to reopen the issue or create new one for ask additional questions.
