### ISSUE TITLE
I am using dynamic panel in my survey but after completing survey its just showing data from dynamicpanel in result json, fields before it are not coming in json.

### ISSUE THREAD

**Issue by manoj-negi** [surveyjs/surveyjs#626]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@manoj-negi There are here. Here is demo: https://plnkr.co/edit/5AhEXAi6t2LBCl9YHbmy?p=preview
For some reason they are not before panel, but after.
Is it important for you? If yes, we take a look later.

Thank you,
Andrew

**Comment by manoj-negi** [comment]
Not much important but may be in future. Actually i am making excel file from data for my client, and the dynamic panel data depends on the previous fields, so that. Anyway thanx for your help.

**Comment by manoj-negi** [comment]
Not much important but may be in future. Actually i am making excel file from data for my client, and the dynamic panel data depends on the previous fields, so that. Anyway thanx for your help.

one more thing , is there anyway to get title also with name and value of question in result json.

**Comment by andrewtelnov** [comment]
@manoj-negi Sorry, we have missed the question. 
You may always go through your survey data, like
```
var data = survey.data;
var newData  = {};
for(var key in data) {
  var q = survey.getQuestionByValueName(key);
  var title = q ? q.title : key;
  newData[key] = {value: data[key], title: title;
}
```

Thank you,
Andrew
