### ISSUE TITLE
Support cascading dropdown with restful API in matrix row

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#627]
You may refer to the column value of the same row with "row." prefix. Here is the example:
```
{ type: "matrixdynamic", name: "salesByCountry", title: "Please set sales by country", addRowText: "Add new Country",
        columns: [{ name: "region", title: "Region", isRequired: true,  choices: ["Africa", "Americas", "Asia", "Europe", "Oceania"]},
        { name: "country", title: "Select the country...", isRequired: true, 
         choicesByUrl: {url: "https://restcountries.eu/rest/v2/region/{row.region}", valueName: "name"} },
            { name: "sales", cellType:"text", isRequired: true, inputType:"numeric", title: "Sales" }],
        rowCount: 2}
```

**Comment by masciugo** [comment]
I am trying to do the same but with panel dynamic. The restful request to pupulate the second dropdown does not seem to take the correct parameter (titleName insted of valueName) from the first dropdown

https://plnkr.co/edit/sv6pYceDt00QFhupVfTW?p=preview

**Comment by andrewtelnov** [comment]
@masciugo Hm... It looks like a bug to me. I will investigate it.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@masciugo Thank you for reporting this issue to us. [It has been fixed](https://github.com/surveyjs/surveyjs/issues/996). A Unit test has been added.
The fix will be available in the next minor update on the next week.

Thank you,
Andrew
