### ISSUE TITLE
How to change Message "Thank you for completing the survey!" after completing the survey.

### ISSUE THREAD

**Issue by syash2015** [surveyjs/surveyjs#629]
### Are you requesting a feature, reporting a bug or ask a question?
How to change Message "Thank you for completing the survey!"

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@syash2015 Please use survey.completedHtml. Take a look at [this demo](https://www.surveyjs.io/Examples/Library/?id=survey-processtext)

Thank you,
Andrew

**Comment by yangxu698** [comment]
Hello, I'm now using surveyJs creator to create survey, in the meantime, I'm checking the survey through the tab of "Test Survey" when still composing survey, is there a way to change the "Thank you for completing the survey!" text during stage of survey create? I know the demo above is for the mode: window.survey = new Survey.Model, which is more of when conducting survey.
![Screenshot from 2019-11-11 10-53-12](https://user-images.githubusercontent.com/29738383/68601138-c0c25c00-0471-11ea-9bdf-9abab56ccc4c.png)

var options = {
    showLogicTab: true
};
var creator = new SurveyCreator.SurveyCreator("creatorElement", options);

Thanks.

**Comment by deepika231-max** [comment]
Hello @yangxu698 ,
I am also looking for a way to change "Thank you for completing the survey!" text during stage of survey create? If you got to know any work around. Can you please help me regarding this.
![Surveytextch](https://user-images.githubusercontent.com/60771969/74009323-f27f8c00-49a8-11ea-8e77-8c5c81c5dd06.png)

Thanks.

**Comment by andrewtelnov** [comment]
@yangxu698 @deepika231-max You are talking about SurveyJS Creator, it is another library. 
You can change the default localized string for "completingSurvey":
```js
var myloc = Survey.surveyLocalization.locales["localename"];
myloc.completingSurvey= "Your text on completing survey";
```
For more information, please read [localization documentation topic](https://surveyjs.io/Documentation/Library/?id=LibraryOverview#localization)

Thank you,
Andrew

**Comment by ssukienn** [comment]
Is it possible to render something more than text with preprocessing from the survey. I am talking about complete React components or in general styled HTML with some handlers onClick etc.

Thank you

**Comment by andrewtelnov** [comment]
@ssukienn You can simply hide react survey component onComplete event and show any react component you want.

Thank you,
Andrew

**Comment by ssukienn** [comment]
Actually, I was doing something alike but was wondering if there is a build-in option for it. But the one you mentioned is also fine. Thanks.

**Comment by alescanog** [comment]
I found a way to change the message. I downloaded the file "...survey.jquery.min.js", searched and found the text in the file and replaced it. Then I uploaded the new file to my site and replaced the "src" tag wherever it was mentioned. Works like a charm...
