### ISSUE TITLE
Signature pad state

### ISSUE THREAD

**Issue by AvinashVarmaSagi** [surveyjs/surveyjs#630]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?

State of Signature pad not maintaining  when we move to next page and coming back this signature page.

### What is the expected behavior?

How to maintain state for signature pad.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
We have to update our example.
Please use the code from this [plunker demo](http://plnkr.co/edit/g84DjANkKr7AGHA2hWGW?p=preview)

Thank you,
Andrew

**Comment by AvinashVarmaSagi** [comment]
https://plnkr.co/edit/aIz4bdA0pFVw7WttInVF?p=preview

**Comment by dmitrykurmanov** [comment]
@AvinashVarmaSagi hello! Do you mixed up the issue? Or why did you post the example above? It is example of "CssClasses" feature. 

Thanks.

**Comment by tscott1213** [comment]
If I attempt to use this custom widget in the survey editor the "afterRender" function fails because el.querySelector("canvas") returns null. I'm not sure why....

**Comment by tscott1213** [comment]
I was able to determine why the querySelect returns null in the survey editor.   When added to a Survey the el that is passed to "afterRender" is the div that contains the canvas specified in the "htmlTemplate" parameter.  However, in the SurveyEditor (when both designing and testing a survey) the el that is passed to "afterRender" contains the canvas element.  This inconsistency appears to be a bug, but I'm not which behavior is correct.

The widget will work in both the SurveyEditor and the Survey by making the following change in the afterRender function:
      var canvas = el.querySelector("canvas");
      if(canvas === null) {
        canvas = el;
      }
By checking if the canvas is null and then setting the canvas to the passed in element, this custom widget will work in the SurveyEditor.

I am happy to create a plunker demo if that is helpful.  It does appear to be a bug in terms of consistency between the two projects.

Thank you.
Todd

**Comment by dmitrykurmanov** [comment]
@tscott1213 sorry for the late answer, we've released new custom widgets scructure. Please check https://surveyjs.io/Examples/Library/?id=custom-widget-signaturepad&platform=jQuery . If the bug still exists, please create a plunker with it. Thank you.
