### ISSUE TITLE
Input fields allowed symbols length

### ISSUE THREAD

**Issue by obitohub** [surveyjs/surveyjs#631]
### Are you requesting a feature, reporting a bug or ask a question?
feature

### What is the current behavior?
Currently user can input any number of symbols into input fields.

### What is the expected behavior?
It should be possible to limit how many symbols are allowed to enter into input fields like its done in html: <input type="text" name="usrname" maxlength="10"> (https://www.w3schools.com/tags/att_input_maxlength.asp). Template for html should be edited to have this feature.

**Comment by mellogarrett** [comment]
Can we change the language from "symbols" to "characters"? 

Also, there should be a live character counter on the question to show them what character count they are at.

**Comment by andrewtelnov** [comment]
@mellogarrett changed.

Thank you,
Andrew
