### ISSUE TITLE
matrixdynamic text Change event

### ISSUE THREAD

**Issue by AvinashVarmaSagi** [surveyjs/surveyjs#633]
### Are you requesting a feature, reporting a bug or ask a question?
question
### What is the current behavior?

matrixdynamic  i had textbox when i focus out i need to check validate given text in the textbox if it not valid text i need to clear that.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@AvinashVarmaSagi Here is the event you have to use: https://www.surveyjs.io/Documentation/Library/?id=surveymodel#onMatrixCellValueChanged

Thank you,
Andrew
