### ISSUE TITLE
Uploading file along with other question

### ISSUE THREAD

**Issue by deepakjain2502** [surveyjs/surveyjs#634]
### Are you requesting a feature, reporting a bug or ask a question?
feature

### What is the current behavior?

Currently, the file upload is a type of question. However, it is generally a supporting document for an answer

### What is the expected behavior?

We should allow file upload to any type of question. E.g. we can have radio button, text and checkbox type of question but these should allow file upload as well along with answering the question. This would be similar to HTML type,which can be attached to any question.

### How would you reproduce the current behavior (if this is a bug)?

NA

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version:

**Comment by dmitrykurmanov** [comment]
@deepakjain2502, hello! What about using any question with the file question but with the same name? May be this workaround is ok for you?

**Comment by deepakjain2502** [comment]
Hi,

Thanks for response,

No, that might not work, it would be confusing for user, as question numbering would be different. Also the backend data would be saved without relation and we might not use it for backend processing.

**Comment by dmitrykurmanov** [comment]
@deepakjain2502 may be it would be something like common "alternative question" feature? Just possibility to add alternative question of any type to question of any type. What do you think?

**Comment by deepakjain2502** [comment]
You mean a child question? thats a bit of workaround but not the right solution. As file is linked with question and not with a response per say

**Comment by dmitrykurmanov** [comment]
@deepakjain2502 not worlaround but new feature. I think it could be more common solution than just _file_

**Comment by deepakjain2502** [comment]
Not sure how are you perceiving the "alternative question", but if we look into survey, its always question answer and sometime a proof to substantiate the answer we are providing. The answer could be in the form of attachment (document) or a "data form". Data form is just a form with data which can be attached to a question

**Comment by deepakjain2502** [comment]
Hello, do you think anyway of doing this? Or any plan to add these features?

**Comment by andrewtelnov** [comment]
@deepakjain2502 Do be honest I do not think we will implement it in the near future. As I see it, you have a pretty unique scenario.
However, you may use the afterQuestionRender event or custom widget to implement this functionality.
I think we will be able to create an example on the next week, if you have a problem to do it by yourself. Just ping us in the middle next week. It will be cool if you show us UI you want to implement.

Thank you,
Andrew

**Comment by deepakjain2502** [comment]
Hi Andrew,

 

I could not understand the implementation, if you can please guide with some examples? I do not have a UI in mind, but if we have a question and on right side of question an icon to upload a file.

 

Thanks,

Deepak Jain | Subtlelabs Technologies Pvt. Ltd | Phone: +91-9818542953 | Email: deepak.jain@subtlelabs.com |  <http://www.subtlelabs.com> www.subtlelabs.com

logoFinal_RGB(web&video_purposes).png

**Comment by andrewtelnov** [comment]
@deepakjain2502 Here is the example: https://plnkr.co/edit/xsdl0DoNRIaGGvWluRhQ?p=preview
I may add the property, showTitle (true by default). So you will be able to hide the title of the question. In you case for the file type question.
Let me know is it any close to what you have in your mind?

Thank you,
Andrew
