### ISSUE TITLE
 Input question of "inputType" property "numeric" does not report error on non-numeric input.

### ISSUE THREAD

**Issue by abolger** [surveyjs/surveyjs#635]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug. 

### What is the current behavior?
In survey editor, if the property for a single input question is set to "numeric" (rather than the default of "text"), the question allows the text entry of other data, but then does not tell the user there is a problem.  The question DOES prevent the text data from being sent to the server (which is good), but the user does not get a validation error (which is bad). 

### What is the expected behavior?
The question should prevent the text data from being sent to the server AND display an error message that the data entered is invalid. Alternately, questions of input type numeric should not allow text entry. 

### How would you reproduce the current behavior (if this is a bug)?
Create a question with the following JSON: 
{
     type: "text",
     inputType: "number",
     name: "test",
     title: "Enter text here and see what happens."
    }

On the survey test page in the editor, test this question by entering text characters into the field and click 'complete'. You will not get a red invalid/error message.

### Specify your

* browser: Firefox 
* browser version: 54.0.1
* surveyjs platform: knockout
* surveyjs version: 0.12.23

**Comment by andrewtelnov** [comment]
@abolger Please use the "number" validator. Here is the [plunker demo](https://plnkr.co/edit/mqte6NBCeZAfEKPRqnoe?p=preview).

Thank you,
Andrew

**Comment by abolger** [comment]
That plunker demo demonstrates my *exact* reported problem, including use
of validator. I entered the data "test" in the number field and the numeric
validator did NOT report a problem.  This clearly happens because of what I
stated in the report: the number input type field clears the input instead
of returning it to the server. The means that the validator passes when it
should fail, likely*, *because the validator is being run on an empty
field. This is bad because the user doesn't know that their data is
invalid, or that is has been cleared before being sent to the
server/database.

**Comment by andrewtelnov** [comment]
@abolger What browser and what version do you use? It works fine in Chrome.

Thank you,
Andrew

**Comment by abolger** [comment]
Quick note on my testing: to use your plunker I had to change the
isRequired flag to get the results I'm having (otherwise you get the "this
field is required message" when you enter text, which is it's own confusing
error message).  I have attached screenshots of both cases on Firefox and
Chrome- 1 when "isRequired" = true, and 1 when "isRequired"=false.

I have tried it and the test failed,\ on Firefox 54 and on Safari 9.1.3.
When I try on Chrome, I technically get the same error, but the Chrome
number input does what I want and prevents me from entering non-numeric
characters (except, apparently, for the letter 'e').  In chrome, I can
enter in the letters "eeeeee" into the number field and submit
successfully.  So in this case, it seems a way to fix it is to fix the
"number" input type on Firefox and Safari to disallow non-numeric
characters.

**Comment by andrewtelnov** [comment]
@abolger I will think how to solve the issue. The problem that input in a browser returns undefined/empty value. There are a lot of discussion on the web about this issue.
To be honest, I do not understand, why type="numeric" doesn't handle correctly by the most of browsers. 
We will think about the solution. 

PS: 'e' is valid because 1e2 is a valid number, it equals 10^2 = 100. 

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@abolger I do not see any good solution so far.
What if we add a custom widget: mask, based on [vanilla-masker](http://vanilla-masker.github.io/vanilla-masker/). What do you think?

Thank you,
Andrew

**Comment by abolger** [comment]
That would be great. My workaround so far has been to change the inputType back to text- it’s not ideal because then the user doesn’t get a number picker widget, but they do then get an error when they type in invalid input. 

Adrienne

**Comment by dmitrykurmanov** [comment]
@abolger we've implemented it in https://github.com/surveyjs/surveyjs/issues/567, please check it.

**Comment by ZakMiller** [comment]
This bit me really badly. Is there a way to allow all data through if it makes it past the frontend validation layer @andrewtelnov ? Data was lost even though from the entry side it looked like everything was fine.

**Comment by andrewtelnov** [comment]
@ZakMiller It an old issue. Here is the example with [the latest version](https://plnkr.co/edit/GitAMEwUwOVrjfxQ).
In the version we are going to release tomorrow, then user will not be able to enter values that less than `min` and greater than `max` properties.

Thank you,
Andrew
