### ISSUE TITLE
Add a span and class around required asterisk

### ISSUE THREAD

**Issue by enricribas** [surveyjs/surveyjs#636]
### Are you requesting a feature, reporting a bug or ask a question?

feature

### What is the current behavior?

displays an asterisk

### What is the expected behavior?

displays an asterisk with a span and class of required

### Reason
Unfortunately, we need to hide the asterisk or potentially change it to something else. I don't agree with this decision but that's our requirement. Because it is not wrapped in any way, it's very difficult to remove it without removing all the text of the title.

**Comment by andrewtelnov** [comment]
@enricribas There is the [survey.requiredText property](https://www.surveyjs.io/Documentation/Library/?id=surveymodel#requiredText), it is "*" by default.
However in your case I would change the survey.questionTitleTemplate property.
Here is [the demo](https://www.surveyjs.io/Examples/Library/?id=survey-processtext) where you may play with all properties.
Just click on "Edit in Plunker" and change the questionTitleTemplate to "{no}. {title}:".

Thank you,
Andrew

**Comment by enricribas** [comment]
Amazing! Thanks, missed that in the docs.

**Comment by ElitekrishnaRao** [comment]
I added it  requiredText: "<b>(*)</b>", like this but this html did not go parsed insted showed it as is

**Comment by andrewtelnov** [comment]
@ElitekrishnaRao It works as expected. Here is [the example](https://plnkr.co/edit/DIM1sTlp3GLKxA42FnQZ?p=preview).

Thank you,
Andrew
