### ISSUE TITLE
Can we have hybrid sequence number of question and panel?

### ISSUE THREAD

**Issue by deepakjain2502** [surveyjs/surveyjs#637]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

Can we sequence a panel as one question. E.g. if we have 4 questions and last 2 questions are in a panel, can we have the sequence as 1,2,3 where 3 is the sequence for panel. So that user will get impression tha last two questions are required to answer third question?

### What is the expected behavior?

NA

### How would you reproduce the current behavior (if this is a bug)?

NA

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@deepakjain2502 Right now there is no this functionality. However, I may do a trick with dynamic panel.
You will have to set the panelCount, minPanelCount and maxPanelCount properties to 1. In this case there will be no navigation through panels (panelCount is 1) and buttons for adding/removing panels will be invisible as well. Here is [the example](https://plnkr.co/edit/pBpoiPVhBqJ6nagC8VWC?p=preview),
However, the data will be store as: `panelName: {question1: value1, question2:value2}`.
Let me know if this solution works for you.

Thank you,
Andrew

**Comment by deepakjain2502** [comment]
That will do the trick. Thanks a lot J

 

Thanks,

Deepak Jain | Subtlelabs Technologies Pvt. Ltd | Phone: +91-9818542953 | Email: deepak.jain@subtlelabs.com |  <http://www.subtlelabs.com> www.subtlelabs.com

logoFinal_RGB(web&video_purposes).png
