### ISSUE TITLE
Allow File type as option in dynamic row?

### ISSUE THREAD

**Issue by siberian1967** [surveyjs/surveyjs#641]
### Are you requesting a feature, reporting a bug or ask a question?

Feature

### What is the current behavior?

Unsupported

### What is the expected behavior?

It would be great to allow for a user to add multiple files to a question. We have a need to gather supplemental content to support questions and that content can be many different files. Our users are not good at zipping files up. Currently File is not a supported type for dynamic rows.

**Comment by andrewtelnov** [comment]
@siberian1967 How do you want to store the data? Inside the row as text, file question has the storeDataAsText property, or handle it on event?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@siberian1967 In the current version you may add the following code:
```
        Survey.matrixDropdownColumnTypes.file = {
            properties: ["showPreview", "imageHeight", "imageWidth"]
        };
```
After that you get the file cell type.

Thank you,
Andrew

**Comment by sanjayksuthar** [comment]
@andrewtelnov 
Hi, i have a issue in this, in my survey i have create a question type of matrixdropdown and create two columns 1 is text and 2nd is file type but when i try to add property to store file using api then it not working it always storedata as text in response json. when i try same on file type question then it work but on column type file is not working. can you help me in this.

this is my code :


var json = {
    questions: [
        {
            type: "matrixdynamic",
            name: "sendHomework",
            title: "Please send your homework",
            addRowText: "Add Subject",
            columns: [
                {
                    name: "file",
                    "cellType": "file",
                    title: "Please upload your document",
            storeDataAsText: false,
            showPreview: true,
            imageWidth: 150,
            maxSize: 102400
                }, {
                    name: "description",
                    cellType: "comment",
                    title: "Please describe your homework"
                }
            ],
            rowCount: 1
        }
    ]
};



survey
    .onUploadFiles
    .add((survey, options) => {
        var formData = new FormData();
        options
            .files
            .forEach(function (file) {
                formData.append(file.name, file);
            });
    });

**Comment by andrewtelnov** [comment]
@sanjayksuthar You should add this property into string array:
```
       Survey.matrixDropdownColumnTypes.file = {
            properties: ["storeDataAsText", "showPreview", "imageHeight", "imageWidth"]
        };
```

Thank you,
Andrew

**Comment by sanjayksuthar** [comment]
@andrewtelnov 
after add this code it working fine.
**Thanks you**

I have a another query is there any option to render 1st column in one line and 2nd column in another line.


Thanks

**Comment by andrewtelnov** [comment]
@sanjayksuthar Please create a new issue.

Thank you,
Andrew
