### ISSUE TITLE
Expression Parser - support native Boolean Lang

### ISSUE THREAD

**Issue by eladh** [surveyjs/surveyjs#643]
### Are you requesting a feature, reporting a bug or ask a question?

A feature.

### What is the current behavior?
Following our last conversion.
Our system using surveyjs as a generic engine to display questionnaires based on client and server state.
we using Internal Rule Engine that parse the VisibleIf expression and evaluate part of it in the server side.
in this case the server return native Boolean values such as true / false  and some part of the expression will be evaluated in the client side by surveyjs.

for example : (**~4424**()>5) &&  ({question2} = 3 and {question3} < 5)
the server will evaluate it to : true &&  ({question2} = 3 and {question3} < 5)

### What is the expected behavior?
the expected  behavior will support a native Boolean language true/false - 1/0  

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by eladh** [comment]
hi @andrewtelnov 

following up on this issue we also have issue regarding the **equals operator** on **checkbox**, 
we developing MD editor that super users will be able to assign rules to the questions and in 
checkbox its confusing because the users has to use **contains()** function and not the equals operator.

my question - is it possible to support also **== (equals)** operator when evaluating on **checkbox** as a **contains()** function ? 

best,
elad.

**Comment by andrewtelnov** [comment]
@eladh Do you mean if the constant is not an array, then deal with "equals" operator as "contains"?
I think it is better to give the ability to override the operator as you wish. The only problem, you need it only for arrays. Let me think...

I will probably add it the functionality by Monday, but if not, please ping me.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@eladh Another suggestion, what if I would add *= . It would  means **contains**.
Will it helps?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
I have added '*=' support event if it doesn't help you.

Thank you,
Andrew
