### ISSUE TITLE
No posibility to set visibility on whole panel

### ISSUE THREAD

**Issue by obitohub** [surveyjs/surveyjs#644]
### Are you requesting a feature, reporting a bug or ask a question?
feature

### What is the current behavior?
Only seperate elements like radiobuttons, checkboxes, input fields, etc. could be made as visible/not visible but not panel with all elements in it.

### What is the expected behavior?
When registering trigger I expect to be able to make panel visible/not visible when clicking checkbox:
"triggers": [
        {
            "type": "visible",
            "name": "PT2",
            "operator": "equal",
            "value": "Y",
            "questions": [
                "PT2_panel"
            ]
        }
],
"pages": [
       {
            "type": "panel",
            "innerIndent": 1,
            "name": "PT2_panel",
            "visible": false,
            "elements": [
                ..........................................
            ]
       }
]

**Comment by obitohub** [comment]
@andrewtelnov just wondering is it fixed in 26 release and if so then PT2_panel hides all the elements inside when setting visible to false but trigger visible doesn't respond on "questions": ["PT2_panel"] and on clicking checkbox elements does not appear. Maybe property "questions" is not right in trigger because its not a question ? Also this issue is related to https://github.com/surveyjs/surveyjs/issues/656 which is not released. When can we expect release 27 ?

Thank you.

**Comment by andrewtelnov** [comment]
@obitohub I am not sure I quite understand you. From v0.12.26 you are able to add panel into the list. It calls now "Make elements visible" and list all questions and panels.
We will likely release a new version on this week.

Thank you,
Andrew

**Comment by obitohub** [comment]
@andrewtelnov here is an example to my question:
https://plnkr.co/edit/hOwjIXNw9cWuuvBEaOiq?p=preview

If we make "QR5_SP" field as visible: false then checkbox "SN10" and its trigger works, that is hides/shows element. If we put visible: false on PT2_panel and do the same thing with trigger then first time all elements on panel are hidden (right behaviour) and clicking checkbox "SN10" it no longer appears. So again, maybe trigger with "questions": ["PT2_panel"] is not right thing to do because panel is not a question or maybe its not implemented ? Or maybe there is another solution to this problem because I don't want to add 30 visible: false properties on each element in panel and describe all of them in trigger. Hope you get my point.

Thank you,
Tomas.

**Comment by obitohub** [comment]
Found the solution by not using trigger for panel but putting "visibleIf": "{SN10}='Y'" condition to PT2_panel itself. Thank you for colloboration.
