### ISSUE TITLE
requiredText can't be empty

### ISSUE THREAD

**Issue by balping** [surveyjs/surveyjs#646]
In commit https://github.com/surveyjs/surveyjs/commit/d71906247e7575f1eec714f281e814bc68865606 this line was added: 

https://github.com/surveyjs/surveyjs/blob/d71906247e7575f1eec714f281e814bc68865606/src/base.ts#L129

Before that it was possible to set `requiredText` to an empty string, but now if I do that , `* ` is displayed, which is not surprising given the above line.

My workaround to hide the asterisk  is  setting `requiredText` to the unicode character 'ZERO WIDTH SPACE' (U+200B).

However given the line below, an unnecessary space is added anyway, which causes an ugly little indent in a required question's title.

https://github.com/surveyjs/surveyjs/blob/ec7837d4b123339f0ea617a318d09f77385ce3d9/src/question.ts#L121

My suggestion is to add a `showRequiredText` parameter which  when set to false, hides the asterisk and the extra space character.

**Comment by andrewtelnov** [comment]
@balping Yes, I see the issue. 
Could you use the follwoing code:` survey.questionTitleTemplate = "{no}. {title}:";`

Thank you,
Andrew

**Comment by balping** [comment]
This works, thank you.
