### ISSUE TITLE
Zero values get blanked out

### ISSUE THREAD

**Issue by enricribas** [surveyjs/surveyjs#647]
### Are you requesting a feature, reporting a bug or ask a question?

Seems like a minor bug

### What is the current behavior?

with fields, even if they are required or have validation, when you enter a zero ie 0 the answer gets displayed as a blank field. It validates fine which is related to previous bug https://github.com/surveyjs/surveyjs/issues/345
but the zero disappears and the field looks blank

### What is the expected behavior?

The input that I entered should display in the field

### How would you reproduce the current behavior (if this is a bug)?

make a field, enter a zero, tab to another field, zero disappears

UPDATE: This doesn't seem to happen on the online editor when you run it so it's most likely a react-surveyjs thing.

Thanks

**Comment by andrewtelnov** [comment]
@enricribas It is fixed.

Thank you,
Andrew

**Comment by enricribas** [comment]
Wow! Thanks.
