### ISSUE TITLE
Using ES6 import on survey-jquery - return Survey is not defined

### ISSUE THREAD

**Issue by eladh** [surveyjs/surveyjs#649]
### Are you requesting a feature, reporting a bug or ask a question?

bug / questions

### What is the current behavior?

We integrate survey JQuery version with angularJS 1 + webpack infrastructure

1. we added a resolve alias 
2. import 'survery-jquery' in the relevant point

we some how missing the proper injection point to how to expose Survey infrastructure via webpack.

in our case we getting Survey is not defined

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by dmitrykurmanov** [comment]
@eladh hello! Did you try to import SurveyJS like that: `import * as Survey from 'survey-jquery';` ?

**Comment by eladh** [comment]
hi @dmitrykurmanov  

yes , and still got the same error

10x

**Comment by dmitrykurmanov** [comment]
@eladh, I've reproduced the problem, thank you!

**Comment by dmitrykurmanov** [comment]
@eladh as a workaround you can use `import Survey from 'survey-jquery';`

**Comment by dmitrykurmanov** [comment]
@eladh in fact I've done error and the problem was reproduce. And the error was in class name. I've named my class same as import object. So I've fixed this error and it works fine. Please checj the example:

https://stackblitz.com/edit/react-zcj5kb?file=SurveyComponent.js

PS (Survey => SurveyComponent class name). Please notify if it helps or not.

**Comment by eladh** [comment]
thanks @dmitrykurmanov

**Comment by legreco** [comment]
I have the same problem, i tried
```
import * as Survey from 'survey-jquery';
```
but it doesnt work

**Comment by dmitrykurmanov** [comment]
@legreco, what version of the surveyjs do you use?

**Comment by legreco** [comment]
I am using survey-jquery@0.12.34.
