### ISSUE TITLE
Select2 widget overrides another answer data when used on several pages

### ISSUE THREAD

**Issue by nikitakarpenkov** [surveyjs/surveyjs#654]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

Select2 widget data value gets overridden by another select2 widget data value from another page.
Question names are different.

### What is the expected behavior?

Each widget to update related value only.

### How would you reproduce the current behavior (if this is a bug)?

Plunkr: https://plnkr.co/edit/NjH4h3rog9yeQ2k8T3N0
1) Select the 1st answer, click "next"
2) Enter the 2nd answer, "next"
3) Enter the 3rd answer, "next"
4) Click "Complete"
See 3rd answer value to be present as 1st answer value as well:
```json
{"countries1":"foo","countries2":"foo","testText":"test"}
```

Note: is not reproduced if 2nd page is removed.

### Specify your

* browser: Google Chrome
* browser version: 60.0.3112.113 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery
* surveyjs version: 0.12.25

**Comment by andrewtelnov** [comment]
@nikitakarpenkov We are going to rewrite our custom widgets. We have implemented them as an example to show how it is possible to embedded a third party widget into the library.
In fact the most people expect from us support this code. We will create a new repo for widgets and we will start fully support them.

Thank you,
Andrew

**Comment by nikitakarpenkov** [comment]
There is a workaround! See fixed plinker: https://plnkr.co/edit/8HzcfJ5SttrYxI4pJxUW
All you need is to remove event handler on widget unmount using jquery .off function:
`
willUnmount: function(question, el) {
        $(el).find("select").off('select2:select').select2("destroy");
    }
`

**Comment by dmitrykurmanov** [comment]
@nikitakarpenkov, ok, select2("destroy") method was taken from the documentation. And I think that this is _select2_ bug. I've created an [issue ](https://github.com/select2/select2/issues/5064) in the select2 repo. So your workaround is good and we will include it in our examples. Thank you!
