### ISSUE TITLE
navigationButtonsVisibility not working as expected

### ISSUE THREAD

**Issue by sasankmukkamala** [surveyjs/surveyjs#655]
@andrewtelnov - I am facing a problem with this. When `showNavigationButtons: true` at survey level and `navigationButtonsVisibility: "hide"` at page level, it seems to be working as expected. But `showNavigationButtons: false` and  `navigationButtonsVisibility: "show"` are set, the buttons are not visible ever. If I am not wrong, according to the documentation this should work. Am I doing something wrong?
#206

**Comment by sasankmukkamala** [comment]
#206

**Comment by andrewtelnov** [comment]
@sasankmukkamala Yes, thank you!

**Comment by andrewtelnov** [comment]
@dhwanivora It should work fine. Could you create an example or share a json that doesn't work? Please tell us the platform and version you are using.

Thank you,
Andrew
