### ISSUE TITLE
Editing a previously filled survey and going directly to a page having restful choices and imagepicker, then the choices are not populated

### ISSUE THREAD

**Issue by gaurav-singhal** [surveyjs/surveyjs#657]
### Are you requesting a feature, reporting a bug or ask a question?

BUG!

### What is the current behavior?

When we edit a previously filled survey and take user directly to say 2nd or 3rd page instead of 1st which has choices coming from restful services, then the choices from restful services are not loaded.

### What is the expected behavior?
Choices should be loaded from restful services even in first instance.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
ngOnInit() {
        this.surveyService.getSurvey(1).then(survey => {
            this.surveyModel = new Survey.ReactSurveyModel(survey);
            if (this.route.snapshot.paramMap.get('resultId')) {
                this.responseId = +this.route.snapshot.paramMap.get('resultId');
                this.userService.getToken().then(token => {
                    this.surveyService.getSurveyResponse(this.responseId, token).then(data => {
                        survey.data = data;
                        this.surveyModel.currentPageNo = +this.route.snapshot.paramMap.get('pageNum');
                        Survey.SurveyNG.render('surveyElement', { model: this.surveyModel });
                    })
                })
            } else {
                Survey.SurveyNG.render('surveyElement', { model: this.surveyModel });
            }
        });
    }

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version: 0.12.26

**Comment by andrewtelnov** [comment]
@gaurav-singhal Here is [the  example](https://plnkr.co/edit/6wZbTBVQCQxRhrwKqlTB?p=preview) that works fine.

Thank you,
Andrew

**Comment by gaurav-singhal** [comment]
See [this plunkr ](https://plnkr.co/edit/EGVJkPw4nhOi9CuwbiIt?p=preview)

On further research, I think the issue is not with previously answered survey but any survey.

If we go directly to a page (irrespective of 1st or second) which has choices coming from restful services and we have used imagepicker to display that page then the images will not be loaded on that page. We can go next and previous and then it will work fine.

**Comment by andrewtelnov** [comment]
@gaurav-singhal The issue is in the custom widget. If you comment the custom widget registration, it works fine. 
Here is what happen. The afterRender calls before the choices are getting from the restful service. You need to rebuild the widget after you get the result from the server.
Here is the [updated pluker](https://plnkr.co/edit/2tJHzakIfCaojx6DwfId?p=preview).

Thank you,
Andrew

**Comment by gaurav-singhal** [comment]
Thanks that worked. I should have thought of this... You are wonderful!

**Comment by gaurav-singhal** [comment]
Is there any callback on survey available which is called when all the choices are loaded?

**Comment by andrewtelnov** [comment]
@gaurav-singhal Nope, why do you need this?

**Comment by gaurav-singhal** [comment]
Actually I am creating my own custom progress bar which shows the selected image in each question. I could have picked up the choices by making a call to these rest API's myself to get the image URL's but I thought to use the activeChoices in each question and then get the selected image url's from there based on survey response. Now on initial load, as the choices are not yet loaded, I am stuck.

So in absence of the callback at survey level telling me that all the restful choices are now loaded, I can use setTimeout method and solve it...

**Comment by andrewtelnov** [comment]
You may modify the following method in the custom widget code:
```
        question.choicesChangedCallback = function() { 
            updateWidget(); 
        }
```
You may add a counter or an array/hashtable to understand if all data has been loaded.
I do not think, that I will be able to add an event for a general case. The developer may set/change restful object or re-run the request manually: `question.choicesByUrl.run();`

Thank you,
Andrew

**Comment by gaurav-singhal** [comment]
Ok I have another issue. If the choices are dependent on previous filled answer, then its an issue as previous value is not picked by url.

[](https://plnkr.co/edit/hBcORIh9cSvbWw3bTj4Y?p=preview)

**Comment by andrewtelnov** [comment]
@gaurav-singhal survey.setValue() mehtod is working: https://plnkr.co/edit/W3xJsNYbfHKbSkBdgdHV?p=preview
survey.data  - doesn't work, because it doesn't call the notification and the request is send before setting the value to survey.data
If the current solution, is not working for you, please let me know.

Thank you,
Andrew

**Comment by gaurav-singhal** [comment]
Thanks that works.

Another issue is if we change the value of question on which further questions choices are dependent, then the value of the dependent questions in data does not change and remains valid.
[https://plnkr.co/edit/IXTnkEGvUG9I71TAKwSY?p=preview](https://plnkr.co/edit/IXTnkEGvUG9I71TAKwSY?p=preview)

So if we change the value of region to Americas in there from Africa, the country value is not invalidated leading to user being bale to complete the survey with invalid value of country. Any suggestions?

**Comment by andrewtelnov** [comment]
@gaurav-singhal It will be hard for the library to find this dependence and clear the value. I would suggest to use onValueChanged event. Here is the working example: https://plnkr.co/edit/EytqdR1h1SkR5vl5Gg07

Thank you,
Andrew

**Comment by gaurav-singhal** [comment]
Seems like the value is not cleared from the survey data immediately. Please check.

[https://plnkr.co/edit/GIJcXElBHHJZjEq77cQ9?p=preview](https://plnkr.co/edit/GIJcXElBHHJZjEq77cQ9?p=preview)

If you change region from Africa to Asia, the value in country is not immediately cleared as well as it lets us submit country without selecting it.

**Comment by andrewtelnov** [comment]
@gaurav-singhal Yes, I would consider this as bug. For some reason clearValue doesn't work correctly. I will take a look at it.
I think, I will be able to handle this scenario without clearValue. If there is a value and it exists in visibleChoices and after updating visibleChoices (for example getting new values from the restful service) the value doesn't exists in visibleChoices any more, then clear the value.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@gaurav-singhal I have fixed the bug, it will be available in the next minor release.
I will think about clearing the value automatically. It is not as easy as I think initially.

Thank you,
Andrew

**Comment by gaurav-singhal** [comment]
Thanks. Saw the change that you did. 

I tried three options to clear the value in question.choicesChangedCallback but it does not clear. Let me know when your changes are available in the release. Thanks!

```
question.choicesChangedCallback = function () {
            if (question.value && question.activeChoices){
                if (question.activeChoices.findIndex(el => el.permalink === question.value) == -1){
                    question.value = undefined;
                    question.setNewValue(undefined);
                    question.cachedValueForUrlRequests = undefined;
                }
            }
        }
```

**Comment by andrewtelnov** [comment]
@gaurav-singhal I have implemented the clearing values on changing choices from restful service, if the value previous existed in the choices and then doesn't exists in the choices array.
It means, that from the next minor release you don't need to clear value, it should be done by the library.

Thank you,
Andrew

**Comment by gaurav-singhal** [comment]
Thanks!
