### ISSUE TITLE
Using Editor,   checkbox control: unable to set the text

### ISSUE THREAD

**Issue by lalitkhanna** [surveyjs/surveyjs#658]
### Are you requesting a feature, reporting a bug or ask a question?
Facing this issue, while using editor. I'm setting text values for checkbox & click on 'Ok" but after coming on same dialog , I saw nothing is there for text.  ? 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@lalitkhanna Unfortunately, I do not understand how to reproduce the problem :-(

Thank you,
Andrew
