### ISSUE TITLE
is it possible to pre-select a radiobutton of a radio group?

### ISSUE THREAD

**Issue by vanBersie** [surveyjs/surveyjs#659]
**Question**

In this example https://surveyjs.io/Examples/Library/?id=questiontype-radiogroup&platform=jQuery I couldn't find anything about setting a default choice or pre-selecting a radio button. Is it possible?

The current behaviour is, that none of the radio buttons is selected. But I'd like to be one of these radio buttons checked so that the user could submit the survey faster.

So for example:
`choices: ["Value 1:checked", "Value 2"]`

or however if even possible would display two radiobuttons and one of them is already set to checked. Thanks in advance!

**Comment by andrewtelnov** [comment]
@vanBersie you may use setValue method: `survey.setValue("myQuestionName", "Value 1");`
There is a request: [defaultValue property](https://github.com/surveyjs/surveyjs/issues/638). I think we will implement it soon. After that you will be able to write: `defaultValue: "Value 1"`.

Thank you,
Andrew

**Comment by vanBersie** [comment]
@andrewtelnov : Thank you very much! This did the job! :)

**Comment by RitheshShantharaju** [comment]
@vanBersie Could you let me know how you solved the issue.

Thanks

**Comment by tsv2013** [comment]
```JSON
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "radiogroup",
     "name": "question1",
     "defaultValue": "item2",
     "choices": [
      "item1",
      "item2",
      "item3"
     ]
    }
   ]
  }
 ]
}
```

**Comment by letitechera** [comment]
@tsv2013 
Hi! I'm trying to pre-select the "other" option, so the "Other" input is shown and the user can straight up start writing,  but defaultValue is not working right..

This is the question:
`{
	"type": "radiogroup",
	"name": "1.12",
	"title": "To which gender do you most identify?",
	"isRequired": true,
	"hasOther": true,
	"otherText": "Please specify",
	"otherErrorText": "Please specify",
	"hasNone": true,
	"noneText": "Prefer not to answer",
	"defaultValue": "other"
				}`

This is what it shows:
![image](https://user-images.githubusercontent.com/22220084/156448577-c0e0ede5-f483-4391-ad5d-15d755bd444f.png)

And this is what I want it to do:
![image](https://user-images.githubusercontent.com/22220084/156448688-1042edac-f238-4deb-9fa3-aca498795b4c.png)

Does anybody know how can I achieve that?
