### ISSUE TITLE
Triggers clobber each other

### ISSUE THREAD

**Issue by alzulas** [surveyjs/surveyjs#660]
### Are you requesting a feature, reporting a bug or ask a question?
feature, sort of a bug

### What is the current behavior?
If you have a question with multiple answers which should make the next answer visible, this is not currently possible. 

For instance, if I have a question like "Do you use the bus?" and the answers are "Yes", "No", and "I would like to start" and the next question is "What bus routes are useful to you?" you would want "Yes" and "I would like to start" from the previous question to both make the next question visible. 

Currently, there is no way to use "visibleIf" with multiple requests (I have tried array, comma, "or" and calling visibleIf multiple times) and if you set multiple triggers to the same location, only the bottom request will work. This is because, as the code checks the set, it tests the first trigger, and finds true, so it sets the question to visible, but then the next trigger is false and it sets the question to not visible again. This is somewhat of a bug, but probably just a feature not implemented yet.

### What is the expected behavior?

If one trigger sets the group to true, the next should not be checked.

### How would you reproduce the current behavior (if this is a bug)?

Take any example of multiple triggers, set more than one to the same question.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: Not currently available on the internet

Test code

```
your_code_here

        triggers: [{ type: "visible", name: "thoughts", value: "Rarely", questions: ["Quality"]},
                { type: "visible", name: "thoughts", value: "sometimes", questions: ["Quality"]},
                { type: "visible", name: "thoughts", value: "Often", questions: ["Quality"]},
                { type: "visible", name: "thoughts", value: "time", questions: ["Quality"]},
                { type: "visible", name: "thoughts", value: "Always", questions: ["Quality"]}],

//Always is the only response that will make the next question available.

### Specify your

* browser: Safari, Chrome. and Firefox
* browser version: All the most current for Mac on 9/17/17
* surveyjs platform (angular or react or jquery or knockout or vue): jquery 3.2.1
* surveyjs version: 0.12.26

**Comment by andrewtelnov** [comment]
@alzulas Have you seen these issues?
https://github.com/surveyjs/surveyjs/issues/330
https://github.com/surveyjs/surveyjs/issues/565

PS: https://www.google.com/search?q=surveyjs+visibleIf+checkbox&oq=surveyjs+visibleIf+checkbox

Thank you,
Andrew

**Comment by alzulas** [comment]
Ahh. I see. I did a search on triggers. Not on visibleIf. I figured my answer was somewhere in triggers. Thanks!
