### ISSUE TITLE
How robust surveyJS for Mobile

### ISSUE THREAD

**Issue by lalitkhanna** [surveyjs/surveyjs#661]
### Are you requesting a feature, reporting a bug or ask a question?
This is just a query if you could use surveyJS in Mobile. Any instructions respect to this area.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
If you mean to use SurveyJS in the mobile browser, I don't see any poblems. If you'll face any troubles I hope we'll overcome them with the additional CSS.
