### ISSUE TITLE
Set value on "html" type question

### ISSUE THREAD

**Issue by obitohub** [surveyjs/surveyjs#663]
### Are you requesting a feature, reporting a bug or ask a question?
question

### What is the current behavior?
It is possible to set simple input field value through trigger with statement like this:
let question = this.surveyModel.getQuestionByName( "QS5A" ) as Survey.Question;
question.value = "sssssssssssss";

Is it possible to set value for question which has type of "html" ?
{
  "type": "html",
  "name": "QS5A",
  "html": "test"
}

### What is the expected behavior?
Instead of "html": "test" it should be set to "html": "changed" when trigger is executed.

**Comment by andrewtelnov** [comment]
@obitohub html question doesn't have value property. In general, you want to modify  a property of an element on a value changing. It is another type of trigger and it definitely makes sense.
We may introduce it in the upcoming releases. We will be able to implement it after we implement the following functionality: https://github.com/surveyjs/surveyjs/issues/596.
At the current moment you have to use onValueChanged event.

Thank you,
Andrew

**Comment by ajien** [comment]
It would be nice to have a way to programmatically change the content of an html field, as it can be a really helpful, for example, to use it in displaying summary of all questions and answers at the end of a survey.

**Comment by andrewtelnov** [comment]
@ajien You can do this, htmlquestion.html = youValue, additionally you may use text preprocessing,
for example: `htmlquestion.html = "You name is : <b>{name}</b>, e-mail: <b> {email}</b>"`, where {name} and {email} question names.
Here is [the example](https://surveyjs.io/Examples/Library/?id=survey-processtext).

Thank you,
Andrew

**Comment by ajien** [comment]
Perfect! I was trying setValue and it did not work, but I was about to try setting assigning a value to the html property and you came to the rescue.
