### ISSUE TITLE
Property tag

### ISSUE THREAD

**Issue by hugofabricio** [surveyjs/surveyjs#665]
How to retrieve question tag?

**Comment by andrewtelnov** [comment]
@hugofabricio Here is the code to add a tag to a question:
`Survey.JsonObject.metaData.addProperty("questionbase", {name: "tag:number", default: 1});`
After that you may use myquestion.tag.
If you are using the latest version you may also using myquestion.getPropertyValue("tag");
If you do not setup the value, the default value (1) will be returned by calling myquestion.tag or getPropertyValue function.

Thank you,
Andrew

**Comment by hugofabricio** [comment]
Its possible return tag of question onAfterRenderQuestion?

**Comment by tsv2013** [comment]
You can access the question and it's tag in the handler of the onAfterRenderQuestion event:
```
function onAfterRenderQuestionHandler(survey, options) {
    var question = options.question;
    if(question.tag !== 1) {
    }
}
```

**Comment by hugofabricio** [comment]
I am trying, but only return undefined.

My api.
```
{
  "locale": "pt",
  "evaluationId": 1,
  "pages": [
    {
      "elements": [
        {
          "type": "matrix",
          "columns": [
            {
              "value": "0",
              "text": "Não se aplica"
            },
            "1",
            "2",
            "3",
            "4",
            "5",
            {
              "value": "6",
              "text": "Satisfeito"
            }
          ],
          "name": "Lorem ipsum",
          "tag": 123,
          "rows": [
            {
              "value": "1",
              "text": "Lorem ipsum dolor 1?"
            },
            {
              "value": "2",
              "text": "Lorem ipsum dolor 2?"
            }
          ]
        }
      ],
      "name": "page_1"
    }
  ]
}
```

Event
```
      survey.onAfterRenderQuestion.add(function(sender, options) {
        let question = options.question;
        console.log(question.tag);
      });
```

**Comment by tsv2013** [comment]
Have you added the option setup code, as suggests @andrewtelnov 
`Survey.JsonObject.metaData.addProperty("questionbase", {name: "tag:number", default: 1});`
?

**Comment by hugofabricio** [comment]
No, I'm put tag in the json file

**Comment by andrewtelnov** [comment]
@hugofabricio You have to add this code before you are processing the json.

Thank you,
Andrew

**Comment by hugofabricio** [comment]
Solved, thanks Andrew and tsv2013 :)
