### ISSUE TITLE
oncomplete when submit form 

### ISSUE THREAD

**Issue by xiuzhen1103** [surveyjs/surveyjs#667]
### Are you requesting a feature, reporting a bug or ask a question?

ask a question

### What is the current behavior?
In SurveyJs has behaviour when complete survey and display message.
```
model = new Model(json);	
 model.onComplete.add(function(result) {
         document.querySelector('#container').innerHTML = "Thank you for completing survey"
  );
```

### What is the expected behavior?

Is there any chance that if I could render survey with component? 
```
model.onComplete.add(function(result) {
          return (
    <div>
         <SurveyEmpty message="No round data available"/>
   </div>
  );

```

**Comment by andrewtelnov** [comment]
@xiuzhen1103 You may hide the survey and show your own component.

Thank you,
Andrew

**Comment by xiuzhen1103** [comment]
do you have any sample code for this, it only happens when oncomplete triggered ?

**Comment by xiuzhen1103** [comment]
onComplete it is inside constructor, should not be rendering a component inside the constructor.

**Comment by andrewtelnov** [comment]
@xiuzhen1103 you may set survey.showCompletedPage = false; and the survey will be invisible after it's completed.
You may use the survey.completedHtml property to show the custom html on survey complete.

**Comment by xiuzhen1103** [comment]
But I would like to have render component instead of customHTML

**Comment by andrewtelnov** [comment]
Then set showCompletePage to false and render your component.

Thank you,
Andrew

**Comment by xiuzhen1103** [comment]
would you give an example, please? @andrewtelnov

**Comment by andrewtelnov** [comment]
@xiuzhen1103  [Here it is](https://plnkr.co/edit/dz1O6mC1XhVKL234Yjof?p=preview)
