### ISSUE TITLE
Is it possible to validate a field onChange?

### ISSUE THREAD

**Issue by Starojitski** [surveyjs/surveyjs#668]
Right now validation of all answers happens onComplete

I use onValueChanged event to persist all entered values on the server and would like to prevent saving invalid values. 

I am using surveyjs jquery

**Comment by andrewtelnov** [comment]
@Starojitski Sure, you have to call the `question.hasErrors(true);` function
Here is [the example](https://plnkr.co/edit/ZNJ6TfOvHxLsquIXfmpY?p=preview).

Thank you,
Andrew

**Comment by Starojitski** [comment]
No. Thank you!! :)
but one thing: for some reason the handler in your example is being called twice for some rows and only once for other rows. When it is called twice i get error message displayed twice as well. 

I don't do any fancy stuff so i don't know whether it is my code that does it. 

By following the call stack stack i found at least one function where this can be prevented by returning when the value does not really change and calling `onValueChanged` is not necessary

```
    Question.prototype.setNewValue = function (newValue) {
        // new code starts here 
        if (newValue === this.value) return;
        // new code ends here
  
        this.setNewValueInData(newValue);
        this.onValueChanged();
    };
```
Should i wait for your update or should i try and debug my own code?

**Comment by Starojitski** [comment]
I see the double error messages pattern. My element/question's definition looks like this :
```
    {
        "id": 68,
        "type": "text",
        "name": "B9BD-2E67E28E1D7F",
        "title": "SSI personal brand",
        "commentText": "",
        "otherText": "",
        "renderAs": "number",
        "validators": [
            {
                "type": "numeric",
                "minValue": "0",
                "text": "Min value is 0"
            },
            {
                "type": "numeric",
                "maxValue": "25",
                "text": "Max value is 25"
            }
        ]
    }
```

When the first validator produces error then only one message is displayed
When the second validor produces error then the message is displayed twice

**Comment by andrewtelnov** [comment]
@Starojitski I have fixed the bug. The problem was that numeric change the value from "26" to 26 and calls the validation one more time.
Commonly there is no such a problem, since the validation is called on page next or complete.

Thank you,
Andrew

**Comment by Starojitski** [comment]
I tried installing the latest version (0.12.26) but did not see any difference in behaviour. Besides for some reason the layout we use was affected so i reverted to version 0.12.17.  To solve double error message i combined validators into a single one with both min and max conditions.

**Comment by andrewtelnov** [comment]
@Starojitski The fix will be available in v0.12.27. Could you please post here the layout issues? I would love to fix them before releasing a new version. 

Thank you,
Andrew

**Comment by Starojitski** [comment]
I'm pretty sure the problem lies on our side, not yours. My colleague responsible for styling is due back on monday. I will run it past him and will get back to you on this.

**Comment by xiuzhen1103** [comment]
Hi @andrewtelnov @tsv2013 May I ask if you could do immediate validation after first submit survey, please?
