### ISSUE TITLE
widget matrixdropdowncolumn stop working on latest release

### ISSUE THREAD

**Issue by madceb** [surveyjs/surveyjs#669]
In version 0.12.25 is working but not in 0.12.26,

It is a change in how to use widgets in a matrixdynamic?

Regards,

**Comment by andrewtelnov** [comment]
@madceb I just tried, custom widgets work in matrix dynamic.
Could you tell what exactly stop working or give us a plunker example.

Thank you,
Andrew

**Comment by madceb** [comment]
https://plnkr.co/edit/h8GGdHthEiYeirDdypK3?p=preview
After some troubleshooting I got where the issue is, is in line 4 & 5, in this new version only one line works at a time. 

hope this helps.
Regards,

**Comment by andrewtelnov** [comment]
@madceb The issue was because  of the default values. We started to work with them differently.
It is fixed now.

Thank you,
Andrew

**Comment by madceb** [comment]
Great. It's working again in latest release! Regards
