### ISSUE TITLE
Attaching meta data before submitting to dxsurvey

### ISSUE THREAD

**Issue by aliogaili** [surveyjs/surveyjs#671]
I'm trying to attach some meta data to the survey results (such is user name, id etc.) before sending to dxSurvey but I'm unable to do so.

What is the best way to attach meta data to survey result before sending to dxsurvey using react?

**Comment by andrewtelnov** [comment]
@aliogaili onComplete event is fired before the results are sent to the server.

Thank you,
Andrew

**Comment by aliogaili** [comment]
Thanks Andrew, yeah I just manually edited the data object and it was passed a long.
