### ISSUE TITLE
Validator with minValue equal to 0 does not work

### ISSUE THREAD

**Issue by Starojitski** [surveyjs/surveyjs#672]
No validation is performed with `minValue=0` and no error message is displayed on negative values. 

The workaround is `minValue=-0.000001`

* latest Chrome:
* survey-jquery
* version 12.17

**Comment by andrewtelnov** [comment]
@Starojitski You are right. There was a bug that has been fixed several weeks ago. Let's make sure that you may use the new version that we are going to release.

Thank you,
Andrew
