### ISSUE TITLE
Empty blank title for a question displays name instead. How to avoid 

### ISSUE THREAD

**Issue by enricribas** [surveyjs/surveyjs#673]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

Having a blank title uses the name field instead.

### What is the expected behavior?

How do I for a particular question, NOT have a title. I know it seems strange, but there are questions that we don't want a title for. An empty space doesn't work. An em-space does but seems very brittle and hard to explain to non-developers. Overwriting title template doesn't work because it says { title } but injects name if title is blank

### How would you reproduce the current behavior (if this is a bug)?

have an empty title and see the name displayed.

**Comment by tsv2013** [comment]
You can try to enter space for the question's title.

**Comment by enricribas** [comment]
Did that change? That didn't use to work,  I think.

Seems pretty hacky, but will do.

Is there a reason why the name is used as a default value even if I customize the titleTemplate? Seems wrong to me.  Without template, maybe, but if I customize it, seems the default should go away, no?

**Comment by tsv2013** [comment]
I've tried it before write here. Link to the survey is https://dxsurvey.com/published?id=d12527f4-6537-4cef-94a8-7afcf266065a - the only question in the survey has no title, but still has a number.
If I undestood you correctly...

**Comment by Buffalonian** [comment]
This shouldn't work this way. I am using Font-awesome stars and I have to inject html types instead vs. using the title option. I don't want the {name} to show. I want it suppressed.

**Comment by andrewtelnov** [comment]
@Buffalonian `question.titleLocation = "hidden";` will do the trick.

Thank you,
Andrew
