### ISSUE TITLE
Deeper Dynamic Question CSS Button Controls

### ISSUE THREAD

**Issue by wollerman** [surveyjs/surveyjs#675]
### Are you requesting a feature, reporting a bug or ask a question?
feature

### What is the current behavior?
Buttons have CSS classes applied for dynamic questions with the same styling: https://github.com/surveyjs/surveyjs/blob/4eab3d1f45709990ba1fb279de5eb808a19b4fe0/src/defaultCss/cssbootstrap.ts#L23

### What is the expected behavior?
Is it possible to separate button CSS by their functionality? This would allow customization of the matrixdynamic and paneldynamics in the same way that panelAddText and panelRemoveText allow for the button text to change. 

E.g.: 
`matrixdynamic: { root: "table", buttonAdd: "button", buttonRemove: "button" },`

**Comment by SamMousa** [comment]
This is also required for "proper" bootstrap integration. Remove buttons tend to get some class like `btn-danger` while add buttons have something like `btn-success` or `btn-primary`. Currently this is not possible.

**Comment by tsv2013** [comment]
I've added this customizations.
This is the code sample for survey-knockout:
```JS
  var myCss = {
    matrixdynamic: {
      buttonAdd: "btn-success",
      buttonRemove: "btn-danger"
    }
  };
  Survey.Survey.cssType = "bootstrap";
  var model = new Survey.Model(json);
  model.css = myCss;

  model.render("surveyElement");

```

**Comment by masciugo** [comment]
Thanks! What about doing the same for panel dynamic?
