### ISSUE TITLE
Visible if for answer choices - request feature

### ISSUE THREAD

**Issue by dprogaki** [surveyjs/surveyjs#676]
I just noticed issue #472 is closed but I would like some more feedback on that. I have the same issue where I would need a visibleIf for every answer choice, and I could use something more generic than the answer provided at issue 472, as  I need this for more than one questions and each question will have to add more text to each choice. 
I also provided a small example at issue 472.
It would be very useful if this could actually be implemented in order for it to be used through the editor as well and not to be hard coded in the code.

Thank you in advance

**Comment by andrewtelnov** [comment]
@dprogaki I have replied in https://github.com/surveyjs/surveyjs/issues/472'
To be honest I do not know any really good and understandable solution. I suggested one, let me know what do you think.

Thank you,
Andrew

**Comment by dprogaki** [comment]
Thank you for your answer! 
It would be extremly helpful for me if just the visible if for choices was implemented. The rest won't be such a problem. Thank you again.

**Comment by dprogaki** [comment]
Hi guys! Any news on this one?

**Comment by andrewtelnov** [comment]
@dprogaki Unfortunately we have posponed this functionality.
Aftere releasing the first version we are going to re-write the our expression functionality. If we implement it for every items in dropdown/checkbox/radiogroup as it is now, it will kill the performance the survey if there are any question with a lot of items.
But it is still in our radar.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@dprogaki It has been impelemented. More information is [here](https://github.com/surveyjs/surveyjs/issues/1079)

Thank you,
Andrew
