### ISSUE TITLE
Default value after 27 version

### ISSUE THREAD

**Issue by obitohub** [surveyjs/surveyjs#677]
### Are you requesting a feature, reporting a bug or ask a question?
question/bug

### What is the current behavior?
After 27 version if you use defaultValue property on question without json data then default value appears on input field. If you add json data even wihout elements then there is no default value.

### What is the expected behavior?
If you add defaultValue to property of the question it should be priority number one to set this value not concidering what is in data json. 

### How would you reproduce the current behavior (if this is a bug)?
https://plnkr.co/edit/5d6wqMvfG4qTsx5V1wCt?p=preview

you can throw out window.survey.data = {//"QS2_a1":"sss"} part and default will be "sd" but if you leave window.survey.data even empty then value will not be displayed.

I know that you can add default in data json as this: QS2_a1":"sss". Its logical mistake because data json is meant for data, not defaults. Defaults should be on questions property.

Simple situation:
we are getting all real data from backend witch returns it to json data. Backend will not give us e.g. "0" to numbers, so that is why we need to set it on property.

**Comment by andrewtelnov** [comment]
@obitohub `survey.data = {};` cleans the survey data. I can't change it. It is  correct way to clear all survey results.
I have modify [the example](https://plnkr.co/edit/iVLMD8SCfRM2iMXIkgCG?p=preview)
Here is the  correct code:
```
var data = {}; //custom data
for(var key in data) {
  survey.setValue(key, data[key]);
}
```

Thank you,
Andrew

**Comment by obitohub** [comment]
@andrewtelnov  Thank you very much, it works :+1:
