### ISSUE TITLE
DXSurvey Crashes

### ISSUE THREAD

**Issue by enricribas** [surveyjs/surveyjs#678]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

![image](https://user-images.githubusercontent.com/438493/30703364-7ca94f9a-9ebd-11e7-9575-7ecc790a5f11.png)

### What is the current behavior?

Seems like editing a survey is crashing

**Comment by tsv2013** [comment]
Thank you for the report, @enricribas ! I've temporary reverted sites to the 0.12.26. We'll fix it ASAP.
