### ISSUE TITLE
onComplete with React fires twice

### ISSUE THREAD

**Issue by enricribas** [surveyjs/surveyjs#679]
### Are you requesting a feature, reporting a bug or ask a question?

Bug. I know this is going to sound impossible but we have tried it and reproduced

### What is the current behavior?

call it once

### What is the expected behavior?

gets called twice

### How would you reproduce the current behavior (if this is a bug)?

```
                <SurveyJs.Survey
                  model={ this.state.model }
                  css={ cssOverrides }
                  onCurrentPageChanged={ this.handlePageChange }
                  onComplete={  () => { console.log('called') } }
                  />
```

The onComplete gets called twice

Currently we're using lodash throttle to ensure only one completion.

### Specify your

* surveyjs platform (react ):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@enricribas Unfortunately I could not reproduce it :( 
Here is the [plunker example](https://plnkr.co/edit/pYjUg6HF3c88AVv4cC84?p=preview)

Thank you,
Andrew

**Comment by enricribas** [comment]
```
import React, { Component } from 'react';
import * as SurveyJs from 'survey-react';

import data from './surveys/005.js';

class Discovery extends Component {
  constructor(props) {
    super(props);
    const model = new SurveyJs.Model(data);

    this.state = {
      model,
    };
  }

  render () {
    return (
      <SurveyJs.Survey
        model={ this.state.model }
        onComplete={ () => console.log('getting here') }
        />
    )
  }
}

export default Discovery;
```

The console.log gets called twice. not doing any magic here. maybe it has to do with the survey-react version? I don't know

**Comment by enricribas** [comment]
ok, it has to do with putting the model into the state. So not a surveyjs issue. will close. sorry.

For reference for anyone else...
```
import React, { Component } from 'react';
import * as SurveyJs from 'survey-react';

import data from './surveys/005.js';

class Discovery extends Component {
  render () {
    const model = new SurveyJs.Model(data);

    return (
      <SurveyJs.Survey
        model={ model }
        onComplete={ () => console.log('getting here') }
        />
    )
  }
}

export default Discovery;
```

This only calls the onComplete once.

**Comment by enricribas** [comment]
FYI, if this helps anyone in the future. It actually had to do with ReactRouter and RelayModern. Apparently, they don't get along and switching to FoundRouter fixed our double render issue.
