### ISSUE TITLE
clearInvisibleValues properties

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#680]
Hi, i have a question...

when i set this properties in survey model, at onComplete event, the values of hidden answers are deleted from survey.data...

Is there a possibility to do this also at event onValueChanged and onVisibleChanged?

I ask this because I should make an automatic save at change of each answer, and recovering the value of the survey.data I do not have the option to have it cleared from hidden values

Thanks

**Comment by andrewtelnov** [comment]
@care46 There were already many requests about this. I have maden clearInvisibleValues property a string, instead of boolean. It has 3 values: 'none', 'onComplete' - clear on complete and 'onHidden' - clear on making question invisible.
Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov woow, thanks!

**Comment by cliewdevelop** [comment]
Hi Andrew - is there a possibility to get valueHash of both versions?
Meaning I want both:
valueHash (for none)
valueHash (for onHidden)

The reason is, I have custom buttons for saving and submitting a survey.
