### ISSUE TITLE
Is it possible to add choices property with multiple values? 

### ISSUE THREAD

**Issue by jakubknejzlik** [surveyjs/surveyjs#681]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
Is it possible to create property with `choices` and add possibility to specify multiple values? For example when I have question that can be in multiple categories. I only found way how to provide select for single choice.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/IsMmvUwvIBLDumBIGBqU?p=preview

**Comment by andrewtelnov** [comment]
@jakubknejzlik Unfortunately we do not have this type of Property Editor yet. What kind of property do you try to edit?
I may add a multiple choice Property Editor. It will be similar to what you have now when you are editing defaultValue of the checkbox question.

Thank you,
Andrew

**Comment by jakubknejzlik** [comment]
@andrewtelnov thanks for your reply. Currently we have situation when single question can have multiple categories and adding custom property fits to this scenario very well. The only thing is that current solution is to add:

categories = [“catA”,”catB”]
- category1:string choices:categories
- category2:string choices:categories
...

The ideal way how to achieve this would be:
categories=[{value:1,title:”catA”},...]
- categories:[number] choices:categories

Sorry for the formatting (mobile version). Basically we need to provide array of objects (categories) and have possibility to select multiple categories in designer, which will be represented by array of numbers in json (category ids).

**Comment by andrewtelnov** [comment]
@jakubknejzlik  I have created the plunker: https://plnkr.co/edit/Yut8OJJcjK6f9Dr0R3qQ?p=preview
Please let me know if property editor is ok.
There is an issue in run-time with this approach. If this is what you need, I will fix the issue.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@jakubknejzlik I have updated the example, it works just fine now.

**Comment by jakubknejzlik** [comment]
@andrewtelnov thanks for the plunked. I’m afraid I was not clear. Currently I can see the page property named categories where I can specify list of items and “category x” as value. But I’m not able to select from categories in each question.

**Comment by andrewtelnov** [comment]
@jakubknejzlik I am not sure that I fully understand you. Could you please describe the task in more details?

Thank you,
Andrew

**Comment by jakubknejzlik** [comment]
I’ll try to explain more detailed by providing real example (hope it helps). We have multiple questionnaires with set of questions:

1 - how fast patient reacted to picture
2 - what’s patience hearth rate after viewing picture
3 - how fast patient reacted to mirror exposure
4 - what’s patience heart rate after exposure

And following categories:
A - reaction time
B - time analysis
C - heart rate 

These categories are specified in another system and we load them to designer via rest api. In designer we create questions 1-4 and we need to assign categories to each question 1 (a, b); 2 (c); 3(a,b); 4(c). On different system we can create statistics for each category based on assigned questions.

**Comment by andrewtelnov** [comment]
@jakubknejzlik I am afraid it doesn't make any easy to me.
These categories are seen by end-users? Do you want just dynamically change the choice property. I am sorry, I do not get it :(
Maybe you will post your survey on the paper?

Thank you,
Andrew

**Comment by jakubknejzlik** [comment]
I’ll return tomorrow so I’ll try to prepare some plunker to make it clearer. Also the categories are used internally for statistics (we just need to be able to group questions together) so only admins (creators of form - can access designer) can see these categories

**Comment by jakubknejzlik** [comment]
Also if you see the original plunker in issue description, it’s almost it, but two things:
- we can choose only one category per question (we need way to select multiple) - this is more critical for us
- it would be great if we can provide array of objects not only array of strings for property choices (object with for example value and title keys)

**Comment by andrewtelnov** [comment]
@jakubknejzlik You initial example adds a property to the page object. 
Ok. I have modify a litle my example: https://plnkr.co/edit/Yut8OJJcjK6f9Dr0R3qQ
Now, for every question, you have a categories property. The property is an array of objects. Each object has a value that can be added taken from the list and title.

Probably, again, I am not sure exactly, you are looking for a property editor that will presented by checkboxes, where the value is your object value and the checkbox caption/title is your object title. Is it what you looking for?

Thank you,
Andrew

**Comment by jakubknejzlik** [comment]
@andrewtelnov ok for the example I written above the current solution that i found would be like this:
https://plnkr.co/edit/Hb16HS4n0Bvp6Xu8CRWP?p=preview

and filling this json in editor:
```
{
 "pages": [
  {
   "elements": [
    {
     "type": "radiogroup",
     "category1": "reaction time",
     "category2": "time analysis",
     "choices": [
      {
       "value": "0",
       "text": "very slow"
      },
      {
       "value": "0.5",
       "text": "normally"
      },
      {
       "value": "1",
       "text": "very fast"
      }
     ],
     "name": "how fast patient reacted to picture"
    },
    {
     "type": "text",
     "category1": "heart rate",
     "inputType": "number",
     "name": "what’s patience hearth rate after viewing picture"
    },
    {
     "type": "radiogroup",
     "category1": "reaction time",
     "category2": "time analysis",
     "choices": [
      {
       "value": "0",
       "text": "very slow"
      },
      {
       "value": "0.5",
       "text": "normally"
      },
      {
       "value": "1",
       "text": "very fast"
      }
     ],
     "name": "how fast patient reacted to mirror exposure"
    },
    {
     "type": "text",
     "category1": "heart rate",
     "inputType": "number",
     "name": "what’s patience heart rate after exposure"
    }
   ],
   "name": "page1"
  }
 ]
}
```

The problems I'm facing:
- it would be great if we can group `category1`,`category2`,`category3` in single `categories` (`category1="reaction time",category2="time analysis"` should be `categories="reaction time,time analysis"`)
- able to use array of objects (in `var categories`) instead array of strings

**Comment by jakubknejzlik** [comment]
Also let's say in end we'd love to use it like this: https://plnkr.co/edit/mmvORb6K9ZoNzaJkll8c?p=preview

...but:
- only one category can be selected
- in designer the string representation of each category is `[object Object]`
<img width="243" alt="screen shot 2017-09-30 at 10 33 31" src="https://user-images.githubusercontent.com/1138023/31044222-925fa194-a5cb-11e7-8d7f-95dcc8080157.png">

**Comment by andrewtelnov** [comment]
So you need a propety that will looke like:

**Comment by andrewtelnov** [comment]
@jakubknejzlik So you need a property that in json will look like:
`[categories : [{"category 1" : "reaction time"}, {"category 2" : "time analysis"}]]`
I have three questions now:
1) How many categories do you have? Is it same number? 3 categories or it can be from 0 to N, where N is constant or unlimited. Do you have the list of all categories or an user will just name them in the text box?
2) Categories values. Are they the same for all categories, like in your example `[null,"reaction time","time analysis","heart rate"]` ?
3) Are you ok if it will be the modal dialog? I can't see how it can be done by using a drop down.

Thank you,
Andrew

**Comment by jakubknejzlik** [comment]
Technically categories:[1,138,45] would be the easiest for our servers to parse (list of category ids (number or string) - more info below)

1) number of categories could be unlimited, but we are trying to stay at reasonable amount (but it could be still 10+). We store those categories on our side in db table (id/code and name) and load them to editor via url request.(sorry for not mentioning, now it looks really important when you mentioned it). Also categories should not be manageable within editor.

2) list could change based on several criteria, but basically it could by anything as we have dynamic list provided by url endpoint (in our case the only rule is list of object with identifier and name)

3) sure thing. IMHO It could be more clear whith large number of categories

Thanks for your effort, I really appreciate your help and patience with my explanations :)

Jakub

**Comment by andrewtelnov** [comment]
@jakubknejzlik No problem. I want to make an example of creating a custom Property Editor and your case should be a good example. Since it is a real case and not something fancy.
So, let me clarify, before I start to code:
1) There is the list of objects, that you are getting from your server, where every object has id (numeric) and name (string). 
2) An user may select unlimeted number of this categories
3) They should be stored in the json by list of numbers (object ids)
I would recommend the following. Create an editor that will show in Property Grid the list of selected categories by name as ["reaction time", "heart rate"], On clicking on this property, the Modal Window will be show with the list of checkboxes:
reaction time, heart rate, time analysis and so on (the list of you objects from server), where the value is object id and checkbox caption is object name. 
The categories will be selected by selected/unselected the checkboxes. If 10 checkboxes are selected, that means 10 categories will be choosen.
In Json it will be stored as `categories : [3, 4, 9]`

Is it what you are trying to build?

Thank you,
Andrew

**Comment by jakubknejzlik** [comment]
@andrewtelnov exactly. Just for the 1) the id isn't required to be number. In our case it is, but from general perspective UUID or manually created codes could be used too (so maybe using string instead of number could help cover all cases)

**Comment by jakubknejzlik** [comment]
Also I'm not sure if it helps you with implementation, but I just found that the similar approach is when selecting default values for checkbox (list of keys as value and displaying modal where I can select multiple choices):
![image](https://user-images.githubusercontent.com/1138023/31053645-8facfc9e-a6a2-11e7-9c20-9a94ea7b0fc4.png)

IMHO the exact same UI could be used :)

**Comment by andrewtelnov** [comment]
@jakubknejzlik It is not a complex task. I have implemented [this functionality](https://github.com/surveyjs/editor/issues/163)
It was really hard to understand, what do you need :) I have suggested to have dialog with checkboxes nine days ago (see my comments 9 days ago), but for some reason, it was ignored :-)

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@jakubknejzlik Here is [the example](https://plnkr.co/edit/O5zPOetlHqzMoyp5JeAk) with dev version. There are three different ways to set choices.

Thank you,
Andrew

**Comment by jakubknejzlik** [comment]
You are correct, I’ve totally missed the checkbox defaultValue in your first reply. I’m sorry for that :-/.
Thanks for your examples, it works great!
