### ISSUE TITLE
The word 'minimum' is misspelled in the Rating question type

### ISSUE THREAD

**Issue by Lumiras** [surveyjs/surveyjs#683]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug

### What is the current behavior?

The word 'minimum' is misspelled as 'mininum' in the Rating question

### What is the expected behavior?

The word 'mininum' should be spelled 'minimum'

### How would you reproduce the current behavior (if this is a bug)?

by misspelling the word 'minimum'

### Specify your

* browser: Firefox
* browser version: 57
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery (though it's misspelled in all versions)
* surveyjs version: v0.12.28

**Comment by andrewtelnov** [comment]
@Lumiras I has been fixed some times ago:
`{name: "minRateDescription", alternativeName: "mininumRateDescription", serializationProperty: "locMinRateDescription"},`
alternativeName needs so the old JSON continues to work.

Thank you,
Andrew
