### ISSUE TITLE
Vue onAfterRenderQuestion event didn't fire

### ISSUE THREAD

**Issue by snay** [surveyjs/surveyjs#684]
### Are you requesting a feature, reporting a bug or ask a question?

bug

### What is the current behavior?

Events on Vue components did not fire - onAfterRenderQuestion, onAfterRenderPage. 

onCurrentPageChanged is firing, but as far as i understand before the DOM change, so i can't use it for my purposes

### What is the expected behavior?

Expect event fired on each question (onAfterRenderQuestion) and on each page render (onAfterRenderPage).

### How would you reproduce the current behavior (if this is a bug)?

Check fiddle below.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://jsfiddle.net/c0um561w/2/
Test code

```
survey.onAfterRenderQuestion.add(function() { console.log('onAfterRenderQuestion') })
survey.onAfterRenderPage.add(function() { console.log('onAfterRenderPage') })

```

### Specify your

* browser: Chrome 
* browser version: 60.0.3112.113
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: 0.12.29

**Comment by andrewtelnov** [comment]
@snay I have fixed the bug.

Thank you,
Andrew
