### ISSUE TITLE
Crash on empty navigator.userAgent (react native)

### ISSUE THREAD

**Issue by r8** [surveyjs/surveyjs#685]
### Are you requesting a feature, reporting a bug or ask a question?
- bug/question

We are using surveyjs inside React Native application (long story).
Unfortunately, it makes our app crash during initialization.

The reason is `browserFromUA` function in `utils.ts`
navigator.userAgent is empty in React Native, so `ua.toLowerCase()` is causing a fatal error.

I tried to shim navigator object, but still no luck.

Now, I completely understand that our case is not how one's supposed to use surveyjs, but anyway: what do you think about adding a check for empty string inside that function?

Code in question is following:
https://github.com/surveyjs/surveyjs/blob/master/src/utils.ts#L7

**Comment by dmitrykurmanov** [comment]
@r8, hello, thanks for your interest! I think that this problem may reproduce in another libraries too ( for example https://stackoverflow.com/questions/29408492/is-it-possible-to-combine-react-native-with-socket-io). So may be a good solution is to add `window.navigator.userAgent = 'react-native';` before using surveyjs. I think it is more common way to solve the problem. What do you think?

**Comment by r8** [comment]
Yeah, I saw this link too, and that's exactly the way I tried to fix it. 
But for some reason, it didn't work.
So I decided to ask a question here first. Maybe you'll agree to add that check and I wouldn't need to dive deep into investigating different hacks :)

But it's ok, if it's out of your scope. I completely understand (that's why it's mostly a question, not bug report)
