### ISSUE TITLE
onVisibleChanged options are undefined

### ISSUE THREAD

**Issue by mellogarrett** [surveyjs/surveyjs#687]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
`onVisibleChanged` options is `undefined`

### What is the expected behavior?
`options` should have properties `name`, `questions, and `visible`

### How would you reproduce the current behavior (if this is a bug)?
$("#survey").Survey({
      ...
      onVisibleChanged: handleQuestionVisibilityChange
});

function handleQuestionVisibilityChange(survey, question) {
      console.log(survey);
      console.log(question);    --> undefined
}

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.12.28

**Comment by andrewtelnov** [comment]
@mellogarrett Could you please show the example?

**Comment by andrewtelnov** [comment]
Nevemind, it is definately a bug.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
It is fixed. As a workaround, please use the following code:

```
survey.onVisibleChanged.add(function(survey, options) {
    alert(options.name);
});
```
Thank you,
Andrew

**Comment by mellogarrett** [comment]
Awesome! Thanks for the speedy help
