### ISSUE TITLE
Incorrect behaviour in React Survey Component

### ISSUE THREAD

**Issue by jing159w** [surveyjs/surveyjs#689]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
The survey component gets its attributes (json and data) from the container, and the json is fetched from an API call. Therefore, component is rendered twice. Once with ```null``` json and another time when the API returns the actual survey json (with structure similar to json file below)

However, the logic doesn't for navigation doesn't seen to work. If the user selects the first Next for both Question 1 and Question 1B, the navigation button remains as "Complete" and will complete the survey upon clicked.

### What is the expected behavior?
The navigation button should display "Next" and continue to page 2.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
{
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
          "type": "radiogroup",
          "name": "Q1_A",
          "title": "Question 1",
          "isRequired": true,
          "choices": [
            {
              "value": "1",
              "text": "Done"
            },
            {
              "value": "2",
              "text": "Show Next"
            }
          ]
        },
        {
          "type": "radiogroup",
          "name": "Q1_B",
          "visible": false,
          "visibleIf": "{Q1_A} > 1",
          "title": "Question 1B",
          "isRequired": true,
          "choices": [
            {
              "value": "1",
              "text": "Done"
            },
            {
              "value": "2",
              "text": "Show Next"
            }
          ]
        }
      ]
    },
    {
      "name": "page2",
      "elements": [
        {
          "type": "checkbox",
          "name": "Q2_A",
          "visible": false,
          "visibleIf": "{Q1_A} > 1 AND {Q1_B} > 1",
          "title": "Question 2",
          "isRequired": true,
          "choices": [
            {
              "value": "1",
              "text": "Okay"
            },
            {
              "value": "2",
              "text": "Okay"
            }
          ]
        }
      ]
    }
  ],
  "showQuestionNumbers": "off"
}
```

### Specify your

* browser: Chrome
* browser version: Latest
* surveyjs platform: React
* surveyjs version: Latest

**Comment by andrewtelnov** [comment]
@jing159w I have just created the example and it works fine to me: https://plnkr.co/edit/Vy2vgx7qiUeM7YkDn2mm?p=preview

Thank you,
Andrew
