### ISSUE TITLE
matrixdynamic / dropdown width choicesByUrl and hasOther:true selecting other incorrectly?

### ISSUE THREAD

**Issue by madceb** [surveyjs/surveyjs#690]
Hello,

Not sure if this is a bug or I have something missing, in order to explain this issue this is the example:
https://plnkr.co/edit/lj8wMzb0RhcQl2lpBGMD?p=preview

It is a matrixdynamic with a dropdown column loading values from a Url, and a default data. If the dropdown column has the hasOther property as false, it shows the correct information but with the hasOther property true, the dropdown options show as other.

I hope I've explained myself well.

Regards,

**Comment by andrewtelnov** [comment]
@madceb Looks like a bug to me.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@madceb I have fixed the issue.

Thank you,
Andrew

**Comment by madceb** [comment]
Wow that was fast @andrewtelnov 
Great.
Regards,

**Comment by madceb** [comment]
Hello @andrewtelnov 

I check the example with the new code and it works great, but is it possible that the values are wrong sent when using a widget? I have a similar behavior that before but in a widget.

Regards,

**Comment by andrewtelnov** [comment]
@madceb Do you mean custom widget, select2? 

Thank you,
Andrew

**Comment by madceb** [comment]
I've created a different widget based in select2 (btw I just realized that the examples are not working, the preselected country is not showing) 

This case is in a MatrixDyanmic with dropdown like question
the data used it is just the "SelectedOption".

if the question "hasOther" is true, the values come as 
question.cachedValueForUrlRequests = "other"
question.cachedValue = "other"
question.commentValue = "SelectedOption"

if it is false the values come as
question.cachedValueForUrlRequests = "SelectedOption"
question.cachedValue = not defined
question.commentValue = not defined
question.comment = ""

Regards,

**Comment by andrewtelnov** [comment]
@madceb Sorry, I have missed the question. We have re-written custom widgets completely.
It should be fine now.

Thank you,
Andrew
