### ISSUE TITLE
clientId survey answered not resetting after result deleted

### ISSUE THREAD

**Issue by mnhospitals** [surveyjs/surveyjs#691]
I deleted the individual result from the MySurvey results screen, but the user still isn't able to re-answer the survey. It still throws the already answered flag.

**Comment by andrewtelnov** [comment]
@mnhospitals We will fix the bug and let you know.
Could you please send us your surveyId, postId and cliendId to support@surveyjs.io 
We will clear the hash for this clientId manually.

Thank you,
Andrew

**Comment by mnhospitals** [comment]
Its fine, it was test data. Just let me know when the bug is fixed. Thanks!

**Comment by tsv2013** [comment]
@mnhospitals I've updated the site. Could you check it to insure we have no another issues?

**Comment by mnhospitals** [comment]
Works perfect now. Thank you!
