### ISSUE TITLE
Add clientId to survey results

### ISSUE THREAD

**Issue by mnhospitals** [surveyjs/surveyjs#692]
It would be nice to see the clientId in the survey results.

**Comment by tsv2013** [comment]
ClientId is saved in post results. I'll check why it doesn't visible as a result column.

**Comment by mrojas18** [comment]
same here... i would like to see the ClientId as a value in the results, when i process the data i cant access this value.

**Comment by tsv2013** [comment]
I've added the clientid column to the survey results and updated sites.

**Comment by mnhospitals** [comment]
This still does not allow for the clientId to be passed in the REST API call to https://surveyjs.io/api/MySurveys/getSurveyResults.

**Comment by andrewtelnov** [comment]
@tsv2013 Could you please check it out?

Thank you,
Andrew

**Comment by tsv2013** [comment]
This is the page with the results of my survey
![image](https://user-images.githubusercontent.com/3013415/32090712-69231354-baf9-11e7-9282-65a0adefc4da.png)
As you can see client IP address is accessible.
But first you should turn this option on.
Another reason - your result columns can be customized and you need to show corresponding column.
And by default client ID column doesn't visible in public results link, You can change it via `Customize Columns` button on the results page.

If this doesn't help we'll need to check your certain survey.

**Comment by tsv2013** [comment]
@mnhospitals @andrewtelnov I'll check the API right now

**Comment by tsv2013** [comment]
@mnhospitals @andrewtelnov 
The `IPAddress` column is present in the API results as well:
![image](https://user-images.githubusercontent.com/3013415/32091536-4ff785aa-bafd-11e7-9184-062e7cca4ad2.png)
