### ISSUE TITLE
Cannot set requiredText to an empty string anymore?

### ISSUE THREAD

**Issue by sco2tbold** [surveyjs/surveyjs#693]
### What is the current behavior?
We have all questions as mandatory and thus the asterisk is not necessary but visually annoying. Formerly it was possible to set the property requiredText="". 

### What is the expected behavior?
As soon as I set requiredText="" then it's restored to requiredText="*". 

It would be great if you can consider to bring back this simple feature. Thanks!

**Comment by andrewtelnov** [comment]
@sco2tbold I do not do it on purpose. I am rewritting the way we are working with properties and sending notification on properties changing. If the value is empty it returns the default value. Right now the library deals with empty string as underfined property value. I will change it.
I will fix this issue. As a workaround you may set `survey.questionTitleTemplate = "{no}. {title}:";`

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@sco2tbold The fix will be available in the next release.

Thank you,
Andrew
