### ISSUE TITLE
Vue onQuestionAdded does not work.

### ISSUE THREAD

**Issue by usamaSaddiq** [surveyjs/surveyjs#695]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
onQuestionAdded does not work.

### What is the expected behavior?
Hey I have been testing this event and this one does not fire, plus another thing onAfterRenderQuestion fires 2 times, is that how that is supposed to work because that was I was after the first time.

but anyhow onQuestionAdded does not fire when a new question is added.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://jsfiddle.net/wgvs05z0/

### Specify your

* browser: Chrome 
* browser version: 30.0.1577
* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version: 0.12.30 (latest)

**Comment by andrewtelnov** [comment]
@usamaSaddiq You have created the second instance of Survey Model on mount function. The second instance doesn't have onQuestionAdded event.
Here is the corrected version: https://jsfiddle.net/wgvs05z0/2/

Thank you,
Andrew

**Comment by usamaSaddiq** [comment]
@andrewtelnov  Thanks for that one andrew.

I have been struggling to get ahold of the docs, anywhere there might be some examples of the methods implemented?

**Comment by usamaSaddiq** [comment]
Tried exploring this link: https://surveyjs.io/Documentation/Library/?id=surveymodel but there is no method like addNewQuestion or similar helper methods.

Plus explored this link: https://surveyjs.io/Examples/Library/ 

But just couldn't find anything of help.

Any helper methods for accessing already rendered json, because vue doesn't allow you to edit the 
DOM conventionally. 


Cheers

**Comment by andrewtelnov** [comment]
@usamaSaddiq You are adding questions/panels into the page object, https://surveyjs.io/Documentation/Library/?id=pagemodel
However, I am absolutely agree, there should be an example of creating the survey in code from scratch. It is actually in our TODO list. We just busy with other things, but we will add these examples as well later.

Thank you,
Andrew
