### ISSUE TITLE
Boolean field in matrix cell type

### ISSUE THREAD

**Issue by murrah** [surveyjs/surveyjs#696]
### Are you requesting a feature, reporting a bug or ask a question?
Feature

### What is the current behavior?
In the online editor the list of questions types in the Matrix column Cell Type drop down list does not include the Boolean question type. 

### What is the expected behavior?
It would be great if it did. :-) As a workaround I am using a single Checkbox but the Boolean would be neater.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

Thanks!

**Comment by andrewtelnov** [comment]
@murrah Yes, it makes sense. We will do it after v1.0 release :-)

Thank you,
Andrew

**Comment by murrah** [comment]
Cool! Thanks Andrew.

**Comment by andrewtelnov** [comment]
Here is the example: https://plnkr.co/edit/pjOgBE?p=preview
