### ISSUE TITLE
Sequence of text processing

### ISSUE THREAD

**Issue by murrah** [surveyjs/surveyjs#697]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
I have a Comment question type with a description property that has a custom parameter:

"description" : "Regarding your goal of: {p\_itc\_improvementgoal}, what happened?"

All good. I wanted the data substituted for the parameter to be &lt;strong&gt; so I added markdown (I am using Showdown) so it looked like this:

"description" : "Regarding your goal of: **{p\_itc\_improvementgoal}**, what happened?"

and (of course) the \_itc\_ bit of the parameter was converted to &lt;em&gt;itc&lt;/em&gt; so then the parameter would not be replaced because it was "corrupted" by the html:
ie = {p&lt;em&gt;itc&lt;/em&gt;improvementgoal}

### What is the expected behavior?
I was wondering whether the sequence could be changed to do the parameter substitution *before* the onTextMarkdown() ? As a workaround I changed the parameter token to remove the "markdown syntax" ( ie parameter token is now **{pxitcimprovementgoal}** ) , so all good for now.

In other parts of my app the data that is substituted is a whole paragraph and I might want to include markdown in that block of text. Under the current sequence the markdown conversion would occur **before** the paragraph of data had been substituted so the substituted paragraph would contain the markdown syntax and not the converted html. 

So, would it work if the parameter substitution was done *before* the onTextMarkdown() process runs? 

Thanks,
Murray.

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version: v0.12.30

**Comment by andrewtelnov** [comment]
@murrah I would say it is a bug. It is unexpected behaviour. I will work on the fix.

Thank you,
Andrew

**Comment by murrah** [comment]
Again, thank you!
