### ISSUE TITLE
DXSurvey with custom question types

### ISSUE THREAD

**Issue by enricribas** [surveyjs/surveyjs#698]
### Are you requesting a feature, reporting a bug or ask a question?

question or feature

### What is the current behavior?

We like using dxsurvey but we have custom question types that do not work, specifically for currency formatting at the moment. Is there a way to set it up so we can set type to "currency"?
Barring that we could download and host ourselves for our use in creating surveys not for our clients to create surveys.

Does that require a commercial license?
If so, what options do we have for creating surveys with custom question types with a UI?

Thanks,

**Comment by andrewtelnov** [comment]
@enricribas We are planning to add this functionality. However, we are going to add it after we will introduce orgranization/user collabaration into dxsurvey.com.
We see it as: There will be the list of custom widget/additional question types and customer may enabled/disabled them for his organization.
To be honest, I can't give you any timeframe about this functionality. Plus we are planning to add it into the paid subscription.
I would recommend to create your own Survey Management System by using our Editor. In this case you will be able to handle everything by yourself. So far we have only [php example of this Service](https://github.com/surveyjs/surveyjs-php).  We are planning to work on ASP.Net MVC version.

Thank you,
Andrew

**Comment by enricribas** [comment]
Thanks for your response. My followup question would be if we build something like your php example, (probably not in PHP, probably Ruby or Elixir) and we only use it internally and not for our customers, is that considered a commercial usage for the editor source code?

Thank you.
Enric

**Comment by andrewtelnov** [comment]
@enricribas If you are working in non-profitable organization or do it for personal usage, then you should not buy the commercial license.
However, if you organization/company gets the profit, you will have to buy a developer license...
The most our customers use SurveyJS Editor in their intranet applications, where employees are creating and feeling the surveys/forms. Editor and Survey are built-in into corporate web application.

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
wrong link, it should be https://github.com/surveyjs/surveyjs/issues/567
