### ISSUE TITLE
update survey form into write only

### ISSUE THREAD

**Issue by xiuzhen1103** [surveyjs/surveyjs#699]
### What is the current behavior?
I understand 
`survey.mode = 'display'; ` is for read only model.  
I have `survey.mode = '' "` to convert back to survey form, not sure if this is correct. 

I included custom widget for image picker, however when I switch between ready only and form mode, image picker still exist on ready only mode. Would you help me with this, please?  

### What is the expected behavior?
Currently, I have a page default to read only, when certain action happens. I would like to convert it to survey form 

#### Provide the test code and the tested page URL (if applicable)
https://surveyjs.io/Examples/Library/?id=survey-displaymode&platform=Reactjs

**Comment by andrewtelnov** [comment]
@xiuzhen1103 The default value is 'edit', so your code should be:
```
survey.mode = 'edit';
survey.currentPageNo = 0;
```

Thank you,
Andrew
