### ISSUE TITLE
goNextPageAutomatic property should not work for checkbox/matrix

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#70]
If goNextPageAutomatic property set to true, on answering all questions, the survey goes on the next page.
It should not work for checkbox and matrix questions. Currently, on setting on check, the survey goes on the next page which is wrong.

**Comment by andrewtelnov** [comment]
4 questions support this property only: radio, dropdown, rating and text.
For more information take a look at unit test: "goNextPageAutomatic: should not work for complex questions like matrix, checkbox, multiple text".

**Comment by elsigh** [comment]
I've found a bug where if you set the `valueName` property on a checkbox type item and `goNextPageAutomatic: true` it automatically jumps to the next page upon the first click of a checkbox. I'm guessing it's some part related to the code that looks like `this.tryGoNextPageAutomatic(name);`

**Comment by elsigh** [comment]
^ Actually, I don't know why I was using valueName vs just name and title in my test fwiw. When using name+title all works as expected so this may be a non-issue

**Comment by andrewtelnov** [comment]
@elsigh It sounds as a bug to me. It is a valid scenario. We will look at it.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@elsigh I have reproduced the bug in a unit test and fix it. The fix will be available in the next release.

Thank you,
Andrew

**Comment by elsigh** [comment]
Nice work!
