### ISSUE TITLE
Matrix cell render event?

### ISSUE THREAD

**Issue by murrah** [surveyjs/surveyjs#700]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the expected behavior?
I would like to modify the dom of a specific cell in a matrixdynamic question type. I know I can use afterRenderQuestion() to modify the dom for non-matrix type questions. Is there a way to listen for when a matrix cell is rendered? I can't seem to find such a thing.

Thanks.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@murrah Indeed it doesn't called. The problem that the cell questions do not have the full rendering. To be honest, I do not know how to solve this in a good way.
What is problem you trying to solve? Maybe we will may deal with it in a different way?

Thank you,
Andrew

**Comment by murrah** [comment]
Thanks Andrew.

Each row has 5 cells. In one of them I wanted to add a tooltip because it is a single checkbox that needs a little explanation. I have added a "tooltip" property for the tip text to the model via
`Survey.JsonObject.metaData.addProperty("questionbase", "tooltip");`

For "normal" questions I use the `afterRenderQuestion` method to set the tooltip text via  the element's `title` attribute (at this stage). Later I will do a proper css tooltip. 

So, for the cell questions I was hoping I could get the relevant question dom rather than using  `afterRenderQuestion` on the whole matrix and drilling down through the table to fnd the questions with a `tooltip` property. I could use the checkbox question `id` property but I can't see how to know what it will be in advance.

Any suggestions are most welcome!

**Comment by murrah** [comment]
Related to this is some confusion about event names.

At present I am using the following which gets called for each question, which is what I want.

    surveyModel = new Survey.Model(j);
    surveyModel.afterRenderQuestion = function(q, options){
          // Do something with the question dom via options
    };

I see there is also an example like this:
    
    surveyModel.onAfterRenderQuestion.add(function (sender, options) {
          // Only seems to be called once. On the first question only.
    });

While these have the "same" name semantically ie `afterRenderQuestion` and  `onAfterRenderQuestion` it seems that they do different things. Is that correct? Am I implementing a question-by-question after render in the correct way? If not maybe that will help me with the tooltip problem.

I am using the jQuery version.
Thanks.

**Comment by andrewtelnov** [comment]
@murrah The correct way is to use onAfterRenderQuestion event: https://surveyjs.io/Documentation/Library/?id=surveymodel#onAfterRenderQuestion
In fact, you are overridden afterRenderQuestion function. Here is the code:
```
    afterRenderQuestion(question: IQuestion, htmlElement) {
        this.onAfterRenderQuestion.fire(this, { question: question, htmlElement: htmlElement });
    }
```

About tooltips. I think it makes sense to add this feature into the library. Do you show the tooltip over question inputs? 
About matrix cells, I am not sure what is the best solution: show the tooltip over every cell or over the column header. What do you think?

Thank you,
Andrew

**Comment by murrah** [comment]
@andrewtelnov 
1. Thanks for the syntax. I realised I was overriding the method and was using an example I found somewhere. Now I get it. Thank you.
2. Tooltips: At this stage I am just setting the title attribute on the dom element. The equivalent of:
    options.htmlElement.title = options.question.tooltip;
That sets it on the question wrapper so it pops up when over either the question title, input or description which I think is good. User's don't necessarily know there IS a tooltip so being a bit generous in where they mouse over is helpful, I reckon.
3. Matrix cells: Over every cell I think. That is where the user's mouse will go and they won't know there is a tip, as per point 2.

Once I sorted out the issue with the matrix cell dom manipulation I was going to implement something like this example as a way to have reasonable looking tooltips. Perhaps there is a better solution available within the libraries you already use? This is new territory for me so I was just working through ideas.
[https://www.w3schools.com/howto/howto_css_tooltip.asp](https://www.w3schools.com/howto/howto_css_tooltip.asp)

Thanks again, Andrew. I am really enjoying using surveyjs and it opens the possibility for more than just surveys in my app. Thinking about forms, automated workflow, electronic training, induction, etc. Not commercial at this early developmental stage but very happy to go commercial license if everything works out.

Cheers,
Murray

**Comment by andrewtelnov** [comment]
@murrah I've got you about 3. Makes sense.
About 2. Do you want to display it over all question elements, including title/description or just over question input area?

Thank you,
Andrew

**Comment by murrah** [comment]
@andrewtelnov All elements I reckon. That is how it is working if I assign as per above post and it seems to work well that way. The idea is to explain the "question" as a whole, not just what one should type into the input field - there is a placeholder for that anyway. :-)

**Comment by murrah** [comment]
@andrewtelnov Just a follow up for clarification re the tooltip on matrix cell checkbox groups. I am proposing that the tooltip be per checkbox. ie the target el is the wrapper div around each checkbox and label so a mouseover of the box or the label will produce the tooltip for that one option. eg:

    <div class="checkbox" title="My tooltip text goes here" style="margin-right: 5px; display: inline-block;">

The reason is that we don't have room for a description field on cell checkbox options and want some way of offering a more detailed description / guidance on what ticking / unticking the box will mean.

If we were using a "real" tooltip via css the same would apply regarding which html element is the mouseover target - ie the wrapper for both the checkbox and its label.

Thanks again, Andrew.

**Comment by andrewtelnov** [comment]
@murrah I will work on it in several days, I will come back here, so you may check it on the dev version.

Thank you,
Andrew

**Comment by murrah** [comment]
@andrewtelnov Thanks Andrew. Great service! :-)

**Comment by andrewtelnov** [comment]
@murrah Sorry, I have just read carefully your comment that you have made two days ago.
I was going to implement:
tooltip property for all questions + matrix column,
It would show tooltip when somebody move the mouse over the question or matrix cell.
Do you want to have the tooltip for every element for radiogroup or checkbox questions (cellTypes)?

Thank you,
Andrew

**Comment by murrah** [comment]
@andrewtelnov Yes, what you describe for all questions and matrix column would be useful. 

What I also had in mind was the ability to have a tooltip for each choice in the checkbox (I hadn't thought about radio groups but yes, the same would apply). This would be useful for check boxes in normal questions too although my main need is within matrix cells.

Each row of a matrix represents a person. A checkbox / radio group in a column of a cell with 2 options eg:
"On hold" - tooltip would say eg "Tick this box so the person on this row will be placed "on hold"
"Resend email" - tooltip would say eg "Tick this box to resend the email to this person"

Thanks again,
Murray

**Comment by andrewtelnov** [comment]
@murrah The problem that it will be easy enough to implement for question and cells and I am not sure, how to implement it for every choice in checkbox and radiogroup.
I think I will do it on question and column level first and then I will think about adding it into choices.

Thank you,
Andrew

**Comment by murrah** [comment]
@andrewtelnov Yes, I understand. Once you complete the onAfterRenderMatrixCell event I could apply the tooltip to the dom "manually" for each option. Each check box is in its own div. See below. So if I get a ref to the td element or the form-inline div it will be simple to amend the dom on the fly.

    <td>
        <div class="form-inline">
            <div class="checkbox" style="margin-right: 0px; display: inline-block; width: 100%;">
                <label class="">
                    <input type="checkbox" value="1" id="sq_123i" style="margin-right: 3px;"><span class="checkbox-material" style="margin-right: 5px;"><span class="check"></span></span><span><span>On&nbsp;hold</span></span>
                </label>
            </div>
            <div class="checkbox" style="margin-right: 0px; display: inline-block; width: 100%;">
                <label class="">
                    <input type="checkbox" value="2" style="margin-right: 3px;"><span class="checkbox-material" style="margin-right: 5px;"><span class="check"></span></span><span><span>Resend&nbsp;email</span></span>
                </label>
            </div>
        </div>
    </td>

**Comment by murrah** [comment]
@andrewtelnov Or maybe I misunderstood about that proposed event? If you are not going to do that any time soon I will manage it myself via the onAfterRenderQuestion on the matrix question and drill down to the cell dom from there.

**Comment by andrewtelnov** [comment]
@murrah I have just added the [onMatrixAfterCellRender event](https://github.com/surveyjs/surveyjs/issues/709). 
For now, you should be fine. You will be able to set your tooltip. I think we will add tool tip support later, since you are already done them for all other questions.

**Comment by murrah** [comment]
@andrewtelnov Fantastic Andrew! I will test it out this morning. :-)
Thanks,
Murray

**Comment by andrewtelnov** [comment]
@murrah I will have to update the dev version then. The changes will be in the next release only.

Thank you,
Andrew

**Comment by murrah** [comment]
@andrewtelnov All good Andrew. The next release is fine. You do a great job of getting stuff done. Thanks!
