### ISSUE TITLE
Submitting each page of form

### ISSUE THREAD

**Issue by wollerman** [surveyjs/surveyjs#701]
### Submitting each page of form Question

Is it possible to submit the form on each 'next'? I would like to make sure results are saved between surveyjs pages. Right now, when the page is refreshed, all information is lost. 

Thanks,
-Matt

**Comment by andrewtelnov** [comment]
@wollerman Please take a look at this property: https://surveyjs.io/Documentation/Library/?id=SurveyModel#sendResultOnPageNext

Thank you,
Andrew

**Comment by wollerman** [comment]
Perfect. Thank you!
