### ISSUE TITLE
Loading survey data doesn't work for Number and 0 values

### ISSUE THREAD

**Issue by jason-russell** [surveyjs/surveyjs#704]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a Bug

### What is the current behavior?

Setting the value for a number-type to be 0 does not render the number

### What is the expected behavior?

The number 0 should be rendered in the result

### How would you reproduce the current behavior (if this is a bug)?

So in this line I am specifying that the number of spiders I have eaten is 0

`survey.data = {spiders: 0, name:'John Doe'};`

But when the survey is rendered, the numeric value is not displayed

#### Provide the test code and the tested page URL (if applicable)

```
Survey.Survey.cssType = "bootstrap";
Survey.defaultBootstrapCss.navigationButton = "btn btn-green";
window.survey = new Survey.Model({ questions: [
    {type: "text", name: "name", title: "Your name:"},
    {type: "text", name: "spiders", title: "Spiders eaten today:", inputType:"number"}
]});

survey.onComplete.add(function(result) {
    document.querySelector('#surveyResult').innerHTML = "result: " + JSON.stringify(result.data);
});

survey.data = {spiders: 0, name:'John Doe'};

$("#surveyElement").Survey({ model: survey });
```

### Specify your

* browser: **chrome**
* browser version: 
* surveyjs platform (angular or react or jquery or knockout or vue): **jquery**
* surveyjs version: **v0.12.30**

**Comment by andrewtelnov** [comment]
@jason-russell Indeed, it was a bug. I have fixed it.

Thank you,
Andrew

**Comment by jason-russell** [comment]
Awesome, thanks for the quick fix!
