### ISSUE TITLE
onPartialSend

### ISSUE THREAD

**Issue by Iphoning** [surveyjs/surveyjs#705]
### Are you requesting a feature, reporting a bug or ask a question?
How to implement this method?
It is actually don't work for me

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
///<reference path="../../../node_modules/survey-react/survey.react.d.ts"/>
import * as React from 'react';
import { Survey, defaultBootstrapCss } from 'survey-react';

export default class KidsSurvey extends React.Component<any, any> {
    public state: any;
    constructor(props: any) {
        Survey.cssType = 'bootstrap';
        defaultBootstrapCss.navigationButton = 'btn btn-primary';
        super(props);
        this.state = {
//have some json with 3 pages
            surveyJSON: ....
        };
    }

    render() {
        if (this.state.surveyJSON) {
            return <Survey json={this.state.surveyJSON}
                           onComplete={this.sendDataToServer}
                           sendResultOnPageNext={true}
                           onPartialSend={this.testsdf}
            />;
        }
        return <div>Loading...</div>;
    }

    testsdf(data: any) {
//cant even get there!!!!
        console.log(2222);
        console.log(data);
    }
   sendDataToServer(data: any){
   //this works fine!!!!
  }
}


```

### Specify your

* browser: chrome
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version:0.12.30

**Comment by Iphoning** [comment]
Actually I just need some callback on each page. It would be awesome to set this callback via page parameter
`"pages" : [
{
"name": "page1",
"onComplete": "callbackName",
"onValidate": "callbackName",
"doNext": "callbackName",
]`

Something like this maybe

**Comment by andrewtelnov** [comment]
@Iphoning Please use "sendResultOnPageNext" in the JSON. We do not process "sendResultOnPageNext" as react attribute.

Thank you,
Andrew
