### ISSUE TITLE
Changing choices in a matrixdropdown

### ISSUE THREAD

**Issue by faso** [surveyjs/surveyjs#706]
### Are you requesting a feature, reporting a bug or ask a question?
Question

Is it possible to dynamically change choices for a column in a matrixdropdown question? I want to change the possible choices from javascript after the survey has been rendered.

**Comment by andrewtelnov** [comment]
@faso Here is the example on changing choices on changing another cell in the same row: https://plnkr.co/edit/r80ZfA?p=preview
You may likely need another event. [onMatrixCellCreated](https://surveyjs.io/Documentation/Library/?id=surveymodel#onMatrixCellCreated)

Thank you,
Andrew

**Comment by faso** [comment]
Thanks for your reply.

But you see, I need it the other way around. I have a matrixdropdown with three columns of dropdown boxes. When I change a value in a previous question, I want to update the choices in the matrixdropdown.

If i try something like `question.columns[0].choices = myChoices;` it does not work.

**Comment by andrewtelnov** [comment]
@faso I did not test the code, but you may do something like this:
```
var rows = matrixQuestion.visibleRows;
for(var i = 0; i < rows.length; i ++) {
  //i rows, first cell/column
  rows[i].cells[0].question.choices = myChoices;
}
```

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
You code doesn't work, because the quetion has been already created...
