### ISSUE TITLE
Have width of dropdown dependent on the maximum width of an answer

### ISSUE THREAD

**Issue by ZakMiller** [surveyjs/surveyjs#71]
<img width="818" alt="screen shot 2016-09-24 at 12 11 47 pm" src="https://cloud.githubusercontent.com/assets/18072671/18809674/29742ffa-8250-11e6-802a-5909bfb3a86d.png">
Specifically this would be helpful for a dropdown that had something like years, 1900-2016, where the width is currently much larger than necessary.

**Comment by andrewtelnov** [comment]
Hi @Splinterfloss,
I agree, that in many cases it doesn't look great. I am using 'form-control' class for input elements in bootstrap version. This class defines width as '100%'.
There are several solutions for this problem:
1) set a question width attribute to 'auto': `{ type: "dropdown", name: "q1", choices: [1, 2, 3],  width: "auto" }`
2) Override surveyjs css classes, here is the [example](http://surveyjs.org/examples/survey-customcss.html). You need to change survey.css.dropdown property: `mySurvey.css.dropdown = "myNewClass"`;
3) Fix it on bootstrap css level: override the bootstrap 'form-control' class or add a custom rule for select element.

Please let me know if it helps.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@ZakMiller We have added question.width property some times ago.
Here is the example: https://plnkr.co/edit/JwIuOw9x3UjWIXsHP144?p=preview

Thank you,
Andrew
