### ISSUE TITLE
onAfterRenderQuestion doesn't work correctly in vue platform

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#711]
It pass html element without title and errors

**Comment by snay** [comment]
btw, what's the correct behaviour?
Should the event be triggered on each question render or only if model changed?
After #684 it was on each render (let's say, after page change) and now it shows the laziness in full, afaiu.

**Comment by andrewtelnov** [comment]
@snay It passed the incorrect html element into the event. Right now, the current wrong version, passes into options.htmlElement the input html element of the question, where it should pass an element that contains: question title, question description, question errors and question input elements.

I was doing an example: https://surveyjs.io/Examples/Library/?id=survey-afterrender and it works for all platforms except vue. I have fixed the issue.

Right now we are calling onAfterRenderXXX events on mounted function. We do not call it on updated function at the current moment.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@snay You may also be interesting in this enhancement: https://github.com/surveyjs/surveyjs/issues/714
You have function isDefaultRender that will return true, so the default rendering will be available.
I am thinking about adding updateRender() function in the custom widget, It will be called on updated function. I am not sure, do we need it or not.
Also you may just use your own vue component, instead of the default vue question component.

Thank you,
Andrew
