### ISSUE TITLE
Preact vs React 16

### ISSUE THREAD

**Issue by mellogarrett** [surveyjs/surveyjs#718]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
Everything under the hood renders with Preact

### What is the expected behavior?
I want to use a library on top of SurveyJS that requires React 16. How would I go about replacing Preact with React 16??

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@mellogarrett Why don't want to use the SurveyJS react version in this case?
To be honest, we have never try react + preact. The whole point of using preact, is to avoid using react libraries and as result decrease the size.

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
we don't support react 16 yet, I think we should try it

**Comment by andrewtelnov** [comment]
We stopped using preact since January.

Thank you,
Andrew
