### ISSUE TITLE
custom property choices attribute is not rendering properly

### ISSUE THREAD

**Issue by editplus86** [surveyjs/surveyjs#719]
I am adding a new "question base" property which is dropdown in nature like choicesOrder.
When it render to question edit model (Editor) it shows [object,object] in <select> and value for <option> not set.
 
Survey.JsonObject.metaData.addProperty("question", {name: "customProperty", choices: [ {"value": "USA", "text": "United States of America"}, {"value": "GBR", "text": "Great Britain"} ] });

Thanks & Regards
John

**Comment by andrewtelnov** [comment]
@editplus86 There is a way to implement it by using this code:
```
Survey.JsonObject.metaData.addProperty("question", {name: "customProperty", choices: [ "USA", "GBR"] });
SurveyEditor.defaultStrings.pv["USA"] = "United States of America";
SurveyEditor.defaultStrings.pv["GBR"] = "Great Britain";
```
However, I would agree that your code is cleaner. It doesn't support the localization, but the most people doesn't need it.
So I would consider this as a usability bug in API.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Here is the plunker example: https://plnkr.co/edit/TyxwpRfCnQDtcDROzfJC?p=preview

**Comment by editplus86** [comment]
Thank you Andrew,
The workaround is perfectly fine. 👍

**Comment by andrewtelnov** [comment]
@editplus86 After the next update, your code will work as well:
`Survey.JsonObject.metaData.addProperty("question", {name: "customProperty", choices: [ {"value": "USA", "text": "United States of America"}, {"value": "GBR", "text": "Great Britain"} ] });`

Thank you,
Andrew
