### ISSUE TITLE
Editing a submitted survey by clientId

### ISSUE THREAD

**Issue by mnhospitals** [surveyjs/surveyjs#721]
I am wondering if there is any functionality to allow a user (clientId) to go back into a survey after they have submitted the survey and change their answers?

**Comment by andrewtelnov** [comment]
@mnhospitals Are you talking about this API: http://api.dxsurvey.com/Help/Index?
It is intergrated into SurveyJS. I guess we may add a new method into our public API:
api/Survey/getClientResult?resultId={resultId}&clientId={clientId}
It will return the survey JSON result, if succeed.
Let me know if you need this functionality.

Thank you,
Andrew

**Comment by mnhospitals** [comment]
Hello Andrew,

Currently, when using the clientId functionality, when you render the survey it shows that they have entered. But we are looking for the ability to then edit those answers. So the process would be having the user fill out the survey, but once they render the survey again with the same clientId, instead of showing the message that they have already entered, show the survey with their answers. Then, those changes made would update the results object already saved by that clientId.

Thanks,
Matt

**Comment by andrewtelnov** [comment]
@mnhospitals Just to be 100% clear, you are talking about our service, am I right?
In this case, we will add this functionality, maybe on the next week.

Thank you,
Andrew

**Comment by legreco** [comment]
i want to save and edit incomplete survey to my backend? 
How can i do that?

**Comment by andrewtelnov** [comment]
@legreco survey.data contains the survey result as JSON. You may save them onCurrentPageChanged event, https://surveyjs.io/Documentation/Library/?id=surveymodel#onCurrentPageChanged
and onComplete event.
You may do it on timer, let's say every 60 seconds, it is up to you.

Thank you,
Andrew

**Comment by mnhospitals** [comment]
Does this also work with completed surveys? And how would I get the data out from the service by clientId. e.g loadSurveyFromService(clientId)

**Comment by tsv2013** [comment]
@mnhospitals Currently our service hasn't functionality that returns result data by resultId and clientId. You can obtain only whole results data array. Could you please specify - what manipulations you want to do with already posted data for completed survey? What is your certain scenario?

More over - I see potential privacy violation problems if we will have public API that will return de-anonymized answers.
