### ISSUE TITLE
Regex validation doesn't work with "other" values

### ISSUE THREAD

**Issue by juleslui** [surveyjs/surveyjs#722]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
A regex validator isn't fired when entering custom values on checkbox or radiogroup questions (through choosing the "Other" option). The validator fires fine with normal textbox questions.

### What is the expected behavior?
A regex validator is fired when entering custom values on checkbox or radiogroup questions (through choosing the "Other" option)

### How would you reproduce the current behavior (if this is a bug)?
1. Go to SurveyJS Survey Editor
2. Place a checkbox or radiogroup question onto the page
3. Allow question for "Other" value
4. Add regex validator to question with the following regex expression "[a-zA-Z0-9 .,!?;'\/]+".
5. Test Survey.
6. Choose "Other" option.
7. Enter Japanese characters.
8. Survey accepts the value.

### Specify your

* browser: Chrome
* browser version: 61.0.3163.100 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): Angular
* surveyjs version:

**Comment by andrewtelnov** [comment]
@juleslui I just did not think about "other" value, but if there is the validator in the question, I guess, I may run it against the other value as well.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@juleslui The bug is fixed. The fix will be available in the next minor update.

Thank you,
Andrew

**Comment by juleslui** [comment]
Thank you so much! How would I know when it's out? I'm currently using the survey-angular package.

**Comment by andrewtelnov** [comment]
@juleslui The new version is released.

Thank you,
Andrew
