### ISSUE TITLE
Equivalent of ionViewCanGoBack

### ISSUE THREAD

**Issue by juleslui** [surveyjs/surveyjs#723]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question

### What is the current behavior?
The only available lifecycle events available are for if the user leaves the page by either popping or pushing a new one. I'd like a lifecycle event for just the former to check if the user decides to leave mid form instead of checking even when the form is accomplished and the user proceeds to the next page.

### What is the expected behavior?
An available lifecycle event for just checking if the user is popping a page (going back through the navigation stack).

### Specify your

* browser: Chrome
* browser version: 61.0.3163.100 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): Angular
* surveyjs version:

**Comment by andrewtelnov** [comment]
@juleslui I am not sure, if I understood you correctly. Do you need this?
[survey.onCurrentPageChanged event](https://surveyjs.io/Documentation/Library/?id=surveymodel#onCurrentPageChanged)
and [Page.visibleIndex property](https://surveyjs.io/Documentation/Library/?id=pagemodel#visibleIndex)

It will allow you to find out, if a user go to the next page or back.

Thank you,
Andrew

**Comment by juleslui** [comment]
Thank you so much for your reply, good sir, but this was my bad. I posted this on the wrong repository.

I'll be closing this now.

Sorry for the confusion.
