### ISSUE TITLE
Version 0.12.33 not working firefox 56

### ISSUE THREAD

**Issue by rlouissidney** [surveyjs/surveyjs#726]
But works with chrome, ie, opera
Tested page URL:  https://surveyjs.io/Editor/Editor/
### Specify your
TypeError: _this.sheet.addRule is not a function[En savoir plus]  survey.ko.js:14721:80
	StylesManager</StylesManager.prototype.initializeStyles/< https://surveyjs.azureedge.net/0.12.33/survey.ko.js:14721:80
	forEach self-hosted:269:13
	StylesManager</StylesManager.prototype.initializeStyles https://surveyjs.azureedge.net/0.12.33/survey.ko.js:14721:9
	StylesManager https://surveyjs.azureedge.net/0.12.33/survey.ko.js:14698:13
	<anonyme> https://surveyjs.azureedge.net/0.12.33/survey.ko.js:8734:29
	__webpack_require__ https://surveyjs.azureedge.net/0.12.33/survey.ko.js:30:12
	<anonyme> https://surveyjs.azureedge.net/0.12.33/survey.ko.js:12710:67
	__webpack_require__ https://surveyjs.azureedge.net/0.12.33/survey.ko.js:30:12
	<anonyme> https://surveyjs.azureedge.net/0.12.33/survey.ko.js:14909:72
	__webpack_require__ https://surveyjs.azureedge.net/0.12.33/survey.ko.js:30:12
	<anonyme> https://surveyjs.azureedge.net/0.12.33/survey.ko.js:76:18
	<anonyme> https://surveyjs.azureedge.net/0.12.33/survey.ko.js:11:18
	webpackUniversalModuleDefinition https://surveyjs.azureedge.net/0.12.33/survey.ko.js:9:20
	<anonyme> https://surveyjs.azureedge.net/0.12.33/survey.ko.js:1:11
TypeError: __WEBPACK_IMPORTED_MODULE_3_survey_knockout__ is undefined[En savoir plus]  surveyeditor.js:4280:1
ReferenceError: SurveyEditor is not defined[En savoir plus]

* browser:  Firefox
* browser version: 56.0.1
* surveyjs platform (angular or react or jquery or knockout or vue): knockout
* surveyjs version: 0.12.33

**Comment by rlouissidney** [comment]
Investigate a little, it  seems addRule doesn't exist in Firefox, use insertRule instead ?
http://help.dottoro.com/ljuucnct.php

**Comment by andrewtelnov** [comment]
@rlouissidney Yes, we will fix it ASAP and release a new version.

Thank you,
Andrew

**Comment by tsv2013** [comment]
I've changed `addRule` -> `insertRule`
