### ISSUE TITLE
Image selector with choices restful on iOS opens native select

### ISSUE THREAD

**Issue by gaurav-singhal** [surveyjs/surveyjs#727]
### Are you requesting a feature, reporting a bug or ask a question?

bug

### What is the current behavior?

I am using the image picker with dropdown and rest API calls. On iOS, it popsup the select native wheel even though it is later hidden. I am assuming that this happens because of rest as the sample given on your site works fine.

![img_1595](https://user-images.githubusercontent.com/26900527/31875285-0ebcacec-b7eb-11e7-81b0-1199fd8686c5.png)

### What is the expected behavior?
wheel should either have not opened or closed after select is hidden. Any suggestion how we can handle this?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
Can you post here the exact steps to reproduce this behaviour on our side? Is it reproducable with our examples?

**Comment by gaurav-singhal** [comment]
See this [plnkr](https://plnkr.co/edit/e5kg8it3gB5hYBaziUQc?p=preview). Go prev/next and you will notice the select wheel.

**Comment by tsv2013** [comment]
Thank you for the provided sample. I'll check it and update this thread.

**Comment by gaurav-singhal** [comment]
Thanks!

**Comment by tsv2013** [comment]
Hi, @gaurav-singhal 
You need to set
`"focusFirstQuestionAutomatic": false,`
survey option.

You can check the modified [plunk](https://plnkr.co/edit/5SfXPoWxGH6r7W6zo53s?p=preview).

**Comment by gaurav-singhal** [comment]
Thanks!
