### ISSUE TITLE
add hasComment new property

### ISSUE THREAD

**Issue by guns81** [surveyjs/surveyjs#728]
### Are you requesting a feature, reporting a bug or ask a question?
question

### What is the current behavior?
doesnt show nothing

### What is the expected behavior?
show second textbox

hi,
i'm trying to implement another hasComment property
i want to show 2 textbox. I have try to introduce in survejs (for jquery):

//__WEBPACK_IMPORTED_MODULE_1_react__["createElement"]("div", null, commentText1),
            //__WEBPACK_IMPORTED_MODULE_1_react__["createElement"](__WEBPACK_IMPORTED_MODULE_3__reactquestioncomment__["a" /* SurveyQuestionCommentItem */], { question: this.question, cssClasses: cssClasses })));
	    
it add another textbox but it will be linked to first hasComment property and output json will show only this second property

thanks for all answers

**Comment by andrewtelnov** [comment]
@guns81 We are going to launch the new way of adding custom widgets and plug-ins in several days. Actually the code that support a new approach has been already released. You may take a look how to implement them by looking at these code: https://github.com/surveyjs/widgets/tree/master/src
Probably inputMask is the closest implementation: https://github.com/surveyjs/widgets/blob/master/src/inputmask.js

Let me know if it helps.

Thank you,
Andrew

**Comment by guns81** [comment]
thanks for the answer
but i cant undestand how to use it. 
this will set an input mask on existing textbox am i right?
i need to add a new one with another property like hasComment

let me know and thanks

**Comment by andrewtelnov** [comment]
@guns81 the code just shows the approach. So what is your goal?
You are having hasComment property. Now you want to have hasComment2 boolean property?
If i is set, then show the text box that get/set value as 
```
survey.getValue("questionName_" + "comment2");
survey.setValue("questionName_" + "comment2", val);

```
Something like that?

Thank you,
Andrew
