### ISSUE TITLE
Boolean values don't work in visibleIf expressions

### ISSUE THREAD

**Issue by mdickin** [surveyjs/surveyjs#729]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
`visibleIf` works fine when the values are not "True" or "False". If they are, then it fails to enable visibility.

### What is the expected behavior?
I would expect boolean values to either work as strings (`{MyValue} = 'True'`) or boolean values (`{MyValue} = true`)

I submit the survey result as JSON to a web service, so I'd rather not have to write a custom deserializer to convert "Yes"/"No" to true/false.

### How would you reproduce the current behavior (if this is a bug)?
Use the Plunker below. Note that the first Yes/No question (with values of "True"/"False") does not drive visibility properly. The second Yes/No question (with values of "Yes"/"No") works correctly.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/asfhtPqM9VAtKG7KRHzX?p=preview

### Specify your

* browser: Chrome
* browser version: 61.0.3163.100 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.12.34

**Comment by mdickin** [comment]
Looks like I can get it to work by doing `{MyValue} contains 'true'`

**Comment by andrewtelnov** [comment]
@mdickin Yes, it is definately the bug. I have fixed it, the fix will be available in the next minor release.

Thank you,
Andrew

**Comment by mdickin** [comment]
Awesome, thanks for the quick turnaround! I love the library.
