### ISSUE TITLE
Embedding survey.js survey in wordpress

### ISSUE THREAD

**Issue by javismiles** [surveyjs/surveyjs#73]
Any advice to embed a survey into a page of a wordpress website?
best

**Comment by andrewtelnov** [comment]
Hi @javismiles.
I am thinking about writing a plug-in for it.
Do you need it ASAP?

**Comment by javismiles** [comment]
hey Andrew,
yeah basically I would need it now ;)
but its ok, in the meantime i will host it as a separate page outside of
the wordpress theme, what to do


Ideami Studios
http://torchprinciple.com
http://ideami.com
http://posterini.com
http://incredivid.com
http://fineartphotolux.com

**Comment by andrewtelnov** [comment]
I will spend some time on WordPress widget plugin. I can not make any promises since I have never used WordPress or written any php code before. It is time to learn some php :)

**Comment by javismiles** [comment]
hey,  no probs, no rush, but tell me something urgent
how can I prevent the
"Thank You for Completing the Survey!"
from appearing when  completing the survey? I need to eliminate  it from
there,
thank u
Jav


Ideami Studios
http://torchprinciple.com
http://ideami.com
http://posterini.com
http://incredivid.com
http://fineartphotolux.com

**Comment by andrewtelnov** [comment]
Sure, you may use onComplete event:
```
        survey.onComplete.add(function (s) {
            document.getElementById("mySurveyElementId").style.display = 'none';
         });

```

**Comment by javismiles** [comment]
Thank you very much for your quick reply,
thanks a lot
best


Ideami Studios
http://torchprinciple.com
http://ideami.com
http://posterini.com
http://incredivid.com
http://fineartphotolux.com

**Comment by dmitrykurmanov** [comment]
@javismiles we have the wordpress plugin now, please check https://wordpress.org/plugins/surveyjs/
