### ISSUE TITLE
Measuring time spent on each page (screen)

### ISSUE THREAD

**Issue by P8888** [surveyjs/surveyjs#731]
Hi,
I would like to measure time spent on each question (screen) in my questionnaire. Can anyone help me how to do that using javascript? :) Thank you in advance.

**Comment by andrewtelnov** [comment]
@P8888 Here is the example: https://plnkr.co/edit/ZxIQLg?p=preview

Thank you,
Andrew

**Comment by P8888** [comment]
Thank you very much!
And is it possible to save the information about the time directly on the server into the results from the survey? So that there will be for example an extra column with all the times spent on page for each respondent?

Thank you!
P.

**Comment by P8888** [comment]
Thank you very much for your response!

**Comment by andrewtelnov** [comment]
@P8888 Now, we have a built-in functionality for this: https://surveyjs.io/Examples/Library/?id=survey-quiz

Thank you,
Andrew
