### ISSUE TITLE
example of How to set custom properties in choices restful

### ISSUE THREAD

**Issue by gaurav-singhal** [surveyjs/surveyjs#732]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
Need an example for setting choices restfull custom properties in lib as well as editor. There was a commit recently. So what it changes for us. [commit](https://github.com/surveyjs/surveyjs/commit/176fa520f4f75442149a65319fd1114b383e8309)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
Are you talking about [this](https://surveyjs.io/Examples/Library/?id=questiontype-dropdownrestfull&platform=jQuery) example?

**Comment by gaurav-singhal** [comment]
No I am talking about an example where we can create and access the custom properties in choices restfull. It was working earlier in 0.12.26 but after taking the latest version of 0.12.34 these properties are no longer accessible. So am just wondering if you have change the way.

      `  Survey.JsonObject.metaData.addProperty("itemvalue", "name");`

**Comment by andrewtelnov** [comment]
@gaurav-singhal I have just checked it is here: https://plnkr.co/edit/zuP2xLI0zvUpRXuv9mag?p=preview
I have debuged it and name property is here in run-time as well.

You may now do this: 

`Survey.JsonObject.metaData.addProperty("itemvalue", {name: "name", default: "myDefaultText"});`

All values will be myDefaultText by default in run-time.

Thank you,
Andrew

**Comment by gaurav-singhal** [comment]
As mentioned above want an example for choices restful but the example you are showing is direct adding in choices. I think you have already mentioned in #615 that it was a bug and you have fixed it. waiting for release now.
