### ISSUE TITLE
Radio button input not initially focused

### ISSUE THREAD

**Issue by enricribas** [surveyjs/surveyjs#733]
### Are you requesting a feature, reporting a bug or ask a question?

bug. it seems or doing something wrong again

### What is the current behavior?

focus on first input does not seem to work with radio buttons

### What is the expected behavior?

I would expect to be able to switch to other radio button with arrow keys if input was selected

### How would you reproduce the current behavior (if this is a bug)?

create a page with a radio button in dxsurvey and then test it. Arrow keys do not move input. If you click next and get an error due to validation, then the input is correctly focused

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: 

https://dxsurvey.com/Home/EditSurvey/cc151b92-f270-4dbd-9bbc-47c1d9515805

**Comment by andrewtelnov** [comment]
@enricribas Do you want to focus the first input on the first page?

Thank you,
Andrew

**Comment by enricribas** [comment]
yes, please. I think that makes the most sense, at least for us

**Comment by andrewtelnov** [comment]
@tsv2013 Let's add the code that will focus the first question on published page in our service:
`survey.focusFirstQuestion();`
call it right after the initial rendering.

Thank you,
Andrew

**Comment by tsv2013** [comment]
@andrewtelnov Done
@enricribas I've updated the sites. Please check.
