### ISSUE TITLE
matrixdropdown  trigger on a field

### ISSUE THREAD

**Issue by guns81** [surveyjs/surveyjs#736]
### Are you requesting a feature, reporting a bug or ask a question?
question

Hi Again and thanks for your work.
I have a question about matrixdropdown element.
If i have 2 questions in two rows is possibile to enable the second row only if a field in first row answer is for example "Yes" ?

thanks a lot

**Comment by andrewtelnov** [comment]
Hi,
Here is the example: https://plnkr.co/edit/u1Obq5T4fX0Rc3hJA3AI?p=preview

Thank you,
Andrew

**Comment by guns81** [comment]
ok thanks for the example 
but this works also for 2 questions in different rows? 
thanks a lot

**Comment by andrewtelnov** [comment]
@guns81 Just add one more variable and modify the example accordingly based on your needs.

Thank you,
Andrew

**Comment by guns81** [comment]
this is what i do based on your example:

Survey.Survey.cssType = "bootstrap";
Survey.defaultBootstrapCss.navigationButton = "btn btn-green";

window.survey = new Survey.Model({questions: [
{ type: "matrixdropdown", name: "frameworksRate", title: "Please tells us your opinion about JavaScript MVVM frameworks",
    choices: ["Excelent", "Good", "Average", "Fair", "Poor"],
    columns: [{ name: "using", title: "Do you use it?", choices: ["Yes", "No"], cellType: "radiogroup" }, 
              { name: "experience", title: "How long do you use it?", choices: [{value: 5, text:"3-5 years"}, {value: 2, text:"1-2 years"}, {value: 1, text:"less then a year"}] }
    ],
    rows: [{ value: "angularv1", text: "angularjs v1.x" }
  ]},
{ type: "matrixdropdown", name: "frameworksRate1", title: "Please tells us your opinion about JavaScript MVVM frameworks",
    choices: ["Excelent", "Good", "Average", "Fair", "Poor"],
    columns: [{ name: "using1", title: "Do you use it?", choices: ["Yes", "No"], cellType: "radiogroup" }, 
              { name: "experience1", title: "How long do you use it?", choices: [{value: 5, text:"3-5 years"}, {value: 2, text:"1-2 years"}, {value: 1, text:"less then a year"}] }
    ],
    rows: [{ value: "angularv2", text: "angularjs v1.x" }
  ]}
]});
survey.onComplete.add(function(result) {
    document.querySelector('#surveyResult').innerHTML = "result: " + JSON.stringify(result.data);
});

var cellQuestion = null;

survey.onValueChanged.add(function(survey, options) {
  if(cellQuestion && options.name == "frameworksRate") {
    var val = options.value;
 	  cellQuestion.readOnly = val.angularv1.using != "Yes";
  }
});

survey.onMatrixCellCreated.add(function(survey, options){
  if(options.row.rowName == "angularv2" && options.columnName == "using1") {
    cellQuestion = options.cellQuestion;
    cellQuestion.readOnly = true;
  }
});

this disable the cell in second row but this don't enable again clicking on Yes on first Row
can u help me? 

thank you

**Comment by andrewtelnov** [comment]
@guns81 I have updated the example: https://plnkr.co/edit/u1Obq5T4fX0Rc3hJA3AI?p=preview

Thank you,
Andrew

**Comment by guns81** [comment]
Thanks Andrew,

You have Just added another question on the same Matrix am i right ? 
I have 2 Matrix and i need to make an interaction from first to second

Thnks

**Comment by andrewtelnov** [comment]
@guns81 I see the issue. For some reason pReact doesn't update the rootQuestion/matrix. I made a workaround: https://plnkr.co/edit/k1Q8cHUkHCEbd641g5tW?p=preview

Thank you,
Andrew

**Comment by guns81** [comment]
Oh! thanks!! you are the best :+1: 

so i have to ask you something... 
with normal question i was using enableIf property to disable questions based on previous answer.

if i have tree Matrix and i need to enable the third Matrix if the answer on first is Yes for example do u think i need to add a property for every field and use it?

thnks again!

**Comment by andrewtelnov** [comment]
@guns81 For some reason enableIf doesn't work here. I did not have time to look at it. I will do it soon. Likely there is a bug, but I do not understand where exactly.
The following code should work:
```
survey.onMatrixCellCreated.add(function(survey, options){
  if(options.row.rowName == "angularv2" && options.columnName == "using1") {
    options.cellQuestion.enableIf = "{frameworksRate.angularv1.using} = 'Yes'";
  }
});
```
I will investigate what is wrong here and let you know.

PS: I will mark it as bug, to make sure I do not forget about it. Please do not close it.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@guns81 I have fixed the bug. From the next minor version, the visibleIf/enableIf assign onMatrixCellCreated will work as expected.

Thank you,
Andrew

**Comment by guns81** [comment]
is this fix on 0.12.35? 

thank you Andrew

**Comment by andrewtelnov** [comment]
@guns81 Unfortunately not, I have fixed it on the next day after 0.12.35 has been released.

Thank you,
Andrew

**Comment by tsv2013** [comment]
@guns81 We'll do our best.

**Comment by guns81** [comment]
hi and thanks for your work,
i've seen the release 0.12.36 but if i try to set enableif on the online editor it doesn't work
i've try this for example:
{p1_d1} = 'Yes' on the p2_d2 question

thanks

**Comment by andrewtelnov** [comment]
@guns81 It works fine to me: https://plnkr.co/edit/aoQvM1gmbJK8Nrk5v92H?p=preview

Thank you,
Andrew
