### ISSUE TITLE
Can we use intl-tel-input JQuery plugin with Survey.js?

### ISSUE THREAD

**Issue by akmr9** [surveyjs/surveyjs#737]
### Are you requesting a feature, reporting a bug or ask a question?
requesting a feature

### What is the expected behavior?
Have a country code drop down on the existing telephone field.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here
$("#telId").intlTelInput({
        separateDialCode: true,
        utilsScript: "/Scripts/utils.js"
    });

```

### Specify your

* browser:  Any
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): JQuery
* surveyjs version:

**Comment by akmr9** [comment]
Can we also use stuff like Ladda button spinner.  Because when I do Ladda.Create() it is throwing an error.

**Comment by andrewtelnov** [comment]
@akmr9 We are going to introduce new way of adding custom widgets into our library in several days. In fact the code is already in the released version. Here is the code for inputMask: https://github.com/surveyjs/widgets/blob/master/src/inputmask.js

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
and the example: https://surveyjs.io/Examples/Library/?id=custom-widget-inputmask&platform=jQuery

**Comment by akmr9** [comment]
got it Thanks.
