### ISSUE TITLE
Value of answer before hiding

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#738]
Hi, i have this case:

- 1 standard text answer
- 1 answer with custom widget

The answer with custom widget have a visibleIf condition like {question1 = 'hello'}
The survey have the clearInvisibleValue property like "onHidden"

well, when i write hello on first answer, the second question disappear and custom widget call the function "willUnmount: function(question, el)", but when this function is called, the question.value is already "undefined"... is there a possibility to retrieve the old value of the second answer before the clearInvisibleValue function clears it?

Thank you!

**Comment by tsv2013** [comment]
Can you introduce a local variable (or property in the question) for previous value, use it's value on widget init and update it on value changed?

**Comment by andrewtelnov** [comment]
@care46 clearInvisibleValue will call clearValue method on making the question invisible.
If you set clearInvisibleValue to "onComplete" you get the behavior you need.

Thank you,
Andrew

**Comment by care46** [comment]
@tsv2013 great idea!
