### ISSUE TITLE
isExpanded and isShowing properties

### ISSUE THREAD

**Issue by g87** [surveyjs/surveyjs#740]
Hi,
I'm having some trouble getting  properties isExpanded or isShowing.
For some reason it returns undefined.
I'm using version 0.12.34

I've created an object using the following code.
`var survey = new Survey.Model(surveyJSON);
survey.isShowing`
Does not return any value.

The Survey itself seems to work fine, I've managed to include it in my webpage and it shows up in the corner.

I'm not sure if I'm calling the property incorrectly or not?

Thanks

**Comment by andrewtelnov** [comment]
@g87 Please the following mode:
```
var survey = new Survey.SurveyWindowModel(surveyJSON);
var isShowing = survey.isShowing
```

Thank you,
Andrew

**Comment by g87** [comment]
@andrewtelnov 

I've just tried this and survey.isShowing still returns undefined.
I'm wondering if I'm using it correctly.
I'm also have:
`var surveyWin = new Survey.SurveyWindowModel(surveyJSON);`

 ` $("#surveyContainer").SurveyWindow({
            model: surveyWin.survey,
            onComplete: sendDataToServer
        });`

**Comment by andrewtelnov** [comment]
@g87 I will add an example 
Here is the code:
```
var survey = new Survey.Model(surveyJSON);
$("#surveyContainer").SurveyWindow({ model: survey, expanded: true, onComplete: sendDataToServer });
```

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@g87 I'm trying to make the example and I do not like the way it works right now. I will improve API on the next week and finish with the example.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@g87 I have redesined the API for survey window. 
The old code I have past here, will continue to work. From the next minor update you will be able to use the following code:
```
var surveyWindow = new Survey.WindowModel(surveyJSON);
$("#surveyElement").SurveyWindow({ window: surveyWindow, isExpanded: true });   
```
surveyWindow have the following properties and methods:
expand(), collapse() and isExpanded property on get/set
hide(), show() and isShowing property on get/set

`<button onclick="surveyWindow.show()">Show Survey Window</button>`

Thank you,
Andrew

**Comment by g87** [comment]
@andrewtelnov 
The changes sound good.
When will the new version be released?

**Comment by andrewtelnov** [comment]
@g87 Definately on this week.

Thank you,
Andrew
