### ISSUE TITLE
How to set timer for question and page

### ISSUE THREAD

**Issue by editplus86** [surveyjs/surveyjs#742]
### Are you requesting a feature, reporting a bug or ask a question?
question/feature

### What is the current behavior?
not found this functionality

### What is the expected behavior?
I have requirement to create multi page quiz questionnaire having timer for question and page.
Surveyjs is good fit for this but needs an additional feature or solution how to implement.

Assume I have create custom property for page and question to set the timer value.

1. Each question will have fix time to answer 
    How to start timer as soon as question display in screen ? 
    if user will not answer with time (lets say 10 sec) Surveyjs will show next question and not allow to go back to previous question.

2. Same for Page : Each page have 10 question and have fix time to answer. If user will not complete within time limit then Surveyjs will move to next page and not allow to go back to previous page.

Could you please help me to setup this ?

Thanks & Regards
John

**Comment by andrewtelnov** [comment]
@editplus86 Right now it can be done with some coding, here is an [example with timer](https://plnkr.co/edit/ZxIQLg?p=preview)
You will need to create the [custom navigation](https://surveyjs.io/Examples/Library/?id=survey-customnavigation) to remove the "previous" button.
Here is one more example that you may want to see: https://surveyjs.io/Examples/Library/?id=survey-autonextpage

I like the idea to let developers create quiz without a lot of coding or without coding at all. The following functionality and properties are missed:
1) survey.showPreviousButton, the default is true. Set it to false to disable end-user go to the previous page.
2) survey.timeToAnswer  in seconds, the default value is 0 - do nothing. If it more then 0 then go to the next page after {timeToAnswer) seconds are gone. Page will have the same property as well, if it is 0 then get the value from the survey. It will allow to have different times to different pages.
3) Some properties to show the timer, how much time is left.

I may introduce these properties and functionality already on the next week, if in exchange you provide a good example and we discuss the UI elements.

Additionaly we may introduce the correct results and the cost of the correct answer, so we can show the results after the survey is completed immediately.

Let me know if you willing to work together. I believe in a week we will have the required functionality.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@editplus86 We have a built-in functionality now. Here is the example: https://surveyjs.io/Examples/Library/?id=survey-quiz

Thank you,
Andrew
