### ISSUE TITLE
Make it possible to create a quiz

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#745]
Required functionality
- Disable previous button (**done**)
- Enable timer to calculate time spent on survey and on every page (**done**)
- Time limitation for survey/page - go to the next page/ complete the quiz + show the time (spent/left) (**done**)
- timer panel with progress (**done**)
- Right answers (**done**) 
- Answers cost and score calculation

**Comment by andrewtelnov** [comment]
The demo has been created: https://surveyjs.io/Examples/Library/?id=survey-quiz

**Comment by tizzo** [comment]
Looks like the [react version](https://surveyjs.io/Examples/Library/?id=survey-quiz&platform=Reactjs) isn't working atm. I'm currently evaluating libraries to use for a quiz build.

**Comment by andrewtelnov** [comment]
@tizzo I have fixed the issue. It is working now.

Thank you,
Andrew

**Comment by tizzo** [comment]
I'm currently working on a quiz system based on surveyjs. I'm implementing `Right answers` like this for the simple cases:

``` javascript
 {
   type: 'radiogroup',
   name: 'SurveyJS is a lot of fun',
   choices: [
     {
       value: 'true',
       text: 'True',
       correct: true,
     },
     {
       value: 'false',
       text: 'False',
     },
   ],
 },

```

And I'm implementing a simple answer cost and score calculation system. I'm supporting most of the question types provided by surveyJs so there's handling for different question types but in essence I'm doing similar to the following (but with a bunch of different plugin classes that wrap corresponding survyejs question objects).

``` javascript
let correctAnswers = 0;
let totalAnswers = 0;
for (let question of survey.getAllQuestions()) {
  for (let choice of question.activeChoices) {
    if (choice.correct === true) {
      totalAnswers++;
      if (question.value === choice.value) {
        correctAnswers++;
      }
    }
  }
}
```

I wonder whether you could share more about your roadmap and the architecture for question correctness, grading, providing feedback, etc.  Thanks and again I love your work!

**Comment by andrewtelnov** [comment]
Hello @tizzo,
We are working on release v1.0 right now. We are pretty close. 
We have the question cost and right answers in our TODO list to finish with Quiz completely, but we have decided to postponed it.
I can't tell your the precise time frame. We may work on it in January, but I can't garantee this.
Anyway, if you have any difficulty of implementing what you want, just let us know and we will help.

Thank you,
Andrew

**Comment by tizzo** [comment]
Thanks @andrewtelnov! Yeah, we need to have something working this week. Would love to find a way to contribute my own answer to this problem but I think it's probably not totally a generalizable solution as I'm building something around SurveyJS rather than into it for this specific use case.

**Comment by andrewtelnov** [comment]
Added:
question.correctAnswer, survey.getCorrectedAnswers(), survey.getInCorrectedAnswers() and the following completedHtml is possible: 
`"You have answered correctly {correctedAnswers} on {questionCount} questions. {inCorrectedAnswers} answers are incorrect."

**Comment by skeary-immt** [comment]
Hi,

The ability to do quizzes looks really useful :)

I was looking through the changes and noticed a couple of typos or grammar issues:

* `getCorrectedAnswers()` should probably be `getCorrectAnswers()` or perhaps, even better, `getCorrectAnswerCount()` as the function returns the count and not the actual answers.
* Similarly, `getIncorrectedAnswers()` should probably be `getIncorrectAnswers()` or perhaps, even better, `getIncorrectAnswerCount()`.

Hope you don't mind me making these suggestions and that they're helpful. I also noticed a couple of functions on the Page object that looked like they could be tweaked:

* `Page.hasShown()` to `Page.hasBeenShown()` or `Page.wasShown()`.
* `Page.isQuestionsRandomized()` to `Page.areQuestionsRandomized()`

Cheers,
Simon

**Comment by andrewtelnov** [comment]
@skeary-immt I have modified/added properties names.

Thank you,
Andrew
