### ISSUE TITLE
Custom Widget loaded value missing?

### ISSUE THREAD

**Issue by madceb** [surveyjs/surveyjs#746]
### Are you requesting a feature, reporting a bug or ask a question?
question, possible bug?

### What is the current behavior?
if json data is loaded the value is no where found in widget, is different since version 0.12.32

### What is the expected behavior?
To have the loaded value available to pre select or display data

### How would you reproduce the current behavior (if this is a bug)?
in 0.12.32 I use question.cachedValueForUrlRequests to get the current loaded value, but now since that version I don't see any property with the value.

Also, in select widget example even if the survey has assign a json data to be display, the widget does not show that value, it selects the first item in the list, not the one in the json.

Regards and Thanks,

**Comment by andrewtelnov** [comment]
@madceb Yes, I have changed gettting values from restful services. The property is still there, however it is better do not use it, it is a private property. What do you want to achieve?

Thank you,
Andrew

**Comment by madceb** [comment]
Hello @andrewtelnov, what I'm trying to do it is to preselect in the select2 widget a previously saved data. Using the property mentioned I used to do it in 0.12.32 and back version.
Thanks,

**Comment by andrewtelnov** [comment]
@madceb You may take a code from here: https://github.com/surveyjs/widgets/blob/master/src/select2.js
It supports preselect.
We are going to release new custom widgets approach on this week.

Thank you,
Andrew

**Comment by madceb** [comment]
Thanks @andrewtelnov, I'll be looking forward for the new widgets approach.
Excellent work.
Regards,
