### ISSUE TITLE
How to validate if atleast one text field is entered out of three text fields?

### ISSUE THREAD

**Issue by akmr9** [surveyjs/surveyjs#748]
### Are you requesting a feature, reporting a bug or ask a question?

Yes

### What is the expected behavior?

I have three text fields and I want to validate if atleast one is entered out of three.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
You need to process onValidateQuestion event, as shown in this example - https://surveyjs.io/Examples/Library/?id=validators-event&platform=jQuery

**Comment by andrewtelnov** [comment]
@akmr9 Here is the plunker example: https://plnkr.co/edit/LnCbZm?p=info

Thank you,
Andrew

**Comment by akmr9** [comment]
Works great. Thanks.
