### ISSUE TITLE
Angular SPA and SurveyWindow Expand/Collapse Link  

### ISSUE THREAD

**Issue by maddog72** [surveyjs/surveyjs#752]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug

### What is the current behavior?
When using the surveyjs component in an Angular SPA webapp, opening the collapsed survey window will display the survey momentarily and then the browser opens the Angular route defined as the root of the site.

### What is the expected behavior?
The surveyjs collapsed window should open and remain on the current Angular route.

### How would you reproduce the current behavior (if this is a bug)?

I am using the instructions from the getting started section of the documentation but in an Angular SPA. The displayed link when hovering over the expand carrot shows the link as the root of the site terminated with a hash character (http://localhost:60270/#) which does not match the current route. The surveyjs component should allow for the current route to be configured for the survey window or maybe the href should be set to "javascript:void(0);" rather than using the hash sign.

#### Provide the test code and the tested page URL (if applicable)

Test code
```
// Angular component typescript file that hosts the survey container.
// The ngOnInit function creates the Survey object and initializes it.
import { Component, EventEmitter, Inject, Input, OnInit, Output, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import * as Survey from 'survey-angular';

@Component({
    selector: 'survey',
    template: '<div class="survey-container contentcontainer codecontainer"><div id="surveyElement"></div></div>'
})
export class SurveyComponent implements OnInit {
    @Input() json: any;
    @Output() onComplete = new EventEmitter<any>();

    // Define the isBrowser that indicates if running during server-size rendering or
    // if running on the client's browser.'
    private isBrowser: boolean = isPlatformBrowser(this.platform_id);

    // Constructor method used to initialize the platform_id object.
    constructor( @Inject(PLATFORM_ID) private platform_id: any) {
    }

    ngOnInit() {
        if (this.isBrowser) {
            Survey.Survey.cssType = "bootstrap";
            let surveyModel = new Survey.ReactSurveyModel(this.json);
            Survey.SurveyWindowNG.render('surveyElement', { model: surveyModel, expanded: false });
            surveyModel.onComplete.add(survey => { this.onComplete.emit({ survey: survey }); });
        }
    }
}
```

### Specify your

* browser: Chrome (and IE11)
* browser version: 61.0.3163.100
* surveyjs platform (angular or react or jquery or knockout or vue): angular 4
* surveyjs version: current (0.12.35)

**Comment by tsv2013** [comment]
I've fixed it - changed 'a' tag to the 'span' thus got rid of navigation. Fix will be available in the nearest minor update.
