### ISSUE TITLE
Custom control support for multipletext

### ISSUE THREAD

**Issue by mdickin** [surveyjs/surveyjs#753]
### Are you requesting a feature, reporting a bug or ask a question?
Requesting a feature

### What is the current behavior?
I have a custom control for text inputs with `inputType = 'tel'`. This works fine for a single text question, but for `multipletext` inputs with `inputType = 'tel'`, the library does not detect it.

### What is the expected behavior?
I would like to have custom control support inside the `multitext` input.

### How would you reproduce the current behavior (if this is a bug)?
[Plunker](https://plnkr.co/edit/34XvTCUkKTTtbUfyAcmh?p=preview)

### Specify your

* browser: Chrome
* browser version: 62
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.12.36

**Comment by andrewtelnov** [comment]
@mdickin It is one multiple text item level. Here is the example: https://plnkr.co/edit/itDld0Kmy2H461OHG5lY?p=preview

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@mdickin Here is the code that should help you: https://github.com/surveyjs/widgets/blob/master/src/inputmask.js
We are going to release a new way of creating custom widgets. However, the code is already working in the latest version.

Thank you,
Andrew

**Comment by mdickin** [comment]
That's perfect, thank you for your help!
