### ISSUE TITLE
Display Multiple Pages in Single View?

### ISSUE THREAD

**Issue by wollerman** [surveyjs/surveyjs#756]
### Are you requesting a feature, reporting a bug or ask a question?

Asking a question.

### Question
Is it possible to render all pages in a single view? I'm looking to make a sort of single page survey where by clicking 'next' instead of hiding/showing things, the view scrolls down to the next surveyjs page. 

I can implement all questions on a single page and simply have custom navigation that scrolls to question anchors. However, I like the separation of things in surveyjs into 'pages'. These group conceptually nice and make survey design simple. Leaving the 'pages' structure would also allow me to switch between the two different view types in the future.

**Comment by andrewtelnov** [comment]
@wollerman I would create another json, where I would change the pages on panels and put them on one page. Another option,  create a Survey model from Json and before rendering create another Survey Model with one page and add for every page create a panel in the second and move all pages elements into panels.

Thank you,
Andrew

**Comment by wollerman** [comment]
@andrewtelnov that makes sense. Thanks! A quick follow up: is there a way to style panels? I tried looking around first and found @648 which suggests there is no class being generated for panels.

**Comment by wollerman** [comment]
Actually looking at the [custom CSS page](https://www.surveyjs.io/Examples/Library?id=survey-customcss&platform=Angular2) seems to provide what I need. Thanks again!

**Comment by wollerman** [comment]
I ended up using a third party library for the single page scroll actions and custom css to align with that tool. The hardest part is making sure the different javascript libraries don't clash because they fight over the DOM.
