### ISSUE TITLE
Change Response 

### ISSUE THREAD

**Issue by Ourdesignz123** [surveyjs/surveyjs#758]
Hi Team

I want to change the response of survey js from Thank you for completing the survey! to something else.

Will i be able to change using and js code

Please revert ASAP!

Thanks

**Comment by andrewtelnov** [comment]
@Ourdesignz123 survey.completedHtml = yourvalue;

Thank you,
Andrew

**Comment by Ourdesignz123** [comment]
function sendDataToServer(survey) {
    survey.sendResult('5db2de91-9d2a-4478-bcdd-907844cf2132');
}

var survey = new Survey.Model(surveyJSON);
$("#surveyContainer").Survey({
    model: survey,
    onComplete: sendDataToServer,
    completedHtml: "​<p><h4>Thank​ ​ you​ ​ for completing​ ​ the​ ​ survey.​ ​ ​ Our​ ​ mortgage​ ​ specialist​ ​ will​ ​ be​ ​ in​ ​ touch​ ​ shortly.​ ​ ​ In​ ​ the​ ​ meantime, please​ ​ check​ ​ your​ ​ email​ ​ for​ ​ the​ ​ list​ ​ of documents​ ​ that​ ​ you​ ​ will​ ​ need​ ​ to​ ​ provide​ ​ to​ ​ keep​ ​ the application​ ​ going</h4></p>"
    
}); 




survey.onComplete.add(function(result) {
	
	$.post("getxl.php",
        {
          data: result.data          
        },
        function(data,status){
            //alert("Data: " + data + "\nStatus: " + status);
        });
	
	//document.querySelector('#result').innerHTML = "result: " + JSON.stringify(result.data);
});

**Comment by andrewtelnov** [comment]
You may try this:
```
survey.completedHtml  = "Thank​ ​ you​ ​ for completing​ ​ the​ ​ survey.​ ​ ​ Our​ ​ mortgage​ ​ specialist​ ​ will​ ​ be​ ​ in​ ​ touch​ ​ shortly.​ ​ ​ In​ ​ the​ ​ meantime, please​ ​ check​ ​ your​ ​ email​ ​ for​ ​ the​ ​ list​ ​ of documents​ ​ that​ ​ you​ ​ will​ ​ need​ ​ to​ ​ provide​ ​ to​ ​ keep​ ​ the application​ ​ going";

$("#surveyContainer").Survey({
model: survey,
onComplete: sendDataToServer
});

```
Here is the example: https://plnkr.co/edit/v5qMnCSGYKXQRWOB8q5C?p=preview

Thank you,
Andrew
