### ISSUE TITLE
Problem with visibleIf in jquery Version

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#762]
Hi, i have found this bug.. this is an example

https://plnkr.co/edit/1Zm11LjQe03DQtpiLy7U?p=preview

I have a problem with visibleIf formula in this format "01-01-2018"

If i have a question with visibleIf property set like "{question1} == '01-01-2018'", the formula match only the first 2 character... if in question1 i write '01-01-2018' or '01-02-2018' the second question is visible... if i write '02-01-2018' the second question is hidden... 

Can anyone help me?

Thank you!

**Comment by andrewtelnov** [comment]
@care46 I have started to use parseFloat to check if the string is number or not. I did not know that it can convert the expression as well.
Anyway the issue is fixed. The fix will be avaliable in the next minor update.

Thank you,
Andrew
