### ISSUE TITLE
Clear value "onHidden" not working with panel condition

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#765]
Hi, i have this case:

{
 clearInvisibleValues: "onHidden",
 pages: [
  {
   elements: [
    {
     type: "text",
     name: "question3"
    },
    {
     type: "panel",
     elements: [
      {
       type: "checkbox",
       choices: [
        "item1",
        "item2",
        "item3"
       ],
       name: "question2"
      }
     ],
     name: "panel2",
     visibleIf: "{question3} = 'hello'"
    }
   ],
   name: "page1"
  }
 ]
}

In this case, when i have a visibleIf condition on panel and not on question, if i put value on second question and after i change value in first question, the second question and the second panel is hidden, but the value is not cleared

if i sets visibleIf condition in panel and also in question, the value is cleared

It's a bug or i have to replicate panel condition in all question?

Thank you

**Comment by andrewtelnov** [comment]
@care46 It is hard to say, is it a bug or not. We do not clear the value recursively for elements in the panel. We can do it of course, but I am not sure, is it a good thing to do. 

Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov ok! is not a problem because now i can use a workaround and i set the same condition on all question..

**Comment by andrewtelnov** [comment]
@care46 ok then. If we have more requests, then we change the behavior and start to clear values recursively.

Thank you,
Andrew

**Comment by shailendramonu** [comment]
This should be a feature as in a panel if we have multiple question (dropdowns), values are not cleared for invisible conditions.

**Comment by spingary** [comment]
I would also propose that if the page that a question is on is hidden, then that question's value should be cleared as well.

**Comment by andrewtelnov** [comment]
@care46 @shailendramonu @spingary Values are cleared recursively now.

Thank you,
Andrew
