### ISSUE TITLE
Customize Panels after Loading into SurveyModel

### ISSUE THREAD

**Issue by wollerman** [surveyjs/surveyjs#766]
### Are you requesting a feature, reporting a bug or ask a question?

Question. This is related to #756 where I am trying to make a single page survey. I'm using survey-angular with angular2. My two questions are listed below:

### Injecting buttons

I've updated my json to have all questions in separate panels. I would now like to add a custom button to each panel that will trigger a script. After creating the SurveyModel I've tried to access the panel elements as below:

```
let surveyModel = new Survey.ReactSurveyModel(this.surveySkeleton)
let panels = surveyModel.getAllPanels();
for (let p of panels) {
   console.log(p.id);
   p.addElement('<button>Test button</button>');
}
```

The panel ID prints to the console. However, in the editor I receive an error that `addElement` does not exist on type IPanel.  And when running I see the following error:

```
core.js:1350 ERROR TypeError: element.setSurveyImpl is not a function
    at PanelModelBase.onAddElement (survey.angular.js:7286)
    at survey.angular.js:7007
    at Array.newArray.push (survey.angular.js:2061)
    at PanelModelBase.addElement (survey.angular.js:7416)
    at SafeSubscriber._next (survey.ts:75)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:238)
    at SafeSubscriber.next (Subscriber.js:185)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at MapSubscriber._next (map.js:85)
```

Is there some sort of instantiation I'm missing? It seems like I'm interacting with the interface and not the actual object.

### Wrapping Panels
To facilitate easy scrolling, I was hoping to use some third party library that exists. Some use special tags to wrap pages. Is it possible to wrap each panel in a custom tag? E.g.:
```
<myspecialtag>
<div class="panel-body" id="sp_100"></div>
</myspecialtag>
```

Thanks.

**Comment by andrewtelnov** [comment]
@wollerman Please take a look at this demo: https://surveyjs.io/Examples/Library/?id=survey-afterrender&platform=Angular2
and on this event: https://surveyjs.io/Documentation/Library/?id=surveymodel#onAfterRenderPanel

Thank you,
Andrew

**Comment by wollerman** [comment]
@andrewtelnov, thank you. That is helpful. I have a follow up question: Is there a way to get the next panel or element on a page? I see documentation for next page but not next element.

**Comment by andrewtelnov** [comment]
The panel and page has the elements property, the array of elements.
element can be question or another panel. 

Thank you,
Andrew

**Comment by wollerman** [comment]
Thanks!
