### ISSUE TITLE
Should we exclude the value of invisible questions from the survey results by default?

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#767]
We are thinking about making a breaking change before releasing the v1.0.
Right now, the [survey.clearInvisibleValues](https://surveyjs.io/Documentation/Library/?id=surveymodel#clearInvisibleValues)  property has default value "none'. It means that values for invisible questions are included into survey results.
Do anybody has an objection if we change the default value from "none" to "onComplete"?
It means that values for invisible questions by default would be cleared right after the "Complete" button is clicked and before sending the survey json results.
What do you think? 

Thank you,
Andrew

**Comment by care46** [comment]
For me no problem! I use only "onHidden" value :D

**Comment by andrewtelnov** [comment]
@care46 Thank you! 
If we do not get any objection during a week, we will do the change.

**Comment by Lynn42** [comment]
Thanks for the heads-up! I'm checking with my programmers now and hope to let you know tomorrow.

**Comment by Lynn42** [comment]
We have no objection!

**Comment by andrewtelnov** [comment]
@Lynn42 Thank you!
