### ISSUE TITLE
Select2 tag box for plaform jQuery not working

### ISSUE THREAD

**Issue by akmr9** [surveyjs/surveyjs#768]
### Are you requesting a feature, reporting a bug or ask a question?

question/bug

### What is the current behavior?

I am trying to implement the Select2 tag box for JQuery which is implemented on the custom widgets example on the Survey js website. And I am having choices array instead of using choicesbyUrl. But when the page loads the control is rendered but the choices are not present. The choices are not loaded intl the html.

### What is the expected behavior?

Select2 tag box works when the choices are loaded directly as a array or list.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
{type: "tagbox", choices: Array(254),  choicesByUrl: null, isRequired: true, title: null, …}

<div class=""><div id="countries" class="sv_qstn" style="width: 100%;"><h5 class=""><span style="">Please provide the countries: *</span></h5><div><select multiple="multiple" style="width: 100%;"></select></div></div></div>

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@akmr9 It works with choices as well: https://plnkr.co/edit/KeSTSmO5fwo3FzLuwhcy?p=preview

Thank you,
Andrew

**Comment by akmr9** [comment]
Yup..It is working. Thanks.
