### ISSUE TITLE
question.value is undefined in custom widgets if set to []

### ISSUE THREAD

**Issue by faso** [surveyjs/surveyjs#769]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

question.value is undefined in afterRender if set to an empty array

### What is the expected behavior?

That I can assign question.value in afterRender to be equal to an empty array

```
let getOpCodesWidget = () => {
    var widget = {
        name: "myWidget",
        isFit: function (question) { return question["renderAs"] === 'myWidget'; },
        htmlTemplate: myWidgetTemplate,
        afterRender: function (question, el) {
              question.value = [];
              question.value.push('item'); // this fails because the value is undefined
        }
    }
    return widget;
}

```

### Specify your

* browser: any
* browser version: any
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: latest

**Comment by andrewtelnov** [comment]
@faso Could you try:

```
let newValue = [];
newValue.push('item');
question.value = newValue;
```

Thank you,
Andrew

**Comment by faso** [comment]
Yes, it works now, thanks!

Just out of curiosity - why is it this way?

**Comment by faso** [comment]
But if I do 

```
let newValue = [];
question.value = newValue;
```

It's still undefined. Why so?

**Comment by andrewtelnov** [comment]
@faso Because the library change the empty array into undefined value, if the array is empty. Empty array should not be in the survey result and required value check should produce the error.

Thank you,
Andrew

**Comment by faso** [comment]
Alright, thank you for quick answers. Always a joy to get help from you guys!
