### ISSUE TITLE
Text in progress bar should be moved

### ISSUE THREAD

**Issue by harishmegharaj** [surveyjs/surveyjs#774]
I need an option to move the "Page <start> of <end>" to outside progress bar.

Currently: I can move the text within progress bar limits.

Expected: I need to move the text outside the progress bar Eg: Page <start> of <end> : (Progress bar appearing at this place). Attaching image for reference
![image](https://user-images.githubusercontent.com/6915297/32947252-04faf864-cbc1-11e7-8d49-e307af371d00.png)

* surveyjs platform (angular or react or jquery or knockout or vue): angular 2
* surveyjs version: 0.12.32

**Comment by andrewtelnov** [comment]
@harishmegharaj You may create your own naviation or render your own progress bar. Here is the demo: https://surveyjs.io/Examples/Library/?id=survey-customnavigation

Thank you,
Andrew

**Comment by harishmegharaj** [comment]
Thanks Andrew, this information was very helpful.

Regards,
Harish
