### ISSUE TITLE
Add image as part of a question

### ISSUE THREAD

**Issue by maalina** [surveyjs/surveyjs#775]
Is it possible to add an image as part of a question currently?

**Comment by andrewtelnov** [comment]
@maalina Have you tried the [hml question](https://surveyjs.io/Examples/Library/?id=questiontype-html)

Thank you,
Andrew

**Comment by yumyo** [comment]
Hi @andrewtelnov how would you place a question(dropdown) next to the image?

**Comment by andrewtelnov** [comment]
@yumyo You can set `queston.startWithNewLine` property to false. It is located in "Layout" category.

Thank you,
Andrew

**Comment by paquinmathieu** [comment]
that would be really nice if it could be easier to insert an image on any question. Inserting an image like the way we can insert an image in the "image" question type
