### ISSUE TITLE
onPartialSend - sendResultOnPageNext - working example - how to include onPartialSend event

### ISSUE THREAD

**Issue by cnx90** [surveyjs/surveyjs#780]
### Are you requesting a feature, reporting a bug or ask a question?
I ask a question and if possible I kindly request to add a working example of onPartialSend functionality  to the surveyjs.io Documentation page.

### What is the current behavior?
I have a working survey (knockout js) with several pages on my server. I would like to send the result to the sever after next button is pressed and next page is loaded and not only when the complete button is pressed. 

### What is the expected behavior?
When user clicks next button - the data from current page is sent to the sever as if complete button was clicked - and it allows to collect incomplete surveys - which is a very helpful feature especially with longer surveys.

It is not fully clear to me how to add onPartialSend event

onPartialSend event
The event is fired on clicking 'Next' page if sendResultOnPageNext is set to true. You may use it to save the intermediate results, for example, if your survey is large enough. 
sender the survey object that fires the event
Type: Event<(sender: SurveyModel) => any, any>
Implemented in: SurveyModel
See also:  sendResultOnPageNext

#### Provide the test code and the tested page URL (if applicable)

I set already  sendResultOnPageNext: true, as true in JSON configuration. This JSON part is clear to me.  

I have some doubts about adding onPartialSend event. 
Could you provide a working example in Plunker / add this to documentation? 

Tested page URL: https://surveyjs.io/published?id=b63a069e-9284-4bbd-8b27-460690581b7d
I created a test page via editor to invesigate how this feature is implemented by you.
Test code

When sending the data to sever - example from your page I implemented:

The basic configuration is following:

function sendDataToServer(survey) {
  var resultAsString = JSON.stringify(survey.data);
  alert(resultAsString); //send Ajax request to your web server.
}

Can I just add onPartialSend event like that? To replace my current code or this onPartialSend event is an additional object?

survey.onPartialSend.add(function sendDataToServer(survey) {
  var resultAsString = JSON.stringify(survey.data);
  alert(resultAsString); //send Ajax request to your web server.
})

In GitHub examples I found something like that with function sender -is it correct like that?

survey.onPartialSend.add(function(sender) {
  var resultAsString = JSON.stringify(survey.data);
  alert(resultAsString); //send Ajax request to your web server.
});

Should I use options.data?
//options.data contains the data for the current page.

Thank you for any help and great work with the whole project.
your_code_here

```

### Specify your

* browser: Chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): knockout
* surveyjs version: 0.96.1

**Comment by andrewtelnov** [comment]
@cnx90 I may create an example. I am not sure it would help you.
onPartialSend event is fired on pressing the next page if sendResultOnPageNext equals true. It doesn't have any options.
It doesn't called on pressing the complete button.
For our service, the only difference between sending data on partial send (pressing next button) or on complete (pressing complete button) is that it has the flag partial/incompleted = true. The service overrides the previous incomplete survey results all the time.

Thank you,
Andrew

**Comment by cnx90** [comment]
@andrewtelnov  Thank you for a quick reply. I hope the example will still be useful. 
I set the sendResultOnPageNext  in both ways in a script and JSON. The survey result is sent only when I will go to the end of the survey and click **Submit** but when I am clicking next no data is sent to server.

```
<script type="text/javascript">
Survey.Survey.cssType = "bootstrap";
Survey.sendResultOnPageNext = true;
...
```
**JSON:**
```
pageNextText: "Next >>",
pagePrevText: "<< Previous",
completeText: "Submit",
sendResultOnPageNext: "true",
```
There are no errors in console. Can you suggest a way to debug it?

For testing purpose can I create a button to send the survey data anytime the button is pressed - and survey results are sent - for example?
 
`<button onclick="sendDataToServer()">Send data now</button>`

Before asking a questions I was checking simillar issues on Github and in the issue
Saving intermediate results when "Next" is pressed? #351  you suggest calling survey.sendResult method

Thank you!

**Comment by andrewtelnov** [comment]
@cnx90 Sure, there is the [example](https://plnkr.co/edit/yU0BJA?p=preview)

Thank you,
Andrew

**Comment by maltitco** [comment]
@andrewtelnov it is possible to test this function with your data storage?
I tried to implement it but I save each page as a separate survey.
How to set it for survey.onPartialSend and survey.onComplete updated the same survey?
