### ISSUE TITLE
Visible if functionality doesn't work the same in newer SurveyJS editor version?

### ISSUE THREAD

**Issue by Lynn42** [surveyjs/surveyjs#781]
### Are you requesting a feature, reporting a bug or ask a question?

Ask a question

### What is the current behavior? vs. What is the expected behavior?

On https://surveyjs.io/Editor/Editor/:

When testing the form, and selecting '1' and '2' on the question 'Resultaatselectie', I expect the two panels 'Resultaat1'  and 'Resultaat2'  to show, as defined in their respective 'Visible if' statements.
This works well in an older version of the editor that is currently installed on our system, but it doesn't work anymore on the newest version I find on https://surveyjs.io/Editor/Editor/. 
I would expect this to work in the newest version, same as it did on the older version of the editor. Could you help me find out where in the form I'm going wrong, or whether there's possibly a bug that makes older forms incompatible with this new editor?

### How would you reproduce the current behavior (if this is a bug)?

Take Json code from below, test it on editor, and determine if I made a mistake or if there is a bug that makes the newer version not compatible with forms built on previous version of the editor.

#### Provide the test code and the tested page URL (if applicable)

JSON code:

{
 "pages": [
  {
   "name": "Pagina2",
   "elements": [
    {
     "type": "checkbox",
     "name": "ResultaatSelectie",
     "title": "Selecteer resultaat dat van toepassing is",
     "isRequired": true,
     "choices": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "13",
      "7"
     ],
     "colCount": 4
    },
    {
     "type": "panel",
     "elements": [
      {
       "type": "dropdown",
       "choices": [
        {
         "value": "-1",
         "text": "Achteruitgang t.o.v. start"
        },
        {
         "value": "0",
         "text": "Situatie gelijk aan start"
        },
        {
         "value": "1",
         "text": "Resultaat deels behaald"
        },
        {
         "value": "2",
         "text": "Resultaat volledig behaald"
        },
        {
         "value": "3",
         "text": "Meer dan het resultaat behaald"
        }
       ],
       "isRequired": true,
       "name": "Gas1",
       "optionsCaption": "Selecteer GAS Score",
       "title": "Score"
      },
      {
       "type": "radiogroup",
       "choices": [
        "Ja",
        "Nee"
       ],
       "isRequired": true,
       "name": "Consensus1",
       "title": "Was er consensus over de score?"
      }
     ],
     "name": "panel1",
     "title": "1. Client is ondersteund.",
     "visible": false,
     "visibleIf": "{ResultaatSelectie} contains '1'"
    },
    {
     "type": "panel",
     "elements": [
      {
       "type": "dropdown",
       "choices": [
        {
         "value": "-1",
         "text": "Achteruitgang t.o.v. start"
        },
        {
         "value": "0",
         "text": "Situatie gelijk aan start"
        },
        {
         "value": "1",
         "text": "Resultaat deels behaald"
        },
        {
         "value": "2",
         "text": "Resultaat volledig behaald"
        },
        {
         "value": "3",
         "text": "Meer dan het resultaat behaald"
        }
       ],
       "isRequired": true,
       "name": "Gas2",
       "optionsCaption": "Selecteer GAS Score",
       "title": "Score"
      },
      {
       "type": "radiogroup",
       "choices": [
        "Ja",
        "Nee"
       ],
       "isRequired": true,
       "name": "Consensus2",
       "title": "Was er consensus over de score?"
      }
     ],
     "name": "Resultaat2",
     "title": "2. Heeft een plek verzorgingstehuis",
     "visible": false,
     "visibleIf": "{ResultaatSelectie} contains '2'"
    }
   ],
   "title": "Pagina 2"
  }
 ],
 "requiredText": "",
 "showQuestionNumbers": "off"
}
```

### Specify your

* browser: Firefox
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): https://surveyjs.io/Editor/Editor/
* surveyjs version: 0.96.1

**Comment by Lynn42** [comment]
The version of the editor we currently have installed, where the Visibility If does work as expected, is v0.12.31.

**Comment by Lynn42** [comment]
Thank you Andrew!

**Comment by Lynn42** [comment]
I think I have found a different way in which the VisibleIf functionality works in an older version (v0.12.31), but not on the newest version of the editor (0.97.0). 

It concerns the following JSON code, you expect the 2nd and 3rd questions to only become visible after the answer on the 1st question is 'Ja'. However, they immediately show, regardless of the answer being filled in. 

{
 pages: [
  {
   elements: [
    {
     type: "radiogroup",
     choices: [
      "Ja",
      "Nee"
     ],
     isRequired: true,
     name: "VoortijdigEindeSelectie",
     title: "Is er sprake van voortijdige beëindiging van deze beschikking?"
    },
    {
     type: "radiogroup",
     choices: [
      "Verhuizing",
      "Overlijden",
      "Andere zorgaanbieder",
      "Onbekend/Overige"
     ],
     isRequired: true,
     name: "RedenVoortijdigEinde",
     title: "Reden voortijdige beëindiging:",
     visibleIf: "{VoortijdigEindeSelectie} equals 'Ja'"
    },
    {
     type: "text",
     isRequired: true,
     name: "DatumVoortijdigEinde",
     placeHolder: "dd-mm-jjjj",
     title: "Datum voortijdige beëindiging:",
     validators: [
      {
       type: "regex",
       text: "Geen geldige datum. Een geldige datum heeft de volgende opbouw: dd-mm-jjjj",
       regex: "^([\\d]{2,2}-[\\d]{2,2}-[\\d]{4,4})$"
      }
     ],
     visibleIf: "{VoortijdigEindeSelectie} equals 'Ja'"
    }
   ],
   name: "page1"
  }
 ]
}

**Comment by andrewtelnov** [comment]
@Lynn42 Yes, it is a bug. 'equals' doesn't work for some reason. You may use '=' as a work-around.
visibleIf: "{VoortijdigEindeSelectie} = 'Ja'"
I will work on the fix.

Thank you,
Andrew

**Comment by Lynn42** [comment]
I will do that, thank you.

**Comment by andrewtelnov** [comment]
@Lynn42 We do not support 'equals' before. We have 'equal'. Anyway, I have added 'equals' into the operator list as well. In case if somebody will use 'equals'.

Thank you,
Andrew
