### ISSUE TITLE
Question Description not showing when 'questionTitleLocation' is set to 'left'

### ISSUE THREAD

**Issue by Zucka** [surveyjs/surveyjs#785]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
Question description is not showing when questionTitleLocation is set to left

### What is the expected behavior?
That the description is showed as it is on the online editor

### How would you reproduce the current behavior (if this is a bug)?
See url

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs-angular5-example-gh771-gkh98b.stackblitz.io 

Test code

```
{
  "pages":[
    {
      "name":"page1",
      "questionTitleLocation":"left",
      "elements":[
        {
          "type":"panel",
          "name":"questionPanel1",
          "title":"Panel Title",
          "elements":[
            {
              "type":"rating",
              "name":"question1",
              "title":"Q1 Ttile",
              "description":"Q1 Description",
              "isRequired":true,
              "rateValues":[
                {
                  "value":1,
                  "text":"True"
                },
                {
                  "value":0,
                  "text":"False"
                }
              ]
            }
          ]
        },
        {
          "type":"radiogroup",
          "choices":[
            "item1",
            "item2"
          ],
          "colCount":"0",
          "description":"radiogroup Description",
          "name":"question1"
        }
      ]
    }
  ]
}

```

### Specify your

* browser: Chrome
* browser version: 62.0.3202.94
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version: 0.96.1

**Comment by dmitrykurmanov** [comment]
Thaks, I will fix it. The bug is only in react, jquery and angular

**Comment by dmitrykurmanov** [comment]
fix will available in the next release, I hope it will be today

**Comment by Zucka** [comment]
Awesome !

**Comment by Zucka** [comment]
Verified working :)
