### ISSUE TITLE
Navigation delay

### ISSUE THREAD

**Issue by paritoshmmmec** [surveyjs/surveyjs#789]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question

### What is the current behavior?
Navigation between pages is pretty quick, if autonext is selected.

### What is the expected behavior?
Is it possible to introduce a scroll affect?

**Comment by andrewtelnov** [comment]
@paritoshmmmec There is [onCurrentPageChanged event](https://surveyjs.io/Documentation/Library/?id=surveymodel#onCurrentPageChanged).
I beleive you may appy a transition effect on this event.

Thank you,
Andrew
