### ISSUE TITLE
Anchor tag not parsing into a link

### ISSUE THREAD

**Issue by akmr9** [surveyjs/surveyjs#790]
### Are you requesting a feature, reporting a bug or ask a question?

question

### What is the current behavior?

When I include anchor tag in a string the anchor tag is not parsed to a link.
Ex: I like Survey js library. <a  href = "https://surveyjs.io/Examples/Editor/">Click here</a> to see examples.

### What is the expected behavior?

I would expect that "Click here" would turn into a link.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
 I like Survey js library. <a href = "https://surveyjs.io/Examples/Editor/">Click here</a> to see examples.

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by dmitrykurmanov** [comment]
Could you please specify you use case? Where do you want to insert the link? I think you need the markdown [feature](https://surveyjs.io/Examples/Library/?id=survey-markdown-radiogroup&platform=jQuery#) Here an example with title : https://plnkr.co/edit/hiAEp7?p=preview

**Comment by akmr9** [comment]
That's what I am exactly looking for. Thank you very much.
