### ISSUE TITLE
Request: Singlepage view mode

### ISSUE THREAD

**Issue by Noino** [surveyjs/surveyjs#791]
So this one is quite similar to #598  in that i wish to be able to view all the answers given on a single page. The main difference is that i don't want to have to navigate past all the pages of the survey to get to it, so basically its the same feature (or same page) but with a different way to get to it.
Two birds with one stone!

The use case for this would be after a user has submitted their survey, you could use this for example to save the results to a pdf using tools like [wkhtmltopdf](https://wkhtmltopdf.org/), print it out on paper or even for an admin to get a fast overview of whats going on with the answers.

I would imagine something like this should be easy to use
```
            var survey = new Survey.Model(surveyJSON);
            survey.data = answers;
            $("#surveyContainer").Survey({
                model: survey,
                reviewMode: true
            });
```
or even reviewMode: 'singlepage' if you foresee other modes in the future.

**Comment by andrewtelnov** [comment]
@Noino It is definately make sense. We had several requests with this functionality already. I have added the issue to [the project ideas](https://github.com/surveyjs/surveyjs/projects/1). We will likely implement it in the next versions.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@Noino It has been implemented, set properyt survye.isSinglePage to true
`survey.isSinglePage = true;`

Thank you,
Andrew
