### ISSUE TITLE
Matrix Dropdown With Multiple File Upload

### ISSUE THREAD

**Issue by pankanis-rushikesh** [surveyjs/surveyjs#793]
I would like to have MatrixDropDown with following cells
1st Column : RadioGroup with options Yes,No,Mabe
2nd Column : Comment Box visible only if Value of 1st column is N
3rd Column : Multiple File Upload

There would be Multiple Rows , For each Row Comment Box  should be visible according to the 1st column value of that row. 
 
Could you please tell me how to build this survey json.

**Comment by andrewtelnov** [comment]
@pankanis-rushikesh Unfortunately it is not possible to create it at the current moment.
I would suggest you to go with PanelDynamic.
You may have all 3 questions on the same line and it will be pretty the same.

Thank you,
Andrew

**Comment by pankanis-rushikesh** [comment]
I tried with Panel Dynamic but then it does not show me in Matrix Format ( CSS ).I wanted it to look like matrix but with addition questions. If each row in matrix Dropdown could have name then each cell in that row will have name like  `rowName.cellName`  this could maybe solve the problem.

**Comment by andrewtelnov** [comment]
@pankanis-rushikesh I do not see any good solution rigth now :(
I may add an event, that will allow you to create the question you want in the matrix. Probably there is a more elegant solution. I have to think...

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@pankanis-rushikesh You have to add the following code to support the file cell type:
```
        Survey.matrixDropdownColumnTypes.file = {
            properties: ["showPreview", "imageHeight", "imageWidth"]
        };
```

Thank you,
Andrew
