### ISSUE TITLE
Image picker does not work correctly.

### ISSUE THREAD

**Issue by willgdjones** [surveyjs/surveyjs#795]
### Are you requesting a feature, reporting a bug or ask a question?

Bug!

### What is the current behavior?
Image picker does not work correctly.
https://surveyjs.io/Examples/Library/?id=custom-widget-image-picker&platform=jQuery#

### What is the expected behavior?
To return the result from the given example.

### How would you reproduce the current behavior (if this is a bug)?
By using the version of surveyjs that I am using and running this example.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
This the generated result - surveyjs does not recognise that there are questions in the JSON I provide. 
<img width="349" alt="screen shot 2017-11-29 at 21 35 25" src="https://user-images.githubusercontent.com/1719848/33400236-44172d70-d54d-11e7-9355-3685fd3b9a66.png">

Test code

```
var MathTestJSON = {
   "elements": [
      {
         "type": "imagepicker",
         "name": "choosepicture",
         "title": "What animal would you like to see first ?",
        "choices": [
          {
            "value": "lion",
            "imageLink": "https://surveyjs.io/Content/Images/examples/image-picker/lion.jpg"
          },
          {
            "value": "giraffe",
            "imageLink": "https://surveyjs.io/Content/Images/examples/image-picker/giraffe.jpg"
          },
          {
            "value": "panda",
            "imageLink": "https://surveyjs.io/Content/Images/examples/image-picker/panda.jpg"
          },
          {
            "value": "camel",
            "imageLink": "https://surveyjs.io/Content/Images/examples/image-picker/camel.jpg"
          }
        ]
      }
   ]
};


window.math_test = new Survey.Model(MathTestJSON);
math_test["name"] = "math_test"

var converter = new showdown.Converter();

math_test.onTextMarkdown.add(function(survey, options){
    //convert the mardown text to html
    var str = converter.makeHtml(options.text);
    //remove root paragraphs <p></p>
    str = str.substring(3);
    str = str.substring(0, str.length - 4);
    //set html
    options.html = str;
});

$("#math_test").Survey({
model:math_test,
css:surveyCSS,
onComplete:sendDataToServer
});

```

### Specify your

* browser: Chrome
* browser version: Version 62.0.3202.94 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.97.0

**Comment by tsv2013** [comment]
Custom widgets are 3rd patry controls, integrated with SurveyJS and thus require some additional scripts to be loaded on the page.
Have you added custom widget's scripts on your page, as shown on the HTML tab of the [Image Picker widget](https://surveyjs.io/Examples/Library/?id=custom-widget-image-picker&platform=jQuery) example?

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/image-picker/0.3.0/image-picker.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/image-picker/0.3.0/image-picker.css" />
<script src="https://unpkg.com/surveyjs-widgets"></script>
```
