### ISSUE TITLE
How to customize the question title to put the question number in a unique span?

### ISSUE THREAD

**Issue by benweizhu** [surveyjs/surveyjs#796]
### Are you requesting a feature, reporting a bug or ask a question?

I want to ask how can I customize the question title to split the question number  into a span, so that I can add style for the number itself?

### What is the current behavior?

In current question title template, the number and the question is in a string.

```
<script type="text/html" id="survey-question-title">
    <h5 data-bind="css: koCss().title" class="mbb_survey_editor_question_title">
        <!-- ko template: { name: 'survey-string', data: locTitle } --><!-- /ko -->
    </h5>
    <div data-bind="visible: hasDescription, css: koCss().description">
        <!-- ko template: { name: 'survey-string', data: locDescription } --><!-- /ko -->
    </div>
</script>
```

Like:
1.What's your name?

But I want the 1. is in another span, not in the locTitle String.

### What is the expected behavior?
I want to split the number into another span, so that I can change the number font-size without change the whole title.

Any suggestion?

**Comment by andrewtelnov** [comment]
@benweizhu I believe [this example](https://surveyjs.io/Examples/Library/?id=survey-afterrender) should help you.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@benweizhu Or another suggestion use markdown functionlity: https://surveyjs.io/Examples/Library/?id=survey-markdown-radiogroup
But at first you have to change the survey.questionTitleTemplate from the default: {no}. {require} {title} to what ever you want.

Thank you,
Andrew

**Comment by benweizhu** [comment]
Thanks a lot. @andrewtelnov
