### ISSUE TITLE
Required Multipletext items do not respect questionTitleTemplate

### ISSUE THREAD

**Issue by mdickin** [surveyjs/surveyjs#799]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
Multipletext item titles are hardcoded to put the required text to the left of the title

### What is the expected behavior?
Use Survey.questionTitleTemplate to determine how to format the title

### How would you reproduce the current behavior (if this is a bug)?
See [plunker](https://plnkr.co/edit/paX73FEyPovh7efpZPHK?p=preview)

### Specify your

* browser: Chrome
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.12.36

**Comment by mdickin** [comment]
As a work around, I have used this code (which is still not using the template, but it's okay for our purposes):

```javascript
Survey.MultipleTextItemModel.prototype.getFullTitle = function (str) {
	if (!str) str = this.name;
	if (this.isRequired && this.data)
		str = str + " " + this.data.getIsRequiredText();
	return str;
}
```

**Comment by andrewtelnov** [comment]
@mdickin Could you use the Panel and several text questions?
I have introduced the multiple text question before we had the Panel. Panel was added in a year after multple text question.

I think we need another property for text item titles in mutlple text question.

PS: I am going to work on this functionality: https://github.com/surveyjs/surveyjs/issues/798

Thank you,
Andrew

**Comment by mdickin** [comment]
One of the uses we have for `multipletext` is for providing phone numbers, like work/home/mobile. Only one is required, and it's easy to just set `isRequired` on the `multipletext` element

**Comment by andrewtelnov** [comment]
@mdickin Hm, I think we can add isRequired validation into Panel.

Thank you,
Andrew

**Comment by mdickin** [comment]
I'm not sure that would fix things. We use panels as a way of grouping sets of questions on a page, and don't know that nesting panels would be the right approach. It seems like they serve two different purposes. Also, panels don't currently allow arranging questions inline.

**Comment by andrewtelnov** [comment]
@mdickin I have looked the code. I think I will change it. There is a code duplication. It is better remove all custom rendering for multiple text item and create and render the text question, similar to the matrix dropdown/dynamic. In this case title location we will get for free, as well as other features.
The only issue, we will have another property to setup the title location. It should be "left" by default. In other case, we will break a lot of surveys.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@mdickin We have added isRequried into Panel: https://github.com/surveyjs/surveyjs/issues/844

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@mdickin We are using text question for rendering items in mutiple text question. 

Thank you,
Andrew
