### ISSUE TITLE
Is there an example to setup the SurveyEditor?

### ISSUE THREAD

**Issue by Amnesi4c** [surveyjs/surveyjs#80]
Hi,

If I want to have the SurveyEditor / Builder on my site, any examples that can help me with that? 

Thanks!

**Comment by andrewtelnov** [comment]
@Amnesi4c, we do not have good examples yet. From [here](https://github.com/andrewtelnov/surveyjs.editor) you may get the code snippet.

You may ask a question, if you have any.

Thank you,
Andrew

**Comment by PAK90** [comment]
Adding an example would be good. I'm having trouble adding this survey component to my React page (with webpack), and the lack of examples is very limiting.

**Comment by andrewtelnov** [comment]
@Amnesi4c @PAK90 I have added some [demos](http://editor.surveyjs.io/).

Thank you,
Andrew
