### ISSUE TITLE
Explicitly click on Complete when using goNextPageAutomatic=true

### ISSUE THREAD

**Issue by rfortunati** [surveyjs/surveyjs#807]
### Are you requesting a feature, reporting a bug or ask a question? 
Reporting a bug

### What is the current behavior?
When using the goNextPageAutomatic=true, every page including the lastPage will jump to the nextPage or the CompletedPage. Example code below.

### What is the expected behavior?
I expect that we stay on the lastPage and the user explicitly needs to click on the Complete button.

### How would you reproduce the current behavior (if this is a bug)?
https://plnkr.co/edit/5JbzAKfWRCFwENQWlDe3?p=preview

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
see https://plnkr.co/edit/5JbzAKfWRCFwENQWlDe3?p=preview

```

### Specify your

* browser: Chrome
* browser version: 62.0.3202.94
* surveyjs platform: jquery
* surveyjs version: 0.97.0

**Comment by tsv2013** [comment]
Thank you for the report, @rfortunati 
We've discussed the issue with the team and decided to make this option more flexible:
true - go next page and submit automatically
false - do not go next page and submit automatically
"autogonext" - go next page automatically but do not submit

**Comment by andrewtelnov** [comment]
@tsv2013 it works for me. You may implement it. Just extend the unit tests related to goNextPageAutomatic option and update the property definition.

Thank you,
Andrew

**Comment by tsv2013** [comment]
@andrewtelnov ok

**Comment by tsv2013** [comment]
I've implemented the option value, mentioned above.
It will be available in the nearest update.

**Comment by rfortunati** [comment]
Thanks @tsv2013 @andrewtelnov
