### ISSUE TITLE
Is it possible to pre-populate the survey form with some answers? 

### ISSUE THREAD

**Issue by benweizhu** [surveyjs/surveyjs#808]
### Are you requesting a feature, reporting a bug or ask a question?

Ask a question:

Is it possible to pre-populate the survey form JSON with some answers in it?

Something like:

```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "question1",
     "answer": "This is the question"
    },
    {
     "type": "checkbox",
     "choices": [
      "item1",
      "item2",
      "item3"
     ],
     "name": "question2"
     "answer": "item1"
    }
   ]
  }
 ]
}
``` 
Because I want to save the partial question that my users filled in.

**Comment by dmitrykurmanov** [comment]
Sure, please check the example https://surveyjs.io/Examples/Library/?id=survey-data&platform=jQuery

**Comment by benweizhu** [comment]
Thanks a lot. @dmitrykurmanov
