### ISSUE TITLE
After section visibleIf is false, the hidden data is still sent

### ISSUE THREAD

**Issue by wollerman** [surveyjs/surveyjs#817]
### Are you requesting a feature, reporting a bug or ask a question?

Bug/Question

### What is the current behavior?

If there's a section that has a visibleIf condition on previous questions, the user can somehow toggle the questions and fill them out. However, if the user changes their mind on the previous question and it then hides the visibleIf, then the hidden question values are still sent.

### What is the expected behavior?

I would expect either the hidden question values would be removed or only the visible questions would be sent in the data.

Essentially, because the user changed the response that removes the conditional questions, I think the conditional questions should no longer be part of `data`.

### How would you reproduce the current behavior (if this is a bug)?

Using the below example, select `yes` for kids. Select a number. Then choose `no` for kids. Finally, submit. In this case the results send `{"haveKids":"No","kids":"3"}` which seems contradictory. 

```

Survey.Survey.cssType = "bootstrap";
Survey.defaultBootstrapCss.navigationButton = "btn btn-green";

var json = {
    showQuestionNumbers: "off",
    questions: [
        {
            type: "radiogroup",
            name: "haveKids",
            title: "Do you have a kid(s)?",
            isRequired: true,
            choices: [
                "Yes", "No"
            ],
            colCount: 0
        }, {
            type: "dropdown",
            name: "kids",
            title: "How many kids do you have",
            visibleIf: "{haveKids}='Yes'",
            isRequired: true,
            choices: [1, 2, 3, 4, 5]
        }
    ]
};

window.survey = new Survey.Model(json);
survey.onComplete.add(function(result) {
	document.querySelector('#surveyResult').innerHTML = "result: " + JSON.stringify(result.data);
});

survey.onValueChanged.add(function(sender, options) {
  if(options.name !=="cars") return;
  var choices = [];
  var newValue = options.value ? options.value : [];
  for(var i = 0; i < newValue.length; i ++) {
    choices.push(newValue[i]);
  }
  sender.getQuestionByName("selectCars").choices = choices;
});


$("#surveyElement").Survey({model:survey});


```

#### Provide the test code and the tested page URL (if applicable)
Drop code in plunker with HTML:

```
<!DOCTYPE html>
<html>

<head>
    <title>Welcome to JQuery</title>
    <script src="https://unpkg.com/jquery"></script>
    
    <script src="https://surveyjs.azureedge.net/0.12.18/survey.jquery.js"></script>
    
    
    <link rel="stylesheet" href="https://unpkg.com/bootstrap@3.3.7/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="./index.css">
</head>

<body>
    <div id="surveyElement"></div>
    <div id="surveyResult"></div>
    <script src="./index.js"></script>
</body>

</html>
```

**Comment by andrewtelnov** [comment]
@wollerman You have to set the `survey.clearInvisibleValues = "onComplete";`
From the next minor version you should not do anything. It will be the value by default: https://github.com/surveyjs/surveyjs/issues/810

Thank you,
Andrew

**Comment by wollerman** [comment]
Awesome, thanks. Quick follow up: when the next minor version is released, will that feature flag still be available/supported?

Also thank you for the amazingly quick response times!

**Comment by andrewtelnov** [comment]
Yes, the property will be there. We have changed the default value only.

**Comment by wollerman** [comment]
Thank you!
