### ISSUE TITLE
Can you add support for customising 'panel' elements?

### ISSUE THREAD

**Issue by halexiev-hedgeserv** [surveyjs/surveyjs#823]
### Are you requesting a feature, reporting a bug or ask a question?
Question.

### What is the current behavior?
Panels are not customisable via custom widget support. We would like to have panels as collapsible containers just like Bootstrap's collapse (https://v4-alpha.getbootstrap.com/components/collapse).

### What is the expected behavior?
To be able to customise panels so that they, in our case, can collapse/expand.

Currently we are using the **onAfterRenderSurvey** and **onAfterRenderPanel** events, but they are not enough as panels' headers get overridden (re-rendered) in uncontrollable way as questions show/hide.

Any hint is appreciated.
Regards,
Hristo

**Comment by andrewtelnov** [comment]
@halexiev-hedgeserv We have this functionality in our TODO list. Unfortunately we have postponed it. The easy solution is to have a boolean question and set the visibileIf to the panel. Here is the example: https://plnkr.co/edit/eDdIsdccLy5PLnduYlfn?p=preview

Thank you,
Andrew

**Comment by halexiev-hedgeserv** [comment]
@andrewtelnov That's a cool around it, however if the wrap-around checkbox is deselected (meaning the panel is collapsed and not visible) the answers from the questions in that panel won't be submitted to the survey. Is there a way to submit the answers for questions that are not visible?

**Comment by andrewtelnov** [comment]
@halexiev-hedgeserv Sure, survey.clearInvisibleValues = "none";

Thank yuo,
Andrew

**Comment by halexiev-hedgeserv** [comment]
@andrewtelnov Yes, but this still will not quite do it because, for example if you have a question with anwers {a, b} and based on the selection you show/hide one of two more questions with answers {a2, a3} and {b2, b3}. If you first select {a} and then {a2}, but then you switch to {b} and {b2}, we don't want to submit {a2}. Which is what happens if you clearInvisibleValues="none"...

**Comment by andrewtelnov** [comment]
@halexiev-hedgeserv Just test the example. I think it works as you need :)

Thank you,
Andrew

**Comment by halexiev-hedgeserv** [comment]
@andrewtelnov We tested it, here's our scenario:

https://plnkr.co/edit/GgK65eeJJwXzRmj8SGj8?p=preview

Steps to follow:
1. Select 'Product A' 
2. Provide answer to the comment question, for example, 'Dont want this!'
3. Change to 'Product B'
4. Provide answer to the new comment question, for example, 'Want this!'
5. Complete survey

Here's the result we get:

`result: {"isImprovePanelShowing":true,"ProductToImprove":"2","suggestionsA":"Dont want this!","suggestionsB":"Want this!"}`

The problem is when we configure **clearInvisibleValues="none"** we get **"suggestionsA":"Dont want this!"** in the results, which is undesirable.

Thank you,
Hristo

**Comment by andrewtelnov** [comment]
@halexiev-hedgeserv You do not to set the clearInvisibleValues="none". 
The question value will be in the result if the question is visible, the default behavior now. It doesn't matter if the question in the visible or invisible panel. We are checking on question visible property only and not its parent.

Thank you,
Andrew

**Comment by halexiev-hedgeserv** [comment]
@andrewtelnov Yep you are right, that could actually work, we'll definitely try it out :)

Just one last question - is there any ETA on the real support for collapsible panels, like in couple of months maybe, year?

Thank you for your quick replies 👍 
Hristo

**Comment by andrewtelnov** [comment]
@halexiev-hedgeserv We will public our TODO list here: https://github.com/surveyjs/surveyjs/projects/1
Probably we will allow to vote on features, we are not sure yet.
I like the idea to expand/collapse the panel content.

Thank you,
Andrew

**Comment by halexiev-hedgeserv** [comment]
@andrewtelnov Hi Andrew, just to let you know that we implemented your suggestion and it works fine as far as collapsing/expanding the panel, so thank you once more! 

One thing that's not working though is the validation of required questions within the panel when the panel is collapsed :( 

To us being able to collapse/expand panels is more of a UX thing, definitely important but not critical, whereas validation is one of crucial features of the library.

So the question is how can we have them both :)

Thanks,
Hristo

**Comment by andrewtelnov** [comment]
@halexiev-hedgeserv What is your deadline? I think the easiest for us, is adding the state property to the model: normal, expanded, collapsed. If there expanded and collapsed is shown then show the UI for expanding/collapsing the panel.
If the panel is collapse and some questions inside it do not pass validation then change the state to expand.

Thank you,
Andrew

**Comment by halexiev-hedgeserv** [comment]
@andrewtelnov Deadline is Feb'18 so there's some time, but the clock is ticking.

Your idea sounds good. Maybe it also make sense to add another flag or something like that to prevent validation from happening and automatically expanding the panel for people in the situation that we are now who are perfectly fine with (and maybe even expecting) validation not being triggered when the panel is collapsed ... just food for thought.

Thanks,
Hristo

**Comment by andrewtelnov** [comment]
@halexiev-hedgeserv I was not sure that we may implement it this year, but in January, it is fine.
I wanted to implement this functionality from the beginning. The main problem I have is UI. We have the designer on board right now, so it should not be an issue.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@halexiev-hedgeserv FYI: https://github.com/surveyjs/surveyjs/issues/843

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@halexiev-hedgeserv It has been implemented: https://plnkr.co/edit/SwRobS1FS0MpHnDJ6G3X?p=preview

Thank you,
Andrew

**Comment by halexiev-hedgeserv** [comment]
@andrewtelnov Great! Could you only clarify how can the panel be expanded when it contains required question that has not been populated and the "complete" button is clicked:

https://plnkr.co/edit/tdiTaVYq0QNchYTpWhwM?p=preview

Thank you,
Hristo

**Comment by andrewtelnov** [comment]
@halexiev-hedgeserv Yes, you are right. It is a bug. I have just fixed it with the commit above.

Thank you,
Andrew
