### ISSUE TITLE
Custom defaultValue behaviour not implementing setDefaultValue correctly.

### ISSUE THREAD

**Issue by Kichi93** [surveyjs/surveyjs#825]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behaviour?

setDefaultValue() changes the data but the dropdown still displays the old value.

### What is the expected behaviour?

setDefaultValue() should change the data and appearance of dropdowns.

### How would you reproduce the current behaviour (if this is a bug)?

Go to the plunkr example and hit the complete button without touching the dropdown. You should see that the value is set to 7 even though the dropdown appears to have 1 selected.

#### Provide the test code and the tested page URL (if applicable)

My motivation is to have the default value set even if other data is passed into the survey and to remove the ability to reset the question to null (i.e. remove the "Choose..." option).

Tested page URL: [plunkr](https://plnkr.co/edit/jCE5Yp2Z7gKp79fUWwmg?p=preview)

Test code

```
var defaultValueEnhancement = {
  name: "defaultValueEnhancement",
  isDefaultRender: true,
  isFit: function(question) {
    return question.getType() === "dropdown" && question.defaultValue !== undefined;
  },
  afterRender: function(question, element) {
    var chooseOption = element.querySelector('option[value=""]');
    chooseOption.parentNode.removeChild(chooseOption);
    question.setDefaultValue();
  }
};

Survey.CustomWidgetCollection.Instance.addCustomWidget(defaultValueEnhancement);

```

### Specify your

* browser: IE 11 / firefox 52.2
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.98.1

**Comment by andrewtelnov** [comment]
@Kichi93 You do not need to call setDefaultValue on afterRender. 
setDefaultValue is called when it is needed, after loading the survey from Json, if defaultValue property is set, for example. It is a protected method, not public.

Do you want to remove optionsCaption completely? What should be shown if the value is not set?

Thank you,
Andrew

**Comment by Kichi93** [comment]
Hi @andrewtelnov, thanks for the response.

setDefaultValue is not called automatically if data is loaded into the survey - I am trying to recreate the effect when data is passed into the survey.

Yes, I would like to remove it completely. The value should always be set to either something the user has selected or the default value, so the "Choose..." option is not needed and allows the user to make the answer invalid, which is not helpful in this case.

**Comment by andrewtelnov** [comment]
@Kichi93 Here is [the example](https://plnkr.co/edit/xSVLWR?p=preview) that does what you need.

Thank you,
Andrew

**Comment by Kichi93** [comment]
@andrewtelnov, thanks for your help so far.

That example doesn't set the default value if data is passed into the survey - i.e. if you change the survey initiation to `$("#surveyElement").Survey({model: survey, data:{}});`

The reason we need this is because our system allows users to edit the answers to their surveys, so we load their previous answers in using the data attribute. If they change their answers to make some new questions visible, we want the defaults to be set automatically.

As a minor point on your example, having the "Choose..." option in the dropdown but using a default value and not letting the user select it so it is never actually used is not very user-friendly. Removing the option is much better if the user is not allowed to select it.

**Comment by andrewtelnov** [comment]
@Kichi93 When you set the data to empty object, all values, including the default values are cleared.
You have to use the following code:
```
function isEmptyObject(obj) {
  for(var prop in obj) {
    if (Object.prototype.hasOwnProperty.call(obj, prop)) {
      return false;
    }
  }
  return true;
}
if(!myPrevData && !isEmptyObject(myPrevData)) {
  survey.data = myPrevData;
}
$("#surveyElement").Survey({model: survey});
```
Regarding removing the "Choose..." option item. I have updated [the example](https://plnkr.co/edit/xSVLWR?p=preview) but it shows the "Choose..." option after value changed....
I may add into our TODO list, but adding this specific option will take some time. Probably, we have to call afterRender function after value change...

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@Kichi93 I have fixed the problem with rendering: https://github.com/surveyjs/surveyjs/issues/832
As result the code in the example before will work perfectly, "Choose..." option will not be shown on value changed.
The fix will be available in the next minor update, this week or early next week.

Thank you,
Andrew
