### ISSUE TITLE
Mobile device viewing issues for 0.97 or greater

### ISSUE THREAD

**Issue by alzulas** [surveyjs/surveyjs#827]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
Broken on Mobile devices

### What is the expected behavior?
Proper layout on smaller devices. Worked before I requested Bootstrap 4.0 updates (oops, sorry)

### How would you reproduce the current behavior (if this is a bug)?
Look at any of the 0.97 or newer surveys on a small device

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: personassessment.com/BISBAS.html or personassessment.com/RSSM
Beautiful on desktop. Terrible on mobile.

Test code

```
your_code_here

```

### Specify your

* browser: Safari for iOS, Chrome for iOS
* browser version: Current and up to date
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.98.3

![img_7225](https://user-images.githubusercontent.com/7562391/33911000-9aeb78de-df45-11e7-9db0-e0f0074c254e.jpeg)
![img_7226](https://user-images.githubusercontent.com/7562391/33911001-9b05b58c-df45-11e7-92b8-b9c947b00d1f.jpeg)

**Comment by tsv2013** [comment]
@alzulas Thank you for the report. We'll fix it.

**Comment by dmitrykurmanov** [comment]
We've fixed it and it will be in the next release. As a workawound you can use the following code:

```
  var myCss = {
    radiogroup: {
      itemControl: "",
      controlLabel: ""
    },
    checkbox: {
      itemControl: "",
      controlLabel: ""
    }
  };

...

  $("#surveyElement").Survey({
    model: survey,
    css: myCss
  });
```
you can see it in action at the https://surveyjs.io/Examples/Library/?id=survey-customcss&platform=jQuery
