### ISSUE TITLE
Validation after submission? 

### ISSUE THREAD

**Issue by JudyWu** [surveyjs/surveyjs#83]
Hi, 

Is there a way to validate the answers after submission instead of preventing people from completing the survey? Thank you very much!!!

Best,
Judy

**Comment by andrewtelnov** [comment]
@JudyWu Sure, you may use the onComplete event. It calls before  sendResults methods.
```
var survey = new Survey.Survey(surveyJSON, "surveyContainer");
survey.onComplete.add(function (s) {
    if (s.getValue("question1") == "no") {
        s.setValue("question1", "yes");
    }
});

```

**Comment by JudyWu** [comment]
@andrewtelnov Thank you very much for the prompt response! Your suggestion is that I do not add the validators attribute in the survey json but write my own validation inside the onComplete event? Is there possible that I add validators inside the survey json but I can still allow user to complete the survey and get notified that some of their answers are not valid?

**Comment by JudyWu** [comment]
@andrewtelnov Thank you very much for the prompt response! Sorry that I accidentally closed the issue. So your suggestion is that instead of putting the validators inside the survey json I write my own validation inside the onComplete event? How can I have the validators inside the survey json but users can still complete the survey and I get notified when the answers are not valid?

**Comment by andrewtelnov** [comment]
@JudyWu 
Here is the code that validates all questions before submission.
```
survey.onComplete.add(function (s) {
    var questions = s.getAllQuestions();
    for (var i = 0; i < questions.length; i++) {
        s.validateQuestion(questions[i].name);
    }
});

```
However, I am not sure, what you are trying to achieve. The error may be on the first page and you have several pages. If you provide more information, I may likely get a better suggestion.

Thank you,
Andrew

**Comment by JudyWu** [comment]
@andrewtelnov Sorry for the confusion. What I want is probably not validation but more like matching. People will get different thank you page depending on their answers and I can put them in the survey json instead of checking them at the onComplete event like adding a 'matching' attribute like 'validators'. Thank you very much!

**Comment by andrewtelnov** [comment]
@JudyWu Do you need something like [this](http://surveyjs.org/builder/?surveyid=8ee3a2e1-2741-48ce-9dad-d9f1b38879e0) ?
