### ISSUE TITLE
The "contains" conditional is not working for string variables

### ISSUE THREAD

**Issue by Kichi93** [surveyjs/surveyjs#831]
### Are you requesting a feature, reporting a bug or ask a question?

bug

### What is the current behavior?

Questions with visibleIf expressions using the "contains" keyword are not displaying even when the values match.

### What is the expected behavior?

A question will become visible if the referenced question contains a certain value.

### How would you reproduce the current behavior (if this is a bug)?

see test plunkr, type something containing the character "7" into the first question. See that the second question does not display.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: [plunkr](https://plnkr.co/edit/fQCH3NVjTxUrjqK7solm?p=preview)

### Specify your

* browser: IE 11 / Firefox
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.98.1

**Comment by andrewtelnov** [comment]
@Kichi93 contains doesn't work with string. Probably it makes sense to add this functionality and check for substring, if the value is string.
You have to register the function right now. Here is the updated [plunk](https://plnkr.co/edit/LJA5AMKBzzamTbRI1cFx?p=preview)

Thank you,
Andrew

**Comment by Kichi93** [comment]
@andrewtelnov, thanks, that fix is perfect.

It definitely worked with previous versions of surveyJS though - last version I know it worked with was 0.12.34.

**Comment by andrewtelnov** [comment]
@Kichi93 Yes, you are right. I will make it works again.

**Comment by andrewtelnov** [comment]
@Kichi93 The issue was fixed, unit tests were added.
The fix will be available in the next minor update.

Thank you,
Andrew
