### ISSUE TITLE
BUG Deleting a survey with PRIVATE API

### ISSUE THREAD

**Issue by abritopach** [surveyjs/surveyjs#835]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?

When you try to delete a survey by calling

https://dxsurvey.com/api/MySurveys/delete/{id}?accessKey={accessKey}

I get the following error

<Error>
<Message>An error has occurred.</Message>
</Error>

I think the endpoint is wrong.

### What is the expected behavior?

Delete the survey

### How would you reproduce the current behavior (if this is a bug)?

Call endpoint with parameters.

Specify your
browser: Google Chrome
browser version: 63.0.3239.84
surveyjs platform (angular or react or jquery or knockout or vue): angular

**Comment by tsv2013** [comment]
@abritopach Thank you for the report. We'll fix it ASAP.

**Comment by tsv2013** [comment]
@abritopach I've tried to delete the survey via this endpoint and everything works ok for me. Can you please open a ticket at the https://surveyjs.answerdesk.io/ ? I 'll mark it as private and you can post your account and survey info that allows me to reproduce the issue and fix it.

**Comment by abritopach** [comment]
@tsv2013 Done. Ticket created.

Thanks!!

**Comment by tsv2013** [comment]
@abritopach Thank you, I'll take a look.

**Comment by tsv2013** [comment]
@abritopach JFYI: I've made this ticket private.

**Comment by tsv2013** [comment]
@abritopach The bug is fixed. Site updated. Thank you for the report.

**Comment by abritopach** [comment]
@tsv2013 Thank you very much!

I'm sorry to be a bore, but I've detected other strange things.

When I make the request it is now deleted but instead of getting a OK message  I get a HttpErrorResponse

`
HttpErrorResponse {headers: HttpHeaders, status: 200, statusText: "OK", url: "https://dxsurvey.com/api/MySurveys/delete/ab877922…5b9f3c?accessKey=ac6bc54aee714bcaab3dc2e6aed0f15d", ok: false, …}
error
:
{error: SyntaxError: Unexpected end of JSON input at JSON.parse (<anonymous>) at XMLHttpRequest.onLo…, text: ""}
headers
:
HttpHeaders {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}
message
:
"Http failure during parsing for https://dxsurvey.com/api/MySurveys/delete/ab877922-484c-430a-ade3-ab354b5b9f3c?accessKey=ac6bc54aee714bcaab3dc2e6aed0f15d"
name
:
"HttpErrorResponse"
ok
:
false
status
:
200
statusText
:
"OK"
url
:
"https://dxsurvey.com/api/MySurveys/delete/ab877922-484c-430a-ade3-ab354b5b9f3c?accessKey=ac6bc54aee714bcaab3dc2e6aed0f15d"
__proto__
:
HttpResponseBase`

The same applies to requests for restore and archive survey.

- archive: api/MySurveys/archive/{id}?accessKey={accessKey}
- restore: api/MySurveys/restore/{id}?accessKey={accessKey}

With other requests such as activeSurveys or archiveSurveys the response is correct.

Can I help in any way?

Thanks!!
