### ISSUE TITLE
Substitution for question.DefaultValue

### ISSUE THREAD

**Issue by irynmare** [surveyjs/surveyjs#837]
### Are you requesting a feature, reporting a bug or ask a question?
question

### What is the current behavior?
Can you add substitution for question.defaultValue as it was done for title and description. 

### What is the expected behavior?
It will be great if I can assign some variable  name value through survey.setValue('name', 'test substitution') and then assign question.defaultValue = {name}. so survey should show 'test substitution' as default value.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@irynmare Why do you want to set the defaultValue and not the value itself?

Thank you,
Andrew

**Comment by irynmare** [comment]
we want to predefined some customer data like phone number from data we already have. But user should be able to change it.

**Comment by andrewtelnov** [comment]
@irynmare  If you set it to value directly, he will be still able to change it.
The only difference between defaultVaue and value, that defaultValue can be in survey JSON, it is a part of survey definition.
You may set the value dirrectly in our phone/e-mail question. You user is able to change them later. For end-user, it will look absolutely the same.

Thank you,
Andrew

**Comment by tsv2013** [comment]
@irynmare  you can assign pre-defined customer data via "survey.data" property, e.g:

```
var surveyModel = new Survey.Model(json);
surveyModel.data = { question1: "some text value" }
```

**Comment by irynmare** [comment]
Thank you for answers, I understand that I can assign values derectly in script, but then I am tied to question names, so I should know exact questions where this variable should be used. Also I would like to have this value in survey json.
It will be ideal if this substitution value can be assign in Survey Editor for the each question where I want to use it and in the script so I just can assign list of this values to survey. So basically for each question I would have list of substitution that I can use. In this way user that will create survey using survey editor won't be allowed to change the script which executes survey.

**Comment by tsv2013** [comment]
@irynmare You can add a tag to a question. This tag property can contains the name of your environment variable name (work_phone, person_city) and thus you can collect default values for certain variables and set them via the "data" property. What do you think?

**Comment by irynmare** [comment]
@tsv2013 I'll try this solution. Thank you.
