### ISSUE TITLE
Cannot seem to override values of certain default strings

### ISSUE THREAD

**Issue by JonBetts** [surveyjs/surveyjs#838]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question

### What is the current behavior?
I cannot seem to override the default text for strings such as 'requiredInAllRowsError'.

### What is the expected behavior?
To be able to override the values of such strings. Some can be overridden (e.g. 'showQuestionNumbers'), but I cannot seem to change others. Is there a standard way of doing this?

### How would you reproduce the current behavior (if this is a bug)?
N/A

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@JonBetts Do you want to override it for on all matrixes or just one?
You can always change the localized string for all questions like this:
`Survey.surveyLocalization.surveyStrings.requiredInAllRowsError = "My text";`

Thank you,
Andrew

**Comment by JonBetts** [comment]
Just one matrix would be ideal, but just changing it for all questions is a good start. Thanks Andrew, I will try that out! I'll close the ticket later on after I've been playing around.

**Comment by andrewtelnov** [comment]
@JonBetts If you need it to be diffrent for diffrent matrix and it should be a part of survey JSON, then I convert it to suggestion.

Thank you,
Andrew

**Comment by JonBetts** [comment]
How can I achieve this server-side rather than in the Javascript? For example, with `isAllRowRequired`, I can just create add it to a map in Java land like so: `questionObject.put("isAllRowRequired", true);` and it picks it up. But this doesn't seem to work for these string localisations.

**Comment by andrewtelnov** [comment]
@JonBetts SurveyJS is a client JavaScript library. I guess you are having the surver side code that renders the client code. You have to render the code I have provided:
`Survey.surveyLocalization.surveyStrings.requiredInAllRowsError = "My text";`
before you are rendering the code that creates the Survey on the client.
Probably I do not understand your scenario, then provide it in more details please.

Thank you,
Andrew
