### ISSUE TITLE
Add expand/collapse for Panel

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#843]
Add property panel.state: string, where 3 options are available, "default", "expanded", "collapsed".
When the state is collapsed then only a panel caption (title + expand/collapse button) is rendered.
When the state is expanded a panel caption contains the collapse button except panel title.
Two new methods should be added into panel: collapse() and expand().
If the panel is collapsed, but there a validation errors in it's questions then the panel should be expanded automatically.

**Comment by nicklas669** [comment]
Hi @andrewtelnov, is it possible to add a state that disables the collapse/expand feature somehow? I just want to have a section that can not be clicked to collapse/expand.

Thanks in advance,
Nicklas

**Comment by andrewtelnov** [comment]
@nicklas669 It is a default behavior. You can't expand/collpase the panel if it has the state = "default".
However, the cursor change it's state on panel title, also the panel title is not clickable. We will fix it in the next minor update.

Thank you,
Andrew
