### ISSUE TITLE
Survey doesn't scroll to the first question with an error

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#847]
Survey scrolled to the first question with an error. This functionality stopped to work in v1.0.

**Comment by andrewtelnov** [comment]
It was fixed with the following commit: https://github.com/surveyjs/surveyjs/commit/c8a7227c600cf3d7ec096d6abc60d52a6fe713af

**Comment by stsiushkevich** [comment]
@andrewtelnov There is an issue again.

**Comment by andrewtelnov** [comment]
@stsiushkevich Yes, it stopped working for checkbox and radiogroup. I have fixed it.

Thank you,
Andrew
