### ISSUE TITLE
Visible If not working after you click "Run Survey"

### ISSUE THREAD

**Issue by abrambailey** [surveyjs/surveyjs#848]
When you click on the Run Survey button depicted below, all questions load, even if you have some with visible false and those are meant to be triggered by visibleIf conditions. The survey seems to work fine when you enter the "Test Survey" tab instead.

![image](https://user-images.githubusercontent.com/978462/34498561-c77c8eaa-efc7-11e7-9fdb-d6411b9bfbf2.png)

**Comment by andrewtelnov** [comment]
@abrambailey We will look at it. Do you use surveyjs.io or dxsurvey.com website?

Thank you,
Andrew

**Comment by abrambailey** [comment]
surveyjs.io

**Comment by tsv2013** [comment]
@abrambailey
I've tried to reproduce the issue with the following JSON:

```
{
 pages: [
  {
   elements: [
    {
     type: "radiogroup",
     name: "question4",
     choices: [
      "item1",
      "item2",
      "item3"
     ]
    },
    {
     type: "boolean",
     name: "question3",
     visible: false,
     visibleIf: "{question4}='item1'"
    }
   ],
   name: "page1"
  }
 ]
}
```
And it works ok for me - "question3" is not visible until I select "item1" in both cases - neither on the "test survey" tab, nor via the "run survey button".
Could you provide us with the sample survey JSON, illustrating the issue?
