### ISSUE TITLE
Custom CSS panel

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#849]
Hi, in my survey i write a function like this

 this.model.onUpdateQuestionCssClasses.add(function(survey, options)
		{
			var classes = options.cssClasses
			
			if (options.question.renderAs == "SiteNV")
			{
				classes.mainRoot = "question_css question_nv";
			}
			
		});

to customize a question css class

It's possible to do the same for customize the PANEL css class?

thank you

**Comment by andrewtelnov** [comment]
@care46 It will be available from the next minor version.
```
  /**
   * The event is fired before rendering a question. Use it to override the default question css classes.
   * There are two parameters in options: options.question and options.cssClasses
   * <br/> sender the survey object that fires the event
   * <br/> options.question a question for which you may change the css classes
   * <br/> options.cssClasses an object with css classes. For example {root: "table", button: "button"}. You may change them to your own css classes.
   */
  public onUpdateQuestionCssClasses: Event<
    (sender: SurveyModel, options: any) => any,
    any
  > = new Event<(sender: SurveyModel, options: any) => any, any>();
```

Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov thank you! when will the minor version be released? can i have the min.js for jquery as beta?

**Comment by andrewtelnov** [comment]
@care46 I have updated the dev version: https://github.com/surveyjs/builds

Thank you,
Andrew
