### ISSUE TITLE
How to pass custom error and hold screen like existing validation message. 

### ISSUE THREAD

**Issue by ak34504** [surveyjs/surveyjs#851]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@ak34504 Have you seen validation examples: https://surveyjs.io/Examples/Library/?id=validators-event?

Thank you,
Andrew

**Comment by ak34504** [comment]
@andrewtelnov  Actually we are implementing some rule .according to rule we are generating Some error Message.we need to pass this error message as a existing validation message.

**Comment by andrewtelnov** [comment]
@ak34504 I am not sure I follow you. The example, I have posted above, should do what you need. Please click on "JavaScript" tab and look at code. There is a code onValidateQuestion event. 
There are 4 examples in this section. However, I think you need the one I have posted here.

Thank you,
Andrew
