### ISSUE TITLE
jQuery choicesByUrl not firing when first value select

### ISSUE THREAD

**Issue by erbaker** [surveyjs/surveyjs#852]
I have a question/concern about a two dropdown (country/state) system where the second dropdown is dependent and changes based on a selection of the first. When selections are manually done with jQuery, they do not get recognized as being selected and the page errors out. This is the in the context of an automated test.

Currently, using jQuery to select the first option does not fire any kind of event that will update the second dropdown. I have tried to manually trigger every event I can think of, yet nothing works.

I would expect that an event is raised when the first dropdown has changed so that the second dropdown will refresh from the URL based on the input from the first dropdown.

https://plnkr.co/edit/0sZFOKzlAlWUujDpgQuN?p=preview

Find the ID of the first dropdown, and select one of the options via jquery in console:
$("#sq_100i").val("Africa");

The second dropdown does not get populated. 

```

### Specify your

* browser: Firefox
* browser version: recent
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: recent

**Comment by andrewtelnov** [comment]
@erbaker You are using an old version of SurveyJS. Please use the latest one, v1.0.0. We were out of beta!
I have updated the version in your plunker: https://plnkr.co/edit/0sZFOKzlAlWUujDpgQuN?p=preview

Thank you,
Andrew

**Comment by erbaker** [comment]
Hi @andrewtelnov ,
I see the updated plunkr, however now running `$("#sq_100i").val("Africa");` via console doesn't even select the country. That is in Firefox. In Chrome, it does select, but does not populate the country dropdown. Are we missing anything else?

**Comment by andrewtelnov** [comment]
@erbaker You have to use SurveyJS function/properties, for example to set the value to the question use the following code: `survey.setValue("region", "Africa");`
I've updated the plunker again: https://plnkr.co/edit/0sZFOKzlAlWUujDpgQuN?p=preview

Thank you,
Andrew

**Comment by erbaker** [comment]
Is this accessible in the context of an automation test? We have access to jQuery, but seemingly not Survey.

**Comment by andrewtelnov** [comment]
@erbaker What tools do you use for functional testing?
We are using TestCafe and happy with it: https://github.com/DevExpress/testcafe
It fully emulates User Input operations.
Here is our functional tests: https://github.com/surveyjs/surveyjs/tree/master/testCafe

Thank you,
Andrew

**Comment by erbaker** [comment]
Seleno, which sits on top of Selenium. We wanted to try and keep it in C#, but it looks like we might have to change.

**Comment by andrewtelnov** [comment]
@erbaker Unfortunately, there is no two-way binding. We do not get notification about changing the value via jQuery :-(
The correct way for functional testing is emulating input operation. In this case, if a widget/input are hiding by a window or something, you will get error that test failed. The mouse/keyboard operation could not performed.

Thank you,
Andrew
