### ISSUE TITLE
Call other function in  survey.onComplete.add() without going to "Thank you for completing the survey!" Message

### ISSUE THREAD

**Issue by ak34504** [surveyjs/surveyjs#853]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@ak34504 I do not understand the issue, you may call any function on this event:

```
survey.onComplete.add(function(survey, options) {
   myFunction();//
});
```
Thank you,
Andrew
