### ISSUE TITLE
Problem with jquery selector (maybe) like issue #405

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#854]
Hi, i have a problem like this (you can see in this example)

https://plnkr.co/edit/8BCb8HYetDmqBrS0IOui?p=preview

I have a 3 pages survey, and i have a custom widget for date/datetime field (jquery datepicker)

If you go in the second page of the survey, you can see the widget on date field (question 4,5,10,16) and work correctly, if you go to third page you can see that the 17 question was a text question

Now, if you come back to second page, add and remove a row in the 16 question and then return on the third page, you can see that the text question (17) take the widget!!! but is not correct...

It's a problem woth my json?? there is another problem?

Thank you

**Comment by andrewtelnov** [comment]
@care46 I just copied the code from our jquery datetime widget and everything is working: https://plnkr.co/edit/q2wUANY6CjuuGjqiuaqI?p=preview
I would suggest to use our custom widget:  https://surveyjs.io/Examples/Library/?id=custom-widget-datepicker

Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov  ok, i see that your widget is not with "default render"... probably there is a problem only if widget have property "default render" = true?

Now i try this solution, and i create all my widget with no default render
