### ISSUE TITLE
Use localized otherText in matrixdynamic

### ISSUE THREAD

**Issue by sfcrebecca** [surveyjs/surveyjs#857]
### Are you requesting a feature, reporting a bug or ask a question?

New Feature: To support localized otherText value in matrixdynamic

### What is the current behavior?
I want to use a dropdown in a matrixdynamic with the "others" option with a customized otherText. 

The code I used:
`Survey.JsonObject.metaData.addProperty("matrixdropdowncolumn", { name: "otherText:text", default: "Customized Other Text" });`

The current behavior is:
1. Specify otherText with no localized value, it can show the customized otherText. (correct)

"otherText": "Others, please specify the reason:"

2. Specify otherText with localized values, it always shows the default value. (incorrect)

### What is the expected behavior?
When I specify "otherText" like the following:
```
          "otherText": {
            "default": "Others, please specify the reason (in Eng): ",
            "zh": "Others, please specify the reason (in Chi)"
          },
```
I expect it could pick up the localized value and I want to know how could I customize it to make it works.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular 
* surveyjs version: 1.0.0

**Comment by andrewtelnov** [comment]
@sfcrebecca You are right. There is no API for adding a localized property. I have added it into our TODO list.

Thank you,
Andrew

**Comment by sfcrebecca** [comment]
Thanks a lot, @andrewtelnov 

May I know if this applies to all surveyjs platform?

If I switch to React, could I customize it to make it works before the enhancement is done? Many thanks.

**Comment by andrewtelnov** [comment]
@sfcrebecca It has to be implemented in platform independed part, surveyJS model. As soon as, we will add it, it will be available in all supported platforms.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@sfcrebecca It has been implemented. It will be available in the next minor version. We will release it on Monday/Tuesday.

**Comment by sfcrebecca** [comment]
Thanks so much for your prompt action, @andrewtelnov
