### ISSUE TITLE
alter style properties in jquery version not work correctly

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#858]
Hi, i need an help... i have this survey

https://plnkr.co/edit/16dWjVeYu5SaUrGC01yl?p=preview

In this survey i have created a link to show/hide some field, and i have also question that is hiding by formula..

In my example the bug was like this:

in first page you can see TEST TITLE of first question.. then go on second page and click on link "close section", this link set display=none on field text... then put flag "NON VALUTABILE" that hide question by formula, now if you come back on first page, TEST TITLE of first question disappear!!

what i can do to resolve this?

thank you

**Comment by andrewtelnov** [comment]
@care46 We have added panel.state property. It is available in the latest version.
Here is [the example](https://plnkr.co/edit/TeoXlpKANFQvfYo2eULb?p=preview)

It looks good and you do not to do anything.

Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov works good!
