### ISSUE TITLE
How to get JSON Definition programmatically 

### ISSUE THREAD

**Issue by pankanis-rushikesh** [surveyjs/surveyjs#859]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
I have  json definition which I am using to render Survey Model. But after adding a qquestion dynamically i need to update the exisiting json definition also.
So how would I get the json definition from survey model
Form Render Code : 
 ```
 var model = new Survey.Model(this.state.formDefinition)
let Questions= model.getAllQuestions()
for(var question  in Questions){
            
          if(matrixQuestion.)
        for(let i=0;i<this.state.noOfDyanamicRows;i++){
            matrixQuestion.addRow()
        } 
}
        return (
            <Survey.Survey model={model} />
```
What I need is after adding row in matrixdynamic question type  I need to access new json defintion 

How would I do this
Also I need to hide the addRow button from user.
* surveyjs platform (angular or react or jquery or knockout or vue): React

**Comment by dmitrykurmanov** [comment]
Hello! You can use the following code: `new Survey.JsonObject().toJsonObject(model);`

**Comment by pankanis-rushikesh** [comment]
Thanks

**Comment by andrewtelnov** [comment]
@hugomejia In the latest version you may simply call
survey.toJSON();, as well as any other element, for exampel page.ToJSON() or myQuestion.toJSON();

Thank you,
Andrew
