### ISSUE TITLE
anable to call surveyValidateQuestion() function.

### ISSUE THREAD

**Issue by ak34504** [surveyjs/surveyjs#862]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by dmitrykurmanov** [comment]
Hello! Could you please describe the issue in more details?

Please check the example: https://surveyjs.io/Examples/Library/?id=validators-event&platform=jQuery&theme=default
