### ISSUE TITLE
Custom element disappears on conditional comments

### ISSUE THREAD

**Issue by cruckie** [surveyjs/surveyjs#863]
### Are you requesting a feature, reporting a bug or ask a question?
bug/asking a question

### What is the current behavior?
Custom element disappears when comments are conditionally changed 

### What is the expected behavior?
Custom elements do not disappear

### How would you reproduce the current behavior (if this is a bug)?
With the provided test code and survey I insert a div element, which I expect to stay.
I have a rating going from 1 to 6. I then have 3 comments that are shown depending on the chosen rating. 1 and 2 shows one message. 2 and 3 shows another and 4 and 6 shows a third comment.
My custom div element is shown initially, but it gets hidden when I choose an option (when a different comment is shown).

So:
1. Initially my div is shown
2. I choose 4. My element disappears (not expected)
3. I choose 3. My element stays (expected)
4. I choose 2. My element disappears again (not expected)

I'd like to know if this is intended and I'm doing it wrong or if this is a potential bug

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

Survey (change da-DK to your preference):

 {
  "questionTitleTemplate": "{title} {require}",
  "showCompletedPage": false,
  "pages": [
    {
      "elements": [
        {
          "type": "rating",
          "name": "1516006346046",
          "tag": "",
          "visibleIf": "",
          "isRequired": true,
          "title": {
            "da-DK": "Rate me!"
          },
          "description": {
            "da-DK": "Some describing description"
          },
          "minRateDescription": {
            "da-DK": "Lowest"
          },
          "maxRateDescription": {
            "da-DK": "Highest"
          },
          "rateValues": [
            {
              "id": "1516006373437",
              "value": "1",
              "color": "#ff0000",
              "text": {
                "da-DK": "1"
              }
            },
            {
              "id": "1516006374821",
              "value": "2",
              "color": "#ff0000",
              "text": {
                "da-DK": "2"
              }
            },
            {
              "id": "1516006375341",
              "value": "3",
              "color": "#c2ba02",
              "text": {
                "da-DK": "3"
              }
            },
            {
              "id": "1516006375717",
              "value": "4",
              "color": "#c2ba02",
              "text": {
                "da-DK": "4"
              }
            },
            {
              "id": "1516006376024",
              "value": "5",
              "color": "#30b800",
              "text": {
                "da-DK": "5"
              }
            },
            {
              "id": "1516006376485",
              "value": "6",
              "color": "#30b800",
              "text": {
                "da-DK": "6"
              }
            }
          ]
        },
        {
          "type": "comment",
          "name": "1516006414261",
          "tag": "",
          "visibleIf": "{1516006346046} = \"1\" or\n{1516006346046} = \"2\"",
          "isRequired": false,
          "title": {
            "da-DK": "1 or 2"
          },
          "description": {
            "da-DK": "You chose 1 or 2!"
          }
        },
        {
          "type": "comment",
          "name": "1516006737504",
          "tag": "",
          "visibleIf": "{1516006346046} = \"3\" or\n{1516006346046} = \"4\"",
          "isRequired": false,
          "title": {
            "da-DK": "3 or 4"
          },
          "description": {
            "da-DK": "You chose 3 or 4!"
          }
        },
        {
          "type": "comment",
          "name": "1516006751391",
          "tag": "",
          "visibleIf": "{1516006346046} = \"5\" or\n{1516006346046} = \"6\"",
          "isRequired": false,
          "title": {
            "da-DK": "5 or 6"
          },
          "description": {
            "da-DK": "You chose 5 or 6!"
          }
        }
      ]
    }
  ]
}

Code:
On the onAfterRenderQuestion event I do the following:

model.onAfterRenderQuestion.add(function (sender, options) {
    if (options.question.rates) {
        var question = container.find('#' + options.question.id);
        question.find('div.btn-group').prepend('<div>Some custom text</div>');
    }
}

### Specify your

* browser: Chrome
* browser version: 63.0.3239.132
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery
* surveyjs version: 1.0.1

**Comment by cruckie** [comment]
Does a workaround currently exist?

**Comment by tsv2013** [comment]
@cruckie We are investigating this issue right now. We'll update this thread immediately.

**Comment by tsv2013** [comment]
Fixed in the v1.0.2

**Comment by cruckie** [comment]
Thank you very much! The issue is now gone.
