### ISSUE TITLE
Mobile version does not display properly

### ISSUE THREAD

**Issue by alzulas** [surveyjs/surveyjs#864]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

Text on mobile version of website overlaps.

### What is the expected behavior?

Text and formatting should look the same on mobile as it does on desktop.

### How would you reproduce the current behavior (if this is a bug)?

Create any radio button or multichoice question with more than 3 responses. Put answers in columns. view on a mobile device. 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
http://www.personassessment.com/BISBAS.html

Test code
I know the below question displays improperly on an iPhone in Safari, Firefox, and Chrome
```
{ questions: [
            //Inserting space between questions.
                { type: "html", name: "InsertSpaceHere", html:"<p></p>"},
            //Another radio group. This time for age. 
            {type: "radiogroup", name: "age", colCount: 3, title: "What is your age?", choices: ["16-|16 years and below", "23-30|23-30 years old", "65-74|65-74 years old", "17-19|17-19 years old", "31-45|31-45 years old", "75+|75 years and older", "20-22|20-22 years old", "46-64|46-64 years old"]},
            //Inserting space between questions.
                { type: "html", name: "InsertSpaceHere", html:"<p></p>"},
        ]},
```

### Specify your

* browser: Safari, Firefox, Chrome on iPhone 7
* browser version: All up to date
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.1, been broken since at least 0.98.3

![fullsizeoutput_c2e](https://user-images.githubusercontent.com/7562391/34961117-ca3ba6fa-f9f2-11e7-9bde-d982b096506a.jpeg)
![fullsizeoutput_c2f](https://user-images.githubusercontent.com/7562391/34961118-ca5262fa-f9f2-11e7-9b11-e3d6daa8ad64.jpeg)

**Comment by tsv2013** [comment]
I've opened your page and found large left and right margins around the survey.
These margins are not set by SurveyJS library.
If I remove them the page looks ok for me:

![image](https://user-images.githubusercontent.com/3013415/34973641-e42328b6-fa99-11e7-9329-2e76a920ffb1.png)

**Comment by alzulas** [comment]
I forgot that I had to set margins a long time ago so that the survey wouldn't sit on the edge of the laptop screen. Set a media size for margins, and it's fixed. Thanks!
