### ISSUE TITLE
Survey styling in modal is strange

### ISSUE THREAD

**Issue by healkar01** [surveyjs/surveyjs#867]
I upgraded to the latest version of SurveyJS and now our surveys look very strange in the modal dialog that we are using.  It was fine before.  Now there is a large border to the top, right, and left.  Previously, there was no border like that.  

![previewsurvey](https://user-images.githubusercontent.com/20865786/35001808-ad3eed32-fab5-11e7-9bf0-e68b3ac52f7b.png)

Please advise,

Karen Healey

**Comment by tsv2013** [comment]
This is the SurveyJS library new default theme. If you want, you cam remove side margins via custom CSS.

**Comment by dmitrykurmanov** [comment]
I've created an example for you (default theme without paddings): https://plnkr.co/edit/QtxuSd?p=preview

Or you can just change 
` <link href="https://surveyjs.azureedge.net/1.0.2/survey.css" type="text/css" rel="stylesheet" />` 
to
`<link href="https://surveyjs.azureedge.net/0.12.36/survey.css" type="text/css" rel="stylesheet" />`

here an example: https://plnkr.co/edit/0NSP18?p=preview

**Comment by healkar01** [comment]
Thank you... I tried your CSS but it did not work for me.  I'll put our UI designer on it... 

Thanks again!

Karen

**Comment by dmitrykurmanov** [comment]
Is `0.12.36/survey.css` styles not fine as before? It could be an our bug because 0.12.36 version was published before the new design.

**Comment by healkar01** [comment]
I didn't want to go back to the earlier style sheet because there were some other issues displaying the survey in the earlier version (which is why we upgraded).

**Comment by dmitrykurmanov** [comment]
Ok please feel free to contact us with any difficulties with custom styling.
