### ISSUE TITLE
How to add question types in MatrixDynamic Question Editor

### ISSUE THREAD

**Issue by pankanis-rushikesh** [surveyjs/surveyjs#869]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
Currently when I add matrixDynamic question , number of question types I can add in that are limited also i am not able to change the all the properties from QuestionEditor as It does not show all properties.

### What is the expected behavior?
I would like to know if there is a way to show new dynamic properties in MatrixDynamicQuestionEditor as that would be helpful Plus is there a way to show new Question Types in MatrixDynamicQuestion

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your
* surveyjs platform (angular or react or jquery or knockout or vue):
****

**Comment by pankanis-rushikesh** [comment]
Ok.
But can we show all properties which are there for existing Questions for whatever question type we are selecting in MatrixDynamic in QuestionEditor?
i.e.
![cropped-questioneditor-screenshot](https://user-images.githubusercontent.com/33685353/35034475-524db7ca-fb94-11e7-9c11-595d4c0a85d1.png)

**Comment by andrewtelnov** [comment]
@pankanis-rushikesh We have several requests about improving the flexibility of our matrix columns. Our users want to have diffrent question types (cellType), have more properties and add/remove cellTypes based on their needs.
I will work on these tasks next days. I'm not sure I will be able to implement something better, but let's see what can I do.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@pankanis-rushikesh The following code will add the file cell type:
```
        Survey.matrixDropdownColumnTypes.file = {
            properties: ["showPreview", "imageHeight", "imageWidth"]
        };
```

Thank you,
Andrew
