### ISSUE TITLE
How to set State of survey.we don't want to clear answered field when click on complete button.?

### ISSUE THREAD

**Issue by kmmamta** [surveyjs/surveyjs#872]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
Entered data is held in the `data` property of the survey model
```
survey.data
```
You can get/set the data value.

Then you click on the "Complete" button, you will see the "complete survey" banner, but survey data is not cleared.
On our service: if you refresh the web page survey will be completely reloaded and will not contain data of the previous answerer.
In your custom page you can initialize survey with some data as shown in this example: https://surveyjs.io/Examples/Library/?id=survey-data&platform=jQuery&theme=default

Could you clarify your requirements?

**Comment by kmmamta** [comment]
thanku @tsv2013 ,
Actually i want to create a survey  when click on complete button answer data will not clear.after  click on complete button i don't to go "complete survey" banner.

**Comment by dmitrykurmanov** [comment]
If I understand you correctly, you need to use **displaymode** feature: please see the example https://surveyjs.io/Examples/Library/?id=survey-displaymode&platform=jQuery&theme=default

Or you can override `completeLastPage`:

```
survey.completeLastPage = function () {
  console.dir(survey.data);
};
```
