### ISSUE TITLE
How we can remove Question No sequence.?

### ISSUE THREAD

**Issue by kmmamta** [surveyjs/surveyjs#874]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@kmmamta `survey.showQuestionNumbers = "off";`
https://surveyjs.io/Examples/Library/?id=survey-options

Thank you,
Andrew

**Comment by kmmamta** [comment]
thanku @andrewtelnov

**Comment by sarn3792** [comment]
What about if I only want to avoid question number in my first page? Is there any way to do it?

Thanks!

**Comment by andrewtelnov** [comment]
@sarn3792 I have answered [here](https://github.com/surveyjs/surveyjs/issues/1631).

Thank you,
Andrew
