### ISSUE TITLE
Ability to use custom functions (as operators) in visibleIf

### ISSUE THREAD

**Issue by asilverstein** [surveyjs/surveyjs#878]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

VisibleIf expressions support a set of predefined operators

### What is the expected behavior?

Does surveyjs support creating custom operators, i.e., user-defined functions as operators, to use inside visibleIf expressions?

For example, a visibleIf expression would be just a function call that returns true or false, i.e., "myBooleanFunction()" 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@asilverstein Could you please provide us an example of expression?

Thank you,
Andrew

**Comment by asilverstein** [comment]
Sorry if I'm not being clear. I'm trying to determine if this is possible in surveyjs. I'm looking at [this page](https://surveyjs.io/Examples/Library/?id=condition-kids&platform=jQuery)

The example for _visibleIf_ in the JSON is:

`"{kids} >= 5`

Instead, I would like to use an existing javascript function that I wrote, instead of the comparison operator.

For example:
```
function myFunction(surveyQuestion) {
    return 123; //obviously with some more complex logic here
}
```
Where myFunction() is a function that can be used in the survey question's _visibleIf_ expression. For example:

`"myFunction(kids) > 122`

Thanks for your quick reply!

**Comment by andrewtelnov** [comment]
@asilverstein We public [a story](https://hackernoon.com/surveyjs-an-open-source-javascript-survey-library-with-versions-for-angular-2-react-vue-2086d988b974) on medium yesterday. 
Please read the following paragraph: "Custom Functions in “visibleIf” and “enableIf” Expressions".
It describes exactly what you need.

Thank you,
Andrew

**Comment by asilverstein** [comment]
Excellent, thank you very much!
