### ISSUE TITLE
[Feature] Text replacements

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/surveyjs#879]
Do you or do you plan to support custom replacements inside all question fields?

Think of things like replacing the question text or an answer label with a dynamic expression that uses the answer of previous question(s).

If not would you like to support it at some point and are you open to PRs implementing such a feature?

**Comment by andrewtelnov** [comment]
@SamMousa Are you talking about [this functionality](https://surveyjs.io/Examples/Library/?id=survey-processtext)

Thank you,
Andrew

**Comment by SamMousa** [comment]
Hmm, sorry for wasting your time. I missed this in the documentation, looks nice!
