### ISSUE TITLE
[Feature] Piping

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/surveyjs#880]
### Are you requesting a feature, reporting a bug or ask a question?
Feature

Do you or do you plan to support answer piping?

An example of piping is having 2 multiple choice questions like this:
`````
1. Which car brands do you know?
[   ] A
[ x ] B
[ x ] C
[   ] D

2. Out of the car brands that you know, which ones would you consider buying?
[ ] B
[ ] D
````

Basically the answer options for 1 and 2 are the same, but in question 2 they are filtered based on what's selected in question 1.

Would you accept a PR implementing such functionality?

**Comment by andrewtelnov** [comment]
@SamMousa Here is [the example](https://plnkr.co/edit/FfYvPB?p=preview)

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@SamMousa Here is the [generic example](https://plnkr.co/edit/4leKYN?p=preview).
The library allows to add extentions based on your needs.

Thank you,
Andrew

**Comment by SamMousa** [comment]
Okay thanks!
