### ISSUE TITLE
Could not change checkbox question value onValueChanged event in knockout/jQuery versions

### ISSUE THREAD

**Issue by cruckie** [surveyjs/surveyjs#881]
### Are you requesting a feature, reporting a bug or ask a question?
bug

### What is the current behavior?
On the onValueChanged event I change the options.value, but the change is not reflected in the survey.

### What is the expected behavior?
I expect it to work as in version 1.0.1 where the change would reflect in the survey.

In case this is intended, how am I supposed to get around this problem?

### How would you reproduce the current behavior (if this is a bug)?
I have a custom property called maxChoices which limits the amount of checkboxes that can be checked.
I expect the number of selected checkboxes to be limited to the custom property value.

The following code worked in version 1.0.1 but stopped working in 1.0.2:

```
model.onValueChanged.add(function (sender, options) {
    if (options.question.maxChoices) {
        var question = container.find('#' + options.question.id);
        var checked = question.find('input[type="checkbox"]:checked').length;

        if (checked > options.question.maxChoices) {
            options.value.pop();
        }
    }
});

```

### Specify your

* browser: Chrome
* browser version: 63.0.3239.132
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery
* surveyjs version: 1.0.3

**Comment by andrewtelnov** [comment]
@cruckie I doubt that it worked. The code should be:
`options.question.value.pop();`

Thank you,
Andrew

**Comment by cruckie** [comment]
@andrewtelnov Thanks for the reply and suggestion.
It did work fine in 1.0.1 with the code I posted. Perhaps it wasn't supposed to work, but it did for me.
As for your suggestion options.question.value.pop() is still not working for me. The checkbox stays checked and when the onValueChanged is hit again options.question.value contains the value it was supposed to remove the first time, e.g lets say maxChoices is 2.

1. I check one checkbox
2. I check the second checkbox
3. I check the third checkbox. At this point I'll expect only two checkboxes to be checked, but all three are checked).
4. I check the fourth checkbox. The options.question.value now contains the list of all four boxes (prior to the pop()), where I hoped it would contain only the three (first, second and fourth)

It seems like the values are restored after the manipulation in the onValueChanged event.

**Comment by andrewtelnov** [comment]
@cruckie You are right. It doesn't work in knockout and it doesn't work in jQuery now, because it is build based on knockout since the last version. We will work on the fix.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@cruckie We will release the minor update today. After that the following code will work:
```
            if (options.value && options.value.length > 2) {
                options.value.shift();
                options.question.value = options.value;
            }
```
I have added a unit-test on this bug.

Thank you,
Andrew

**Comment by cruckie** [comment]
@andrewtelnov Thank you very much for the fast response and fix. I'm looking forward to the update.

Best regards,
Casper

**Comment by cruckie** [comment]
It works! Thanks a lot!

**Comment by tsv2013** [comment]
@cruckie 1.0.4 has been released. You can check it.
