### ISSUE TITLE
Survey-react throwing onComplete.add not a function error

### ISSUE THREAD

**Issue by pankanis-rushikesh** [surveyjs/surveyjs#883]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the expected behavior?
I need to render a form based on json model.
My code is this  : 
```
import * as Survey from 'survey-react';

                            <Survey.Survey
                                model={form[0].definition}
                                onValueChanged={this.onValueChanged}
                                onComplete={this.onComplete.bind(this)}
                            />

```
But I am getting this error : 
```
survey.react.js:9339 Uncaught TypeError: this.survey.onComplete.add is not a function
    at Survey.setSurveyEvents (survey.react.js:9339)
    at Survey.updateSurvey (survey.react.js:9330)
    at new Survey (survey.react.js:9182)
    at ReactCompositeComponent.js:294
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (ReactCompositeComponent.js:293)
    at ReactCompositeComponentWrapper._constructComponent (ReactCompositeComponent.js:279)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:187)
    at Object.mountComponent (ReactReconciler.js:45)
    at ReactDOMComponent.mountChildren (ReactMultiChild.js:236)
```

I have defined onComplete and onValueChanged functions inside my react component.but I am still getting this.Could you tell me what can be the cause for this behaviour.
Am I missing something or It's bug in library ? 

### Specify your

* browser: google chrome
* browser version: Version 61.0.3163.100 
* surveyjs platform (angular or react or jquery or knockout or vue): survey-react
* surveyjs version:  0.95.0

**Comment by dmitrykurmanov** [comment]
I can't reproduce it. Here an example https://plnkr.co/edit/SNcSUjRC5pYkNNVbnw6U?p=preview Could ypu please check it? May be I've missed something...

**Comment by pankanis-rushikesh** [comment]
I actually not rendering the survey directly
I am actually dynamically rendering it.
**Main Component **  
```
class MainComp {

//this component render form based on some condition otherwise it returns some div
createSurveyModel(){
// Code to get definiton dynamically 
//  I have also defined onComplete adn onValueChanged in this component only 
return (<Survey.Survey
                            model={definition}
                            onValueChanged={this.onValueChanged}
                            onComplete={this.onComplete.bind(this)}
                        />

}

 render() {
        return (
            <div>                
                 {this.createSurveyModel()}
            </div>
        )
    }

}

```

And in this component I am getting that error.
Inside main component this is pointing towards MainComponentClass . 
Can that be a issue

**Comment by dmitrykurmanov** [comment]
I've added "onValueChanged" and "onComplete" in an our [react_quickstart ](https://github.com/surveyjs/surveyjs_react_quickstart) repo, please see the commit: 
https://github.com/surveyjs/surveyjs_react_quickstart/commit/0ca29579882da7b644de44c325ccf6234ea36935
Could you check it please? I think that it works as expected.

May be you need to update node modules? You can remove `node_modules` folder and then cast `npm i`
or you can create an example repo with this bug and we will check it. Thanks.
