### ISSUE TITLE
Add clone pattern to surveyjs

### ISSUE THREAD

**Issue by pigeonflight** [surveyjs/surveyjs#885]
Unless I'm missing it, surveyjs doesn't seem to have a straight forward way for a user to make a field or group of fields clonable.

# Ideal scenario
## Defining something as "clonable"
Developer/Editor "flags" a field or group of fields as "clonable".

## Usage
When a user visit the survey. Clonable fields provide an option to "add a new one". 
A good example of an implementation is http://patternslib.com/clone, see the animation below.
![clonepattern](https://user-images.githubusercontent.com/31827/35482523-c8344f58-0404-11e8-8be7-508a89e2cc85.gif)

**Comment by andrewtelnov** [comment]
@pigeonflight We have Dynamic Panel that does what you need: https://surveyjs.io/Examples/Library/?id=questiontype-paneldynamic
You may find more information on [this blog on medium](https://hackernoon.com/surveyjs-an-open-source-javascript-survey-library-with-versions-for-angular-2-react-vue-2086d988b974)
Please go to "Dynamic Panel: Dealing with List Data" section.

Thank you,
Andrew
