### ISSUE TITLE
VisibleIf extension

### ISSUE THREAD

**Issue by Kichi93** [surveyjs/surveyjs#887]
### Are you requesting a feature, reporting a bug or ask a question?

New feature

### What is the current behavior?

Questions require very long visibleIf queries where there is a tall tree of questions.

For example, if question2 is visible depending on the answer to question1 and question3 is visible depending on the answer to question2 etc.... See example survey JSON below. In this case, the visibleIf query for question10 has to be exactly the same as question9, with the addition of the clause for question9's value. If this isn't done, changing the value of question1 will turn question2 invisible but not any subsequent questions.

### What is the expected behavior?

If there was functionality in the visibleIf parameter to determine if question9 is visible (e.g. "{question9} isVisible"), then the rule would become a lot simpler and more robust to future changes in question definitions.

#### Provide the test code and the tested page URL (if applicable)

Here is the JSON for an example. What I'm looking to do is only display one question at a time. If you answer "Yes" to questions 1-4 then change the answer to question1 to "No", you'll see that question5 is still visible. It would be nice if there was a way to make it only visible if question4 is visible and equals "Yes" without having to reference all the other questions. The conditions don't get too long or horrible here but imagine extending it by 20 questions and it gets to be a pain to manage.

Test code

```
{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "radiogroup",
     name: "question1",
     title: "Show next question?",
     choices: [
      "Yes",
      "No"
     ]
    },
    {
     type: "radiogroup",
     name: "question2",
     visible: false,
     visibleIf: "{question1}==\"Yes\"",
     title: "Show next question?",
     choices: [
      "Yes",
      "No"
     ]
    },
    {
     type: "radiogroup",
     name: "question3",
     visible: false,
     visibleIf: "{question1}==\"Yes\" && {question2}==\"Yes\" ",
     title: "Show next question?",
     choices: [
      "Yes",
      "No"
     ]
    },
    {
     type: "radiogroup",
     name: "question4",
     visible: false,
     visibleIf: "{question1}==\"Yes\" && {question2}==\"Yes\" && {question3}==\"Yes\"",
     title: "Show next question?",
     choices: [
      "Yes",
      "No"
     ]
    },
    {
     type: "radiogroup",
     name: "question5",
     visible: false,
     visibleIf: "{question4}==\"Yes\"",
     title: "This is the end.",
     choices: [
      "OK"
     ]
    }
   ]
  }
 ],
 showNavigationButtons: false,
 showCompletedPage: false,
 showQuestionNumbers: "off"
}

```

Many thanks
K

**Comment by andrewtelnov** [comment]
@Kichi93 Yes, it is in our TODO list and it is high priority, together with better UI for expression Editor (visibleIf, enableIf, expression properties).
There are some technical issues in implementing this functionality and make sure it works fast, that is why, I can't give you any estimation at the current moment.
I just want to assure you, that this is something we want to implement it.

Thank you,
Andrew

**Comment by tsv2013** [comment]
The original task is https://github.com/surveyjs/editor/issues/251
Copied details from this issue and closed as duplicate

**Comment by tsv2013** [comment]
We've implemented autocomplete feature for visibleIf, enableIf and expression in the SurveyJS Builder (Editor) via Ace editor + ext language tools. You can try this feature in the [Online Survey Builder](https://surveyjs.io/Survey/Builder/) on our site. You feedback is hightly appreciated.
