### ISSUE TITLE
Timed questions and mixed reply options

### ISSUE THREAD

**Issue by f-weber** [surveyjs/surveyjs#888]
Dear SurveyJS,

thank you so much for making this available.
I have just two features, I am wondering if they are possible to integrate:

1) Timed questions - I need to know how long people took to answer a question. This could be achieved by implementing timestamps on each page and calculating the time in between?

2) Mixed radio button and text questions - I need to be able to give people wither the option to respond 'A' provide some 'text input' or to answer 'B' without a text. It would be a multipletext type with the text part being optional to be displayed. Is this possible to add?

Thank you very much for your help.

Kind regards,
Florian Weber

**Comment by andrewtelnov** [comment]
@f-weber I have answered on questions here: https://surveyjs.answerdesk.io/internal/ticket/details/T400

Thank you,
Andrew
