### ISSUE TITLE
hide a field

### ISSUE THREAD

**Issue by masciugo** [surveyjs/surveyjs#889]
### Are you requesting a feature, reporting a bug or ask a question?

question

### What is the current behavior?

cannot hide a field

### What is the expected behavior?

hide a field in order to manipulate it behind the scenes and send it to the server along with others

I am trying to reach my aim by using onUpdateQuestionCssClasses event but I wonder if there is a more elegant method

thanks

**Comment by tsv2013** [comment]
You can write an expression in 'visibleIf' to show/hide your question(s).
Here is the example - https://surveyjs.io/Examples/Library/?id=condition-kids&platform=jQuery&theme=default
Here is the documentation - https://surveyjs.io/Documentation/LibraryParameter?id=QuestionBase&parameter=visibleIf

Does it fit your needs?

**Comment by masciugo** [comment]
`visibleIf` completely removes the filed from data. I need to keep in data so that it can be sent back to the server

**Comment by tsv2013** [comment]
You can set the `clearInvisibleValues` property of the survey to 'none' to include the invisible values into the survey data. Here is the documentation - https://surveyjs.io/Documentation/Library/?id=surveymodel#clearInvisibleValues

**Comment by masciugo** [comment]
thank you... Sorry I had missed it
