### ISSUE TITLE
support html tags in choices elements

### ISSUE THREAD

**Issue by reece** [surveyjs/surveyjs#890]
### Are you requesting a feature, reporting a bug or ask a question?

Feature.

### What is the current behavior?

Checkbox and radiogroup choices cannot contain markup.

### What is the expected behavior?

The desired behavior is for surveyjs to support some markup, such as b, i, span. 

### How would you reproduce the current behavior (if this is a bug)?

Not a bug

#### Provide the test code and the tested page URL (if applicable)

N/A

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version: 64.0.3282.119
* surveyjs platform (angular or react or jquery or knockout or vue): React and Vue at least
* surveyjs version: 1.0.5

**Comment by andrewtelnov** [comment]
@reece Have you seen [this example](https://surveyjs.io/Examples/Library/?id=survey-markdown-radiogroup)?

Thank you,
Andrew

**Comment by reece** [comment]
@andrewtelnov I hadn't seen that example. That looks like the right direction.

Unfortunately, I can't make it work in the surveyjs.io online editor. For example, I have:

![selection_223](https://user-images.githubusercontent.com/109453/35651599-2b03453e-0695-11e8-86bf-b8ff777ba867.png)

The resulting json looks as expected and consistent with the example:

```
    {
     type: "checkbox",
     name: "why_tested",
     title: "Why are you requesting testing?",
     choices: [
      {
       value: "curious",
       text: "Curious"
      },
      {
       value: "rel",
       text: "Relative had *testing*"
      },
      {
       value: "doc",
       text: "Doctor"
      }
     ]
    },
```

But the resulting survey (using "Test Survey") shows literal asterisks:

![selection_224](https://user-images.githubusercontent.com/109453/35651721-8650b1d8-0695-11e8-94da-65ea0cb4d3ef.png)

Would you have expected that to show testing italicized?

**Comment by reece** [comment]
After rereading the markdown example, I see that one must include a markdown library manually. I put `<script src="https://cdnjs.cloudflare.com/ajax/libs/showdown/1.6.4/showdown.min.js"></script>` in the loading HTML section of the survey config. However, that snippet isn't used when testing a survey. So I have markdown with no renderer.

The same code works fine when tested outside the editor (with showdown).

I'm not sure whether Test Survey should honor the loading html or not. I'll close this issue now.

**Comment by reece** [comment]
P.S. And, thank you!
