### ISSUE TITLE
Bug: Ratings pre-selected on new page when using vue v1.0.5

### ISSUE THREAD

**Issue by balping** [surveyjs/surveyjs#895]
### Related bug

https://github.com/surveyjs/surveyjs/issues/620

It seems that the fix doesn't work any more.

### Current behavior

See this fiddle:

https://jsfiddle.net/zd5rvL2z/2/

I created 2 pages with 4-4 rating questions on them.

If I fill the first page and click the next button, the exact same answers are highlighted as on the previous page.

![1](https://user-images.githubusercontent.com/5840038/35654036-effe42a6-06e2-11e8-9287-9a46f598c35e.png) ![2](https://user-images.githubusercontent.com/5840038/35654037-f0168352-06e2-11e8-9816-1ba70db45100.png)

### Expected behavior

No answer in an unanswered question should be highlighted.

### Specify your

* browser:  Firefox 58
* surveyjs platform: vue (latest: v2.5.13)
* surveyjs version: latest: 1.0.5

**Comment by tsv2013** [comment]
@balping Thank you for the report. We'll fix it ASAP.

**Comment by tsv2013** [comment]
We've fixed the issue. Fix will be available in the nearest update.

**Comment by balping** [comment]
Fixed. Thanks.
