### ISSUE TITLE
Is it possible to change value in "matrixdropdown"  based on response in same row . Exp:i need to change value based on Column1,2,3  responce in "Result"

### ISSUE THREAD

**Issue by kmmamta** [surveyjs/surveyjs#896]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:
![capture1](https://user-images.githubusercontent.com/35524762/35666712-1117a04a-0751-11e8-8fc6-73bb81908e1e.PNG)

**Comment by tsv2013** [comment]
Thank you for the good suggestion. We've added the expression type to the available column types.
This feature will be available in the nearest update.
You will be able to do it vai code as well as in the SurveyJS Editor.

JSON example:
```
          {
            type: "matrixdropdown",
            name: "question1",
            columns: [
              { name: "Column 1" },
              { name: "Column 2" },
              {
                name: "Result",
                cellType: "expression",
                expression: "{row.Column 1} + {row.Column 2}"
              }
            ],
            choices: [1, 2, 3, 4, 5],
            rows: ["Row 1", "Row 2"]
          }
```

**Comment by kmmamta** [comment]
Thank You @tsv2013 ,When we can expect ?

**Comment by dmitrykurmanov** [comment]
Most likely this week
