### ISSUE TITLE
Multiple questions with same valueName loses data in onComplete handler

### ISSUE THREAD

**Issue by enricribas** [surveyjs/surveyjs#898]
### Are you requesting a feature, reporting a bug or ask a question?

bug

### What is the current behavior?

with 1.0 versions and later, data is missing from model.data in onComplete handler but not on onCurrentPageChanged handler

### What is the expected behavior?

I would expect the data to be the same in both sections, assuming I don't change any of the data.

### How would you reproduce the current behavior (if this is a bug)?

Create a question whose answer changes the visibility of another question. If the original question is duplicated with unique names say "fred1" "fred2" but the same valueName, say "ginger". I can see the value of ginger in model.data in the page change handler, as well as the data of "fred1" or "fred2" depending on the value of "ginger". However, in the onComplete handler, I do NOT get any of the values for "ginger" or either of the freds. Reverting to previous surveyjs versions with the same "name" as valueName did not exist, works in both the page handler and the complete handler. 

#### Provide the test code and the tested page URL (if applicable)

Can provide the survey data used here but it's quite large.

### Specify your

* browser: Chrome
* browser version: 64
* surveyjs platform (react ):
* surveyjs version: └─ survey-react@1.0.5

**Comment by andrewtelnov** [comment]
@enricribas I have introduced a breacking change from v1.0: https://github.com/surveyjs/surveyjs/issues/767
I believe this is the reason of the issue you have.
However, if only one question with valueName "ginger" is invisible and another one is visible, then it sounds as a bug to me. Is it what you have?

Thank you,
Andrew

**Comment by enricribas** [comment]
Yes, exactly only one of them is visible and the other is hidden with a visibleIf that depends on the "ginger" question. The conditional question ie neither "fred1" nor "fred2" does not make into the model data nor does the original question that determines which of the two is visible.

In the page transition modal data, ginger is in the model data as is one of the freds.

**Comment by andrewtelnov** [comment]
@enricribas as a workaround, you may set survey.clearInvisibleValues = "none".
We will work on the fix. 

Thank you,
Andrew

**Comment by enricribas** [comment]
excellent, will do for now, didn't know about that. That will allow us to upgrade and use other cool new features.

**Comment by andrewtelnov** [comment]
@enricribas the issue has been reproduced in the unit test and fixed.
The fix will be available in the next minor update.

Thank you,
Andrew

**Comment by enricribas** [comment]
great! thanks, will test.
