### ISSUE TITLE
How to apply customised CSS in surveyjs-react?

### ISSUE THREAD

**Issue by sfcrebecca** [surveyjs/surveyjs#900]
### Are you requesting a feature, reporting a bug or ask a question?
A question

### What is the current behavior?
In surveyjs-react, we notice that one of the CSSs is rendered at run-time. (https://github.com/surveyjs/surveyjs/blob/master/src/stylesmanager.ts)

This design causes us some problems since we need to apply our own CSS for some components. Our issue is for those items which are common in both CSSs, they are overriden by this dynamic CSS.

### What is the expected behavior?
May I know the rationale of having the dynamic CSS rendered at run-time?

And under the current design, how could we apply our CSS as the last CSS in the rendering process?

Many thanks for your assistance.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.0.4

**Comment by tsv2013** [comment]
@sfcrebecca To override any CSS style (no matter how they are declared) you should use more specific selectors. This technique is described in a lot of articles, one of them - https://css-tricks.com/specifics-on-css-specificity/
