### ISSUE TITLE
Need some ideas about issues after taking latest changes of library

### ISSUE THREAD

**Issue by kmmamta** [surveyjs/surveyjs#904]
Hi There, I have been using this library on my sample application since last 4 months, and not taken the latest changes from the Server till date, for some improvement when I took latest (i.e. 1.0.6) version, surprisingly I am seeing a lot of behavior change.

Now we are not able to use the Library as we composed to use, and need some ideas about it, Please do the needful

**Urgent**

**Comment by tsv2013** [comment]
Could you specify - what exact problems are you experiencing?

**Comment by kmmamta** [comment]
1:-We are adding some custom button in footer now we are not able to add.(PFA)
2:-We are implement some css on page now it not working. 

![footer](https://user-images.githubusercontent.com/35524762/35802952-14a554ec-0a98-11e8-90b8-7361700ca357.JPG)
![w_footer](https://user-images.githubusercontent.com/35524762/35802954-14e00c0e-0a98-11e8-9570-1551c6601ed7.PNG)
