### ISSUE TITLE
Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by xiuzhen1103** [surveyjs/surveyjs#905]
### Are you requesting a feature, reporting a bug or ask a question?

Ask a question

### What is the current behavior?

I am trying to render survey on display mode, I have similar code as this one. http://plnkr.co/edit/EDpk1P01Zw9i6RCBfAXK?p=preview, it shows message on Cannot read property 'add' of undefined. In debugger, I saw pass model and data into Survey component, but still show this error message. 
survey.react.min.js:6 Uncaught TypeError: Cannot read property 'add' of undefined

### What is the expected behavior?
Render survey in display mode.

**Comment by dmitrykurmanov** [comment]
Hello! We tested your sample with the latest version of SurveyJS (minified version) and it works ok. We need the code to reproduce your issue. We can start immediately after you provide us with it.
