### ISSUE TITLE
Maximum size

### ISSUE THREAD

**Issue by aslanbeily** [surveyjs/surveyjs#906]
Is it possible to make a survey show as big as possible on mobile browser screen?
I mean, I can play with JS/CSS, detect mobile phones and try to do this myself, but maybe something could be done with parameters? It looks really small on mobile, because it takes the entire screen width and the questions become very small and hardly seen somewhere in the corner. This is how it looks on my mobile Chrome.
![screenshot_20180206-104619](https://user-images.githubusercontent.com/6705791/35849975-0114b05a-0b2c-11e8-836f-e59d9c6bdf7c.png)

**Comment by tsv2013** [comment]
It looks like font size is too small. Ordinary on devices survey looks like on the screenshots in the https://github.com/surveyjs/surveyjs/issues/864 issue. I have no ideas why it looks so. We need a link (example code) to reproduce the issue on our side.

**Comment by aslanbeily** [comment]
I never changed the fonts, I mean I use Bootstrap according to your guide.
Here is the sample link:
http://survey.clinicrowd.xyz/survey.php?id=10&lang=en&nickname=clinicrowd
Thanks in advance!

**Comment by tsv2013** [comment]
You need to add meta viewport tag to the head of your site:
```
<meta name="viewport" content="width=device-width, initial-scale=1">
```

You can find more info in various articles like this - https://www.w3schools.com/css/css_rwd_viewport.asp

**Comment by aslanbeily** [comment]
Great, thanks!
