### ISSUE TITLE
Multiple file upload

### ISSUE THREAD

**Issue by nicklas669** [surveyjs/surveyjs#907]
Hello SurveyJS.

I have a question about your framework. Right now it seems you can only select 1 file per "upload input". Do you support uploading multiple files from the same "File Selection Dialog" or is it something that you intend to implement? And if so, when?

To clarify the wanted behaviour: I want to click one button and select multiple files for upload, instead of clicking one button and selecting one file, then doing the same x amount of times.

Kinds regards,
Nicklas

**Comment by tsv2013** [comment]
SurveyJS currently doesn't support multiple files uploading at once. We've included this feature in our task list. We'll update this thread in case of any progress.

Related issue - https://github.com/surveyjs/surveyjs/issues/793

**Comment by nicklas669** [comment]
Hey @tsv2013, thanks for the quick answer and for the work you guys are doing! Do you have any sort of idea when this will be implemented? Are we talking a couple of months or even a year?

**Comment by tsv2013** [comment]
@nicklas669 We'll make a spike solution this week. If implementation will kooks clear and fine, if we willn't face blocking issues - we'll do it. Otherwise we'll postpone it.

**Comment by nicklas669** [comment]
@tsv2013 Sounds cool, please do let me know if there are any news on this matter.

**Comment by tsv2013** [comment]
Sure, @nicklas669 we'll update this thread immediately

**Comment by tsv2013** [comment]
We've implemented this feature (basic scenario) in these commits: dac72cc11717725b02c399acf3ae3a6435d86dcc and dac72cc11717725b02c399acf3ae3a6435d86dcc
You can test it in the nearest update

You should set `allowMultiple` question property to true:
```
          {
            type: "file",
            name: "question4",
            allowMultiple: true,
            showPreview: true,
            maxSize: 0
          }
```
