### ISSUE TITLE
New feature requested - only load valid data from JSON to surveyJS data model

### ISSUE THREAD

**Issue by sfcrebecca** [surveyjs/surveyjs#909]
### Are you requesting a feature, reporting a bug or ask a question?
A feature

### What is the current behavior?
We have set some numeric fields which only accept numbers and we have a import function allows users to upload the answers from a JSON file.

If the user edits the JSON file such that a non-numeric char is set to a numeric field, that value will not be displayed on the screen (since that field only accept numbers only) but the "isRequired" checking fails. The same applies to radio group etc. where although the imported value could not be shown on the screen, that value is still passed to the surveyJS model which enable the users to bypass the "isRequired" validation.

Therefore, as seen from the screen, that "empty" numeric field could pass without value.

### What is the expected behavior?
Could we add a feature that when the answers are loaded from the JSON file, only valid data will be set to the surveyJS model and those invalid data will be removed?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.0.4

**Comment by tsv2013** [comment]
This can be easily achieved be data validating function, as shown below

```JavaScript
var json = {
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "text",
     name: "question1"
    },
    {
     type: "text",
     name: "question2",
     inputType: "number"
    },
    {
     type: "text",
     name: "question3",
     inputType: "number"
    },
    {
     type: "text",
     name: "question4",
     inputType: "number"
    }
   ]
  }
 ]
};

var data = {
	"question1": "a",
	"question2": "b",
	"question3": 1,
	"question4": "2"
}


function validateData(survey, data) {
  var validData = {};
	Object.keys(data).forEach(function(questionName) {
  	var question = survey.getQuestionByName(questionName);
    if(question.getType() === "text" && question.inputType === "number") {
    	if(typeof data[questionName] === "number") {
	    	validData[questionName] = data[questionName];
      }
    } else {
    	validData[questionName] = data[questionName];
    }
  });
  return validData;
}

var survey = new Survey.Model(json);
survey.data = validateData(survey, data);
```

Working sample is here - https://jsfiddle.net/unwb7u6o/

Does if fit your needs?

**Comment by sfcrebecca** [comment]
Thanks, this is what I want. But if I want to check other data types also, do you mean I have to implement one by one?

**Comment by tsv2013** [comment]
@sfcrebecca You are absolutely right

**Comment by sfcrebecca** [comment]
Thanks, we have done that.
