### ISSUE TITLE
defaultValue doesn't work for questions in PanelDynamic

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#910]
The following JSON doesn't work correctly. Questions in panel doesn't have defaultValues

```
{
    elements: [
      {
        type: "paneldynamic",
        name: "question1",
        templateElements: [
          {
            type: "text",
            name: "question2",
            defaultValue: "100"
          },
          {
            type: "dropdown",
            name: "question3",
            defaultValue: "item2",
            choices: ["item1", "item2", "item3"]
          }
        ]
      }
    ]
  }
```

**Comment by andrewtelnov** [comment]
It doesn't work in knockout and jQuery-

**Comment by pelshen** [comment]
Should the fix work in React?

Using this JSON in the React component

```
{
 "pages": [
  {
   "name": "Test page",
   "elements": [
    {
     "type": "dropdown",
     "name": "test1",
     "defaultValue": "test1Option1",
     "isRequired": true,
     "choices": [
      {
       "value": "test1Option1",
       "text": "Option 1"
      },
      {
       "value": "test2Option2",
       "text": "Option 2"
      }
     ]
    },
    {
     "type": "paneldynamic",
     "name": "panel1",
     "title": "Panel 1",
     "templateElements": [
      {
       "type": "dropdown",
       "name": "test2",
       "defaultValue": "test2Option1",
       "isRequired": true,
       "choices": [
        {
         "value": "test2Option1",
         "text": "Option 1"
        },
        {
         "value": "test2Option2",
         "text": "Option 2"
        }
       ]
      },
      {
       "type": "paneldynamic",
       "name": "innerPanel1",
       "title": "Inner Panel 1",
       "templateElements": [
        {
         "type": "text",
         "name": "testText1",
         "title": "Text 1"
        }
       ],
       "panelCount": 1,
       "panelAddText": "Add Inner Panel",
       "panelRemoveText": "X"
      }
     ],
     "panelCount": 1,
     "panelAddText": "Add Outer Panel",
     "panelRemoveText": "X"
    }
   ]
  }
 ],
 "showQuestionNumbers": "off",
 "completeText": "Submit"
}
```

I end up with
![image](https://user-images.githubusercontent.com/1704114/145206468-a24b15ec-f4ba-4b52-a9a4-cfbe2af3a97c.png)

But in the Survey Designer with the same JSON I get
![image](https://user-images.githubusercontent.com/1704114/145206560-04b8ae07-fead-446c-a616-505ed0c13825.png)

Note that the styling of question titles is also messed up, which is triggered by adding panelCount (as that is a separate issue, happy to open a new issue for it).

**Comment by andrewtelnov** [comment]
@pelshen The fix was done on the model level. survey-react renders the survey model. It works for me. Here is [the example](https://plnkr.co/edit/CYBAnZf9xKE3T8dt).
Probably, you did not update your survey library, react version.

PS: We have [SurveyJS Creator V2 for react](https://surveyjs.io/Documentation/Survey-Creator?id=Creator-V2-Whats-New#react-version). It is in beta, but we beleive it is better than V1.

Thank you,
Andrew

**Comment by pelshen** [comment]
Hmm, so strange. I'm using npm for dependencies and I was pulling in survey-react 1.9.0 and just upped it to 1.9.1 but still seeing the same thing. This is a relatively new project so it was never using an old version (think it was on latest 1.8.x originally). Debugging in Chrome, it looks like I have ts files that have the above changes (and more on top). I'm not sure where else to look, I don't get what else I'm doing differently from you plunker.

**Comment by andrewtelnov** [comment]
@pelshen I am not sure I can help you here. I have just created an [example in Code Sandbox](https://codesandbox.io/s/adoring-lumiere-b42h9?file=/src/SurveyComponent.jsx). It works in module application correctly as well.

Thank you,
Andrew

**Comment by pelshen** [comment]
@andrewtelnov thanks for your help, clearly something my end on the defaultValue, I will investigate further. However, both your examples show the other issue when you add a panelCount to a nested dynamic panel. I've raised this in a separate issue though #3719

**Comment by pelshen** [comment]
Sorry, @andrewtelnov just wondered if you can point me where the react code actually sets the selected dropdown option? I have debugged my code and I can see that the defaultValue is being correctly set in the question model as the value, but the actual rendered select still doesn't show the value.
I can see here https://github.com/surveyjs/survey-library/blob/eff2dd55401485415592cf20d9e1c9c050b1586c/src/react/reactquestion_dropdown.tsx#L62 is where the select and options are rendered but I can't find where "selected" is being set (if that is what is happening) but want to debug that to see why it's not being set correctly.

Thanks for your help

**Comment by andrewtelnov** [comment]
@pelshen We should set it here:
https://github.com/surveyjs/survey-library/blob/eff2dd55401485415592cf20d9e1c9c050b1586c/src/react/reactquestion_dropdown.tsx#L96
However, we do not set it and it works based on select value, I guess.

Thank you,
Andrew

**Comment by pelshen** [comment]
Thanks, I tracked it down - I was accidentally re-setting the survey data after creation. Now that I've found it, it's obvious 🤦‍♂️

**Comment by andrewtelnov** [comment]
@pelshen Great!

Thank you,
Andrew
