### ISSUE TITLE
Display mode have specified question to be editable

### ISSUE THREAD

**Issue by xiuzhen1103** [surveyjs/surveyjs#911]
### Are you requesting a feature, reporting a bug or ask a question?

Ask a question

### What is the current behavior?
when in display mode, all fields are not editable. 

### What is the expected behavior?
when in display mode, if type="comment", in display mode should be textarea, not html text

### How would you reproduce the current behavior (if this is a bug)?
http://plnkr.co/edit/EDpk1P01Zw9i6RCBfAXK?p=preview

in plunker, would you able to make this question to be editable 
What would make you more satisfied with the Product?

**Comment by tsv2013** [comment]
Instead of 
```
survey.mode = "display";
```
you can use `readOnly` option of each question:
```
survey.getAllQuestions().forEach(function(q) {
  q.readOnly = q.name !== "Quality";
});
```

You can check the updated plunk - http://plnkr.co/edit/kl0jW8L4cGH8Lb5bJOjB?p=preview
