### ISSUE TITLE
Survey is exceeding its container on modal

### ISSUE THREAD

**Issue by healkar01** [surveyjs/surveyjs#912]
I have a survey in a modal dialog:

![startsurvey](https://user-images.githubusercontent.com/20865786/35993758-4cc1fb28-0cdc-11e8-9744-e66ab054372a.jpg)

When I complete it, the modal unhides the footer to show the close button but the thank you is exceeding its container on the modal and not behaving appropriately so you cannot see the close button (or rather, you can see the edge of it)

![completesurvey](https://user-images.githubusercontent.com/20865786/35993757-4cb08ce4-0cdc-11e8-988c-d47e8c4f3007.jpg)

My modal code is below:

`<div id="takeSurveyActive">
  <div class="modal-header">
    <h5 *ngIf="IsPreview == 1" class="modal-title" id="previewSurveyLabel">Preview Survey</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close" (click)="activeModal.close('Cancelled');" >
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="modal-body scrollable-area">
      <survey-viewer *ngIf="SurveyId > 0" [AgencyId]="AgencyId"
                     [SurveyId]="SurveyId" [IsPreview]="IsPreview" [SurveyResponseId]="0" (surveyCompleted)="completedSurvey($event)"></survey-viewer>
      <survey-viewer *ngIf="SurveyResponseId > 0" [AgencyId]="AgencyId"
                     [IsPreview]="IsPreview" [SurveyResponseId]="SurveyResponseId"></survey-viewer>
    </div>
  </div>
  <div class="modal-footer" *ngIf="IsPreview == 1 || showCloseButton == true" >
    <button type="button" class="btn btn-primary" (click)="closeModal();">Close</button>
  </div>
</div>
`

FYI, survey-viewer html is this (from your example)

`<div class="survey-container contentcontainer codecontainer">
  <div id="surveyElement"></div>
</div>
`

The modal-footer is where the close button is, and as you can see, it is not visible.

Thank you,

Karen Healey

**Comment by tsv2013** [comment]
Thank you for the report, @healkar01 
I think we've fixed this issue via the https://github.com/surveyjs/surveyjs/commit/1c15d551544d80c4d28f60996397a596a916303b commit.
We've also disabled default paddings in the https://github.com/surveyjs/surveyjs/commit/4874e040e9cb644a4ea90d165b9a0471344df59d commit.
Hope this also solves this issue.
These fixes will be available in the nearest update.

**Comment by healkar01** [comment]
Thank you!  It solved the problem!

Karen Healey
