### ISSUE TITLE
Fields with upper case letters no longer get interpolated into title 

### ISSUE THREAD

**Issue by enricribas** [surveyjs/surveyjs#913]
### Are you requesting a feature, reporting a bug or ask a question?

bug

### What is the current behavior?

How old is {spouseName}? used to inject the actual spouseName into the title. 

### What is the expected behavior?

It should inject the name of the spouse entered in a previous question

### How would you reproduce the current behavior (if this is a bug)?

create a question that uses a dynamic field and use an uppercase character in the name of the field.

**Comment by enricribas** [comment]
Here is the survey test case 

```
{
 "title": "Survey Example",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "emailAddress",
     "title": "uses uppercase"
    },
    {
     "type": "text",
     "name": "email_address",
     "title": "uses snake_case"
    }
   ]
  },
  {
   "name": "page2",
   "elements": [
    {
     "type": "text",
     "name": "question1",
     "title": "snake case {email_address} is"
    },
    {
     "type": "text",
     "name": "question2",
     "title": "upper case  {emailAddress} is"
    }
   ]
  }
 ],
 "showProgressBar": "top"
}
```

**Comment by enricribas** [comment]
This is a big problem for us, as we use camelCase for all our "names", and this is blocking us from release. 
Pretty please, urgent. :)

**Comment by andrewtelnov** [comment]
@enricribas The issue is reproduced in a unit test and fixed.
The fix will be available in the next minor update, hopefully we will release it today.

Thank you,
Andrew

**Comment by enricribas** [comment]
awesome, thanks.
