### ISSUE TITLE
Hide a question title for any question.

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#914]
Add "hidden" value into question.titleLocation.

**Comment by masciugo** [comment]
any way to hide column title in matrix? thank you

**Comment by andrewtelnov** [comment]
@masciugo We do not have this functionality yet. Do you want to have an empty header?
Could you share with us  a picture of layout you are trying to achieve?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@masciugo So, You need to hide the table header completely.
Got it.

**Comment by andrewtelnov** [comment]
@masciugo I have created a [new issue](https://github.com/surveyjs/surveyjs/issues/1026)

**Comment by andrewtelnov** [comment]
@masciugo It has been implemented: https://github.com/surveyjs/surveyjs/issues/1026
It will be available from the next minor update.

Thank you,
Andrew
