### ISSUE TITLE
Visible if with nested surveys has unexpected results

### ISSUE THREAD

**Issue by healkar01** [surveyjs/surveyjs#915]
Hello,

I have a survey that uses visible if and is not quite behaving the way we would like it to behave.  The json is below.  Question 2 is a Yes/No question.  Question 3 displays if Question 2 is yes.  Question 4 displays if Question 2 is No.  So, the user answers No to Question 2 and sees Question 4.  They answer 'Not eligible' to Question 4, which makes Question 5 appear.  Answer 'Accessed maximum number of services' to Question 5.

Then then go BACK and change Question 2 to Yes.  Now they see Question 3, but not Question 4.  Unfortunately, they still see Question 5 and Question 6 because there are answers for 4 and 5 that are making them appear, even though 4 is no longer showing.  

I understand WHY this is happening (because Question 4 has the expected answer as does Question 5), but, in my opinion, Question 5 should only show if Question 4 has the answer that is expected AND is visible itself.  And if Question 6 should only show if 5 is showing.

I think it would be very cumbersome for someone to attempt to design the survey to make Question 5 rely on No for Question 2 and 'Not eligible' to Question 4.  Then, they would have to make question 6 dependent on questions 5, 4, and 2.  You can see how this would become very complicated the deeper the survey goes. 

Can you help me resolve this issue?

`{
	"title": "Survey for Program Emergency Assistance, Service Unserved",
	"pages": [
		{
			"name": "Page 1",
			"elements": [
				{
					"type": "dropdown",
					"name": "Question1",
					"title": "What service(s) was/were requested?",
					"inputType": null,
					"isRequired": false,
					"visible": true,
					"visibleIf": null,
					"hasOther": false,
					"nodeId": 0,
					"choices": [
						{
							"value": "Application Prepared",
							"text": "Application Prepared"
						},
						{
							"value": "Certificate Assistance",
							"text": "Certificate Assistance"
						},
						{
							"value": "Clothing",
							"text": "Clothing"
						},
						{
							"value": "Health",
							"text": "Health"
						},
						{
							"value": "Material Goods",
							"text": "Material Goods"
						},
						{
							"value": "Rent/Mortgage",
							"text": "Rent/Mortgage"
						},
						{
							"value": "Temporary Shelter",
							"text": "Temporary Shelter"
						},
						{
							"value": "Transportation",
							"text": "Transportation"
						},
						{
							"value": "Utility",
							"text": "Utility"
						}
					]
				},
				{
					"type": "dropdown",
					"name": "Question2",
					"title": "Did the customer receive another service?",
					"inputType": null,
					"isRequired": false,
					"visible": true,
					"visibleIf": null,
					"hasOther": false,
					"nodeId": 0,
					"choices": [
						{
							"value": "Yes",
							"text": "Yes"
						},
						{
							"value": "No",
							"text": "No"
						}
					]
				},
				{
					"type": "dropdown",
					"name": "Question3",
					"title": "Which service(s)?",
					"inputType": null,
					"isRequired": false,
					"visible": false,
					"visibleIf": "{Question2} = 'Yes'",
					"hasOther": false,
					"nodeId": 0,
					"choices": [
						{
							"value": "Application prepared",
							"text": "Application prepared"
						},
						{
							"value": "Certificate",
							"text": "Certificate"
						},
						{
							"value": "Clothing",
							"text": "Clothing"
						},
						{
							"value": "Health",
							"text": "Health"
						},
						{
							"value": "Material Goods",
							"text": "Material Goods"
						},
						{
							"value": "Rent/Mortgage",
							"text": "Rent/Mortgage"
						},
						{
							"value": "Temporary Shelter",
							"text": "Temporary Shelter"
						},
						{
							"value": "Transportation",
							"text": "Transportation"
						},
						{
							"value": "Utility",
							"text": "Utility"
						},
						{
							"value": "Nutrition",
							"text": "Nutrition"
						}
					]
				},
				{
					"type": "dropdown",
					"name": "Question4",
					"title": "Why?",
					"inputType": null,
					"isRequired": false,
					"visible": false,
					"visibleIf": "{Question2} = 'No'",
					"hasOther": false,
					"nodeId": 0,
					"choices": [
						{
							"value": "Not eligible",
							"text": "Not eligible"
						},
						{
							"value": "Resources not available",
							"text": "Resources not available"
						},
						{
							"value": "After consultation customer decided to withdraw request",
							"text": "After consultation customer decided to withdraw request"
						}
					]
				},
				{
					"type": "dropdown",
					"name": "Question5",
					"title": "Why?",
					"inputType": null,
					"isRequired": false,
					"visible": false,
					"visibleIf": "{Question4} = 'Not eligible'",
					"hasOther": false,
					"nodeId": 0,
					"choices": [
						{
							"value": "Over income",
							"text": "Over income"
						},
						{
							"value": "Accessed maximum number of services",
							"text": "Accessed maximum number of services"
						},
						{
							"value": "Did not provide requested information/documentation",
							"text": "Did not provide requested information/documentation"
						},
						{
							"value": "NRCA is not serving customer",
							"text": "NRCA is not serving customer"
						}
					]
				},
				{
					"type": "text",
					"name": "Question6",
					"title": "When will they be eligible for services again?",
					"inputType": "datetime",
					"isRequired": false,
					"visible": false,
					"visibleIf": "{Question5} = 'Accessed maximum number of services'",
					"hasOther": false,
					"nodeId": 0,
					"choices": null
				},
				{
					"type": "dropdown",
					"name": "Question7",
					"title": "Why?",
					"inputType": null,
					"isRequired": false,
					"visible": false,
					"visibleIf": "{Question4} = 'Resources not available'",
					"hasOther": false,
					"nodeId": 0,
					"choices": [
						{
							"value": "NRCA lacks resources to aid",
							"text": "NRCA lacks resources to aid"
						},
						{
							"value": "Request exceeds community resources",
							"text": "Request exceeds community resources"
						}
					]
				}
			]
		}
	]
}`

Thank you,

Karen Healey

**Comment by andrewtelnov** [comment]
@healkar01 For Question5 you should use the following expression to make it work:

```
     type: "dropdown",
     name: "Question5",
     visible: false,
     visibleIf: "{Question2} = 'No' and {Question4} = 'Not eligible'",

```
If you have several questions that has to be visible on {Question2} = 'No' and hidden otherwise, you may use a Panel with visibleIf = "{Question2} = 'No'", and put those questions into the Panel. 

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@healkar01 Forgot to say, there is one more solution. Set survey.clearInvisibleValues to "onHidden"
`clearInvisibleValues: "onHidden"`
On hidding Question2 it's value will be clear, it will not equal 'No' any more and Question4 will be hidden as well and it's value will be cleared and as result Question5 will be hidden also.

Thank you,
Andrew

**Comment by healkar01** [comment]
Thank you!  The clearInvisibleValues is preferable!  We actually brought in hundreds of surveys from another system and identifying the ones that have this issue could be a huge problem.  But this solves it perfectly!
