### ISSUE TITLE
Hide rows in matrix

### ISSUE THREAD

**Issue by aslanbeily** [surveyjs/surveyjs#918]
Hello,
Is it possible to hide the rest of the rows in matrix if the answer to the first row was negative or positive or something else - doesnt' matter, just some kind of ifVisible on rows level?
Thanks in advance.

**Comment by tsv2013** [comment]
Unfortunately SurveyJS hasn't such a functionality. But you can do it via code. Similar scenario was discussed in this thread - [Dynamic forms (multiple items)](https://github.com/surveyjs/surveyjs/issues/186).
We can create an example for you if you describe your scenario in greater details.

**Comment by aslanbeily** [comment]
http://survey.clinicrowd.xyz/survey1.php?id=10&lang=en&nickname=clinicrowd is a good sample.
On the seventh page, in a matrix question about Tremor (by the way, page numbers are not shown for some reason, despite "showPageNumbers": true) if one chooses "Full body" not empty and not never, the rest of options should be hidden somehow. I thought I can just hide the table rows or the questions themselves using JS, but there is no way to address them (only by count, but this is not reliable - the number of options changes somtimes) and it turned out to be impossible.

**Comment by andrewtelnov** [comment]
@aslanbeily We have implemented this functionality. Here is [the example](https://surveyjs.io/Examples/Library/?id=condition-matrixDropdownVisibleIf)

Thank you,
Andrew

**Comment by aslanbeily** [comment]
@andrewtelnov , perfect, thanks a lot!
