### ISSUE TITLE
Create questions don't belong Question List?

### ISSUE THREAD

**Issue by quangnd** [surveyjs/surveyjs#92]
First, thanks for your work! I'm finding out your survey.

Currently, I want to create some general questions like: What's your name? How old are you?...before enter to Survey Questions. However, questions're always begin from one, this makes confused.

Let me know if there is a way to resolve this problem.

Thanks!

**Comment by andrewtelnov** [comment]
@quangnd As I understand, you want to be able to have the question visible, but do not want them to be count, am I right?
Do you want to have this values to be stored in the survey result?
The current solution: Create a simple form with two inputs (name and age) and one button: start survey. You may start/show survey after a user enter the data and click on the button: "Start Survey".
A perfect solution - have a survey staring page. We do not have it right now.

**Comment by quangnd** [comment]
Thanks for fast reply @andrewtelnov !

Actually, I'm using your **dxsurvey** and I forgot to mention about this in my question. As I understand, your service don't support this at the moment. 

That's ok! I just want to know. Thanks again!

**Comment by andrewtelnov** [comment]
@quangnd  Yes, it makes sense. I have added: https://github.com/andrewtelnov/surveyjs/issues/93
Unfortunately, I could not make any estimates for this feature. Definitely, we will keep it in mind.

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
please go to  #93
