### ISSUE TITLE
Make it possible to have  multiple options correct/ more than one options correct in Quiz 

### ISSUE THREAD

**Issue by omkardusane** [surveyjs/surveyjs#920]
##Feature Request

## Quiz

quiz demo provided: https://surveyjs.io/Examples/Library/?id=survey-quiz
#
when I put a checkbox instead of radio group, I can achieve a combination of multiple options as correct. but the chosen answers arryay compare to the CorrectAnswer array (which used to be a string in single option correct type) and if the user doesn't select the answers in right order then it cannot conclude the answer to be correct.

### Expected Behavior:

Multiple Choice Correct Should be
```
{
    "type": "checkbox",
    "name": "There are  _______ and _________ hormones in human body",
    "correctAnswer": [
        "A",
        "C"
    ],
    "choices": [
        "A",
        "B",
        "C"
    ]
},
```
    
| Case                             | Behaviour     | 
| -------------                    |:-------------:| 
| if user selects A and then C     | Correct Answer | 
| if user selects C and then A     | Correct Answer | 
| if user selects any other combination in any other order      | Wrong Answer | 

Requesting array check and

More than one Choice Correct Should be
```
{
    "type": "radiogroup",
    "name": "There is _______ hormone in human body",
    "correctAnswer": [
        "A",
        "C"
    ],
    "choices": [
        "A",
        "B",
        "C"
    ]
},
```
    
| Case                             | Behaviour     | 
| -------------                    |:-------------:| 
| if user selects A      | Correct Answer | 
| if user selects C      | Correct Answer | 
| if user selects any other option in any other order      | Wrong Answer |

**Comment by andrewtelnov** [comment]
@omkardusane The only solution, I see, is to add onIsQuestionCorrect event, where you will be able to override the default behavior.
Additionally, instead of checkbox, I would suggest to use the [SortableJS custom widget](https://surveyjs.io/Examples/Library/?id=custom-widget-sortablejs)
Let me know, if event works for you.

Thank you,
Andrew

**Comment by omkardusane** [comment]
Oh Thanks for the prompt response @andrewtelnov ,
The custom widget is not a good option for our use case as we are agnostic to the order of answers, and we are avoiding new dependencies. 

We would prefer having a property in the question object named 'correctAnswerType' specifying if it is a 'SingleOption' , 'MultipleOption' or 'MoreThanOneOption'. which we believe is a very general requirement of a quiz module. 

Let me know if that is aligned with roadmap of SurveyJS and if you don't mind I would like to contribute and implement this into surveyjs.

**Comment by andrewtelnov** [comment]
@omkardusane It will be hard to explain what exactly this property does. It is very specific.
I will add the event onIsQuestionCorrect  and you may add this property by yourself. Here is the example:
https://surveyjs.io/Examples/Builder/?id=addproperties#content-js
https://surveyjs.io/Examples/Builder/?id=addproperties#content-docs
On this event, based on the value property you will be able to return if the answer correct or not.
This solution will solve your issue and keep our library flexible and robust.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@omkardusane I have added the event. 
Please look at the commit above. You will see a new Unit Test: 
"Quiz, correct, incorrect answers and onIsAnswerCorrect event". Here you will find the example of using survey.onIsAnswerCorrect event.

Thank you,
Andrew
SurveyJS Team

**Comment by omkardusane** [comment]
Hi @andrewtelnov 
The event helps in our use case. We really appriciate the robustness and flexibility of surveyjs. Thanks for the support and guidance. 

Thanks  👍
