### ISSUE TITLE
Request: ability to increase size of bubbles

### ISSUE THREAD

**Issue by alzulas** [surveyjs/surveyjs#921]
### Are you requesting a feature, reporting a bug or ask a question?
Feature

### What is the current behavior?
Clients continue to complain that they feel the bubble are too small for radio buttons and matrix buttons. 

### What is the expected behavior?
Would be useful if radio buttons/matrix/check boxes/etc could have a size element. That way the check boxes/bubbles could be set to large in the code. 

### How would you reproduce the current behavior (if this is a bug)?
NA

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Safari/Chrome/Firefox
* browser version: All up to date
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.7

**Comment by andrewtelnov** [comment]
@alzulas This is a library ;) Here is the example with !important attribute. A little dirty, but it works: https://plnkr.co/edit/2Agug0prsUtECbZlgZnj?p=preview

Thank you,
Andrew

**Comment by alzulas** [comment]
This fix only worked for firefox. 

.sv_qcbc input[type="radio"] {
    -ms-transform: scale(1.5) !important; /* IE 9 */
    -webkit-transform: scale(1.5) !important; /* Chrome, Opera */
    transform: scale(1.5) !important;
    margin: 5px !important;
}

Worked for everything but Safari. I'm still a little stuck, but it's better than nothing I suppose.
