### ISSUE TITLE
docs index

### ISSUE THREAD

**Issue by masciugo** [surveyjs/surveyjs#923]
### Are you requesting a feature, reporting a bug or ask a question?

question

### What is the current behavior?

I cannot find all docs pieces

### What is the expected behavior?

a good index for docs

### How would you reproduce the current behavior (if this is a bug)?

I could get to this [doc](https://surveyjs.io/Documentation/LibraryParameter?id=questionbase&parameter=visibleif) only because I bumped into [this](https://github.com/surveyjs/surveyjs/issues/177)

The only way at moment to find some docs is to hack url like https://surveyjs.io/Documentation/LibraryParameter?id=questionbase&parameter=visibleif replacing  property or class name. Correct?

**Comment by andrewtelnov** [comment]
@masciugo We have added several additional examples: 
https://surveyjs.io/Examples/Library/?id=condition-cascade
https://surveyjs.io/Examples/Library/?id=condition-complexquestions
https://surveyjs.io/Examples/Library/?id=condition-dynamic

We may update the documents about visibleIf as well. Are you asking about this?

PS: Could you please try our new expression editor. You can try it at: https://surveyjs.io/Survey/Builder/. We have released it yesterday and we would love to get a feedback.

Thank you,
Andrew

**Comment by masciugo** [comment]
@andrewtelnov thank you for your support but the visibleIf case was only an example to show that it seems there are some doc pages not reachable browsing the [official doc page](https://surveyjs.io/Documentation/Library/). I wonder if there are some other _hidden_ docs or I missed something about docs organisation

At first glance we really love the new expression editor. By the way its autocomplete suggestion feature compensate docs needs someway. We'll use it in the near feature and let you know for any problems

**Comment by cinziasala** [comment]
@masciugo Please see show more link [here](https://surveyjs.io/Documentation/Library?id=QuestionBase#visibleIf)

**Comment by masciugo** [comment]
@cinziasala thank you. Fair enough
@andrewtelnov We started using the expression editor and my not developer colleagues would need to read the whole operators descriptions which is cut in the dropdown.

![screen_shot_2018-02-15_at_17_03_12](https://user-images.githubusercontent.com/454321/36267019-380da104-1273-11e8-964d-79430e851e6e.png)

**Comment by andrewtelnov** [comment]
@tsv2013 @dmitrykurmanov Could you please look at this issue. 

Thank you,
Andrew

**Comment by tsv2013** [comment]
We've added tooltip for autocomplete items via the https://github.com/surveyjs/editor/commit/7ce7006cf56a2f746da33ae1fba88c89769fc74a commit
I think it will be the solution
Fix will be available in the nearest update

**Comment by tsv2013** [comment]
![image](https://user-images.githubusercontent.com/3013415/36387915-53d4a85c-15ab-11e8-8b73-a11e77628c15.png)
