### ISSUE TITLE
Questions are numbered wrong if conditionally hidden (Single page mode)

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/surveyjs#925]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
Questions are numbered 1,2,3,4,5, 7,8,9,...

### What is the expected behavior?
Questions are numbered 1,2,3,4,5, **6,** 7,8,9,...

### How would you reproduce the current behavior (if this is a bug)?
See sample from #922

**Comment by andrewtelnov** [comment]
Had to re-write the updating question.visibleIndex completely. However, it works better now.
