### ISSUE TITLE
Please supply a :key to all v-for in Vue components

### ISSUE THREAD

**Issue by kaphert** [surveyjs/surveyjs#932]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

Related to https://github.com/surveyjs/surveyjs/issues/930

`v-for` for VueJS does not requires a `:key` attribute but without it is has strange behavior when the dom is changed or reordered. See https://vuejs.org/v2/guide/list.html#key

> It is recommended to provide a key with v-for whenever possible, unless the iterated DOM content is simple, or you are intentionally relying on the default behavior for performance gains.

Take example: https://plnkr.co/edit/GCKFIVh3PtVV3st99nKo?p=preview.
A custom widget is used here inside a dynamic panel. The widget it self is pretty stupid, it just creates a dropdown with 4 values. But it has some strange behavior:

1. Press 2 times on 'Add New'. We now have 3 panels, for simplicity we call them A, B and C.
2. Select a value for panel B (second)
3. Remove panel B
4. Notice that panel C now shows the value that we had selected on panel B? 
5. Now press on 'Complete'. Notice that it showing a 'please answer the question' error because he doesnt have a value. 

All this behavior in combination with #930 smells like the 'v-for behavior without a :key parameter`. 

Just confirmed that the same setup with jQuery does not result in this behavior: https://plnkr.co/edit/nKeYYsv9AvTlP0Qej3Kr?p=preview

**Comment by tsv2013** [comment]
It's very strange that vue doesn't complain the "key" is mandatory in fact.

**Comment by tsv2013** [comment]
I've added `:key` attribute, but this doesn't help with #930

**Comment by kaphert** [comment]
@tsv2013 thanks but the `:key` values are not unique keys because the `inputId` property is undefined. If I fix this locally it solves the issue of #930 & the issue I described above. If there is a unique id for the element that you are looping at the moment that will be enough. So just passing `question.id`, `page.id`, `panel.id` to the `:key` will be enough. 

A row does not have a unique id so a combination of the page id or panel id and the row index would be good: `:key="page.id +'_'+ index". 

For all the checkbox, option, and radiobuttons the key could be equal to the value of the `item`. I think you can even leave out the :key here but better safe than sorry.

**Comment by kaphert** [comment]
@tsv2013 do you want me to make a pull request to change the `:key` values to unique values?

**Comment by dmitrykurmanov** [comment]
No problem. Sure.

**Comment by dmitrykurmanov** [comment]
We've checked issues with dynamic panel after your pull request merged. It works ok now. Thank you for the contributing.
