### ISSUE TITLE
default value for matrixdropdown choices

### ISSUE THREAD

**Issue by cinziasala** [surveyjs/surveyjs#933]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

Cannot set default choice

### What is the expected behavior?

 I would like to set the default choice or at least the default value like in [this example](https://plnkr.co/edit/nOTMp4QGjuBBBpbv7cZ2?p=preview)

**Comment by andrewtelnov** [comment]
@cinziasala This json should work. I will fix it.
As a workaround, please use the following code: https://plnkr.co/edit/OYDOVpBLYqQ5HpzJ8hNG?p=preview

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@cinziasala Man, I have spent 20 minutes, trying to understand why my UnitTest doesn't work correctly, based on your JSON. There is a typo. You have "defaulValue" instead of "defaultValue".
Here is the [fork with type fix](https://plnkr.co/edit/U1T1Or7lx4QJRMaHZ3MJ?p=preview)

Thank you,
Andrew

**Comment by cinziasala** [comment]
I deeply apologise, it works correctly.
  
Thank you so much,
Cinzia
