### ISSUE TITLE
[Bug] onAfterRenderPage is only fired once in multi page survey (Vue)

### ISSUE THREAD

**Issue by kaphert** [surveyjs/surveyjs#934]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
For the vue variant the `onAfterRenderPage` is only fired on the first page. It is not fired when you go to step 2, 3 or 4. And also not when you go back form step 2 to 1 while this is the case in the jQuery variant. 

### What is the expected behavior?
`onAfterRenderQuestion` should be fired each time the page is rendered. 

This is a little bit related to #930. The issue is that the `survey-page` component is only rendered once. A solution to get it working is turning the `survey-page` in `survey.vue` into the following:

```
<survey-page v-for="page in survey.pages" :key="page.id" v-if="page.id == survey.currentPage.id" :id="page.id" :survey="survey" :page="page" :css="css" />
```

This way the `survey-page` component is rendered each time the currentpage is changed. I am not sure if this would be the preferred solution. Maybe something could be achieved with a watcher on the `:page` property and a rerender of the component. 

### Specify your

* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version: v1.0.9

**Comment by tsv2013** [comment]
It was discussed here - `onAfterRenderPage` fires only once #664

**Comment by kaphert** [comment]
Ok I understand. I was expecting that all of the js frameworks are acting the same way. For example the JQuery variant will fire on each page visit the onAfterRenderPage event while the Vue version won't this makes it confusing when examples are used. In my opinion it would be better if all of the events would fire on the same time in every framework.

**Comment by tsv2013** [comment]
I see your point. We'll discuss this with the team.

**Comment by tsv2013** [comment]
If we fix it, it will be a breaking change in my opinion. @dmitrykurmanov @andrewtelnov we need to discuss it.

**Comment by tsv2013** [comment]
After discussin I've added corresponding event call
