### ISSUE TITLE
Skip to page functionality?

### ISSUE THREAD

**Issue by daveed80** [surveyjs/surveyjs#935]
### Are you requesting a feature, reporting a bug or ask a question?

Asking a question.

First, this is an unbelievable awesome solution! What I would like to do is if a given question is answered with a particular value, skip to a different page/set of questions (branching logic). From the documentation, I feel that this is possible, I'm just unsure how to get there.

### What is the current behavior?

Not skipping to 'page3' when 'No' is selected for 'frameworkUsing'

### What is the expected behavior?

When 'frameworkUsing' is set to 'No', display/skip to 'page3'

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

  triggers: [{
                type: "visible",
                name: "frameworkUsing",
                operator: "equal",
                value: "No",
                pages: ["page3"]
            }],
            pages: [
      {
          name: "page1", questions: [
            { type: "radiogroup", choices: ["Yes", "No"], isRequired: true, name: "frameworkUsing", title: "Do you use any front-end framework like Bootstrap?" },
            { type: "checkbox", choices: ["Bootstrap", "Foundation"], hasOther: true, isRequired: true, name: "framework", title: "What front-end framework do you use?", visibleIf: "{frameworkUsing} = 'Yes'" }          
          ]
      },
      {
          name: "page2", questions: [
          { type: "radiogroup", choices: ["Yes", "No"], isRequired: true, name: "mvvmUsing", title: "Do you use any MVVM framework?" },
          { type: "checkbox", choices: ["AngularJS", "KnockoutJS", "React"], hasOther: true, isRequired: true, name: "mvvm", title: "What MVVM framework do you use?", visibleIf: "{mvvmUsing} = 'Yes'" }]
      },
      {
          name: "page3", questions: [
              {
                  type: "comment", name: "about", visible:false, title: "Please tell us about your main requirements for Survey library"
              }]
      }]
        };

### Specify your

* browser: chrome
* browser version: Version 64.0.3282.167
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.8

**Comment by andrewtelnov** [comment]
@daveed80 You add to page2
`visibleIf: "{frameworkUsing} <> 'No'"`
It means that page2 will be shown if "frameworkUsing" question value doesn't equal to 'No'

Thank you,
Andrew

**Comment by daveed80** [comment]
Gotcha, makes sense. With that said, I'm curious what the preferred approach would be if multiple questions/steps can result in 'skipping' all the way to the end?

**Comment by daveed80** [comment]
After making the suggested change (**visibleIf: "{frameworkUsing} <> 'No'"**), it does change the button to '**Complete**', which is skipping page 2. However, the question title does not change, and remains as: 

**'1. * Do you use any front-end framework like Bootstrap?**

 pages: [
      {
          name: "page1", questions: [
            { type: "radiogroup", choices: ["Yes", "No"], isRequired: true, name: "frameworkUsing", title: "Do you use any front-end framework like Bootstrap?" },
            { type: "checkbox", choices: ["Bootstrap", "Foundation"], hasOther: true, isRequired: true, name: "framework", title: "What front-end framework do you use?", visibleIf: "{frameworkUsing} = 'Yes'" }
          ]
      },
      {
          name: "page2",  visibleIf: "{frameworkUsing} <> 'No'", questions: [
          { type: "radiogroup", choices: ["Yes", "No"], isRequired: true, name: "mvvmUsing", title: "Do you use any MVVM framework?" },
          { type: "checkbox", choices: ["AngularJS", "KnockoutJS", "React"], hasOther: true, isRequired: true, name: "mvvm", title: "What MVVM framework do you use?", visibleIf: "{mvvmUsing} = 'Yes'" }]
      },
      {
          name: "page3", questions: [
              {
                  type: "comment", name: "about", visible: false, title: "Please tell us about your main requirements for Survey library"
              }]
      }]
        };

**Comment by daveed80** [comment]
Not sure what I did in code, but after using the awesome survey builder, all was good.

Thanks again for an awesome product and quick response!

**Comment by andrewtelnov** [comment]
@daveed80 You are welcome!
