### ISSUE TITLE
The default value for Boolean Element not working

### ISSUE THREAD

**Issue by bidos** [surveyjs/surveyjs#938]
### What is the current behavior?
You can check directly the link of your example on your site( i joined the link in the description)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://surveyjs.io/Examples/Library/?id=questiontype-boolean&platform=jQuery&theme=default
Test code

```
your_code_here

```

### Specify your

* browser: Tested on diffèrent browsers
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version: 1.0.8

**Comment by tsv2013** [comment]
Thank you for the report. We'll fix it.

**Comment by tsv2013** [comment]
It was a bug in the code of the boolean question demo on our site. I've fixed it and updated the site. Please check.
