### ISSUE TITLE
Custom widgets are not being added to the editor or UI

### ISSUE THREAD

**Issue by chambleton** [surveyjs/surveyjs#944]
### Are you requesting a feature, reporting a bug or ask a question?

Asking a question (and possibly reporting a bug).

### What is the current behavior?

I'm trying to add a widget similar to bar-rating in my local project; I've even made a copy of the bar-rating class and that's not being added either. They are being initialized and added to the CustomWidgetCollection, but not displayed.

### What is the expected behavior?

That the custom widgets are added to the editor and UI after being added to the CustomWidgetCollection.

### How would you reproduce the current behavior (if this is a bug)?

I have a sample of the issue that can be modified/forked to resolve the issue: https://stackblitz.com/edit/react-surveyjs-constantsum

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:  https://stackblitz.com/edit/react-surveyjs-constantsum

Test code

```
https://stackblitz.com/edit/react-surveyjs-constantsum
(see "StarRating.js" and "ConstantSum.js"

```

### Specify your

* browser: Chrome and IE
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.0.9

**Comment by tsv2013** [comment]
Have you checked this repo - https://github.com/surveyjs/surveyjs_react_quickstart?
The bar-rating custom widget is demonstrated there in the survey and in the editor.
Does this repo work for you?

**Comment by tsv2013** [comment]
I've checked your sample - it looks like you don't pass `$` to the widgets during initialization:

```JS
    Widgets.jquerybarrating(SurveyKo, $);    /// $ !!!!
    Widgets.jquerybarrating(Survey, $);

    Widgets.sortablejs(SurveyKo, $);    
    Widgets.sortablejs(Survey, $);

    Widgets.nouislider(SurveyKo, $);    
    Widgets.nouislider(Survey, $);

    MyWidgets.constantsum(SurveyKo, $);    
    MyWidgets.constantsum(Survey, $);

    MyWidgets.starrating(SurveyKo, $);    
    MyWidgets.starrating(Survey, $);
```

**Comment by chambleton** [comment]
hi - I updated the sample with your suggestion but it made no impact. Also, the other custom widgets are working properly, but not the ones from "MyWidgets"...

**Comment by chambleton** [comment]
Per your earlier question (trying the surveyjs_react_quickstart example), that's what I've based my example off of (which is working except for my custom widgets).

**Comment by chambleton** [comment]
Hi - is there any update on this issue? Is their a section of the code I can look at to figure out why these widgets aren't loading? thanks!

**Comment by dmitrykurmanov** [comment]
Hello! Sorry for the late rsponse. I've checked your example. I suggest that the problem in this code : 
```
    widgetIsLoaded: function() {
      return !!$.fn.constantsum; // problems here 
    },
```
Is "constantsum" a jquery plugin? Please check the example: https://stackblitz.com/edit/react-surveyjs-constantsum-hcameq?file=ConstantSum.js

**Comment by tsv2013** [comment]
We've not found scripts with constantsum or starrating script in the https://stackblitz.com/edit/react-surveyjs-constantsum?file=index.html file. Dependencies section of the sandbox desn't contain them either.
This can be reason why your custom widgets haven't been loaded.

**Comment by chambleton** [comment]
Thank you for your response! I'll try including those and see if i can get it working...
