### ISSUE TITLE
Data change on Vue js 

### ISSUE THREAD

**Issue by bidos** [surveyjs/surveyjs#946]
### Are you requesting a feature, reporting a bug or ask a question?
Requesting a feature

### What is the current behavior?
There is no option to make one of the checkbox uncheck the others. I found a solution to make it work but it isn't adapted with VueJs and I can't find a way to solve it. (Vue.js is not supporting data change into the onValueChanged event listener)

### What is the expected behavior?
The following solution works in jQuery : https://plnkr.co/edit/H1YjYH?p=preview
However, when using VueJs, it is not working. See the following example : https://plnkr.co/edit/WTQIT3M5DAONNCsDqKhA?p=preview

#### Provide the test code and the tested page URL (if applicable)
VueJS : https://plnkr.co/edit/WTQIT3M5DAONNCsDqKhA?p=preview
jQuery : https://plnkr.co/edit/H1YjYH?p=preview

Test code

```
your_code_here

```

### Specify your

* browser: all
* browser version: all
* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version: 1.0.8

**Comment by kaphert** [comment]
It is a bug, the culprit are these lines:

https://github.com/surveyjs/surveyjs/blob/c2ad3c2cac79a6380d9cd7549228321c5637a0da/src/vue/checkbox.vue#L23-L32

I think this could just be removed and the `v-model` could be set to `question.value`. 
@tsv2013 what do you think? Is there any use case for storing the initial value as `innerValue`?

**Comment by tsv2013** [comment]
Good shot, @kaphert :-) The `question.value` is a proxy to a hash with survey data. The hash is initially empty. That's why VueJS doesn't observes this values and thus doesn't track changes. The `innerValue` initially is `null`. This makes VueJS track changes of it: UI updating is being done then `innerValue` has been changed.
We need some time to investigate it.

**Comment by dmitrykurmanov** [comment]
We've fixed the problem. Fix will be available in the next patch release.
