### ISSUE TITLE
Issue when adding more than 3 question choices (responses)

### ISSUE THREAD

**Issue by healkar01** [surveyjs/surveyjs#947]
When filling out the possible answers to a survey question, when I click 'add new', the Value field doesn't update. So the 1st three Value fields will have item1, item2, item3. I'll add another line, and the Value field will be blank, when it should say item4. 

See attachment for screenshot. Thank you!
![survey value field issue](https://user-images.githubusercontent.com/20865786/36482307-de80c810-16e0-11e8-83f0-88287e7ff66a.jpg)

**Comment by tsv2013** [comment]
This should be created in this repo - https://github.com/surveyjs/editor

I've moved this isuue to the https://github.com/surveyjs/editor/issues/276
And closed this as duplicate.
