### ISSUE TITLE
Fail to clear error message on screen after disabling a question

### ISSUE THREAD

**Issue by ammonlee01** [surveyjs/surveyjs#950]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
- enable a question
- trigger some error (e.g. isRequired)
- run validation and display the error message with the question
- now disable the question
- run validation again, surveyjs reports no error but the error message still appears with the disabled question

### What is the expected behavior?
Since survey.js never validates a read-only question, it should always remove all errors from it once it is being disabled.

### How would you reproduce the current behavior (if this is a bug)?
See my description in the current behavior

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version: 64
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.0.7

**Comment by ammonlee01** [comment]
You may refer to onVisibleChanged in questionbase.ts to modify onReadOnlyChanged under question.ts.

  question.ts
  onReadOnlyChanged() {
    this.setPropertyValue("isReadOnly", this.isReadOnly);
  }

  questionbase.ts  
  protected onVisibleChanged() {
    this.setPropertyValue("isVisible", this.isVisible);
    if (!this.isVisible && this.errors && this.errors.length > 0) {
      this.errors = [];
      this.fireCallback(this.errorsChangedCallback);
    }
  }

**Comment by andrewtelnov** [comment]
@ammonlee01 The unit test is added and fixed.

Thank you,
Andrew
