### ISSUE TITLE
Setting width on an radio button

### ISSUE THREAD

**Issue by Braunson** [surveyjs/surveyjs#953]
### Are you requesting a feature, reporting a bug or ask a question?

- Feature

### What is the current behavior?

- Auto sets inline the width of an element.

### What is the expected behavior?

- Should have the option to override this or turn it off

### How would you reproduce the current behavior (if this is a bug)?

Create any survey question elements, inspect source

--

An example of this is shown here https://goo.gl/KKH2Vz (notice the `width: 100%`) - you can set the `Question` `renderWidth` but not the inline width that is applied to the container for the element, in this case a `radiogroup` set of buttons.

I'd like to remove this or change it but haven't had luck locating how to. The docs under Radiogroup reference `renderWidth` and `width` properties but they are Implemented in the `QuestionBase` and are specific to the question and not the radiogroup elements.

I can't even add a class to that `class="radio"` container div. I can target `.radio` within my surveyContainer but it would be nice to be able to add classes

**Comment by andrewtelnov** [comment]
@Braunson Could you use css similar to [this example](https://plnkr.co/edit/2Agug0prsUtECbZlgZnj?p=preview)
Or do you need a specific css class for input type="radio"?
We can add it.

Thank you,
Andrew

**Comment by Braunson** [comment]
@andrewtelnov Yep I'm already using that but it would be nice to be able to add css classes to elements and their containers too :)

**Comment by tsv2013** [comment]
@Braunson Probably SurveyJS has this already. Could you check this example -  https://plnkr.co/edit/HV0mEh?p=preview
You can override the following class names for radiogroup:
```JS
  radiogroup: {
    root: "sv_qcbc",
    item: "sv_q_radiogroup",
    label: "sv_q_radiogroup_label",
    itemControl: "sv_q_radiogroup_control_item",
    controlLabel: "",
    other: "sv_q_other sv_q_radiogroup_other"
  },
```
For mode detail you can check the https://github.com/surveyjs/surveyjs/blob/master/src/defaultCss/cssstandard.ts file.
