### ISSUE TITLE
How to dynamically add a new page and repeat set of questions based on number of paneldynamic items in a previous page?

### ISSUE THREAD

**Issue by testweird123** [surveyjs/surveyjs#954]
### Are you requesting a feature, reporting a bug or ask a question?
Question.
I need to add list of elements using pandeldynamic on one page. On clicking next, a set of questions should be repeated for those list of elements on the next page.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version:  64.0.3282.119
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.10

**Comment by ajien** [comment]
I am also interested in knowing how this can be implemented.

**Comment by andrewtelnov** [comment]
Please read the [following article](https://hackernoon.com/surveyjs-an-open-source-javascript-survey-library-with-versions-for-angular-2-react-vue-2086d988b974)
The paragraph “Dynamic Panel: Dealing with List Data”.

Thank you,
Andrew

**Comment by ajien** [comment]
Thank you very much! I will check it out.

**Comment by testweird123** [comment]
Thank you!!! I did not expect it to be this simple. I could not find it in the docs or examples on https://surveyjs.io/Overview/Library . Maybe I didn't look hard enough. Thanks for this excellent library and quick response!!!
