### ISSUE TITLE
Untoggling other choices (in a checkbox) if a specific choice is selected?

### ISSUE THREAD

**Issue by ericnograles** [surveyjs/surveyjs#955]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### Details

Hi all,

I just had a quick question regarding the `checkbox` type. We're looking for functionality in which a choice untoggles other choices.

Best example is on the SurveyJS website: https://surveyjs.io/Examples/Library/?id=custom-widget-pretty-checkbox&platform=jQuery&theme=default

I'd expect that, if I checked off "None", it'd clear out the other checkboxes (it doesn't do so in the example above). I can probably sling this with some custom code on the Survey's `onValueChanged` event, but I wanted to ask if there was already an existing solution for this (either natively in SurveyJS or some recipe) before I started hacking away?

It'd be kinda cool if we had a `clearsOtherChoices` property as part of choices that would de-select the other choices if toggled, e.g.

```javascript
let choices = [
  { value: 'item-1', text: 'Item 1' },
  { value: 'item-2', text: 'Item 2' },
  { value: 'item-3', text: 'Item 3' },
  { value: 'none', text: 'None', clearsOtherChoices: true }
];
```

Thanks for your help!

**Comment by kaphert** [comment]
It could be done with a custom listener see the example code in: #946 I think the code could be cleared up a little bit but it will give you an idea. That issue is created because this ain't working as expected in Vue at this moment. So if you are using something else than Vue it should work. 

You could turn it into a custom widget so you can easily reuse it.

**Comment by andrewtelnov** [comment]
@ericnograles Here is the example of what you are tyring to build: https://plnkr.co/edit/x7jhti?p=preview

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
fixed via https://github.com/surveyjs/surveyjs/commit/1240a27ebb532ff62994027899b53d3e069c93da

**Comment by ericnograles** [comment]
Thanks for the help, @andrewtelnov, that snippet works perfectly!
