### ISSUE TITLE
add properties to the quiz result

### ISSUE THREAD

**Issue by dav2491** [surveyjs/surveyjs#960]
### Are you requesting a feature, reporting a bug or ask a question?

hello I would like to know if there is the possibility of adding a property to a question, like an id and if it is possible to return it to the final result of the quiz

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@dav2491 Here is [an example of adding a property](https://surveyjs.io/Examples/Builder/?id=addproperties)
And here is [the example](https://surveyjs.answerdesk.io/internal/ticket/details/T465) on modifing the JSON result.

Thank you,
Andrew

**Comment by dav2491** [comment]
Thanks for the info, but I can not find any more information besides the name in the final json.
My code is as follows:

` builder js

var editorOptions = {};
var editor = new SurveyEditor.SurveyEditor("editorElement", editorOptions);

/* aggiunta di un un pulsante per salvare json da passare alla pagina quiz */
editor
    .toolbarItems
    .push({
        id: "custom-save",
        visible: true,
        title: "Save json",
        action: function(){
                    /* ottengo JSON dall'editor lo converto in stringa e salvo */
                    var json = editor.getSurveyJSON();
                    json = JSON.stringify(json)
                    localStorage.setItem("jsonbuilder",json);
                }
        },
        {
            id: "custom-redirect",
            visible: true,
            title: "Redirect Quiz",
            action: function(){
                        window.location.href="load.html";
            }
        });

Survey
  .JsonObject
    .metaData
    .addProperty("questionbase",{
        name: "score:number",
        default: 1
    });
      
SurveyEditor
  .SurveyQuestionEditorDefinition
  .definition["questionbase"]
  .properties = [
    "name",
    "title",{
      name: "score",
      title: "aagiungi peso"
    }
  ];

survey js

window.onload= function(){
    var json= localStorage.getItem("jsonbuilder");

    window.survey = new Survey.Model(json);
    
    survey
    .onComplete
    .add(function (result) {
        console.log(Object.keys(result.data));
        var modifiedData = Object.keys(result.data).map(function(qType) {
          return {
            questionYes: qType,
            answerNo: result.data[qType]
          }
        });
      
        document
            .querySelector('#surveyResult')
            .innerHTML = "result: " + JSON.stringify(modifiedData);
            
    });

    $("#surveyElement").Survey({model: survey});

};
`
I added a score property in the builder for each question. The json of the quiz then I transfer it to my page where I have to display the survey. At the end of the survey I would like to get a json that contains "name question: value, answer: value, weight: value.
Using the example you gave me I can only get the name of the question and not the value of the weight property I added.
How can I solve the problem?

**Comment by dmitrykurmanov** [comment]
hello!

- in the  _editor_ if you add a custom porperty with default value and don't change it, there is no this property in the JSON tab. Please see the example with the "score" property: https://plnkr.co/edit/DKSKMohxep7HY9OFkiuC?p=preview

-  in the _survey_  and `onComplete `you can get it. The example: https://plnkr.co/edit/U1UXHLBmdLYvU9wIx0LI?p=preview (I think that this code will help you `result.getQuestionByName(qName).score`)

Thank you.
