### ISSUE TITLE
Feature Request - Way to check if all values in matrix are the same (eg: all matrix questions are Yes vs No) 

### ISSUE THREAD

**Issue by cliewdevelop** [surveyjs/surveyjs#961]
Hello,

Given a matrix that has a lot of questions (20 or more)
is there a way to write an expression to check if all the rows have the same value?

Trying to avoid this:
`"visibleIf": "{question1.name}=0 and {question1.address}=0 and {question1.address}=0 ... on and on"`

something along the lines like
`
"visibleIf": "{question1.x} != 1"
`

I checked the documentation, doesn't seem like there's something like this.
Thank you + awesome platform!

**Comment by andrewtelnov** [comment]
@cliewdevelop Could you expalin your scenario in more details. If we see a bigger picture, we may give a better advice.
Normally, you may do what ever you want [onValueChanged event](https://surveyjs.io/Documentation/Library/?id=surveymodel#onValueChanged). 
Probably you need a [keyName property](https://surveyjs.io/Documentation/Library/?id=questionmatrixdynamicmodel#keyName) and you require a complex keyName property (several columns).

Thank you,
Andrew

**Comment by cliewdevelop** [comment]
The big picture is, we have a Matrix Question that has a lot of rows, with True/False
We only want to show the next question/or page only if **all** the Matrix Questions are False.

Right now, the only way I see it is doing 
`{matrix.question1}=0 and {matrix.question2}=0 and {matrix.question3}=0 ... on and on`

**Comment by andrewtelnov** [comment]
@cliewdevelop Could you please clearify, are you talking about [this question](https://surveyjs.io/Examples/Library/?id=questiontype-matrix)?

Thank you,
Andrew

**Comment by cliewdevelop** [comment]
Hi Andrew,

Yes it is related to a Matrix question.

But its more for the next question that depends on the Matrix question's answer.

I have edited the plunker to show what I mean, the second question will only appear if everything is set to "Disagree"

https://plnkr.co/edit/Wy6m7hjQ49KSGbAntsJA?p=preview

To do this, this line was required
`
visibleIf: "{Quality.value1} = 0 and {Quality.value2} = 0 and {Quality.value3} = 0 and {Quality.value4} = 0"
`

But its really long, and if I have 20 values I don't want 20 and statements joined together. 

Hope this helps clarify things!

**Comment by andrewtelnov** [comment]
@cliewdevelop Got it. The best way to implement it is to use the custom function. Here is [the example](https://plnkr.co/edit/AM3Aq2fzXw5GFgcBYWs7?p=preview)

Thank you,
Andrew

**Comment by cliewdevelop** [comment]
Oh neat! Thanks @andrewtelnov 
Code in react for other's reference
```
  componentWillMount(){
    Survey.FunctionFactory.Instance.register("rowsWithValue", this.rowsWithValue);
  }
  rowsWithValue(params) {
    console.log('rowsWithValue got triggered');
    if (!params && params.length < 2) return false;
    var matrixValue = params[0];
    var value = params[1];
    var rowCount = 0;
    for(var key in matrixValue) {
      if(matrixValue[key] == value) rowCount++;
    }
    return rowCount;
  }
```

So its correct to assume that anything inside {something} will be resolved by the time its passed in as params. 

Thanks again.

**Comment by andrewtelnov** [comment]
@cliewdevelop If this code runs before creating the survey, then yes.

Thank you,
Andrew

**Comment by cliewdevelop** [comment]
Thank you Andrew, very helpful. 
Closing this as question answered.
