### ISSUE TITLE
Is there any way to persist the timer and the state of a quiz in case of a browser refresh?

### ISSUE THREAD

**Issue by maria-negrea** [surveyjs/surveyjs#962]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

In the case of a quiz with a timer set, if the user performs a browser refresh/ browser back, all his answers will be lost and the timer will be reset. This affects the accuracy of a quiz, this way, the user has the option to search for the correct answers.

### Specify your

* browser: Google Chrome
* browser version: 64.0.3282.186
* surveyjs platform 1.0.11
* surveyjs version: 1.0.11

**Comment by andrewtelnov** [comment]
@maria-negrea You may store the survey results, the current page and timeSpent property, for example in local storage on another timer, like for every 5 seconds. 
When the user resume the survey/quiz you may check if there is data in local storage and set them back.

Here is [the example](https://surveyjs.io/Examples/Library/?id=real-patient-history#content-js) that may help you. Please take a look at the code on the end.

Let me know if you get the idea.

Thank you,
Andrew

**Comment by maria-negrea** [comment]
I've looked at the code in the example, implemented it and it worked. Thank you!
