### ISSUE TITLE
requiredErrorText for requiredInAllRowsError

### ISSUE THREAD

**Issue by artworkjpm** [surveyjs/surveyjs#970]
### Are you requesting a feature, reporting a bug or ask a question?
feature

### What is the current behavior?
unable to change default text of requiredInAllRowsError string

### What is the expected behavior?
requiredInAllRowsError always shows "Please answer questions in all rows." but I am using a different languages in my survey

### How would you reproduce the current behavior (if this is a bug)?
create a matrix with isAllRowRequired true and isRequired true, then do not select answers and try to proceed to the next page

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version: chrome latest
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version:

**Comment by andrewtelnov** [comment]
@artworkjpm Could you please describe, what doesn't work exactly?
Here is [the example](https://plnkr.co/edit/OzZDoNYhUMWQbath2Fyj?p=preview). It works here.

Thank you,
Andrew

**Comment by artworkjpm** [comment]
Yes it does change the text for the Italian language on the error message, I cannot see the code you added to do this in the js file. Can you tell me how are you changing the language to Italian in the red error message saying "Completare tutte le righe"?

Saludos

John Moran

Tel: (+34) 695 966 706

________________________________

**Comment by andrewtelnov** [comment]
@artworkjpm all you have to do, is to change the survey locale to italian: `survey.locale = "it";`
Please note, if there is already an error shown in English and you are chaning the locale, the error will contine to show in English, you have to call `survey.isCurrentPageHasErrors();` function.
However, in most cases, you do not need to change the locale during the running the survey. The user have to choose the locale before the survey is started.
I hope it makes sense.

Thank you,
Andrew

**Comment by artworkjpm** [comment]
yes I see now, thanks!
