### ISSUE TITLE
MatrixDynamic maxRowCount not changing if decreasing

### ISSUE THREAD

**Issue by snay** [surveyjs/surveyjs#973]
### Are you requesting a feature, reporting a bug or ask a question?
bug

### What is the current behavior?
When decreasing maxRowCount on MatrixDynamic, property on MatrixDynamic did not change.
If increasing the value it's ok.

### What is the expected behavior?
maxRowCount property always set to provided value

### How would you reproduce the current behavior (if this is a bug)?
Set value of rowCount/minRowCount/maxRowCount from the text field.
Input 3, set the properties rowCount/minRowCount/maxRowCount on matrixdynamic.
Input 1, set the properties rowCount/minRowCount/maxRowCount on matrixdynamic.

1 row displayed (rowCount), minRowCount is 1, but it's possible to add 2 more rows (maxRowCount still is 3).

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://plnkr.co/edit/SU3l9zVuNfAJ8hnOcqSn?p=preview

Test code

```
survey
    .onValueChanged
    .add(function (survey, options) {
    
    var numberRows = parseInt(options.value)
    if (numberRows) {
      var question = survey.getQuestionByName('teachersRate')
      question.rowCount = numberRows
      question.maxRowCount = numberRows
      question.minRowCount = numberRows
      
      console.log(question.maxRowCount)
    }
      
})

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
I think you can just change the order of rowCount assignment:

```JS
      question.minRowCount = numberRows
      question.maxRowCount = numberRows
```

It works ok for me - https://plnkr.co/edit/UuRjGG?p=preview

**Comment by snay** [comment]
I don't think so, the only thing that changed - now it's problem if increasing number of rows.
In your example, set 4 - all works as intended. Set 3 after - looks to be ok. Set 4 - minRowCount is 3 and it's possible to remove one row.
Any possible workarounds?

**Comment by tsv2013** [comment]
Yes, my bad
I've changed code a bit:
```JS
      if(question.rowCount > numberRows) {
        question.minRowCount = numberRows;
        question.maxRowCount = numberRows;
      } else {
        question.maxRowCount = numberRows;
        question.minRowCount = numberRows;
      }
      question.rowCount = numberRows;

```

And updated a sample -  https://plnkr.co/edit/UuRjGG?p=preview

Is it suitable for you?

**Comment by snay** [comment]
Tricky, but works for my case, thanks a lot.

**Comment by andrewtelnov** [comment]
@snay We have rewritten this. Now you can set question.maxRowCount/minRowCount without if statement. 
```
question.minRowCount = numberRows;
question.maxRowCount = numberRows;
```

Thank you,
Andrew
