### ISSUE TITLE
localization for Norwegian language

### ISSUE THREAD

**Issue by artworkjpm** [surveyjs/surveyjs#974]
### Are you requesting a feature, reporting a bug or ask a question?
feature

### What is the current behavior?
there is no Norwegian locale, I'm building a survey for Norwegian people and the translated error messages and page navigation. 

### What is the expected behavior?
currently defaulting to English

### How would you reproduce the current behavior (if this is a bug)?
change locale="no" and see it is missing in surveyjs/src/localization/ folder. 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@artworkjpm The localization is supported by community. Here is [the list](https://github.com/surveyjs/surveyjs/tree/master/src/localization) of all localized files we have.
Here is [the example](https://surveyjs.io/Examples/Library/?id=survey-localization) where you can see all languages for that we have localization in action.
Here is all [localizable strings](https://github.com/surveyjs/surveyjs/blob/master/src/surveyStrings.ts). 

Unfortunately, nobody did localization for Norwegian language. You may do it and share with the commnunity by making a pull request. In this case, we add your localization into the library and you will see it in the next minor update, commonly in a week.
You may just post here the tranlation into  Norwegian and we will do the rest.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@artworkjpm The norwegian localization will be included into the next update.

Thank you very much for sharing it with us and with the community!
Andrew

**Comment by artworkjpm** [comment]
any reason why the Norwegian is not updating? it uses the locale of no

**Comment by andrewtelnov** [comment]
@artworkjpm What do you mean? 
I go to https://surveyjs.io/Survey/Builder/ change survey.locale to norsk. I can see now "Choose..." becomes "Velg", "Next" button "Neste" and so on.

Thank you,
Andrew

**Comment by artworkjpm** [comment]
yes you are right, I forgot to update my call to the latest version https://surveyjs.azureedge.net/1.0.14/survey.jquery.min.js. Thanks for you help
