### ISSUE TITLE
Fileupload file names and storeDataAsText

### ISSUE THREAD

**Issue by nicklas669** [surveyjs/surveyjs#984]
Hi SurveyJS.

### Are you requesting a feature, reporting a bug or ask a question?
Question and/or feature

### What is the current behavior?
When I select file(s) using the 'file' element and post the form using storeDataAsText: true, the file(s) are saved as base64 encoding. Is there any way to get the name(s) of the uploaded file(s)?

Also, what can you do if you choose to not store the data as text? How are they saved then?

Thanks in advance,
Nicklas

**Comment by nicklas669** [comment]
Hey, it would also be nice if you could provide the filetypes of the uploaded files?

**Comment by andrewtelnov** [comment]
@nicklas669 Yes, adding a file Types property definitely makes sense.
About storeDataAsText = false, if you are storing survey results in our service, you do not need to do anything, we will upload the file on our backend.
You are storing results on your database, then you have to handle [onFileUpload event](https://surveyjs.io/Documentation/Library/?id=surveymodel#onUploadFile)

Thank you,
Andrew

**Comment by tsv2013** [comment]
This issue is related to the #972 - Support base64 file import

**Comment by nicklas669** [comment]
Hello @andrewtelnov or @tsv2013 . Are there any news on this matter? It would be nice if the filename and type was included in the data stored in text? Or must I handle the onFileUpload event completely? If so, can you look at my follow up question from 12 March?

Thanks in advance!
Nicklas

**Comment by dmitrykurmanov** [comment]
Sorry for the late response. The feature in our TODO list. We are collecting requirements now. Please check the https://surveyjs.answerdesk.io/internal/ticket/details/T526 thread also.

**Comment by sam031026** [comment]
Hi, I cannot find an even on cancel file upload. How can I detect when use storeDataAsText = false and onFileUpload event that file was canceled by user?

Thanks! Alexander

**Comment by tsv2013** [comment]
@sam031026 What do you mean under "file was canceled by user"? SurveyJS library hasn't this functionality.

**Comment by sam031026** [comment]
Sorry I mean "Clean" button

**Comment by tsv2013** [comment]
We'll make an event for the `Clean` button. In case of `storeDataAsText = true` you needn't to handle it. In case of `storeDataAsText = false` you will need to delete a file in your server storage I guess.

**Comment by sam031026** [comment]
Would it be possible to added to next release? 
Заранее спасибо!

**Comment by tsv2013** [comment]
@sam031026 What do you think about usage of the [onValueChanged](https://surveyjs.io/Documentation/Library/?id=surveymodel#onValueChanged) event in order to clean files in the server storage?

**Comment by sam031026** [comment]
yes I just tried. It works for me we can detect question name.

Thanks a lot.

**Comment by sam031026** [comment]
I have another issue I cannot find a solution how show the "Clean" button when open the survey again after move to draft?

**Comment by tsv2013** [comment]
Implemented in 1.0.19
