### ISSUE TITLE
Question: showPrevButton = false to be set at Page level

### ISSUE THREAD

**Issue by cliewdevelop** [surveyjs/surveyjs#987]
Hello! 

Have a quick question on the "showPrevButton" property.
If I want to set it for some pages to be true, and for some pages to be false (instead of the entire survey), is it possible?

Checked the docs, but don't see "showPrevButton" as a setting for Page, only for the entire Survey.

Thanks!

**Comment by tsv2013** [comment]
Hello @cliewdevelop!

The "showPrevButton" is supported on the survey level only. You can implement custom navigation to override this behaviour. Here is the example - https://surveyjs.io/Examples/Library/?id=survey-customnavigation&platform=jQuery&theme=default

Thanks, Serge
SurveyJS Team

**Comment by cliewdevelop** [comment]
Thank you for the answer.
