### ISSUE TITLE
Missing German localization for add row and remove row

### ISSUE THREAD

**Issue by CodeSmolder** [surveyjs/surveyjs#988]
In the German translation

[surveyjs/src/localization/german.ts](url)

entries for add row and remove row are missing comparing to other languages.

The translation could be as follows:

  addRow: "Reihe hinzufügen",
  removeRow: "Löschen"

* surveyjs version: 1.0.13

**Comment by andrewtelnov** [comment]
@CodeSmolder Could you please review german.ts localization and add all missed strings by making a pull request?
The localization is supported by community.
Ich spreche einbischen Deutsch. aber es ist besser, wenn ein Muttersprachler die Übersetzung macht :-)

Danke,
Andrew

**Comment by andrewtelnov** [comment]
@CodeSmolder 
Thank you for [supporting the project](https://github.com/surveyjs/surveyjs/pull/989)!
Andrew
