### ISSUE TITLE
onValidateQuestion  -- Possible to show validation error, but still proceed to next question?

### ISSUE THREAD

**Issue by asilverstein** [surveyjs/surveyjs#990]
### Are you requesting a feature, reporting a bug or ask a question?

Asking a question

###

Is it possible (perhaps using onValidateQuestion or some other way) to make validation work as it currently does, but still allow the user to proceed to the next question?

Basic need is, our customer wants a warning to be displayed, yet still allow the user to proceed to the next question, even if the user's answer is "incorrect"

Thanks!

**Comment by andrewtelnov** [comment]
@asilverstein You may create your own nativation: https://surveyjs.io/Examples/Library/?id=survey-customnavigation
You may add a button "Go Next in Anyway", and just the next page:
```
var index = survey.visiblePages.indexOf(survey.currentPage);
//go to the next page
if(index < survey.visiblePages.length - 1) {
survey.currentPage = survey.visiblePages[index + 1]
} else {
// last page. complete the survey
 survey.doComplete();
}
```
Thank you,
Andrew

**Comment by asilverstein** [comment]
Thanks Andrew, I'll give that a try. Much appreciated.

**Comment by asilverstein** [comment]
This works perfectly, thanks again Andrew!
