### ISSUE TITLE
Slide toggle for surevyjs question

### ISSUE THREAD

**Issue by ashygk** [surveyjs/surveyjs#992]
### Are you requesting a feature, reporting a bug or ask a question?

Question / requesting a feature

### What is the current behavior?

Can’t find slide toggle feature 

### What is the expected behavior?

I would want a slide toggle for yes/no or on/off scenarios

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome 
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version: 1.0.0

**Comment by tsv2013** [comment]
This can be achieved via css - https://www.w3schools.com/howto/howto_css_switch.asp
Here is the working sample - https://plnkr.co/edit/CJU6ia?p=preview

**Comment by tsv2013** [comment]
In case of you need rounded slider, just remove ".round" in the `/* Rounded sliders */` section of the CSS in the plunker
