### ISSUE TITLE
Dynamically initializate Tagbox widget in dynamic matrix  

### ISSUE THREAD

**Issue by KrzysiekHan** [surveyjs/surveyjs#993]
### Are you requesting a feature, reporting a bug or ask a question?
Ask a question

### What is the current behavior?
Hi guys,
I'm struggling for some time with Tagbox widget problem. I'm using dynamic matrix element as attached in plunker. Choices of tagbox depend on first dropdown. I'm loading choices into tagbox with  onMatrixCellValueChanged event. After submit i send data with ajax to database in raw JSON format. Till now everything is working just fine. 

When page is refreshed i want to load JSON data to retrieve the form state ( in plunker i simulate this with InitialData variable).Dropdowns states are ok, but tagboxes are empty...

### What is the expected behavior?
Tagbox should work like in Andrew example: https://plnkr.co/edit/KeSTSmO5fwo3FzLuwhcy?p=preview

I think tagboxes are empty becouse they don't have defined choices but i have no idea how to load those depending on JSON data. Which event should i use?
Thanks in advance 

#### Provide the test code and the tested page URL (if applicable)
https://plnkr.co/edit/t8P66xy67namhjpDGARv?p=preview

### Specify your
* browser: chrome,edge,firefox
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: Survey JavaScript library v1.0.10

**Comment by andrewtelnov** [comment]
@KrzysiekHan [onMatricCellCreated](https://surveyjs.io/Documentation/Library/?id=surveymodel#onMatrixCellCreated) is the event you need
You [updated example](https://plnkr.co/edit/u4khFUVtcPSfsCaHp9C3?p=preview)

Thank you,
Andrew

**Comment by KrzysiekHan** [comment]
Works perfect :) , thank You very much

**Comment by masciugo** [comment]
@andrewtelnov I tried the same **using react** but it seems that tagbox in matrixdynamic column [doesn't work.](https://plnkr.co/edit/5Q08f00LJ5L4yuW3I43t?p=preview). Is it a bug?

**Comment by andrewtelnov** [comment]
@masciugo You have not included select2 scripts, here is the [updated version](https://plnkr.co/edit/shuPEUUKoAHUs562QaiP?p=preview) of your plunker

Thank you,
Andrew

**Comment by masciugo** [comment]
Ok sorry. That was an unhappy an attempt to reproduce the problem I have in my app which actually is that [I cannot see and select the choices set in the model](https://plnkr.co/edit/yzWu5dLBzP5SC6fjY2HL?p=preview). Thanks Andrew

**Comment by andrewtelnov** [comment]
@masciugo You have missed the following code as well:
```
        //add tagbox into matrix columns
        Survey.matrixDropdownColumnTypes.tagbox = {
            properties: ["choices", "choicesOrder", "choicesByUrl", "otherText"],
            onCellQuestionUpdate: (cellQuestion, column, question, data) => {
                Survey.matrixDropdownColumnTypes.dropdown.onCellQuestionUpdate(cellQuestion, column, question, data);
            }
        };

```
It adds "tagbox" cell type
Here is [the update example](https://plnkr.co/edit/NQWgkrbP5pUVqhbEceT3?p=preview)

Thank you,
Andrew

**Comment by masciugo** [comment]
Ok thank you Andrew. To less bother you, if there is a place where this kind of customization are documented please tell me.

**Comment by andrewtelnov** [comment]
@masciugo We will add an example. The most information you may find [here](https://surveyjs.io/Examples/Library/)

Thank you,
Andrew
