### ISSUE TITLE
Custom validator bug

### ISSUE THREAD

**Issue by nicklas669** [surveyjs/surveyjs#994]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
I am making a custom validator and I experienced big problems with my validator not running properly. After a lot of debugging I finally found out that my problem was that my custom validator type had camelCase and not all lowercase.

### What is the expected behavior?
Custom validators should work even if the type is not in full lowercase.

### How would you reproduce the current behavior (if this is a bug)?
See this plunker for a version where my custom validator works: [https://plnkr.co/edit/i2mwxIAqGE9hjSf58Dv1](https://plnkr.co/edit/i2mwxIAqGE9hjSf58Dv1?p=preview) (notice in index.js that 'contactinfoclaimantvalidator' is in lowercase everywhere)

See this plunker for a version where my custom validator does NOT work: [https://plnkr.co/edit/W0YcnSeIT3MkXe53LLE7](https://plnkr.co/edit/W0YcnSeIT3MkXe53LLE7?p=preview) (notice that here the type is called 'contactInfoClaimantValidator')

Don't know if this is intended or if you want to fix it, but it was something that caused me to waste a few hours..

Kind regards,
Nicklas

**Comment by andrewtelnov** [comment]
@nicklas669 Reproduced the issue in the unit test and fixed it.
The fix will be available in the next minor version on the next week.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@nicklas669 Here is the [example of using EmailValidator](https://plnkr.co/edit/ZN49W5wBLRUOiIM0YBDG?p=preview) inside your validator.
You can show several errors, if you will have several validators. One validator may generate one error at one time.

Thank you,
Andrew
