### ISSUE TITLE
choicesByUrl binding does not fire unless dependent name is lowercase

### ISSUE THREAD

**Issue by erbaker** [surveyjs/surveyjs#997]
We have 2 dropdowns; one is populated by a static list, the second is retrieved from a URL based on selection from first dropdown. We noticed that the choicesByUrl does not fire if the "country" element is named "Country" with a capital C, only if it is lowercase. 

https://plnkr.co/edit/Ll2vfUP54T3ZRAqCY0Zi?p=preview

I would expect that the case does not matter for this binding.

* browser: chrome/firefox
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.14

**Comment by andrewtelnov** [comment]
@erbaker I reproduced the issue in a unit test and fixed it. The fix will be available in the next minor update, on the next week.

Thank you,
Andrew
