### ISSUE TITLE
Bug in Visible If + Visible + Panel combination?

### ISSUE THREAD

**Issue by Lynn42** [surveyjs/surveyjs#999]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug

### What is the current behavior?

When specifying a 'Visible if' and then moving to the JSON Editor tab, somehow automatically the 'Visible' property is set to False. In my eyes this is not needed, as this is a seperate property and the Visible if property works well on its own (but I could be wrong). It has no effect on functionality, except when you put the question that has the Visible if in a Panel, and the question it depends on (as specified by the Visible if) outside of that panel. Then, the fact that the Visible property automatically gets set to false results in the Visible If statement not working anymore.

See below for a more detailed walk-through.

### What is the expected behavior?

2 options:

1. The Visible property is not automatically set to False when moving to the JSON Editor tab as a result of the Visible If property being specified.

2. There needs to be a fix that the Visible if still works across panels, given that the Visible property gets automatically set to false. (The problem seems to be that the combination of Visible = false & panel structure results in the Visible If statement not working anymore).

I personally would opt for option 1, since it seems as an unnecessary dependency, but I might very well miss something there.

### How would you reproduce the current behavior (if this is a bug)?

1. Make a form with two questions in the SurveyDesigner part of the SurveyJS Editor
2. Make the second question (question2) dependent on the first (question1) by adding Visible if (i.e. {question1} contain 'Item1'). Leave the Visible property checked (Visible = True)
3. Confirm that the Visible If works by Testing the form.
4. Move to the JSON Editor and out of it to the Survey Designer
5. Confirm that for question2, next to the Visible If option, the Visible option is now set to false. You can of course also see this in the JSON Editor itself.
6. Confirm that the Visible If  still works by Testing the form.
7. Now add a panel and put question2 (that contains the specified visible if property) into that panel. Leave question 1 out.
8. Confirm that the Visible If  _no longer_ works by Testing the form.
9. Add question1 to the panel as well
10. Confirm that the Visible If  _now works again_ by Testing the form
11. Take question1 out of the panel again, but leave question2 in there. Manually set Visible=True for question2 in the SurveyDesigner and directly go to the Test tab. Confirm that now, with the panel, the Visible If _does_ work.
12. Go back and forth to the JSON Editor, see Visible being set to False automatically again, and confirm that now, the Visible if stopped working again.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/Survey/Builder/

**Comment by andrewtelnov** [comment]
@Lynn42 ok, I have added a unit test and fixed it. Survey do not run conditions (change visible/enable) at design mode, in Editor
It should work fine since the next minor update on the next week.

Thank you,
Andrew

**Comment by Lynn42** [comment]
Wow that was fast, thank you! 

For my understanding, do I understand correctly that you implemented the first solution? : The Visible property is not automatically set to False when moving to the JSON Editor tab as a result of the Visible If property being specified.

**Comment by andrewtelnov** [comment]
@Lynn42 Yes, you are right. But the bug is still here. I have to modify the Editor a little bit as well :)

**Comment by andrewtelnov** [comment]
@Lynn42 ok, it is fixed now :)
